### PR TITLE
 AK: Always initialize vector capacity to inline_capacity 

### PR DESCRIPTION
**Pull request by MacDue**
Previously constructors such as `Vector(std::initializer_list<T> list)` did not make use of the inline capacity so would always allocate, even if there was enough inline space.

### CODE REVIEW

**Review by AtkinsSJ — COMMENTED** [review]
Nice catch! I'm on my phone right now, but could we instead assign this in the field declaration to prevent it being forgotten again? eg,
```c++
size_t m_capacity { inline_capacity };
```

**Comment by MacDue** [comment]
Done, and I've also added a few tests to check inline storage is being used when vectors are constructed now,

**Comment by awesomekling** [comment]
Whoa, that's a sweet find!

**Comment by MacDue** [comment]
Only spotted it thanks to AK on compiler explorer!

**Review by GMTA — APPROVED** [review]

**Pull request merged**
