### PR TITLE
Base: Add Faux Pas and Silver themes

### PR DESCRIPTION
**Pull request by bugaevc**
They're... not perfect, especially Silver. But I guess it's a start, and someone who's better at making themes can improve them later.

image

image

### CODE REVIEW

**Comment by alimpfard** [comment]
That second one (I assume that's Faux Pas?) is much more pleasant than its name...

**Comment by bugaevc** [comment]
No, Faux Pas is the dark one 😐

**Comment by alimpfard** [comment]
> No, Faux Pas is the dark one 

Yeah, I realised...it looks pretty uncomfortable to me tbh :shrug:

**Comment by bugaevc** [comment]
I mean, these two themes are made to mimic the look of two certain 90s OSes, not for actually looking good.

**Comment by alimpfard** [comment]
Hm.
never seen any OS that looks like Faux Pas.

**Comment by bugaevc** [comment]
Well, either I'm especially bad at making themes (but no, I *think* Faux Pas turned out quite good), or perhaps you can use online search to find out what OS the code in the screenshot is written for :wink:

**Comment by awesomekling** [comment]
:)

**Pull request merged**
