### PR TITLE
LibGfx: Decrease flatness a little in Path::stroke_to_fill()

### PR DESCRIPTION
**Pull request by MacDue**
Noticed larger stroke widths were looking a little 'low poly', this looks a little nicer.

### CODE REVIEW

**Comment by MacDue** [comment]
Before (look at the bottom left):
image

After:
image

**Comment by awesomekling** [comment]
Looks like this breaks two LibWeb ref tests:
```
Fail: /home/vsts/work/1/s/Tests/LibWeb/Ref/svg-background-no-natural-size.html
Fail: /home/vsts/work/1/s/Tests/LibWeb/Ref/svg-textPath.html
```

**Comment by MacDue** [comment]
> Looks like this breaks two LibWeb ref tests:
> 
> ```
> Fail: /home/vsts/work/1/s/Tests/LibWeb/Ref/svg-background-no-natural-size.html
> Fail: /home/vsts/work/1/s/Tests/LibWeb/Ref/svg-textPath.html
> ```

Updated the tests :+1:

**Comment by MacDue** [comment]
```
Timeout: /Users/runner/work/1/s/Tests/LibWeb/Text/input/HTML/Window-postMessage.html
```
Seems unrelated.

**Pull request merged**
