### PR TITLE
Base: Add various Miscellaneous Symbols and Pictograms glyphs

### PR DESCRIPTION
**Pull request by sppmacd**
1f5c0,1f5c1,1f5cb,1f5cc,1f5cd,1f5ce,1f5cf,1f5e4,1f5e5,1f5e6,1f5e7,
1f5f6,1f5f7
image

### CODE REVIEW

**Review by Xexxa — CHANGES_REQUESTED** [review]
The glyphs looks great, only a minor alignment issue:
1F5E6 should be align to the right and 1F5E7 to the left according to the charts (https://www.unicode.org/charts/PDF/U1F300.pdf) and all fonts I've looked at.

image

_Edit: I really like the consistency in that 1F5F6, 1F5F7 has the same style as 1F5F4, 1F5F5. These small details takes the font to the next level!_

**Comment by awesomekling** [comment]
This has a conflict (and unaddressed review comments from Xexxa)

**Comment by sppmacd** [comment]
Fixed.
image
image

**Review by Xexxa — APPROVED** [review]
LGTM!

**Pull request merged**
