### PR TITLE
Base: Finish Latin Extended-B for Katica

### PR DESCRIPTION
**Pull request by electrikmilk**
Adds 0200-024F to Katica Regular 10 to complete the Latin Extended-B section.

Screen Shot 2022-02-06 at 17 35 23

### CODE REVIEW

**Review by bgianfo — CHANGES_REQUESTED** [review]
The prefix for font changes if you look at history is `Base:`

**Comment by bgianfo** [comment]
CC: @Xexxa

**Comment by Xexxa** [comment]
The font lgtm.

For the sake of future historians, commit message should include what codepoints you added (0200-024F) @electrikmilk.

Personally I also always try to be clear on what font I've been working on in commit & PR, like in this case "Katica Regular 10", but I will never* dig through git-history and have to ask @bgianfo if that's been a total waste of time or not?

**Comment by electrikmilk** [comment]
> The font lgtm.
> 
> For the sake of future historians, commit message should include what codepoints you added (0200-024F) @electrikmilk.
> 
> Personally I also always try to be clear on what font I've been working on in commit & PR, like in this case "Katica Regular 10", but I will never* dig through git-history and have to ask @bgianfo if that's been a total waste of time or not?

That's perfectly fair, out of practice doing commits.

**Comment by electrikmilk** [comment]
Amended commit to specify the specific changes.

**Comment by electrikmilk** [comment]
> The prefix for font changes if you look at history is `Base:`

👍

**Review by bgianfo — APPROVED** [review]

**Pull request merged**
