### PR TITLE
AK: Remove commented-out code from Bitmap container

### PR DESCRIPTION
**Pull request by supercomputer7**
How did it even get to be there?...

### CODE REVIEW

**Comment by trflynn89** [comment]
Can the comment below it be removed too? They were both added here:
https://github.com/SerenityOS/serenity/commit/b7e61180980ccb49916ae224fab8e73acc0482dd#diff-90b66747d436c5b03b836ceec5c584422205c04e7b7da1292f72ebe39f434df4R76

**Comment by supercomputer7** [comment]
> Can the comment below it be removed too? They were both added here: [b7e6118#diff-90b66747d436c5b03b836ceec5c584422205c04e7b7da1292f72ebe39f434df4R76](https://github.com/SerenityOS/serenity/commit/b7e61180980ccb49916ae224fab8e73acc0482dd#diff-90b66747d436c5b03b836ceec5c584422205c04e7b7da1292f72ebe39f434df4R76)

Sure :)

**Comment by ADKaster** [comment]
I think the origin of the comment was so that a casual code reader wouldn't think to add that API, because it's already a thing in the base class. @BenWiederhake  probably knows better about it 🙂.

**Comment by supercomputer7** [comment]
> I think the origin of the comment was so that a casual code reader wouldn't think to add that API, because it's already a thing in the base class. @BenWiederhake probably knows better about it slightly_smiling_face.

In that case, a comment near the ```[[nodiscard]] u8* data() { return m_data; }``` code could look like this:
```
Note: There's a const method variant of this method at the parent class BitmapView.
```
Seems like a much better approach than to do this the way it is now in my opinion.

**Comment by supercomputer7** [comment]
Done, I think it's more clear now that there's a const variant of the `data()` method in the parent class :)

**Review by trflynn89 — APPROVED** [review]

**Comment by BenWiederhake** [comment]
Yup, exactly :)

**Pull request merged**
