### PR TITLE
Ports: Add cbonsai port

### PR DESCRIPTION
**Pull request by tarob0ba**
This PR modifies the port list and adds the package.sh script for `cbonsai`, a delightful program that generates bonsai trees in your terminal.

### CODE REVIEW

**Comment by tarob0ba** [comment]
Fixing the table row, sorry. Next time, I'll remember to run the lint script.

**Comment by AtkinsSJ** [comment]
The `package.sh` script isn't marked as executable. I think you need to `chmod +x` it.

**Comment by AtkinsSJ** [comment]
After trying it out, I get crashes in `strtold()` when trying to provide any of the command-line arguments. :grimacing: It fails `assert(sizeof(double) == sizeof(long double));`

**Comment by tarob0ba** [comment]
Huh. The file was marked as executable, but Git marked it as 644 anyways. Just ran `git update-index --chmod=+x` and now it has registered.

**Comment by AtkinsSJ** [comment]
Looks like it still managed to not be executable. (https://github.com/SerenityOS/serenity/pull/19622) :thonk: Maybe something about your system is messing with it. Are you on Windows?

**Comment by tarob0ba** [comment]
Nope, I’m running Ubuntu. I ran `git ls-files -s package.sh` before updating the commit and it displayed 744 in the file perms. I have no idea what’s going on.

**Pull request merged**
