### PR TITLE
Base: Add a few emoji, update the heart emoji

### PR DESCRIPTION
**Pull request by CenTdemeern1**
Emoji included (updated list):
♟ - U+265F BLACK CHESS PAWN
❣ - U+2763 HEAVY HEART EXCLAMATION MARK ORNAMENT
❤ - U+2764 HEAVY BLACK HEART
🍜 - U+1F35C STEAMING BOWL
🎊 - U+1F38A CONFETTI BALL
🎟 - U+1F39F ADMISSION TICKETS
🐾 - U+1F43E PAW PRINTS
💓 - U+1F493 BEATING HEART
💔 - U+1F494 BROKEN HEART
💕 - U+1F495 TWO HEARTS
💖 - U+1F496 SPARKLING HEART
💗 - U+1F497 GROWING HEART
💘 - U+1F498 HEART WITH ARROW
💙 - U+1F499 BLUE HEART
💚 - U+1F49A GREEN HEART
💛 - U+1F49B YELLOW HEART
💜 - U+1F49C PURPLE HEART
💝 - U+1F49D HEART WITH RIBBON
📰 - U+1F4F0 NEWSPAPER
🖤 - U+1F5A4 BLACK HEART
🗑 - U+1F5D1 WASTEBASKET
🚎 - U+1F68E TROLLEYBUS
🤍 - U+1F90D WHITE HEART
🤎 - U+1F90E BROWN HEART
🧡 - U+1F9E1 ORANGE HEART
🧬 - U+1F9EC DNA DOUBLE HELIX

image

### CODE REVIEW

**Comment by djwisdom** [comment]
Unique style to say the least, with all those burst of colors, lgtm!

**Comment by CenTdemeern1** [comment]
> Unique style to say the least, with all those burst of colors, lgtm!

Thanks! :^)

**Comment by CenTdemeern1** [comment]
image
Updated hearts and trolleybus screenshot

**Comment by CenTdemeern1** [comment]
image
More screenshots

**Comment by CenTdemeern1** [comment]
> "Also ran OptiPNG on some emoji I forgot to run it on" -> edit the specifc commit that introduces the non-optimized emoji?

Rewrote history and resolved that!

**Review by Xexxa — APPROVED** [review]
LGTM

**Comment by sin-ack** [comment]
Please remove `[check desc.]` from the commit title.

**Comment by bgianfo** [comment]
> Please remove `[check desc.]` from the commit title.

Yes please!

Also, the commit message body to remove all the of separate individual descriptions. 
Please write the commit message as a comprehensive statement about the changes it includes.

**Comment by CenTdemeern1** [comment]
Okay, I'll remote into my computer real quick, give me a second...

**Comment by CenTdemeern1** [comment]
Sorry, as you can tell I am very new to this environment...

**Review by Xexxa — APPROVED** [review]
Looking good!

**Comment by CenTdemeern1** [comment]
Alright!

**Review by tarob0ba — APPROVED** [review]
Looks wonderful! 🧋

**Comment by bgianfo** [comment]
Thanks!

**Pull request merged**
