### PR TITLE
Meta: Remove version.txt for downloaded files, and version cache dirs

### PR DESCRIPTION
**Pull request by ADKaster**
@nico is this kind of what you were thinking for train-worthy bisecting?

One thing that I think is missing for this solution to work for that use case is that the old strategy would blast the entire subdirectory if the version mismatches... So perhaps we should download all the raw files/zips/tar.gz files to a caches/downloads/ folder or some such?

### CODE REVIEW

**Comment by trflynn89** [comment]
Fly-by opinion - I'd rather default to removing old versions when a new version is picked up. Optimizing for bad-train-internet bisecting isn't a strong argument IMO, we have the ability to turn off network downloads for that case. Or at least make it opt-in behavior to keep the old versions.

This also affects CI as we'll keep old versions in the actions cache in perpetuity.

**Comment by nico** [comment]
> Fly-by opinion - I'd rather default to removing old versions when a new version is picked up. 

Can you say more on why? The files in my Build/caches are all small (my Build/caches is 287 MB, while Build/x86_64 is 2.85 GB) and most of them change relatively rarely.

**Comment by nico** [comment]
We could delete the files when they're N weeks old or something.

Don't focus on the 'on a train' part too much – just bisecting across these is annoying, no?

**Comment by trflynn89** [comment]
I can only recall bisecting across an update once, but I didn't find it particularly annoying or really even noticeable. Certainly not enough to default to keeping the old downloads around or implement some other cache invalidation.

**Pull request closed without merging**
