### PR TITLE
Base: Update Syrian Flag emoji

### PR DESCRIPTION
**Pull request by DZve**
Syria just had a flag change, thought it should be updated. 

U+1F1F8_U+1F1FE

### CODE REVIEW

**Review by Xexxa — COMMENTED** [review]
From a technical pow it should be 10 px high and at most 10 px wide to follow the format of our other emoji. It should also be optimized.

I've sent a few lines to @timschumi about the political aspect of the change and is very happy I don't have to make any decision on this one.

**Comment by DZve** [comment]
Didn't mean to make this a political commit (I know flags are inherently political but I thought of it more from the fact that I just like flags.) I was unaware of the size constraint so if it's easier I can submit another pull request. In terms of optimization, the file is just an extra 21 bytes long (at least it should be. I submitted it through the github web interface, not the command line, so I don't know if github added some exif data.) But it should all be optimized.

**Comment by timschumi** [comment]
On the topic of the file size, it should be sufficient to run the file through `optipng` (`optipng -strip all Base/res/emoji/U+1F1F8_U+1F1FE.png`) to remove the 21 byte overhead that has been added while editing the file (most likely through unnecessary metadata).

Aside from the technical aspects, it seems that there is no clear consensus (yet) on whether the proposed flag is officially recognized and whether fonts should start updating the representation. For example, similar discussions are currently happening with [Google Noto](https://github.com/googlefonts/noto-emoji/issues/495) and [Twemoji](https://github.com/jdecked/twemoji/issues/119).

Please do note that Wikipedia is not a reliable primary source and that, despite increased usage especially in the last few weeks (even including various government institutions and being regarded as "de facto"), this does not automatically imply that the choice or design is final.

As [documented by Emojipedia for precedent](https://blog.emojipedia.org/what-about-the-afghanistan-flag-emoji/) and as [recommended by Unicode](https://blog.unicode.org/2022/03/the-past-and-future-of-flag-emoji.html) (relevant excerpt to follow), we will keep this PR open until the situation has become more clear.

> Once Unicode designates a codepoint for a flag, Unicode is not part of the process for how the final codepoints look.
>
> However, sometimes flags get redesigned and people have questions about what happens next. Whenever there is a change that requires an update to an existing flag emoji, the update can happen once a new design is officially recognized. For example, in 2023 when the [Martinique assembly voted for and adopted the official flag](https://www.martinique.franceantilles.fr/actualite/societe/le-drapeau-rouge-vert-noir-adopte-par-lassemblee-de-martinique-922149.php).
>
>The implementation of the new design takes some time and doesn’t happen immediately. Given the complexity of flag designs, artwork provided by an official representative is the safest way to ensure codepoints are accurately representing the country. Then, it can be deployed across various platforms.

**Comment by Xexxa** [comment]
> Didn't mean to make this a political commit (I know flags are inherently political but I thought of it more from the fact that I just like flags.) I was unaware of the size constraint so if it's easier I can submit another pull request. In terms of optimization, the file is just an extra 21 bytes long (at least it should be. I submitted it through the github web interface, not the command line, so I don't know if github added some exif data.) But it should all be optimized.

I had to skip adding North Korean provincial flags because the only official flags I could find was the South Korean ones for the northern provinces because they doesn't seem to recognize the north or something like that. I wanted to do it because I like flags but it was a bit to political for being added, iirc.

But you are not alone in liking flags, we do 168 Tag Sequence Flags, it's not RGI but it's allowed in Unicode so we do it: https://github.com/SerenityOS/serenity/blob/9a5d25ce1b4d3d74334b445911ca394c64b61745/Base/home/anon/Documents/emoji-serenity.txt#L84-L251

If you want to have fun with flags and don't mind it being more or less compatible with only Serenity you could add provincial flags for [Canada](https://en.wikipedia.org/wiki/List_of_Canadian_flags#Provincial) or [Brazil](https://simple.wikipedia.org/wiki/Flags_of_Brazilian_states) for example, you can find all the codes at [https://emojipedia.org/emoji-tag-sequence#list](https://emojipedia.org/emoji-tag-sequence#list)

**Comment by DZve** [comment]
That sounds fun! Should a pull request also add the emoji name and codepoints to the anon/Documents/emoji-serenity.txt file or just the emoji folder list?

**Comment by DZve** [comment]
Closed this PR on accident, don't believe I can reopen it since I deleted the original repository. See #25644 for current discussion.

**Pull request closed without merging**
