### PR TITLE
Everywhere: Use my new serenityos.org e-mail + add me to contributors

### PR DESCRIPTION
**Pull request by kleinesfilmroellchen**
:^)

### CODE REVIEW

**Comment by bgianfo** [comment]
Do you want to add your self to the .mailmap so all your commits look uniform in git?

**Review by linusg — CHANGES_REQUESTED** [review]
Not actually requesting changes, just need to add Xexxa to the list first (& then this will conflict, sorry about that!)

**Comment by kleinesfilmroellchen** [comment]
@linusg I just forgot to change my local git config, which I'll do now

**Comment by linusg** [comment]
Great! You'll indeed want to add yourself here then: https://github.com/SerenityOS/serenity/blob/master/.mailmap

**Comment by trflynn89** [comment]
FYI Andreas already added you to the contributor list :)

**Pull request merged**
