### PR TITLE
Meta: Make the gdb kernel debug script work for AArch64

### PR DESCRIPTION
**Pull request by IdanHo**
I've no clue how you've been bringing up the kernel without working GDB :slightly_smiling_face:

### CODE REVIEW

**Comment by nico** [comment]
It used to work back in the day when I did the very early bringup FWIW.

**Comment by IdanHo** [comment]
By "work" I mean having GDB recognize you're actually running the Kernel ELF (meaning it matches up assembly with source code, gives you local variable contents, etc)
I don't see how that can work with an incorrect base offset adjustment

**Review by FireFox317 — APPROVED** [review]
Looks good to me!

I definitely used gdb when working on the aarch64 port, but I just manually run the commands :shrug:

**Review by konradekk — APPROVED** [review]

**Comment by IdanHo** [comment]
> I definitely used gdb when working on the aarch64 port, but I just manually run the commands shrug

Ah, that works :slightly_smiling_face:

**Pull request merged**
