### PR TITLE
Base: Add new glyphs to font Tiny Regular

### PR DESCRIPTION
**Pull request by Xexxa**
Shavian (48 glyphs)
Symbols for legacy computing (194 glyphs)
Misc (latin, symbols, greek, arrows, dingbats, etc): ~300 glyphs
Braille patterns (128 glyphs)
Klingon (39 glyphs) F8D0–F8FF`*`
Braille Extended (61 glyphs) EB60-EB9F`*`
Aurebesh (49 glyphs) E890–E8DF`*`
`*` PUA based on Under-ConScript Unicode Registry

screenshotTiny6TLH

### CODE REVIEW

**Comment by awesomekling** [comment]
This seems of exceedingly low utility, but it also doesn't hurt anyone.

**Comment by Xexxa** [comment]
> This seems of exceedingly low utility, but it also doesn't hurt anyone.

I'm considering adding a 12 size version of the font (scaling a bitmap-font x2 feels like it should be easy to do automatically), would that have higher utility @awesomekling ?

screenshot-x2

**Comment by sin-ack** [comment]
I don't quite see the utility of having a font which is just the same tiny font but bigger. If the font isn't tiny, we can just use those extra pixels for more detail instead, like with Katica et al. :^)

**Comment by Xexxa** [comment]
> I don't quite see the utility of having a font which is just the same tiny font but bigger. If the font isn't tiny, we can just use those extra pixels for more detail instead, like with Katica et al. :^)

Good point! It would be more of a "pixel/retro" font in 12px then a tiny font. I'm actually very content with making 6x6 glyphs, I just wanted to see if I could make it more useful. Anyhow, I have some range gaps and adjustments left on Tiny, then it's time to move on to Katica(or something else more useful).

**Comment by awesomekling** [comment]
> > I don't quite see the utility of having a font which is just the same tiny font but bigger. If the font isn't tiny, we can just use those extra pixels for more detail instead, like with Katica et al. :^)
> 
> Good point! It would be more of a "pixel/retro" font in 12px then a tiny font. I'm actually very content with making 6x6 glyphs, I just wanted to see if I could make it more useful. Anyhow, I have some range gaps and adjustments left on Tiny, then it's time to move on to Katica(or something else more useful).

Right, the utility issue with a 6x6 font is that most people will never use or see it :)

**Pull request merged**
