### PR TITLE
Base: Add 31 new emoji + some adjustments

### PR DESCRIPTION
**Pull request by Xexxa**
screenshot6

⚓ - U+2693 ANCHOR
⛓️ - U+26D3 CHAINS
⛰️ - U+26F0 MOUNTAIN
⛱️ - U+26F1 UMBRELLA ON GROUND
🌋 - U+1F30B VOLCANO
🌵 - U+1F335 CACTUS
🍹 - U+1F379 TROPICAL DRINK
🎹 - U+1F3B9 MUSICAL KEYBOARD
🏔️ - U+1F3D4 SNOW-CAPPED MOUNTAIN
🐙 - U+1F419 OCTOPUS
💌 - U+1F48C LOVE LETTER
📷 - U+1F4F7 CAMERA
📸 - U+1F4F8 CAMERA WITH FLASH
📺 - U+1F4FA TELEVISION
📻 - U+1F4FB RADIO
🕳️ - U+1F573 HOLE
🕶️ - U+1F576 SUNGLASSES
🪀 - U+1FA80 YO-YO
🪢 - U+1FAA2 KNOT
🪤 - U+1FAA4 MOUSE TRAP
🛖 - U+1F6D6 HUT
🛠️ - U+1F6E0 HAMMER AND WRENCH
🇩🇯 - U+1F1E9 U+1F1EF DJ DJIBOUTI
🇨🇬 - U+1F1E8 U+1F1EC CG Congo - Brazzaville
🇪🇦 - U+1F1EA U+1F1E6 EA Ceuta & Melilla
🇪🇭 - U+1F1EA U+1F1ED EH Western Sahara
🇬🇫 - U+1F1EC U+1F1EB GF French Guiana
🇬🇬 - U+1F1EC U+1F1EC GG Guernsey
🇬🇹 - U+1F1EC U+1F1F9 GT Guatemala
🇯🇴 - U+1F1EF U+1F1F4 JO Jordan
🇳🇫 - U+1F1F3 U+1F1EB NF Norfolk Island

Adjust transparency for emoji U+1F1EA_U+1F1EC.png

Change codepoint for U+1F470.png -> U+1F47D.png

Coverage: https://emoji.serenityos.net/

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
Nice! Can we maybe add a bit more snow to `U+1F3D4.png`, and/or make it darker so it's visible on light backgrounds (I doubt we'll be able to fit an outline...)

**Review by linusg — COMMENTED** [review]
oh, and the commit message for `U+1F470.png` should probably also mention that you tweaked it :^)

**Comment by Xexxa** [comment]
> oh, and the commit message for U+1F470.png should probably also mention that you tweaked it :^)

Message re-phrased.

**Comment by Xexxa** [comment]
> Nice! Can we maybe add a bit more snow to `U+1F3D4.png`, and/or make it darker so it's visible on light backgrounds (I doubt we'll be able to fit an outline...)

Darker snow added to U+26F0.png & U+1F3D4.png.

**Pull request merged**
