### PR TITLE
LibSQL: Implement LIKE SQL expressions

### LINKED ISSUE #11447: SQLServer: Crash on SELECT <> LIKE 'txt%';
SQLServer crash on SELECT * FROM <table_name> where <column_name> LIKE 'txt%';

Reproduce:

Create a table (name: test) with a column id (int) and name (varchar(256)).

> SELECT * FROM test;
2, Jane Jones
1, Joe Doe
2 row(s)
> SELECT * FROM test WHERE name LIKE 'Joe%';

Result:

SQLServer crashes and cannot be restarted:

$ SQLServer
Error: Core::LocalServer: No file descriptor for socket takeover

### PR DESCRIPTION
**Pull request by eggpi**
Fixes #11447.

### CODE REVIEW

**Comment by eggpi** [comment]
Hmm, probably a newbie question but the [failure](https://github.com/SerenityOS/serenity/runs/4667399960?check_suite_focus=true#step:19:504) suggests that I need to link LibRegex _somewhere_, yet I'm not sure where. `TestSqlBtreeIndex` does build an run normally for i686 with `Meta/serenity.sh run`. Any pointers please?

**Comment by davidot** [comment]
> Hmm, probably a newbie question but the [failure](https://github.com/SerenityOS/serenity/runs/4667399960?check_suite_focus=true#step:19:504) suggests that I need to link LibRegex _somewhere_, yet I'm not sure where. `TestSqlBtreeIndex` does build an run normally for i686 with `Meta/serenity.sh run`. Any pointers please?

LibSQL is also being built by Lagom (which is used to use code outside of Serenity). So you probably need to add LibRegex to Meta/Lagom/CMakeLists.txt as well.

I suspect something like:
```diff
lagom_lib(SQL sql
    SOURCES ${LIBSQL_SOURCES}
+    LIBS LagomRegex
)
```
At around line 410

**Comment by eggpi** [comment]
Thanks, looks like that did the trick!

**Comment by alimpfard** [comment]
Let's get this in.
It looks alright to me

**Pull request merged**
