### PR TITLE
Meta: Replace remaining LibM/math.h includes with math.h and ensure it's not being used going forward

### PR DESCRIPTION
**Pull request by linusg**

### CODE REVIEW

**Comment by awesomekling** [comment]
Looks great, but let's allow Travis to chew on it :)

**Comment by linusg** [comment]
build broken for seemingly unrelated reasons :grimacing:

**Comment by awesomekling** [comment]
> build broken for seemingly unrelated reasons

Oops my bad :disappointed:

**Comment by linusg** [comment]
not to worry, all green now!

**Comment by BenWiederhake** [comment]
Fun fact: This broke the "heuristic" that tries to cache the toolchain. Finally I have very good reason to get rid of the heuristic, and write something that figures out the actual set of files used for libstdc++.a. ^^'

**Pull request merged**
