### PR TITLE
LibC: Increase atexit region size

### PR DESCRIPTION
**Pull request by cbyrneee**
This commit increases the ``atexit_region_size`` to ``4 * PAGE_SIZE``. This allows us to handle more global destructors, which previously weren't being called. We previously held 256 global destructors per page on 32-bit systems, this increases that to 1024 destructors.

**Notes:**
- This is related to (but doesn't exactly solve) #9094.

### CODE REVIEW

**Comment by awesomekling** [comment]
Can we at least `VERIFY()` that we didn't run out of space, to catch this sooner next time it happens?

**Comment by awesomekling** [comment]
Or wait, back up, what's the reason this storage can't grow dynamically?

**Comment by cbyrneee** [comment]
That would make a lot of sense, but there has to be *some* limit to this storage size, right?

**Comment by awesomekling** [comment]
> That would make a lot of sense, but there has to be _some_ limit to this storage size, right?

We could limit it, I suppose. But why though? If we have memory and the app wants to register more atexit handlers, why not let it?

**Comment by ADKaster** [comment]
I think the only reason it doesn't grow dynamically is because the initial implementation just had a static array, and the next round added the mprotect of the region. So at this point a growable list would be a bit tricky to implement and keep the "read only after init except when executing" behavior. Though you can register a new atexit handler whenever you want at runtime too.🤔

Reason is Technical, rather than architectural.

**Comment by awesomekling** [comment]
> I think the only reason it doesn't grow dynamically is because the initial implementation just had a static array, and the next round added the mprotect of the region. So at this point a growable list would be a bit tricky to implement and keep the "read only after init except when executing" behavior. Though you can register a new atexit handler whenever you want at runtime too.
> 
> Reason is Technical, rather than architectural.

Hmm, what's the difficulty here?
- Keep track of the size of the allocated memory region instead of hard-coding `PAGE_SIZE`
- When reallocating the memory region, transfer old contents to the larger region
- ???

**Comment by ADKaster** [comment]
Oh, that does sound simple doesn't it 😅. For some reason I was thinking it was necessary to not move the existing handlers and you'd have to create a linked list of single page regions or something.

**Comment by cbyrneee** [comment]
Makes sense now, I'll adjust it to be dynamic

**Pull request closed without merging**
