### PR TITLE
File Manager: "Open Terminal here" action

### PR DESCRIPTION
**Pull request by itamar8910**

### CODE REVIEW

**Comment by awesomekling** [comment]
Awesome idea! You've just made `FileManager` 10x better with two patches :D

**Comment by bugaevc** [comment]
Let's *not* add options for the current directories to programs. Unix has a way of passing a current directory to a program, which is... the current directory. In practice, it means you `cd`/`chdir` to the directory before or between fork/exec.

This is the same as adding `-i` and `-o` options to programs to specify input and output paths — we just use the Unix way of passing stdin/stdout/stderr files instead of an explicit argument.

**Comment by awesomekling** [comment]
> Let's _not_ add options for the current directories to programs. Unix has a way of passing a current directory to a program, which is... the current directory. In practice, it means you `cd`/`chdir` to the directory before or between fork/exec.
> 
> This is the same as adding `-i` and `-o` options to programs to specify input and output paths — we just use the Unix way of passing stdin/stdout/stderr files instead of an explicit argument.

Sure, that makes sense. For the "new terminal window" action, I guess we could `readlink()` the child process's `/proc/PID/cwd` and `chdir()` there after `fork()`.

**Comment by bugaevc** [comment]
You don't even have to `readlink()`, just `chdir("/proc/PID/cwd")` works (and in fact, it now works even in cases where the `readlink()` version wouldn't, see an example in https://github.com/SerenityOS/serenity/pull/1079). An alternative way of implementing this is the shell telling the terminal, with an escape sequence, about its current directory (I believe something like that is implemented already for the window title).

**Comment by itamar8910** [comment]
> Let's _not_ add options for the current directories to programs. Unix has a way of passing a current directory to a program, which is... the current directory. In practice, it means you `cd`/`chdir` to the directory before or between fork/exec.

Yes, this is definitely cleaner!
One thing though, it would require the Terminal service that's spawned by SystemServer to know the directory it should `chdir` to before `exec`ing.
Does adding a `WorkingDirectory` entry in `SystemServer.ini` sound reasonable?

**Comment by bugaevc** [comment]
> Does adding a `WorkingDirectory` entry in `SystemServer.ini` sound reasonable?

Sure — stuff that SystemServer can customize between it `fork`s and `exec`s a service is exactly what should be configurable in the config file. It's just that config options are mostly added on as-needed basis, and it sounds like we didn't need a specific WD for anything until now.

If you make a PR adding that, please CC me :slightly_smiling_face:

**Pull request merged**
