### PR TITLE
WindowServer/LibGUI: Enforce minimum window size

### LINKED ISSUE #1649: WindowServer: Enforce minimum window size in Window::set_rect
`Window::set_rect` should also enforce the same minimum window size that the window resizing code uses (50x50 pixels).

**Reproduction:**
Open an icon in QuickShow:
Screenshot_20200405_150324

### LINKED ISSUE #1843: WindowServer: ASSERTION FAILED: !rect.is_empty()
Creating a window with negative height or width causes a failed assertion in `WindowServer/Window.cpp`.

Related: #1649

Reproduce:

```cpp
#include <AK/StringBuilder.h>
#include <LibGUI/Action.h>
#include <LibGUI/Application.h>
#include <LibGUI/Event.h>
#include <LibGUI/Menu.h>
#include <LibGUI/Widget.h>
#include <LibGUI/Window.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#define WIDTH 100
#define HEIGHT 100

class TestWindowServer final : public GUI::Widget {
    C_OBJECT(TestWindowServer)
public:
    virtual ~TestWindowServer() override;

private:
    TestWindowServer();
    RefPtr<GUI::Menu> m_context_menu = GUI::Menu::construct();
};

TestWindowServer::TestWindowServer()
{
}

TestWindowServer::~TestWindowServer()
{
}

int main(int argc, char** argv)
{
    GUI::Application app(argc, argv);

    /* FIXED - empty context menu crash */
    /*
    RefPtr<GUI::Menu> m_context_menu = GUI::Menu::construct();
    Gfx::Point p {1,1};
    m_context_menu->popup(p);
    */

    auto window = GUI::Window::construct();
    window->set_double_buffering_enabled(true);
    window->set_title("TestWindowServer");
    window->set_resizable(true);
    int width = -100;
    int height = -100;
    window->set_rect(100, 100, width, height);
    window->show();

    //auto& test_window = window->set_main_widget<TestWindowServer>();

    return app.exec();
}
```

Log:

```
[Shell(22:22)]: do_exec(/bin/test_windowserver)
USERSPACE(11) ASSERTION FAILED: !rect.is_empty()
Window.cpp:101
[colonel(0:0)]: Terminating due to signal 6
[FinalizerTask(3:3)]: 0xdeadc0de  Kernel::Scheduler::switch_now() +62
0xdeadc0de  Kernel::Scheduler::yield() +86
0xdeadc0de  Kernel::Thread::yield_without_holding_big_lock() +36
0xdeadc0de  Kernel::Process::sys$kill(int, int) +400
0xdeadc0de  syscall_handler +1142
0xdeadc0de  syscall_asm_entry +29
0x0809e162  raise +22
0x08048320  abort +13
0x0809e0ea  kill +0
0x0805ce2d  WindowServer::Window::set_rect(Gfx::Rect const&) +51
0x0804a924  WindowServer::ClientConnection::handle(Messages::WindowServer::CreateWindow const&) +172
0x08050495  WindowServerEndpoint::handle(IPC::Message const&) +199
0x08054b5c  IPC::ClientConnection<WindowServerEndpoint>::drain_messages_from_client() +704
0x0807cc4e  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
0x0807778c  Core::EventLoop::pump(Core::EventLoop::WaitMode) +438
0x0807794d  Core::EventLoop::exec() +71
0x08048813  main +1047
0x08048c9f  _start +94

[FinalizerTask(3:3)]: Unblock SystemServer(4:4) due to signal
SystemServer(4): Core::safe_syscall: -1Taskbar( (4: Interrupted syscall)
ResourceGraph.MenuApplet(17): EOF on IPC fd
18): EOF on IPC fd
test_windowserver([Taskbar(18:18)]: 0xc01533d3  Kernel::Process::sys$exit(int) +31
[Taskbar(18:18)]: 0xc01668cd  syscall_handler +739
[Taskbar(18:18)]: 0xc0166525  syscall_asm_entry +29
[Taskbar(18:18)]: 0x080abe68  ResourceGraph.MenuApplet(Audio.MenuApplet(UserName.MenuApplet(16): EOF on IPC fd
exit +51
[Taskbar(18:18)]: 0x08055f97  IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::drain_messages_from_server() +179
[Taskbar(18:18)]: 0x0805ff0a  AK::OwnPtr<Messages::WindowServer::GetWindowRectResponse> IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::wait_for_specific_message<Messages::WindowServer::GetWindowRectResponse>() +356
[Taskbar(18:18)]: 0x0805cb4d  GUI::Window::rect() const +115
[Taskbar(18:18)]: 0x08058dc2  GUI::Widget::screen_relative_rect() const +40
[Taskbar(18:18)]: 0x08049c1a  TaskbarButton::resize_event(GUI::ResizeEvent&) +34
[Taskbar(18:18)]: 0x08059a99  GUI::Widget::handle_resize_event(GUI::ResizeEvent&) +19
[Taskbar(18:18)]: 0x080593ca  GUI::Widget::set_relative_rect(Gfx::Rect const&) +176
[Taskbar(18:18)]: 0x0804cc41  GUI::BoxLayout::run(GUI::Widget&) [clone .part.0] +649
[Taskbar(18:18)]: 0x08059a6c  GUI::Widget::do_layout() +106
[Taskbar(18:18)]: 0x0805cbe9  AK::Function<void (Core::Object&)>::CallableWrapper<GUI::Window::schedule_relayout()::{lambda(auto:1&)#1}>::call(Core::Object&) const +27
[Taskbar(18:18)]: 0x08088974  Core::EventLoop::pump(Core::EventLoop::WaitMode) +400
[Taskbar(18:18)]: 0x08088b5b  Core::EventLoop::exec() +71
[Taskbar(18:18)]: 0x0804bbbd  GUI::Application::exec() +37
[Taskbar(18:18)]: 0x0804847a  main +187
[Taskbar(18:18)]: 0x08048c1f  _start +94
[FinalizerTask(3:3)]: Unblock SystemServer(4:4) due to signal
SystemServer(4): Reaped child with pid 11
SystemServer(4): Core::safe_syscall: -1 (4: Interrupted syscall)
SystemServer(4): Service WindowServer has exited with exit code 6
SystemServer(4): Spawning WindowServer
22): EOF on IPC fd
[test_windowserver(22:22)]: 0xc01533d3  Kernel::Process::sys$exit(int) +31
[test_windowserver(22:22)]: 0xc01668cd  syscall_handler +739
[test_windowserver(22:22)]: 0xc0166525  syscall_asm_entry +29
[test_windowserver(22:22)]: 0x080aaae8  exit +51
[test_windowserver(22:22)]: 0x08052d7b  IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::drain_messages_from_server() +179
[test_windowserver(22:22)]: 0x0805e778  AK::OwnPtr<Messages::WindowServer::CreateWindowResponse> IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::wait_for_specific_message<Messages::WindowServer::CreateWindowResponse>() +356
[test_windowserver(22:22)]: 0x0805caf5  GUI::Window::show() +253
[test_windowserver(22:22)]: 0x08048587  main +456
[test_windowserver(22:22)]: 0x08048d9f  _start +94
9): EOF on IPC fd
Shell([Audio.MenuApplet(9:9)]: 0xc01533d3  Kernel::Process::sys$exit(int) +31
[Audio.MenuApplet(9:9)]: 0xc01668cd  syscall_handler +739
[Audio.MenuApplet(9:9)]: 0xc0166525  syscall_asm_entry +29
[Audio.MenuApplet(9:9)]: 0x080ae878  exit +51
[Audio.MenuApplet(9:9)]: 0x08056b8b  IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::drain_messages_from_server() +179
[Audio.MenuApplet(9:9)]: 0x08063282  AK::Function<void ()>::CallableWrapper<IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::ServerConnection(WindowClientEndpoint&, AK::StringView const&)::{lambda()#1}>::call() const +18
[Audio.MenuApplet(9:9)]: 0x080901da  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
[Audio.MenuApplet(9:9)]: 0x0808b3a2  Core::EventLoop::pump(Core::EventLoop::WaitMode) +438
[Audio.MenuApplet(9:9)]: 0x0808b563  Core::EventLoop::exec() +71
[Audio.MenuApplet(9:9)]: 0x0804d2c5  GUI::Application::exec() +37
[Audio.MenuApplet(9:9)]: 0x08048569  main +426
[Audio.MenuApplet(9:9)]: 0x08048cff  _start +94
[FinalizerTask(3:3)]: Unblock SystemServer(4:4) due to signal
SystemServer(4): Reaped child with pid 9
SystemServer(4): Core::safe_syscall: -1 (4: Interrupted syscall)
AudioServer(12): ASClientConnection{0x00d90316}: Client disconnected: 1
SystemServer(4): Service Audio.MenuApplet has exited with exit code 256
SystemServer(4): Spawning Audio.MenuApplet
SystemMenu(14): EOF on IPC fd
[SystemMenu(14:14)]: 0xc01533d3  Kernel::Process::sys$exit(int) +31
[SystemMenu(14:14)]: 0xc01668cd  syscall_handler +739
[SystemMenu(14:14)]: 0xc0166525  syscall_asm_entry +29
[SystemMenu(14:14)]: 0x080ada18  exit +51
[SystemMenu(14:14)]: 0x08053e15  IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::drain_messages_from_server() +179
[SystemMenu(14:14)]: 0x0806951e  AK::Function<void ()>::CallableWrapper<IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::ServerConnection(WindowClientEndpoint&, AK::StringView const&)::{lambda()#1}>::call() const +18
[SystemMenu(14:14)]: 0x0808f382  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
[SystemMenu(14:14)]: 0x0808a54a  Core::EventLoop::pump(Core::EventLoop::WaitMode) +438
[SystemMenu(14:14)]: 0x0808a70b  Core::EventLoop::exec() +71
[SystemMenu(14:14)]: 0x08057c6d  GUI::Application::exec() +37
[SystemMenu(14:14)]: 0x0804961b  main +4481
[SystemMenu(14:14)]: 0x08049edf  _start +94
[FinalizerTask(3:3)]: Unblock SystemServer(4:4) due to signal
SystemServer(4): Reaped child with pid 14
SystemServer(4): Core::safe_syscall: -1 (4: Interrupted syscall)
SystemServer(4): Service SystemMenu has exited with exit code 256
SystemServer(4): Spawning SystemMenu
21): Shell: test_windowserver:22 exited with status 1
Shell(21): Command "test_windowserver " finished in 815 ms
[UserName.MenuApplet(16:16)]: 0xc01533d3  Kernel::Process::sys$exit(int) +31
[UserName.MenuApplet(16:16)]: 0xc01668cd  syscall_handler +739
[UserName.MenuApplet(16:16)]: 0xc0166525  syscall_asm_entry +29
[UserName.MenuApplet(16:16)]: 0x080aac08  exit +51
[UserName.MenuApplet(16:16)]: 0x08052e99  IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::drain_messages_from_server() +179
[UserName.MenuApplet(16:16)]: 0x0805f5d8  AK::Function<void ()>::CallableWrapper<IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::ServerConnection(WindowClientEndpoint&, AK::StringView const&)::{lambda()#1}>::call() const +18
[UserName.MenuApplet(16:16)]: 0x0808c56a  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
[UserName.MenuApplet(16:16)]: 0x08087732  Core::EventLoop::pump(Core::EventLoop::WaitMode) +438
[UserName.MenuApplet(16:16)]: 0x080878f3  Core::EventLoop::exec() +71
[UserName.MenuApplet(16:16)]: 0x0804924f  GUI::Application::exec() +37
[UserName.MenuApplet(16:16)]: 0x0804856b  main +428
[UserName.MenuApplet(16:16)]: 0x08048d0f  _start +94
[FinalizerTask(3:3)]: Unblock SystemServer(4:4) due to signal
SystemServer(4): Reaped child with pid 16
SystemServer(4): Core::safe_syscall: -1 (4: Interrupted syscall)
SystemServer(4): Service UserName.MenuApplet has exited with exit code 256
SystemServer(4): Spawning UserName.MenuApplet
Clock.MenuApplet(13): EOF on IPC fd
[Clock.MenuApplet(13:13)]: 0xc01533d3  Kernel::Process::sys$exit(int) +31
[Clock.MenuApplet(13:13)]: 0xc01668cd  syscall_handler +739
[Clock.MenuApplet(13:13)]: 0xc0166525  syscall_asm_entry +29
[Clock.MenuApplet(13:13)]: 0x080aad68  exit +51
[Clock.MenuApplet(13:13)]: 0x08052ffb  IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::drain_messages_from_server() +179
[Clock.MenuApplet(13:13)]: 0x0805f73a  AK::Function<void ()>::CallableWrapper<IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::ServerConnection(WindowClientEndpoint&, AK::StringView const&)::{lambda()#1}>::call() const +18
[Clock.MenuApplet(13:13)]: 0x0808c6ca  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
[Clock.MenuApplet(13:13)]: 0x08087892  Core::EventLoop::pump(Core::EventLoop::WaitMode) +438
[Clock.MenuApplet(13:13)]: 0x08087a53  Core::EventLoop::exec() +71
[Clock.MenuApplet(13:13)]: 0x0804937f  GUI::Application::exec() +37
[Clock.MenuApplet(13:13)]: 0x08048561  main +418
[Clock.MenuApplet(13:13)]: 0x08048cff  _start +94
[SystemServer(23:23)]: do_exec(/bin/WindowServer)
[SystemServer(25:25)]: do_exec(/bin/SystemMenu)
WindowServer(23): Taking the socket over from SystemServer
[WindowServer(23:23)]: BXVGADevice resolution set to 1024x768 (pitch=4096)
[WindowServer(23:23)]: BXVGADevice: mmap with size 6291456 at V0x02742000
[SystemServer(24:24)]: do_exec(/bin/Audio.MenuApplet)
Terminal(8): EOF on IPC fd
[Terminal(8:8)]: 0xc01533d3  Kernel::Process::sys$exit(int) +31
[Terminal(8:8)]: 0xc01668cd  syscall_handler +739
[Terminal(8:8)]: 0xc0166525  syscall_asm_entry +29
[Terminal(8:8)]: 0x080b3c74  [FinalizerTask(3:3)]: Unblock SystemServer(4:4) due to signal
SystemServer(4): Reaped child with pid 13
SystemServer(4): Core::safe_syscall: -1 (4: Interrupted syscall)
SystemServer(4): Service Clock.MenuApplet has exited with exit code 256
SystemServer(4): Spawning Clock.MenuApplet
exit +51
[Terminal(8:8)]: 0x080586a5  IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::drain_messages_from_server() +179
[Terminal(8:8)]: 0x08069c34  AK::Function<void ()>::CallableWrapper<IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::ServerConnection(WindowClientEndpoint&, AK::StringView const&)::{lambda()#1}>::call() const +18
[Terminal(8:8)]: 0x080948bc  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
[Terminal(8:8)]: 0x0808f2c4  Core::EventLoop::pump(Core::EventLoop::WaitMode) +438
[Terminal(8:8)]: 0x0808f485  Core::EventLoop::exec() +71
[Terminal(8:8)]: 0x0804df4b  GUI::Application::exec() +37
[Terminal(8:8)]: 0x08049038  main +3193
[Terminal(8:8)]: 0x0804981f  _start +94
[FinalizerTask(3:3)]: /dev/pts/0: Send signal 1 to everyone in pgrp 21
[FinalizerTask(3:3)]: /dev/pts/0: Send signal 1 to Shell(21)
[FinalizerTask(3:3)]: Unblock SystemServer(4:4) due to signal
SystemServer(4): Reaped child with pid 8
SystemServer(4): Core::safe_syscall: -1 (4: Interrupted syscall)
SystemServer(4): Service Terminal has exited with exit code 256
[ResourceGraph.MenuApplet(17:17)]: 0xc01533d3  Kernel::Process::sys$exit(int) +31
[ResourceGraph.MenuApplet(17:17)]: 0xc01668cd  syscall_handler +739
[ResourceGraph.MenuApplet(17:17)]: 0xc0166525  syscall_asm_entry +29
[ResourceGraph.MenuApplet(17:17)]: 0x080ade22  [ResourceGraph.MenuApplet(17:17)]: Unblock Shell(21:21) due to signal
exit +51
[ResourceGraph.MenuApplet(17:17)]: 0x08053d07  IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::drain_messages_from_server() +179
[ResourceGraph.MenuApplet(17:17)]: 0x080601a2  AK::Function<void ()>::CallableWrapper<IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::ServerConnection(WindowClientEndpoint&, AK::StringView const&)::{lambda()#1}>::call() const +18
[ResourceGraph.MenuApplet(17:17)]: 0x0808de8a  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
[ResourceGraph.MenuApplet(17:17)]: 0x080890fe  Core::EventLoop::pump(Core::EventLoop::WaitMode) +438
[ResourceGraph.MenuApplet(17:17)]: 0x080892bf  Core::EventLoop::exec() +71
[ResourceGraph.MenuApplet(17:17)]: 0x0804a08b  GUI::Application::exec() +37
[ResourceGraph.MenuApplet(17:17)]: 0x080487e0  main +1057
[ResourceGraph.MenuApplet(17:17)]: 0x08048fcf  _start +94
10): EOF on IPC fd
[ResourceGraph.MenuApplet(10:10)]: 0xc01533d3  Kernel::Process::sys$exit(int) +31
[ResourceGraph.MenuApplet(10:10)]: 0xc01668cd  syscall_handler +739
[ResourceGraph.MenuApplet(10:10)]: 0xc0166525  syscall_asm_entry +29
[ResourceGraph.MenuApplet(10:10)]: 0x080ade22  exit +51
[ResourceGraph.MenuApplet(10:10)]: 0x08053d07  IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::drain_messages_from_server() +179
[ResourceGraph.MenuApplet(10:10)]: 0x080601a2  AK::Function<void ()>::CallableWrapper<IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::ServerConnection(WindowClientEndpoint&, AK::StringView const&)::{lambda()#1}>::call() const +18
[ResourceGraph.MenuApplet(10:10)]: 0x0808de8a  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
[ResourceGraph.MenuApplet(10:10)]: 0x080890fe  Core::EventLoop::pump(Core::EventLoop::WaitMode) +438
[ResourceGraph.MenuApplet(10:10)]: 0x080892bf  Core::EventLoop::exec() +71
[ResourceGraph.MenuApplet(10:10)]: 0x0804a08b  GUI::Application::exec() +37
[ResourceGraph.MenuApplet(10:10)]: 0x080487e0  main +1057
[ResourceGraph.MenuApplet(10:10)]: 0x08048fcf  _start +94
[SystemServer(27:27)]: do_exec(/bin/Clock.MenuApplet)
Entering WindowServer main loop.
Shell(21): Terminal DSR issue; received no response
[FinalizerTask(3:3)]: Unblock SystemServer(4:4) due to signal
SystemServer(4): Reaped child with pid 10
SystemServer(4): Core::safe_syscall: -1 (4: Interrupted syscall)
SystemServer(4): Service CPUGraph.MenuApplet has exited with exit code 256
SystemServer(4): Spawning CPUGraph.MenuApplet
[SystemServer(26:26)]: do_exec(/bin/UserName.MenuApplet)
[SystemServer(28:28)]: do_exec(/bin/ResourceGraph.MenuApplet)
[FinalizerTask(3:3)]: Scheduler: Reaped unparented process Shell(21), exit status: 0
[SyncTask(2:2)]: Ext2FS: Flushed 7 blocks to disk
```

### PR DESCRIPTION
**Pull request by linusg**
Fixes #1649
Fixes #1843

### CODE REVIEW

**Comment by awesomekling** [comment]
Let's enforce this on the server side instead, since the server is the authority on what the window rect is anyway :) In `ClientConnection::handle(const Messages::WindowServer::SetWindowRect& message)` (WindowServer/ClientConnection.cpp)

**Comment by linusg** [comment]
@awesomekling I tried - definitley don't merge this yet, it'd not done. Will rebase of course to update that commit message :)

It's not fully clear to me how we should do this - as you can see right now the rect normalization is duplicated in two places, not just the one you mentioned. and to make it fully work, I needed to add it in a third place, LibGUI:

```diff
diff --git a/Libraries/LibGUI/Window.cpp b/Libraries/LibGUI/Window.cpp
index b9bac6a43..b908d6f6e 100644
--- a/Libraries/LibGUI/Window.cpp
+++ b/Libraries/LibGUI/Window.cpp
@@ -161,7 +161,12 @@ Gfx::Rect Window::rect() const
 
 void Window::set_rect(const Gfx::Rect& a_rect)
 {
-    m_rect_when_windowless = a_rect;
+    Gfx::Rect normalized_rect = { a_rect.x(), a_rect.y(), max(a_rect.width(), 1), max(a_rect.height(), 1) };
+    if (m_window_type == WindowType::Normal) {
+        normalized_rect.set_width(max(a_rect.width(), 50));
+        normalized_rect.set_height(max(a_rect.height(), 50));
+    }
+    m_rect_when_windowless = normalized_rect;
     if (!is_visible()) {
         if (m_main_widget)
             m_main_widget->resize(m_rect_when_windowless.size());
```

otherwise the window content of a newly created window with size < 50x50 doesn't render properly until the window is resized.

need some guidance please. Can we somehow share this code across `WindowServer` and `LibGUI` or how do we solve it?

**Comment by awesomekling** [comment]
Ok so here's how we solve this:

Make the WindowServer respond to `SetWindowRect` with the final rect it decided on. You'll need to edit WindowServer.ipc and add a parameter in the response, something like
```
SetWindowRect(i32 window_id, Gfx::Rect rect) => (Gfx::Rect rect)
```

Once you have that, the rest of the code in LibGUI uses the rect from the response instead of the rect provided by the caller of `Window::set_rect()` :)

The response is available as the return value from `send_sync()`

**Comment by linusg** [comment]
maybe now... though the rendering issue mentioned above still exists.

image

after manual resize:

image

(this is Browser with a negative window size)

Maybe it's just fine as we at least now don't crash anymore?

I'm a bit clueless and want to go back to hacking on LibJS instead :smile:

**Comment by awesomekling** [comment]
This is fine as a first fix to get rid of the crashes. We can deal with the "missing update until first resize" issue separately.

**Comment by linusg** [comment]
merge conflicts are fixed :)

**Pull request merged**
