### PR TITLE
AK+LibCore: Add an IDAllocator and use to allocate timer ids

### PR DESCRIPTION
**Pull request by shannonbooth**
This (effectively) eliminates the possibility of an integer overflow on a timer id.

Also add a u64 type trait and hash function so they can be used in HashMaps.

### CODE REVIEW

**Comment by shannonbooth** [comment]
Just read the last commit, should I also change `s_next_client_id`?

**Comment by awesomekling** [comment]
If you’re gonna solve this please do it properly by making an ID allocator that tracks IDs in use and returns a known unused one. Bonus points if ID’s are randomized :)

**Comment by shannonbooth** [comment]
Sure thing :)

**Comment by shannonbooth** [comment]
@awesomekling Not sure if this is what you're after, but here's another go at it :P Doesn't feel right though...

**Comment by awesomekling** [comment]
That's basically what I had in mind yeah, thank you :)

**Pull request merged**
