### PR TITLE
Ports: Add Hatari Atari ST/STE/TT/Falcon emulator

### PR DESCRIPTION
**Pull request by danboid**

### CODE REVIEW

**Comment by thatdutchguy** [comment]
I'll try your version but I couldn't get the latest release (2.3.1) to build with the included package.sh.

Here's what worked for me to get it building with zlib and png support: [gist](https://gist.github.com/thatdutchguy/1b77bdb7337fe485d340d8b405c673fc)

Issues:
- Display output seems slightly squashed for some reason (see screenshots in gist).

I've been testing ST mode with TOS 1.04 and so far it's been fast and stable.

**Comment by danboid** [comment]
Indeed the cmake patch for this port won't work to build the latest stable release of Hatari as its slightly different.

There has been quite a number of improvements to Hatari since the latest release so I thought we'd go with that.

I'm not bothered about png support personally and would rather not install linpng for hatari but if you really want it I suppose we could add it in.

**Comment by aabajyan** [comment]
> I'll try your version but I couldn't get the latest release (2.3.1) to build with the included package.sh.

The latest release won't work because we worked on a git clone and the git clone is pretty different from the latest release.

> Here's what worked for me to get it building with zlib and png support: [gist](https://gist.github.com/thatdutchguy/1b77bdb7337fe485d340d8b405c673fc)
> 
> Issues:
> 
> * Display output seems slightly squashed for some reason (see screenshots in gist).
> 
> I've been testing ST mode with TOS 1.04 and so far it's been fast and stable.

Yeah, I also noticed that Issue but I didn't do any fixes for that. Maybe because the window is small or possibly a ttf issue?

**Comment by thatdutchguy** [comment]
The provided package.sh script does not seem to work for me at all. I don't really care about png support, but since there's already a libpng port I figured I'd add it in.

I'm all for building the newest version if we can get it to work!

**Comment by danboid** [comment]
> The provided package.sh script does not seem to work for me at all. I don't really care about png support, but since there's already a libpng port I figured I'd add it in.
> 
> I'm all for building the newest version if we can get it to work!

**Comment by danboid** [comment]
How did you build it of not with this port?

Which OS and shell are you using?

**Comment by thatdutchguy** [comment]
See this gist for the patch and package.sh I used: https://gist.github.com/thatdutchguy/1b77bdb7337fe485d340d8b405c673fc

The patch is needed because the _SC_CLK_TCK syscall is not available in SerenityOS.

I'm building in a VM dedicated to building SerenityOS running archlinux.
`package.sh` invokes bash, in my case version 5.1.4.

**Comment by danboid** [comment]
I see the problem now sorry!

**Comment by thatdutchguy** [comment]
> I see the problem now sorry!

No worries!

BTW, I managed to get the version referenced in your package.sh file by combining our package.sh scripts! Testing it now.

**Comment by danboid** [comment]
I've fixed the package.sh. It was broken by me trying to make it pretty. I've fixed the version number in the process.

**Comment by thatdutchguy** [comment]
- It still needs a patch for the _SC_CLK_TCK syscall which I don't see included in the PR.
- After I patch it the build fails because it can't find the math library:
```
[ 63%] Linking C executable hatari
/home/daniel/src/serenity/Toolchain/Local/i686/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: /home/daniel/src/serenity/Build/i686/Root/usr/lib/libSDL2.a(SDL_stdlib.c.obj): undefined reference to symbol 'atan2'
/home/daniel/src/serenity/Toolchain/Local/i686/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: /home/daniel/src/serenity/Build/i686/Root/usr/lib/libm.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/hatari.dir/build.make:1117: src/hatari] Error 1
make[1]: *** [CMakeFiles/Makefile2:398: src/CMakeFiles/hatari.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

It does build when I do the following two things:

- add this patch for the _SC_CLK_TCK call to `patches/hardcode-sc-clk-tck.patch`:
```
--- hatari-353379e1f8a847cc0e284541d2b40fd49d175d22/src/main.c	2021-03-12 13:36:10.000000000 -0800
+++ hatari-patched/src/main.c	2021-03-16 09:27:35.282509580 -0700
@@ -103,7 +103,7 @@
 	struct tms fields;
 	if (!ticks_to_msec)
 	{
-		ticks_to_msec = sysconf(_SC_CLK_TCK);
+		ticks_to_msec = 100; // WAS: sysconf(_SC_CLK_TCK);
 		Log_Printf(LOG_INFO, "OS clock ticks / second: %d\n", ticks_to_msec);
 		/* Linux has 100Hz virtual clock so no accuracy loss there */
 		ticks_to_msec = 1000UL / ticks_to_msec;
```
- update the configure() call in `package.sh` to:
```
configure() {
	run cmake $configopts -DCMAKE_EXE_LINKER_FLAGS="-lm -lpthread -lcore -lgfx -lgui"
}
```

Without all those linker flags it will fail to link in one way or another.

**Comment by thatdutchguy** [comment]
The squashed screen can be fixed by launching the emulator, pressing F12, clicking on "Hatari Screen" and then changing the "Max zoomed win" to 640x480.

**Comment by danboid** [comment]
"It still needs a patch for the _SC_CLK_TCK syscall which I don't see included in the PR."

Are you referring to trying to build the latest stable release? The current git based package.sh builds and links fine for me. Have you tried building using the current script @aabajyan ?

**Comment by danboid** [comment]
The linter has been failing because of an empty line at the end of the package.sh, now fixed.

**Comment by aabajyan** [comment]
> "It still needs a patch for the _SC_CLK_TCK syscall which I don't see included in the PR."
> 
> Are you referring to trying to build the latest stable release? The current git based package.sh builds and links fine for me. Have you tried building using the current script @aabajyan ?

sure lemme try!

**Pull request merged**
