### PR TITLE
LibVT+DevTools: Build spec-compliant ANSI escape sequence parser with a code generator 

### PR DESCRIPTION
**Pull request by BertalanD**
These commits add a generic code generator for state machines and a shiny new ANSI escape sequence parser that behaves similarly to other terminal emulators (based on https://vt100.net/emu/dec_ansi_parser) and has a nicer (?) API.

This PR is hopefully the first in the many that will fix bugs and add new features (how shocking?!) to LibVT.

Included changes:
- **new parser API**
- **prettier debug code** for unhandled escape sequences
- **defensive programming** so that Terminal won't crash as often.

The longer explanation below describes the code generator. If it is decided that it should stay a separate utility, we can use the explanation for its documentation.

This program turns a description of a state machine that takes its input byte-by-byte into C++ code. The state machine is described in a custom format as specified below:

```
// Comments are started by two slashes, and cause the rest of the line
// to be ignored

@name ExampleStateMachine // sets the name of the generated class
@namespace Test           // sets the namespace (optional)
@begin Begin              // sets the state the parser will start in

// The rest of the file contains one or more states and an optional
// @anywhere directive. Each of these is a curly bracket delimited set
// of state transitions. State transitions contain a selector, the
// literal "=>" and a (new_state, action) tuple. Examples:
//     0x0a => (Begin, PrintLine)
//     [0x00..0x1f] => (_, Warn)      // '_' means no change
//     [0x41..0x5a] => (BeginWord, _) // '_' means no action

// Rules common to all states. These take precedence over rules in the
// specific states.
@anywhere {
    0x0a         => (Begin, PrintLine)
    [0x00..0x1f] => (_, Warn)
}

Begin {
    [0x41..0x5a] => (Word, _)
    [0x61..0x7a] => (Word, _)
    // For missing values, the transition (_, _) is implied
}

Word {
    // The entry action is run when we transition to this state from a
    // *different* state. @anywhere can't have this
    @entry IncreaseWordCount
    0x09 => (Begin, _)
    0x20 => (Begin, _)

    // The exit action is run before we transition to any *other* state
    // from here. @anywhere can't have this
    @exit EndOfWord
}
```

The generated code consists of a single class which takes a `Function<Action, u8>` as a parameter in its constructor. This gets called whenever an action is to be done. This is because some input might not produce an action, butt others might produce up to 3 (exit, state transition, entry). The actions allow us to build a more advanced parser over the simple state machine.

The sole public method, `void advance(u8)`, handles the input byte-by-byte, managing the state changes and requesting the appropriate Action from the handler.

Internally, the state transitions are resolved via a lookup table. This is a bit wasteful for more complex state machines, therefore the generator is designed to be easily extendable with a switch-based resolver; only the private `lookup_state_transition` method needs to be re-implemented.

My goal for this tool is to use it for implementing a standard-compliant ANSI escape sequence parser for LibVT, as described on <https://vt100.net/emu/dec_ansi_parser>

### CODE REVIEW

**Comment by BertalanD** [comment]
Force-pushed a fix for the too long line in the commit message.

I already have most of the VT parser implemented. If this gets merged, I'd like to ask for help on how to make LibVT build with the parser state machine generated by this tool

**Comment by BertalanD** [comment]
Please excuse the inclusion of the generated code. I'd like to ask for help in implementing the necessary CMake functions to make the state machine build automatically.

**Comment by awesomekling** [comment]
We normally use `ReadonlyBytes` as an alias for `Span<u8 const>` (and `Bytes` for `Span<u8>`)

**Comment by BertalanD** [comment]
The inconsistent use of type aliases has been fixed. I would still like to keep our own `using`'s for `Parameters` and `OscParameters`, as it makes the API easier to read IMO.

This now builds fine, but it's hacky as I could not add `EscapeSequenceStateMachine.h` to LibVT's source list. If I add it, it complains about the file not existing, and if I also add the `generate_state_machine` command, the problem is that Ninja doesn't let the same file to be generated twice.

**Pull request merged**
