### PR TITLE
Fix non-configurable js attribute test

### PR DESCRIPTION
**Pull request by 4ourbit**
I think this needs an extra assert.

### CODE REVIEW

**Comment by linusg** [comment]
This feels a bit awkward imo - why not something like this instead?

```js
try {
    Object.defineProperty(o, "bar", { value: "xx", enumerable: false });
    assert(false);
} catch (e) {
    assert(e.name === "TypeError");
}
```

We could also add an alias for `assert(false)` like we have it in C++:

```js
const assertNotReached = () => assert(false);
```

and then do:

```js
try {
    Object.defineProperty(o, "bar", { value: "xx", enumerable: false });
    assertNotReached();
} catch (e) {
    assert(e.name === "TypeError");
}
```

**Comment by supercomputer7** [comment]
I suggest to change the commit title to be more like "Foo: Bar". Also, please avoid using the word "fix" in the commit message, as it is ambiguous what is the change that you applied in the commit :)

**Comment by 4ourbit** [comment]
Could you squash before merge?

**Comment by supercomputer7** [comment]
> Could you squash before merge?

I'd suggest to squash-rebase your commits by yourself :)

**Comment by awesomekling** [comment]
LibJS: Improve Object.defineProperty test

**Pull request merged**
