### PR TITLE
LibWeb: Add stub for IDBFactory.open

### PR DESCRIPTION
**Pull request by shannonbooth**
I saw that this not being implemented was causing a javascript exception
to be thrown when loading https://profiler.firefox.com/.

I was hoping that like the last time that partially implementing this
interface would allow the page to load further (ref for last time https://github.com/SerenityOS/serenity/pull/24294), but it seems that this
is unfortunately not the case this time!

However, this may help other pages load slightly further, and puts some
of the scaffolding in place for a proper implementation :^)

### CODE REVIEW

**Comment by awesomekling** [comment]
When adding new stubs, let's at least make them `dbgln()` when called :) (ref https://github.com/SerenityOS/serenity/issues/24168)

**Comment by shannonbooth** [comment]
> When adding new stubs, let's at least make them `dbgln()` when called :) (ref #24168)

Like this? https://github.com/SerenityOS/serenity/pull/24376/files#diff-d0f763a1c4375e2e74836ed37ac761c6e78beafd909bedc7ff3e1566dd55bb78R32

I think this is currently the only place which is stubbed and exposed through JS

**Comment by shannonbooth** [comment]
> > When adding new stubs, let's at least make them `dbgln()` when called :) (ref #24168)
> 
> Like this? https://github.com/SerenityOS/serenity/pull/24376/files#diff-d0f763a1c4375e2e74836ed37ac761c6e78beafd909bedc7ff3e1566dd55bb78R32
> 
> I think this is currently the only place which is stubbed and exposed through JS

Or do you want all of the IDL methods uncommented and dbgln / exception thrown?

**Comment by awesomekling** [comment]
Superseded by https://github.com/SerenityOS/serenity/pull/24377

**Pull request closed without merging**
