### PR TITLE
Kernel: Add RTL8169 support

### PR DESCRIPTION
**Pull request by supercomputer7**
This is a basic driver for the known RTL8169 network chipset, written and tested with the help of PCI-passthrough a card to Serenity's VM and testing it.

What works:
* ping
* IRC

What doesn't work:
* Using the browser under heavy load of interrupts

### CODE REVIEW

**Comment by supercomputer7** [comment]
@deoxxa If you can test this patch on your machine and report the results, it will be very appreciated! :)

**Comment by deoxxa** [comment]
@supercomputer7 can do!

**Comment by supercomputer7** [comment]
I tested this patch together with the ICH7 machine (and of course, with the card inserted into a PCI slot) and it seems to get stuck on initialization of the RTL8169, probably when doing the reset sequence.

**Comment by supercomputer7** [comment]
Seems like after applying #6277 (rebasing on it), and trying to boot the kernel - it works but I can't access anything outside my local network.

**Comment by supercomputer7** [comment]
I'll continue to work on this once I finish to work on #6277.

**Comment by supercomputer7** [comment]
Let's reopen this, as I have more time to tackle this important patch now :)

**Comment by supercomputer7** [comment]
Let's close this once again, next time I'll open this is when we have a working patch (and we're pretty close to it) :sweat_smile:

**Pull request closed without merging**
