### PR TITLE
Base+FontEditor: Add new icons already in use

### PR DESCRIPTION
**Pull request by BenWiederhake**
These should have been part of 7180813cd452d496f7f06543923b8a4e110e3d8d.

See also: #10972

Without these icons, FontEditor crashes on startup. Sorry :(

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
pls reword as "Base: Add new FontEditor icons already in use" - it doesn't actually touch FontEditor.

**Comment by BenWiederhake** [comment]
Done

**Comment by BenWiederhake** [comment]
I set it to draft because @Xexxa has other icons that look so much better.

**Comment by BenWiederhake** [comment]
Superceded by  #10976.

**Pull request closed without merging**
