### PR TITLE
 LibWeb+WebContent: Move scrollbar painting into WebContent

### PR DESCRIPTION
**Pull request by jamierocks**
See https://github.com/LadybirdBrowser/ladybird/pull/21 for details :^)

### CODE REVIEW

**Comment by kalenikaliaksandr** [comment]
Without making changes in SerenityOS Browser you will get duplicated scrollbar (one painted in WebContent and another in Browser) and probably some other issues.

**Comment by jamierocks** [comment]
Hmm, silly me. I'll work on this later / tomorrow :)

**Comment by nico** [comment]
This gets things at least to compile: [hack.patch](https://github.com/user-attachments/files/16117308/hack.patch)

It removes client-side scrollbars from Browser.

But the renderer-side scrollbars look supremely janky in serenity, even more so in non-browser apps that use a webview:

Screenshot 2024-07-03 at 11 04 26 PM

So we probably want to move scrollbar painting to a new LibTheming or something, and make both LibGUI and LibWeb use that to draw scrollbars.

Also, it comments out a few calls (to `set_scrollbars_enabled(false)` in Presenter which now always shows scrollbars; `scroll_to_top()` in Help; scroll position restoration for previews in TextEditor). Probably just needs some more plumbing, but it's something that needs doing.

Also also, `OutOfProcessWebView::to_content_position()` and `OutOfProcessWebView::to_widget_position()` are now identity functions, which is at best pretty sus.

**Comment by jamierocks** [comment]
Looks like we've both been working on this at the same time, although you've gone further than me.

https://gist.github.com/jamierocks/3607e73f472ec6efba0fce1030b8b5c8

image

**Comment by nico** [comment]
I gave it a short look last Thursday (that's when the diff is from). I'm not actively looking at this :)

**Comment by jamierocks** [comment]
>  it comments out a few calls (to set_scrollbars_enabled(false) in Presenter which now always shows scrollbars

I've added a FIXME for this, for now.

> scroll_to_top() in Help

This shouldn't be required anymore, it should reset when the new document loads.

> scroll position restoration for previews in TextEditor

I've added some FIXMEs for this, for now.

**Pull request merged**
