### PR TITLE
Everywhere: Rename JPG to JPEG

### PR DESCRIPTION
**Pull request by LucasChollet**
No functional changes intended.

### CODE REVIEW

**Comment by nico** [comment]
What about these:

```
% git ls-files '*.jpg' | wc -l
      12
% git ls-files '*.jpeg' | wc -l
       0
```

?

**Comment by LucasChollet** [comment]
Are you saying that because I said everywhere and it's not the case, or because you think we should not have `.jpg` files in the repo?

IMO, `.jpg` as a file extension is fine (and you can't fight it, it's widely accepted). My intention was to do the rename where we speak of the encoding.

**Comment by nico** [comment]
I don't have an opinion here, just pointing out that the current state is kinda self-consistent and the new one kinda isn't. (But that's probably fine.)

**Comment by linusg** [comment]
There's also a ton of `#define JPG_*` in `JPEGLoader`, what about those?

**Comment by LucasChollet** [comment]
We can't remove this one `__ENUMERATE_IMAGE_FORMAT(jpeg, ".jpg")`

And for these `#define` I considered that it wasn't very useful because it touches every line of this file, they already use abbreviations like `JPG_RST` and finally they are confined to the `.cpp` file.

I'm okay to do it if you really want though.

**Comment by linusg** [comment]
> I considered that it wasn't very useful because it touches every line of this file

Well, renaming stuff will touch files and code, sure.

> they already use abbreviations like `JPG_RST`

`JPEG` is still an abbreviation, except now it's inconsistent even within that file.

**Comment by LucasChollet** [comment]
Sure, let me commit that.

**Pull request merged**
