### PR TITLE
PixelPaint: Use a mutable lambda instead of const_cast in filters

### PR DESCRIPTION
**Pull request by Zaggy1024**

### CODE REVIEW

**Comment by BertalanD** [comment]
Can we not call non-const methods on `NonnullRefPtr<T> const`? That sounds like a bug, the dereference operator should mimic `T`'s constness, not the `NonnullRefPtr`'s.

**Comment by BertalanD** [comment]
#7059

**Comment by Zaggy1024** [comment]
Ah, I wondered about that but forgot to check before I pushed this drive-by. Thanks!

**Review by BertalanD — APPROVED** [review]
Thanks! I'll track fown when the bug was fixed to properly close the issue.

**Pull request merged**
