### PR TITLE
Documentation: Add Neovim configuration instructions

### PR DESCRIPTION
**Pull request by Matrix89**
As in the title, I've compiled those instructions by searching through other build instructions and discord and I want to make it easier for others :)

### CODE REVIEW

**Comment by MacDue** [comment]
How does this relate to: https://github.com/SerenityOS/serenity/pull/16670?

**Comment by Matrix89** [comment]
I didn't see that one. I think it's better for somebody not familiar with nvim configuration, mine assumes that the user has their own configuration, I think the other one should be merged, as it covers everything I've written about. Maybe just add the part about `.clangd`

@Vetrox FYI

**Comment by kleinesfilmroellchen** [comment]
@Matrix89 Can we close this PR then?

**Comment by Matrix89** [comment]
Yep, I'm closing it

**Pull request closed without merging**
