### PR TITLE
LibAudio+Meta: Pass the FLAC spec test suite

### LINKED ISSUE #14683: LibAudio/FlacLoader: Non-spec-compliant behavior found by the reference test suite
While we're waiting for the PR that allows you to run this test on master, here's a list of all FLAC loader crashes detected with the [reference test suite](https://github.com/ietf-wg-cellar/flac-test-files).

```
 76/132 Test  #76: TestFLACSpec .........................***Failed    4.41 sec
Running test 'flac_spec_test_07 - blocksize 725.flac'.
Completed test 'flac_spec_test_07 - blocksize 725.flac' in 49ms
Running test 'flac_spec_test_60 - mono audio.flac'.
Completed test 'flac_spec_test_60 - mono audio.flac' in 5ms
Running test 'flac_spec_test_01 - blocksize 4096.flac'.
Completed test 'flac_spec_test_01 - blocksize 4096.flac' in 45ms
Running test 'flac_spec_test_22 - 12 bit per sample.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sample bit depth invalid (at 42)
Failed test 'flac_spec_test_22 - 12 bit per sample.flac' in 0ms
Running test 'flac_spec_test_03 - blocksize 16.flac'.
Completed test 'flac_spec_test_03 - blocksize 16.flac' in 76ms
Running test 'flac_spec_test_20 - samplerate 39kHz.flac'.
Completed test 'flac_spec_test_20 - samplerate 39kHz.flac' in 33ms
Running test 'flac_spec_test_44 - 8-channel surround, 192kHz, 24 bit, using only 32nd order predictors.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_44 - 8-channel surround, 192kHz, 24 bit, using only 32nd order predictors.flac' in 0ms
Running test 'flac_spec_test_41 - 6 channels (5.1).flac'.
Completed test 'flac_spec_test_41 - 6 channels (5.1).flac' in 21ms
Running test 'flac_spec_test_43 - 8 channels (7.1).flac'.
Completed test 'flac_spec_test_43 - 8 channels (7.1).flac' in 30ms
Running test 'flac_spec_test_32 - high resolution audio, partition order 8 containing escaped partitions.flac'.
Completed test 'flac_spec_test_32 - high resolution audio, partition order 8 containing escaped partitions.flac' in 228ms
Running test 'flac_spec_test_48 - Extremely large SEEKTABLE.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Invalid metadata block (at 16777261)
Failed test 'flac_spec_test_48 - Extremely large SEEKTABLE.flac' in 247ms
Running test 'flac_spec_test_62 - predictor overflow check, 20-bit.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sample bit depth invalid (at 42)
Failed test 'flac_spec_test_62 - predictor overflow check, 20-bit.flac' in 0ms
Running test 'flac_spec_test_06 - blocksize 512.flac'.
Completed test 'flac_spec_test_06 - blocksize 512.flac' in 47ms
Running test 'flac_spec_test_38 - 3 channels (3.0).flac'.
Completed test 'flac_spec_test_38 - 3 channels (3.0).flac' in 8ms
Running test 'flac_spec_test_29 - high resolution audio, blocksize 16384.flac'.
Completed test 'flac_spec_test_29 - high resolution audio, blocksize 16384.flac' in 224ms
Running test 'flac_spec_test_50 - Extremely large PICTURE.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_50 - Extremely large PICTURE.flac' in 2ms
Running test 'flac_spec_test_56 - JPG PICTURE.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_56 - JPG PICTURE.flac' in 0ms
Running test 'flac_spec_test_16 - partition order 8 containing escaped partitions.flac'.
Completed test 'flac_spec_test_16 - partition order 8 containing escaped partitions.flac' in 40ms
Running test 'flac_spec_test_35 - samplerate 134560Hz.flac'.
Completed test 'flac_spec_test_35 - samplerate 134560Hz.flac' in 308ms
Running test 'flac_spec_test_36 - samplerate 384kHz.flac'.
Completed test 'flac_spec_test_36 - samplerate 384kHz.flac' in 756ms
Running test 'flac_spec_test_49 - Extremely large PADDING.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_49 - Extremely large PADDING.flac' in 2ms
Running test 'flac_spec_test_10 - blocksize 2304.flac'.
Completed test 'flac_spec_test_10 - blocksize 2304.flac' in 41ms
Running test 'flac_spec_test_31 - high resolution audio, using only 32nd order predictors.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_31 - high resolution audio, using only 32nd order predictors.flac' in 0ms
Running test 'flac_spec_test_28 - high resolution audio, default settings.flac'.
Completed test 'flac_spec_test_28 - high resolution audio, default settings.flac' in 230ms
Running test 'flac_spec_test_57 - PNG PICTURE.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_57 - PNG PICTURE.flac' in 0ms
Running test 'flac_spec_test_39 - 4 channels (4.0).flac'.
Completed test 'flac_spec_test_39 - 4 channels (4.0).flac' in 12ms
Running test 'flac_spec_test_51 - Extremely large VORBISCOMMENT.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_51 - Extremely large VORBISCOMMENT.flac' in 1ms
Running test 'flac_spec_test_15 - only verbatim subframes.flac'.
Completed test 'flac_spec_test_15 - only verbatim subframes.flac' in 46ms
Running test 'flac_spec_test_23 - 8 bit per sample.flac'.
Completed test 'flac_spec_test_23 - 8 bit per sample.flac' in 24ms
Running test 'flac_spec_test_58 - GIF PICTURE.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_58 - GIF PICTURE.flac' in 0ms
Running test 'flac_spec_test_26 - variable blocksize file created with CUETools.Flake 2.1.6.flac'.
Completed test 'flac_spec_test_26 - variable blocksize file created with CUETools.Flake 2.1.6.flac' in 189ms
Running test 'flac_spec_test_40 - 5 channels (5.0).flac'.
Completed test 'flac_spec_test_40 - 5 channels (5.0).flac' in 14ms
Running test 'flac_spec_test_34 - samplerate 192kHz, using only 32nd order predictors.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_34 - samplerate 192kHz, using only 32nd order predictors.flac' in 0ms
Running test 'flac_spec_test_19 - samplerate 35467Hz.flac'.
Completed test 'flac_spec_test_19 - samplerate 35467Hz.flac' in 64ms
Running test 'flac_spec_test_33 - samplerate 192kHz.flac'.
Completed test 'flac_spec_test_33 - samplerate 192kHz.flac' in 440ms
Running test 'flac_spec_test_11 - partition order 8.flac'.
Completed test 'flac_spec_test_11 - partition order 8.flac' in 44ms
Running test 'flac_spec_test_14 - wasted bits.flac'.
Completed test 'flac_spec_test_14 - wasted bits.flac' in 22ms
Running test 'flac_spec_test_37 - 20 bit per sample.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sample bit depth invalid (at 42)
Failed test 'flac_spec_test_37 - 20 bit per sample.flac' in 0ms
Running test 'flac_spec_test_30 - high resolution audio, blocksize 13456.flac'.
Completed test 'flac_spec_test_30 - high resolution audio, blocksize 13456.flac' in 217ms
Running test 'flac_spec_test_27 - old format variable blocksize file created with Flake 0.11.flac'.
Completed test 'flac_spec_test_27 - old format variable blocksize file created with Flake 0.11.flac' in 185ms
Running test 'flac_spec_test_09 - blocksize 1937.flac'.
Completed test 'flac_spec_test_09 - blocksize 1937.flac' in 47ms
Running test 'flac_spec_test_17 - all fixed orders.flac'.
Completed test 'flac_spec_test_17 - all fixed orders.flac' in 43ms
Running test 'flac_spec_test_53 - CUESHEET with very many indexes.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Invalid metadata block (at 2656126)
Failed test 'flac_spec_test_53 - CUESHEET with very many indexes.flac' in 0ms
Running test 'flac_spec_test_59 - AVIF PICTURE.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_59 - AVIF PICTURE.flac' in 0ms
Running test 'flac_spec_test_18 - precision search.flac'.
Completed test 'flac_spec_test_18 - precision search.flac' in 40ms
Running test 'flac_spec_test_52 - Extremely large APPLICATION.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_52 - Extremely large APPLICATION.flac' in 1ms
Running test 'flac_spec_test_24 - variable blocksize file created with flake revision 264.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_24 - variable blocksize file created with flake revision 264.flac' in 0ms
Running test 'flac_spec_test_63 - predictor overflow check, 24-bit.flac'.
Completed test 'flac_spec_test_63 - predictor overflow check, 24-bit.flac' in 16ms
Running test 'flac_spec_test_25 - variable blocksize file created with flake revision 264, modified to create smaller blocks.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_25 - variable blocksize file created with flake revision 264, modified to create smaller blocks.flac' in 0ms
Running test 'flac_spec_test_42 - 7 channels (6.1).flac'.
Completed test 'flac_spec_test_42 - 7 channels (6.1).flac' in 27ms
Running test 'flac_spec_test_05 - blocksize 254.flac'.
Completed test 'flac_spec_test_05 - blocksize 254.flac' in 50ms
Running test 'flac_spec_test_46 - no min-max framesize set.flac'.
Completed test 'flac_spec_test_46 - no min-max framesize set.flac' in 42ms
Running test 'flac_spec_test_54 - 1000x repeating VORBISCOMMENT.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_54 - 1000x repeating VORBISCOMMENT.flac' in 0ms
Running test 'flac_spec_test_02 - blocksize 4608.flac'.
Completed test 'flac_spec_test_02 - blocksize 4608.flac' in 50ms
Running test 'flac_spec_test_61 - predictor overflow check, 16-bit.flac'.
Completed test 'flac_spec_test_61 - predictor overflow check, 16-bit.flac' in 11ms
Running test 'flac_spec_test_55 - file 48-53 combined.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Invalid metadata block (at 33627388)
Failed test 'flac_spec_test_55 - file 48-53 combined.flac' in 263ms
Running test 'flac_spec_test_47 - only STREAMINFO.flac'.
Completed test 'flac_spec_test_47 - only STREAMINFO.flac' in 31ms
Running test 'flac_spec_test_45 - no total number of samples set.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Number of samples is zero (at 42)
Failed test 'flac_spec_test_45 - no total number of samples set.flac' in 0ms
Running test 'flac_spec_test_08 - blocksize 1000.flac'.
Completed test 'flac_spec_test_08 - blocksize 1000.flac' in 47ms
Running test 'flac_spec_test_04 - blocksize 192.flac'.
Completed test 'flac_spec_test_04 - blocksize 192.flac' in 50ms
Running test 'flac_spec_test_12 - qlp precision 15 bit.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_12 - qlp precision 15 bit.flac' in 0ms
Running test 'flac_spec_test_13 - qlp precision 2 bit.flac'.
FAIL: /home/kleines/serenity/Tests/LibAudio/TestFLACSpec.cpp:26: FLAC header: Sync code (at 0)
Failed test 'flac_spec_test_13 - qlp precision 2 bit.flac' in 0ms
Running test 'flac_spec_test_21 - samplerate 22050Hz.flac'.
Completed test 'flac_spec_test_21 - samplerate 22050Hz.flac' in 20ms
Finished 63 tests and 0 benchmarks in 4412ms (4388ms tests, 0ms benchmarks, 24ms other).
Out of 63 tests, 40 passed and 23 failed.
```

### PR DESCRIPTION
**Pull request by kleinesfilmroellchen**
This PR:
- makes FLAC tests work on both Lagom and Serenity (directory shenanigans)
- refactors the FLAC and Wasm test suite downloaders to use a backwards-compatible tar extraction helper
- makes the FLAC test runner not use a custom TestCase subclass because ASAN doesn't like you allocating with a different size (64 bytes TestCase) than what you allocated (160 bytes FLACTest)
- fixes the two remaining issues in the FLAC loader so that the spec suite passes
- ~~makes FLAC tests run on CI so that we don't regress on our spec compliance~~

With this PR, we are officially one of the least crashy decoders. See <https://wiki.hydrogenaud.io/index.php?title=FLAC_decoder_testbench>. However, during manual review of the tests, I noticed that several files are still glitchy. This is not something the test suite checks for (checksums are not implemented in the loader), but checking for non-crashing audio playback is enough for CI.

~~This PR adds significant time to the CI tests, over 12 minutes in on-target tests and 1'19" in Lagom tests. If this is an issue, we can drop either test, though that will mean we don't get to catch platform-specific issues.~~

Closes #14683

### CODE REVIEW

**Comment by GMTA** [comment]
> This PR adds significant time to the CI tests, over 12 minutes in on-target tests and 1'19" in Lagom tests

This seems a bit excessive for an audio decoder - what do you think about leaving this out of CI for now? If there are any FLAC PRs not by you, you´ll probably still chime in with this test suite :^)

**Comment by kleinesfilmroellchen** [comment]
Dropped the CI part of this PR as per @GMTA's request. Of course, manual checking is never as reliable as automatic CI, but it is quite a bit of test time.

**Comment by LucasChollet** [comment]
Shouldn't that close #14683?

**Review by linusg — APPROVED** [review]
Very cool! Has a conflict though.

**Pull request merged**
