### PR TITLE
Base: Update FontEditor manual use images with improved resolution

### PR DESCRIPTION
**Pull request by djwisdom**

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
You have a manpage for `pape` that managed to sneak in there.

**Comment by MacDue** [comment]
Why? Isn't it helpful to be able to see the screenshots clearly? 

If you just want them smaller when viewing the .md you can set the displayed width, but keep them full-sized, so if you click on the image you can see it clearly.

**Comment by djwisdom** [comment]
Am seriously considering MacDue's recommendation. 👍🏼  
Converting to Draft in the meanwhile.

**Comment by AtkinsSJ** [comment]
Looking at them, the existing ones are too large, they're blurry. For example:
image

This is at 100% zoom, so actual size, but you can see from the window title bars that the screenshots are stretched somehow. Not sure how that happened. Making them actual size would help, then someone can look into making help images shrink to fit automatically.

**Comment by MacDue** [comment]
@AtkinsSJ  I think the blurriness you see their is because of the > 100% scaling + QEMU on Windows (I remember someone saying that before). I think windows just scales up the window contents. 

https://discord.com/channels/830522505605283862/830529037251641374/976470532633542717

**Comment by djwisdom** [comment]
I tried to declare width and height in markdown but it's not displaying properly inside **Help** application. Downsizing the FontEditor manual images will naturally degrade user experience. I hope there is a natural compromise on this issue. I remember Andreas being surprised at the size of the images inside Help when I asked him about the chunky-ness of FontEditor manual in a previous episode of Office Hours.

**Comment by MacDue** [comment]
I think :atkinssj:AtkinsSJ is suggesting someone looks into getting the sizing working automatically in help (which would probably just mean tweaking how the md -> html generation works).

**Comment by djwisdom** [comment]
Images that automatically shrink to fit. That would be great. :)

**Comment by MacDue** [comment]
The easiest fix is updating `LibMarkdown` to add `style="max-width: 100%"` to images. A little trickier solution would be to support parsing image sizes (which is something [CommonMark](https://commonmark.org/) does not seem to support for <some reason>, so it'd have to be a little outside the spec).

**Comment by MacDue** [comment]
Ah there's is an extension to CommonMark for image sizes: https://github.com/commonmark/commonmark-spec/wiki/Deployed-Extensions#image-size

**Comment by AtkinsSJ** [comment]
Yeah, I was thinking either we add that to all markdown images, or make Help insert some JS into every help page that shrinks them and gives you the "click to expand" ability. Depends if we want to affect all markdown files or not. I kind of think it's useful to have everywhere, but there could be cases where you don't want it.

Either way, that doesn't have to be done as part of this PR! More of a "this would be a good solution to the problem".

**Comment by MacDue** [comment]
I've been messing around with implementing the image size extension as start, the JS solution sounds nice too (though currently the markdown loading is handled in LibWeb, so any widget like that would be active everywhere)

**Comment by djwisdom** [comment]
This sounds to me like more ❤️ to Help application :^). Either way, I'm liking it!

**Comment by djwisdom** [comment]
Implemented MacDue's suggestion of using `shot` native application from within SerenityOS to capture 1:1 ratio of screen shots. Now images are clearer and respects the actual size of the application. `Optipng` was also used on these images.

**Review by MacDue — APPROVED** [review]
:+1: Looks good! 

P.s. #14764 was merged so you can resize images within markdown now too (though you might need to anymore :^))

**Comment by djwisdom** [comment]
> 👍 Looks good!
> 
> P.s. #14764 was merged so you can resize images within markdown now too (though you might need to anymore :^))

Markdown image resizing will surely come in handy for documentation moving forward. :^)

**Pull request merged**
