### PR TITLE
Ports: Improve authenticity of downloads and various fixes

### PR DESCRIPTION
**Pull request by lnzero1dev**
Hello Mr. Kling, 
these patches improve the ports a bit in my view. It is possible to have various checksums/signature files etc. to check that the downloaded files are correct.
If you have any suggestions, additions or if I made something stupid, just tell me and I'll fix it :-)
Have a nice evening!

### CODE REVIEW

**Comment by awesomekling** [comment]
cc @larb0b

**Comment by bugaevc** [comment]
I don't see why you would want to build all ports with a single script. Ports are meant to follow an open world approach: there are many ot them, and there will be more, and they vary in usefulness depending on what you need. Your distro package manager probably doesn't have a command to install *all* the available packages, does it?

**Comment by lnzero1dev** [comment]
Hey @bugaevc,

it's more like a test script to see, which ports are actually working :-D So maybe this isn't really necessary for real world usage, but it could be used e.g. for CI purposes to check if all ports are buildable.
I just used it to see that some ports still need some improvement and that I don't crash ports that were working before my changes.
Anyhow, I can remove it and keep it locally on my disk. :-) What do you think?

Cheers,
Emanuel

**Comment by awesomekling** [comment]
The integrity checking is a very nice improvement. I don't mind the build all script. It's a nice way to quickly verify that all ports still build.

**Pull request merged**
