### PR TITLE
Documentation: Fix typo in BuildInstructions.md

### PR DESCRIPTION
**Pull request by RaigZ**
QUEMU -> QEMU
he -> they (more universal)

### CODE REVIEW

**Comment by drunderscore** [comment]
As already set forth in #6814, your gender change will _(most likely)_ not be accepted.
> This project is not an appropriate arena to advertise your personal politics.

**Comment by RaigZ** [comment]
Honestly did not realize that the change was considered to be political, just thought it was an unintentional flaw; but, I will stand by this decision and remove this change.

**Comment by awesomekling** [comment]
Please observe the [contributing guidelines](https://github.com/SerenityOS/serenity/blob/690eb3bb8a538e9773024f40e8b4676336c8f849/CONTRIBUTING.md)

Specifically:
> Squash your commits when making revisions after a patch review.

**Comment by RaigZ** [comment]
This is my first pull request; as it can be seen, I have had some trouble. I tried to perform a squash and believed I may have either done it twice or have not done it successfully. I apologize to the reviewers for the inconvenience. This tells me that I need to study git more.

**Comment by drunderscore** [comment]
No worries, I believe you may see more help in the [discord server](https://discord.gg/29gCcKsXkF) :^)

**Comment by bedantadey17** [comment]
It's just a small text no one will really take note of, and it's necessary, do you really think it's important enough to change it?

**Comment by spookyvision** [comment]
insisting on exclusively male pronouns is incredibly political too, my man.

**Comment by rebane2001** [comment]
the "no politics" rule is fine, but refusing to change male-only pronouns makes people (including me) feel unwelcome, which doesn't really work with the "everyone is welcome here" rule :/

**Comment by bedantadey17** [comment]
why are comments still allowed after closing the ticket?

**Comment by bedantadey17** [comment]
i believe it should use he/she

**Comment by iam-py-test** [comment]
> i believe it should use he/she

With all due respect, there are many people who identify as neither.
Thank you

**Comment by bedantadey17** [comment]
idk about all that, i was taught he/she to mention people so im suggesting that

**Pull request closed without merging**
