### PR TITLE
[joke] LibC: Reduce time_t to 32 bits so we can crash properly

### PR DESCRIPTION
**Pull request by alimpfard**
In memory of win2k :^)

### CODE REVIEW

**Comment by alimpfard** [comment]
I stole your #2000 with a silly PR

**Comment by alimpfard** [comment]
aww it doesn't build

silly printf size checks

**Comment by awesomekling** [comment]
For maximum Y2K horror, we'll need to go down all the way to 8-bit BCD!

**Comment by alimpfard** [comment]
That's more suited to an April 1st joke.

...I think this PR made enough people laugh, I'll close it now~

**Pull request closed without merging**
