### PR TITLE
WindowServer+KeyboardSetting+Applets+Utilities: Add support for switching between different keymaps

### PR DESCRIPTION
**Pull request by TSultanov**
- Add functionality to WindowServer to switch between keymaps on Alt-Shift key combo
- Add ability to select multiple keymaps to the KeyboardSettings dialog
- `keymap` commands supports both setting a keymap and configuring the list of selected keymaps. Setting active keymap not from the list of selected keymaps is prohibited
- Add an applet to show current active keymap

Screenshot:
image

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Nice feature! It's a bit weird to me that you removed the typing test area in one commit and then added it back again in the next though.

**Comment by TSultanov** [comment]
> It's a bit weird to me that you removed the typing test area in one commit and then added it back again in the next though.

At first I thought that making it work with multiple keymaps will be harder compared to having to deal with only one, so I removed it just to not have a broken feature. Afterward I figured out that it actually the exact same thing, so I brought it back. I can rewrite commit history to not show that it was ever removed if you wish.

**Comment by Xexxa** [comment]
I'm waiting with anticipation for this one, looks like a great feature. :)

**Comment by awesomekling** [comment]
This has conflicts that need to be resolved.

**Pull request merged**
