### PR TITLE
 Shell: Add a 'for' loop 

### LINKED ISSUE #2760: Shell: Needs more loops
After having used the shell on my host system for...basically forever, I have determined that loops are the most important next feature I want.
So let's discuss design!

Here are some initial ideas:
- Keep the bash-y syntax of `for <varname> in <expr>; block`
    - keep the block syntax: `do <stuff>... done`
    - use braces for block: `{ <stuff>... }`
- Borrow syntax from some existing language
    - js: `for (<var> in <expr>) block`
    - c++: `for (<var> : <expr>) block`
- Be more functional about it with `map`/`fold`
    - Syntax for blocks? semantics for passing blocks around?
- Invent something
    - ???

### PR DESCRIPTION
**Pull request by alimpfard**
Closes #2760.

The syntax I went with is:
- `for <expr> { sequence }`
- `for <ident> in <expr> { sequence }`

the braces are mandatory, and in the first one, the value is implicitly called `it`.
This PR also adds variable frames, because a proper language is a good language :^)

### CODE REVIEW

**Comment by alimpfard** [comment]
And I forgot again...cc @bugaevc (and @awesomekling, you seemed to also have some input on this).

I would also like to incorporate the `map` idea, by allowing them to be specific 'forms', in that the parser treats them differently (but that's for another PR).

**Comment by awesomekling** [comment]
@bugaevc any nitpicks here? ;)

**Comment by bugaevc** [comment]
¯\\\_(ツ)\_/¯

I haven't looked too closely, but nothing looks immediately wrong

**Comment by awesomekling** [comment]
Let's do it :)

**Pull request merged**
