### PR TITLE
Build: Make OSX build work with cmake

### PR DESCRIPTION
**Pull request by kevmeyer**
- [x] Working build with valid elf files & booting in qemu
- [ ] ~~Dynamic library demo compiles~~
- [ ] ~~Evaluate better use of cmake cross toolchain instead of darwin workarounds~~

### CODE REVIEW

**Comment by jonnii** [comment]
Do you have any idea on how to fix the below error?

```
[  8%] Built target boot
[  8%] Building CXX object Kernel/CMakeFiles/Kernel.dir/ACPI/DMIDecoder.cpp.o
In file included from .../ACPI/DMIDecoder.cpp:28:
.../serenity/./AK/Vector.h:40:14: fatal error: initializer_list: No such file or directory
   40 | #    include <initializer_list>
      |              ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Kernel/CMakeFiles/Kernel.dir/ACPI/DMIDecoder.cpp.o] Error 1
make[1]: *** [Kernel/CMakeFiles/Kernel.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by kevmeyer** [comment]
@jonnii did you follow the steps to build the toolchain prior to your build?  https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructions.md#build

Seems related to this: https://github.com/SerenityOS/serenity/blob/master/AK/Vector.h#L36

**Comment by jonnii** [comment]
@kevmeyer I tried recreating the toolchain before posting the comment but it didn't help and I have the same error. This used to work up until the `cmake` changes...

**Comment by devsh0** [comment]
Clean build the toolchain. In other words, delete the Local and Build  directory in serenity/Toolchain and do a rebuild. Even better if you git-clone to a new location and try a rebuild there. Also, make sure you are compiling with latest gcc (10.x or something).

**Comment by jonnii** [comment]
I have the same problem with a fresh copy of the repository.

**Pull request closed without merging**
