### PR TITLE
LibWasm: Use u32's instead of size_t's when reading LEB128 numbers

### PR DESCRIPTION
**Pull request by dzfrias**
The WebAssembly spec never relies on host system information, like size_t. For consistency's sake, we should stick to the usage of u32's instead of size_t's. This didn't cause issues before because LEB128-encoded u64's are a superset of LEB128-encoded u32's.

There's also a usage of ssize_t in the parser, but I didn't want to change that yet. It's only used when reading blocktypes, but I didn't want to touch it yet because the [encoding of blocktypes](https://webassembly.github.io/spec/core/binary/instructions.html#binary-blocktype) is a huge headache in the specification. Let me know if I should change it to an i32. I think it should actually be an i33 (or s33 in spec terms), but I think that's worth a separate discussion.

### CODE REVIEW

**Comment by alimpfard** [comment]
Yeah that was a bit dodgy, technically some crazy platform _could_ use 16b size_t...
re `i33`, if you _want to_, you can use `UFixedBigInt<33>`, or just slap a i64 there and pretend all is well.

**Review by alimpfard — APPROVED** [review]

**Comment by dzfrias** [comment]
Just to follow up on my comment about i33's, I just took a quick look at `block_0.wasm`, and it looks like it fails as a result of `ParseError::InvalidIndex`, likely from [this line](https://github.com/SerenityOS/serenity/blob/ed8d036b4171bca12bb7eaa6ff17783614468b36/Userland/Libraries/LibWasm/Parser/Parser.cpp#L283). I'm pretty sure that means that it's reading the blocktypes wrong, because it's trying to read a ssize_t when it should be reading an i33.

**Comment by dzfrias** [comment]
Hmm ok. We might need to make a custom way to read i33's in order to get block types working

**Comment by alimpfard** [comment]
Either is fine.
I'll hold off on merging this PR if you want.

**Comment by dzfrias** [comment]
Ok, I'll put it into a separate issue so that this PR can be merged. thank you!

**Pull request merged**
