### PR TITLE
Kernel: Don't enumerate blocks of ext2 symlinks by default

### LINKED ISSUE #1608: Ext2FS: ASSERTION FAILED: group_index <= m_block_group_count
Not sure if related to #1549

Reproduce:

```sh
ln -s /bin/Shell test
sleep 10     # optional wait to allow filesystem sync
rm test
```

Log:

```
[Shell(20:20)]: do_exec(/bin/ln)
[ln(20:20)]: VFS::symlink: 'test' (-> '/bin/Shell') in 1:15364
Shell(19): Command "ln -s /bin/Shell test" finished in 79 ms
[syncd(2:2)]: Ext2FS: Flushed 6 blocks to disk
[Shell(21:21)]: do_exec(/bin/sleep)
Shell(19): Command "sleep 10" finished in 10112 ms
[Shell(22:22)]: do_exec(/bin/rm)
Shell(19): Command "rm test" finished in 67 ms
[syncd(2:2)]: Ext2FS: Flushed 3 blocks to disk
[syncd(2:2)]: ASSERTION FAILED: group_index <= m_block_group_count
FileSystem/Ext2FileSystem.cpp:92 in const ext2_group_desc& Kernel::Ext2FS::group_descriptor(Kernel::Ext2FS::GroupIndex) const
[syncd(2:2)]: 0xc0118c63  __assertion_failed(char const*, char const*, unsigned int, char const*) +180
[syncd(2:2)]: 0xc0129df7  Kernel::Ext2FS::group_descriptor(unsigned int) const +55
[syncd(2:2)]: 0xc012ac64  Kernel::Ext2FS::set_block_allocation_state(unsigned int, bool) +106
[syncd(2:2)]: 0xc012cd05  Kernel::Ext2FS::free_inode(Kernel::Ext2FSInode&) +193
[syncd(2:2)]: 0xc012cdd8  Kernel::Ext2FSInode::~Ext2FSInode() +48
[syncd(2:2)]: 0xc012ce22  Kernel::Ext2FSInode::~Ext2FSInode() +28
[syncd(2:2)]: 0xc01878ef  AK::HashMap<unsigned int, AK::RefPtr<Kernel::Ext2FSInode>, AK::Traits<unsigned int> >::remove(unsigned int const&) +207
[syncd(2:2)]: 0xc012b128  Kernel::Ext2FS::uncache_inode(unsigned int) +50
[syncd(2:2)]: 0xc012e2a6  Kernel::Ext2FS::flush_writes() +414
[syncd(2:2)]: 0xc01307b8  Kernel::FS::sync() +638
[syncd(2:2)]: 0xc013c031  Kernel::VFS::sync() +21
[syncd(2:2)]: 0xc0175faa  init::{lambda()#1}::_FUN() +40
```

### PR DESCRIPTION
**Pull request by supercomputer7**
Fixes #1608.

### CODE REVIEW

**Comment by awesomekling** [comment]
Great job tracking this down :)

**Comment by bugaevc** [comment]
So, can we reland https://github.com/SerenityOS/serenity/pull/1513 now?

**Comment by supercomputer7** [comment]
> So, can we reland #1513 now?

I'd want to solve #1549 first, than to reland #1513 back. Also, this is a good chance for changing the code in the `FileBackedFS` class :)

**Comment by awesomekling** [comment]
#1513 introduced disk image corruption that was unrelated to this fix. We need to fix that first :)

**Pull request merged**
