### PR TITLE
Ports: Improve consistency and quality of ports

### PR DESCRIPTION
**Pull request by panos**
See: https://github.com/SerenityOS/serenity/pull/6444#discussion_r615617959

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
There's also `DESTDIR` btw. Maybe we should use that instead?

**Comment by panos** [comment]
> There's also `DESTDIR` btw. Maybe we should use that instead?

Wait, `${SERENITY_ROOT}/${SERENITY_BUILD_DIR} == ${DESTDIR}`?

**Comment by gunnarbeutner** [comment]
Almost, `$DESTDIR` also has `/Root`, so:

`${SERENITY_ROOT}/${SERENITY_BUILD_DIR}/Root == ${DESTDIR}`

And, as a bonus, `$DESTDIR` is `/` when building ports _in_ SerenityOS.

**Comment by linusg** [comment]
From https://github.com/SerenityOS/serenity/blob/master/Ports/.hosted_defs.sh:

```bash
export SERENITY_ROOT="$(realpath "${SCRIPT}/../")"
export SERENITY_BUILD_DIR="${SERENITY_ROOT}/Build/${SERENITY_ARCH}"
# ...
DESTDIR="${SERENITY_BUILD_DIR}/Root"
```

The only thing I don't like about `DESTDIR` is its terrible name, please use `SERENITY_BUILD_DIR` for now (no need to prepend `SERENITY_ROOT`, btw).

**Comment by linusg** [comment]
> And, as a bonus, $DESTDIR is / when building ports in SerenityOS.

That's neat, I guess it's fine then..

**Comment by gunnarbeutner** [comment]
I agree, the name is bad because `DESTDIR` also happens to be what most autoconf-based Makefiles use as their staging directory when running `make install`. We should probably rename that at some point. Maybe rename `SERENITY_ROOT` to `SERENITY_SOURCE` and `DESTDIR` to `SERENITY_ROOT`?

**Comment by panos** [comment]
> Maybe rename `SERENITY_ROOT` to `SERENITY_SOURCE` and `DESTDIR` to `SERENITY_ROOT`?

Makes sense.

**Comment by panos** [comment]
Excuse the brief mess up with the title, I really hope that this won't break everything. I started building up until flex and a few packages failed, but I'm not sure if that was the result of my change or not. Is it possible to compare these two in order to pinpoint any issues before merging?

**Comment by panos** [comment]
`./build_all.sh`:
```
$ ./build_all.sh 
Built bash.
Built bc.
Built binutils.
Built bison.
Built byacc.
ERROR: Build of bzip2 was not successful!
Built carl.
ERROR: Build of chester was not successful!
ERROR: Build of cmake was not successful!
ERROR: Build of cmatrix was not successful!
ERROR: Build of c-ray was not successful!
Built curl.
Built dash.
Built dialog.
ERROR: Build of diffutils was not successful!
Built dmidecode.
Built doom.
Built dropbear.
ERROR: Build of ed was not successful!
Built emu2.
Built figlet.
ERROR: Build of flatbuffers was not successful!
ERROR: Build of flex was not successful!
Built freetype.
Built frotz.
ERROR: Build of gcc was not successful!
ERROR: Build of genemu was not successful!
Built git.
Built gmp.
ERROR: Build of gnucobol was not successful!
Built gnupg.
Built gnuplot.
ERROR: Build of grep was not successful!
ERROR: Build of hatari was not successful!
ERROR: Build of imgcat was not successful!
ERROR: Build of indent was not successful!
Built jot.
Built jq.
Built klong.
Built less.
ERROR: Build of libarchive was not successful!
Built libassuan.
Built libexpat.
Built libffi.
Built libgcrypt.
Built libgpg-error.
Built libiconv.
Built libicu.
Built libjpeg.
Built libksba.
ERROR: Build of libogg was not successful!
Built libpng.
Built libpuffy.
ERROR: Build of libtiff was not successful!
Built libtool.
Built libvorbis.
ERROR: Build of libzip was not successful!
Built links.
Built lua.
Built m4.
Built make.
Built mandoc.
ERROR: Build of mawk was not successful!
Built mbedtls.
Built mrsh.
Built nano.
Built nasm.
Built ncurses.
Built neofetch.
ERROR: Build of nesalizer was not successful!
Built nethack.
Built ninja.
ERROR: Build of nnn was not successful!
Built npth.
Built ntbtls.
Built nyancat.
Built oksh.
ERROR: Build of openssh was not successful!
Built openssl.
Built patch.
Built pcre.
Built pcre2.
Built pkgconf.
Built printf.
ERROR: Build of pt2-clone was not successful!
Built python3.
ERROR: Build of quake was not successful!
ERROR: Build of rsync was not successful!
ERROR: Build of scummvm was not successful!
ERROR: Build of SDL2 was not successful!
ERROR: Build of SDL2_gfx was not successful!
ERROR: Build of SDL2_image was not successful!
ERROR: Build of SDL2_mixer was not successful!
ERROR: Build of SDL2_ttf was not successful!
ERROR: Build of SDLPoP was not successful!
ERROR: Build of sed was not successful!
Built sl.
ERROR: Build of sqlite was not successful!
Built stress-ng.
ERROR: Build of Super-Mario was not successful!
Built termcap.
Built tinycc.
Built tinyscheme.
Built tr.
Built vim.
Built vitetris.
Built vttest.
ERROR: Build of xz was not successful!
Built yasm.
Built zlib.
Built zstd.
```

**Comment by gunnarbeutner** [comment]
Which distro is that on btw? Just out of curiosity because most of the ports build just fine here on ArchLinux.

**Review by linusg — APPROVED** [review]
this is great, thank you!

**Comment by panos** [comment]
> Which distro is that on btw?

I use Arch btw.

**Pull request merged**
