### PR TITLE
Kernel: Add FAT12 Read Only FileSystem

### PR DESCRIPTION
**Pull request by elp2**

### CODE REVIEW

**Comment by bgianfo** [comment]
What's the motivation for adding this? Are you planning on adding write support later? Where did you get the definitions for disk metadata sizes, etc? Is the spec open and publicly available, I didn't see a link in the comments, but maybe I missed it?

It would be nice to actually describe the commit, a five word commit message for a new FS implementation seems a bit short 😁

**Comment by IdanHo** [comment]
Note also that FAT12 supports a maximum volume size of 32MB, which makes it a bit useless for pretty much everything today..

**Comment by nico** [comment]
Having a fat32 driver would probably be useful for running on an rpi.

**Comment by elp2** [comment]
What would a 90's operating system be without the premier 90's File System?

I wasn't sure what the right way to break this down would be and first wanted to get something out there to see what the appetite from the project generally was. I'm planning the following future commits:

1) FAT 16/32 Allocation Table support
2) VFAT (long file names)
3) Writing support (probably split out across creating the children of a directory, writing files, writing directories)
4) Is it possible to add a dependency on Userland/Libraries/LibCore/DateTime.cpp somehow? I see some Kernel/ files are depending on Userland. I've implemented a very simple version of that since the FAT times store the decimal times.

**Comment by supercomputer7** [comment]
> What would a 90's operating system be without the premier 90's File System?
> 
> I wasn't sure what the right way to break this down would be and first wanted to get something out there to see what the appetite from the project generally was. I'm planning the following future commits:
> 
>     1. FAT 16/32 Allocation Table support
> 
>     2. VFAT (long file names)
> 
>     3. Writing support (probably split out across creating the children of a directory, writing files, writing directories)
> 
>     4. Is it possible to add a dependency on Userland/Libraries/LibCore/DateTime.cpp somehow? I see some Kernel/ files are depending on Userland. I've implemented a very simple version of that since the FAT times store the decimal times.

While I'm not against adding a FAT support in Serenity, I do think the slogan of "90's operating system" makes sense in relation to  the aesthetics and usability benefits that 90s software and OSes had. However, it doesn't make sense to add a FAT12 driver as it was already said that this is not practical for usage in modern daily desktop usage (unless you play with floppy disks, but we removed support for them a long time ago).
Also, FAT (and I mean, VFAT and FAT32) makes more sense to use if you have a USB thumb drive to plug into the system. Remember that unix systems in general support FAT-based filesystems, but don't allow you to use it as a primary storage device. We still lack support of USB mass storage (and USB hotplug in relation to USB mass storage devices), so again, at least I can't see how can I use it now. However, if it's a WIP and you commit to make it usable (i.e. adding FAT32 support), then I think that's fine :)
I'd still argue that we can skip FAT12 and FAT16 and go right into FAT32 (so we keep things simple and usable), but that's not up to me to make the call about this.

**Comment by supercomputer7** [comment]
_**warning: this will be a long message.** I do believe in not shortening things if it's important... I wrote this here because not everyone are on the discord server._

There was also a discussion on patent issues on the discord server. now, people suggest to not speak too much about this so we don't have to deal with it (which to be honest, I think this is really a silly solution for this matter, since when silencing of problems helped anybody?). I don't know what is the status of patents holding FAT32 and VFAT, but I know these 2 facts:
1. exfat is completely out of the scope when talking about patents. this means we can't touch it without explicit permission, because it's under a patent we can't do anything about. Linux on the other hand, was given a permission so they included it in their source tree.
2. **there were legal problems in the past with implementations of fat32 and vfat.** no way around it. although the articles I read were from the mid 2000s.

Now, I raised few questions in regard to legal problems vs the benefits of this patch:
1. People already found workarounds of this legal question. Although I'm sure many just didn't care enough, I don't want this project to blindly include something that has some trouble with it. I raised the idea of leveraging FUSE-based solution. this means **we add support for a FUSE mechanism to do all the good for us**, without caring about the actual implementation.
People raised the fact that 1. FAT32 is mandatory for EFI booting, 2. Many people use FAT32 on thumb drive, 3. Many people use FAT32 on SD cards and also on SD cards for RPi installations. I get it - we want to use FAT32. However, if it's possible to do that not in the Kernel, then I assume we're good.
I didn't even mention the benefits of security from using FUSE-based solution, and the opportunities to mount all sorts of filesystems out there.
2. There's the community question we need to ask. Let's say we merge this and merge future patches. Then let's say someone else see that and doesn't like it so they tell us with nice words which say "get rid of it right now.". We do that without a question I guess, but what effect this will have on our community? **it's definitely a bad look for us as a project**.

Regardless of the legal issues, I also raised the question of usability of this feature (FAT12, FAT16 and FAT32). People use this filesystem only because everyone else support this (hence UEFI spec mandates the use of this filesystem) . **Remember, this filesystem has no mitigations against file corruption, not mitigations for fragmentation, it has hard limits of file sizes which are really limiting nowadays.** The one good thing about this family of filesystem is simplicity, nothing else.

**I say we should play it "better safe than sorry"**, or in relation to this patch and future patches "better safe than sorry, I'll remove this code now". As I said in the discord server, we are hackers (in the good sense of the word) and programmers - not lawyers.
That's not up to me on whether to merge or not the patch, but I'd highly suggest to reconsider this.

**Comment by elp2** [comment]
If there are any questions about this patch from a patents perspective I'm happy to close it for now and start looking at writing a FUSE file system interface which could power this plus other options.

My original goal here was to get more familiar with how file systems on Serenity worked while providing something the community would be excited about which is why I wanted to get some early feedback on the FAT 12 version.

**Comment by supercomputer7** [comment]
> If there are any questions about this patch from a patents perspective I'm happy to close it for now and start looking at writing a FUSE file system interface which could power this plus other options.
> 
> My original goal here was to get more familiar with how file systems on Serenity worked while providing something the community would be excited about which is why I wanted to get some early feedback on the FAT 12 version.

The reason I asked these questions is because I'm a bit worried about the consequences of this patch (and future patches that are based on this patch). It's a project that strives to create some beautiful and usable, and I assume that if there were no issues with patents in regard to FAT filesystems (and I also assume that really nobody wants to mess around with all of these questions, because it's really not the job of anyone in this project), then that could be another nice feature in the project :)
I guess it's up to @awesomekling to decide on this. I'm definitely not at the position to tell you to close the pull request, nor to tell you to start writing a FUSE interface.

**Comment by nico** [comment]
I still think this is a cool patch and a good basis for more modern fat support later on fwiw.

**Comment by frhun** [comment]
Just want to drop here that you can legally implement Fat32 - license free - when it is for the purposes of implementing UEFI.

**Comment by supercomputer7** [comment]
> And also all the long file name patents have expired by now: https://patents.google.com/patent/US5579517A/en https://patents.google.com/patent/US5745902A/en https://patents.google.com/patent/US6286013B1/en

I didn't know you can search for these patents with the help of google :)
That's more satisfactory. Do you know anything else about patents for FAT32 (the pure FAT32, not VFAT)?

Although I don't have any legal knowledge whatsoever to examine the topic thoroughly, I still think we can make some sense from all of this "mess" somehow if we really want to.

**Comment by frhun** [comment]
As can be read [here](https://en.wikipedia.org/wiki/ExFAT#Adoption) later FAT versions/related technology is open to [OIN](https://en.wikipedia.org/wiki/Open_Invention_Network) members. I think it (maybe) could be possible for such technologies to be part of SerenityOS if @awesomekling , or more likely the company he set up for SerenityOS, would join OIN.

**Pull request closed without merging**
