### PR TITLE
LibWasm: Sync with ladybird

### LINKED ISSUE #8668: LibWasm: loop_0.wasm spec test causes CI timeout
Investigate whether the source is:

1) The way the test is written just takes forever to execute, and increase the Lagom test timeouts in `.github/workflows/cmake.yml`
2) Bug(s) in the way upstream wat2wasm parses the test source
3) Bug(s) in the way `generate_wasm_spec_test.py` handles the test
4) Bug(s) in LibWasm regarding heavily nested loops

### PR DESCRIPTION
**Pull request by alimpfard**
Also closes #8668.

### CODE REVIEW

**Comment by nico** [comment]
If you add ladybird as a remote, you can use `git cherry-pick -x` which will put the upstream commit in the commit desc. And/or linking to the upstream PR is nice too. (But as-is is fine too as long as CI likes it.)

**Comment by alimpfard** [comment]
I just yoinked the commit as-is from the ladybird remote, but sure, let's cherry-pick -x.

**Review by nico — APPROVED** [review]

**Comment by nico** [comment]
Not quite sure what happened here, but the commit hashes are all wrong. The first commit has hash e64ac8c17732bdb97689644b43d07f61d3f6cab2 in lb for example.

**Comment by nico** [comment]
This cherry-picked:
https://github.com/LadybirdBrowser/ladybird/pull/134
https://github.com/LadybirdBrowser/ladybird/pull/130
https://github.com/LadybirdBrowser/ladybird/pull/149
https://github.com/LadybirdBrowser/ladybird/pull/148
https://github.com/LadybirdBrowser/ladybird/pull/147

**Pull request merged**
