### PR TITLE
Terminal: Kill shell to fix crash dialog on close

### PR DESCRIPTION
**Pull request by IanMarcoMoffett**
Before this commit when you close the terminal you'll get a crash dialog saying shell has crashed.
Now, that should be gone.

### CODE REVIEW

**Comment by GMTA** [comment]
Hi, thanks for trying to fix this issue! Unfortunately this doesn't seem like the right fix:

* What happens when `should_confirm_close` is `false`?
* What happens when `close_message` has a value?
* Why `SIGKILL` the Shell process? Shouldn't we give it some chance to terminate properly?

The crash seems to originate in `Shell::read_single_line()`. Start there, and try to see why it crashes.

**Comment by IanMarcoMoffett** [comment]
> Hi, thanks for trying to fix this issue! Unfortunately this doesn't seem like the right fix:
> 
>     * What happens when `should_confirm_close` is `false`?
> 
>     * What happens when `close_message` has a value?
> 
>     * Why `SIGKILL` the Shell process? Shouldn't we give it some chance to terminate properly?
> 
> 
> The crash seems to originate in `Shell::read_single_line()`. Start there, and try to see why it crashes.

Alright, I will see what I can do.

**Comment by GMTA** [comment]
@Ian-Marco-Moffett since you opened this PR, commit c045d09840503350b9ec576cfdbbdc1dadbb849a has landed in `master` and probably fixes the issue you were trying to fix as well.

**Comment by IanMarcoMoffett** [comment]
> @Ian-Marco-Moffett since you opened this PR, commit [c045d09](https://github.com/SerenityOS/serenity/commit/c045d09840503350b9ec576cfdbbdc1dadbb849a) has landed in `master` and probably fixes the issue you were trying to fix as well.

Ah, alright :+1: .

**Comment by linusg** [comment]
Seems like this is no longer needed then, please reopen otherwise.

**Pull request closed without merging**
