### PR TITLE
Base: Add a lot of emoji

### PR DESCRIPTION
**Pull request by treuks**
This commit adds many, many flags.
# subgroup: sound
📢 - U+1F4E2 LOUDSPEAKER (fully-qualified)
📣 - U+1F4E3 MEGAPHONE (fully-qualified)

# subgroup: office
📐 - U+1F4D0 TRIANGULAR RULER (fully-qualified)

# subgroup: tool
🔫 - U+1F52B WATER PISTOL (fully-qualified)
🏹 - U+1F3F9 BOW AND ARROW (fully-qualified)

# group: Symbols

# subgroup: other-symbol
🔰 - U+1F530 JAPANESE SYMBOL FOR BEGINNER (fully-qualified)

# group: Flags

# subgroup: country-flag
🇦🇨 - U+1F1E6 U+1F1E8 FLAG: ASCENSION ISLAND (fully-qualified)
🇦🇩 - U+1F1E6 U+1F1E9 FLAG: ANDORRA (fully-qualified)
🇦🇫 - U+1F1E6 U+1F1EB FLAG: AFGHANISTAN (fully-qualified)
🇦🇮 - U+1F1E6 U+1F1EE FLAG: ANGUILLA (fully-qualified)
🇦🇱 - U+1F1E6 U+1F1F1 FLAG: ALBANIA (fully-qualified)
🇦🇷 - U+1F1E6 U+1F1F7 FLAG: ARGENTINA (fully-qualified)
🇦🇸 - U+1F1E6 U+1F1F8 FLAG: AMERICAN SAMOA (fully-qualified)
🇧🇱 - U+1F1E7 U+1F1F1 FLAG: ST. BARTHÉLEMY (fully-qualified)
🇧🇲 - U+1F1E7 U+1F1F2 FLAG: BERMUDA (fully-qualified)
🇧🇳 - U+1F1E7 U+1F1F3 FLAG: BRUNEI (fully-qualified)
🇧🇶 - U+1F1E7 U+1F1F6 FLAG: CARIBBEAN NETHERLANDS (fully-qualified)
🇧🇿 - U+1F1E7 U+1F1FF FLAG: BELIZE (fully-qualified)
🇨🇨 - U+1F1E8 U+1F1E8 FLAG: COCOS (KEELING) ISLANDS (fully-qualified)
🇨🇰 - U+1F1E8 U+1F1F0 FLAG: COOK ISLANDS (fully-qualified)
🇨🇻 - U+1F1E8 U+1F1FB FLAG: CAPE VERDE (fully-qualified)
🇨🇽 - U+1F1E8 U+1F1FD FLAG: CHRISTMAS ISLAND (fully-qualified)
🇨🇾 - U+1F1E8 U+1F1FE FLAG: CYPRUS (fully-qualified)
🇩🇬 - U+1F1E9 U+1F1EC FLAG: DIEGO GARCIA (fully-qualified)
🇩🇲 - U+1F1E9 U+1F1F2 FLAG: DOMINICA (fully-qualified)
🇩🇿 - U+1F1E9 U+1F1FF FLAG: ALGERIA (fully-qualified)
🇪🇨 - U+1F1EA U+1F1E8 FLAG: ECUADOR (fully-qualified)
🇪🇷 - U+1F1EA U+1F1F7 FLAG: ERITREA (fully-qualified)
🇪🇹 - U+1F1EA U+1F1F9 FLAG: ETHIOPIA (fully-qualified)
🇫🇯 - U+1F1EB U+1F1EF FLAG: FIJI (fully-qualified)
🇫🇰 - U+1F1EB U+1F1F0 FLAG: FALKLAND ISLANDS (fully-qualified)
🇬🇩 - U+1F1EC U+1F1E9 FLAG: GRENADA (fully-qualified)
🇬🇪 - U+1F1EC U+1F1EA FLAG: GEORGIA (fully-qualified)
🇬🇮 - U+1F1EC U+1F1EE FLAG: GIBRALTAR (fully-qualified)
🇬🇲 - U+1F1EC U+1F1F2 FLAG: GAMBIA (fully-qualified)
🇬🇵 - U+1F1EC U+1F1F5 FLAG: GUADELOUPE (fully-qualified)
🇬🇶 - U+1F1EC U+1F1F6 FLAG: EQUATORIAL GUINEA (fully-qualified)
🇬🇸 - U+1F1EC U+1F1F8 FLAG: SOUTH GEORGIA & SOUTH SANDWICH ISLANDS (fully-qualified)
🇬🇺 - U+1F1EC U+1F1FA FLAG: GUAM (fully-qualified)
🇮🇴 - U+1F1EE U+1F1F4 FLAG: BRITISH INDIAN OCEAN TERRITORY (fully-qualified)
🇰🇾 - U+1F1F0 U+1F1FE FLAG: CAYMAN ISLANDS (fully-qualified)
🇲🇸 - U+1F1F2 U+1F1F8 FLAG: MONTSERRAT (fully-qualified)
🇳🇺 - U+1F1F3 U+1F1FA FLAG: NIUE (fully-qualified)
🇳🇿 - U+1F1F3 U+1F1FF FLAG: NEW ZEALAND (fully-qualified)
🇵🇳 - U+1F1F5 U+1F1F3 FLAG: PITCAIRN ISLANDS (fully-qualified)
🇸🇭 - U+1F1F8 U+1F1ED FLAG: ST. HELENA (fully-qualified)
🇹🇦 - U+1F1F9 U+1F1E6 FLAG: TRISTAN DA CUNHA (fully-qualified)
🇹🇨 - U+1F1F9 U+1F1E8 FLAG: TURKS & CAICOS ISLANDS (fully-qualified)
🇹🇻 - U+1F1F9 U+1F1FB FLAG: TUVALU (fully-qualified)
🇻🇬 - U+1F1FB U+1F1EC FLAG: BRITISH VIRGIN ISLANDS (fully-qualified)
##
It also adds some (cool) emojis
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
> Psst hey, you might want to list your emojis in your commit and PR description, like I was told to do, in a format like this:
> 
> > tickets - U+1F39F ADMISSION TICKETS

Yes please! Also, squash those two commits together since the second one just corrects a mistake in the first one.

**Comment by treuks** [comment]
> Psst hey, you might want to list your emojis in your commit and PR description, like I was told to do, in a format like this:
> 
> > 🎟 - U+1F39F ADMISSION TICKETS

You can't send most of the flags from the PR onto GitHub (and I'm also extremely lazy), hope just the images will be okay.

**Comment by treuks** [comment]
i am extremely good at git

**Comment by Xexxa** [comment]
> > Psst hey, you might want to list your emojis in your commit and PR description, like I was told to do, in a format like this:
> > > tickets - U+1F39F ADMISSION TICKETS
> 
> You can't send most of the flags from the PR onto GitHub (and I'm also extremely lazy), hope just the images will be okay.

Meta/generate-emoji-txt.sh Build/i686/UCD/emoji-test.txt /folder/to/the/emoji/you/have/made /the/file/you/want/the/list/of/emoji/in/the/right/format/commit.txt :^)

**Comment by treuks** [comment]
> > > Psst hey, you might want to list your emojis in your commit and PR description, like I was told to do, in a format like this:
> > > > tickets - U+1F39F ADMISSION TICKETS
> > 
> > 
> > You can't send most of the flags from the PR onto GitHub (and I'm also extremely lazy), hope just the images will be okay.
> 
> Meta/generate-emoji-txt.sh Build/i686/UCD/emoji-test.txt /folder/to/the/emoji/you/have/made /the/file/you/want/the/list/of/emoji/in/the/right/format/commit.txt :^)

Where is the Build directory, do you need to build serenity to have it, if so, I am on Windows

**Comment by treuks** [comment]
okay i got it, thanks

**Review by Xexxa — CHANGES_REQUESTED** [review]
Your commits need some squashin' and the commit message should contain what emoji has been added (good example at [15252/commits](https://github.com/SerenityOS/serenity/pull/15252/commits). Basically just copy the codepoints you have in the PR description to the commit message. :^)

image

**Comment by AtkinsSJ** [comment]
Looks good! And wow, you weren't joking with it being a lot of emoji.

**Pull request merged**
