### PR TITLE
LibCore+Userland: Add more detectable formats to file utility

### PR DESCRIPTION
**Pull request by vkoskiv**
This PR adds 7 new detectable formats, as well as new functionality for detecting binary signatures at an arbitrary offset in a given file.

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
Let's keep those lists sorted. Also, we're reading `0x9001` bytes and one mime type has a header offset of `0x9001` and size of `5` - that doesn't seem right?

**Comment by vkoskiv** [comment]
Fixed and fixed!

**Comment by vkoskiv** [comment]
Removed the unused `var_name_offset` variables. I have no idea why I put them there in the first place!

**Comment by linusg** [comment]
Cool!

**Pull request merged**
