### PR TITLE
LibGUI+Browser: Address bar focus behaviour + bookmarking keyboard shortcut

### PR DESCRIPTION
**Pull request by robryanx**
Currently the browser address bar is a bit slow to use compared to Chrome/ Firebox bahaviour of autofocusing.

This changes the behaviour to select all and place the cursor at the end of the line when focused, subsequent bahaviour after initial focusing is as normal for a TextBox.

This also adds the ability to specify a widget as not autofocusable when Window::focus_a_widget_if_possible is called. This is so when the browser is loaded or a new page is loaded that the address bar doesn't automatically gain focus.

### CODE REVIEW

**Comment by awesomekling** [comment]
> This changes the behaviour to select all

Sure, that makes sense.

> and place the cursor at the end of the line when focused

What is the significance of this?

**Comment by robryanx** [comment]
> What is the significance of this?

When selecting the line placing the cusor at the end of the line is more natural. I don't think it changes the functionality whether it is at the start or the end. The select all on focus was the same behaviour as triple click so I updated the pull request so that both cases use a new `select_current_line` method.

**Comment by awesomekling** [comment]
I force-pushed some fixes to the commit messages, primarily for turning a 2-line subject into a single line.

**Comment by robryanx** [comment]
Thanks, noted for next time :)

**Pull request merged**
