### PR TITLE
HackStudio: Fix desync between hackstudio texteditor widget and language server

### LINKED ISSUE #4369: HackStudio: Crash due to LanguageServer desynchronizing from TextEditorWidget when pasting multiple lines.
This a a kind of strange bug that has a fairly precise (though reliable) reproduction. It can be triggered in a lot of different ways when pasting code that gets autoindented, but this is the simplest reproduction I've found.

1. Open a c++ file in hack studio.
2. Insert, on a new line at the end of the the file, the following characters: `<SPACE><A><NEWLINE><SPACE><B>`.
3. Select from the start of `<A>` to the end of `<B>` (selection should be `<A><NEWLINE><SPACE><SPACE><B>`, with the second space inserted due to autoindent).
4. Press Ctrl+x with the characters still selected.
5. Press Ctrl+v.
6. Press Enter.
7. Press Backspace.

This crashes HackStudio, with the following debug output.

```
CppLanguageServer(89): InsertText for file: main.cpp
CppLanguageServer(89): Text:  
CppLanguageServer(89): [28:0]
CppLanguageServer(89): InsertText for file: main.cpp
CppLanguageServer(89): Text: a
CppLanguageServer(89): [28:1]
CppLanguageServer(89): InsertText for file: main.cpp
CppLanguageServer(89): Text: 

CppLanguageServer(89): [28:2]
CppLanguageServer(89): InsertText for file: main.cpp
CppLanguageServer(89): Text:  
CppLanguageServer(89): [29:1]
CppLanguageServer(89): InsertText for file: main.cpp
CppLanguageServer(89): Text: b
CppLanguageServer(89): [29:2]
Clipboard(17): Storage::set_data <- [text/plain] 0x02808000 (5 bytes)
CppLanguageServer(89): RemoveText for file: main.cpp
CppLanguageServer(89): [28:1 - 29:3]
CppLanguageServer(89): InsertText for file: main.cpp
CppLanguageServer(89): Text: a
  b
CppLanguageServer(89): [28:1]
CppLanguageServer(89): InsertText for file: main.cpp
CppLanguageServer(89): Text: 

CppLanguageServer(89): [29:3]
CppLanguageServer(89): RemoveText for file: main.cpp
CppLanguageServer(89): [30:0 - 30:2]
USERSPACE(89) ASSERTION FAILED: length <= m_text.size()
./Libraries/LibGUI/TextDocument.cpp:197
[CppLanguageServer(89:89)]: CPU[0] NP(error) fault at invalid address V0x019025e8
[CppLanguageServer(89:89)]: 0xc0182103  Kernel::Process::sys$exit(int) +31
[CppLanguageServer(89:89)]: 0xc017bb69  syscall_handler +691
[CppLanguageServer(89:89)]: 0xc017b8ae  syscall_asm_entry +49
[CppLanguageServer(89:89)]: 0x080480d5  __cxa_guard_acquire.cold +0
[CppLanguageServer(89:89)]: 0x08071bf4  tolower +0
[CppLanguageServer(89:89)]: 0x080510e8  GUI::TextDocumentLine::remove_range(GUI::TextDocument&, unsigned long, unsigned long) +94
[CppLanguageServer(89:89)]: 0x0805150b  GUI::TextDocument::remove(GUI::TextRange const&) +175
[CppLanguageServer(89:89)]: 0x08049504  LanguageServers::Cpp::ClientConnection::handle(Messages::LanguageServer::FileEditRemoveText const&) +366
[CppLanguageServer(89:89)]: 0x0804ab14  LanguageServerEndpoint::handle(IPC::Message const&) +110
[CppLanguageServer(89:89)]: 0x0804cd89  IPC::Connection<LanguageServerEndpoint, LanguageClientEndpoint>::handle_messages() +125
[CppLanguageServer(89:89)]: 0x0806f0ba  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
[CppLanguageServer(89:89)]: 0x08067559  Core::EventLoop::pump(Core::EventLoop::WaitMode) +397
[CppLanguageServer(89:89)]: 0x080677cf  Core::EventLoop::exec() +43
[CppLanguageServer(89:89)]: 0x080485d2  main +396
[CppLanguageServer(89:89)]: 0x08048b1e  _start +94
```

### PR DESCRIPTION
**Pull request by ccapitalK**
Fixes #4369.

### CODE REVIEW

**Comment by ccapitalK** [comment]
I think the CI check may be broken, It appears to want to move `#include "Editor.h"` below `#include "Debugger/Debugger.h"`, which breaks the alphabetical `#include`'s rule.

**Comment by linusg** [comment]
> It appears to want to move #include "Editor.h" below #include "Debugger/Debugger.h"

No, it doesn't: https://github.com/SerenityOS/serenity/runs/1541508565

```diff
diff --git a/DevTools/HackStudio/Editor.cpp b/DevTools/HackStudio/Editor.cpp
index 257dfd1..c52f838 100644
--- a/DevTools/HackStudio/Editor.cpp
+++ b/DevTools/HackStudio/Editor.cpp
@@ -24,8 +24,8 @@
  * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  */
 
-#include "Debugger/Debugger.h"
 #include "Editor.h"
+#include "Debugger/Debugger.h"
 #include "EditorWrapper.h"
 #include "HackStudio.h"
 #include "Language.h"
```

It clearly wants to `move #include "Editor.h" above #include "Debugger/Debugger.h"` / `move #include "Debugger/Debugger.h" below #include "Editor.h"`.

> but I still think the linter's broken.

It's not. clang-format-10 with the project's config file does exactly this. If your local setup is doing something different, then that's broken :)

**Comment by ccapitalK** [comment]
@linusg Sorry, I think I got that backwards, either way it wants to change the order so it's not alphabetical, which I thought was weird. If you are certain this is expected behaviour, I have no issue with it. :)

**Comment by awesomekling** [comment]
This feels badly factored. It's not very nice that the text insertion command has to know anything about auto indentation. Can we instead make the auto indentation mechanism happen earlier, so that it's simply some extra whitespace merged into the command?

**Comment by ccapitalK** [comment]
> This feels badly factored. It's not very nice that the text insertion command has to know anything about auto indentation. Can we instead make the auto indentation mechanism happen earlier, so that it's simply some extra whitespace merged into the command?

Sure, I'll try to do that then. This will result in a change to texteditor's API though; where the `InsertTextCommand` value made visible to `Editor::on_edit_action()` used to show the text that was inserted before auto-formatting, it will now show what was actually inserted into the document. It looks like HackStudio is the only program right now that overrides `Editor::on_edit_action()`, so it shouldn't affect anything else.

**Comment by ccapitalK** [comment]
I've updated the PR, now it also fixes the undo/redo bug that I also reported in #4369. I'm not sure if this is the best way to refactor it, I feel like I've duplicated LibGUI's Cursor logic, but I think the modification to the API is decent. I did the formatting outside the constructor since I feel like formatting should be a seperate step, which can only be done with a client.

**Comment by awesomekling** [comment]
cc @itamar8910

**Comment by itamar8910** [comment]
Yeah looks good to me, nice factoring @ccapitalK :smile:

**Pull request merged**
