### PR TITLE
Let aarch64 port call into C++

### PR DESCRIPTION
**Pull request by nico**
Originally wanted to make this a bit bigger, but have to run a surprise errand instead.

### CODE REVIEW

**Review by linusg — APPROVED** [review]
Linter failing because `len("Put all but the first core into a loop, make room for some stack, and call init().") == 82`, code LGTM!

**Comment by IdanHo** [comment]
Also `arch64` => `aarch64` in the first commit title

**Comment by nico** [comment]
Both fixed, thanks.

**Comment by nico** [comment]
> Linter failing because `len("Put all but the first core into a loop, make room for some stack, and call init().") == 82`, code LGTM!

Also, can I run that locally? `Meta/run-ci.sh` didn't flag that locally for me.

**Comment by linusg** [comment]
> Also, can I run that locally? Meta/run-ci.sh didn't flag that locally for me.

Sure, but it's handled in a different script - [`lint-commit.sh`](https://github.com/SerenityOS/serenity/blob/master/Meta/lint-commit.sh). I recommend installing pre-commit and letting it deal with all commit-related linting.

**Comment by IdanHo** [comment]
> Sure, but it's handled in a different script - [`lint-commit.sh`](https://github.com/SerenityOS/serenity/blob/master/Meta/lint-commit.sh?rgh-link-date=2021-09-06T18%3A30%3A30Z). I recommend installing pre-commit and letting it deal with all commit-related linting.

Adding onto that, check this out for more info: https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#commit-hooks

**Pull request merged**
