### PR TITLE
TextEditor: Set modified flag after save 

### PR DESCRIPTION
**Pull request by previa**
Solution for #8902 by adding a SaveCommand to the TextEditor. This command does not add any actions to the UndoStack and won't be merged with undo/redo actions that were previously added to the UndoStack. This way the modified flag gets set after saving the file without losing undo/redo functionality.

### CODE REVIEW

**Comment by GMTA** [comment]
Having a save action on the undo stack that you cannot undo is a bit strange; wouldn't it be simpler to mark the undo stack as unmergeable for the next action only after saving a file? Basically leave out the `SaveAction` and `no_action` changes, and leave in the `m_merge` bit.

**Comment by previa** [comment]
You are correct, the `SaveAction` does bring a lot of overhead and is not needed. Just pushed a commit that should change that.

**Comment by awesomekling** [comment]
Please squash fixups into the relevant preceding commit, we don't need to see your random editing history. :)

**Comment by previa** [comment]
Sorry about that, the random editing commits are now squashed.

**Comment by awesomekling** [comment]
> Sorry about that, the random editing commits are now squashed.

Hmm? You still have a commit adding a `SaveFileCommand` and then the next commit immediately removes it again.

Also please clean up your commit messages after performing a squash :)

**Pull request closed without merging**
