### PR TITLE
HexEditor: Change Hex Editor Close options to Yes/No/Cancel

### PR DESCRIPTION
**Pull request by sidkapoor97**
1. Changed HexEditor close options from Ok/Quit to Yes/No/Cancel
2. Added respective actions for each action
3. References #7169

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
Hello! Please update the commit message according to the [contribution guidelines](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md), something like `HexEditor: Change unsaved changes message box type to Yes/No/Cancel`. Please also format the code with clang-format.

**Comment by sidkapoor97** [comment]
Sure, I will squash both these commits to a newer commit and update the commit message

**Comment by linusg** [comment]
Yes :)

**Comment by linusg** [comment]
That didn't quite work...

**Comment by apoorv-mishra** [comment]
@sidkapoor97 Still working on it?

**Comment by bcoles** [comment]
This was implemented in #8069.

**Pull request closed without merging**
