### PR TITLE
Ports: Implement './package.sh shell' to get a shell with all the environment set

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Can you also update the list of options in `Ports/README.md`? :)

**Comment by radare** [comment]
I have updated the readme, but the failing lint check doesn't seems to be good to me, there are already > 72 column lines in this file before my edit. So not sure what should I do in here

**Comment by gunnarbeutner** [comment]
The lint error is about your commit message - not the contents of the files you edited.

**Comment by radare** [comment]
Oh.. I need more coffee, thanks for clarifying

**Pull request merged**
