### PR TITLE
Ports: Update Cave Story version

### PR DESCRIPTION
**Pull request by gloof11**
Updated the version of Cave Story that is pulled from my repo. The original port of this was missing game files that would've been extracted on first boot.

### CODE REVIEW

**Review by MacDue — COMMENTED** [review]
> Ports: Cave Story port fix. **Upadated** ingame files #20215

Typo in your commit message ^

Though I think I'd be better to just say: "Ports: Update Cave Story version" (and maybe add a commit description saying this version fixes x, y, and z).

**Comment by gloof11** [comment]
> > Ports: Cave Story port fix. **Upadated** ingame files #20215
> 
> Typo in your commit message ^
> 
> Though I think it'd be better to just say: "Ports: Update Cave Story version" (and maybe add a commit description saying this version fixes x, y, and z).

Made the appropriate changes to the PR

**Comment by AtkinsSJ** [comment]
> Made the appropriate changes to the PR

You need to modify the commit message, not the PR title. Use `git commit --amend` to change it, and then `git push --force` to update it here.

**Comment by gloof11** [comment]
> > Made the appropriate changes to the PR
> 
> You need to modify the commit message, not the PR title. Use `git commit --amend` to change it, and then `git push --force` to update it here.

Force pushed the new commit message.

**Pull request merged**
