### PR TITLE
Ports: Use immutable tarballs for libsodium

### PR DESCRIPTION
**Pull request by timschumi**
The tarball appears to have been updated after the release.

### CODE REVIEW

**Comment by GMTA** [comment]
The reason why can be read here:
https://download.libsodium.org/libsodium/releases/README.html

The `-stable` variant receives periodic (security) fixes and the like from the currently unreleased next version of libsodium. We can either drop the `-stable` suffix so our port uses the immutable tarball, or we accept that we need to update the SHA-256 every so often.

**Comment by timschumi** [comment]
I'll take a look at verifying integrity via signatures instead, which is probably the most stable solution.

**Comment by awesomekling** [comment]
We should use an immutable tarball IMO. Otherwise we don't know what we're building.

**Comment by GMTA** [comment]
Using signatures from the same source defeats the purpose of the signature. Even when you verify it through GPG, if someones key gets compromised we still verify the wrong thing. Using an immutable tarball + SHA-256 signature that we checked ourselves is probably one of the most stable and safe versions to use.

**Comment by timschumi** [comment]
Updated the patch to use immutable tarballs.

**Pull request merged**
