### PR TITLE
Documentation: Add libssl-dev apt package in build instructions

### PR DESCRIPTION
**Pull request by tbhaxor**

### CODE REVIEW

**Comment by GMTA** [comment]
In the commit message, you're talking about `Utilities/cmcurl`. Is this for the `cmake` port? If so: we have lots of port with extra dependencies required to install them. It does not warrant adding these to the general build instructions though - you can build SerenityOS just fine without them.

**Comment by tbhaxor** [comment]
> In the commit message, you're talking about `Utilities/cmcurl`. Is this for the `cmake` port? If so: we have lots of port with extra dependencies required to install them. It does not warrant adding these to the general build instructions though - you can build SerenityOS just fine without them.

I got the error while building toolchain `Meta/serenity.sh rebuild-toolchain`

**Comment by GMTA** [comment]
> I got the error while building toolchain Meta/serenity.sh rebuild-toolchain

Ah, in that case: you need to fix up your commit message :^)

**Comment by ADKaster** [comment]
This is when we detect that the host CMake is not 3.25 or better and build it ourselves in the Toolchain directory. It's correct that we need to add this to the dependencies. However your commit message is too long for the linter.

It's probably better to say the requirement comes from Toolchain/BuildCmake.sh

**Comment by tbhaxor** [comment]
I fixed it, based on previous commit messages. Since this is my first commit in the repo, would you guide me?

**Comment by tbhaxor** [comment]
> However your commit message is too long for the linter.

Is there any way I could locally link this?

**Comment by ADKaster** [comment]
If you want to verify your commit messages and other CI checks locally, you can install both(!) pre-commit hooks. 

https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#commit-hooks

**Review by ADKaster — APPROVED** [review]

**Pull request merged**
