### PR TITLE
Ports: Remove auth_type for our own packages

### PR DESCRIPTION
**Pull request by gunnarbeutner**
Otherwise we'd have to update them in this repository every time something changes.

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Oh right, I need to update the lint checks.

**Comment by gunnarbeutner** [comment]
> It does seem unlikely that the ports would be compromised without the main source tree also being compromised.

Aye, if we can't trust GitHub, then who can we trust?

**Comment by bcoles** [comment]
> 
> 
> > It does seem unlikely that the ports would be compromised without the main source tree also being compromised.
> 
> Aye, if we can't trust GitHub, then who can we trust?

I know what you mean, but to clarify for historical purposes:

It's not so much as about trusting GitHub, it's about trusting a repository and everyone who has access to a repository. In this instance, using integrity hashes doesn't offer much value, as anyone who has write access to the ports likely also has write access to the SerenityOS repository.

If this assumption is wrong (does anyone have write access to the ports but not to the main source tree?) then integrity hashes *do* offer value and *should be used*.

**Comment by panos** [comment]
Hashes are not only good for security, but they also help with corrupted downloads. However, they also tend to waste a lot of time.

**Comment by linusg** [comment]
@gunnarbeutner please resolve conflicts :)

**Comment by gunnarbeutner** [comment]
Done. :)

**Pull request merged**
