### PR TITLE
LibGUI: Add on_return_pressed event callback to Dialog

### PR DESCRIPTION
**Pull request by diath**
Rationale: While working on a feature for `PixelPaint`, I noticed that I could only submit the `New Image` dialog by pressing the return key when the name `TextEditor` widget is focused, but not when the width and height `SpinBox` widgets are focused. As it turns out, the dialog was being manually `done(ExecOK)`'d in a custom `on_return_pressed` callback in the `TextEditor`, I propose an own `on_return_pressed` handler for `Dialog` class that allows for submitting the `Dialog` regardless of which child widget is focused, improving keyboard based navigation. Additionally, the `on_return_pressed` callback returns a boolean value, returning `false` value from the callback will then propagate the event to the child widgets (as needed).

### CODE REVIEW

**Comment by diath** [comment]
The CI failure seems to be due to #9962.

**Comment by diath** [comment]
Also, the reason why it's a callback instead of calling `done(ExecOK)` directly in the `Dialog` event handler (like Escape -> `done(ExecCancel)` does) is that so you can implement validate-on-return handlers, such as:
```cpp
on_return_pressed = [this] {
	if (!validate()) {
		focus_invalid_child();
		return;
	}

	done(execOK);
	return true;
};
```

**Comment by ADKaster** [comment]
I see the extra callback being added but I don't see any users of it in this PR.

If you've got a text editor patch to replace the custom on return pressed callback with your new generic one, then adding that patch as a second commit to this PR would be better than trying to add an API with no users at all.

**Comment by diath** [comment]
I meant to open a separate PR but I just moved the changes here.

**Pull request closed without merging**
