### PR TITLE
Meta: Port recent LibWeb changes to gn and fix one pre-existing issue

### PR DESCRIPTION
**Pull request by ADKaster**
New files/features:

- CSS Math Functions generator
- Transform Streams
- Queueing Strategies for Streams

Pre-existing:
- WriteableStreamDefaultController was not bound to JS in @mattco98 's original commit.

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
Seems a little silly having to backport a bunch of changes now. Can we not have a basic GN build in CI?

**Comment by ADKaster** [comment]
We could add a CI job, but then that would make it everyone's responsibility to keep this build working, rather than just me and whoever else is interested in testing it out. Which isn't actually that much extra work, but it is measurable extra work for PRs adding new source files in areas that already have gn build files.

**Comment by linusg** [comment]
Dunno - clearly it was considered important enough to be merged into the main repo, and at that point we can expect people to not break it with their PRs. If you don't think it should be everyone's responsibility then I'm not sure why this is not just part of a testing branch or something.

**Comment by linusg** [comment]
(this LGTM btw)

**Pull request merged**
