### PR TITLE
Documentation: Remove explaination for why we don't support 32 bit CPUs

### PR DESCRIPTION
**Pull request by supercomputer7**

### CODE REVIEW

**Comment by nico** [comment]
Comment from the peanut gallery: I find the framing here a bit weird. Once there's 64-bit support, imho the default assumption should be that _of course_ we wouldn't support 32-bit unless there's some great reason for it. There isn't, so it's not supported. I'd write from that angle. (But, from that angle, there really isn't all that much to say.)

**Comment by supercomputer7** [comment]
> Comment from the peanut gallery: I find the framing here a bit weird. Once there's 64-bit support, imho the default assumption should be that _of course_ we wouldn't support 32-bit unless there's some great reason for it. There isn't, so it's not supported. I'd write from that angle. (But, from that angle, there really isn't all that much to say.)

I agree we could write from that angle, but ofc as you said, in that case there really isn't all that much to say. So I rather keep it this way.

**Review by kleinesfilmroellchen — APPROVED** [review]

**Comment by nico** [comment]
> in that case there really isn't all that much to say

Win-win, shorter docs :)

**Review by BenWiederhake — APPROVED** [review]
Exactly what it says on the tin. Great!

**Comment by awesomekling** [comment]
Agree with nico. This seems excessively verbose for something we're *not* doing. Also, is this really a frequently asked question?

**Comment by supercomputer7** [comment]
> Agree with nico. This seems excessively verbose for something we're _not_ doing. Also, is this really a frequently asked question?

To be honest,  I find this question quite weird to ask too. If we just assume that 64 bit is the normal thing, we might as well just remove this because as nico said, it should quite obvious that we should support 64-bit, and we are not the only OS to be 64-bit only.
I will send a commit removing this altogether then.

**Comment by supercomputer7** [comment]
Rebased this and force-pushed because CI failed on the flaky `TestKernelAlarm` test.

**Review by GMTA — APPROVED** [review]

**Pull request merged**
