### PR TITLE
Ports: Add grepcidr port

### PR DESCRIPTION
**Pull request by EWouters**
grepcidr

### CODE REVIEW

**Comment by EWouters** [comment]
Oops, forgot to add the `package.sh` and I don't know how to force push with Github Desktop.

```bash
#!/usr/bin/env -S bash ../.port_include.sh
port='grepcidr'
version='2.0'
files="http://www.pc-tools.net/files/unix/grepcidr-${version}.tar.gz grepcidr-${version}.tar.gz 61886a377dabf98797145c31f6ba95e6837b6786e70c932324b7d6176d50f7fb"
auth_type='sha256'

export CFLAGS='-O3 -Wall -Werror'
```

**Comment by GMTA** [comment]
@EWouters you should really find a way to update your branch with the right files :^)

**Comment by EWouters** [comment]
@GMTA Done!

**Review by timschumi — CHANGES_REQUESTED** [review]
Looks reasonable, but the `package.sh` script isn't marked as executable, so we can't actually run it.

**Comment by EWouters** [comment]
Fixed the permissions of `package.sh` 😅.

**Review by timschumi — APPROVED** [review]
Not too sure about if we really want that `-O3`, but compiles and works just fine.

**Comment by EWouters** [comment]
I just followed the [instructions](http://www.pc-tools.net/unix/grepcidr/).

Any reason we don't want `O3`?

**Comment by timschumi** [comment]
If it uses `-O3` by default that's fine, but then we don't need to export it manually to begin with.

**Comment by EWouters** [comment]
Right, thank you.

**Comment by EWouters** [comment]
I removed the `export` and it still compiles with `-O3`, so it should be fine now I think.

**Pull request merged**
