### PR TITLE
Documentation: Add a table of contents for Documentation

### PR DESCRIPTION
**Pull request by AtkinsSJ**
Back by popular demand*, it's #14295! Fixed up the links that had changed, and rearranged a couple of them.

<small>* For very small values of "popular"</small>

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
Should be in Documentation/README.md tho

**Comment by AtkinsSJ** [comment]
> Should be in Documentation/README.md tho

My bad! I forgot to move it back there.

**Comment by linusg** [comment]
Now it's `Documentation/Documentation.md` :thonk:

The point of `README.md` is that it'll actually show up when you go into `Documentation/` on GitHub

**Comment by AtkinsSJ** [comment]
:facepalm: :facepalm: :facepalm:

**Review by linusg — APPROVED** [review]

**Pull request merged**
