### PR TITLE
Improve launching applications from Terminal

### PR DESCRIPTION
**Pull request by ls-1801**
Currently, right-clicking applications inside the terminal presents the options to launch the application via itself or Text Editor.
image
This pull request changes the current behavior to launch applications without URLs, by creating an appropriate IPC call to the LauncherServer and differentiating by the LauncherType attribute.
image
While preserving the behavior of opening files (test.html)
image

Note: the last commit also changes the LauncherServer.ini in that the TextEditor is no longer the default for all files. Previously every file could be launched using the Text Editor which appears to be odd in most cases. The Text Editor AppFile already includes most of the actual useful file extensions.

### CODE REVIEW

**Comment by networkException** [comment]
The commit prefix of 704636e9b2f98689f13f6e01a98f4a68da18d70c would probably rather be `LibVT` and the one of 1c89f9e22ea630f286774a52ed91b30bbced7d05 `Base`.

Also having TextEditor as the default fallback for unknown file types seems reasonable to me, especially for files without an extension (for example `/etc/fstab`).

**Comment by ls-1801** [comment]
@networkException Okay, I do see your point regarding Text Editor as default, but maybe there should be a way to exclude binary files.

**Comment by networkException** [comment]
Well if something needs to be executed its encoded in the file permission

**Comment by ls-1801** [comment]
but what about shell scripts?

**Comment by networkException** [comment]
In order to be able to run them they also need to have said permission

**Comment by ls-1801** [comment]
No, I was thinking about the other way around. You may want to edit the shell script using the Text Editor, but also want to be able to execute it. But I guess in that case the '.sh' file extension would be enough.

**Pull request closed without merging**
