### PR TITLE
Base: Add 11 new emoji

### PR DESCRIPTION
**Pull request by hansejo**
🎱 - U+1F3B1 Pool 8 Ball
💭 - U+1F4AD Thought Balloon
🌼 - U+1F33C Blossom
🍚 - U+1F35A Cooked Rice
🍬 - U+1F36C Candy
🌐 - U+1F310 Globe with Meridians
🌸 - U+1F338 Cherry Blossom
🍁 - U+1F341 Maple Leaf
🍦 - U+1F366 Soft Ice Cream
🐦 - U+1F426 Bird
🥣 - U+1F963 Bowl with Spoon

Screenshot_20220903_203845

### CODE REVIEW

**Comment by demostanis** [comment]
there's no 8 on the 8 ball?

**Comment by hansejo** [comment]
> there's no 8 on the 8 ball?

Very difficult on a 10x10 pixel grid. This is the compromise I came up with.

**Comment by djwisdom** [comment]
Any further improvements welcome but as I see it currently, lgtm. :^)

**Review by Xexxa — APPROVED** [review]
lgtm

**Pull request merged**
