### PR TITLE
LibWeb: Run XML parser input through encoding decoder

### PR DESCRIPTION
**Pull request by kalenikaliaksandr**
Fixes parsing error on:
http://wpt.live/css/CSS2/positioning/position-relative-nested-001.xht

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
Can we find a spec to reference for this please?

**Comment by awesomekling** [comment]
> Can we find a spec to reference for this please?

Based on https://html.spec.whatwg.org/multipage/introduction.html#html-vs-xhtml it sounds like we should be handling this with an XML parser.

**Comment by kalenikaliaksandr** [comment]
sorry, right, for some reason I thought that "application/xhtml+xml" is exception like "image/svg+xml" that needs to be parsed like html. I will have to fix XML document parser then.

**Comment by awesomekling** [comment]
> sorry, right, for some reason I thought that "application/xhtml+xml" is exception like "image/svg+xml" that needs to be parsed like html. I will have to fix XML document parser then.

It's non-normative but... it sounds like https://html.spec.whatwg.org/#dom-parsing-and-serialization kinda implies that we should be pulling `image/svg+xml` through the XML parser as well 😅

**Comment by kalenikaliaksandr** [comment]
the actual problem is that http://wpt.live/css/CSS2/positioning/position-relative-nested-001.xht has byte order mark that was not sniffed before passing to XML parser.

**Review by linusg — COMMENTED** [review]
Typo in commit message: it's -> it

**Comment by kalenikaliaksandr** [comment]
@linusg thank you for catching this! I updated commit with fixed typo.

**Pull request merged**
