### PR TITLE
AK: Add FixedString

### PR DESCRIPTION
**Pull request by ldm5180**
Problem:
- There is no compile-time string capability.

Solution:
- Create a FixedString class which supports conversion to StringView
  and concatenation.

### CODE REVIEW

**Comment by bgianfo** [comment]
We already have `operator sv`, does this add additional capabilities that could compile time string views don't?

**Comment by alimpfard** [comment]
We had an equivalent (albeit badly named) `LiteralString` for this purpose which was used for `AK/Format.h` for format string validity checking, but it was removed in favour of `CheckedFormatString` and co.
Do you have any particular use-case in mind for this?

**Comment by ldm5180** [comment]
> We already have [`operator "" sv`](https://en.cppreference.com/w/cpp/string/basic_string_view/operator%22%22sv) for string view literals, does this add additional capabilities that compile time string view literals don't have?

StringViews do not manipulate strings such as concatenate.

**Comment by ldm5180** [comment]
> We had an equivalent (albeit badly named) `LiteralString` for this purpose which was used for `AK/Format.h` for format string validity checking, but it was removed in favour of `CheckedFormatString` and co.
> Do you have any particular use-case in mind for this?

@awesomekling Asked me about this a few months ago. This is an initial implementation which we can continue to expand to do compile-time string manipulation. He was looking for a string class which can be used at compile-time so that some strings which are currently being constructed at initialization time could be constructed at compile-time and stored in the binary. I don't know if this is still desired or not. If not, feel free to close.

**Comment by alimpfard** [comment]
For the record, I think this is a good addition (though I don't like using `operator+` for string concat, but that's a separate issue).
I'm just curious if you have any use-case in mind.

**Comment by ldm5180** [comment]
I don't know exact use-cases he was considering. I wish I did so I could put this to use somewhere. I can take a look around and see if anything pops out at me.

Would you prefer `.append()` in favor of `operator+()`?

**Comment by alimpfard** [comment]
Could be interesting to see what would benefit from comptime string ops 🤷 

`.append()` sounds nice, but also sounds like a mutating member fun...
Some more ideas:
- `.add()`
- `.concat()`
...on second thought, `operator+` looks the best, so LGTM.

**Comment by awesomekling** [comment]
Without a specific use-case in mind, I don't think we should add this.

I think the compile-time strings I've talked about in the past have been specifically about something that could be used to key into a `HashMap<String, T>` at compile time.

**Pull request closed without merging**
