### PR TITLE
Meta: Document that clang-15 is required, and update the compiler check

### PR DESCRIPTION
**Pull request by trflynn89**
We require clang-15 for consteval.

### CODE REVIEW

**Review by caoimhebyrne — APPROVED** [review]

**Comment by BertalanD** [comment]
Could we remove `AK_STRING_VIEW_LITERAL_CONSTEVAL` now, then?

**Comment by nico** [comment]
If you use https://llvm.org/PR48886 it should redirect to the matching GitHub issue.

**Review by nico — APPROVED** [review]
Lgtm fwiw

**Comment by BertalanD** [comment]
But a4f8590247264b9c3121f48dd5b3db707c934ba2 is in the [llvmorg-15.0.0-rc1](https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.0-rc1) tag, no?

**Comment by trflynn89** [comment]
> But [a4f8590247264b9c3121f48dd5b3db707c934ba2](https://github.com/llvm/llvm-project/commit/a4f8590247264b9c3121f48dd5b3db707c934ba2) is in the [llvmorg-15.0.0-rc1](https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.0-rc1) tag, no?

Nice! yeah seems to work fine

**Comment by BertalanD** [comment]
hopefully Xcode 14.3 will be fine with this change too...

**Comment by ADKaster** [comment]
The consteval change broke oss-fuzz :( I opened a fix.

**Pull request merged**
