### PR TITLE
Base: Add manpages for cut, diff, head & rmdir command line utilities

### PR DESCRIPTION
**Pull request by salaaad2**
First batch of manpages. Missing manpages found in issue #11311.

### CODE REVIEW

**Comment by bgianfo** [comment]
small nitpick, the commit title prefix of `Base:` is normally used for man pages.

**Review by bgianfo — CHANGES_REQUESTED** [review]
small nitpick, the commit title prefix of `Base:` is normally used for man pages.

**Comment by bgianfo** [comment]
@salaaad2 looks like you changed the PR title but didn't change the commit title?

**Comment by salaaad2** [comment]
The commit following the wrong naming convention has been rebased

**Pull request merged**
