### PR TITLE
headless-browser: Re-implement headless-browser using an OOPWV

### PR DESCRIPTION
**Pull request by trflynn89**

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
headless-browser importing code from Ladybird seems backwards, shouldn't this live in LibWebView to be shared across the two, and possibly Browser as well?

**Comment by trflynn89** [comment]
I can move the process launcher to LibWebView, but it wouldn't be used by Browser, as we launch WebContent through SystemServer there. That is kinda how SQLServer works now too, the process launcher is in LibSQL, but only used by Ladybird.

That would still leave some amount of headless-browser.cpp pulling in Ladybird. It needs to know the candidate paths to WebContent, and figuring that out is Qt-specific. We could do what sql.cpp does and pass in the path as a command line argument:
https://github.com/SerenityOS/serenity/blob/874c7bba289222916911caf3102c77ee3a261d77/Userland/Utilities/sql.cpp#L352-L354

**Comment by trflynn89** [comment]
I pushed what it looks like to move the process launcher to LibWebView. Not sure what else to do about using Ladybird's helper for finding the Qt-specific path to WebContent. A command line flag like we use for sql.cpp would be uglier than this IMO, as WebDriver would also need to know the path in order to launch headless-browser.

**Review by linusg — APPROVED** [review]
LGTM! Shrinking that down to 200 lines is just delightful :yakkiss:

**Pull request merged**
