### PR TITLE
Base: Add more emojis

### PR DESCRIPTION
**Pull request by nataliakeniganti**
bandicam 2024-10-12 19-50-56-638
Base: Add more emojis
🏍 - U+1F3CD MOTORCYCLE
👪 - U+1F46A FAMILY
👲 - U+1F472 PERSON WITH SKULLCAP
💑 - U+1F491 COUPLE WITH HEART
🦛 - U+1F99B HIPPOPOTAMUS

### CODE REVIEW

**Comment by nataliakeniganti** [comment]
@nico merge pull request?

**Comment by nico** [comment]
Did you see https://github.com/SerenityOS/serenity/pull/25089#issuecomment-2403637430?

**Comment by nataliakeniganti** [comment]
> Did you see https://github.com/SerenityOS/serenity/pull/25089#issuecomment-2403637430?

@nico merge this?

**Comment by nico** [comment]
> > Did you see [#25089 (comment)](https://github.com/SerenityOS/serenity/pull/25089#issuecomment-2403637430)?
> 
> @nico merge this?

What I was trying to ask: Shouldn't the background pixels be transparent instead of white?

**Comment by nataliakeniganti** [comment]
> > > Did you see [#25089 (comment)](https://github.com/SerenityOS/serenity/pull/25089#issuecomment-2403637430)?
> > 
> > 
> > @nico merge this?
> 
> What I was trying to ask: Shouldn't the background pixels be transparent instead of white?

i tried merge this?

**Pull request closed without merging**
