### PR TITLE
Base: Add Bubble Tea emoji (U+1F9CB)

### PR DESCRIPTION
**Pull request by tarob0ba**
One single glyph: Bubble Tea (U+1F9CB)
Since you've taken the time to look at this, have a 🧋.

If I've screwed something up, please let me know.

### CODE REVIEW

**Comment by tarob0ba** [comment]
Fixing the commit titles now. Whoops!

**Comment by tarob0ba** [comment]
Alright, crossing my fingers.

**Review by linusg — CHANGES_REQUESTED** [review]
Please remove all these useless history updates from the commit message

**Comment by tarob0ba** [comment]
Fixed, sorry.

**Comment by tarob0ba** [comment]
Apologies for my screw-ups.

**Review by linusg — APPROVED** [review]
Nice, thanks!

**Pull request merged**
