### PR TITLE
CMake: fix cmake toolchain and missing header

### PR DESCRIPTION
**Pull request by predmond**
- AK and Kernel headers should be installed Root/usr/include
- Toolchain/CMakeToolchain.txt should point to Root/ in the Build/
  directory

### CODE REVIEW

**Comment by bugaevc** [comment]
Looks fine to me, I guess, modulo the commit message.

And perhaps let's rename the function to `serenity_install_headers`?

**Comment by linusg** [comment]
@awesomekling can this be merged please? I need it and manually editing `CMakeToolchain.txt` is annoying :)

**Comment by awesomekling** [comment]
I was waiting for @bugaevc's review to be addressed but I can just merge it manually :)

**Comment by awesomekling** [comment]
Merged manually in 4d4e578edfde7299cfbebce8af9f34b82b0fbd21

**Pull request closed without merging**
