### PR TITLE
Base: Change JSON file icon to add CSS file icon

### PR DESCRIPTION
**Pull request by electrikmilk**
Adding a typical CSS file icon conflicts with the current JSON file icon.

I'm proposing to fix this the JSON file icon color be changed to red (or possibly grey like the JSON logo), and the current JSON file icon becomes the CSS file icon as blue is the primary color in the CSS logo and is more often associated with CSS in other file icons I found in research. Obviously, this isn't a perfect solution as I imagine contributors are used to this current icon.

For example:

filetype-css style.css

filetype-css_32
style.css

filetype-json data.json

filetype-json_32
data.json

The CSS logo could be used instead as we do with JS, Python, etc., but I'm not sure it works at 16x16, and this ties the icon to the current version of CSS. @AtkinsSJ pointed out they have abandoned using versions either way.

### CODE REVIEW

**Comment by electrikmilk** [comment]
Checks seem irrelevant to my current changes

**Comment by electrikmilk** [comment]
> One key consideration when designing icons is that any two don't differ only in their colours - this would make it hard to impossible for colour blind folks to distinguish them.

That's a fair point 🤦

I'll work on another option for JSON. I can't see a better option being used for CSS other than the current JSON icon, however.

**Comment by linusg** [comment]
Hint: the 16px variant doesn't need to use the file shape as it's base, we have a couple of icons that use a language logo for example. "CSS" is three letters, that could fit.

**Comment by linusg** [comment]
- filetype-javascript javascript
- filetype-python python
- filetype-cplusplus cpp - using "C++" and extending to the left and right of the file shape

**Comment by electrikmilk** [comment]
> * filetype-javascript javascript
> * filetype-python python
> * filetype-cplusplus cpp - using "C++" and extending to the left and right of the file shape

I tried putting just the letters "CSS" in an icon with not much luck, trying an icon with a globe on it like the HTML icon since they are related. Maybe this works?

**Comment by electrikmilk** [comment]
> Hint: the 16px variant doesn't need to use the file shape as it's base, we have a couple of icons that use a language logo for example. "CSS" is three letters, that could fit.

I tried putting just the letters "CSS" in an icon with not much luck, trying an icon with a globe on it like the HTML icon since they are related. Maybe this works?

**Review by linusg — COMMENTED** [review]
I feel like the browser icon could be larger on the 32px variant, but this seems fine for now.

**Comment by electrikmilk** [comment]
> I feel like the browser icon could be larger on the 32px variant, but this seems fine for now.

I agree, maybe in a future PR I'll change that, didn't wanna cover up the brackets too much

**Pull request merged**
