### PR TITLE
Base: Add black and white icon set

### PR DESCRIPTION
**Pull request by Xexxa**
381 of our icons in black and white. Some looks awesome, most looks good and a few I hope somebody improves later on. :caret:

Not sure if the path is the best one :bikeshed:.

Icons optimized with `optipng -nb -nc -np`, total size 137.6 kB (color icons 502,8 kB in comparison)

done

## All 16x16 icons

16x16

### CODE REVIEW

**Comment by djwisdom** [comment]
So clean... so pristine... so... white  :^)

**Comment by Xexxa** [comment]
> So clean... so pristine... so... white :^)

They are less white on a coloured background(as you can see in the menus)... ;-)

**Comment by Xexxa** [comment]
I hereby summon the great decider @awesomekling

I made these icons for a black and white theme, I noticed these looked good in other themes, I hope the icons could be too help for someone with sight impairment(just a guess) and realized that the two color icons could probably programmatically be swapped in the UI for almost endless end user customization.

But at the same time idk if SerenityOS needs a black and white icon theme or if the icons are good enough. Usually Andreas decide these things :caret:

**Comment by kennethmyhra** [comment]
I think these look pretty cool. And nice to look at!

**Comment by Xexxa** [comment]
Closing because it's now available at https://github.com/SerenityOS/theming

**Pull request closed without merging**
