### PR TITLE
Ports: Unbreak the vim port (+ some other ports as well)

### PR DESCRIPTION
**Pull request by spholz**
The vim port was broken due to fc2d46c0b9db98b589bbedf5d4525f031ad996ce, which caused the termcap weak symbol hack (from #10493) to no longer work, and the terminal resize trick of 54ab6fe5b9ab1d95a2a58ba2ebd40aaeb8e3eeaa.

This PR resolves the first issue by simply removing our LibC termcap implementation and making all ports use the ncurses one instead.
I tested building all ports (and toolchains) to see if this breaks anything else, and all ports that work on current master still build fine with this PR.

The second issue was solved by simply not sending resize events on clears when the alternate buffer is in use.

### CODE REVIEW

**Comment by DanShaders** [comment]
> However, building with libintl support enabled fails due to symbol resolving issues.

Is it the problem with dynamic loader?

The commits here make me think if we should do something like <https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot> for ports.

**Comment by spholz** [comment]
> > However, building with libintl support enabled fails due to symbol resolving issues.
> 
> Is it the problem with dynamic loader?

**Comment by spholz** [comment]
> > However, building with libintl support enabled fails due to symbol resolving issues.
> 
> Is it the problem with dynamic loader?

Ah sorry, I forgot to update that commit message. No, it just fails to link. 

> The commits here make me think if we should do something like https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot for ports.

I'm not sure how we could do something like that. We could maybe create minimal "chroots" once pkg is able to install packages?

**Comment by timschumi** [comment]
This appears to break `luajit`, at least for me?

```
=> Fetching luajit...
[luajit/fetch] + git init --bare /home/tim/dev/serenity/Ports/luajit/luajit.git (nocd)
[luajit/fetch] Reinitialized existing Git repository in /home/tim/dev/serenity/Ports/luajit/luajit.git/
[luajit/fetch] + git -C /home/tim/dev/serenity/Ports/luajit/luajit.git config core.autocrlf false (nocd)
[luajit/fetch] + git -C /home/tim/dev/serenity/Ports/luajit/luajit.git worktree prune (nocd)
[luajit/fetch] + git -C /home/tim/dev/serenity/Ports/luajit/luajit.git fetch --tags https://luajit.org/git/luajit.git v2.1.0-beta3 (nocd)
[luajit/fetch] From https://luajit.org/git/luajit
[luajit/fetch]  * tag                 v2.1.0-beta3 -> FETCH_HEAD
=> Patching luajit...
[luajit/patch_internal] + git am --keep-cr --keep-non-patch /home/tim/dev/serenity/Ports/luajit/patches/0001-Recognize-Serenity-as-POSIX.patch
[luajit/patch_internal] error: patch failed: src/lj_arch.h:74
[luajit/patch_internal] error: src/lj_arch.h: patch does not apply
[luajit/patch_internal] hint: Use 'git am --show-current-patch=diff' to see the failed patch
[luajit/patch_internal] hint: When you have resolved this problem, run "git am --continue".
[luajit/patch_internal] hint: If you prefer to skip this patch, run "git am --skip" instead.
[luajit/patch_internal] hint: To restore the original branch and stop patching, run "git am --abort".
[luajit/patch_internal] hint: Disable this message with "git config advice.mergeConflict false"
[luajit/patch_internal] Applying: Recognize Serenity as POSIX
[luajit/patch_internal] Patch failed at 0001 Recognize Serenity as POSIX
```

**Comment by timschumi** [comment]
This was a completely fresh clone of serenity, so not sure what happened that I already had a patched luajit repository there, but it indeed works fine after cleaning once again. Sorry for the confusion!

**Review by timschumi — APPROVED** [review]

**Pull request merged**
