### PR TITLE
Base: Add czech language keymaps

### PR DESCRIPTION
**Pull request by Zorby-dev**
_disclaimer: my first pr_

Adds the following keymaps:

- cs-cz (Czech QWERTY)
- cs-cz-qwertz (Czech QWERTZ)
- cs-cz-programmers (US keymap with czech glyphs accessible in combination with alt gr)

### CODE REVIEW

**Comment by drunderscore** [comment]
Awesome! The category for these commits should be `Base` instead though.

**Comment by Zorby-dev** [comment]
Oh ok, I wasn't sure, so i searched for other keymap related rps and a lot of them had this format. Thanks for letting me know!

**Comment by drunderscore** [comment]
Ah, certainly my bad -- it seems both categories have been used previously... someone else may chime in later, but for now it's fine the way it is :^)

**Comment by bgianfo** [comment]
For the `cs-cz-programmers` keymap, please add the description you included in the PR description, in the actual commit message. Just so we have some history of what the intended difference actually is.

Everything looks good besides that. 👍

**Comment by Zorby-dev** [comment]
Thanks, should be done now.

**Pull request merged**
