### PR TITLE
LibCore+shot: Fail on negative delay values

### PR DESCRIPTION
**Pull request by abyesilyurt**
Return an error on a negative delay option instead of underflowing.

### CODE REVIEW

**Review by alimpfard — APPROVED** [review]
Something in me says "why not generalize this since `u8`, `u16` and `u64` are gonna look the same, but let's not add further complexity where it's not needed.

**Comment by abyesilyurt** [comment]
> Something in me says "why not generalize this since `u8`, `u16` and `u64` are gonna look the same, but let's not add further complexity where it's not needed.

Thanks, I am trying to keep my PRs small for now, as I am getting used to the project guidelines/idioms etc.
I will see what I can do in the background though.

**Comment by alimpfard** [comment]
Nah, I don't think generalising these is particularly useful (not until we actually hit a use-case for it)
your PR is good as-is :)

**Comment by abyesilyurt** [comment]
Can we merge now? :)

**Pull request merged**
