### PR TITLE
Libraries: Use default constructors/destructors in LibJS

### PR DESCRIPTION
**Pull request by ldm5180**
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#cother-other-default-operation-rules

"The compiler is more likely to get the default semantics right and
you cannot implement these functions better than the compiler."

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
We've ignored this in a couple of PRs, but please don't add new copyright lines for trivial changes like these. The copyright header should be an indicator of who has put significant work into a certain file, and while moving to default ctors is certainly a nice change, I don't think a copyright update is justified - in this case it just adds a bunch of noise to the diff, and assigns generic "the SerenityOS developers" copyright to countless individual files. If there already is a generic SerenityOS developers copyright, you can update the year of that if you want.

**Comment by ldm5180** [comment]
> We've ignored this in a couple of PRs, but please don't add new copyright lines for trivial changes like these. The copyright header should be an indicator of who has put significant work into a certain file, and while moving to default ctors is certainly a nice change, I don't think a copyright update is justified - in this case it just adds a bunch of noise to the diff, and assigns generic "the SerenityOS developers" copyright to countless individual files. If there already is a generic SerenityOS developers copyright, you can update the year of that if you want.

Sure. I can remove those.

**Comment by ldm5180** [comment]
@linusg Done.

**Review by linusg — APPROVED** [review]
Thanks!

**Pull request merged**
