### PR TITLE
Ports: Update zlib to 1.2.12

### PR DESCRIPTION
**Pull request by Sebbl0508**
This fixes building (for example) the cmake port.  
Previous version 1.2.11 returned 404 when trying to download.

### CODE REVIEW

**Comment by BertalanD** [comment]
Hi! Welcome to Serenity! 🎉

Please squash the AvailablePorts.md change into your first commit.

**Review by BertalanD — APPROVED** [review]
Thanks, LGTM.

**Comment by EWouters** [comment]
https://github.com/madler/zlib/commit/05796d3d8d5546cf1b4dfe2cd72ab746afae505d fixes a bug in this version ([Discord](https://discord.com/channels/830522505605283862/830807158047244329/958423108367314984)).

**Comment by BertalanD** [comment]
The upstream fix has been backported in #13336.

**Pull request merged**
