### PR TITLE
Kernel+Userland: Remove KCOV instrumentation

### PR DESCRIPTION
**Pull request by supercomputer7**
Nobody was testing this code for a very long time as the author of this code is not an active contributor anymore.

We usually don't remove code just because the code author is not active anymore.
However, there are multiple reasons for removing this:
- The code is presumably incomplete, which means there's no userspace code to handle KCOV instrumentation (fuzzing) from the userland side.
- It has code patterns which are in general bad. For example, the class of KCOVInstance exposes a method to grab its spinlock from anywhere. Also, it uses a LockRefPtr for a VMObject. LockRefPtrs are designated to be removed as soon as possible, so either we figure out how to fix this for this piece of code, or remove it completely.
- It simplifies our code in a few places because we also remove an ifdef called ENABLE_KERNEL_COVERAGE_COLLECTION with this removal.

### CODE REVIEW

**Comment by supercomputer7** [comment]
Just to be clear, KCOV was added in July 2021 in this commit:
https://github.com/SerenityOS/serenity/commit/83f88df7574c41bd3c7255d7f46930eef6744b6b
But since then nobody touched the code except for maintenance work on this. This is why this is presumably dead code.

**Comment by supercomputer7** [comment]
#1025 should be updated once this is merged and KCOV is removed.

**Comment by bgianfo** [comment]
Uhh no thanks, please don't remove this. This is a dependency of us being able to be use syzkaller to actually fuzz the kernel boundary.

**Comment by supercomputer7** [comment]
> Uhh no thanks, please don't remove this. This is a dependency of us being able to be use syzkaller to actually fuzz the kernel boundary.

Sorry, Just saying "no thanks, please don't remove this" without contradicting my reasons seem like a weak argument.
I want to see a userland program that is using this feature. There's none of it.
Anyway, I have my reasons, I wrote those both in the commit message as well as for the PR description. We don't have syzkaller working on our OS, this code does not match the code style of our project and nobody is pushing on that front for more than a year.

We are pushing towards removing the LockRefPtrs and this piece of code has at least one LockRefPtr, as well as other quite bad patterns in its code. `git-revert` can always bring this code back, when we need it.

I don't think this is a discussion we should do on GitHub. Please respond to me in the discord server.

**Comment by awesomekling** [comment]
The KCOV code seems non-intrusive, so I don't see the value in removing it if Brian intends to continue working on it.

The value of working towards syzkaller support is higher than the value of removing four easy-to-maintain `#ifdef`s IMO.

**Comment by supercomputer7** [comment]
> The KCOV code seems non-intrusive, so I don't see the value in removing it if Brian intends to continue working on it.
> 
> The value of working towards syzkaller support is higher than the value of removing four easy-to-maintain `#ifdef`s IMO.

I am not against keeping it if someone works on it (if it comes up to be @bgianfo then that's cool), but essentially for almost 2 years nobody really touched this piece of code and it lacks both at the code style criteria (the key here is that nobody improves this piece of code) and also at good concurrency patterns (as it uses `LockRefPtr`s which is a can of worms).

I haven't seen any real effort to port `syzkaller` in a while (last comment in #1025 was from May 3, 2022), hence it's safe to assume that nobody actually tests this piece of code nor use it for something else.

This is my primary reason to remove this. I will accept your decision regardless of merging this or not, but keeping dead code (or code that nobody uses and doesn't improve over time) was never a thing we actually do.

**Comment by supercomputer7** [comment]
Let's wait about this. I will see how I can help with porting `syzkaller` so this can be useful.

**Pull request closed without merging**
