### PR TITLE
Base: Add new bitmap font Tiny

### PR DESCRIPTION
**Pull request by Xexxa**
screenshotTiny

### CODE REVIEW

**Comment by awesomekling** [comment]
What is the purpose of this font?

**Comment by Xexxa** [comment]
> What is the purpose of this font?

The purpose is to write really small text. Personally I mainly use really small font sizes in pixel-art(I know Pixel Paint does not have an "Insert text" tool yet). But I'm sure there is a lot of other uses.

The font is mainly **decorative** because it is really hard to read. Honestly, I really like tiny fonts and I thought it was missing from SerenityOS. But I stopped at ~150 glyphs to see if it gets merged or not. :)

**Comment by Xexxa** [comment]
screenshotTinyRegular6runic

**Comment by awesomekling** [comment]
All right. But please remove the merge commit :)

**Comment by Xexxa** [comment]
> All right. But please remove the merge commit :)

I tried. I messed up. Felt better to close the PR then wasting resources for all the checks. Is it acceptable to create a clean new pull request?

(obviously I'm much better at spending hours drawing glyphs based on the Unicode character code charts then GIT)

**Pull request closed without merging**
