### PR TITLE
Ports+Toolchain+LibC: Update the LLVM port to version 13.0.0

### PR DESCRIPTION
**Pull request by BertalanD**
This PR updates the LLVM port to 13.0.0, and adds support for the `$arch-pc-serenity` frontend.

Because of the recent `mmap()` fixes by Andreas (32aa37d5dcfedf90a14696a5a6eec76bc029cffa), the LLD linker now outputs files correctly, so we no longer have to rely on the `gcc` port for linking.

I have tested this port with `i686-GNU`, `i686-clang` and `x86-64-GNU` builds, and all seem to flawlessly (although slowly) compile `/home/anon/Source/little`. Furthermore, using `AK` and C++ standard functions also works.

This PR touches a couple of other places beside the port:
- The LLVM patch in `Toolchain/Patches` has been updated to work with no sysroot specified, and with `libstdc++` for the standard library.
- A new `errno` value has been added (`ENOTRECOVERABLE`) to support LLVM's use of `std::errc::state_not_recoverable`.
- `bits/stdint.h` has been updated to use the correct suffix for `UINT64_C` on x86_64, and the correct maximum value for `(u)intptr_t`.
- The C++ standard library and its headers are now copied into the disk image. This was necessary because GCC lacks support for a feature which allows `libc++` to use our less-than-complete LibC. This means that — unless we want to jump through many hoops — we have to use the C++ standard library built on the host.

This image shows `clang++` successfully compiling (a modified version) of `little` on `x86_64-GNU`:
Grimshot 2021-11-21 13-04-43

### CODE REVIEW

**Comment by BertalanD** [comment]
Change since initial push:
- Fixed build failure with the Clang toolchain due to the use of the GCC-specific `__UINT64_C`.

**Comment by BertalanD** [comment]
Change since last push:
- Re-add implicit `-lm` when linking C++ code.

**Comment by BertalanD** [comment]
Rebased and force pushed to run CI again. It looks like we encountered a [download failure](https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=5012&view=logs&jobId=29e09774-1db5-5934-d7f9-e9dc4ea7db74&j=29e09774-1db5-5934-d7f9-e9dc4ea7db74&t=4be71d12-8aa1-5eec-91bd-78a24d15d2ce).

**Comment by BertalanD** [comment]
Change since last push:
- Changed the `SIZE_MAX` macro to a less dodgy value. These macros have to be understood by the C preprocessor, so the `((size_t)-1)` casting magic is not ideal. This prevents a `static_assert` from firing in the LLVM build.

From [POSIX](https://pubs.opengroup.org/onlinepubs/009604599/basedefs/stdint.h.html):
> Each instance of these macros shall be replaced by a constant expression suitable for use in #if preprocessing directives, and this expression shall have the same type as would an expression that is an object of the corresponding type converted according to the integer promotions.

**Comment by BertalanD** [comment]
Removed `use-i686-in-filenames.patch` which, contrary to its purpose, actually prevented the runtime files from being picked up by the compiler.

**Review by timschumi — APPROVED** [review]
It builds Lagom! :^)

**Comment by BertalanD** [comment]
Changes since the last push:
- Rebased.
- Split the `SIZE_MAX` change into a separate commit and added explanations for the change.
- Changed `libLLVM` to be statically linked, as otherwise a large part of the run time is spent in DynamicLoader.

**Pull request merged**
