### PR TITLE
Tests/LibWeb: Move LibWeb test frames to their own directory

### PR DESCRIPTION
**Pull request by trflynn89**
I was recently writing a test that involved iframes and came across this little annoyance.

We currently have a handful of iframe tests whose sources are in the "input" directory. This means they get run as their own tests, when they are really just helper files. We've had to add empty test expectation files for these "tests", and invoke a dummy test() method just to keep the test runner happy.

Instead, move them to their own directory so the test runner does not see them at all.

### CODE REVIEW

**Comment by kalenikaliaksandr** [comment]
Since we already have [config](https://github.com/SerenityOS/serenity/blob/master/Tests/LibWeb/TestConfig.ini) to specify "Skipped" tests maybe we should also added "Ignored" there, instead of moving iframe files into `LibWeb/Tests/frames` 🤔 It would allow to keep these supplemental files in the same directory with tests which seems more convenient.

Also besides frames, we likely want to ignore other kind of files. I suppose we already have some dummy SVGs.

**Comment by trflynn89** [comment]
I had actually implemented "Ignored" originally, but then decided I'd probably find it more annoying to have to update that file for each iframe test rather than just putting the frame somewhere else. I don't feel super strongly about it though.

> Also besides frames, we likely want to ignore other kind of files. I suppose we already have some dummy SVGs.

I can rename the directory to something other than "frames", if there's more .html file types we want to put in there.

**Comment by kalenikaliaksandr** [comment]
> I don't feel super strongly about it though.

I don't feel strongly about that easier so separate directory approach seems fine for me as well.

> I can rename the directory to something other than "frames", if there's more .html file types we want to put in there.

for example we added expectations for some SVGs there are used by html files in this commit https://github.com/SerenityOS/serenity/commit/2ede299b4ac9405b248910ac06e3dc55db2b0bee#diff-f7165a45d9eb763c02fd32dbc5a6976427ea942e2c8121fe29be681f159bea3b That could have been avoided if we had mechanism to ignore files.

**Comment by trflynn89** [comment]
I've changed the name of the directory to "data" and added a commit for those SVGs.

**Review by kalenikaliaksandr — APPROVED** [review]

**Pull request merged**
