### PR TITLE
AK: Prefer VERIFY_NOT_REACHED in ByteBuffer

### PR DESCRIPTION
**Pull request by nico**

### CODE REVIEW

**Comment by nico** [comment]
@BertalanD This was from #13954 – any reason not to use the macro here?

**Comment by BertalanD** [comment]
The commit that added this was a workaround for a GCC regression that caused the compiler not to understand that this invariant is always true, leading to a false positive diag.

My reasoning for not going with an assert: this doesn't generate any extra code and quiets the warning even if we were to disable assertions.

**Comment by nico** [comment]
Well, leaving it to maintainers if they want this or not then :)

**Comment by awesomekling** [comment]
> My reasoning for not going with an assert: this doesn't generate any extra code and quiets the warning even if we were to disable assertions.

To clarify: `VERIFY*` are explicitly not assertions, that's why they're not called `ASSERT*`. :)

If someone wants to add classic assertions that can be compiled out, they are welcome to add an `ASSERT()` mechanism.

**Pull request merged**
