### PR TITLE
Base: Update our earth emoji to be more scientifically accurate

### PR DESCRIPTION
**Pull request by Xexxa**
After an earlier vote in [serenityos.social](https://serenityos.social/@xexxa/109580173370382564) a majority voted that we should replace our current propaganda depictions of earth with a more scientifically accurate depiction of earth, flat and beautiful. This also decrease the file size with ~50%!

🌍 - U+1F30D GLOBE SHOWING EUROPE-AFRICA
🌎 - U+1F30E GLOBE SHOWING AMERICAS
🌏 - U+1F30F GLOBE SHOWING ASIA-AUSTRALIA

**Old emoji:**
old

**New emoji:**
new

**Important scientific notice:**

As is well known: nobody has passed the edge of earth(and returned) so any depiction of the earth from her sides is pure speculation. These are artistic depictions of the dominating continent close to the earth edge from different angles. It's also a well known fact that nobody has dug deep enough to see how thick earth it is, this is also drawn with some artistic freedom.

### CODE REVIEW

**Comment by Hendiadyoin1** [comment]
The elephants and the tortoise are missing

**Comment by Xexxa** [comment]
> The elephants and the tortoise are missing

Copying my answer from [https://serenityos.social/@xexxa/109580173370382564](https://serenityos.social/@xexxa/109580173370382564):
> Don't be silly, we should not mix science with fiction... It's a well known fact that nobody has dug deep enough to see what lies beneath the earth. ⛏️

**Review by drunderscore — CHANGES_REQUESTED** [review]
This will not be merged as-is. Everyone knows the Earth is two pixels tall -- the top hemi-rectangle, and the bottom hemi-rectangle (for those "spherical earth" believers, those are known as "hemispheres".)

Incredibly disheartening to see such misinformation attempt to be merged into the project.

**Comment by Xexxa** [comment]
1 April is over(with some margin) so time to close this one :^)

**Pull request closed without merging**
