### PR TITLE
Ports: Fix binutils and gcc ports

### PR DESCRIPTION
**Pull request by itamar8910**
I don't actually know what lead to their sudden breakage, but this fixes them.

### CODE REVIEW

**Comment by awesomekling** [comment]
Hm, that's weird, I just built these ports last night and they worked fine.
Regardless, my instinct says this may have something to do with adding `sysconf()` recently.
Perhaps gcc/binutils is trying to get the page size from `sysconf(_SC_PAGESIZE)` but that doesn't work so it falls back to its own `getpagesize()` for whatever reason.

**Comment by itamar8910** [comment]
@awesomekling, yep you had it right. They checked whether `_SC_PAGESIZE` was defined, and since it wasn't they brought their own `getpagesize`.

**Comment by awesomekling** [comment]
Nice!

**Comment by nico** [comment]
After the enum addition, _SC_PAGESIZE still isn't defined. If the port is still broken, we also need a `#define _SC_PAGESIZE _SC_PAGESIZE` I suppose.

**Pull request merged**
