### PR TITLE
LibJS: rename m_string to m_name, and add is_valid() in Identifier

### PR DESCRIPTION
**Pull request by howar6hill**

### CODE REVIEW

**Comment by howar6hill** [comment]
I intend to change the following functions
https://github.com/SerenityOS/serenity/blob/e07f50c39860ec006a7110dc13ea7001a6a54fc9/Libraries/LibJS/Interpreter.h#L55-L56
to
```C++
Value get_variable(const Identifier& name);
void set_variable(Identifier name, Value);
```
since not all strings are valid identifier.

**Comment by awesomekling** [comment]
It's the parser's job to produce a valid AST. This function is not necessary, as we should never construct an invalid `Identifier` node.

**Comment by howar6hill** [comment]
> I intend to change the following functions
> 
> https://github.com/SerenityOS/serenity/blob/e07f50c39860ec006a7110dc13ea7001a6a54fc9/Libraries/LibJS/Interpreter.h#L55-L56
> 
> to
> 
> ```c++
> Value get_variable(const Identifier& name);
> void set_variable(Identifier name, Value);
> ```
> 
> since not all strings are valid identifier.

Is this change needed?

**Comment by howar6hill** [comment]
> It's the parser's job to produce a valid AST. This function is not necessary, as we should never construct an invalid `Identifier` node.

`is_valid()` should be removed.

**Comment by awesomekling** [comment]
> > I intend to change the following functions
> > https://github.com/SerenityOS/serenity/blob/e07f50c39860ec006a7110dc13ea7001a6a54fc9/Libraries/LibJS/Interpreter.h#L55-L56
> > 
> > to
> > ```c++
> > Value get_variable(const Identifier& name);
> > void set_variable(Identifier name, Value);
> > ```
> > 
> > 
> > since not all strings are valid identifier.
> 
> Is this change needed?

Let's not make this change. It forces you to provide an AST node if you want to look up a variable. This will make common development tasks like adding debug logging unnecessarily complicated, for example if you just want to say
```cpp
dbg() << interpreter.get_variable("foo");
```

**Pull request closed without merging**
