### PR TITLE
Base: Add new font Katica Bold Italic 10, add Mathematical Alphanumeric Symbols to font Katica Regular 10, add 2713, 2714 to Katica Bold 10, add 1f785-1F78B, 1F517 to Katica Bold 12, fix glyphs in Katica Bold 10

### PR DESCRIPTION
**Pull request by Xexxa**
## Katica Bold Oblique 10
For your bold italic needs. :^)

0020-007E
https://www.unicode.org/charts/PDF/U0000.pdf

katica-bold-italic-10

## Katica Regular 10
**Mathematical Alphanumeric Symbols**
1D522, 1D525, 1D52A, 1D51C, 1D4EA, 1D4F8, 1D4F7, 1D4FC, 1D4FD,
1D516-1D51C
https://www.unicode.org/charts/PDF/U1D400.pdf

## Katica Bold 10

**Dingbats**
2713, 2714
https://www.unicode.org/charts/PDF/U2700.pdf

**Remove painted parts outside of view**
A few glyphs is "cut" with painted part outside of the view.
0023, 0026, 0040, 004B, 004D, 004E, 004F, 0051, 0052, 0057,
006D, 0077

## Katica Bold 12

**Geometric Shapes Extended**
1f785-1F78B
https://www.unicode.org/charts/PDF/U1F780.pdf

**Miscellaneous Symbols and Pictographs**
1F517
https://www.unicode.org/charts/PDF/U1F300.pdf

As always, coverage is found on https://fonts.serenityos.net/

### CODE REVIEW

**Comment by Xexxa** [comment]
Ok, I'm not 100% sure about the naming for the new font.

In the moment it made sense naming it italic because a oblique slope is often called italic but in the font picker it says oblique so I'm not sure it's worth the potential confusion or not... 🤔

**Comment by djwisdom** [comment]
Notify Discord check emitted this -> `Message : { title: [ 'Must be 256 or fewer in length.' ] }`
regardless, lgtm. 
Another quality contribution you have here mate :^)

**Comment by Xexxa** [comment]
Name changed to Katica Bold Oblique and filename changed to KaticaBoldOblique10.font.

**Comment by linusg** [comment]
> Notify Discord check emitted this -> Message : { title: [ 'Must be 256 or fewer in length.' ] }

cc @networkException :)

**Pull request merged**
