### PR TITLE
LibWeb+LibHTTP: Support multiple Set-Cookie response headers

### PR DESCRIPTION
**Pull request by SeekingBlues**

### CODE REVIEW

**Comment by tomuta** [comment]
This feels like it should be solved more generically for all headers, not just `Set-Cookie`. Most (if not all) can appear multiple times as per the http spec.

**Comment by SeekingBlues** [comment]
Okay. I will fold the headers with the same name together by joining them with a comma. However, the `Set-Cookie` header should still be JSON serialized because of parsing reasons. ([RFC7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2))

**Comment by tomuta** [comment]
> Okay. I will fold the headers with the same name together by joining them with a comma. However, the `Set-Cookie` header should still be JSON serialized because of parsing reasons. ([RFC7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2))

Interesting, wasn't aware of this one exception.

**Comment by alimpfard** [comment]
How about exposing the headers as a `HashMap<String, Vector<String>>` and have the application worry about what multiple values for a header means?
I'm not too sure if it's LibHTTP's job to interpret these headers for the application

**Comment by SeekingBlues** [comment]
Yes, I have thought of that. But LibHTTP is not interpreting the headers. Instead, it is transforming multiple headers with the same name into one without understanding what they mean or changing the semantics. The [spec](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2) says that "A sender MUST NOT generate multiple header fields with the same field name in a message unless the entire field value for that header field is defined as a comma-separated list" (with the exception of `Set-Cookie`), which means that the folded headers should be well-defined and semantically equivalent to the original message. So I think `HashMap<String, Vector<String>>` might not be necessary here.

**Comment by alimpfard** [comment]
Sorry I managed to forget about this somehow :/

**Comment by alimpfard** [comment]
Continuing in #10966 since I can't push to this branch.

**Pull request closed without merging**
