### PR TITLE
New args parser

### PR DESCRIPTION
**Pull request by bugaevc**
Here's the new, completely rewritten `CArgsParser`. Hope you like it!

It properly supports and distinguishes between:
* Positional arguments (required or not)
* Options

Options can be short and/or long.

The API allows you to add custom option and argument types (see `nl` for an example). A few types are pre-implemented for convenience:
* Boolean options (take no value)
* String and integer options (take a required value)
* String and integer arguments
* Vector-of-string arguments

The general pattern of using the new API is:

```cpp
bool some_option = false;
const char* some_stirng = "default";

CArgsParser args_parser;
args_parser.add_option(some_option, "Do some useful stuff", "do-stuff", 's');
args_parser.add_positional_argument(some_string, "A very important string", "some-string");
args_parser.parse(argc, argv);

// Use some_option and some_string here.
```

I ported all the old `CArgsParser` users, and some manual `getopt()` users (namely, `copy` and `paste`). I could have broken things while porting them, so cc @zlotny @rburchell @balatt @Quaker762

Some more stuff that either uses `getopt()` or parses args manually remains to be ported at some other time, because I gotta run home :smile:

### CODE REVIEW

**Comment by bugaevc** [comment]
On second thought, maybe this isn't that much of an improvement over the old API? What do you think?

**Comment by awesomekling** [comment]
Seems like an upgrade over the old `CArgsParser` although the subclassing `CArgsParser::Option` stuff is kinda awkward.

**Comment by bugaevc** [comment]
It is kinda awkward! Got any better ideas?

I wanted it to be type-safe with respect to the value and to not make it exhaustive (so not `GVariant`).

**Comment by bugaevc** [comment]
Hmm, maybe we could do with storing a `Function<bool(const char*)>`

**Comment by awesomekling** [comment]
> Hmm, maybe we could do with storing a `Function<bool(const char*)>`

Oh that sounds a lot nicer! :)

**Comment by bugaevc** [comment]
Done! Turned out a lot nicer indeed.

Plus, I've ported a few more utilities from `getopt()`.

**Comment by awesomekling** [comment]
Much better! Let's merge it :)

**Pull request merged**
