### PR TITLE
Base: Update Chillychilly Theme for better aesthetics

### PR DESCRIPTION
**Pull request by djwisdom**
### Before and after comparison
Chillychilly-1024-r1 

Chillychilly-1024-r2

### CODE REVIEW

**Comment by djwisdom** [comment]
"for better aesthetics"

**Comment by linusg** [comment]
I meant in the commit message :)

**Comment by djwisdom** [comment]
Yup, saw that, and I updated the commit message. I didn't know what was going on in my head that time since I just woke up when I submitted the PR. :^)

**Comment by linusg** [comment]
haha, no worries!

**Pull request merged**
