### PR TITLE
Base: Add Lucidity Bold font

### PR DESCRIPTION
**Pull request by djwisdom**
Supplement Lucidity Regular font

image

### CODE REVIEW

**Review by Xexxa — CHANGES_REQUESTED** [review]
Latin-1 supplement looks amazing in bold!

There is scripts in this PR that isn't bold, like: Lisu and Unified Canadian Aboriginal Syllabics.

All the scripts in a bold font should be... bold.

Emojis, pictographs and other symbols that is not part of a writing system can stay the way they are.

**Comment by djwisdom** [comment]
Removed Miscellaneous Symbols since there's no point making them bold.
The ones mentioned previously now have their weight in bold.

**Comment by Xexxa** [comment]
> Removed Miscellaneous Symbols since there's no point making them bold.

> Emojis, pictographs and other symbols that is not part of a writing system **can stay the way they are**.

Agree, that was my point, perhaps I wasn't clear enough. ;-)

**Review by Xexxa — APPROVED** [review]
lgtm

**Pull request merged**
