### PR TITLE
LibWeb: Make`Web::Layout::overflow_value_makes_box_a_scroll_container()` static.

### PR DESCRIPTION
**Pull request by Popaulol**
Now serenity should build again ;)

### CODE REVIEW

**Comment by Popaulol** [comment]
The moment when symbols are so long, accurately describing what you are doing in the commit message becomes impossible.

**Review by timschumi — CHANGES_REQUESTED** [review]
This just seems to be an internal helper, so it should likely be made `static` instead of adding it to the header file.

**Comment by Popaulol** [comment]
Yeah, I'll ammend the commit.

> This just seems to be an internal helper, so it should likely be made `static` instead of adding it to the header file.

**Comment by Popaulol** [comment]
So uhm, how the hell should this commit be named, since the symbol name is so long, you can't really fit it within the 72 character limit.

**Comment by Popaulol** [comment]
So I'll be closing this pr now, as i've noticed i've fucked up the commit history here, with two seperate commits, where the second should've been an amend an squashing that isn't worth the time.

**Pull request closed without merging**
