### PR TITLE
LibGfx/JBIG2: Add support for pattern and halftone segments

### PR DESCRIPTION
**Pull request by nico**
A pattern dictionary stores n bitmaps with the same dimensions w x h.
They're stored in a single bitmap of width `n * w` that's then cut
into n stripes.

A halftone region stores a grayscale bitmap and a linear coordinate
system the grayscale bitmap is in.  The grayscale bitmap is overlaid
the halftone region using the coordinate system, and each sample in
the grayscale bitmap is used as an index into a pattern dictionary
and the bitmap at that index is drawn at the current location.
This allows for efficient compression of ordered dithering
(but not error-diffusion dithering).

This does not yet implement halftone region decoding for MMR bitmaps.

The halftone region decoding procedure is the only way to call the
generic region decoding procedure with a skip pattern. This does
include code to compute the skip pattern, but support for that
is not yet implemented in the generic region decoding procedure,
so it'll error out when encountered. (I haven't yet found a file
using this feature, not a way to create such a file yet.)

---

Pattern/halftone are the two big remaining segments from the original JBIG2 spec, so this is a good step towards complete JBIG2 support.

No test yet, since I haven't found a way to make one yet. Hopefully I'll make a test input later.

Part of the motivation is to implement all generic region decoding procedure inputs (see skip pattern remark above) before I try to optimize that.

For amb_1.jb2 from https://git.ghostscript.com/?p=tests.git;a=tree;f=jbig2;h=8a7abaf842435e204c1ff1dbeed10826bf24afe6;hb=refs/heads/master , this is the pattern dictionary (this is 16 4x4 bitmaps):

pattern-0_skip_not pdf

This is the 4bpp grayscale image:

image_skip_not pdf

The halftone grid in that file is aligned with the page grid, resulting in this decoded image:

image_skip_not pdf

While this is rarely used, it _is_ sometimes hit in practice. For https://fraser.stlouisfed.org/files/docs/publications/employment/1970s/1970-1974/empl_081971.pdf here's a before/after:

empl_081971.pdf_p6_before

empl_081971.pdf_p6_after

empl_081971.pdf_p10_before

empl_081971.pdf_p10_after

### CODE REVIEW

**Comment by nico** [comment]
Here are the bitplanes for the grayscale image, how they're stored in the file, in the order they're stored in the file:

bitplane-3_skip_nopdf
bitplane-2_skip_nopdf
bitplane-1_skip_nopdf
bitplane-0_skip_nopdf

Here's what they look like after undoing the gray coding (first one is unchanged):
bitplane-3_skip_nopdf
bitplane-2degray_skip_nopdf
bitplane-1degray_skip_nopdf
bitplane-0degray_skip_nopdf

The degrayed version is how they are combined to form the final grayscale image.

The stored, gray-coded images have larger areas of contiguous color, which presumably helps compression.

**Comment by nico** [comment]
Also fixes

```
% time Build/lagom/bin/pdf --debugging-stats ~/Downloads/Modern-Electronics-1990-02.pdf                                          
page number 76 / 76
11 times: Internal error while processing PDF file: JBIG2ImageDecoderPlugin: Cannot decode pattern dictionary yet
    on pages: 3 9 12 37 45 51 57 59 66 71 72
```

on https://www.worldradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1990-02.pdf

**Review by leroy182 — COMMENTED** [review]
Thanks

**Review by leroy182 — COMMENTED** [review]
Thanks

**Pull request merged**
