### PR TITLE
Meta: Add AlignConsecutiveBitFields and AlignConsecutiveMacros formating flags

### PR DESCRIPTION
**Pull request by Hendiadyoin1**
Also sorts .clang-format alphabetically

----

For the maintainer who merges this
It might be a good idea to add this commit to a `.git-blame-ignore-revs` file
(as well as all previous pure formatting commits)

### CODE REVIEW

**Comment by nico** [comment]
why though

**Comment by bgianfo** [comment]
> why though

Yea I agree with nico.

Leon, it's up to you as the contributor to provide an argument for why this is a good thing to do. It would have been nice if that was provided in the commit messages / PR description. 

I don't see much value in these rules personally, and in some cases, it makes things look awkward and out of place. Perhaps I'm missing some argument where this is a good thing?

**Comment by Hendiadyoin1** [comment]
I think it boils down to personal preference

I think it is better to have related values line up with each other;
This makes it easier to add them up (mainly BitFields) or spot inconsistencies (mainly Macros)

For BitFields this is quite nice, because they often come from hardware related code, where names vary length a lot and being able to follow just a simple line of values to check, rather than having to jump left and right depending how long the field name is.

If you agree I can add a more thought over version of this text in a more objective tone to the commit message

**Comment by linusg** [comment]
Yeah, let's not do this. Modern C++ should make use of fewer macros and more constexpr variables anyway.

**Pull request closed without merging**
