### PR TITLE
Base: Add more emoji (Emoji 16 edition)

### PR DESCRIPTION
**Pull request by Xexxa**
These are the current Emoji 16 alpha emoji.

x67-screenshot

🫩 - U+1FAE9 FACE WITH BAGS UNDER EYES
🫟 - U+1FADF SPLATTER
🪉 - U+1FA89 HARP
🫆 - U+1FAC6 FINGERPRINT
🫜 - U+1FADC ROOT VEGETABLE
🪾 - U+1FABE LEAFLESS TREE
🪏 - U+1FA8F SHOVEL
🇨🇶 - U+1F1E8_U+1F1F6 CQ SARK

https://www.unicode.org/review/pri498/pri498-emoji-recently-added-v16-0%CE%B1.pdf

### CODE REVIEW

**Comment by Xexxa** [comment]
Is the issues :ciflakes:? 🤔

**Comment by ADKaster** [comment]
> Is the issues :ciflakes:? 🤔

I don't think we can add these emoji until we start downloading `https://www.unicode.org/Public/emoji/16.0/emoji-test.txt`

Currently we still only download the file for version 15.1, same as our UCD data.

**Comment by trflynn89** [comment]
Putting these in emoji-serenity.txt is fine until Unicode 16 is released, but I think the issue is the last line::
```
U+1F1E8_U+1F1F6 CQ SARK
```

There should not be an underscore between the code points, there should just be a space:
```
U+1F1E8 U+1F1F6 CQ SARK
```

**Comment by Xexxa** [comment]
> Putting these in emoji-serenity.txt is fine until Unicode 16 is released, but I think the issue is the last line::
> 
> ```
> U+1F1E8_U+1F1F6 CQ SARK
> ```
> 
> There should not be an underscore between the code points, there should just be a space:
> 
> ```
> U+1F1E8 U+1F1F6 CQ SARK
> ```

Thanks, you are totally right! TBH it's not usual I make two major mistakes for a simple emoji PR but the "Meta/emoji-file-list.txt" addition to my workflow has thrown me a bit out of balance... :^)

**Pull request merged**
