### PR TITLE
LibWeb: Handle nullish this_value when creating idl functions

### PR DESCRIPTION
**Pull request by stelar7**
This allows http://wpt.live to run tests :D

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
Don't think this is the right way to do it; see discussion on Discord.

**Comment by linusg** [comment]
> linusg — Today at 20:57
> I don't think this is the right place to do this tbh
> we call this from within the JS_DEFINE_NATIVE_FUNCTION
> which receives a global object (aka realm), but has no way of knowing the original realm which is being passed around in the spec
> starting here: https://webidl.spec.whatwg.org/#interface-prototype-object
> The interface prototype object for a given interface interface and Realm realm is created as follows:
> and then we end up in
> To create an operation function, given an operation op, a namespace or interface target, and a Realm realm:
> and getting that realm is not possible once we're within the static cpp function AFAICT
> it's the global object of the NativeFunction
> the PR uses vm.current_realm(), which isn't right either

> stelar7 — Today at 21:17
> Where would be the correct place to do it then?

> linusg — Today at 21:22
> I don't know
> perhaps NativeFunction's function needs to receive some sort of third argument, passing the native function it's a part of?
> something like NativeFunction const& self
> I'm sure @Lubrsi has some ideas when he's back online

**Comment by stelar7** [comment]
Accidentally closed this.. But it seems like it wont be merged in its current form, so maybe it can just stay closed? @linusg

**Comment by linusg** [comment]
Actually, thinking about it again, this might just work, if calling a NativeFunctuin does the right thing and current_realm() can pick up that function's realm from the call stack.

AFK at the moment, will verify this later. Let's just merge it :)

**Pull request merged**
