### PR TITLE
LibKeyboard+Applets: Add click to cycle functionality to Keymap applet

### PR DESCRIPTION
**Pull request by fluxth**
This PR adds the click to cycle functionaility for the Keymap applet. (inspired by the KDE keymap applet)
The original keyboard settings panel is still accessible via a right click.

There's also some refactoring to unify `/etc/Keyboard.ini` file reading logic into `LibKeyboard`.

### CODE REVIEW

**Comment by Xexxa** [comment]
Yes, yes, yes!

I've even tried to implement "left click cycle, right click settings" for the keymap myself earlier. I so want this! ;-)

**Comment by fluxth** [comment]
Glad you liked it :)

I thought this could come in handy when I was working with Font Editor preview in multiple keymaps.

(Got to discover later through refactoring tho, that Serenity already has ALT+SHIFT as a switch keymap shortcut; Nevertheless, the more choices of switching keymaps, the better 😀)

**Comment by fluxth** [comment]
I'm putting this PR into draft for the time being, I've talked to the author of #13450 and decided to rebase onto his PR.

I'll reopen this when the rebase is complete and #13450 is merged.

**Comment by fluxth** [comment]
Not stale, waiting for #13450 to get merged.

**Pull request closed without merging**
