### PR TITLE
LibM: Switch sin() for fast sin()

### PR DESCRIPTION
**Pull request by faissaloo**
I made some mistakes the first time I implemented this, now that we have an application that uses these functions I was able to figure out the bug
image

### CODE REVIEW

**Comment by awesomekling** [comment]
How much faster is this? Are we losing precision? If so, how much?

**Comment by faissaloo** [comment]
Compared to real sine my implementation has a max error of 0.056, while compared to current the implementation this has a max error of 0.056009, in practice this error isn't an issue for your average application since all that matters is the wave pattern of sine being there and having the right scale (i.e: being accurate enough to draw circles), anything more than that will probably end in the programmer writing their own implementation anyway.  
In terms of speed, executing `sin(angle)` 125663706 times at `-O3` produces code that does the job in half the time (0.92s vs 0.52s).

**Comment by bugaevc** [comment]
Again, why don't we use the hardware instruction for this? I suspect it's both fast & correct.

**Comment by faissaloo** [comment]
@bugaevc Because the hardware instruction `fsin` is in fact neither [correct](https://randomascii.wordpress.com/2014/10/09/intel-underestimates-error-bounds-by-1-3-quintillion/) nor fast, there's a reason why it isn't used anymore.

**Comment by bugaevc** [comment]
Interesting; but that (their worst case: actual -5.0165576126683320235E-20, `fsin` -5.42101086242752217E-20) still sounds way more precise than the error of 0.056 you're mentioning.

**Comment by faissaloo** [comment]
@bugaevc Yes but that's not the point, the point is that it fails to provide *both* accuracy and speed and as a result shouldn't be considered, like I said, there's a reason why no one uses it anymore.  

I am favoring speed because I don't think a hugely accurate sine is necessary as part of a standard C library, the standard C library only requires enough to produce correct looking results for your typical usecase.

**Comment by bugaevc** [comment]
So how fast or slow it is then? Could you add it to your benchmark?

> In terms of speed, executing `sin()` 1256637060 times at `-O3` produces code that does the job in half the time (9.53s vs 5.19s).

**Comment by faissaloo** [comment]
@bugaevc 
My version: 5.25s
Current version: 10.14s
Hardware instruction based version: 44.62s

**Comment by awesomekling** [comment]
All right then.

**Pull request merged**
