### PR TITLE
LibJS: Basic implementation of most of Date's constructor arguments

### PR DESCRIPTION
**Pull request by nico**
The constructor with a string argument isn't implemented yet, but
this implements the other variants.

The timestamp constructor doens't handle negative timestamps correctly.

Out-of-bound and invalid arguments aren't handled correctly.

### CODE REVIEW

**Comment by nico** [comment]
The LibCore change is wrong, hold off for now.

**Comment by nico** [comment]
Ok, better.

**Comment by nico** [comment]
Maybe "New Game" could start a standard game always, and "new custom game" could remember what was filled in last time so that you only have to hit return to create a new game with a nondefault size?

**Comment by awesomekling** [comment]
Ok!

**Pull request merged**
