### PR TITLE
Everywhere: Add outln_if and warnln_if

### PR DESCRIPTION
**Pull request by Hendiadyoin1**
These are pendants to dbgln_if and should be compiled away when they are dissabled

### CODE REVIEW

**Comment by Hendiadyoin1** [comment]
Need to set semicolons....

**Review by linusg — CHANGES_REQUESTED** [review]
Seems fine for UserspaceEmulator, but the HexEditor changes should be using `dbgln_if()`, there's no reason to print this stuff to stdout.

**Comment by Hendiadyoin1** [comment]
changed that

**Comment by linusg** [comment]
Please remove the `HexEditor: Use outln_if` commit, that's not needed - we can go straight from `#if, outln()` to `dbgln_if()` :)

**Comment by Hendiadyoin1** [comment]
Then when the ci finishes this should be ready?

**Pull request merged**
