### PR TITLE
Update EventHandler.cpp

### PR DESCRIPTION
**Pull request by Chetax**
Changing shadowDom From candidate->parent() To candidate->parent_or_shadow_host().

### CODE REVIEW

**Comment by ADKaster** [comment]
Hi Chetan, welcome to the project. There's a few things this PR is missing.

1. It should link the relevant issue in the PR description  (#17801)
2. The commit title and description are very important to this project. Please force-push and fixup-squash your changes as described by the bot. If you aren't sure how to do that, have a look at this video as a guide: https://youtu.be/ElRzTuYln0M
3. The commit message should describe the purpose of the changes, with the commit description providing context.
4. The code looks like it was not formatted with clang-format-15. See CONTRIBUTING.md for instructions on how to properly format the code and setup your IDE to auto-format it with the project style.

If you have any questions, please ask them on our discord in the #development channel. Have a look at this post from one of our maintainers, Sam, for some additional context on why we structure code review this way: https://atkinssj.github.io/How-to-PR/

**Comment by Chetax** [comment]
Thanks SerenityOS/serenity For Your Guidance.

**Comment by Chetax** [comment]
Good Morning Andrew Kaster.
Sir I Am Chetan Padhen,A Second Year BTech Computer Engineering Student.
Sir I Am Beginner In SerenityOS ,So Sir Can You Please Tell How Can Start
To Success Contribute In SerenityOS.
My TechStack Are: C,C++,HTML,CSS, JavaScript.
Waiting for your reply.
Thanks & Regards
Chetan Padhen.

**Comment by ADKaster** [comment]
It looks like Andreas fixed this issue on master just now in the course of doing some other changes.

**Pull request closed without merging**
