### PR TITLE
LibCrypto: Implement little endian CRC using the slicing-by-8 algorithm

### PR DESCRIPTION
**Pull request by trflynn89**
This implements Intel's slicing-by-8 algorithm for CRC checksums (only little endian CPUs for now, as I don't have a way to test big endian).

The original paper for this algorithm seems to have disappeared, but Intel's source code is still available as a reference:

    https://sourceforge.net/projects/slicing-by-8/

As well as other implementations for reference:

    https://docs.rs/slice-by-8/latest/src/slice_by_8/algorithm.rs.html

Using the "enwik8" file as a test (100MB uncompressed, commonly used in benchmarks: https://www.mattmahoney.net/dc/enwik8.zip), decompression time decreases from:

    4.89s to 3.52s on Serenity (cold)
    1.72s to 1.32s on Serenity (warm)
    1.06s to 0.92s on Linux

### CODE REVIEW

**Comment by nico** [comment]
Any idea how this compares to the sse4.2 instruction? (Could add `-march=native` to the lagom `gunzip` to get away with a preprocessor check for 4.2. See https://www.corsix.org/content/fast-crc32c-4k for some details – I'd only try doing something basic like I did for arm and hope that that's enough, instead of going super all out.)

**Comment by nico** [comment]
(i.e. something like

```
#if defined(__SSE4_2__)
  … call __builtin_ia32_crc32qi() / __builtin_ia32_crc32di ...
#endif
```
)

**Comment by Hendiadyoin1** [comment]
We have a FIXME for that under the AARCH-CRC32 version

**Comment by trflynn89** [comment]
> We have a FIXME for that under the AARCH-CRC32 version

Nico wrote that FIXME a few days ago.

Unfortunately the GCC built-ins are hard-coded to use the Castagnoli polynomial, whereas we need to use the Ethernet polynomial for Deflate.

**Comment by Hendiadyoin1** [comment]
>There are two widely used polynomials, IEEE and Castagnoli. These parameterize the CRC-32 algorithm, and are sometimes known as crc32 and crc32c.
> The IEEE polynomial is used by Bzip2, Ethernet (IEEE 802.3), Gzip, MPEG-2, PNG, SATA, Zip and other formats.
> The Castagnoli polynomial is used by Btrfs, Ext4, iSCSI, SCTP and other formats.
> For better or worse, the hardware instruction computes CRC-32-Castagnoli, which means it's not relevant for e.g. Zip. 
<https://news.ycombinator.com/item?id=19405841>
Ah OK, so until we have SCSI or ext4 or btrfs

**Pull request merged**
