### PR TITLE
Libraries: Fixed LibVideo library for parsing, decoding, and displaying videos

### PR DESCRIPTION
**Pull request by xslendix**
I fixed https://github.com/SerenityOS/serenity/pull/5189 and plan to work on it in the future.

### CODE REVIEW

**Comment by tomuta** [comment]
You're going to need to remove the merge commit b61d0c9

**Comment by xslendix** [comment]
Oh, oops! How do I do that?

**Comment by ngc6302h** [comment]
> Oh, oops! How do I do that?
`git rebase --interactive '<first 7 or 8 characters of the hash of the **previous** commit of that you wish to edit plus ^>'

For example:
`git rebase --interactive '5f130aa3^'`

In the menu that appears, change `pick` to `edit` the commit you wish to edit. You can change more than one.
Exit the editor and HEAD will now be in the oldest commit you selected to edit. Now you can rebase instead of merge so that no commit is created. Once you finish, run ''git rebase --continue` to end the process.

Note that all this is to keep the "LibVideo: Fixed build" commit intact. If you don't care about destroying it you can do a git revert to before the merge :^)

**Comment by xslendix** [comment]
I think I did something wrong

**Pull request closed without merging**
