### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by BenWiederhake**
# Why?

Travis tries to extort Open Source: "Beg for mercy, or receive no more builds" https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
> Trial plans expire when you use all of our credits or after a year.

We need >10 minutes per build, and regularily reach 10 builds a day, so we would have to beg for "more credits" every two weeks or so.

# Proposed solution: Github Actions

This PR implements a "Github Actions workflow", by just moving all we would do on Travis over to GA.

- We need only a single *workflow*: "Just build and run and test it!"
- This workflow consists of a single *job*: "Just build and run and test it!"
- A single step in this job is called a *step*.

# Controversial stuff

## Logs are good, but real-time is meh

Already-generated logs are partially unavailable while the step is running.

Example: For some reason the toolchain has to be regenerated. This generates hundreds of lines of output, and takes 15 minutes or so. If you open the job page during this step, the previous output lines of the steps are unavailable.

This feels like a bug, and I just hope it'll go away maybe.

## Toolchain cache

Historically, we assumed that *ALL* LibC headers have an impact on the Toolchain, and have *always* rebuilt when any LibC header changed.

This PR changes nothing about that. However, due to the way GA works, it's now a bit harder to improve this situation. Oh well.

On the positive side, building the toolchain now takes only 20 minutes, so it shouldn't be too devastating.

## IRC notifications

Theoretically they work.

How notifications for pushes are supposed to look:
```
(16:32:54) serenity-ga [~serenity-@13.89.60.161] joined.
(16:32:54) serenity-ga: BenWiederhake opened PR #3: success
(16:32:54) serenity-ga: Subject: PR notification tests, again
(16:32:54) serenity-ga: Details: https://github.com/BenWiederhake/serenity/pull/3
(16:32:54) serenity-ga left.
```

How notifications for PRs are supposed to look:
```
(16:36:19) serenity-ga [~serenity-@52.173.25.196] joined.
(16:36:19) serenity-ga: BenWiederhake pushed master https://github.com/BenWiederhake/serenity/compare/cbd37b2532ce...19a4f6bc606b: success
(16:36:19) serenity-ga: Subject: More grammaticallier correctly
(16:36:19) serenity-ga: Details: https://github.com/BenWiederhake/serenity/actions/runs/351224074
(16:36:20) serenity-ga left.
```

However, due to the way Github Actions works we can only pass *all* commit descriptions to it, or *none*, resulting in behavior like this:

```
(17:06:14) serenity-ga [~serenity-@13.89.49.99] joined.
(17:06:14) serenity-ga: BenWiederhake pushed master on https://github.com/BenWiederhake/serenity/compare/3c480dd7c41e...5267c761363e: failure
(17:06:14) serenity-ga: Subject: LibJS: Use array-like size for IndexedProperties::is_empty()
(17:06:14) serenity-ga:  
(17:06:14) serenity-ga left (quit: Excess Flood).
```
(Note that it tries to print the commits in chronological order, so only the oldest commit message is displayed.)

The `cmake.yml` feels like the wrong place to do any more advanced logic anyway. We could, in theory, write a script that takes a large JSON with all the info, spits out a nice IRC message, and hand that message to the IRC messenger. However, that script shouldn't be written in bash (parsing JSON is too complex), and not in C++ (build errors would mean we can't report build errors). It would be about 50 lines in Python, but I really don't want to add a new language to the project now.

So I'll just stick with "send the first commit" and that's it then.

### CODE REVIEW

**Comment by BenWiederhake** [comment]
Aaand I'm done fumbling with the IRC notifier details. Now it's ready to merge.

**Comment by BenWiederhake** [comment]
Oh, and: @kling may or may not need to enable it first under https://github.com/SerenityOS/serenity/settings/actions

**Comment by awesomekling** [comment]
That's not my GitHub username :)

Anyways, this is super awesome Ben! Let's also remove the travis banner in ReadMe.md

**Comment by BenWiederhake** [comment]
Indeed! And, indeed!

**Comment by linusg** [comment]
> Let's also remove the travis banner in ReadMe.md

...and replace it with a GitHub Actions one:

```
[![Build status](https://github.com/SerenityOS/serenity/workflows/CMake%20lint,%20build,%20test/badge.svg)](https://github.com/SerenityOS/serenity/actions?query=workflow%3A"CMake+lint%2C+build%2C+test")
```

Here's the one from @BenWiederhake's fork:

[Build status](https://github.com/BenWiederhake/serenity/actions?query=workflow%3A"CMake+lint%2C+build%2C+test")

I'd suggest renaming the workflow to not contain "CMake", that's not relevant IMO. e.g. `Build, lint & test`.

**Comment by BenWiederhake** [comment]
Done.

Because I'm so contrarian, I went with the name `Build, lint, and test`. Thank you @linusg, I was about to look them up! :D

**Pull request merged**
