### PR TITLE
Kernel+LibCore+LibHTTP: Properly handle TCP/HTTP closed connections.

### LINKED ISSUE #7966: NetworkTask: Send RST/ACK if no socket is available for packet
Currently, if we receive a TCP packet with a destination port where nothing is listening, we do nothing (except debug output):
https://github.com/SerenityOS/serenity/blob/00a83a295774089e21080d173e3b33da8bf5fd17/Kernel/Net/NetworkTask.cpp#L379-L396
This leads to the behavior that if you e.g. navigate to `http://localhost:1337` in Browser and nothing is listening there, it just loads indefinitely.

As a comparison, Linux sends `RST,ACK` if it receives a `SYN` packet on a non-listening port. This means that the client can then knows to close the connection.

(I've just seen that I already created an issue (#7869) for that a few days ago, closed that one since it's less specific.)

### PR DESCRIPTION
**Pull request by brapru**
Resolves #7966

**Kernel: Clear SO_ERROR on successful socket connection**
When TCP sockets successfully establish a connection, any SO_ERROR
should be cleared back to success. For example, SO_ERROR gets set to
EINPROGRESS on asynchronous connect calls and should be cleared when
the socket moves to the Established state.

**LibCore: Add on_error callback for socket**

**LibHttp: Implement on_error callback**
Previously the system assumed that when it reached the callback
connection the socket was establish, and it would continue processing
the HTTP request.

This would lead to the unintentional consequences of the browser hanging
when attempting to connect to a closed port. This patch allows the HTTP
request to fail in the case of an error.

**LibCore: Check the status of the socket after EINPROGRESS**
Previously the system would assume the socket was connected after the
file descriptor became writeable. Just because the fd is signaled as
ready for output does not necessarily indicate the socket is connected.
Instead, we should check the status of the socket with SO_ERROR and
handle successes/errors accordingly.

### CODE REVIEW

**Comment by alimpfard** [comment]
Why are we firing `on_connected` when the socket _isn't_ connected?
Perhaps the socket should have a `on_error` that gets called in such cases instead?

**Review by alimpfard — COMMENTED** [review]
I think it makes a bit more sense to merge the second and last commits, and put that in place of the second commit, there's no dependency here, so two commits for adding a field and adding its behaviour sounds kinda pointless

**Comment by brapru** [comment]
> I think it makes a bit more sense to merge the second and last commits, and put that in place of the second commit, there's no dependency here, so two commits for adding a field and adding its behaviour sounds kinda pointless

Yeah that's something I always struggle with -- making commits _too_ atomic. Fixed!

**Review by alimpfard — APPROVED** [review]
LGTM, let's just wait for CI :)

**Pull request merged**
