### PR TITLE
Add Arm toolchain

### PR DESCRIPTION
**Pull request by redbrain**
I want to try and port serenity to arm and the first part was to get a toolchain. I approached this by extracting the tarball and creating a git repo and using git diff to get the patch file.

### CODE REVIEW

**Comment by awesomekling** [comment]
Hmm, I can't really make out from the changes: is it still possible to build the i686-pc-serenity toolchain with these patches, or do they break that?

**Comment by redbrain** [comment]
It is yes but let me redo those builds for you and provide the evidence here just to double check.

**Comment by danboid** [comment]
Which ARM platform / model are you targeting first?

**Comment by redbrain** [comment]
```edbrain@redbrain-XPS-13-7390 {~/workspace/serenity/Toolchain} $ ls Local/i686-pc-serenity/bin/
ar  as  ld  ld.bfd  nm  objcopy  objdump  ranlib  readelf  strip
redbrain@redbrain-XPS-13-7390 {~/workspace/serenity/Toolchain} $ ls Local/bin/
i686-pc-serenity-addr2line  i686-pc-serenity-elfedit    i686-pc-serenity-gcc-ranlib  i686-pc-serenity-ld.bfd   i686-pc-serenity-size
i686-pc-serenity-ar         i686-pc-serenity-g++        i686-pc-serenity-gcov        i686-pc-serenity-nm       i686-pc-serenity-strings
i686-pc-serenity-as         i686-pc-serenity-gcc        i686-pc-serenity-gcov-dump   i686-pc-serenity-objcopy  i686-pc-serenity-strip
i686-pc-serenity-c++        i686-pc-serenity-gcc-8.3.0  i686-pc-serenity-gcov-tool   i686-pc-serenity-objdump
i686-pc-serenity-c++filt    i686-pc-serenity-gcc-ar     i686-pc-serenity-gprof       i686-pc-serenity-ranlib
i686-pc-serenity-cpp        i686-pc-serenity-gcc-nm     i686-pc-serenity-ld          i686-pc-serenity-readelf
```

Thanks for asking me to confirm i had a missing bit for both gcc for the original builds. I added stuff to the built it script to help with making toolchain changes where the patches are applied using git now.

**Comment by redbrain** [comment]
I want to target raspberry pi 2 because i have one and qemu supports it

**Comment by redbrain** [comment]
closing finding a crash in binutils at the moment

**Comment by Quaker762** [comment]
Would it be better to structure this with folders? As in:

`
Toolchain
|
|----ARM
|----amd64
|----i686
`

This way, you can just source whatever script you want to build for as well as not having to touch the original scripts we have right now.

**Comment by danboid** [comment]
@redbrain Whilst you're looking at the toolchain, I'd like to hear your thoughts on https://github.com/SerenityOS/serenity/issues/866 . Is there a gcc build/install option that would install the std C++ headers for us, under x86 and ARM, that isn't enabled right now? I came across another app thst I'd like to port last night that needs std::isblank to build, another needs std::thread etc.

**Pull request closed without merging**
