### PR TITLE
Userland: implement passwd

### PR DESCRIPTION
**Pull request by JustBeYou**
Implement passwd utility as #1168 requests.
This is not ready for merging yet.

### CODE REVIEW

**Comment by awesomekling** [comment]
Thank you for working on this :)
Please see https://github.com/SerenityOS/serenity/blob/master/Documentation/CodingStyle.md for coding style. Most importantly:
- Use `clang-format` to ensure that basic formatting is consistent with the rest of the codebase.
- Please don't use non-idiomatic C++ syntax like `and` instead of `&&` and `not` instead of `!`.
- Please only put `#include` statements at the top of a file.
- Please squash commits that iterate on the same code instead of stacking commits that fix bugs in previous commits.

**Comment by bugaevc** [comment]
`pw_passwd` is not the actual password; so this is all wrong. The actual password's hash could be read from `/etc/shadow`, if something were to write it there, as discussed in https://github.com/SerenityOS/serenity/issues/1168

**Comment by JustBeYou** [comment]
@bugaevc I know, it's just a quick sketch. I just opened the PR to get code review/be visible that someone is working on this.

I think if we modify `pwd.cpp` to load the password hash from the right place, the code from this PR would only need to hash the input password and the rest would remain good.

**Comment by awesomekling** [comment]
I don't think the code in `pwd.cpp` should be reading from `/etc/shadow` since it won't be available for unprivileged users.

**Comment by jcs** [comment]
`strcmp` should probably not be used for checking passwords either since it bails early.

**Comment by awesomekling** [comment]
Closing due to inactivity. Feel free to reopen if you work more on this :)

**Pull request closed without merging**
