### PR TITLE
LibWeb: Add NodeFilter to window object

### PR DESCRIPTION
**Pull request by miller-time**
noticed that on certain pages, Ladybird and Browser both throw the error:

```
Unhandled JavaScript exception: [ReferenceError] 'NodeFilter' is not defined
```

MDN: https://developer.mozilla.org/en-US/docs/Web/API/Document/createNodeIterator
w3: https://www.w3.org/TR/DOM-Level-2-Traversal-Range/traversal.html#Traversal-NodeFilter

Followed the [AddNewIDL](https://github.com/SerenityOS/serenity/blob/master/Documentation/Browser/AddNewIDLFile.md) guide in the Serenity docs, to add the existing `NodeFilter` to the window object.

### CODE REVIEW

**Comment by miller-time** [comment]
```
/usr/bin/ld: CMakeFiles/LibWeb.dir/LibWeb/Bindings/NodeFilterWrapper.cpp.o: in function `Web::Bindings::wrap(JS::GlobalObject&, Web::DOM::NodeFilter&)':
/home/runner/work/serenity/serenity/Build/lagom/LibWeb/Bindings/NodeFilterWrapper.cpp:362: multiple definition of `Web::Bindings::wrap(JS::GlobalObject&, Web::DOM::NodeFilter&)'; CMakeFiles/LibWeb.dir/home/runner/work/serenity/serenity/Userland/Libraries/LibWeb/Bindings/NodeFilterWrapperFactory.cpp.o:/home/runner/work/serenity/serenity/Userland/Libraries/LibWeb/Bindings/NodeFilterWrapperFactory.cpp:14: first defined here
```

I don't understand this error. I can't find the second definition...

**Review by linusg — CHANGES_REQUESTED** [review]
Needs a update for the LibJS GLobalObject -> Realm changes

**Comment by linusg** [comment]
ping @miller-time

**Comment by miller-time** [comment]
> ping @miller-time

oh shoot, this slipped my mind! I will try to do the Realm update later today.

**Comment by miller-time** [comment]
Rebased and pushed but I'm guessing that the `NodeFilterWrapperFactory` should ***not*** be added because the section that talked about wrapper factories has been removed from [AddNewIDLFile.md](https://github.com/SerenityOS/serenity/blob/master/Documentation/Browser/AddNewIDLFile.md).

**Comment by linusg** [comment]
That seems right, yeah :)

**Comment by ADKaster** [comment]
This has conflicts again, for some refactors that I did this time :sweat_smile:

**Pull request closed without merging**
