### PR TITLE
Base: Add SQL and Database filetypes icon

### PR DESCRIPTION
**Pull request by alichraghi**
**SQL**
filetype-sql
filetype-sql

**Database**
filetype-db
filetype-db

### CODE REVIEW

**Comment by Quaker762** [comment]
Hi @alichraghi 

Did you make these on Windows by any chance? Looks like the permissions are a little bit funky (they contain `x`). The easiest way to change these is with `chmod`. 

https://www.howtogeek.com/437958/how-to-use-the-chmod-command-on-linux/

**Review by linusg — CHANGES_REQUESTED** [review]
You'll also have to run `optipng -strip all` on them, several kb for 16/32 px images is not acceptable.

**Review by linusg — APPROVED** [review]
:star_struck:

**Review by linusg — CHANGES_REQUESTED** [review]
Ah, just noticed they're still marked executable...

**Comment by alichraghi** [comment]
did `chmod -x` on every icons. does that work?

**Pull request merged**
