### PR TITLE
Gender neutral language within build instructions

### PR DESCRIPTION
**Pull request by Tunas1337**
It's a minor nitpick, but I think it's important; assuming the user and/or developer of the operating system is male isn't exactly the best.

### CODE REVIEW

**Comment by awesomekling** [comment]
This project is not an appropriate arena to advertise your personal politics.

**Comment by Tunas1337** [comment]
I had no intention to advertise anything, my bad. I thought it was a neutral enough change, but I do understand if it's necessary to discuss it further, or just not implement it whatsoever if you do not agree with it.

**Comment by cafkafk** [comment]
hi fedi :wave:

**Comment by MostAwesomeDude** [comment]
The denial of non-male users and/or developers is sufficient reason to not use SerenityOS. Thanks for documenting your beliefs clearly.

**Comment by cafkafk** [comment]
> The denial of non-male users and/or developers is sufficient reason to not use SerenityOS. Thanks for documenting your beliefs clearly.

check this as well https://github.com/SerenityOS/serenity/pull/8046#issuecomment-860350155, totally cooked project

**Comment by dtfleetwood** [comment]
Yup, projects that defend dehumanization deserve to wither on the vine. Will see if the new leadership course corrects.

**Comment by rollerozxa** [comment]
If English is not your native language and you accidentally use gendered language directed at an undetermined person then that is understandable, but lashing out when someone contributes a change to correct it is just vile.

**Comment by Higgs1** [comment]
There's a [report button](https://support.github.com/contact/report-abuse?category=report-abuse&report=awesomekling). Good day.

**Comment by Syphist** [comment]
What a vile response and terrible look for you and your projects.

**Comment by quietautumns** [comment]
made an account just to say how shitty this is :3

**Comment by Tunas1337** [comment]
OP here. I'd just like to chime in and say that it's been nearly 3 years and a month since I tried to make what I believed to be a minuscule neutral change entirely rooted in grammar, and not once have I touched this project until these replies brought it back into my attention. If the developer has a right to develop under the assumption that every user is male, I have the right to boycott the software. I don't know what "new leadership" is being talked about, as I haven't searched the web about it yet, but I also hope that they are more logical about issues like this.

**Comment by iskamag** [comment]
Good day cat people.  awesomekling, you're truly awesome :3
1c559886d46f5fbd

**Comment by mia-0** [comment]
Every time some FOSS dev rejects a change from generic masculine the mastoqueers come crawling out of the woodwork to start screeching about how he’s literally Hitler. This is pathetic.

Good job validating his views, I guess. Surely that’ll help.

Some of you may be thinking there’s no arguing with such people but to be honest, I used to be like that, too. Sometimes much worse—fiercely “anti-woke”. And yet I’ve changed. Maybe he won’t, but brigading isn’t going to achieve anything but provide more ammunition.

**Comment by alexispurslane** [comment]
> Every time some FOSS dev rejects a change from generic masculine the mastoqueers come crawling out of the woodwork to start screeching about how he’s literally Hitler. This is pathetic.

Who said that? This just sucks. I've been following kling, Serenity OS, and LadyBird for a very long time and I assumed they'd be better.

**Comment by SepiaChiptunes** [comment]
>mastoqueers
i'm gonna start using this for myself now LMAO that's genuinely so funny

**Comment by MeowcaTheoRange** [comment]
> Every time some FOSS dev rejects a change from generic masculine the mastoqueers come crawling out of the woodwork to start screeching about how he’s literally Hitler. This is pathetic.

bold of u to assume everyone here uses m*stodon 🤢🤢🤮🤮 /silly

**Comment by ddvarpdd** [comment]
>Good job validating his views, I guess. Surely that’ll help.

That's the whole point of the toothpaste flag behavior though. Societally sanctioned harassment to fill the need of domination in the lack of any productive ways to do so.

**Comment by tulpenkiste** [comment]
> > Every time some FOSS dev rejects a change from generic masculine the mastoqueers come crawling out of the woodwork to start screeching about how he’s literally Hitler. This is pathetic.
> 
> bold of u to assume everyone here uses m*stodon 🤢🤢🤮🤮 /silly

Yeah, we all use queerkey here, smh >:3

**Comment by mia-0** [comment]
> That's the whole point of the toothpaste flag behavior though. Societally sanctioned harassment to fill the need of domination in the lack of any productive ways to do so.

Think it’s really just siege mentality.

**Comment by MeowcaTheoRange** [comment]
but yeah as a they/them user mysel it would be cool if this pull request was re-reviewed :3

**Comment by tulpenkiste** [comment]
> > Good job validating his views, I guess. Surely that’ll help.
> 
> That's the whole point of the toothpaste flag behavior though. Societally sanctioned harassment to fill the need of domination in the lack of any productive ways to do so.

Using the behaviour of an individual to demean an entire community is, quite frankly, pretty stupid and incredibly rude.

**Comment by SleepyCatgirl** [comment]
> Every time some FOSS dev rejects a change from generic masculine the mastoqueers come crawling out of the woodwork to start screeching about how he’s literally Hitler. This is pathetic.
> 
> Good job validating his views, I guess. Surely that’ll help.
> 
> Some of you may be thinking there’s no arguing with such people but to be honest, I used to be like that, too. Sometimes much worse—fiercely “anti-woke”. And yet I’ve changed. Maybe he won’t, but brigading isn’t going to achieve anything but providing more ammunition.

We... really do need a better way of handling those issues to be honest. I mean... this is open source, this is about doing things together. And please, no one is screeching about how anyone is literally hitler. Just that... its disappointing.

**Comment by nukeop** [comment]
Mastodonites seething even after 3 years lol

**Comment by tulpenkiste** [comment]
> Mastodonites seething even after 3 years lol

Not everyone here came from Mastodon

**Comment by ddvarpdd** [comment]
>And please, no one is screeching about how anyone is literally hitler. Just that... its disappointing.

At least one user here agitated others to report the project for "harassment" because Kling didn't want to bother with DEI bureaucracy in his pet project three whole years ago.

**Comment by MeowcaTheoRange** [comment]
> Mastodonites seething even after 3 years lol

errm... gross...... 🤢🤢🤢🤮🤮🤮🤮 see above: https://github.com/SerenityOS/serenity/pull/6814#issuecomment-2203644678 (being even more silly rn)

**Comment by nukeop** [comment]
Ah okay so you're using mastodon with a changed logo and name

**Comment by MeowcaTheoRange** [comment]
> Ah okay so you're using mastodon with a changed logo and name

Correct !!!! ✅✅✅✅✅✅✅

**Comment by K4rakara** [comment]
I really should have specified on my fediverse post to _not_ harass the guy about it. While I might disagree with his views and no longer wish to use his software, it was not my intent for people to harass him about his views. I simply wanted people to be made aware of it so they can decide whether it's a project they wanted to use or not.  This is a three year old issue, and the outcome of it is not going to change.

**Comment by nukeop** [comment]
If this kind of thing is what makes you decide to use the project or not, you were not going to use it or even know what it is in the first place.

**Comment by MeowcaTheoRange** [comment]
> I really should have specified on my fediverse post to _not_ harass the guy about it. While I might disagree with his views and no longer wish to use his software, it was not my intent for people to harass him about his views. I simply wanted people to be made aware of it so they can decide whether it's a project they wanted to use or not. This is a three year old issue, and the outcome of it is not going to change.

yeah true
im just over here bring silly but i will Stop participating here cus yall are too Not silly for me to care :3 (and it'z actually filling up this thread and exploding in terms of github notifications)
so just see https://github.com/SerenityOS/serenity/pull/6814#issuecomment-2203664170 - im out :3

**Comment by 4risu** [comment]
Sunlight is the best disinfectant.
I tried being "understanding" of bullies for many years. It's easier... If people change that's good but I'm not waiting around.

**Comment by nukeop** [comment]
You all have 0 open source contributions and this guy built an entire OS by himself

**Comment by tulpenkiste** [comment]
> You all have 0 open source contributions and this guy built an entire OS by himself

What does this have to do with anything? Those who have not contribute are still permitted to write issues for projects. To gatekeep such a thing worsens the reputation of open source.

Also, I have contributed to open source. :3

**Comment by TheEvilSkeleton** [comment]
> You all have 0 open source contributions

Well, your commit number means very little in practice, because you don't have to be a developer to contribute to FOSS. You can work on documentation, designs, marketing, moderation, reporting issues, etc. etc.

Since you're comparing about source contributions, you might want to look at my GNOME GitLab profile and acknowledge that I contribute to software used by millions of users :) https://gitlab.gnome.org/TheEvilSkeleton

But even then, many people may have 0 contributions because they don't want to deal with people who think that any kind of step toward inclusivity is "personal politics," when it's fundamentally collective politics of making it more welcoming for everyone else.

**Comment by MeowcaTheoRange** [comment]
> > You all have 0 open source contributions
> 
> Well, your commit number means very little in practice, because you don't have to be a developer to contribute to FOSS. You can work on documentation, designs, marketing, moderation, reporting issues, etc. etc.
> 
> Since you're comparing about FOSS contributions, you might want to look at my GNOME GitLab profile and acknowledge that I contribute to software used by millions of users :) https://gitlab.gnome.org/TheEvilSkeleton
> 
> But even then, many people may have 0 contributions because they don't want to deal with people who think that any kind of step toward inclusivity is "personal politics," when it's fundamentally collective politics of making it more welcoming for everyone else.

^^ this, [i don't even use github anymore](https://git.gay/MeowcaTheoRange)

**Comment by isabelroses** [comment]
> hi fedi 👋

Haiiii

P.S. Surprised this hasn't been locked yet lol

**Comment by tulpenkiste** [comment]
> > > You all have 0 open source contributions
> > 
> > 
> > Well, your commit number means very little in practice, because you don't have to be a developer to contribute to FOSS. You can work on documentation, designs, marketing, moderation, reporting issues, etc. etc.
> > Since you're comparing about FOSS contributions, you might want to look at my GNOME GitLab profile and acknowledge that I contribute to software used by millions of users :) https://gitlab.gnome.org/TheEvilSkeleton
> > But even then, many people may have 0 contributions because they don't want to deal with people who think that any kind of step toward inclusivity is "personal politics," when it's fundamentally collective politics of making it more welcoming for everyone else.
> 
> ^^ this, [i don't even use github anymore](https://git.gay/MeowcaTheoRange)

[Nor do I](https://codeberg.org/tulpenkiste)

**Comment by tulpenkiste** [comment]
> > hi fedi 👋
> 
> Haiiii
> 
> P.S. Surprised this hasn't been locked yet lol

I imagine the project managers just aren't aware of whats going on yet

**Comment by MeowcaTheoRange** [comment]
> > hi fedi 👋
> 
> Haiiii
> 
> P.S. Surprised this hasn't been locked yet lol

even if it's not locked though I think the conversation here should   Come to a halt. see https://github.com/SerenityOS/serenity/pull/6814#issuecomment-2203687225

**Comment by RedCyberPandaz** [comment]
I wanna get in on this before it gets locked. Dev bad.

**Comment by MeowcaTheoRange** [comment]
> > hi fedi 👋
> 
> Haiiii
> 
> P.S. Surprised this hasn't been locked yet lol

even if it's not locked though I think the conversation here should   Come to a halt. see https://github.com/SerenityOS/serenity/pull/6814#issuecomment-2203687225

**Comment by SegoCode** [comment]
Neither wrong or right, your project, your rules, and everyone can make the decision they want about contributing

**Pull request closed without merging**
