### PR TITLE
Kernel: Support passing arguments to shebanged scripts

### PR DESCRIPTION
**Pull request by karolba**

### CODE REVIEW

**Comment by awesomekling** [comment]
Looks good!
If this fixes #585, please add a line saying "Fixes #585" to the bottom of the commit message :)

**Comment by karolba** [comment]
> Looks good!
> If this fixes #585, please add a line saying "Fixes #585" to the bottom of the commit message :)

It doesn't yet because to close #585 support for arguments in the shebang line is also required (e.g. `#!/usr/local/bin/bash -x`). I'll make this PR a WIP and try to implement it here so that #585 can be closed in one PR.

**Comment by karolba** [comment]
@awesomekling  What do you think about it now? I've also implemented spplitting arguments in the shebang line, so that `#!/usr/local/bin/bash -x -e` becomes `"/usr/local/bin/bash" "-x" "-e"` instead of `"/usr/local/bin/bash" "-x -e"`. It doesn't match Linux's behaviour, but the one found in MacOS and Plan9.

**Comment by awesomekling** [comment]
Yes, this looks good! I'm also surprised about the Linux behavior, this behavior seems more sensible :)

**Pull request merged**
