### PR TITLE
LibGfx: Behave nicely with non-(int/float) Rect and Point

### PR DESCRIPTION
**Pull request by AtkinsSJ**
...because linker errors after you've waited 10+ minutes for a build are not fun. :^(

This makes more methods work on `Rect<T>`, and uses concepts to give a clear error when trying to use unsupported types in some `AffineTransform` methods.

EDIT: To be completely clear, that first commit is just moving code without changing it. Don't be scared by the big diff!

### CODE REVIEW

**Comment by linusg** [comment]
CI not happy about this :frowning:

**Comment by davidot** [comment]
> > CI not happy about this frowning
> 
> Indeed. I can't figure out why at the moment.

I had a quick look at this, and I can get it to build by just specifying it should use Gfx::Rect in two spots. 
To prevent this in the future maybe the intersected(Line<T> const& line) method could be renamed? But I'll stop ideaguying at this point

```diff
Index: Userland/Services/WindowServer/ConnectionFromClient.cpp
<+>UTF-8
===================================================================
diff --git a/Userland/Services/WindowServer/ConnectionFromClient.cpp b/Userland/Services/WindowServer/ConnectionFromClient.cpp
--- a/Userland/Services/WindowServer/ConnectionFromClient.cpp	(revision 5f36e54d56cc18cd4299c632b9fe98ec2736b522)
+++ b/Userland/Services/WindowServer/ConnectionFromClient.cpp	(date 1666301672728)
@@ -686,7 +686,7 @@
     }
     auto& window = *(*it).value;
     for (size_t i = 0; i < rects.size(); ++i)
-        window.request_update(rects[i].intersected({ {}, window.size() }), ignore_occlusion);
+        window.request_update(rects[i].intersected(Gfx::Rect { {}, window.size() }), ignore_occlusion);
 }
 
 void ConnectionFromClient::did_finish_painting(i32 window_id, Vector<Gfx::IntRect> const& rects)
Index: Userland/Services/WindowServer/WindowFrame.cpp
<+>UTF-8
===================================================================
diff --git a/Userland/Services/WindowServer/WindowFrame.cpp b/Userland/Services/WindowServer/WindowFrame.cpp
--- a/Userland/Services/WindowServer/WindowFrame.cpp	(revision 5f36e54d56cc18cd4299c632b9fe98ec2736b522)
+++ b/Userland/Services/WindowServer/WindowFrame.cpp	(date 1666292088367)
@@ -349,7 +349,7 @@
         auto top_bottom_height = frame_rect.height() - window_rect.height();
         if (m_bottom_y > 0) {
             // We have a top piece
-            auto src_rect = rect.intersected({ frame_rect.location(), { frame_rect.width(), m_bottom_y } });
+            auto src_rect = rect.intersected(Gfx::Rect { frame_rect.location(), { frame_rect.width(), m_bottom_y } });
             if (!src_rect.is_empty())
                 painter.blit(src_rect.location(), *m_top_bottom, src_rect.translated(-frame_rect.location()), frame.opacity());
         }
```

**Comment by AtkinsSJ** [comment]
Brilliant, thanks @davidot! :grinning: Hopefully it'll pass CI this time.

**Review by davidot — APPROVED** [review]
Since you just moved code and everything passes LGTM

**Pull request merged**
