### PR TITLE
Kernel/USB: Add support for xHCI bulk transfers

### PR DESCRIPTION
**Pull request by spholz**
This makes booting from a USB mass storage device connected to an xHCI host controller possible!

You can try doing so with the following command:
`qemu-system-x86_64 -M q35 -m 2G -kernel Build/x86_64/Kernel/Kernel -serial mon:stdio -append 'serial_debug root=block3:0' -s -device qemu-xhci -drive file=Build/x86_64/_disk_image,format=raw,if=none,id=drive -device usb-storage,drive=drive`

Note that until #24902 is merged Shell may crash when booted from a mass storage device.

### CODE REVIEW

**Comment by Hendiadyoin1** [comment]
Does it also work with the USB boot mode from serenity.sh?

**Comment by spholz** [comment]
`SERENITY_NVME_ENABLE=0 SERENITY_USE_USBDRIVE=1 Meta/serenity.sh run` does boot but I assume it doesn't use xHCI since I think that worked before as well?

**Comment by spholz** [comment]
I cleaned up the boot drive options now and made it possible to choose between UCHI and xHCI for USB storage.

**Review by Hendiadyoin1 — APPROVED** [review]
LGTM

**Comment by nico** [comment]
Do we need to update any docs for the run.py tweaks?

**Comment by spholz** [comment]
Grepping for these old options results in no matches. We probably just don't have those options documented.

**Pull request merged**
