### PR TITLE
LibJVM: Start parsing class files

### PR DESCRIPTION
**Pull request by noahhaasis**
The `ClassFileParser` is able to parse simple classfiles into a `ClassFile` structure.
The parser successfully consumes the .class file of the most basic Java program:
```java
class Main {
    static void main(String args[]) {}
}
```

There is still a lot missing but I want to have this overall structure reviewed before I flesh out the parser and start using the ClassFile interface in the Runtime.
I'm new to modern C++ so there's probably lots to improve.

One design decision I made, is that the ClassFile structure holds onto the buffer containing the contents of the `.class` file. This is because fields of the ClassFile structure point into the buffer e.g. for strings or bytecode.

Another design decision is using `unions` instead of inheritance to represent constants in the java constant pool.

### CODE REVIEW

**Comment by cbyrneee** [comment]
Looks like you're missing a CMakeLists.txt file for LibJVM :)

**Comment by awesomekling** [comment]
From our [contributing guidelines](https://github.com/SerenityOS/serenity/blob/d364c8e352eda946f5c585733460e7e7c770da9f/CONTRIBUTING.md):
> When contributing to SerenityOS, make sure that the changes you wish to make are in line with the project direction. If you are not sure about this, open an issue first, so we can discuss it.

I haven't seen any discussion about building a JVM anywhere. SerenityOS has nothing to do with Java, so why does it suddenly need a JVM?

**Comment by noahhaasis** [comment]
> From our [contributing guidelines](https://github.com/SerenityOS/serenity/blob/d364c8e352eda946f5c585733460e7e7c770da9f/CONTRIBUTING.md):
> 
> > When contributing to SerenityOS, make sure that the changes you wish to make are in line with the project direction. If you are not sure about this, open an issue first, so we can discuss it.
> 
> I haven't seen any discussion about building a JVM anywhere. SerenityOS has nothing to do with Java, so why does it suddenly need a JVM?



> 

I saw a single mention on the Discord
> A: Do Serenity supports Java or nor yet?
> B: There's no port nor custom implementation, so no.
> C: You are more than welcome to implement stuff though! (Maybe dont start with the jvm...)

And I think it came up in office hours a few times, does Serenity run Minecraft, support Java ... with the typical answer, no but you could work on that.

But yes I understand that a second VM might not fit into Serenity and that nobody wants a dead library.
So should I open an issue or close the MR? It was a fun learning exercise over the holidays anyways :)

**Comment by awesomekling** [comment]
If you want to build a JVM, I suggest doing it as a completely separate project from SerenityOS, as there is no natural need for Java anywhere in this system. :)

**Pull request closed without merging**
