### PR TITLE
Base: Merge Serifina into Roman font family as italic variant

### PR DESCRIPTION
**Pull request by thankyouverycool**
They were meant to be

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
cc @Xexxa @electrikmilk

**Review by Xexxa — APPROVED** [review]
Makes sense to me, the only characters that differs in style "Q" and "a" between Roman and the italic variant and it seems to be common to make double-storey "a" in a serif font single-storey when italic.

**Comment by electrikmilk** [comment]
Thank you for caring about Roman enough to merge a variant into it. :^) It has some differences, but these can be ironed out later.

**Review by electrikmilk — COMMENTED** [review]
Thank you for caring about Roman enough to merge a variant into it. :^) As @Xexxa said, they have some differences, but these can be ironed out later.

**Pull request merged**
