### PR TITLE
HexEditor: Fix crash of copy action when is empty

### PR DESCRIPTION
**Pull request by guerinoni**
Closes: #11925

At least the part related to the crash should be fine now.

### CODE REVIEW

**Review by metmo — COMMENTED** [review]
Hi! As far as I can tell this does fix the crash and the issue of not copying.
There's still a bug where one character too much get's copied but that is another issue.

Would you mind fixing the typo in the commit and pr message to "...when the _selection_ is empty"

**Comment by guerinoni** [comment]
@metmo thank you for feedback... Now should be fixed all problems :D

**Review by metmo — COMMENTED** [review]
The functionality is right but I still think you should clarify in the commit messages why the change was needed, even if it's a trivial fix context is always good.

`copy_selected_hex_to_clipboard_as_c_code()` will have to be changed as well

```diff
diff --git a/Userland/Applications/HexEditor/HexEditor.cpp b/Userland/Applications/HexEditor/HexEditor.cpp
index 95a318a9ed..880c5915e3 100644
--- a/Userland/Applications/HexEditor/HexEditor.cpp
+++ b/Userland/Applications/HexEditor/HexEditor.cpp
@@ -188,9 +188,9 @@ bool HexEditor::copy_selected_hex_to_clipboard_as_c_code()
         return false;
 
     StringBuilder output_string_builder;
-    output_string_builder.appendff("unsigned char raw_data[{}] = {{\n", (m_selection_end - m_selection_start) + 1);
+    output_string_builder.appendff("unsigned char raw_data[{}] = {{\n", m_selection_end - m_selection_start);
     output_string_builder.append("    ");
-    for (size_t i = m_selection_start, j = 1; i <= m_selection_end; i++, j++) {
+    for (size_t i = m_selection_start, j = 1; i < m_selection_end; i++, j++) {
         output_string_builder.appendff("{:#02X}", m_document->get(i).value);
         if (i != m_selection_end)
             output_string_builder.append(", ");
```

**Comment by metmo** [comment]
Code looks good to me, but there's still typos in the commit messages, sorry for being nitpicky but the code submission policy is clear on things like that :)

`exatly selected chars` => `exactly the selected chars`

`when is empty` => `when selection is empty`

**Comment by guerinoni** [comment]
@metmo no problem :)
I'm here to improve myself, inspiring from serenity's developer that looks very skilled!

**Review by metmo — APPROVED** [review]

**Comment by guerinoni** [comment]
@mustafaquraish what you think about this? :)

**Comment by mustafaquraish** [comment]
> @mustafaquraish what you think about this? :)

I haven't worked much with `HexEditor` before, but at least just looking at the code here it seems this change wouldn't include the end character of a selection? I think the expected behaviour would be to have the end position of the cursor also be included as part of the selection. 

For instance, would this allow me to select / copy a single character? Since the selection start would be equal to the selection end. I haven't actually checked out and run the code, so perhaps this does actually work, but on an initial inspection without being familiar with the specifics, this definitely stands out to me.

**Comment by guerinoni** [comment]
@mustafaquraish thanks for feedback... I just check the behavior and it works as expected :)

**Comment by guerinoni** [comment]
@awesomekling friendly code review request :)

**Pull request merged**
