### PR TITLE
Kernel: Fix race condition using thread safe singelton

### LINKED ISSUE #3226: Kernel/Net Race Condition?
https://github.com/SerenityOS/serenity/blob/413db2d6d5a49400d9587c9aa37bedd83968a6dd/Kernel/Net/IPv4Socket.cpp#L50-L53

There is a potential race condition on `s_table` .
Shouldn't checking if null, assignment to and dereferencing s_table be  **_atomic_** ?
I have prepared a _fix_, but am holding the PR.

### PR DESCRIPTION
**Pull request by tryfinally**
- [x] Modify Atomic to support Atomic enums
- [x] Implement thread safe singleton usable from both kernel and userland + Unit test
singleton uses atomic acquire/release memory order for performance
- [x] fix #3226 
- [x] fix other race condition in kernel
- [x] fix one race in AK FlyString

### CODE REVIEW

**Comment by tryfinally** [comment]
The race condition is present in other parts of the OS 
I will push more commits later to fix

**Comment by awesomekling** [comment]
Please format your commit messages like all other commit messages in the project.
See the [contribution guidelines](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md)

**Comment by tomuta** [comment]
While very similar approach, I like my implementation in #3229 a little better. Rather than doing a compare_exchange every time, it's simply doing a load and in the unlikely event that it hasn't been initialized do the more expensive operations. My approach also only uses one pointer.

**Comment by tryfinally** [comment]
@awesomekling I there is a typo in the commit message: Kernet should be Kernel.
Anything else I missed?

**Pull request closed without merging**
