### PR TITLE
Base: Add yet more color emojis

### PR DESCRIPTION
**Pull request by tarob0ba**
This commit adds more colorized emojis to the system.

🌻 - U+1F33B SUNFLOWER
🐌 - U+1F40C SNAIL
👑 - U+1F451 CROWN
📵 - U+1F4F5 NO MOBILE PHONES
🥇 - U+1F947 FIRST PLACE MEDAL
🥈 - U+1F948 SECOND PLACE MEDAL
🥑 - U+1F951 AVOCADO
🥕 - U+1F955 CARROT
🩸 - U+1FA78 DROP OF BLOOD

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
Am I missing something - this only seems to add emojis?

**Comment by tarob0ba** [comment]
The PR title is terrible, sorry.

**Comment by linusg** [comment]
The commit messages are what matters most, so please always update those :)

**Comment by tarob0ba** [comment]
Ah, sorry. Misunderstood what you said. One moment, please. :]

**Comment by tarob0ba** [comment]
Apologies. I've updated the commit title and message for clarity, since I worded the previous message awfully.

**Review by linusg — APPROVED** [review]
These are great, don't be too hard on yourself :)
Thanks! 🥑👑🐌

**Pull request merged**
