### PR TITLE
Ports: Pre-Christmas Port Cleanup

### PR DESCRIPTION
**Pull request by BertalanD**
Happy holidays, friends!

Many families around the world spend the days before Christmas cleaning their houses while waiting for the arrival of guests.  They do this to get rid of the baggage—both literal and emotional—that accumulated during the year, so that they can spend the holiday without worrying about everyday matters.

I thought I'd help our holiday preparation by getting rid of the almost 500 lines of patches that are no longer necessary, and now only contribute to software rot.

### CODE REVIEW

**Comment by BertalanD** [comment]
Converting to draft for a moment, as the CMake conflicting redeclaration issue reappeared on CxByte's branch.

**Comment by BertalanD** [comment]
Rebased on top of #11387 and fixed a typo.

**Comment by itamar8910** [comment]
The `libuv` fails to build for me on latest master.
Looks like it might be related to abc5426?
```
FAILED: CMakeFiles/uv_a.dir/src/unix/fs.c.o 
/home/itamar/serenity/Toolchain/Local/i686/bin/i686-pc-serenity-gcc --sysroot=/home/itamar/serenity/Build/superbuild-i686/../i686/Root -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Iinclude -Isrc -fvisibility=hidden   -Wstrict-prototypes -Wextra -Wall -Wno-unused-parameter -fno-strict-aliasing -std=gnu90 -MD -MT CMakeFiles/uv_a.dir/src/unix/fs.c.o -MF CMakeFiles/uv_a.dir/src/unix/fs.c.o.d -o CMakeFiles/uv_a.dir/src/unix/fs.c.o   -c src/unix/fs.c
src/unix/fs.c:94:11: fatal error: sys/statfs.h: No such file or directory
   94 | # include <sys/statfs.h>
      |           ^~~~~~~~~~~~~~
compilation terminated.
```

**Comment by BertalanD** [comment]
> The `libuv` port fails to build for me on latest master. Looks like it might be related to [abc5426](https://github.com/SerenityOS/serenity/commit/abc5426123084f163d3fa414d1d1ca938c8f236c)?
> 
> ```
> FAILED: CMakeFiles/uv_a.dir/src/unix/fs.c.o 
> /home/itamar/serenity/Toolchain/Local/i686/bin/i686-pc-serenity-gcc --sysroot=/home/itamar/serenity/Build/superbuild-i686/../i686/Root -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Iinclude -Isrc -fvisibility=hidden   -Wstrict-prototypes -Wextra -Wall -Wno-unused-parameter -fno-strict-aliasing -std=gnu90 -MD -MT CMakeFiles/uv_a.dir/src/unix/fs.c.o -MF CMakeFiles/uv_a.dir/src/unix/fs.c.o.d -o CMakeFiles/uv_a.dir/src/unix/fs.c.o   -c src/unix/fs.c
> src/unix/fs.c:94:11: fatal error: sys/statfs.h: No such file or directory
>    94 | # include <sys/statfs.h>
>       |           ^~~~~~~~~~~~~~
> compilation terminated.
> ```

Fixed in #11440. Sorry for the inconvenience.

**Pull request merged**
