### PR TITLE
Base+PixelPaint: Add more menu icons

### PR DESCRIPTION
**Pull request by electrikmilk**
Add icons missing from Pixel Paint menubar, either by creating new icons, or adding existing ones.

New Icons:
Screen Shot 2022-01-10 at 23 01 23

Screen Shot 2022-01-11 at 23 50 32
Screen Shot 2022-01-11 at 17 28 23
Screen Shot 2022-01-11 at 17 28 14
Screen Shot 2022-01-11 at 17 28 07
Screen Shot 2022-01-11 at 17 27 56
Screen Shot 2022-01-11 at 17 27 45
Screen Shot 2022-01-11 at 17 27 34

### CODE REVIEW

**Comment by metmo** [comment]
The icons look good! I do however get an assertion failure when i try to start pixelpaint. Seems it fails when loading `active-layer-down.png`. Opening it in gimp and resaving it fixed it for me, do you have any issues on your side?

**Comment by electrikmilk** [comment]
Thanks! Hmm...maybe I didn't optimize that one properly.

**Comment by electrikmilk** [comment]
> The icons look good! I do however get an assertion failure when i try to start pixelpaint. Seems it fails when loading `active-layer-down.png`. Opening it in gimp and resaving it fixed it for me, do you have any issues on your side?

Thanks! Hmm...maybe I didn't optimize that one properly.

**Comment by electrikmilk** [comment]
```
pixelpaint % optipng active-layer-down.png
** Processing: active-layer-down.png
16x16 pixels, 4 bits/pixel, 6 colors (3 transparent) in palette
Input IDAT size = 75 bytes
Input file size = 3365 bytes

Trying:
  zc = 9  zm = 8  zs = 0  f = 0		IDAT size = 77
  zc = 1  zm = 8  zs = 2  f = 5		IDAT size = 75
                               
active-layer-down.png is already optimized.
```

Should I not be using Photoshop to make these icons? I thought maybe @linusg's suggestion of `optipng` might help...

**Comment by metmo** [comment]
The error is `PNGImageDecoderPlugin: Palette index out of range`. This could be a bug in our png decoder since gimp and other applications read it just fine

**Comment by electrikmilk** [comment]
Reduced size of that icon and it was able to launch.

**Review by linusg — COMMENTED** [review]
LGTM, but please reword the commit message a bit (Userland -> PixelPaint, Added -> Add, no spaces around "+") - something like:

> Base+PixelPaint: Add more menu icons

**Pull request merged**
