### PR TITLE
Ports: Add RetroArch

### PR DESCRIPTION
**Pull request by gouchi**
It is working using SDL2 audio/video driver. [LibGL](https://github.com/SerenityOS/serenity/tree/master/Userland/Libraries/LibGL) is not [yet ready](https://pastebin.com/raw/FPUFZpd4) to enable [GL1 video driver](https://github.com/libretro/RetroArch/blob/master/gfx/drivers/gl1.c).

I have begun to package [Libretro cores](https://github.com/gouchi/libretro-cores-serenityos) to avoid to "clutter" the Ports directory.

## RetroArch menu

ra

## RetroArch running snes9x core
libretro-snes9x

### CODE REVIEW

**Comment by gouchi** [comment]
@EWouters @timschumi Sorry hope it will be good now.

**Comment by timschumi** [comment]
Why not... use the old PR?

**Comment by circl-lastname** [comment]
> Why not... use the old PR?

Low Git Fu

**Comment by gouchi** [comment]
I tried to rebase then squash but got some merging issue.

**Comment by EWouters** [comment]
I tested your PR again with the same result. No window ever shows but CPU stays at 100% (M1 Mac x86_64 GNU). 

But if It works on other systems it is not a problem that is doesn't work mine.

**Comment by timschumi** [comment]
Does this still work on the latest `master` branch with fresh builds of all ports? I'm hitting quite a few assertions (at least on `i686 GNU`) that make RetroArch basically unusable because they repeatedly appear:

Bildschirmfoto_2022-05-12_02-04-05
Bildschirmfoto_2022-05-12_02-04-14
Bildschirmfoto_2022-05-12_02-04-26

**Comment by gouchi** [comment]
Yes I am getting those issues I did not have before.

Is it coming from SDL2 update ? GCC update ? 

We will have to bisect...

**Comment by gouchi** [comment]
I did try to bisect SDL2 but I can't reproduce the issue anymore (maybe because I did from SerenityOS clean build).


## RetroArch running on SerenityOS [964f8fb](https://github.com/SerenityOS/serenity/commit/964f8fbf3a8b1faf73f763d4cb37a0a946c9ef29)
serenityos-964f8fb

**Comment by timschumi** [comment]
It's still broken for me, even on 964f8fbf3a8b1faf73f763d4cb37a0a946c9ef29. Clean build of everything, `i686 GNU`. Three failed assertions at the start, then nothing for some time, but in the end RetroArch goes into an endless loop of failed assertions before I get a chance to load some content.

**Comment by timschumi** [comment]
#14066 is in, so one last rebase to pick up the new CI and resolve the conflicts and we should be good.

**Review by timschumi — APPROVED** [review]
Looks reasonable, and builds (and appears to run) fine on `{i686,x86_64} GNU`.

**Pull request merged**
