### PR TITLE
Grammar fixes

### PR DESCRIPTION
**Pull request by ryancdotorg**
There are a few instances where comments and documentation have minor grammar
issues likely resulting from English being the author's second language.

This PR fixes several such cases, changing to idiomatic English and resolving
where it is unclear whether the user or program/code is being referred to.

### CODE REVIEW

**Comment by sylv256** [comment]
Thank you! In my opinion, this would make the project a lot more neutral-toned and less controversial.

**Comment by gmta** [comment]
Please fix the commit messages (see BuggieBot's comment); and maybe this can go in one commit? Doesn't really need to be 5 separate ones.

**Comment by ryancdotorg** [comment]
Sure, I'll squash and force push in about an hour.

**Comment by lavenderdotpet** [comment]
hell yeah! <3

**Comment by BertalanD** [comment]
Two more commit title nitpicks and we're good to go:
- The part after the category should start with a capital letter, and
- be in the imperative mood

From CONTRIBUTING.md:
> Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").

Thanks!

**Comment by ryancdotorg** [comment]
@BertalanD Look good now?

**Review by trflynn89 — APPROVED** [review]

**Comment by ryancdotorg** [comment]
Thanks all!

**Comment by LiEnby** [comment]
yeah of course can't have people of other genders *existing* thats too "political" but being mildly racist about it, now thats the 'correct' way to do it

**Comment by LiEnby** [comment]
yeah of course can't have people of other genders *existing* thats too "political"

**Comment by ryancdotorg** [comment]
Folks, please assume good faith here, and do not brigade this thread.

**Comment by LiEnby** [comment]
> Folks, please assume good faith here, and do not brigade this thread.

please assume good faith
> maintainers constantly acting in bad faith constantly

**Comment by ryancdotorg** [comment]
@LiEnby This PR has been merged. Please don't complain about the locked PRs/issues in my notifications. There are better outlets.

**Comment by LiEnby** [comment]
maybe try not claiming people's mere existence is "poltiical* and 'controversal' or something,

**Comment by ryancdotorg** [comment]
@LiEnby 

1. I'm not involved in SerenityOS.
2. I created this PR fixing the grammar errors.
3. The PR has been merged.
4. I'm a trans enby suing the British government for more gender, please do not lecture me about politics.

**Comment by LiEnby** [comment]
> 4\. I'm a trans enby suing the British government for more gender, please do not lecture me about politics.

see this is exactly the problem your once again validating that somehow the mere existence of trans people / neutral pronouns is 'politics'

**Comment by ryancdotorg** [comment]
@LiEnby Others have made it so... for now. Eventually it will not be. I will not be engaging with you here further, out of respect for the maintainer's notifications. My contact information for other platforms is easy to find if you still want to talk about it.

**Comment by ADKaster** [comment]
@LiEnby Previous discussions were closed due to inflammatory rhetoric. No matter the topic being discussed or points being made, that kind of heated flame war has no place on our issue tracker or pull request queue. Please discuss this elsewhere.

**Comment by BertalanD** [comment]
I was so happy that we could keep this PR's discussion civil and bring a definitely positive change into our code base.

This is why we can't have nice things.

**Comment by LiEnby** [comment]
> @LiEnby Previous discussions were closed due to inflammatory rhetoric. No matter the topic being discussed or points being made, that kind of heated flame war has no place on our issue tracker or pull request queue. Please discuss this elsewhere.

yes yes i know acknowledging gender neutral pronouns and people who aren't men *exist* is ""inflammatory"" and "heated flame waar" sorry my bad. how dare i

**Comment by ADKaster** [comment]
If the discussion three years after the fact in https://github.com/SerenityOS/serenity/pull/6814 is not a flame war I don't know what is. Stop assuming bad faith and projecting the worst possible interpretation of events because we closed GitHub items where people were clearly brigading and not acting in good faith

**Pull request merged**
