### PR TITLE
Shell: Cache PATH for faster tab completion

### PR DESCRIPTION
**Pull request by willmcpherson2**
This patch reduces the O(n) tab completion to something like O(log(n)).
The cache is just a sorted vector of strings and we binary search it to
get a string matching our input, and then check the surrounding strings
to see if we need to remove any characters. Also we no longer stat each
file every time.

Also added an #include in BinarySearch since it was using size_t. Oops.

But what if PATH changes? It's quite easy to just check PATH and recache
if it has changed. But what if you add a file to a directory in PATH...?

### CODE REVIEW

**Comment by awesomekling** [comment]
Please use `<AK/Types.h>` instead of `<stddef.h>` in AK stuff, since `stddef.h` is a `LibC` thing and `AK` wants to be mostly kernel/userspace agnostic.

Also if an executable is added to a directory in `PATH`, we can have a `rehash` command just like bash does. It's a fairly rare thing so meh.

**Comment by bugaevc** [comment]
I guess this (binary search + cutting) works, but wouldn't it be much nicer with a completion tree? (I mean something like Aho-Corasick, but without the backwards links)

**Comment by willmcpherson2** [comment]
@bugaevc 
Yes, kling suggested a trie which fits this problem quite perfectly. I do however like the binary search solution because it is so simple. I might look into implementing a trie template class, although to be honest this problem is becoming quite boring to me now... :laughing:

**Comment by awesomekling** [comment]
We don't always need to use the perfect data structure in the first implementation of something :)

**Comment by bugaevc** [comment]
I don't mean it as an optimization; with the number of executables that we have even *O(n²)* would be fine, what I mean is it might be clearer and *nicer*. But this is also fine with me.

**Pull request merged**
