### PR TITLE
AudioServer: Stop glitching when toggling mute

### PR DESCRIPTION
**Pull request by achronop**
Initialize the `AudioServer::Mixer::m_zero_filled_buffer` to zero. The garbage memory inside that buffer was causing a glitch sound when the user was toggling the mute checkbox or was moving the volume slider on and off zero. Glitching was more obvious if the toggling was happening without any sound being played in parallel.

In addition to that, the `m_zero_filled_buffer` turned to const since there is no intention to modify its content.

Finally, the buffer provided to `OutputMemoryStream` was made a private class member since there is no reason to re-create it in every iteration.

### CODE REVIEW

**Comment by GMTA** [comment]
You should probably split up this commit into two, since you are fixing an issue _and_ trying to increase performance at the same time.

> Finally, the buffer provided to OutputMemoryStream was made a private class member since there is no reason to re-create it in every iteration.

That `Array` has uninitialized inline storage, can you show that this actually increases performance or has other benefits?

**Comment by achronop** [comment]
> You should probably split up this commit into two, since you are fixing an issue _and_ are trying to increase performance at the same time.

Sure, I thought it was small enough to go in one commit.

> That `Array` has uninitialized inline storage, can you show that this actually increases performance or has other benefits?

I have not put it on the profiler. Doing less in that for loop must be better but tbh I do not expect a huge performance increase. My sense is that the piano app glitches less but without numbers. I also did it because we already do the same for `m_zero_filled_buffer` for the same reason (I guess) so it becomes symmetric to that logic. In parallel, we save some buffer allocations on the stack which is not a bad idea for something running all the time.

**Comment by kleinesfilmroellchen** [comment]
If you split up the commit this is good.

**Comment by achronop** [comment]
I have split the patch into two commits. Please, have a look when you have a chance.

**Review by kleinesfilmroellchen — APPROVED** [review]

**Pull request merged**
