### PR TITLE
 LibWeb: Forbid interleaving execution of HTML tasks with same source

### PR DESCRIPTION
**Pull request by kalenikaliaksandr**
From HTML spec https://html.spec.whatwg.org/#definitions-3
"... Note that in this setup, the processing model still enforces that
the user agent would never process events from any one task source out
of order."

I can't come up with an example that is fixed by this change. However,
debugging a bug caused by violating this assumption from the spec is
likely to be very painful.

### CODE REVIEW

**Comment by awesomekling** [comment]
Should we also honor the task source blocked flag in `TaskQueue::has_runnable_tasks()`?

**Comment by kalenikaliaksandr** [comment]
> Should we also honor the task source blocked flag in `TaskQueue::has_runnable_tasks()`?

This method is used to check whether we need to reschedule event processing. I think we need to reschedule even if task is runnable but currently blocked, so eventually it will be executed.

**Comment by awesomekling** [comment]
> > Should we also honor the task source blocked flag in `TaskQueue::has_runnable_tasks()`?
> 
> This method is used to check whether we need to reschedule event processing. I think we need to reschedule even if task is runnable but currently blocked, so eventually it will be executed.

But.. what's the point of rescheduling if all runnable tasks are blocked?

**Comment by kalenikaliaksandr** [comment]
> > > Should we also honor the task source blocked flag in `TaskQueue::has_runnable_tasks()`?
> > 
> > 
> > This method is used to check whether we need to reschedule event processing. I think we need to reschedule even if task is runnable but currently blocked, so eventually it will be executed.
> 
> But.. what's the point of rescheduling if all runnable tasks are blocked?

yes, you are right. we always check whether it is possible to reschedule after task is completed so it should be fine to not reschedule when all runnable tasks are blocked. I updated `has_runnable_tasks()`.

**Pull request merged**
