### PR TITLE
LibWeb: Implement fully reading a response body using streams, and some needless exception handling cleanup

### PR DESCRIPTION
**Pull request by trflynn89**

### CODE REVIEW

**Comment by kennethmyhra** [comment]
With these changes I'm seeing crashes on a few websites:
- https://github.com/SerenityOS/serenity

```
VERIFICATION FAILED: !event_loop.is_backup_incumbent_settings_object_stack_empty() at /home/kennethmyhra/src/serenity/Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp:359
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-ak.so.0(ak_verification_failed+0xef) [0x7d22da0af94f]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::incumbent_settings_object() 0xb1) [0x7d22dac5a751]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0x7636c0) [0x7d22da9636c0]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-js.so.0(+0x36ba8f) [0x7d22d9b6ba8f]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-js.so.0 JS::Promise::perform_then(JS::Value, JS::Value, JS::GCPtr<JS::PromiseCapability>) 0x56) [0x7d22d9c0d886]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::WebIDL::react_to_promise(JS::PromiseCapability const&, JS::GCPtr<JS::HeapFunction<Web::WebIDL::ExceptionOr<JS::Value> (JS::Value)> >, JS::GCPtr<JS::HeapFunction<Web::WebIDL::ExceptionOr<JS::Value> (JS::Value)> >) 0x3e7) [0x7d22dae269d7]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::Streams::readable_stream_default_controller_can_pull_if_needed(Web::Streams::ReadableStreamDefaultController&) 0x114) [0x7d22dadadb44]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::Streams::ReadLoopReadRequest::on_chunk(JS::Value) 0x211) [0x7d22dadc4931]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::Streams::readable_stream_default_controller_enqueue(Web::Streams::ReadableStreamDefaultController&, JS::Value) 0xcc) [0x7d22dadad51c]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0xbbc9f0) [0x7d22dadbc9f0]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0x73c639) [0x7d22da93c639]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::EventLoop::perform_a_microtask_checkpoint() 0x10c) [0x7d22dab7d36c]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::TemporaryExecutionContext::~TemporaryExecutionContext() 0xc) [0x7d22dac6dbec]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0x921dc8) [0x7d22dab21dc8]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0x91ef99) [0x7d22dab1ef99]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0x73c639) [0x7d22da93c639]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0x73c639) [0x7d22da93c639]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::EventLoop::process() 0x4f) [0x7d22dab7d57f]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0xba39c0) [0x7d22dada39c0]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-core.so.0(+0x73889) [0x7d22d97d1889]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-core.so.0 Core::EventReceiver::dispatch_event(Core::Event&, Core::EventReceiver*) 0x75) [0x7d22d97d0dd5]
/home/kennethmyhra/src/serenity/Build/lagom/libexec/WebContent(+0x11839d) [0x594533ec039d]
/lib/x86_64-linux-gnu/libQt6Core.so.6(+0x18113e) [0x7d22dbd8113e]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QTimer::timeout(QTimer::QPrivateSignal) 0x3e) [0x7d22dbd855ce]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QObject::event(QEvent*) 0x1c6) [0x7d22dbd73856]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QCoreApplication::notifyInternal2(QObject*, QEvent*) 0xf5) [0x7d22dbd36975]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QTimerInfoList::activateTimers() 0x369) [0x7d22dbe70e69]
/lib/x86_64-linux-gnu/libQt6Core.so.6(+0x3266f4) [0x7d22dbf266f4]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5ab2c) [0x7d22d8713b2c]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xb646f) [0x7d22d876f46f]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x30) [0x7d22d8711d20]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x70) [0x7d22dbf24420]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) 0x2ba) [0x7d22dbd40cea]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-core.so.0 Core::EventLoop::exec() 0x23) [0x7d22d97c97a3]
/home/kennethmyhra/src/serenity/Build/lagom/libexec/WebContent(+0x121115) [0x594533ec9115]
/home/kennethmyhra/src/serenity/Build/lagom/libexec/WebContent(+0x122ad2) [0x594533ecaad2]
/lib/x86_64-linux-gnu/libc.so.6(+0x28150) [0x7d22d9028150]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89) [0x7d22d9028209]
/home/kennethmyhra/src/serenity/Build/lagom/libexec/WebContent(+0x7dd25) [0x594533e25d25]
97552.725 Ladybird(321314): WebContent process crashed!
```

- https://www.osnews.com/
```
VERIFICATION FAILED: !is_readable_stream_locked(source) at /home/kennethmyhra/src/serenity/Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp:261
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-ak.so.0(ak_verification_failed+0xef) [0x752d0c28694f]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::Streams::readable_stream_pipe_to(Web::Streams::ReadableStream&, Web::Streams::WritableStream&, bool, bool, bool, AK::Optional<JS::Value>) 0x3b6) [0x752d0cfa9e36]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::Fetch::Fetching::fetch_response_handover(JS::Realm&, Web::Fetch::Infrastructure::FetchParams const&, Web::Fetch::Infrastructure::Response&) 0x543) [0x752d0cd124d3]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0x91b5a1) [0x752d0cd1b5a1]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0x90ddff) [0x752d0cd0ddff]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0x928c29) [0x752d0cd28c29]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0x73c639) [0x752d0cb3c639]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::EventLoop::process() 0x4f) [0x752d0cd7d57f]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0xba39c0) [0x752d0cfa39c0]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-core.so.0(+0x73889) [0x752d0c363889]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-core.so.0 Core::EventReceiver::dispatch_event(Core::Event&, Core::EventReceiver*) 0x75) [0x752d0c362dd5]
/home/kennethmyhra/src/serenity/Build/lagom/libexec/WebContent(+0x11839d) [0x63f2c7ceb39d]
/lib/x86_64-linux-gnu/libQt6Core.so.6(+0x18113e) [0x752d0df8113e]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QTimer::timeout(QTimer::QPrivateSignal) 0x3e) [0x752d0df855ce]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QObject::event(QEvent*) 0x1c6) [0x752d0df73856]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QCoreApplication::notifyInternal2(QObject*, QEvent*) 0xf5) [0x752d0df36975]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QTimerInfoList::activateTimers() 0x369) [0x752d0e070e69]
/lib/x86_64-linux-gnu/libQt6Core.so.6(+0x3266ac) [0x752d0e1266ac]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5ab2c) [0x752d0a913b2c]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xb646f) [0x752d0a96f46f]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x30) [0x752d0a911d20]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x70) [0x752d0e124420]
/home/kennethmyhra/src/serenity/Build/lagom/libexec/WebContent(+0x117cb0) [0x63f2c7ceacb0]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-core.so.0 Core::EventLoop::spin_until(AK::Function<bool ()>) 0x4e) [0x752d0c35b82e]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::Platform::EventLoopPluginSerenity::spin_until(JS::SafeFunction<bool ()>) 0xb3) [0x752d0cfa2d63]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::EventLoop::spin_until(JS::SafeFunction<bool ()>) 0xd6) [0x752d0cd7d226]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::HTMLParser::handle_text(Web::HTML::HTMLToken&) 0x342) [0x752d0ce30262]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::HTMLParser::run(Web::HTML::HTMLTokenizer::StopAtInsertionPoint) 0x17e) [0x752d0ce2801e]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::HTMLParser::run(URL::URL const&, Web::HTML::HTMLTokenizer::StopAtInsertionPoint) 0x11f) [0x752d0ce2937f]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-web.so.0(+0xba3125) [0x752d0cfa3125]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-core.so.0(+0x73889) [0x752d0c363889]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-core.so.0 Core::ThreadEventQueue::process() 0x1da) [0x752d0c37946a]
/home/kennethmyhra/src/serenity/Build/lagom/libexec/WebContent(+0x11818f) [0x63f2c7ceb18f]
/home/kennethmyhra/src/serenity/Build/lagom/libexec/WebContent(+0x118da9) [0x63f2c7cebda9]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QCoreApplication::notifyInternal2(QObject*, QEvent*) 0xf5) [0x752d0df36975]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) 0x197) [0x752d0df36b87]
/lib/x86_64-linux-gnu/libQt6Core.so.6(+0x326717) [0x752d0e126717]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5ab2c) [0x752d0a913b2c]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xb646f) [0x752d0a96f46f]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x30) [0x752d0a911d20]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x70) [0x752d0e124420]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) 0x2ba) [0x752d0df40cea]
/home/kennethmyhra/src/serenity/Build/lagom/lib/liblagom-core.so.0 Core::EventLoop::exec() 0x23) [0x752d0c35b7a3]
/home/kennethmyhra/src/serenity/Build/lagom/libexec/WebContent(+0x121115) [0x63f2c7cf4115]
/home/kennethmyhra/src/serenity/Build/lagom/libexec/WebContent(+0x122ad2) [0x63f2c7cf5ad2]
/lib/x86_64-linux-gnu/libc.so.6(+0x28150) [0x752d0b228150]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89) [0x752d0b228209]
/home/kennethmyhra/src/serenity/Build/lagom/libexec/WebContent(+0x7dd25) [0x63f2c7c50d25]
97881.292 Ladybird(322162): WebContent process crashed!
```

**Comment by trflynn89** [comment]
Regarding the second crash, I'm wondering if there's a spec bug here. We acquire a reader in `Body::fully_read`, which from what I understand, "locks" the stream so that no one else can acquire a reader. But that reader is never released. The crash goes away if I do the following:

```diff
     // 2. Let successSteps given a byte sequence bytes be to queue a fetch task to run processBody given bytes, with taskDestination.
-    auto success_steps = [&realm, process_body, task_destination_object](ByteBuffer bytes) {
+    auto success_steps = [this, &realm, process_body, task_destination_object](ByteBuffer bytes) mutable {
+        Streams::readable_stream_default_reader_release(m_stream->reader()->get<JS::NonnullGCPtr<Streams::ReadableStreamDefaultReader>>());
+
         queue_fetch_task(*task_destination_object, JS::create_heap_function(realm.heap(), [process_body, bytes = move(bytes)]() mutable {
             process_body->function()(move(bytes));
         }));
     };

     // 3. Let errorSteps optionally given an exception exception be to queue a fetch task to run processBodyError given exception, with taskDestination.
-    auto error_steps = [&realm, process_body_error, task_destination_object](JS::Value exception) {
+    auto error_steps = [this, &realm, process_body_error, task_destination_object](JS::Value exception) mutable {
+        Streams::readable_stream_default_reader_release(m_stream->reader()->get<JS::NonnullGCPtr<Streams::ReadableStreamDefaultReader>>());
+
         queue_fetch_task(*task_destination_object, JS::create_heap_function(realm.heap(), [process_body_error, exception]() {
             process_body_error->function()(exception);
         }));
     };
```

**Comment by kennethmyhra** [comment]
I am wondering if me having overlooked the Finalize step in AO `readable_stream_pipe_to()` might be the cause of the second crash: https://streams.spec.whatwg.org/#rs-pipeTo-finalize. I think that should also remove the need for the call to `writable_stream_default_writer_close()` I added yesterday

**Comment by kennethmyhra** [comment]
Tried a quick implementation of the Finalize step, but no. Without the `writable_stream_default_writer_close()` it's back to failing the same way as earlier. Reading a bit more into the previous steps I am slightly confused when the Finalize step is supposed to be executed.

For later reference I'll attach what I wrote up here:
```cpp
auto finalize_step = [&realm, writer, reader, promise ](Optional<JS::Value> error = {}) {
    // 1. Perform ! WritableStreamDefaultWriterRelease(writer).
    writable_stream_default_writer_release(writer);

    // FIXME 2. If reader implements ReadableStreamBYOBReader, perform ! ReadableStreamBYOBReaderRelease(reader).

    // 3. Otherwise, perform ! ReadableStreamDefaultReaderRelease(reader).
    // NOTE: This can currently only be a ReadableStreamDefaultReader since we explicitly
    // acquired a ReadableStreamDefaultReader above.
    readable_stream_default_reader_release(reader);

    // FIXME 4. If signal is not undefined, remove abortAlgorithm from signal.

    // 5. If error was given, reject promise with error.
    if (error.has_value())
        WebIDL::reject_promise(realm, promise, error.value());
    // 6. Otherwise, resolve promise with undefined.
    WebIDL::resolve_promise(realm, promise, JS::js_undefined());
};

auto chunk_steps = [&realm, writer](ByteBuffer buffer) {
    auto array_buffer = JS::ArrayBuffer::create(realm, move(buffer));
    auto chunk = JS::Uint8Array::create(realm, array_buffer->byte_length(), *array_buffer);

    auto promise = writable_stream_default_writer_write(writer, chunk);
    WebIDL::resolve_promise(realm, promise, JS::js_undefined());
};

auto success_steps = [finalize_step](ByteBuffer) {
    finalize_step();
};

auto failure_steps = [finalize_step](JS::Value error) {
    finalize_step(error);
};
```

**Comment by trflynn89** [comment]
Ah yeah, I had a quick patch locally that just calls `readable_stream_default_reader_release` on the reader in `readable_stream_pipe_to`'s success/failure callbacks, and also didn't see it help. We do need to do that anyways, otherwise the `source` stream also remains locked, but just doesn't happen to cause an issue on this site

**Comment by trflynn89** [comment]
Dug into it more, this is a case that is hit when a fetch's integrity metadata is set. Smaller repro:
```html
<script>
    const request = new Request("foo.txt");

    fetch(request, { integrity: 'sha256-5CiiNvDROuUE0lHe/1cqDxz4zOW+5IyEb1TkZ2uwuNw=' })
        .then(response => response.text())
        .then(text => {
            console.log(text);
        });
</script>
```

Where foo.txt is:
```
well hello friends
```

In [main fetch](https://fetch.spec.whatwg.org/#concept-main-fetch) step 22, we have (abbreviated):
```
22. If request’s integrity metadata is not the empty string, then:
     3. Let processBody given bytes be these steps:
         3. Run fetch response handover given fetchParams and response.
    4. Fully read response’s body given processBody and processBodyError.
```

So we fully read the body in step 22.4 (which acquires a reader and locks the stream), then when that completes, we run fetch response handover. When that hits the transform stream steps, we enter the "pipe through" AO which asserts the stream is *not* locked, and go boom.

This actually doesn't have anything to do with our ad hoc pipe-to implementation, so I'm leaning towards a spec bug here

**Comment by trflynn89** [comment]
I think we do have another issue with the integrity case with that fixed though, due to calling `read_all_bytes` and then `read_all_chunks` on the same response.

We first call `read_all_bytes` on the body's stream in `Body::fully_read`. The data read here comes from `Fetch::extract_body`, where we `Streams::readable_stream_enqueue` the data onto the stream. When that completes, we close the stream.

So then when `Body::fully_read` completes, we go to the fetch response handover and set up the transform stream. When we pipe-through from the response body's stream, that stream is now closed. So `readable_stream_pipe_to` calling `read_all_chunks` doesn't get any data.

**Comment by trflynn89** [comment]
I've pushed fixes for the crashes, but leaving this a draft for now as the closed stream thing is still a thing. I've opened an issue on the fetch spec github asking about that and releasing the acquired reader from `Body::fully_read`.

**Pull request closed without merging**
