### PR TITLE
Meta: Generalize virtualization toggle

### PR DESCRIPTION
**Pull request by kleinesfilmroellchen**
This now also works on Windows and we rename it from KVM to Virtualization.

### CODE REVIEW

**Review by Mitumaru — APPROVED** [review]

**Review by Mitumaru — APPROVED** [review]

**Review by linusg — CHANGES_REQUESTED** [review]
of -> off in first commit

**Comment by kleinesfilmroellchen** [comment]
That "on" is the preposition as in "on operating system X" or "within operating system X"

**Comment by linusg** [comment]
Sure. But of -> off, not on :^)

**Comment by kleinesfilmroellchen** [comment]
can't read today, apparently :facepalm:

**Pull request merged**
