### PR TITLE
Libraries: Make more syntax highlighters make folding regions

### PR DESCRIPTION
**Pull request by AtkinsSJ**
image

- **C++:** Fold `{ ... }` blocks
- **CSS:** Fold `{ ... }` blocks
- **HTML:** Fold `<!-- ... -->` comments and also show the JS/CSS ones
- **INI:** Fold the contents of a section

Still remaining would be HTML `<foo> ... </foo>` tags, CMake things once #17668 is merged, and... whatever Shell does. :sweat_smile:

### CODE REVIEW

**Comment by LucasChollet** [comment]
It seems that it usually keep the "end delimiter", should we not do the same for INI?
Keeping the new line between sections would be better IMO.

**Comment by AtkinsSJ** [comment]
> It seems that it usually keeps the "end delimiter", should we not do the same for INI? Keeping the new line between sections would be better IMO.

Yeah that would be nicer. Taking a look now. And I just realised that the `Section` token isn't the right one anyway. :sweat_smile:

**Comment by AtkinsSJ** [comment]
Changes:
- INI highlighter now leaves a blank line after each folded section, if possible.

**Comment by awesomekling** [comment]
Super nifty. For HTML, would it make sense to make all elements collapsible?

**Pull request merged**
