### PR TITLE
Base: Add Forum link to ".config"

### PR DESCRIPTION
**Pull request by kimkulak**
Because I dont use Discord I made a forum for SerenityOS, LadyBird and Jakt.
I hope other people will find it useful!
Suggestions are always welcome!

### CODE REVIEW

**Comment by linusg** [comment]
That doesn't seem like a good fit for the default bookmarks.

**Comment by awesomekling** [comment]
Indeed not.

**Comment by kimkulak** [comment]
Thats fair. Are there any plans for a official Forum in the future? Im just throwing my hat in the ring to show that there is some demand for it.

**Comment by mulquin** [comment]
>Are there any plans for

I think if you've been following the project for long enough, you'd know the answer to that question :^)

But in all seriousness, the Discord walled-garden is kind of crappy but hopefully someone will make a Discord-scraper mirror thing one day.

**Pull request closed without merging**
