### PR TITLE
CMake+Userland: Build serenity_lib libraries with a custom SONAME

### PR DESCRIPTION
**Pull request by timschumi**
This allows libraries and binaries to explicitly link against `<library>.so.serenity`, which avoids some confusion if there are other libraries with the same name, such as OpenSSL's `libcrypto`.

This fixes 20 Ports that previously had build issues.

### CODE REVIEW

**Comment by awesomekling** [comment]
If we're going to do this, we should do it for all libraries, not just for a single arbitrary one.

**Comment by timschumi** [comment]
> If we're going to do this, we should do it for all libraries, not just for a single arbitrary one.

I wasn't sure whether I would want to clutter everything with symlinks, and wanted to keep the chances for side effects to a minimum, but sure. I'll change it accordingly and push a new revision after testing.

**Comment by timschumi** [comment]
Updated the PR to include SONAMEs for all SerenityOS libraries, the CI failure seems to be the usual spurious test.

**Comment by awesomekling** [comment]
This seems like it will break things that check for filenames ending in ".so"
Actually, I can only find one example, in DebugSession.cpp:

```cpp
        if (lib_name.ends_with(".so"))
            lib_name = LexicalPath::basename(object_path.value());
```

**Comment by timschumi** [comment]
> This seems like it will break things that check for filenames ending in ".so" Actually, I can only find one example, in DebugSession.cpp:
> 
> ```c++
>         if (lib_name.ends_with(".so"))
>             lib_name = LexicalPath::basename(object_path.value());
> ```

There seem to be a few more, at least when quickly grepping through the source code (UserspaceEmulator, Profiler, etc.).
I'd rather avoid the mental gymnastics of having to generate sonamed libraries without a suffix (especially since it may very well defeat the point of the Pull Request), so extending `ends_with` with another condition would probably be the easiest.

For that, the two options that I can think of would either be something like `contains(".so.")` (which has a _chance_ for a false positive, but I can't imagine it to be too big) or the more strict `ends_with(".so.serenity")`, although the latter might break again if we ever decide to use a different soname (or are dealing with any non-serenity soname libraries).

Which one of those options would be preferable?

**Comment by AtkinsSJ** [comment]
> There seem to be a few more, at least when quickly grepping through the source code (UserspaceEmulator, Profiler, etc.).

If several places check if a file is a library, maybe that should be pulled out into `File::is_shared_library(name)` or something, rather than duplicating that logic around.

**Comment by timschumi** [comment]
> > There seem to be a few more, at least when quickly grepping through the source code (UserspaceEmulator, Profiler, etc.).
> 
> If several places check if a file is a library, maybe that should be pulled out into `File::is_shared_library(name)` or something, rather than duplicating that logic around.

We're only guessing based on the file name, so... `looks_like_shared_library()`?

**Comment by timschumi** [comment]
Updated the PR to commonize the "does this look like a shared library name?" checks and to add support for soname libraries in the process.

The only name-based checks that remain are for `Loader.so` and `libsystem.so`, both of which do not have a soname and therefore don't need to be modified.

**Comment by timschumi** [comment]
Fixed a small issue with path matching in the Profiler, and added more intermediate commits to aid with bisecting in case anything else is revealed to be broken in the future.

**Pull request merged**
