### PR TITLE
DeprecatedFile: Convert a bunch of small Utilities and remove DeprecatedFile::copy_*

### PR DESCRIPTION
**Pull request by BenWiederhake**
This PR migrates `install`, `cp`, `mv`, `usermod`, and a recursive copy in `HackStudio` from DeprecatedFile to LibFileSystem, and removes the old API from DeprecatedFile.

Advances #17129.

### CODE REVIEW

**Comment by BenWiederhake** [comment]
Changes since last push:
- Rebased for convenience
- Made extra sure that the "conflict" due to other DeprecatedFile PRs is correctly resolved.

**Comment by BenWiederhake** [comment]
CI flake: Timeout during On-target test `Shell/if.sh` (which looks like it did nothing for an entire hour).

**Comment by BenWiederhake** [comment]
Changes since last push:
- Rebased to resolve "conflicts" with other DeprecatedFile API removal PRs
- Rebuild to remove CI flakes

**Comment by BenWiederhake** [comment]
Changes since last push:
- Rebased for convenience
- Made extra-super sure that the random test failures in TestThreading aren't due to this PR. Given that these tests are [contain a data race](https://discord.com/channels/830522505605283862/830739873119207426/1108253420135125052), I don't think those failures were due to the PR.

**Review by GMTA — CHANGES_REQUESTED** [review]

**Comment by BenWiederhake** [comment]
Changes since last push:
- Removed a `#include <DeprecatedFile.h>` that is now obsolete
- Rebased for convenience

**Pull request merged**
