### PR TITLE
LibAudio: Fixes for seeking in a FLAC file with no seek table

### PR DESCRIPTION
**Pull request by Zaggy1024**
The FLAC loader did not properly handle files in which there was no seek table. This PR fixes the following:
- Seek table would return a sample after the target seek point if there exists no seek point before the target.
- The FLAC loader would not skip samples forward to the target seek point if it determined that the loader's current position is closer to the target than the found seek point.
- The seek point distance calculation treated a missing previous seek point as a seek point at sample 0, meaning that it would never insert a seek point at 0.
- Seeking used a "tolerance" value to get close enough to the target sample, but we can just seek accurately to the frame containing the target sample instead.

**Old summary:**
> The FLAC loader would often fail to seek back to the start of the file, so to prevent that, we can add a fast path for seeking to zero, since we know we don't need to skip forward from the data start position and can just return immediately.
>
> Seeking to zero is used by HTMLMediaElement to implement looping.
>
> @kleinesfilmroellchen Not sure if this papers over an issue with the seek table, but having a fast path here seems beneficial anyway. I'll be having a look at the seeking system when I work on chunked audio decoding, though, so I'll probably end up fixing any issues I find then.

### CODE REVIEW

**Comment by kleinesfilmroellchen** [comment]
Yes, this is not quite an appropriate fix. (I actually never hit this in testing before.) Please instead insert a seekpoint for sample 0 as soon as we know the data start location.

**Comment by Zaggy1024** [comment]
I've gone through and fixed all the bugs the correct way, I believe, please take another look!

**Review by kleinesfilmroellchen — CHANGES_REQUESTED** [review]
> Previously, the FLAC loader would not skip samples to reach its seek target if it saw that the current sample in the loader is closer to the
target than the seek point it finds. This prevents seeking forward when
there are no seek points past the current position.

I'm not sure what issue the second commit fixes, exactly. If we can't get more close to a target point than where we are right now, there is no point in seeking.

> Instead of using a seek tolerance value to get close enough to the
target, we can skip frames forward until we pass the target, then seek
back to the previous frame.

The reason for the tolerance is to improve seek speed. `tell` incurs a system call, therefore the change with the last commit will perform significantly worse, at an increase in seek accuracy which should not be noticeable.

**Comment by kleinesfilmroellchen** [comment]
The 0 insertion code looks good, though you don't actually force insert a seek point at sample zero, you just rely on the seek point distance logic to do that for you. If there's a seek point less than the tolerance away from sample 0, we still don't get a seek point at 0. It's totally fine to perform this force insert after reading the header.

**Comment by Zaggy1024** [comment]
> I'm not sure what issue the second commit fixes, exactly. If we can't get more close to a target point than where we are right now, there is no point in seeking.

We will not always be as close to the target point as we should be. Firstly, if we have no seek points after the current position in the file, then it will never seek. Also, according to the logic of `should_insert_seekpoint_at()`, when no seek points exist after the current position, seek points will initially be filled in at 5 second intervals, so it will not always have a seek point as close to the target sample as desired.

See here:

https://github.com/SerenityOS/serenity/assets/3149592/f421c39a-a0df-4e47-ae26-7900bca67a7d

> The reason for the tolerance is to improve seek speed. `tell` incurs a system call, therefore the change with the last commit will perform significantly worse, at an increase in seek accuracy which should not be noticeable.

The `seek_tolerance_ms` value is set to 5 seconds, so when seeking forward past the currently available seek points, the seeking inaccuracy is _very_ noticeable. Once seek points are inserted every 1 seconds by the `maximum_seekpoint_distance_ms` value, it is admittedly less noticeable, but still not good.

Also, why should we need to make a system call for `tell()`? That seems like an oversight if it is doing that, since we can track reads in the stream and then update an offset value, even for buffered streams.

However, I would argue that a few milliseconds of extra seek time (obviously more for the first time seeking with no seek table) is a small price to pay for seeking accuracy and consistency. Here is a comparison:

Before my fix:

https://github.com/SerenityOS/serenity/assets/3149592/b23ba690-adcc-4272-883e-9a217d28beaa

After my fix:

https://github.com/SerenityOS/serenity/assets/3149592/d8b4e27b-6588-4307-b8b1-3205be3fd37d

As you can see, the seeking is still quite responsive, but it never jumps back anymore (except due to a bug in LibWeb). I also don't notice a large difference in speed in SoundPlayer in Serenity, either. If there was a noticeable difference, though, we could skip calling `tell()` until we are within seek tolerance of the target, then accurately seek from there.

It's worth noting, this will be a temporary fix until I can replace this seeking logic with a FLAC "demuxer", so that PlaybackManager can take care of accurate seeking (or optionally not do so). I'm not really interested in putting more time into this when it will be superceded soon enough, the goal here was just to have this function correctly so I could ensure that any bugs I'm encountering are not issues with the new abstract audio output system for LibWeb.

**Comment by Zaggy1024** [comment]
> The 0 insertion code looks good, though you don't actually force insert a seek point at sample zero, you just rely on the seek point distance logic to do that for you. If there's a seek point less than the tolerance away from sample 0, we still don't get a seek point at 0. It's totally fine to perform this force insert after reading the header.

Good point, I'll add that. It definitely can't hurt.

**Comment by Zaggy1024** [comment]
Also, it looks like [we already are calling `tell()` every frame](https://github.com/SerenityOS/serenity/blob/5619bb3e04ac6f32bd3e7a10186788de45bd2494/Userland/Libraries/LibAudio/FlacLoader.cpp#L368).

**Review by kleinesfilmroellchen — CHANGES_REQUESTED** [review]
The audio seeking functionality won’t be superseded in every case, since we don’t always have a container with accurate seek data for demuxing purposes.

The seek tolerance should be lower than 5s, sure, but you could have just changed that :) I don’t like how this is factored in the end, there’s too many special cases for already close to seek point vs. further away, and the seeking behavior could be more uniform if the tolerance was always the same

**Comment by Zaggy1024** [comment]
> The audio seeking functionality won’t be superseded in every case, since we don’t always have a container with accurate seek data for demuxing purposes.

I'm not sure what you mean here. FLAC doesn't have accurate seek data either, but we are creating a seek table in memory to make up for that already. If my plan pans out, the seeking to known seek points like your SeekTable does now will be handled by the demuxer, of which there should be one for FLAC as well as all the other audio formats. Once we seek to the most recent random access point, the PlaybackManager will handle seeking accurately to the location that the user has selected, if they haven't disabled that accurate seeking mode.

> The seek tolerance should be lower than 5s, sure, but you could have just changed that :)

I don't believe that having any kind of "seek tolerance" value is of use, given that from my testing it makes a negligible difference in performance. If you can prove a significant difference, I'm open to that, but we also undoubtedly have plenty of optimization headroom in the frame-skipping loop here anyway, so I would argue that this is premature optimization even if it is measurably slower.

Again, sacrificing seeking any seeking accuracy solely for the sake of preventing system calls or a minimal performance difference is both pointless and counter to a good user experience.

> I don’t like how this is factored in the end, there’s too many special cases for already close to seek point vs. further away, and the seeking behavior could be more uniform if the tolerance was always the same

Not sure what you mean by this, the only new condition I added was to return nothing when we don't have a seek point before the target point, which is not an optional fix. Other than that, all the logic I implemented here is essentially the same behavior that LibVideo's PlaybackManager implements (albeit with the layer of abstraction between keyframe seeking and accurate seeking), and that has put the logic to very good use to produce the most efficient and accurate seeking that I believe we can achieve. The condition checking whether we are closer to the seek target than the random access point (which you already had implemented partially) is something that should always be supported.

**Review by kleinesfilmroellchen — APPROVED** [review]
Approval as discussed on Discord.

**Pull request merged**
