### PR TITLE
Base: Add 🎟️ emoji (U+1F39F)

### PR DESCRIPTION
**Pull request by CenTdemeern1**
Just thought I'd contribute something, does this look good?

image

🎟️ - U+1F39F Admission Tickets

### CODE REVIEW

**Comment by djwisdom** [comment]
Optipng to further compress the image, as is always suggested here :^) aside from that lgtm

**Review by Xexxa — CHANGES_REQUESTED** [review]
Please remove "Run the file through OptiPNG" from the commit message.

Except for that, it looks great!

**Comment by CenTdemeern1** [comment]
> Please remove "Run the file through OptiPNG" from the commit message.
> 
> Except for that, it looks great!

Huh? I thought I did that. I'll check and correct it.

**Comment by sin-ack** [comment]
Buggie will complain again because of the merge commit. :^(

**Comment by CenTdemeern1** [comment]
Yep.

**Comment by CenTdemeern1** [comment]
Wait huh? It reappeared? What is even happening

**Comment by CenTdemeern1** [comment]
Closing this because this PR is causing me a lot of trouble, I'll just add it to #15252

**Pull request closed without merging**
