### PR TITLE
FileOperation: Set umask to 0 when creating new files or directories

### PR DESCRIPTION
**Pull request by tcl3**
This ensures that file permissions are correctly preserved.

The issue this PR fixes can be seen here:
https://www.youtube.com/watch?v=54wL_OgKU9I&t=284s

NB: This will also preserve SUID and SGID bits. I'm not sure if this is desirable or not.

### CODE REVIEW

**Comment by gmta** [comment]
Is this the right direction though? If I `cp` a file on my Linux machine, it does not blindly copy over its mode bits - it correctly applies my umask.

**Comment by tcl3** [comment]
> Is this the right direction though? If I `cp` a file on my Linux machine, it does not blindly copy over its mode bits - it correctly applies my umask.

I made this change because this is how my file manager (Dolphin on Linux) behaves. `cp` on Serenity will also apply your umask by default. This change makes the file manager behave like: `cp --preserve src dest`. 

I'm not sure how other file managers behave. I'd be happy to drop this change if the behavior isn't desirable.

**Comment by gmta** [comment]
> I made this change because this is how my file manager (Dolphin on Linux) behaves

You are right, and it's definitely different from how `cp` operates. I'm not sure what the expected behavior in general should be, but at least it's consistent with other applications!

**Comment by tcl3** [comment]
OK, so I've been investigating around how different file managers preserve permissions when copying.

On Linux I tested Dolphin, Nautilus and Thunar (XFCE) on different machines. None of these try to preserve the owner as we are currently trying to do. I'm not sure what I was thinking there to be honest :sweat_smile:. They all preserve the mode bits for files and directories though. The only difference here is that Dolphin does not preserve SUID/SGID bits when copying but Nautilus and Thunar do.

Windows TLDR: I don't think the way Windows behaves is particularly relevant for us.
I also tested Windows Explorer. It preserves the read-only attribute when copying, but beyond that it doesn't preserve any explicitly granted security information, so the copied file tends to inherit its permissions from the parent directory. There are, however certain situations where permissions are preserved: [see here](https://learn.microsoft.com/en-us/troubleshoot/windows-client/windows-security/permissions-on-copying-moving-files) for relevant info.

I've reverted the change I made previously to try and preserve owner information. Our implementation should now work like Nautilus and Thunar, which both behave like `cp --preserve=mode` AFAICT.

I'm going to set this to draft for now because I think this merits further investigation before proceeding.

**Comment by tcl3** [comment]
I'm marking this ready for review as is. All of the graphical file managers I have looked at seem to behave the same way as this implementation; copying as if the `umask` was set to 0 and not attempting to preserve the owner. I'm still not sure whether its a good idea to preserve SUID/SGID bits or not; there doesn't seem to be agreement between different file managers on this.

**Pull request merged**
