### PR TITLE
Base: Add and Change Emoji

### PR DESCRIPTION
**Pull request by OfficialPixelBrush**
combined

#### Changes
- 🕷️ - U+1F577 SPIDER
- 🕸️ - U+1F578 SPIDER WEB
#### Adds
- 🛳 - U+1F6F3 PASSENGER SHIP

### CODE REVIEW

**Comment by trflynn89** [comment]
Unfortunately that spider web is next-to-impossible to see against a light background:
Screenshot_20240322_074725

**Comment by OfficialPixelBrush** [comment]
Gonna look into changing it to more of a grey tone.

**Comment by Xexxa** [comment]
Huurray for a spider that does not look like a weird buggalo :tada: (I made the old one)

**Comment by trflynn89** [comment]
FYI the CI failures are legit:
```
[409/2998] Generating EmojiData.h, EmojiData.cpp
FAILED: Userland/Libraries/LibUnicode/EmojiData.h Userland/Libraries/LibUnicode/EmojiData.cpp /home/runner/work/serenity/serenity/Build/lagom/Userland/Libraries/LibUnicode/EmojiData.h /home/runner/work/serenity/serenity/Build/lagom/Userland/Libraries/LibUnicode/EmojiData.cpp 
cd /home/runner/work/serenity/serenity/Build/lagom/Userland/Libraries/LibUnicode && /home/runner/work/serenity/serenity/Build/lagom/bin/GenerateEmojiData -h EmojiData.h.tmp -c EmojiData.cpp.tmp -e /home/runner/work/serenity/serenity/Build/superbuild/../caches/UCD/emoji-test.txt -s /home/runner/work/serenity/serenity/Base/home/anon/Documents/emoji-serenity.txt -f /home/runner/work/serenity/serenity/Meta/emoji-file-list.txt -r /home/runner/work/serenity/serenity/Base/res/emoji && /usr/local/bin/cmake -E copy_if_different EmojiData.h.tmp EmojiData.h && /usr/local/bin/cmake -E copy_if_different EmojiData.cpp.tmp EmojiData.cpp && /usr/local/bin/cmake -E remove EmojiData.h.tmp EmojiData.cpp.tmp

Error! Emoji entry for U+1F6F3.png not found. Please check emoji-file-list.txt.
```

In order to bundle emoji in applications such as Ladybird, we have to explicitly list them as source files, which we do in this file now:
https://github.com/SerenityOS/serenity/blob/master/Meta/emoji-file-list.txt

**Comment by OfficialPixelBrush** [comment]
Not again.

**Comment by OfficialPixelBrush** [comment]
Apologies for the mess. I wasn't sure how to handle dealing with files that didn't exist on my branch yet >.>

**Comment by trflynn89** [comment]
I'm not sure what happened but that didn't quite work - git looks confused about the emoji-file-list.txt file, it has it marked as a conflict. When you view it in the "Files changed" tab, I'd expect to just see a 1 line diff adding U+1F6F3.

What did you try to get your branch up to date? The general workflow is to rebase your branch on the upstream master branch. Assuming you've added `https://github.com/SerenityOS/serenity.git` as a remote called "upstream", that would look something like:
```git
git fetch upstream master
git rebase upstream/master
```

This is the video we typically send people on discord about rebasing (I haven't watched it myself so idk what it says, but it seems helpful to a lot of people learning rebasing):
https://www.youtube.com/watch?v=ElRzTuYln0M

**Comment by OfficialPixelBrush** [comment]
I JUST WANT TO PUT ALL MY CHANGES INTO ONE COMMIT AAAAAAAAAAAAAAAAAAAAAAAa

**Comment by OfficialPixelBrush** [comment]
thisHurt
I apologize to anyone who had to witness this.

**Pull request merged**
