### PR TITLE
LibGUI: Verify internal_data exists prior return

### PR DESCRIPTION
**Pull request by kevmeyer**
Fixes https://github.com/SerenityOS/serenity/issues/2787

### CODE REVIEW

**Comment by bugaevc** [comment]
No; a valid index with a null internal data is always (in case of the file system model) a mistake of whoever's supplying the index — clearly they've corrupted the index somehow, because the only two ways to create a valid model index are:

* Default-constructing an (invalid) index with `{}`
* Asking the model itself to create a new index into it (with `index()` or `parent_index()`), and the file system model never gives out valid indexes with null data

**Comment by bugaevc** [comment]
Also I believe the table/list view in FileManager (and in the file dialog) are the only times the sorting proxy model is used on a tree-like model (correct me if I'm wrong! 🙂) — so it's important that we find & fix the root cause here, and not just paper over it like this.

**Comment by kevmeyer** [comment]
> No; a valid index with a null internal data is always (in case of the file system model) a mistake of whoever's supplying the index — clearly they've corrupted the index somehow, because the only two ways to create a valid model index are:
> 
> * Default-constructing an (invalid) index with `{}`
> * Asking the model itself to create a new index into it (with `index()` or `parent_index()`), and the file system model never gives out valid indexes with null data

Initially I also had this intention, but only until I saw this default `nullptr` argument here, so I assumed that this might still be a valid case:
https://github.com/SerenityOS/serenity/blob/master/Libraries/LibGUI/Model.h#L114

I found something in the Proxy, where the internal_data got lost.

**Comment by bugaevc** [comment]
> Initially I also had this intention, but only until I saw this default `nullptr` argument here, so I assumed that this might still be a valid case

`create_index()` is a protected method (not a public API for the model users!) to aid the model itself in creating indexes; it's often reasonable to create indexes with nullptr internal data, so that's why it's the default. But it's up to the model to do decide whether it uses internal data or not; and the file system model in particular always creates indexes with non-null internal data.

> I found something in the Proxy, where the internal_data got lost.

It doesn't look like there's a problem there either. Here, we're creating an index into the *proxy* model, so it's up to the proxy model to decide how it uses internal data — and it decides that it doesn't, and that it always sets internal data to null. So it's fine not to override that method.

The important part is for the proxy model to create indexes into the *target model* properly — that is, by calling target's `index()`, and not just creating a row/column index itself. And the proxy model seems to do that correctly:

https://github.com/SerenityOS/serenity/blob/7739497e34f7617cb2f6d838cc3710596b91d13e/Libraries/LibGUI/SortingProxyModel.cpp#L74

**Comment by bugaevc** [comment]
Submitted a proper fix in https://github.com/SerenityOS/serenity/pull/2809

**Comment by awesomekling** [comment]
Superseded by #2809

**Pull request closed without merging**
