### PR TITLE
Meta: Silence warnings from optional CMake packages

### PR DESCRIPTION
**Pull request by trflynn89**
These can be quite verbose on the command line if the packages aren't found. As they do not break the build, let's not spam warnings.

The OpenGL package is also now skipped on macOS, where there's no point in looking for the package anyways.

### CODE REVIEW

**Review by nico — APPROVED** [review]
lg

**Comment by ADKaster** [comment]
OpenGL should work on macOS, @kalenikaliaksandr did some work to enable it, I thought

**Comment by nico** [comment]
> OpenGL should work on macOS, @kalenikaliaksandr did some work to enable it, I thought

Yes, on macOS it's used without a find_package call, see diff :)

**Comment by trflynn89** [comment]
Right, macOS just slaps the framework linkage in there without find_package

**Pull request merged**
