### PR TITLE
LibJS+LibUnicode: Introduce a Unicode library for interacting with UCD files

### PR DESCRIPTION
**Pull request by trflynn89**
Adds LibUnicode for parsing Unicode Character Database (UCD) files at build time and provide accessors to that data.

Updates LibJS to use LibUnicode for `String.prototype.toLowerCase` and `String.prototype.toUpperCase`.

### CODE REVIEW

**Comment by IdanHo** [comment]
If i understand this correctly since the tests are part of lagom (aka they will be run by lagom CI) each lagom CI test run will download the unicode data file? that seems like a waste, it should either be added to the github cache or disabled for CI.

**Comment by trflynn89** [comment]
> If i understand this correctly since the tests are part of lagom (aka they will be run by lagom CI) each lagom CI test run will download the unicode data file? that seems like a waste, it should either be added to the github cache or disabled for CI.

I can set `ENABLE_UNICODE_DATABASE_DOWNLOAD=OFF` in the Lagom workflows, but it'll get weird with `test-js`, since `String.prototype.to{Lower,Upper}Case.js` will fail if the Unicode data isn't generated. So we'd need a way to disable those tests when `ENABLE_UNICODE_DATABASE_DOWNLOAD` is off.

**Comment by IdanHo** [comment]
> I can set `ENABLE_UNICODE_DATABASE_DOWNLOAD=OFF` in the Lagom workflows, but it'll get weird with `test-js`, since `String.prototype.to{Lower,Upper}Case.js` will fail if the Unicode data isn't generated. So we'd need a way to disable those tests when `ENABLE_UNICODE_DATABASE_DOWNLOAD` is off.

In that case the caching approach can also work.

**Review by linusg — APPROVED** [review]
LGTM, wonderful to see how nicely things fall into place now :partying_face:

IMO we can deal with the caching on CI separately, I don't see that as a requirement for getting this merged.

**Comment by trflynn89** [comment]
Looks like I need to compile this out of the fuzz build though:
```
[59/468] Linking CXX executable LibUnicode/CodeGenerators/GenerateUnicodeData
FAILED: LibUnicode/CodeGenerators/GenerateUnicodeData 
: && /usr/bin/clang++ -Wno-unknown-warning-option -Wno-literal-suffix -O2 -Wall -Wextra -Werror -std=c++2a -fPIC -g -Wno-deprecated-copy -Wno-overloaded-virtual -Wno-user-defined-literals -fconstexpr-steps=16777216 -fsanitize=address -fsanitize=fuzzer  -rdynamic LibUnicode/CodeGenerators/CMakeFiles/GenerateUnicodeData.dir/GenerateUnicodeData.cpp.o -o LibUnicode/CodeGenerators/GenerateUnicodeData  libLagomCore.a  -lpthread && :
/usr/bin/ld: LibUnicode/CodeGenerators/CMakeFiles/GenerateUnicodeData.dir/GenerateUnicodeData.cpp.o: in function `main':
/home/runner/work/serenity/serenity/Userland/Libraries/LibUnicode/CodeGenerators/GenerateUnicodeData.cpp:273: multiple definition of `main'; /usr/lib/llvm-12/lib/clang/12.0.1/lib/linux/libclang_rt.fuzzer-x86_64.a(fuzzer.o):(.text.main+0x0): first defined here
/usr/bin/ld: /usr/lib/llvm-12/lib/clang/12.0.1/lib/linux/libclang_rt.fuzzer-x86_64.a(fuzzer.o): in function `main':
(.text.main+0x12): undefined reference to `LLVMFuzzerTestOneInput'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Pull request merged**
