### PR TITLE
TextEditor: fix file opening at line and column position

### LINKED ISSUE #13213: TextEditor: Opening a file at a line and column position is broken
TextEditor has support for opening a file with the cursor at a specific location, with `TextEditor file.txt:line:col`, but when I tested it out today, it was putting the cursor in the wrong place.

Steps:
1. Run `TextEditor README.md:40:6` in the terminal
2. Notice that README.md is opened, but the cursor is at the end of line 1, not at line 40.

I tested a few different files, and line/column combinations, and it always positions the cursor somewhere on line 1.

### PR DESCRIPTION
**Pull request by alichraghi**
Fixes #13213

### CODE REVIEW

**Review by alimpfard — COMMENTED** [review]
- Please add a "Fixes #13213" to the commit description
- Please avoid "Fix..." as the commit message, instead describe the fix itself.

**Comment by simonmcmftx** [comment]
this crashes with no line/column arg since your regex doesn't match a filename without a colon.

**Comment by simonmcm1** [comment]
this crashes with no line/column specifed since your regex doesn't match a filename with no colon

**Review by simonmcm1 — COMMENTED** [review]
this crashes with no line/column specifed since your regex doesn't match a filename with no colon

**Comment by alichraghi** [comment]
because `:` is a valid character in ext2. so `myfile:hello:2:3` will be splitted into [`myfile`, `hello`, `2`, `3`]. instead, see [that regex](https://regex101.com/r/VlKymw/1) works as expected

**Pull request merged**
