### PR TITLE
Kernel/riscv64: Fix typo in naming of Devicetree

### PR DESCRIPTION
**Pull request by odnal**
First time contributor here. Just fixing a small comment  typo: "Fevice Tree" -> "Devicetree". :)

### CODE REVIEW

**Comment by nico** [comment]
Thanks! We call it "DeviceTree" in code, so we should keep the space in the comment. I'd also keep the capitalization and just fix the typo.

**Comment by spholz** [comment]
The devicetree spec calls it "Devicetree" most of the time. But sometimes it is written as "Device Tree", even the spec sometimes calls it that.

I think both variants are fine.

**Comment by Hendiadyoin1** [comment]
I think there technically might be difference between `devicetree` and `device tree`
The former being the spec name, and the latter a generic name or the data described or just the preferred term by other parties than the spec, best to ask @spholz, they have a better memory of this
In the webs you find both as a long form for `FDT` (which is the matter of that comment), the separated version a bit more, although the spec seems to use the concatenated version in the description of the DTB format, and then again uses the separated version for other stuff
And I think we're also not very consistent in what we use where?

Personally I prefer the separated version in this context as that makes it easier to see the acronym

**Comment by nico** [comment]
Well, if we're not consistent atm, then this doesn't make it worse, so let's merge as-is :) If the spec isn't self-consistent, there isn't a ton we can do about it I suppose. Mayb someone's motivated to make us self-consistent in the future.

**Pull request merged**
