### PR TITLE
Kernel: Fix USB hotplug kernel crash

### PR DESCRIPTION
**Pull request by b14ckcat**
Fix the USB hotplug kernel crash bug & move/rename the SysFS USB device information node creation method to be in its respective source file and match the "try_create" idiom that seems to be pretty common across the codebase to reflect that it may return an error.

### CODE REVIEW

**Comment by b14ckcat** [comment]
Will hopefully eventually learn to lint with clang-format before opening the PR...

**Comment by drunderscore** [comment]
I'd have to search the Discord, but it's been said before that new facilities that are fallible by default shouldn't be prefixed with `try_` -- that was only for early implementation alongside existing infallible APIs.

**Comment by b14ckcat** [comment]
> I'd have to search the Discord, but it's been said before that new facilities that are fallible by default shouldn't be prefixed with `try_` -- that was only for early implementation alongside existing infallible APIs.
> 
> EDIT: [This is where it's been said before](https://discord.com/channels/830522505605283862/830739873119207426/943617700847030332)

Commit has been updated

**Review by bgianfo — APPROVED** [review]
LGTM!

**Pull request merged**
