### PR TITLE
LibGUI: Make Layout more comfy to use :^)

### PR DESCRIPTION
**Pull request by AtkinsSJ**
Before:
```c++
(void)TRY(widget.try_set_layout<BoxLayout>(orientation));
widget.layout()->set_margins({ 2, 2, 2, 2 });
widget.layout()->set_spacing(0);

// (Or, saving the value returning by try_set_layout() and then calling set_foo() on it.)

// ...

TRY(widget.layout()->try_add_spacer());
```

After:
```c++
TRY(widget.set_layout<BoxLayout>(orientation, GUI::Margins { 2, 2, 2, 2 }, 0));

// ...

TRY(widget.add_spacer());
```

### CODE REVIEW

**Comment by linusg** [comment]
This has a conflict already, somehow

**Comment by AtkinsSJ** [comment]
Oops, fixed! That was my fault too, I merged a PR that changed some GUI code.

**Comment by krkk** [comment]
this has conflicts. again. (sorryy

**Review by awesomekling — APPROVED** [review]
Comfier!

**Comment by AtkinsSJ** [comment]
Fixed the conflicts again. :^)

**Pull request merged**
