### PR TITLE
Everywhere: Convert `(*foo).bar` to `foo->bar`

### PR DESCRIPTION
**Pull request by creator1creeper1**

### CODE REVIEW

**Comment by mustafaquraish** [comment]
I don't think it's as simple as this, since `(*foo).` and `foo->` can mean different things in C++ depending on how the operators have been overloaded. I'm guessing the build failure is because of this.

**Comment by creator1creeper1** [comment]
I'll make this a draft until it compiles.

**Comment by trflynn89** [comment]
Please do not open PRs that you haven't built and tested locally.

**Comment by creator1creeper1** [comment]
I'll close this for now.

**Pull request closed without merging**
