### PR TITLE
Base: Add more emoji 🤱 💃 🪶 🧉 👩‍👦‍👦 (ᵈᵒ ʷᵉ ʳᵉᵃˡˡʸ ⁿᵉᵉᵈ ᵐᵒʳᵉ ᵉᵐᵒʲᶦ? ʸᵉˢ!)

### PR DESCRIPTION
**Pull request by Xexxa**
x42-screenshot

🤱 - U+1F931 BREAST-FEEDING
💃 - U+1F483 WOMAN DANCING
🚣 - U+1F6A3 PERSON ROWING BOAT
🚣‍♂️ - U+1F6A3 U+200D U+2642 MAN ROWING BOAT
🚣‍♀️ - U+1F6A3 U+200D U+2640 WOMAN ROWING BOAT
⛹️ - U+26F9 PERSON BOUNCING BALL
⛹️‍♂️ - U+26F9 U+200D U+2642 MAN BOUNCING BALL
⛹️‍♀️ - U+26F9 U+200D U+2640 WOMAN BOUNCING BALL
👨‍👦‍👦 - U+1F468 U+200D U+1F466 U+200D U+1F466
FAMILY: MAN, BOY, BOY
👩‍👦 - U+1F469 U+200D U+1F466 FAMILY: WOMAN, BOY
👩‍👦‍👦 - U+1F469 U+200D U+1F466 U+200D U+1F466
FAMILY: WOMAN, BOY, BOY
👩‍👧 - U+1F469 U+200D U+1F467 FAMILY: WOMAN, GIRL
👩‍👧‍👦 - U+1F469 U+200D U+1F467 U+200D U+1F466
FAMILY: WOMAN, GIRL, BOY
👩‍👧‍👧 - U+1F469 U+200D U+1F467 U+200D U+1F467
FAMILY: WOMAN, GIRL, GIRL
🪶 - U+1FAB6 FEATHER
💮 - U+1F4AE WHITE FLOWER
🧉 - U+1F9C9 MATE
⛴️ - U+26F4 FERRY

Coverage: https://emoji.serenityos.net/

### CODE REVIEW

**Comment by diegogangl** [comment]
Looks great, just two things: I'm not sure the white flower is easily understood. Maybe it should be more symmetrical, like the original emoji?

Second, the mate emoji could use a couple improvements. [This what a mate looks like](https://www.google.com/search?q=mate+argentina&hl=en&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj0h5HmkMj8AhXmpJUCHfKfB6wQ_AUoAXoECAEQAw&biw=1371&bih=698&dpr=1.4). The green should lean more towards the yellow, and the straw should be more straight.

**Comment by Xexxa** [comment]
> Looks great, just two things: I'm not sure the white flower is easily understood. Maybe it should be more symmetrical, like the original emoji?
> 
> Second, the mate emoji could use a couple improvements. [This what a mate looks like](https://www.google.com/search?q=mate+argentina&hl=en&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj0h5HmkMj8AhXmpJUCHfKfB6wQ_AUoAXoECAEQAw&biw=1371&bih=698&dpr=1.4). The green should lean more towards the yellow, and the straw should be more straight.

Thank you for your feedback @diegogangl!

Good points, I focused more on the shape on the petal for the white flower then symmetry, never the less on a white background it's hard to see what is part of the background and what is part of the flower. I will change the flower colour a bit and make a new attempt giving the emoji some more symmetry (hopefully without loosing the petal shapes).

Regarding the mate, you are right about the straw! The colour is in line with other vendors [https://emojipedia.org/mate/](https://emojipedia.org/mate/) imho and I'm content with that. But if you have a better colour suggestion then `#17b066` feel free to write it here. :^)

**Comment by Xexxa** [comment]
There we go, adjusted the colour and shape of U+1F4AE WHITE FLOWER(still couldn't get it proportional and keep the shape of the petals) and the straw for U+1F9C9 MATE

image

**Comment by squeek502** [comment]
That woman dancing emoji is really nice!

**Pull request merged**
