### PR TITLE
LibCore: REMOVE DeprecatedFile and IODevice – finally, fallible I/O! :^)

### LINKED ISSUE #17129: Migration: Remove `Core::IODevice` and replace all uses of it with `AK::Stream`s
`AK::Stream` (previously known as `Core::Stream`) is our new(ish) API for reading/writing from files, sockets, and other streamable data.

It replaces:
- `Core::IODevice`
- The file IO parts of `Core::DeprecatedFile`
- ~`AK::Stream`~
- ~`AK::InputStream`~
- ~`AK::OutputStream`~
- ~`AK::DuplexStream`~
- ~`AK::MemoryStream`~

All of these want to instead use one of `AK::Stream`'s subclasses.

### PR DESCRIPTION
**Pull request by BenWiederhake**
This PR removes the now-unused API of DeprecatedFile and IODevice, assuming that the following PRs get merged first (hence the "draft" state):
- [x] #19008 LibPartition
- [x] #19087 Shell
- [x] #19135 LibCore

Closes #17129.

Now all that's left to do is to rewrite the code around each and every `.release_value_but_fixme_should_propagate_errors()` call. :^)

Please take a look and rejoice at how DeprecatedFile usage has dropped over time: https://benwiederhake.github.io/serenity-fixmes/#month

### CODE REVIEW

**Review by konradekk — APPROVED** [review]
well… an approval in advance for removing the code! 😄

**Comment by GMTA** [comment]
@BenWiederhake time to update this! :^)

**Comment by BenWiederhake** [comment]
Changes since last push:
- Undrafted since all dependent PRs have been merged – hooray!
- Rebased

**Comment by BenWiederhake** [comment]
Moved to #19297, because Github broke. This PR should be only 3 commits, not 222, and apparently no amount of force-pushing helps.

**Pull request closed without merging**
