### PR TITLE
Ports: Update readline to version 8.2.13

### PR DESCRIPTION
**Pull request by zaki951**
**Update Readline version to 8.2.13 due to unavailable 8.2 link**

The link for version 8.2 of Readline is no longer available, so we've updated the dependency to version 8.2.13 instead.

### CODE REVIEW

**Comment by nico** [comment]
CI says: `Version in AvailablePorts.md for port readline is incorrect, expected "8.2.13", found "8.2"`.

You have to update Ports/AvailablePorts.md too.

**Comment by timschumi** [comment]
Side note before this gets ninja-merged: Is there any tarball source for readline where we can be somewhat certain that tarballs for old versions stay available?

**Comment by zaki951** [comment]
The previous link is now accessible, no need to upgrade to a newer version.

**Comment by timschumi** [comment]
Updating the package is still something that we might want to do though, and it seems that versions 8.2.1 to 8.2.12 are still missing (so the "other mirror" question also stands).

**Comment by zaki951** [comment]
I couldn't find a better alternative. I think we can keep the current mirror.

**Pull request merged**
