### PR TITLE
Terminal: Added more options for terminal themes

### PR DESCRIPTION
**Pull request by djwisdom**
Added several themes for Terminal

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Did you come up with these color schemes on your own? Their names imply that you didn't.

**Comment by djwisdom** [comment]
> Did you come up with these color schemes on your own? Their names imply that you didn't.

I got the idea from themes existing in Linux terminal and just applied the needed fore/background colors.
If these themes are not needed, no worries. I'll cancel/close this PR.

**Comment by gunnarbeutner** [comment]
Well, I'm not saying that more themes would not be appreciated. However, you can't just take someone else's work (in this case, the color schemes) and claim them as your own. There's no attribution to whoever came up with those color schemes originally - or any mention of a license.

Also, original work would be more in line with the rest of the project. :)

**Comment by djwisdom** [comment]
> Well, I'm not saying that more themes would not be appreciated. However, you can't just take someone else's work (in this case, the color schemes) and claim them as your own. There's no attribution to whoever came up with those color schemes originally - or any mention of a license.
> 
> Also, original work would be more in line with the rest of the project. :)

Got it.

**Comment by djwisdom** [comment]
Closing this PR. Thanks for the very enlightening review.

**Pull request closed without merging**
