### PR TITLE
TextEditor: Fix multi-line cut and paste in the text editor.

### PR DESCRIPTION
**Pull request by mshojatalab**
- Make sure we first normalize in TextDocument::text_in_range()
- in RemoveTextCommand::redo() call set_all_cursors_post_update() rather than set_all_cursors() which tries to re-read an already deleted text which causes the crash.

### CODE REVIEW

**Comment by mshojatalab** [comment]
Hi,
Can someone assist here so I know what these errors are about? It looks to me as they are formatting errors? Is there any script that I could run before creating PR that checks for these kind of errors?
Kind regards,
Mo

**Comment by ADKaster** [comment]
You'll want to install `clang-format-11` to lint your C++ code. Most editors will have a format on save option that is helpful.

There's also a pre-commit-config.yaml file in the repo for use with this tool: https://pre-commit.com/ just have to `pre-commit install` and it should complain about linter tools you are missing.

**Comment by mshojatalab** [comment]
Thanks @ADKaster I installed `clang-format-11` although I don't know what to do with it. I also ran `Meta/lint-ci.sh` script which fails like in the checks here, but again I don't understand what is going wrong and how I can fix it. I sthere a more elaborate report somewhere? Also I built with  `-DBUILD_LAGOM=ON` and ran the `ninja test` which has one failure but again no details. Could you please  give me some pointer how to follow these up?

**Comment by ADKaster** [comment]
The issue is that when clang-format is run on the files you changed, there are differences from the code style of the project present.

Clang format is a code formatter tool. Docs are here
https://clang.llvm.org/docs/ClangFormat.html

If you're using the command line to format, I would do

`clang-format-11  -i Libraries/LibGUI/FileThatWasEdited.cpp` and it will edit (inline) the file to conform to the coding style on the . clang-format file at the root of the repository.

Normally though, you would configure your IDE with a clang-format plugin.

 For example, in vscode you would use this one with the format on save option mentioned in the docs. https://marketplace.visualstudio.com/items?itemName=xaver.clang-format . CLion and Qt creator likely have different extensions or plugins to do this but I haven't used those IDEs myself.

**Comment by mshojatalab** [comment]
Thanks again @ADKaster for the pointers and helps. I think my pre-commit configuration works now, and I think those two issues have been resolved, but now locally pre commit I get error from
`[FAIL]: Meta/check-newlines-at-eof.py`

Also in the end I get this traceback:
Traceback (most recent call last):
  File "Meta/check-newlines-at-eof.py", line 27, in <module>
    capture_output=True
  File "/snap/pre-commit/51/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'


But I haven't touched end of the files and indeed I can see that there is one new line at the end of those files just like the rest of the files in the LibGUI, and when I run `Meta/check-newlines-at-eof.py` manually doesn't complain, so I'm stuck again...

**Comment by linusg** [comment]
> TypeError: init() got an unexpected keyword argument 'capture_output'

The `capture_output` parameter was added in Python 3.7, see https://docs.python.org/3/library/subprocess.html#subprocess.run.

> File "/snap/pre-commit/51/usr/lib/python3.5/subprocess.py", line 693, in run

However you're running this is still using Python 3.5 which had EOL in September 2020.

Upgrade your Python (3.9 is the current  version), if you want to run this script. Anyhow, this script isn't actually complaining here - it's clang-format which wants you to do the following changes:

```diff
diff --git a/Userland/Libraries/LibGUI/TextDocument.h b/Userland/Libraries/LibGUI/TextDocument.h
index 9409991..072a0cd 100644
--- a/Userland/Libraries/LibGUI/TextDocument.h
+++ b/Userland/Libraries/LibGUI/TextDocument.h
@@ -67,7 +67,7 @@ public:
         virtual void document_did_change() = 0;
         virtual void document_did_set_text() = 0;
         virtual void document_did_set_cursor(const TextPosition&) = 0;
-        virtual void document_did_set_cursor_post_update(const TextPosition&) {}
+        virtual void document_did_set_cursor_post_update(const TextPosition&) { }
 
         virtual bool is_automatic_indentation_enabled() const = 0;
         virtual int soft_tab_width() const = 0;
diff --git a/Userland/Libraries/LibGUI/TextEditor.cpp b/Userland/Libraries/LibGUI/TextEditor.cpp
index a31d169..0213e04 100644
--- a/Userland/Libraries/LibGUI/TextEditor.cpp
+++ b/Userland/Libraries/LibGUI/TextEditor.cpp
@@ -1128,8 +1128,7 @@ void TextEditor::set_cursor_post_update(const TextPosition& a_position)
         m_cursor_state = true;
     }
     cursor_did_change();
-    if (m_highlighter)
-    {
+    if (m_highlighter) {
         m_highlighter->cursor_did_change();
     }
 }
```

**Comment by mshojatalab** [comment]
Thanks @linusg, I ended up installing pre-commit using conda as that one uses my python3.8.x.

**Comment by mshojatalab** [comment]
Any idea/pointer about how I can investigate why/How the last test failed would be appreciated.

**Comment by ADKaster** [comment]
@mshojatalab the macOS Lagom tests fail one of the AK::RefPtr tests. However, because that test doesn't fail in linux or on serenity, it's being ignored in CI. As you can see, all the checks are green.

No one who's been interested in the tests has an actual Mac to test on, and debugging tests with a GitHub Actions push is very tedious.

If you do find the issue with the test (AK/Tests/TestRefPtr.cpp) it would resolve this issue: https://github.com/SerenityOS/serenity/issues/4592

**Comment by ADKaster** [comment]
Ah, right. If you want to use ninja test, you'll want to set 

`CTEST_OUTPUT_ON_FAILURE=1 ` in the environment before running tests. You can check the macOS build_and_test_lagom job on your PR to see what it does in the Run CMake Tests step.

https://github.com/SerenityOS/serenity/pull/6040/checks?check_run_id=2247437087

**Comment by mshojatalab** [comment]
This is ready to go in as far as I'm concerned. @linusg

**Comment by bgianfo** [comment]
You should squash your cleanup commits, and fix the commit title to follow what's described in [CONTRIBUTING.md](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md)

**Pull request closed without merging**
