### PR TITLE
LibWeb: Do not invalidate elements with animations in the CSS cascade

### PR DESCRIPTION
**Pull request by mattco98**
See the note added to Animation::cancel for more info. Fixes a regression on shopify.com.

### CODE REVIEW

**Comment by awesomekling** [comment]
Can we add a test?

**Comment by mattco98** [comment]
> Can we add a test?

Added, though I did discover an unrelated bug while doing so :sweat_smile: I'm also not sure why it wants 3 spaces in front of my `println` output

**Comment by awesomekling** [comment]
> > Can we add a test?
> 
> Added, though I did discover an unrelated bug while doing so 😅 I'm also not sure why it wants 3 spaces in front of my `println` output

Thank you!! Tests will make it much easier to work on this code with confidence in the future :)

The spaces in front of the first `println` is a weird artifact of how the testing system works. Nothing to worry about

**Comment by mattco98** [comment]
Sorry, deleted my message since it was wrong. Guess I wasn't quick enough :) The original test I pushed was wrong, I didn't realize how the `style` property on DOM elements worked (there was no extra bug). Should be good now!

**Pull request merged**
