### PR TITLE
Base: Add Keyboard Shortcuts and Tips man pages

### PR DESCRIPTION
**Pull request by cubiclove**
Add a list of system and general keyboard shortcuts as well as a list of Tips & Tricks to man7 (Miscellanea).
Add links to these in the Help Index for easy discoverability for new users.
Delete tips.txt because it's now subsumed into Tips.md

Also add U+229E and U+2318 to Katica Regular 12 because these glyphs represent the Super key on user's keyboards. This will enable the ⊞ Windows key or ⌘ Command key used in this documentation to display (the Help application uses Katica Regular 12).

https://www.unicode.org/charts/PDF/U2200.pdf
⊞ - U+229E SQUARED PLUS
Squared Plus is [used by Wikipedia in place of a Windows key glyph](https://en.wikipedia.org/wiki/Windows_key)

https://www.unicode.org/charts/PDF/U2300.pdf
⌘ - U+2318 PLACE OF INTEREST SIGN
Place of Interest Sign is used by Apple keyboards as the Command symbol

### CODE REVIEW

**Comment by MacDue** [comment]
Where `Super+H` highlight cursor :smile:

**Comment by cubiclove** [comment]
Thanks for letting me know!

**Comment by thankyouverycool** [comment]
You might also delete the welcome app for now since it doesn't have much utility outside tips.txt. `Welcome`-enjoyers, do not lament; our phoenix may rise again...

**Comment by cubiclove** [comment]
I realised this mistake in the early hours and will fix it asap. I will reinstate tips.txt so the Welcome application’s future can be decided outside of this PR.
I, for one, like the Welcome application and think it should stay.

**Pull request closed without merging**
