### PR TITLE
LibWeb: adding initial MutationObserver implementation

### PR DESCRIPTION
**Pull request by lukasz-m-maciejewski**
Just the text change observing is working... barely.

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy

> Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").

**Review by linusg — COMMENTED** [review]
FWIW, @Lubrsi [has been working on an implementation as well][1], and it seems much further along - so no guarantees that we'll end up using this PR.

[1]: https://github.com/SerenityOS/serenity/compare/master...Lubrsi:mutation-observer2

**Comment by lukasz-m-maciejewski** [comment]
> FWIW, @Lubrsi [has been working on an implementation as well](https://github.com/SerenityOS/serenity/compare/master...Lubrsi:mutation-observer2), and it seems much further along - so no guarantees that we'll end up using this PR.

It's about the journey, not the destination. :^)

**Comment by lukasz-m-maciejewski** [comment]
> https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy
> 
> > Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").

Done

**Pull request closed without merging**
