### PR TITLE
Kernel/PCI: Split host bridge code from the Access singleton

### PR DESCRIPTION
**Pull request by supercomputer7**
This is a preparation to solve #11594.

### CODE REVIEW

**Comment by supercomputer7** [comment]
I've read a bunch of articles and other documents to understand the relation between host bridges, PCIe bus communication and PCI domains.
To let others verify some assumptions I applied in these changes here are some links:
https://blogs.oracle.com/linux/post/a-study-of-the-linux-kernel-pci-subsystem-with-qemu
https://www.kernel.org/doc/html/latest/PCI/acpi-info.html
https://stackoverflow.com/questions/66924486/does-modern-operating-systems-use-the-mcfg-acpi-table-to-find-the-registers-of-t
https://elixir.bootlin.com/linux/latest/source/drivers/pci/controller/vmd.c

Last but definitely not the least, I used the dmesg log of @tomuta machine:
https://pastebin.com/raw/fPu7bYLd

It would be awesome if someone can use these references to verify that I didn't mess up here.

**Comment by tomuta** [comment]
I tried these changes on my laptop and this is the output of `PCI::enumerate` looks like is enumerating only the `Intel Corporation Tiger Lake-LP PCI Express Root Port #9 [8086:a0b0]` device.

IMG_20220107_200732339

**Comment by supercomputer7** [comment]
> I tried these changes on my laptop and this is the output of `PCI::enumerate` looks like is enumerating only the `Intel Corporation Volume Management Device NVMe RAID Controller [8086:9a0b]` device.
> 
> IMG_20220107_200732339

This is a preparation to solve that problem, so it makes sense you still can't use this to boot :)

**Comment by tomuta** [comment]
Yeah I get that. Just wanted to give you some feedback as to what happens when you boot with these changes on real hardware :)

**Comment by supercomputer7** [comment]
> > I tried these changes on my laptop and this is the output of `PCI::enumerate` looks like is enumerating only the `Intel Corporation Volume Management Device NVMe RAID Controller [8086:9a0b]` device.
> > IMG_20220107_200732339
> 
> This is a preparation to solve that problem, so it makes sense you still can't use this to boot :)

Just to keep a record here:

> 7:57 PM] supercomputer7:
if (device_identifier.class_code().value() != to_underlying(PCI::ClassID::MassStorage)) {
                return;
            }
[7:57 PM] supercomputer7: that's why you don't see all the controllers :)
[7:58 PM] supercomputer7: https://github.com/SerenityOS/serenity/commit/d2ac40bcd7163b05aca7abb6f8dbb08c9c874ad1#diff-8a716159a6854658daeaae10dbcad11420596bfdf95a429e3899ba74adb293e8
GitHub
Kernel: Enumerate PCI devices a single time in StorageManagement · ...
Previously we were enumerating multiple times for each storage type.
We can easily enumerate once instead.
[7:59 PM] supercomputer7: and that's the reason to the change in the results of your printing :)
[8:00 PM] supercomputer7: my changes have nothing to do with that

**Pull request merged**
