### PR TITLE
LibGUI: Remove unused functions in EditingEngine class

### PR DESCRIPTION
**Pull request by moustafaraafat**
Less dead code :^)

### CODE REVIEW

**Comment by EWouters** [comment]
These functions seem quite useful. Maybe we can configure keyboard shortcuts for it.

**Comment by circl-lastname** [comment]
> These functions seem quite useful. Maybe we can configure keyboard shortcuts for it.

They seem to be done by shortcuts like Ctrl+Left or Right

**Comment by moustafaraafat** [comment]
> > These functions seem quite useful. Maybe we can configure keyboard shortcuts for it.
> 
> They seem to be done by shortcuts like Ctrl+Left or Right

AFAICT they were used for vim editing, but after #6437 the logic is moved to VimEditingEngine itself. So, I guess it's more of a duplicated functionality.

**Review by AtkinsSJ — APPROVED** [review]
Removing dead code is worthwhile. If someone needs it in the future, it'll still be here in the git logs. :^)

**Pull request merged**
