### PR TITLE
Ports: Fix dependency install when port name is not port folder name

### PR DESCRIPTION
**Pull request by EWouters**
There was a bug in the way the .port_include.sh script handled installing dependencies. According to the [documentation](https://github.com/SerenityOS/serenity/tree/master/Ports#depends) the depends array should have port names in it. The port system allows the for the name of the port to be different from the folder where build scripts live. Previously the installdepends function would change directory to the name of the port, hence this was used in the depends list of several ports. These have also been fixed.

### CODE REVIEW

**Comment by GMTA** [comment]
Hm, why do we allow ports to have a different name than the directory they are in? If it's just for the `workdir` default value, I'd rather override that than have the port name be different from the directory name...

**Comment by circl-lastname** [comment]
I see a simpler solution being renaming the internal name of libtiff from tiff, and then making some check that the internal name being the same as the folder name

**Comment by EWouters** [comment]
Yes, it would be possible to have the port name always the same as the folder name, then you don't even have to specify it. However, there are probably cases where this is undesirable. I can't really think of any though.

**Comment by circl-lastname** [comment]
Well, then until such a situation occurs this isn't needed, user friendly names are stored in AvailablePorts.md. (this is my opinion and the final say is up to the maintainers)

**Comment by EWouters** [comment]
If there may be exceptions should I leave the fix in place? Or should I update the documentations to say that the port name should be the same as the port folder name?

If it is the latter we should think about moving the `port=` to something like `port="$(basename $PWD)"` in `.port_include.sh` I think.

**Comment by GMTA** [comment]
@EWouters I would go for the latter solution, if there is an exception then the person finding it can create their own PR ;-)

Although I would leave the explicit `port=` in place, that can always come in handy when you want to extract properties based on the `package.sh` for example. Additionally you could update the port linter to verify that the `port` value is identical to the port st directory name.

**Comment by EWouters** [comment]
If you make a `package.sh` script that can build and install multiple versions of the same port (e.g. `python@3.10` and `python@3.9`) you could need to change the port name.

**Comment by EWouters** [comment]
Sorry I pushed some changes as you merged, can you merge commit dbe126f6fa62d6b39dce7aa9b68f78d72c0f1560 instead? 

There was a bug in the regex for when people specify the port name using `port="$depend"`.

**Comment by linusg** [comment]
Please make a new PR with the fix

**Pull request merged**
