### PR TITLE
Themes: Add Light theme

### PR DESCRIPTION
**Pull request by bcoles**
A Cinammon desktop inspired Light theme to contrast the Dark theme. In my biased opinion, this is prettier than the Silver theme, which is the closest we have to a light theme.

Let there be Light

The theme uses the same shadow PNG files as the Redmond theme. There's precedence for sharing shadows between themes: the Redmond 2000 theme also uses these shadow files.

https://github.com/SerenityOS/serenity/blob/325d9445fdf3f0239abca2fecac7e7ee6a973762/Base/res/themes/Redmond%202000.ini#L72-L75

If the shadows are pretty and useful and worth sharing between themes, it may be worth uncoupling these from a specific theme (or duplicating the files I guess).

I would have liked to have used softer threed shadows, but this results in abhorrent clipping when windows overlap.

disgusting, vile, abhorrent, repugnant

I also would have liked to add soft curved edges to the windows, but this is not supported by WindowServer.

I tried using some custom icons in Cinnamon style, but it looked silly. The default icons look better. Here's an older screenshot:

custom icons

### CODE REVIEW

**Comment by linusg** [comment]
The contrast of most of the text seems quite low, maybe we can make it a little bit darker?

**Comment by bcoles** [comment]
> 
> 
> The contrast of most of the text seems quite low, maybe we can make it a little bit darker?

Which text are you referring to? Most of the windows are inactive in the sample screenshot - the `FileManager` window has focus.

Here's a Cinnamon screenshot for comparison.

image

**Comment by linusg** [comment]
> Most of the windows are inactive in the sample screenshot - the FileManager window has focus.

I know, and yet it doesn't seem to differ from the others:

image
image

Contrast-wise the Cinnamon screenshot looks better to me :)

**Comment by bcoles** [comment]
> 
> 
> > Most of the windows are inactive in the sample screenshot - the FileManager window has focus.
> 
> I know, and yet it doesn't seem to differ from the others:
> 
> image
> image

What do you mean? The text color in the active window doesn't differ from the inactive windows?

These screenshots are of the menus and tree view in the active window. The color will be the same for all windows.

All themes use the same color for inactive window text and active window text, as there's no directive in the theme files to control the text color for inactive windows versus active windows. There's only the `ActiveWindowTitle` and `InactiveWindowTitle` directives to control the text color for active window titles and inactive window titles respectively.

Here's what it looks like with the `WindowText` darkened to black.

image

> Contrast-wise the Cinnamon screenshot looks better to me :)

The Cinnamon window is in focus. Here's the same Cinnamon window in focus and out of focus for comparison.

image

image

**Comment by linusg** [comment]
Specific suggestion: darkening the text colors (except window titles)

```diff
--- a/Base/res/themes/Light.ini
+++ b/Base/res/themes/Light.ini
@@ -28,11 +28,11 @@ MenuStripe=#d9d9d9
 MenuSelection=white
 MenuSelectionText=black
 Window=#e3e3e3
-WindowText=#6b6b6b
+WindowText=#4b4b4b
 Button=#e3e3e3
-ButtonText=#6b6b6b
+ButtonText=#4b4b4b
 Base=white
-BaseText=#6b6b6b
+BaseText=#4b4b4b
 ThreedHighlight=#e3e3e3
 ThreedShadow1=#ababab
 ThreedShadow2=#6b6b6b
@@ -65,7 +65,7 @@ SyntaxIdentifier=#092e64
 SyntaxPreprocessorStatement=#008080
 SyntaxPreprocessorValue=#800000
 Tooltip=#fbeaa0
-TooltipText=#6b6b6b
+TooltipText=#4b4b4b
 Tray=#3b3b3b
 TrayText=white
 
```

Before and after:

image

image

**Comment by bcoles** [comment]
> Specific suggestion: darkening the text colors (except window titles)

done

**Pull request merged**
