### PR TITLE
Port: Update wget to version 1.21.2

### PR DESCRIPTION
**Pull request by BodgeMaster**
This is another one where I just changed the version number and it
worked.

Same note of caution as with the other PR:
> This is my first time contributing so please tell me if I did something wrong.

### CODE REVIEW

**Comment by alimpfard** [comment]
The common format for commit titles is just "category: description", (no further "subcategory:"), this one can easily be reworded to something like "Ports: Update wget to version 1.21.2".

**Comment by BodgeMaster** [comment]
Okay, changed the name.

**Comment by alimpfard** [comment]
That's referring to the commit title, not the PR title :sweat_smile:

**Comment by BodgeMaster** [comment]
Oh, oops, forgot to change that. Will do.

**Pull request merged**
