### PR TITLE
Base+Themes: Update Chillychilly use TitleButtonsIconOnly flag

### PR DESCRIPTION
**Pull request by djwisdom**
Update needed for improved aesthetics and compressed icons

Snapshot:
image

### CODE REVIEW

**Comment by MacDue** [comment]
I'm not super sure about this one, the icons are a little hard to see against the blue/teal title bar.

**Comment by djwisdom** [comment]
> I'm not super sure about this one, the icons are a little hard to see against the blue/teal title bar.

image

How about this?

**Comment by MacDue** [comment]
Not sure about the colour, what about white (or a light blue/teal) with a black outline/shadow (or vice versa)

**Comment by djwisdom** [comment]
> Not sure about the colour, what about white (or a light blue/teal) with a black outline/shadow (or vice versa)

image

You have a fine eye for things that are beautiful. Compliments. :^)

**Comment by MacDue** [comment]
Nice one! I think that looks pretty good :smile:

**Comment by hansejo** [comment]
I think it looks better with the buttons. I think `TitleButtonsIconOnly` should only be used sparingly (like what I did on #113828), or on themes that use their own buttons (e.g. Cupertino).

Serenity really isn't really meant to look modern, so these flat buttons look out-of-place.

Even I'm not super proud of my recent changes to the Light theme. But the theme was already there, and it looked worse with title buttons . ChillyChilly looks better with buttons.

**Comment by djwisdom** [comment]
> I think it looks better with the buttons. I think `TitleButtonsIconOnly` should only be used sparingly (like what I did on #113828), or on themes that use their own buttons (e.g. Cupertino).
> 
> Serenity really isn't really meant to look modern, so these flat buttons look out-of-place.
> 
> Even I'm not super proud of my recent changes to the Light theme. But the theme was already there, and it looked worse with title buttons . ChillyChilly looks better with buttons.

This comment just made my day and warms my heart. Thanks!

So it would seem that until there's a global toggle to enable/disable ` TitleButtonsIconOnly `, the preferred default is for them to adhere with the old / retro 90's look.

Still, this PR is a good example of just because an option is available (TitleButtonsIconOnly=true/false) one should use it. It is true that we have flexibility and artistic expression available and provided for in SerenityOS, but the overall encompassing general '_**look and feel**_' must prevail.

Closing this PR to serve as a learning experience for now and in the future.

This one should also be entitled **"Not just because you could, you should.'**   :^)

**Comment by hansejo** [comment]
@djwisdom 
I still think that you should commit the white icons, they look better than the current ones. Just make sure to keep the buttons :)

**Pull request closed without merging**
