### PR TITLE
More SMP related fixes

### PR DESCRIPTION
**Pull request by tomuta**
Not quite stable yet, crashes pretty easily still. But slowly getting there. This can somewhat schedule threads on all processors now, though for some odd reason it seems to prefer the first cpu and doesn't evenly distribute the workload. Baby steps...

Screenshot from 2020-10-27 21-02-21

EDIT: The bias for CPU#0 is because of this line, but removing it triggers the other crashes much more readily:
https://github.com/SerenityOS/serenity/blob/cff734dadd975b1d5ee5d321c00a7a4110a11662/Kernel/Scheduler.cpp#L872

### CODE REVIEW

**Comment by awesomekling** [comment]
Very interesting development! :star:

**Comment by tomuta** [comment]
Most crashes on boot are now exactly the same as #3885, but in about 1 in 10 attempts it will actually boot to the desktop and is usable for a while until you run into the same bug. And in SystemManager (and in the kernel logs) you can see some threads on the other cpu occasionally now.

**Comment by tomuta** [comment]
If anyone is bored, some help trying to track down #3885 would be much appreciated.

9/10 boots fail with this bug in this branch. It seems that somehow two kernel regions with the same range are created, causing a collision because the page directory is already mapped.

**Comment by Lubrsi** [comment]
For me, it always fails to boot with this:
```
[#0 init_stage2(1:1)]: PATAChannel: PATA Controller found, ID (8086:7010)
[#0 init_stage2(1:1)]: PATAChannel: Bus master IDE: IO c080
[#0 init_stage2(1:1)]: PATAChannel: Name=QEMU HARDDISK, C/H/Spt=26/16/63
[#0 init_stage2(1:1)]: ASSERTION FAILED: !(m_bits & 1)
.././AK/NonnullRefPtr.h:87 in AK::NonnullRefPtr<T>::NonnullRefPtr(AK::NonnullRefPtr<T>::AdoptTag, T&) [with T = Kernel::PATADiskDevice]
[#0 init_stage2(1:1)]: c011ee8d (next: c0928338)
[#0 init_stage2(1:1)]: c012bed2 (next: c0928368)
[#0 init_stage2(1:1)]: c012b4a6 (next: c0928498)
[#0 init_stage2(1:1)]: c012ba04 (next: c09284e8)
[#0 init_stage2(1:1)]: c012baa6 (next: c0928548)
[#0 init_stage2(1:1)]: c01a91be (next: c0928ff8)
[#0 init_stage2(1:1)]: 0 (next: 0)
```

**Comment by alimpfard** [comment]
> For me, it always fails to boot with this

That seems to be because `operator new()` for _eternal_ objects does not round the size up, so we end up with uneven pointers (as `kmalloc_eternal()` doesn't round it up either).

```diff
--- a/AK/kmalloc.h
+++ b/AK/kmalloc.h
@@ -33,7 +33,7 @@
 #ifdef KERNEL
 #    define AK_MAKE_ETERNAL                                               \
     public:                                                               \
-        void* operator new(size_t size) { return kmalloc_eternal(size); } \
+        void* operator new(size_t size) { return kmalloc_eternal(round_up_to_power_of_two(size, 2)); } \
                                                                           \
     private:
```

should fix _that_, I think

**Comment by tomuta** [comment]
> For me, it always fails to boot with this:

Interesting, I've only run into this once so far and I couldn't replicate it.

@alimpfard shouldn't it rather align the pointer than the size? Or is this to fix pointers in arrays?

**Comment by tomuta** [comment]
@alimpfard I created #3900 with your change, slightly different but almost the same.

**Comment by tomuta** [comment]
@Lubrsi I added the fix for that crash to this PR.

**Comment by tomuta** [comment]
Hah I found it... https://github.com/SerenityOS/serenity/pull/3864/commits/2f16e48e5a0813e30c6c03c8186f4d11faba6822 isn't quite right ;-) Has a subtle but fatal logic flaw...

**Comment by tomuta** [comment]
Ok I think the PTE assertion is fixed now, at least I'm no longer running into it. Still either hangs occasionally due to some other odd bugs here and there, but it doesn't take 10 attempts anymore to boot it successfully :) And Browser now starts without crashing it due to this bug.

**Comment by Lubrsi** [comment]
Confirmed fixed 👍 , though I'm not sure how to get multiple cores to show up, changing SMP in run.sh does nothing.

**Comment by alimpfard** [comment]
@Lubrsi pass `smp=on` as a kernel param, e.g. `SERENITY_KERNEL_CMDLINE="smp=on"`

**Pull request closed without merging**
