### PR TITLE
Loader: Support loading non-PIE programs (& fix gcc port)

### PR DESCRIPTION
**Pull request by itamar8910**
This adds support for loading non position independent programs that make use of shared libraries (such us gcc),
and also cleans up the way we configure crt files in the toolchain.

The gcc port now builds & runs :)

### CODE REVIEW

**Comment by awesomekling** [comment]
```
Libraries/LibELF/DynamicLoader.cpp:293:25: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  293 |             patch_ptr = (u32*)relocation.offset();
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by awesomekling** [comment]
Thank you for working on this :D

**Comment by danboid** [comment]
Followink

**Comment by awesomekling** [comment]
Ok I'll hand-merge this. :)

**Comment by awesomekling** [comment]
Merged manually as of bbedd320b5d0bc75bb736ce12711ae283fbe2a77

**Comment by itamar8910** [comment]
thanks @awesomekling, sorry i couldn't get to fixing the CI errors sooner :grimacing:

**Pull request closed without merging**
