### PR TITLE
Meta+Toolchain: Enable linting of shell scripts under Toolchain

### PR DESCRIPTION
**Pull request by bgianfo**
-  __Toolchain: Make BuildPython.sh shellcheck compliant.__

    Shell checks unable to source non-literal includes,
    so inform shellcheck to just ignore this include.

 -  __Toolchain: Make BuildFuseExt2.sh shellcheck compliant.__

    BuildFuseExt2.sh was saying it should be run under /bin/sh but it is
    using bash extensions like pushd/popd, ${BASH_SOURCE[0]}, etc. So just
    run it under bash to avoid any potential issues.

 -  __Toolchain: Fix expansion bugs and make BuildIt.sh shellcheck compliant.__

    BuildIt.sh had a bunch of SC2086 errors, where we were not quoting
    variables in variable expansions. The logic being:

        Quoting variables prevents word splitting and glob expansion,
        and prevents the script from breaking when input contains spaces,
        line feeds, glob characters and such.

        Reference: https://github.com/koalaman/shellcheck/wiki/SC2086

    As bcoles noticed in #6772, shell check actually found a real bug here,
    where the users path did have a space in it.

    Closes: #6772

 - __Meta: Enable linting of shell scripts under Toolchain__

    Now that everything under Toolchain is shellcheck clean,
    remove it from the exception list.

### CODE REVIEW

**Comment by bgianfo** [comment]
cc: @bcoles

**Review by Rada8732 — APPROVED** [review]

**Review by bcoles — APPROVED** [review]
I don't care about shells other than Bash so this looks fine to me.

I'm surprised `shellcheck` doesn't care about `$DIR` versus `${DIR}` but I don't remember why I thought the latter was proffered and can't be bothered to find out why.

`shellcheck` and `Meta/lint-shell-scripts.sh` both pass.

**Comment by linusg** [comment]
Nice! Possible typo in first commit message: `Shell checks unable` -> `Shellcheck is unable`?

**Comment by bcoles** [comment]
> 
> 
> Nice! Possible typo in first commit message: `Shell checks unable` -> `Shellcheck is unable`?

So long as we're nitpicking commit messages...

Inconsistent use of `.` commit subject terminator :

image

Grammar: missing possessive`'` for `user's` :

```
where the users path did have a space in it.
```

**Comment by bgianfo** [comment]
I cleaned up the commit messages as requested, thanks!

**Pull request merged**
