### PR TITLE
Fix jakt cache again

### PR DESCRIPTION
**Pull request by alimpfard**

### CODE REVIEW

**Review by trflynn89 — APPROVED** [review]

**Comment by ADKaster** [comment]
wasm.yaml is still getting the bogus jakt_toolchain_cache_path variable.

**Comment by alimpfard** [comment]
ugh
thanks for catching that

**Comment by nico** [comment]
Out of curiosity, why does the cache-save action call this `jakt_prebuilt_path`, but the cache-restore action calls it `jakt_toolchain_cache_path`? That seems a bit confusing to me – but I don't know the CI setup well, and maybe it makes sense somehow.

**Comment by alimpfard** [comment]
No idea, I just went with the existing naming scheme tbh.

**Comment by alimpfard** [comment]
I think that's about it, hopefully it actually works this time.

**Pull request merged**
