### PR TITLE
Base: Moar emojis

### PR DESCRIPTION
**Pull request by linusg**
```
👀 - U+1F440 EYES
😀 - U+1F600 GRINNING FACE
😃 - U+1F603 SMILING FACE WITH OPEN MOUTH
😄 - U+1F604 SMILING FACE WITH OPEN MOUTH AND SMILING EYES
😆 - U+1F606 SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES
😊 - U+1F60A SMILING FACE WITH SMILING EYES
😎 - U+1F60E SMILING FACE WITH SUNGLASSES
⚠ - U+26A0 WARNING SIGN
⛔ - U+26D4 NO ENTRY
```

image

### CODE REVIEW

**Comment by alimpfard** [comment]
In today's episode: Linus trades LibJS for emojis.

*Modernisation*

**Comment by linusg** [comment]
Plot twist: emojis are an inevitable requirement for LibJS.

(source: literally every CLI tool written in JavaScript ever)

**Comment by Zenyiar** [comment]
Is anyone allowed to make emojis  for serenity?

**Comment by bugaevc** [comment]
> Is anyone allowed to make emojis for serenity?

No, you must be an Officially Certified Emoji Designer by the Serenity Emoji Design Committee 😉

**Comment by Zenyiar** [comment]
lol

**Comment by Zenyiar** [comment]
so anyone can

**Pull request merged**
