### PR TITLE
WebDriver: Implement `POST /session/{id}/window/fullscreen` endpoint

### PR DESCRIPTION
**Pull request by TobyAsE**
More for #15551

### CODE REVIEW

**Comment by TobyAsE** [comment]
I guess this needs updating once #15993 is merged

**Comment by trflynn89** [comment]
So this actually isn't quite right - the fullscreen endpoint isn't OS-level-window fullscreen, rather it is element fullscreen, which has its own spec:
https://fullscreen.spec.whatwg.org/

**Comment by TobyAsE** [comment]
Of course it has its own spec... :makemore:

**Comment by TobyAsE** [comment]
I think this gets a big `FIXME` for now. What we do now is basically `requestFullscreen()` with Options `options["[navigationUI]"] = "show"`.
The WebDriver spec tells us to `fullscreen an element` (where element is the document element) which only sets some flag acc to the fullscreen spec, but does not dispatch the `requestFullscreen()".
Either this is weird, wrong, or I dont understand it yet. Any combination of those is possible.

**Comment by trflynn89** [comment]
The fullscreen step is:
> To fullscreen an element, set element’s [fullscreen flag](https://fullscreen.spec.whatwg.org/#fullscreen-flag) and [add](https://fullscreen.spec.whatwg.org/#top-layer-add) it to its [node document](https://dom.spec.whatwg.org/#concept-node-document)’s [top layer](https://fullscreen.spec.whatwg.org/#top-layer).

Adding to the document's top layer is what makes it actually fullscreen. The top layer is a stacking context that this spec adds, with a set of painting rules that go along with it to A) paint the top layer on top of other elements, B) paint them fullscreen.

If we *do* go with this implementation, let's wait for #15993 so we don't make more work for ourselves to move this API to WebContent.

**Comment by TobyAsE** [comment]
I can't see how adding an element to the top layer triggers `requestFullscreen()`, which has to be called in order to actually go fullscreen.

I'd say we leave it with the fixme since we don't implement anything else from the fullscreen spec.
Let's wait for the other PR and then I'll refactor this one.

**Comment by trflynn89** [comment]
FYI you'll also need to stub out `notify_server_did_request_fullscreen_window` in Ladybird

**Pull request merged**
