### PR TITLE
Everywhere: Use C++ concepts instead of requires clauses  

### PR DESCRIPTION
**Pull request by moustafaraafat**
Also, this patchset removes some unnecessary AK and Detail namespace scoping

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
instaed -> instead

**Comment by AtkinsSJ** [comment]
I know you only just rebased, but this has conflicts again. :sweat_smile:

**Review by AtkinsSJ — APPROVED** [review]
Changes all look nice, but it has conflicts again. :fire: 
Hopefully we can get it merged ASAP once you rebase. :sweat_smile:

**Comment by moustafaraafat** [comment]
It should be ready now.

**Pull request merged**
