### PR TITLE
LibCore: Add support for symbolic permissions without access class

### PR DESCRIPTION
**Pull request by xavier**
The `FilePermissionsMask` parser now accepts symbolic permissions without access class, e.g. `+r`.

### CODE REVIEW

**Comment by roytam1** [comment]
I think this needs to be rebased and maybe minimizing changes by just removing 2 lines in https://github.com/SerenityOS/serenity/commit/12a6ec929297fb7dc699c6093b508a402e1ded04#diff-41ec4ad8e4bab9dc503464f7d422b524d318c2a7fd2de9e1ffd75947f20d61a3R86 ?
tag #11429
maybe also tag #12053

**Comment by xavier** [comment]
The aforementioned commit breaks parsing of permissions with multiple classes like `ug+r` for which there was unfortunately no unit test (my bad). I'll rebase and revert to the initial implementation in this branch which did support that case.

**Comment by bgianfo** [comment]
@boricj can you review this so everyone agrees this is the right implementation?

**Comment by boricj** [comment]
I think that's a correct implementation (haven't checked with the POSIX specification), but the test cases do not cover all cases, at the very least specifying the `a` class explicitly isn't tested.

**Comment by xavier** [comment]
There is a test case for `a=rx`, did you have another more specific test in mind?

**Comment by boricj** [comment]
I missed it with the truncated diff view of the PR... Look good to me.

**Review by boricj — APPROVED** [review]

**Comment by bgianfo** [comment]
Great, thanks for the patch @xavier 🎉

**Pull request merged**
