### PR TITLE
Emoji: Add Transgender Emoji (⚧ U+2617)

### PR DESCRIPTION
**Pull request by CodeLikeCrazE**
This change adds a trans emoji.

### CODE REVIEW

**Comment by davidot** [comment]
Hi welcome to Serenity!

As the bot says we would like a category in the git commit title, for now you have just changed the PR title.
You'll have to use something like `git commit --amend` and force push the new commits to this same branch.
If you get stuck feel free to ask for help on the discord!

**Comment by CodeLikeCrazE** [comment]
Odd, its acting like I added a new commit instead of modifying an existing one.

**Comment by drunderscore** [comment]
Although you did modify the existing commit properly, you merged changes from master into your branch -- you should rather rebase your changes on top of master.

**Comment by drunderscore** [comment]
You may find this video to be helpful for re-writing history with Git:
https://youtu.be/ElRzTuYln0M

**Comment by CodeLikeCrazE** [comment]
I think I fixed it.

**Comment by drunderscore** [comment]
Absolutely did! Commit title+message and it's history are correct :^)

**Comment by davidot** [comment]
Could you use `optipng --strip all <file>` on the image? For me it shrinks it from ~600 bytes to just 140

**Comment by linusg** [comment]
Also, the commit prefix should be `Base:`.

**Comment by linusg** [comment]
Second commit needs squashing:

https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy

> Do: Squash your commits when making revisions after a patch review.

**Pull request merged**
