### PR TITLE
Base: Add new moon phase emojis U+1F311-U+1F31A U+1F31D

### PR DESCRIPTION
**Pull request by djwisdom**
🌑 - U+1F311 NEW MOON
🌒 - U+1F312 WAXING CRESCENT MOON
🌓 - U+1F313 FIRST QUARTER MOON
🌔 - U+1F314 WAXING GIBBOUS MOON
🌕 - U+1F315 FULL MOON
🌖 - U+1F316 WANING GIBBOUS MOON
🌗 - U+1F317 LAST QUARTER MOON
🌘 - U+1F318 WANING CRESCENT MOON
🌙 - U+1F319 CRESCENT MOON
🌚 - U+1F31A NEW MOON FACE
🌝 - U+1F31D FULL MOON FACE

Coverage: https://emoji.serenityos.net

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
I know this is a wildly unpopular opinion, but I would've preferred the other set you posted a screenshot of 🌝

**Comment by djwisdom** [comment]
Now that's a head-ache. okayyy... so how do I go about overriding 'popular opinion?' ;)
I mean, it would be easy for me but what's the use of asking for a vote in the first place? Don't get me wrong here, I love the second option also but ~~~ (s.o.s.) ?

**Comment by linusg** [comment]
Let's do this: just pick whichever ones you prefer and we'll use those :)
If it's this one that's totally ok!

**Comment by djwisdom** [comment]
> Let's do this: just pick whichever ones you prefer and we'll use those :) If it's this one that's totally ok!

Picking ones I personally prefer.. I'll be back!

**Pull request merged**
