### PR TITLE
WindowServer: Add shortcut to quit windows.

### PR DESCRIPTION
**Pull request by daubaris**
An addition of simple Ctrl-Q for quitting windows.

### CODE REVIEW

**Comment by tomuta** [comment]
This seems like a rather odd short cut, which is likely used by some ports. Why not just the universal Alt+F4?

**Comment by daubaris** [comment]
@tomuta Well, I guess there were different suggestions, but the present did not seem to be an unreasonable choice. Relevant discussion can be seen [here](https://freenode.logbot.info/serenityos/20210220#c6983191).

**Comment by awesomekling** [comment]
Either way, this is much too simplistic.

First off, WindowServer uses Logo+ for all of its shortcuts, so if this is a WindowServer thing, Logo+ would be a better prefix.

There are two logical functions here, and I think they might be best implemented on the client side. There's "close window" (Ctrl+W) and "quit application" (Ctrl+Q)

**Comment by daubaris** [comment]
Alright, I guess then I will refactor it to be on the client side.

**Comment by alimpfard** [comment]
@awesomekling while I do agree that this is on the simplistic side, handling this on windowserver isn't that bad of an idea (if it was configurable). it's much better imo to have a global known binding that always does what you expect, if you allow the clients to have their own bindings, they will either have nothing, or have the wrong defaults (compared to the system, and each other).

e.g. we've internalised this, but C-w is "kill word" in a terminal more often than not, but it's "close window" (whatever the meaning of "window" is to that specific application) on many other apps, and it simply does nothing on many others.

**Comment by daubaris** [comment]
I just realized that Alt+F4 already existed. As a result, I am closing the PR as it is completely irrelevant.

**Pull request closed without merging**
