### PR TITLE
Kernel: Minor clean up on Aarch64 – unifying access to MIDR

### PR DESCRIPTION
**Pull request by konradekk**

### CODE REVIEW

**Review by ADKaster — APPROVED** [review]
These changes seem fine, but as has been noted on discord, your commit email does not match any that are registered with your github profile. That's fine, but if you want to track how many commits you've made it would be better to verify that email address with github.

**Comment by konradekk** [comment]
> These changes seem fine, but as has been noted on discord, your commit email does not match any that are registered with your github profile. That's fine, but if you want to track how many commits you've made it would be better to verify that email address with github.
> 
> Also note that getting assigned a `@serenityos.org` email addresses that many contributors use are actually a "perk" of reaching 100 commits in the project, so you might want to use an email address you can actually receive email from 😅

iʼll keep it as is for now—count them on my own and ask when ready, if not a problem! (still plenty commits/changes to make!) 😝

thanks for sharing that! 🙇🏻‍♂️

**Comment by nico** [comment]
I explicitly mentioned that I think that this isn't an improvement and that we shouldn't merge this on another pr and your reaction was to move the commit into a separate pr?

Like, it's possible I'm wrong of course, but discussing the issue instead of sneaking it in seems better.

Can we revert this for now?

**Comment by nico** [comment]
Ping?

**Comment by ADKaster** [comment]
@konradekk What happened here with this change? I hadn't noticed that it was extracted from another PR, or I would have brought it up myself. For what it's worth, it was open for two weeks with a review request open to nico... A conversation here or in #aarch64 on discord is probably warranted so that reviewers don't feel like their feedback is completely ignored.

**Comment by konradekk** [comment]
@ADKaster let us revert that to have proper review!

iʼll cite and answer nicoʼs points in the separate comment here.

**Comment by konradekk** [comment]
in reference to the [other comment](https://github.com/SerenityOS/serenity/pull/17210#issuecomment-1407257100):
> Overall, looks great, but I think it could make do with some squashing. And I don't like the two MainIdRegister commits.

with a [following answer](https://github.com/SerenityOS/serenity/pull/17210#issuecomment-1407380552):
> Removed it from this PR – ignoring my mistake, itʼll be easier to get this PR accepted without that change! 😅

details referring to `MMIO.cpp:15`, with discussion thread started with a [comment](https://github.com/SerenityOS/serenity/pull/17210#discussion_r1089590583):
> Why is this better than what was here before? The code's still device-dependent (cf 0x3f00'0000), and on the LHS the checking code is device-dependent too. That's imho clearer (?)

followed with [reply](https://github.com/SerenityOS/serenity/pull/17210#discussion_r1089719216):
> This is yet another instance of me messing up the pull requests, this belongs to https://github.com/SerenityOS/serenity/pull/17201; Iʼm pretty convinced itʼs a decent change and Iʼll gladly explain the my reasoning there! 🙃

**Comment by konradekk** [comment]
@nico: main id register (MIDR_EL1) is not strictly device-dependent — itʼs just platform-dependent. checking the processor, Cortex A53, in the context of RPi truly tells the version of the platform but the processor check is generic.

we already have one accessor for this register in `Registers.h`, along with other ones and i feel that they neatly abstract the assembly in a single place with clear intent and separated concern (register reads/writes). so this change just reduces the duplication we had. my plan was also to provide more parsing on the data provided in this register – got already some of those but it still needs some polishing.

**Comment by nico** [comment]
Well yes, it's machine-dependent, but so will a bunch of drivers be at the start. Inferring RPi model by arm cortex version for the purpose of deciding which MMIO ranges to use is semantically weird.

**Comment by konradekk** [comment]
Well

> Well yes, it's machine-dependent, but so will a bunch of drivers be at the start. Inferring RPi model by arm cortex version for the purpose of deciding which MMIO ranges to use is semantically weird.

Somewhat agreeing that itʼs awkward; my approach here is that we need not to use RPi-specific means to check what kind of version of it weʼre using. We could abstract that a little with a separate RPi version enumeration, esp. for variants if they differ in a meaningful way. Even if they not such indirection would be helpful to keep things clear (for us those would be two versions of RPi only?).

I was just reusing the code here but with proper names. Still, I can provide this abstraction Iʼve mentioned—would you approve such approach while keeping single MIDR register access place as proposed here?

**Comment by nico** [comment]
From a technical PoV, this PR solves no current problems (as far as I understand) and introduces new ones, and from a social PoV, was landed sneakily on a separate PR after it got pushback on the original PR.

As I said, I'd revert this.

**Comment by konradekk** [comment]
> From a technical PoV, this PR solves no current problems (as far as I understand) and introduces new ones […]
i do not agree—this way no refactoring solves any problems… iʼve indicated a two problem i wanted to solve with that change: (a) code duplication, (b) collecting scattered code into one place. i donʼt of course say that those problems were the most important ones to solve—i wonʼt oppose if people decide to revert it, though.

> […] from a social PoV, was landed sneakily on a separate PR after it got pushback on the original PR.
excuse me—what do you mean by “sneakily”? it has been just extracted from the place it did not belong—that happens all the time. it was placed in a separate pull request which was publicly available for everybody to check and put their comments. finally it was accepted by the maintainer. isnʼt that the way you did go with the changes so far? and iʼm not pointing to andrew here.

i definitely could do better here but i cannot see any sneaking in openly admitting that i want to extract the change as not relevant to the core change subject and indicating a target pull request there. (i feel somewhat offended—maybe i shouldnʼt. iʼm not trying to make you feel bad or force you to any behaviour here.)

iʼd agree then that we should restore the previous state then, esp. it seems i did not convince you on my point. is there something i should do here regarding the revert, or could ask a maintainer to act here? @ADKaster? (excuses for the nuisance)

**Comment by ADKaster** [comment]
https://github.com/SerenityOS/serenity/pull/17505

**Pull request merged**
