### PR TITLE
LibC: Fix Issue #13682 in time.h

### PR DESCRIPTION
**Pull request by MejeC10**
As mentioned in issue #13682, passing in a large value for a time_t, converting it to a tm* using localtime(), and then formatting it with asctime() would crash due to the string being too long. This patch fixes this by increasing the value for the expected length of the string. This patch also decreases the length of the buffer for the formatted string, because it had a lot of unused space that would never had been filled.

### CODE REVIEW

**Comment by circl-lastname** [comment]
This PR adds LibJVM and a bunch of other things, make sure to make a fresh branch off master and then push to a fork

**Comment by MejeC10** [comment]
Sorry, I'm very new to Git and Github, so while the commit history mentions LibJVM, it's not in this commit. When I have time later tonight I'll sqaush the git history so that it only mentions changes to time.h.

**Comment by ADKaster** [comment]
If you have questions on how to structure your branches and such, make sure to reach out in the #development channel on the discord 😁

**Comment by MejeC10** [comment]
I think I have it figured out now, I just have to squash most of the commits when I have the opportunity. I'll be able to do it later tonight.

**Pull request closed without merging**
