### PR TITLE
LibGfx(+Base): Fallback to a default scaled bitmap if the upscaled one failed

### PR DESCRIPTION
**Pull request by krkk**
This makes cursors in a 2x Display Scale without a special upscaled version (such as a Hand cursor) display the 1x version instead.

🏆 Achievement unlocked: get yakbaited yourself (https://github.com/SerenityOS/serenity/pull/14957#issuecomment-1230151257)

### CODE REVIEW

**Review by AtkinsSJ — APPROVED** [review]
Yessss. Let the yak-bait run through you!

**Comment by nico** [comment]
I'm a bit confused. Didn't the existing code do this already?

**Comment by linusg** [comment]
No, it would bail out from the function entirely if any of the `TRY`'s failed due to a missing file. By wrapping that in a lambda and explicitly checking the error type, we can then fall back to a 1x scaled cursor.
(not sure what happend in the error case before though - default cursor perhaps?)

**Comment by krkk** [comment]
> I'm a bit confused. Didn't the existing code do this already?

hmm it looks like we actually used to, before we switched to use the ImageDecoder:  https://github.com/SerenityOS/serenity/commit/880fafd2c59c61b3a86cee4f507c800fd8bce185

> (not sure what happend in the error case before though - default cursor perhaps?)

yep, that’s exactly what happens.

**Comment by nico** [comment]
Ah ok. It used to work like this. Thanks for fixing :)

**Pull request merged**
