### PR TITLE
JSON schema validator

### PR DESCRIPTION
**Pull request by lnzero1dev**
Hello @awesomekling ,

I started implementing a Json Schema Validator with userland program "jsonvalidator" and Library "LibJsonValidator". There might be 100 optimizations and I'm more then happy to get some feedback and improve it :-)

I'd like to work further on this, to make it comply to the whole testsuite of the IETF (currently here: https://github.com/json-schema-org/JSON-Schema-Test-Suite/tree/master/tests/draft2019-09)

What do you think about a JSON schema validator in SerenityOS?

### CODE REVIEW

**Comment by awesomekling** [comment]
Hmm, can you describe the use case here? What would this actually be used for? :)

Either way, it definitely needs to be fixed up to not use naked `new` but instead either `OwnPtr` or `RefPtr` depending on the ownership models :)

**Comment by lnzero1dev** [comment]
> Hmm, can you describe the use case here? What would this actually be used for? :)
> 
> Either way, it definitely needs to be fixed up to not use naked `new` but instead either `OwnPtr` or `RefPtr` depending on the ownership models :)

Ok, the ownership model I will rework, thanks for the hint :-)

The use case for schema validation is to check json data against a defined schema. With that a client can check whether the data it expects conforms to the predefined schema. The schema can also be used to create valid JSON files (manually), document the data format of JSON files and to automate JSON file validiation checks (e.g. CI use cases to check that user only commits JSON files that are correct according to the schema).
A use case within serenity would be for example that the SystemMonitor checks whether the data in /proc/memstat is valid. If SystemMonitor got "valid" from jsonvalidator, it doesn't need to check the data/values by itself and can expect to work properly with the data (like the data has been contracted).
As the /proc/memstat file is provided by the kernel, it might not be necessary to do this, but if some handwritten JSON is being used, or the LibJS / Browser has to deal with "manual" or "corruptable" JSON data, it might be handy to have a JSON schema checker in place :-)

**Comment by awesomekling** [comment]
This looks pretty well made, but I don't understand what we would actually use it for. We shouldn't add code just for the sake of adding code, so can you give some concrete examples of where this will be used in the system?

Which of the existing programs will use this and how? Alternatively, which new program becomes possible with the introduction of this functionality?

I don't mean to be discouraging, I just don't see where this fits into the big picture and I need some help understanding it :)

**Comment by lnzero1dev** [comment]
Hi Andreas, your questions are without any doubt valid.
For my build system generator (meta), I need the meta.json files, describing the build properties of each package. For these files, it would be very nice to check, if the user did not made any errors, has missed something or the best would even to provide a JSON editor, that only let you enter things that are defined in the schema.

Another Idea is to make data formats versionable. For example, I added one Idea with bookmarks into another patchset. The current bookmarks are very simple and have "title" and "url" in a JSON array. In the future, this could be changed to support e.g. a tree structure, to have bookmark folders and so on. When we check the JSON schema, we can directly say whether we must use this or that class to instantiate the bookmarks bar. Furthermore, if the file is currupt and does not fit to any schema, we don't have to try to bring up corrupt items. Instead we should let the user repair the file, if possible.

I guess the schema format is currently mostly used for configuration files (see e.g. schemas at http://schemastore.org/json/). But let's see how that goes in the future :-)

If you don't like it, I'm not sad at all, I'll move it then to the meta repository (or a new one) and maybe try it in the future again, let's see ;-)

**Comment by lnzero1dev** [comment]
Will move this code to my code base :^) Maybe we can use it, if there is a clear use-case. :^)

**Pull request closed without merging**
