### PR TITLE
Base: Add shell script file type icon

### PR DESCRIPTION
**Pull request by electrikmilk**
This adds a file type icon for shell scripts.

Screen Shot 2022-09-05 at 15 29 16

### CODE REVIEW

**Comment by demostanis** [comment]
Should we also make the icons display on other file types too? Bash is in the ports and .bash files are a thing.

**Comment by electrikmilk** [comment]
> Should we also make the icons display on other file types too? Bash is in the ports and .bash files are a thing.

That's a good point, I'll do some quick research on shell script extensions and add them.

**Review by linusg — COMMENTED** [review]
Please don't write commits in title case, just use normal sentence capitalization rules

```
Base: Add shell script file type icon
```

**Comment by electrikmilk** [comment]
Alternate 16x16 file icon if it makes more sense for it to look like a file:

Screen Shot 2022-09-05 at 14 30 23

**Comment by linusg** [comment]
Up to you, but I think I like even more, yeah :)

**Comment by electrikmilk** [comment]
> Up to you, but I think I like even more, yeah :)

Yeah, I think it makes more sense with it being a script and it should be pretty agnostic to any one shell or shell logo.

**Pull request merged**
