### PR TITLE
Base: Add cool emoji

### PR DESCRIPTION
**Pull request by treuks**
Added:
	1F32B      # 🌫 E0.7 fog
	1F361      # 🍡 E0.6 dango
	1F3A3      # 🎣 E0.6 fishing pole
	1F3B4      # 🎴 E0.6 flower playing cards
	1F413      # 🐓 E1.0 rooster
	1F456      # 👖 E0.6 jeans
	1F45C      # 👜 E0.6 handbag
	1F5EF      # 🗯 E0.7 right anger bubble
	1F6B0      # 🚰 E1.0 potable water
	1F6B1      # 🚱 E1.0 non-potable water
	1F6FB      # 🛻 E13.0 pickup truck
	1F9C6      # 🧆 E12.0 falafel
	1F9F4      # 🧴 E11.0 lotion bottle
	1FAB0      # 🪰 E13.0 fly
	1FAB1      # 🪱 E13.0 worm
	1FAD4      # 🫔 E13.0 tamale
	2618       # ☘ E1.0 shamrock
	1F684      # 🚄 E0.6 high-speed train
	1F685      # 🚅 E0.6 bullet train
	1F686      # 🚆 E1.0 train

### CODE REVIEW

**Review by Xexxa — CHANGES_REQUESTED** [review]
High quality emoji(as usual), I'm often amazed how you can use so many shades and colours in an emoji, they often feel like small works of art. For example "1F9F4 (lotion bottle)", your usage of 2-3 more colours then I would have makes it feel more alive and more 3d.

A couple of issues:
- U+1F3B4 and U+1F9F4 has padding on left and right that should be removed.
- U+1F6B0 The tap and the glass looks good, but I think the background should conform.
I would suggest using the same background as #15739(we use these mostly for emoji "buttons" before that PR), or same background as U+1F6BA(in blue?), or same background as U+2139, or same background as U+267F. I do not know what is the best approach is overall, my gut feeling is just "no, not yet another style for signs" ;-)

**Comment by treuks** [comment]
I ended up picking the nice cyan shade of blue as in #15739.

**Comment by treuks** [comment]
aaaand i forgot optipng

**Review by Xexxa — CHANGES_REQUESTED** [review]
You forgot optipng on the changed emoji! :^)

**Review by Xexxa — APPROVED** [review]
LGTM!

**Pull request merged**
