### PR TITLE
Base: Add 13 emoji

### PR DESCRIPTION
**Pull request by hansejo**
U+1F3A4 - Microphone
U+1F3D7 - Crane
U+1F4BC - Briefcase
U+1F4BD - Computer Disk
U+1F4DC - Scroll
U+1F6CF - Bed
U+1F6D1 - Stop Sign
U+1F9A2 - Swan
U+1F37D - Plate with knife and fork
U+1F96A - Sandwich
U+1F438 - Frog
U+1F441 - Eye
U+1F489 - Syringe

Screenshot_20220913_205209

### CODE REVIEW

**Comment by djwisdom** [comment]
lgtm

**Review by Xexxa — APPROVED** [review]
This isn't merged yet? Looks great!

**Comment by Xexxa** [comment]
My favorite is: U+1F4BD - Computer Disk :^)

**Comment by hansejo** [comment]
Yes I hope this gets merged soon otherwise conflicts might start to occur. @AtkinsSJ I saw you merge another set of emoji's, could you also merge this one?

**Pull request merged**
