### PR TITLE
debug input doubling/disappearing issue

### PR DESCRIPTION
**Pull request by deoxxa**
This is just some messy debug code that I'm using to try to get to the
bottom of #156.

Right now this does two things:

1. prints out key events as they're received by the window server
2. prints out warnings when key up/down events don't match

### CODE REVIEW

**Comment by christopherdumas** [comment]
It would probably be best to make this a draft PR, and only make it an "official" PR when you've solved the problem. Debug output isn't really a good PR. Thank you for finding this issue though!

**Comment by deoxxa** [comment]
I can reproduce the warning state pretty reliably, just in the course of normal typing.

This is when I type "asdf" in quick succession:

```
WSScreen::on_receive_keyboard_data: [x] A
WSScreen::on_receive_keyboard_data: [x] F
WSScreen::on_receive_keyboard_data: [ ] A
WSScreen::on_receive_keyboard_data: [ ] S
WSScreen: unexpected key up for S
WSScreen::on_receive_keyboard_data: [ ] D
WSScreen: unexpected key up for D
WSScreen::on_receive_keyboard_data: [ ] F
```

This is when I tap "a" a few times (not even very quickly):

```
WSScreen::on_receive_keyboard_data: [x] A
WSScreen::on_receive_keyboard_data: [ ] A
WSScreen::on_receive_keyboard_data: [x] A
WSScreen::on_receive_keyboard_data: [ ] A
WSScreen::on_receive_keyboard_data: [ ] A
WSScreen: unexpected key up for A
WSScreen::on_receive_keyboard_data: [x] A
WSScreen::on_receive_keyboard_data: [ ] A
WSScreen::on_receive_keyboard_data: [ ] A
WSScreen: unexpected key up for A
WSScreen::on_receive_keyboard_data: [x] A
WSScreen::on_receive_keyboard_data: [ ] A
```

Strangely enough, if I mash a bunch of keys at the same time it usually works perfectly:

```
WSScreen::on_receive_keyboard_data: [x] A
WSScreen::on_receive_keyboard_data: [x] D
WSScreen::on_receive_keyboard_data: [x] F
WSScreen::on_receive_keyboard_data: [x] S
WSScreen::on_receive_keyboard_data: [ ] D
WSScreen::on_receive_keyboard_data: [ ] F
WSScreen::on_receive_keyboard_data: [ ] S
WSScreen::on_receive_keyboard_data: [ ] A
```

...but then it will sometimes fail completely:

```
WSScreen::on_receive_keyboard_data: [x] A
WSScreen::on_receive_keyboard_data: [ ] D
WSScreen: unexpected key up for D
WSScreen::on_receive_keyboard_data: [ ] F
WSScreen: unexpected key up for F
WSScreen::on_receive_keyboard_data: [ ] S
WSScreen: unexpected key up for S
WSScreen::on_receive_keyboard_data: [ ] A
```

It seems like unexpected key up events are slightly more common than unexpected key down events, though I do see both of them regularly.

**Comment by deoxxa** [comment]
@christopherdumas good call - I certainly wasn't expecting this to be merged in! I just couldn't think of an easier way to share my debugging code.

**Comment by christopherdumas** [comment]
No problem, don't sorry about it. Also it looks like you've responded with your debug info to the PR, but that should be in the issue. (:
Yeah I use draft PRs to share my code. You can also fork the project and share links to the fork. But it's not really an issue, we can just transition this into a solution PR or close it.

**Comment by christopherdumas** [comment]
This is a truly bizzare bug though, I'll look into it.

**Comment by deoxxa** [comment]
@awesomekling oh no, this definitely shouldn't be merged. It's not useful for anything other than debugging this problem. I'll actually close this PR, but I'll keep the branch up to date at https://github.com/deoxxa/serenity/tree/debug-key-press-issues until I figure out what's going on.

**Pull request closed without merging**
