### PR TITLE
Base: Add Valve Theme

### PR DESCRIPTION
**Pull request by kimkulak**
I'm new to using advanced GitHub tools and thus i've made some mistakes. I hope this time things will go smoothly!
wwwvalve

### CODE REVIEW

**Comment by LucasChollet** [comment]
Please read the commit linter failure, learn how to rewrite the git history and don't reopen new PR
You can hop in the discord server if you need help

**Comment by kimkulak** [comment]
> Please read the commit linter failure, learn how to rewrite the git history and don't reopen new PR You can hop in the discord server if you need help
I did read the commit linter failure and I did manage to fix this in the past, but I reset my serenity dev enviroment to hopefully make things easier for me. 
Now after amending a commit named "Merge Branch 'master'" it automatically renames itself back to  "Merge branch 'master'". Maybe I didn't go far back enough? Either way I failed miserably. 
As for Discord, I don't use it.

**Comment by ADKaster** [comment]
You should create a branch for each change, and not use your master branch as a pull request branch.

As we follow a rebase workflow for the project, commits from pull requests are directly cherry-picked onto master when the PR is closed. Merge commits are not kosher, and must be removed from your branch. You need to rebase your branch onto master so that there is only one commit in the pull request (for this change). For more complex changes, there should be 1 to N commits on the branch that are entirely unique. Your branch currently has over 13 commits, most of which are merge commits. Please look at this video to see how to perform a proper rebase. And please don't close the pull request or delete your fork, just rewrite the history on your master branch to fix it. 

https://youtu.be/ElRzTuYln0M

**Comment by kimkulak** [comment]
> You should create a branch for each change, and not use your master branch as a pull request branch.
> 
> As we follow a rebase workflow for the project, commits from pull requests are directly cherry-picked onto master when the PR is closed. Merge commits are not kosher, and must be removed from your branch. You need to rebase your branch onto master so that there is only one commit in the pull request (for this change). For more complex changes, there should be 1 to N commits on the branch that are entirely unique. Your branch currently has over 13 commits, most of which are merge commits. Please look at this video to see how to perform a proper rebase. And please don't close the pull request or delete your fork, just rewrite the history on your master branch to fix it.
> 
> https://youtu.be/ElRzTuYln0M

I'm going to watch this video after a break, thank you for the help though!

**Pull request closed without merging**
