### PR TITLE
Multi-instance services & accept socket connections

### PR DESCRIPTION
**Pull request by bugaevc**
You can now ask SystemServer to not only listen for connections on the socket, but to actually accept them, and to spawn an instance of the service for each client connection. In this case, it's the accepted, not listening, socket that the service processes will receive using socket takeover.

I haven't added a helper like the existing `Core::LocalServer::take_over_from_system_server()` to `Core::LocalSocket`, because I don't want to duplicate the logic, and I have no idea where a shared version of this could live. Suggestions welcome.

### CODE REVIEW

**Comment by alimpfard** [comment]
I'm very confused about the utility of this...but it sounds like a neat capability to have.

**Comment by bugaevc** [comment]
Note that:
* This (accepting connections) is how inetd has worked on other Unixes for ages
* This was requested by @awesomekling yesterday, for LibWeb/LibJS sandboxing
* SystemServer was always meant to implement this one day when the need arises; apparently that day was yesterday

As to utility, it's twofold:
* You don't have to run a server to just listen for connections — this is like exit on idle, on steroids. But this also means separate instance of the service are, well, separate, and cannot directly communicate, so it's not a good fit for *every* service. But I imagine some services, like perhaps ProtocolServer or NotificationServer, could use this.
* It should, generally, be easier to use an already accepted socket than to listen on a listening socket. But we have enough utilities in place (`Core::LocalServer`) that this doesn't matter.

**Comment by alimpfard** [comment]
Hmmm...it seems I missed quite a bit of stuff yesterday.

That makes sense, I can see how it can be useful for on-demand isolated servers.
Although I fear for the day someone decides to initialise a billion things on start and then finds this, but that's probably an unfounded fear.

Thanks for explaining this~

**Comment by awesomekling** [comment]
This is great, thank you @bugaevc! :)

**Pull request merged**
