### PR TITLE
LibVT: Auto-scroll the terminal

### LINKED ISSUE #4267: Terminal: Cannot select more than a windowful of text
It is not currently possible to click and drag to select and highlight more text than can be displayed in the terminal window without scrolling. The terminal should scroll to allow you to select more than a full terminal window of text.

### PR DESCRIPTION
**Pull request by metalvoidzz**
Fixes #4267

### CODE REVIEW

**Comment by danboid** [comment]
This'll be a pretty major upgrade to the terminal!

Thanks @metalvoidzz !

**Comment by supex0fan** [comment]
I'm not a reviewer, but I was looking at this issue my self and didn't get around to it. That being said I think this issue should be resolved at the LibGUI level as almost every scrollable application should scroll when the cursor is dragged behind the window.

**Comment by danboid** [comment]
@supex0fan That makes sense. TextEditor supports autoscrolling but currently Terminal and Browser don't. TE would prob need to be adapted if this is becoming a LibGUI thing.

@awesomekling

**Comment by awesomekling** [comment]
>I'm not a reviewer

Everyone can review code :)

>I think this issue should be resolved at the LibGUI level as almost every scrollable application should scroll when the cursor is dragged behind the window.

Right, it would be nice to have this functionality in **GUI::ScrollableWidget** (and make **VT::TerminalWidget** inherit it from there.)

It's okay to only do this for the terminal in this PR though, we don't have to make everything perfect right away.

**Pull request merged**
