### PR TITLE
Kernel: Update key_code_count

### PR DESCRIPTION
**Pull request by aatosmajava**
This was not updated when the Menu button was added.

### CODE REVIEW

**Review by TobyAsE — APPROVED** [review]
LGTM
Are there any bugs this introduced?

**Comment by aatosmajava** [comment]
Nope, it's only used by Piano as far a I know. I was just browsing the keyboard code.

**Comment by TobyAsE** [comment]
Good spot!

**Comment by IdanHo** [comment]
We can add a `__Count` entry to the enum, to make sure this will be done automatically in the future.

**Comment by linusg** [comment]
> We can add a __Count entry to the enum, to make sure this will be done automatically in the future.

This is an `enum`, not an `enum class` - doesn't that conflict once you have more than one of those with a `__Count`?

**Comment by IdanHo** [comment]
> This is an `enum`, not an `enum class` - doesn't that conflict once you have more than one of those with a `__Count`?

It does, missed that, good catch.

**Pull request merged**
