### PR TITLE
LibJS: Set name of anonymous functions during assignment

### PR DESCRIPTION
**Pull request by linusg**
Apparently that's a thing :^)

### CODE REVIEW

**Comment by alimpfard** [comment]
what if...you assign it to multiple things?
javascript is _weird_

**Comment by alimpfard** [comment]
shot-2020-05-03_00-34-55
as if that explains it.
javascript is _weird_

**Comment by linusg** [comment]
> what if...you assign it to multiple things?

Great question! I didn't even think about this (the implementation still gets it right!). The last variable name is supposed to be the final function name:

```js
a = b = function() {}
a.name; // "b"
b.name; // "b"
```

Will add a test case.

> javascript is weird

you keep saying that lol - I can't disagree...

**Comment by alimpfard** [comment]
> The last variable name is supposed to be the final function name

It looks to more like `a = b = foo` is parsed as `a = (b = foo)`, and so the function gets `b` as its name...

> you keep saying that lol - I can't disagree...

The damn language has so many weird quirks;
e.g. why even give a name to an anonymous function? that makes no sense

**Comment by linusg** [comment]
> shot-2020-05-03_00-34-55
> as if that explains it.

image

Damn, that's worse than I expected...

**Comment by linusg** [comment]
```js
a = [function(){}, function(){}, function(){}]]
a[0].name; // "a"
a[1].name; // "a"
a[2].name; // "a"
```

ffs

**Comment by alimpfard** [comment]
>a = [function(){}, function(){}, function(){}];
a[0].name; // "a"
a[1].name; // "a"
a[2].name; // "a"

what the...

**Comment by awesomekling** [comment]
Based on countless experiences working on production browsers in the past, this sort of quirk usually exists because some website somewhere depended on it at some point, and browser vendors decided it was easier to maintain the behavior (and keep websites working) instead than switching to something sane. Then the Standards People came along and codified whatever the browsers were doing and boom, here we are. (Disclaimer: this particular thing may be an exception, I don't know) :)

**Pull request merged**
