### PR TITLE
Toolchain: Build pretty. Use xz, not gz. Use sha256, not md5 

### PR DESCRIPTION
**Pull request by bleys**
We were already using lzma in the clang build, but not specifying it as a dependency. I fixed the dependency specs and switched the downloads in BuildIt.sh to xz instead of gz. The files are almost half the size. Also added a note about potential slowness of the GNU servers and an alternative (I started this edit because my initial download took nearly an hour off the GNU server).

It is safer to use sha256 than md5. Even sha1 is broken now: https://github.com/NixOS/nixpkgs/issues/77238

I fully integrated the buildstep helper into the BuildIt.sh output. Also, printf = better echo (easier to use formatting and doesn't fork another process). Output formatting made so it is easier to follow the build process in general.

### CODE REVIEW

**Comment by ADKaster** [comment]
One thing to point out about the use of md5. It's not for any Sevier

**Comment by bleys** [comment]
> In my opinion this could/should rather be split into three commits, since build output doesn't have much to do with the compression algorithm, and the compression algorithm doesn't have much to do with the hash algorithm. It would also make it easier to review and bisect down the line.

@timschumi Yes, agreed. I have done that work now. Thanks!

**Comment by bleys** [comment]
> In addition to the MD5 vs. SHA-256 discussion: (most) people are blindly trusting the scripts to download, compile _and_ execute the resulting binaries on their systems, so making sure the attack plane for a malicious actor is as small as possible is really worthwhile here.

Yes, exactly. It seems in other places in Toolchain we are already using SHA256 checks (e.g., [BuildPython](https://github.com/SerenityOS/serenity/blob/ceb3328877697763987f8575737d111fb592fba3/Toolchain/BuildPython.sh#L26) ) so really BuildIt is the straggler anyway. This just makes it all consistent.

Re: gz vs xz. LZMA (xz) seems like a pretty universal win. XZ itself is a tiny package to require (and indeed we already need it for the Clang build) and the file size savings are significant. Many packagers prefer and default to XZ for good reason.

It looks like a good portion of the packages in Ports also use xz, so it's good to get it into our build dependencies for that reason as well. Another good thing to do might be to go in and patch all the packages in Ports which are currently using gz and change them to pull xz files where available.

```
➜ grep "tar\.gz" ./serenity/Ports/*/*.sh | wc -l
135
➜ grep "tar\.xz" ./serenity/Ports/*/*.sh | wc -l
30
```

**Comment by bleys** [comment]
While I'm thinking about this: Another patch for Ports might be to not assume we have access to GNU tar's compression detection here: [Ports/.port_include.sh](https://github.com/SerenityOS/serenity/blob/ceb3328877697763987f8575737d111fb592fba3/Ports/.port_include.sh#L301-L302)

Relevant: https://unix.stackexchange.com/questions/101561/what-are-the-differences-between-bsdtar-and-gnu-tar

**Comment by bleys** [comment]
> The only places where I can see formatting being used is [here](https://github.com/SerenityOS/serenity/pull/10449/commits/3305b4efd5d9bf5db127c7c814f24b7e6d07055f#diff-27e8b38fa0c632f71ab59fc31a34847ece5cbbc670f74514d313217fb25637a3R75-R76), while all the other `printf` calls still use variables directly. At that point I'd suggest converting all of them or none of them.

I converted the rest of the printf variable inclusions.

**Pull request closed without merging**
