### PR TITLE
Themes: Add Windows95 Theme

### PR DESCRIPTION
**Pull request by jsdevv**
Adds a classical theme from the 90's.

image

### CODE REVIEW

**Comment by sunverwerth** [comment]
Isn't that the same as the Redmond theme? Also I don't think we should have trademarked names like Windows95 in the UI.

**Comment by jsdevv** [comment]
So, should I remove this or rename it or?

**Comment by sunverwerth** [comment]
I gues we can keep it.
We already have Redmond(Windows 3.0) Redmond2000 (Windows 2000) so you should rename it to Redmond95

**Comment by awesomekling** [comment]
The existing "Redmond" theme is already using the colors from Windows 95.

**Pull request closed without merging**
