### PR TITLE
Revamp SystemDialog to be more Win95-like

### PR DESCRIPTION
**Pull request by thatlittlegit**
This PR changes SystemDialog to look more like Windows 95's shutdown box, instead of being a simple yes/no messagebox. It also tells SystemDialog to get all of its potential actions (Restart, Shut Down...) from /etc/SystemDialog.ini.

My only big concern with this code is that it uses `/bin/Shell` to execute its commands. This is kinda nice, because it makes unveiling really easy, but is also a bit of a pain because it doesn't really feel right to be using the shell here. I'm not really sure how to fix it: sure, right now we could just split the string to get arguments, but then it doesn't work right if quotes got involved.

(Note that this doesn't fix the bug about shutdown() having permission denied: SystemDialog is still run as `anon`.)

### CODE REVIEW

**Comment by awesomekling** [comment]
The original purpose of the `SystemDialog` program was to provide a way for `WindowServer` to open a message box. This was relevant back before `SystemMenu` did not exist.

One possibility could be that we embed the functionality inside `SystemMenu` instead of having this in a separate program.

When it comes to `/bin/shutdown`, I think we could make it setuid-root and having it only executable by members of a specific group. Perhaps the `phys` group (intended for users with physical access to the machine.)

**Comment by thatlittlegit** [comment]
I tried moving SystemDialog into SystemMenu and made shutdown/reboot only runnable by `phys`. One problem I noticed there is that since `anon` isn't in `phys`, he still can't shut down the machine.

I also removed the configuration file that I put in, since I didn't want to pledge `wpath` to SystemMenu.

**Comment by awesomekling** [comment]
Looks good :)
We can just make `anon` a member of `phys`, I think that would be okay.

**Comment by awesomekling** [comment]
Totally agree that it would be nice to have a read-only `Core::ConfigFile`.

**Pull request merged**
