### PR TITLE
LibWeb+AK: Get Google Street View working, along with SVG viewboxes, transforms, scaling, and hit testing!

### PR DESCRIPTION
**Pull request by MacDue**
This was a much bigger yak hole than I expected, all the changes made in this PR are done to get Google Street View functioning. I've tried to order commits best I can, but it's a little tricky (since I create the commits as a final step from a pile of `git commit -m "WIP"` :yakkie:)

Rough order: 
 - Commits 1 & 2 fix two stacking context hit-testing cases, that previously failed. 
	- Both are needed to interact with street view and move the camera around.
 - Commit 3 fixes the parsing and then re-serialization of URLs that contain percent encoded data, that does not use the default percent encoding sets.
    - The previous percent decoding during parsing was non spec-compliant and broke street view URLS.
		- (streetview URLs contain a percent encoded URL within their path... its weird)
 - Commit 5 parses and applies the `fill-opacity` attribute for SVG paths/elements
	- This is needed to correctly paint some UI elements
 - Commit 9 allows SVGs to scale on zoom... Kinda akward this did not work before, given they're scalable :P
 - Commit 11 fixes parsing `width/height="<unitless length>` on documents with `<!DOCTYPE html>`
 - All other commits implement SVG transforms and fix SVG viewboxes (for a bunch of cases)
	- This is needed UI elements (such as the streetview cursor) to show up and be rendered in the correct place.
	- The layout and hit testing changes are needed both to render things correctly, and to stop SVGs blocking all hit testing.

**Demos**

**Using looking around on Google Street View** (as you can tell it's a little laggy :^)).

[screen-capture - 2023-04-10T230557.488.webm](https://user-images.githubusercontent.com/11597044/231008057-82e584ba-5402-43e7-b8ab-77791e20036b.webm)

**Moving around on Google Street View**

[screen-capture - 2023-04-10T215856.132.webm](https://user-images.githubusercontent.com/11597044/231007277-4c6a0994-ab07-4996-a233-459dc960f89a.webm)

**Transformed SVGs, all with each of which have a `viewbox`, with working hit testing:**
image

**Scaling SVGs:**

[screen-capture - 2023-04-10T131827.400.webm](https://user-images.githubusercontent.com/11597044/230900278-169acf70-5680-4209-9f07-33e2883a7edb.webm)

### CODE REVIEW

**Comment by MacDue** [comment]
(Working my be a _slight_ exaggeration, it's very slow, and freezes.... a lot :^))

**Comment by MacDue** [comment]
Marking as draft until I can figure out the hit testing changes, other commits should be reviewable.

**Comment by awesomekling** [comment]
There are some hacks in here that need more love, but I think we can administer that love in-tree :)

**Comment by linusg** [comment]
Posting re-encoded videos here so I can hotlink them:

https://user-images.githubusercontent.com/19366641/232325630-4062626b-e0c3-44db-8c7f-cf01232309b2.mp4

https://user-images.githubusercontent.com/19366641/232325657-d6d66716-ce87-49e9-a5cf-b917c2231c8a.mp4

**Pull request merged**
