### PR TITLE
LibPDF+LibGfx: Add initial support for truetype-based type0 fonts

### PR DESCRIPTION
**Pull request by nico**
From a LibPDF point of view, this is a _huge_ progression: Before this, 303 of my 1000 test files rendered without any diagnostics (which doesn't mean that they look 100% correct, but they probably look kinda decent). After this, 652 of my 1000 test files render without any diagnostics.

Disclaimers, similar to what's on #23202 (and most of the
prerequisites mentioned there are needed for this too):

* Only supports the `Identity-H` type0 cmap at the moment
* Doesn't support vertical text yet
* Only supports the `Identity` CIDToGIDMap at the moment
  (this one is a truetype-only thing)

In other words, with this it's (barely, but still) more likely than not that a random PDF of the web will show up fine.

From a LibGfx point of view, this adds a way to provide an external opentype cmap, since PDF needs this. PDFs generally need very little from a font file, since they're already laid out, they're already shaped (ligature replacement has happened etc), characters have dimensions assigned at the PDF level, etc. So a) many tables in an opentype file aren't necessary b) for that reason, many tables that are technically required by opentype aren't included in PDF files: For example, the cmap, but also in some files 'hmtx' (after this patch here, in 25 of my 1000 files – before this patch in 24 of them, so this seems to happen more for type2 fonts than for type0 truetype) or 'name' (after this patch, in 41 of 1000 – before in 10). All PDFs really need are the glyphs. So maybe a better approach might be to split OpenType/Font.cpp into the binary reading parts and the font parts and only use the low-level parts in LibPDF. But for now, this keeps the current architecture and just adds a layer of indirection to make it possible to inject the external CIDToGIDMap. (Doing this requires way less code than this paragraph has words.)

### CODE REVIEW

**Comment by nico** [comment]
Before/After are for the most part not super interesting since the before is often an empty page and the after looks kinda good usually.

But here are a few anyways.

Before (0000277.pdf, the pdf that uses all PDF features):

Screenshot 2024-02-16 at 8 07 48 PM

After:

Screenshot 2024-02-16 at 8 08 15 PM

Before:

Screenshot 2024-02-16 at 8 07 22 PM

After:

Screenshot 2024-02-16 at 8 03 16 PM

Before:

Screenshot 2024-02-16 at 8 07 18 PM

After:

Screenshot 2024-02-16 at 8 05 03 PM

Before:

Screenshot 2024-02-16 at 8 07 37 PM

After:

Screenshot 2024-02-16 at 8 02 51 PM

Before:

Screenshot 2024-02-16 at 8 07 31 PM

After (the cmd symbol in the bottom center):

Screenshot 2024-02-16 at 8 03 07 PM

**Comment by awesomekling** [comment]
Annoying question: would it make sense to push all font implementations into LibGfx and then make LibPDF (and everyone else) clients of LibGfx?

**Comment by nico** [comment]
We eventually want to move the CFF parser over, for CFF tables in OpenType.

But even then, these things remain true:

* OpenType fonts in PDF have some of their tables externalized to PDF objects (glyph widths, encoding stuff, font names, ...) and the OpenType font data in the PDF is invalid per OpenType spec
* Text in PDFs is already pre-kerned, pre-ligatured, pre-layouted, ... so many of the things that LibGFX does aren't needed and actually get in the way

So I think we eventually want to have a low-level layer in LibGfx that is used by both LibPDF and the higher-level layer in LibGfx, but also have some independent parts.

**Comment by nico** [comment]
(also, PDF 1.6 added support for CFF data in OpenType containers I think, so we'll have to integrate the CFF parsing into the OpenType parser just for PDF even!)

**Pull request merged**
