### PR TITLE
Lagom/ConfigureComponents: Run cmake command last

### PR DESCRIPTION
**Pull request by krkk**
Previously the tool was removing the Root directory after configuring cmake which was breaking the build, as some cmake rules put some necessary files there.

Moving the cmake command to be the last one makes it regenerate those files automatically. :^)

### CODE REVIEW

**Comment by krkk** [comment]
oh wait it needs something more xd

**Comment by krkk** [comment]
okay so building serenity using the required config should work now too

**Comment by GMTA** [comment]
Please explain why `install` is now required in the commit message

**Comment by krkk** [comment]
I've explained it, but I wonder whether we even need to make it required the first place. Probably a check if a file exists should be enough. Will try that later. :)

**Review by ADKaster — APPROVED** [review]

**Pull request merged**
