### PR TITLE
Make some ports build, document shortcomings

### PR DESCRIPTION
**Pull request by BenWiederhake**
This fixes / touches up some ports that now build:
- bc
- git
- (In some sense: libogg, genemu)

These ports already worked:
- bash
- binutils
- bison
- byacc
- bzip2
- cmake
- curl
- dmidecode
- doom
- ed
- figlet
- flex
- freetype
- gcc
- genemu
- grep
- indent
- jot
- jq
- klong
- less
- libarchive
- libffi
- libogg
- ncurses
- pcre2
- python3
- quake
- rsync
- SDL2
- SDL2_mixer
- SDL2_ttf - depends on libfreetype-dev of host
- sed
- sl
- termcap
- tinycc
- tinyscheme
- vim
- vttest
- zlib
- zstd

The following ports currently are broken, and I don't know how to fix them:
- **dash and dropbear:** static linkage is broken, will probably be fixed by #5758
- **c-ray and frotz:** desync from upstream
- **diffutils, libiconv, nano:** conflicting definitions of lstat?!
- **libexpat:** "hidden symbol `main' in outline.o is referenced by DSO"
- **mrsh:** "local symbol `main' in /tmp/cchQaYBA.o is referenced by DSO" during configure ("Checking for exported symbol restrictions")
- **ninja:** "hidden symbol `main' in build/ninja.o is referenced by DSO"
- **gnuplot:** Depends on tex?!
- **openssh:** Depends on broken openssl
- **openssl:** Apparently we're missing AI_PASSIVE, NI_MAXHOST, NI_MAXSERV, NI_NUMERICHOST, NI_NUMERICSERV. Maybe due to EAI_FAMILY?
- **stress-ng:** Something about zlib and feclearexcept, I don't get it.
- **tr:** How could this possibly work? conflicting definition of ctypes, doesn't use configure

I took the liberty to remove the "editline" port, as it has never worked. See #2532 and #2677.

CC @alimpfard and @linusg, and everyone else who cares about ports. I'm currently implementing some kind of cronjob that automatically checks the state of the ports every week, that might help in keeping bitrot in check.

### CODE REVIEW

**Comment by linusg** [comment]
> c-ray and frotz: desync from upstream

Here are up-to-date patches for c-ray, the only thing missing now is a `tanf` impl in LibM - it's declared, but not defined anywhere :confused:

---

```diff
diff --git a/Ports/c-ray/patches/disable-checkbuf.patch b/Ports/c-ray/patches/disable-checkbuf.patch
index eea415685..f625e2b05 100644
--- a/Ports/c-ray/patches/disable-checkbuf.patch
+++ b/Ports/c-ray/patches/disable-checkbuf.patch
@@ -1,23 +1,11 @@
-diff --git a/src/utils/filehandler.c b/src/utils/filehandler.c
-index 99638f3..feded8f 100644
---- a/src/utils/filehandler.c
-+++ b/src/utils/filehandler.c
-@@ -162,7 +162,7 @@ char *loadFile(char *inputFileName, size_t *bytes) {
+--- c-ray-master/src/utils/fileio.c	2021-03-13 00:13:46.067407670 +0100
++++ c-ray-master/src/utils/fileio.c	2021-01-11 01:01:57.000000000 +0100
+@@ -83,7 +83,7 @@
+ 
  //Wait for 2 secs and abort if nothing is coming in from stdin
  void checkBuf() {
- #ifndef WINDOWS
--	fd_set set;
-+	/*fd_set set;
+-#ifndef WINDOWS
++#if !defined(WINDOWS) && !defined(__serenity__)
+ 	fd_set set;
  	struct timeval timeout;
  	int rv;
- 	FD_ZERO(&set);
-@@ -176,7 +176,8 @@ void checkBuf() {
- 		logr(error, "No input found after %i seconds. Hint: Try `./bin/c-ray input/scene.json`.\n", timeout.tv_sec);
- 	} else {
- 		return;
--	}
-+	}*/
-+	return;
- #endif
- }
- 
diff --git a/Ports/c-ray/patches/enable-own-asprintf.patch b/Ports/c-ray/patches/enable-own-asprintf.patch
index 9263dd815..57083d29d 100644
--- a/Ports/c-ray/patches/enable-own-asprintf.patch
+++ b/Ports/c-ray/patches/enable-own-asprintf.patch
@@ -1,19 +1,11 @@
-diff --git a/src/libraries/asprintf.h b/src/libraries/asprintf.h
-index 70a95ac..0e46c3c 100644
---- a/src/libraries/asprintf.h
-+++ b/src/libraries/asprintf.h
-@@ -33,7 +33,6 @@ int vscprintf(const char *format, va_list ap) {
+--- c-ray-master/src/libraries/asprintf.h	2021-03-13 00:16:23.782000000 +0100
++++ c-ray-master/src/libraries/asprintf.h	2021-03-13 00:16:41.350553067 +0100
+@@ -33,7 +33,7 @@
   * GNU-C-compatible compilers implement these with the same names, thus we
   * don't have to do anything
   */
 -#ifdef _MSC_VER
++#if defined(_MSC_VER) || defined(__serenity__)
  int cray_vasprintf(char **strp, const char *format, va_list ap) {
  	int len = vscprintf(format, ap);
  	if (len == -1)
-@@ -57,6 +56,5 @@ int asprintf(char **strp, const char *format, ...) {
- 	va_end(ap);
- 	return retval;
- }
--#endif
- 
- #endif // ASPRINTF_H
diff --git a/Ports/c-ray/patches/fix-linkage.patch b/Ports/c-ray/patches/fix-linkage.patch
index f8a44bcf1..93622abb2 100644
--- a/Ports/c-ray/patches/fix-linkage.patch
+++ b/Ports/c-ray/patches/fix-linkage.patch
@@ -1,30 +1,20 @@
-diff --git a/CMakeLists.txt b/CMakeLists.txt
-index 5ccce96..1db6074 100644
---- a/CMakeLists.txt
-+++ b/CMakeLists.txt
-@@ -58,7 +58,7 @@ if (NOT NO_SDL2)
- 		if (MSVC)
-   			target_link_libraries(${PROJECT_NAME} ${SDL2_LIBRARY})
- 		else()
--  			target_link_libraries(${PROJECT_NAME} -lpthread -lm ${SDL2_LIBRARY})
-+			target_link_libraries(${PROJECT_NAME} -lSDL2 -lgui -lgfx -lipc -lcore -lpthread -lm -lstdc++)
- 		endif()
- 		add_definitions(-DUI_ENABLED)
- 	else()
-@@ -66,7 +66,7 @@ if (NOT NO_SDL2)
- 		if (MSVC)
- 			target_link_libraries(${PROJECT_NAME})
- 		else()
--			target_link_libraries(${PROJECT_NAME} -lpthread -lm)
-+			target_link_libraries(${PROJECT_NAME} -lgui -lipc -lcore -lpthread -lm -lstdc++)
- 		endif()
- 	endif()
+--- c-ray-master/CMakeLists.txt	2021-03-13 00:40:48.474000000 +0100
++++ c-ray-master/CMakeLists.txt	2021-03-13 00:41:04.770789629 +0100
+@@ -38,7 +38,7 @@
+ 	set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/DEBUG /MANIFEST:NO /INCREMENTAL:NO /OPT:REF,ICF" CACHE STRING "" FORCE)
  else()
-@@ -75,6 +75,6 @@ else()
- 	if (MSVC)
- 		target_link_libraries(${PROJECT_NAME})
- 	else()
--		target_link_libraries(${PROJECT_NAME} -lpthread -lm)
-+		target_link_libraries(${PROJECT_NAME} -lgui -lipc -lcore -lpthread -lm -lstdc++)
- 	endif()
- endif()
+ 	# set(CMAKE_C_FLAGS "-Wall -Wextra -pedantic -Wconversion -std=gnu99")
+-	set(CMAKE_C_FLAGS "-Wall -Wextra -Wno-missing-field-initializers -std=gnu99 -march=native -mtune=native -D_GNU_SOURCE")
++	set(CMAKE_C_FLAGS "-Wall -Wextra -Wno-missing-field-initializers -std=gnu99 -mtune=native -D_GNU_SOURCE")
+ 	set(CMAKE_C_FLAGS_RELEASE "-O3 -ftree-vectorize")
+ 	set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -O0 -g")
+ 	if (ASAN)
+@@ -71,7 +71,7 @@
+ target_include_directories(c-ray PRIVATE ${c-ray_SOURCE_DIR}/src)
+ target_include_directories(c-ray PRIVATE ${c-ray_SOURCE_DIR}/tests)
+ if (NOT MSVC)
+-	target_link_libraries(c-ray PRIVATE -lpthread -lm)
++	target_link_libraries(c-ray PRIVATE -lSDL2 -lgui -lgfx -lipc -lcore -lpthread -lstdc++ -lm)
+ endif ()
+ 
+ include(CheckIPOSupported)
diff --git a/Ports/c-ray/patches/fix-usleep.patch b/Ports/c-ray/patches/fix-usleep.patch
index b1c7290b0..a32b108a9 100644
--- a/Ports/c-ray/patches/fix-usleep.patch
+++ b/Ports/c-ray/patches/fix-usleep.patch
@@ -1,27 +1,20 @@
-diff --git a/src/utils/timer.c b/src/utils/timer.c
-index 9978a99..c94d33d 100644
---- a/src/utils/timer.c
-+++ b/src/utils/timer.c
-@@ -48,20 +48,13 @@ long getUs(struct timeval timer) {
+--- c-ray-master/src/utils/timer.c	2021-03-13 00:26:36.846000000 +0100
++++ c-ray-master/src/utils/timer.c	2021-03-13 00:27:29.453478737 +0100
+@@ -48,7 +48,7 @@
  	return ((tmr2.tv_sec - timer.tv_sec) * 1000000) + (tmr2.tv_usec - timer.tv_usec);
  }
  
-+#include <unistd.h>
-+
- /**
-  Sleep for a given amount of milliseconds
-  
-  @param ms Milliseconds to sleep for
-  */
- void sleepMSec(int ms) {
--#ifdef WINDOWS
--	Sleep(ms);
--#elif __APPLE__
--	struct timespec ts;
--	ts.tv_sec = ms / 1000;
--	ts.tv_nsec = (ms % 1000) * 1000000;
--	nanosleep(&ts, NULL);
+-#ifdef __linux__
++#if defined(__linux__) || defined(__serenity__)
+ #define _BSD_SOURCE
+ #include <unistd.h>
+ #endif
+@@ -66,7 +66,7 @@
+ 	ts.tv_sec = ms / 1000;
+ 	ts.tv_nsec = (ms % 1000) * 1000000;
+ 	nanosleep(&ts, NULL);
 -#elif __linux__
++#elif defined(__linux__) || defined(__serenity__)
  	usleep(ms * 1000);
--#endif
+ #endif
  }
diff --git a/Ports/c-ray/patches/replace-micro-symbol.patch b/Ports/c-ray/patches/replace-micro-symbol.patch
deleted file mode 100644
index 74ce575b8..000000000
--- a/Ports/c-ray/patches/replace-micro-symbol.patch
+++ /dev/null
@@ -1,13 +0,0 @@
-diff --git a/src/renderer/renderer.c b/src/renderer/renderer.c
-index 90cfee9..4e36ed2 100644
---- a/src/renderer/renderer.c
-+++ b/src/renderer/renderer.c
-@@ -104,7 +104,7 @@ struct texture *renderFrame(struct renderer *r) {
- 			char rem[64];
- 			smartTime((msecTillFinished) / r->prefs.threadCount, rem);
- 			float completion = ((float)completedSamples / totalTileSamples) * 100;
--			logr(info, "[%s%.0f%%%s] μs/path: %.02f, etf: %s, %.02lfMs/s %s        \r",
-+			logr(info, "[%s%.0f%%%s] us/path: %.02f, etf: %s, %.02lfMs/s %s        \r",
- 				 KBLU,
- 				 completion,
- 				 KNRM,
diff --git a/Ports/c-ray/patches/set-sdl-software-renderer.patch b/Ports/c-ray/patches/set-sdl-software-renderer.patch
index 7b7899c0f..40dd12000 100644
--- a/Ports/c-ray/patches/set-sdl-software-renderer.patch
+++ b/Ports/c-ray/patches/set-sdl-software-renderer.patch
@@ -1,13 +1,11 @@
-diff --git a/src/utils/ui.c b/src/utils/ui.c
-index afcb4fc..3713b87 100644
---- a/src/utils/ui.c
-+++ b/src/utils/ui.c
-@@ -63,7 +63,7 @@ int initSDL(struct display *d) {
- 		return -1;
+--- c-ray-master/src/utils/ui.c	2021-03-13 00:30:25.488000000 +0100
++++ c-ray-master/src/utils/ui.c	2021-03-13 00:30:41.056572879 +0100
+@@ -120,7 +120,7 @@
+ 		return;
  	}
  	//Init renderer
--	d->renderer = SDL_CreateRenderer(d->window, -1, SDL_RENDERER_ACCELERATED);
-+	d->renderer = SDL_CreateRenderer(d->window, -1, SDL_RENDERER_SOFTWARE);
- 	if (d->renderer == NULL) {
+-	gdisplay->renderer = SDL_CreateRenderer(gdisplay->window, -1, SDL_RENDERER_ACCELERATED);
++	gdisplay->renderer = SDL_CreateRenderer(gdisplay->window, -1, SDL_RENDERER_SOFTWARE);
+ 	if (gdisplay->renderer == NULL) {
  		logr(warning, "Renderer couldn't be created, error: \"%s\"\n", SDL_GetError());
- 		return -1;
+ 		destroyDisplay();
```

**Comment by alimpfard** [comment]
> gnuplot: Depends on tex?!

I think it's trying to generate documentation, you can probably turn that off :P

> some kind of cronjob that automatically checks the state of the ports every week

fully building (at least) cmake without kvm is going to be a very...very...painful process, maybe skip over that for now?

**Comment by RealKC** [comment]
> stress-ng: Something about zlib and feclearexcept, I don't get it.

The feclearexcept issue is likely caused by me accidentally having named that function feclearexcept**s** instead. Renaming it should help :P

**Comment by BenWiederhake** [comment]
> > c-ray and frotz: desync from upstream
> 
> Here are up-to-date patches for c-ray

Why not just make a PR? :sweat_smile:

**Comment by BenWiederhake** [comment]
> > gnuplot: Depends on tex?!
> 
> I think it's trying to generate documentation, you can probably turn that off :P

Will do so!

> > some kind of cronjob that automatically checks the state of the ports every week
> 
> fully building (at least) cmake without kvm is going to be a very...very...painful process, maybe skip over that for now?

It's going to cross-compile, therefore it runs on host – so there is no "kvm or no kvm" question :D

**Comment by linusg** [comment]
> Why not just make a PR?

Because it still doesn't compile and I don't feel like writing a `tanf` right now :)
(unless `float tanf(float x) { return (float)tan((double)x); }` is acceptable :laughing:)

**Comment by alimpfard** [comment]
> It's going to cross-compile

If you can make cmake cross-compile, please do so!

**Comment by BenWiederhake** [comment]
> > Why not just make a PR?
> 
> Because it still doesn't compile and I don't feel like writing a `tanf` right now :)
> (unless `float tanf(float x) { return (float)tan((double)x); }` is acceptable laughing)

That's precisely what I'm doing right now :P

**Comment by BenWiederhake** [comment]
> > It's going to cross-compile
> 
> If you can make cmake cross-compile, please do so!

That is non-trivial? During compile it looks like it's using the right compiler automatically, so I never worried about that. Let's see whether it runs.

**Comment by BenWiederhake** [comment]
Oof. Okay, I can't do everything in this PR.

Changes since last description:
- Drop the "build in randomized order", since this should go into the port-cron-pr
- Rebase
- Fix the [typo](https://github.com/SerenityOS/serenity/pull/5762#issuecomment-798779561) as suggested by @RealKC
- Make gnuplot fail a bit later: Now it is convinces that we have `extern int signgam;`, specifically because we don't declare it:
  ```
  #if defined(GAMMA) && !HAVE_DECL_SIGNGAM
  ```
  …
  where `HAVE_DECL_SIGNGAM` is 0, and `GAMMA` is 1 because we have `gamma()` (but not `lgamma()`, which has `signgam` as a secondary output).

Thus, gnuplot is too hard for me to fix fully here.

I see that linusg already has a c-ray PR open. I would like to split the "port-cron" stuff into some future PR.

**Pull request merged**
