### PR TITLE
 LibWeb: Improve fetchPriority and loading attribute tests

### PR DESCRIPTION
**Pull request by jamierocks**
Ladybird PR: https://github.com/LadybirdWebBrowser/ladybird/pull/99

### CODE REVIEW

**Comment by jamierocks** [comment]
I did cherry-pick these :)

The third relates to a pull request that hasn't been merged here yet (GH-24500). I've merged that change in Ladybird into that pull request directly :)

**Comment by nico** [comment]
If you pass `-x` to `git cherry-pick`, it'll mention the cherry-pick. Looks like that's what we currently prefer: https://discord.com/channels/830522505605283862/830739873119207426/1249048594892460042

**Comment by nico** [comment]
> The third relates to a pull request that hasn't been merged here yet ([GH-24500](https://github.com/SerenityOS/serenity/pull/24500)). I've merged that change in Ladybird into that pull request directly :)

I merged that one.

**Comment by jamierocks** [comment]
> If you pass -x to git cherry-pick, it'll mention the cherry-pick.

My normal workflow is to write the initial pull request here - this was an exception.

> I just merged that one. Probably good to add the third commit here, to keep things kind of in sync?

I made the same change as the third commit in GH-24500 :)

**Pull request merged**
