### PR TITLE
SystemMonitor: Remove unveiling /tmp/portal/config

### PR DESCRIPTION
**Pull request by doctor-rd**

### CODE REVIEW

**Comment by kleinesfilmroellchen** [comment]
This does not work, as SystemMonitor uses the ConfigServer, see e.g. line 237.

**Comment by doctor-rd** [comment]
It does work. This pattern is used almost everywhere. ```Config::pledge_domains("SystemMonitor")``` connects to the ```ConfigServer```.

**Comment by kleinesfilmroellchen** [comment]
See my comment on #10871.

**Comment by bgianfo** [comment]
@doctor-rd  can you rebase this on lastest master so we can get a clean CI build please?

**Comment by bgianfo** [comment]
> See my comment on #10871.

@kleinesfilmroellchen Your comment in #10871 seems to have been incorrect?
Do you have any other objections?

**Comment by kleinesfilmroellchen** [comment]
Nope let's merge.

**Pull request merged**
