### PR TITLE
crash: Check whether the msyscall mitigation actually works

### PR DESCRIPTION
**Pull request by BenWiederhake**
Bildschirmfoto_2021-09-15_20-49-13

Dunno why I didn't submit this thing earlier.

### CODE REVIEW

**Comment by bgianfo** [comment]
Can we just make this a test instead? `Tests/Kernel/` so we get automated testing verification on every PR? 

`/bin/crash` is nice for adhoc testing, but there's no way to automate it at the moment ☹️

**Comment by BenWiederhake** [comment]
(Old build error in Serenity_Clang_i686 was unrelated)

Changes since last push:
- Run automatically during CI (see below screenshots)
- Rebased for convenience

crash, running as part or `run-tests`:
Bildschirmfoto_2021-09-15_21-51-14

crash, again running as part or `run-tests`, but this time with an injected bug:
Bildschirmfoto_2021-09-15_21-46-51

**Review by bgianfo — APPROVED** [review]
LGTM! ✔️

**Comment by BenWiederhake** [comment]
Do not pull: Something weird is failing; probably a latent bug uncovered by running `crash` in the CI env.

**Comment by BenWiederhake** [comment]
CI runs Qemu without kvm available.
Therefore, Qemu has to emulate the CPU in software.
Apparently, Qemu doesn't seem to implement the feature of preventing certain user-mode instructions like `str` ("Stores the segment selector from the task register (TR) in the destination operand. … The STR instruction is useful only in operating-system software.").
Therefore, ring 3 can freely execute that instruction.
Therefore, the `-U` test ("Trigger x86 User Mode Instruction Prevention") correctly fails.
Therefore, without the last commit in this PR, we would always fail, or at least fail due to an obscure feature missing in qemu.

That's not very helpful for continuous integration of *Serenity*, so the last commit attempts to alleviate that.
Note that this "bug" affects both CI and users who run Serenity in no-kvm-mode for whatever reason, so detecting CI based on envvars doesn't sound like a good idea. That's why I excluded the test from `-A` ("Test all crash types"), so the test can only be run by explicitly invoking it (`/usr/Tests/Kernel/crash -U`).

Thanks to @dascandy for some key infos I needed while debugging this! :D

Other changes since last push:
- Rebased for convenience.

**Comment by BenWiederhake** [comment]
All test failures are due to timeouts in `LibTLS/TestTLSHandshake`, so I'll claim that someone broke `master`, and that those timeouts are not due to my changes in the `crash` program.

**Comment by BenWiederhake** [comment]
b61eff873050a3eb906879cbdddc068bb2875607 confirms this. I'll rebase for extra convenience, but I don't think that's necessary.

**Pull request merged**
