### PR TITLE
LibM: optimized (branchless) copysign

### PR DESCRIPTION
**Pull request by nickwanninger**
This version just copies the sign bit from y into x. This is just an optimization after @awesomekling mentioned there is likely a more clever way to do it in his recent video. I think this is the clever way :^)

### CODE REVIEW

**Comment by TheMorc** [comment]
A minor thing, please squash those commits into a single commit.

**Comment by nickwanninger** [comment]
Sorry, having some trouble with git on my end, I'll see what I can do

**Comment by TheMorc** [comment]
> Sorry, having some trouble with git on my end, I'll see what I can do

No problem, take your time. I also had problems with getting it to work on the first time. 
You can usually do `git rebase -i HEAD~3` and then you change pick to fixup for the commit you want it to merge with.

**Comment by nickwanninger** [comment]
Alright that should do it

**Comment by awesomekling** [comment]
Oh that's super slick :)

**Pull request merged**
