### PR TITLE
LibUnicode+LibWeb: Rework bidirectional_class() API a bit

### PR DESCRIPTION
**Pull request by nico**
Before this commit, GenerateUnicodeData generated a
`BidirectionalClass` enum directly from UnicodeData.txt.

Now, GenerateUnicodeData instead generates `BidirectionalClassInternal`
and CharacterTypes.h has an explicit enum `BidiClass` with nicer names
-- no underscores, but also names more similar to ICUs names.

(Since CharacterTypes.h is included in some of LibUnicode's generators,
it can't refer to generated `BidirectionalClassInternal`, so we instead
have a big manual mapping switch in UnicodeData.cpp.)

`bidirectional_class()` used to return an `Optional<BidirectionalClass>`
for when unicode data was disabled. Now we return `BidiClass` and
just return `BidiClass::LeftToRight` instead of making every client
do this.

It also updates LibWeb's Element.cpp to this new system.

Also remove now-unused `bidirectional_class_from_string()`.

This kind of cherry-picks the 4th commit of
LadybirdBrowser/ladybird#239 (aa3a30870b58c47cb37bce1418d7e6bee7af71d9):
The CharacterTypes.h, Element.cpp and TestUnicodeCharacterTypes.cpp changes are
by trflynn.

Co-authored-by: Tim Flynn <trflynn89@serenityos.org>

### CODE REVIEW

**Comment by nico** [comment]
@trflynn89 Do you want to look at LibUnicode changes over here, or should I just merge?

**Comment by trflynn89** [comment]
Code LGTM. This does break the ability to build with UCD downloads disabled - I generally tried to keep that config building/non-crashing, but if we want to step away from that, that's fine. (I don't know if the build even currently works with UCD downloads disabled, it was just something I tested every couple months or so, or if someone using the option pointed out that it broke).

**Comment by nico** [comment]
I didn't test it, but I intended that to keep working. There's still a weak symbol of the generated function. Is there more I have to take care of?

(I suppose I could actually try building with it disabled...)

**Comment by nico** [comment]
...oh, probably because I'm using the generated enum values unconditionally. I'll tweak that, thanks!

**Comment by nico** [comment]
Done!

**Pull request merged**
