### PR TITLE
 less: Properly stop on eof, and show correct line index 

### PR DESCRIPTION
**Pull request by demostanis**
Before, when pressing `j` too much, less would just go past the buffer in some cases.
It would also show the same line index in the status line in some lines.
Very odd. Anyway, that's past now, because **I fixed it**.

### CODE REVIEW

**Comment by demostanis** [comment]
still a draft since i've realized i forgot to fix top() and bottom()

**Review by timschumi — CHANGES_REQUESTED** [review]
The EOF fix should be split into a separate commit ("and" in a commit title is usually never a good sign).

The fact that we have to track the user-visible line number separately is also quite peculiar. I feel like that deserves more investigation rather than tacking on a band-aid fix.

**Comment by timschumi** [comment]
> my eyes were just in front of the holes lol

Isn't that how eyes usually work? :^)

**Comment by demostanis** [comment]
> > my eyes were just in front of the holes lol
> 
> Isn't that how eyes usually work? :^)

my eyes weren'tttt*
shit, now people are gonna think im drunk when i open PRs
anyway, i removed m_line_in_status, but i still made it so that less starts with line 1 instead of line 0 when printing the current line index in the status line
the pull request thus still applies

**Comment by EWouters** [comment]
Looks good. I vaguely remember that the less line offset was intentional, but I think it's sensible.

**Pull request merged**
