### PR TITLE
Kernel+Userland: Introduce InitRAM filesystem support

### PR DESCRIPTION
**Pull request by supercomputer7**
The main goal of this PR is to allow us to use SerenityOS on bare metal, without the need of writing a GRUB (or any other Multiboot-compatible bootloader) harddrive image to a physical PATA/SATA harddrive. This means we should be able to boot from a USB thumb drive, over PXE (or iPXE which is much more reliable), etc. This also means that we could run entirely from RAM, so the constant question of "why I can't use this with a USB thumb drive?" is eliminated. As a side effect, I expect this to raise the usage of Serenity on bare metal and as a consequence, to lead to more drivers being written.

For now, this PR is still incomplete. We can boot now directly to the initramfs image on i686 (x86-64 doesn't work yet due to low memory condition?). So the next thing I intend to work is to be able to swap the root mount with a real harddrive - this involves using a new syscall, called pivot_root (which is quite similar to what Linux has).

The current tasks to complete this are:
- [x] Fix the `pivot_root` syscall to be able to use a real harddrive and continue booting within it
- [x] Fix x86-64 setup to boot to both into the initramfs and a real harddrive with ext2 filesystem

This relies on #14932 and #14776. The inspiration to use the DROW ELF format is from #11368. Please note that I fixed most of the notes from that PR when I rebased it with my changes, but if you have any other suggestion, I'd be happy to hear about them :)
Another PR being related to this is #14940, which intends to replace https://github.com/supercomputer7/serenity/commit/0ba59c3f26c1ee7fdc8ce564d8ecf63d31b943ff with a slightly better solution.

Preview of what has been achieved so far:
Screenshot_2022-08-19_09-31-36
Screenshot_2022-08-19_10-58-41

### CODE REVIEW

**Comment by supercomputer7** [comment]
Let's reopen this so we can actively advocate this to be merged as soon as possible :)

**Comment by supercomputer7** [comment]
Now that the **BuggieBox** utility is being defined in #15373, we can try this again :)

**Comment by supercomputer7** [comment]
So now that it works quite beautifully, I will post some pictures so you can view the environment:
Screenshot_2022-11-19_19-53-55
Screenshot_2022-11-19_19-54-27
Screenshot_2022-11-19_19-55-51

**Comment by supercomputer7** [comment]
Leaving a side note here - if we failed to boot and we were dropped into emergency shell, and then continued booting with `init /dev/hdX` (or something like this), the graphical environment boots fine up until the LoginServer, but you can't login. If we weren't dropped into the emergency shell (because the `root=` kernel command-line option was set correctly) or we use textual mode - everything behaves normally.

**Comment by supercomputer7** [comment]
Thinking about it seriously, the whole pivot root syscall should really look different. The main problem is our “mount table”, in particular the fact that it is a Vector and not an intrusive list - cant see one reasonable advantage for this, so let’s shave the yak here and make it right - it will also ensure that we don’t have to awkwardly enumerate the list like the way we do in many places in the VFS code.

**Comment by AtkinsSJ** [comment]
This has conflicts.

**Comment by supercomputer7** [comment]
There are a few roadblockers to this
- Getting rid of i686 support: This will greatly help to not run out of memory in case of big initramfs images, as I'd like to restore TmpFS "free" allocation of virtual memory
- If we rely on CPIO for the initramfs image, I'd like to get a utility for handling that format first.
- If we rely on other archive format for the initramfs image, I'd like to ensure that everything is intact with our implementation. Options are [SquashFS](https://en.wikipedia.org/wiki/SquashFS), [CramFS](https://en.wikipedia.org/wiki/Cramfs), [EROFS](https://en.wikipedia.org/wiki/EROFS), tar, zip, [BootFS](https://en.wikipedia.org/wiki/Boot_File_System), FAT16/FAT32 or [ROMFS](https://www.kernel.org/doc/html/latest/filesystems/romfs.html).
Preferably, the solution should easy to implement in our project and that has all the required utilities for Linux.
- We still need to work out the pivot_root syscall. It works, but I am not very happy with the result.
- BuggieBox needs more utilities within it, so in case of failure, you could do something meaningful with it
- In general, I'd like to ensure it all feels natural to the project. The goal is very positive, but if it will slow things down during boot, or the ergonomics will not fit, then we will need to fix this.

**Review by kleinesfilmroellchen — CHANGES_REQUESTED** [review]
One more comment: Why are we duplicating logic across init and SystemServer if the former will just call the latter?

**Comment by supercomputer7** [comment]
We can close this, as #16855 will resolve this as well.

**Pull request closed without merging**
