### PR TITLE
Manpages: Auto-generate many through ArgsParser

### PR DESCRIPTION
**Pull request by BenWiederhake**
This set was hand-curated, *guided* by the questions:
- Does it have at least three options, i.e. is the help page non-trivial?
- Is the program unusual, i.e. does listing it in Help or on man.serenityos.org spread awareness?
- Is the program common, but we only implement a subset of 'common' flags?
- Does scrolling through the result feel natural?

Let me know if I should split this PR up.

### CODE REVIEW

**Comment by BenWiederhake** [comment]
Changes since last push:
- Rebase to show it's not stale (CI was already green)
- Dropped the "Mark files in /root as owned by root" commit. I missed the fact that the script assembling the image already is root, so all files are `root:root` by default, so it wasn't hurting, but also not really doing anything.

**Comment by BenWiederhake** [comment]
Changes since last push:
* Rebase to show it's not stale (CI was already green)
* Changed the new code to follow the new #10737 "readability" conventions (i.e. `ArgsParser::print_usage_markdown` now compares pointers and chars against `nullptr` and `'\0'` respectively)
* Changed the description of an argument in UserspaceEmulator slightly, to avoid the `#` character on the example commandline.
* Refreshed the manpages to reflect changes in [grep](https://github.com/SerenityOS/serenity/commit/0086466b61c11e25388358b4a2a20d9f069b6a20) and UserspaceEmulator

**Review by linusg — CHANGES_REQUESTED** [review]
Nice initiative :^)
Code LGTM, but please update the following commit messages:

---

> profile: The '--help' argument is not an error 

and

> Meta: Script that generates and exports manpages

are not compatible with

> Write the commit message subject line in the imperative mood

---

> Meta: Don't start unnecessary services in self-test

Meta -> Base

---

> LibCore: Enable emitting markdown 

Please mention ArgsParser in the commit message, not clear enough like this. Please also explain how (ARGSPARSER_EMIT_MARKDOWN).

> LibCore: Make '--help' description more general

->

> LibCore: Make ArgsParser '--help' description more general

**Comment by BenWiederhake** [comment]
Changes since last push:
- All of @linusg's suggestions (Thanks!)
- Add a reasoning in the commit description to "LibCore: Make ArgsParser '--help' description more general"

CI failure looks like another instance of #9962.

**Pull request merged**
