### PR TITLE
Base: Add some more Transport and Map to Katica 10

### PR DESCRIPTION
**Pull request by Diogenes31**
I've been meaning to contribute to Serenity in a while, so I figured I'd start off by adding some characters :^)

Before:
image

After:
image

### CODE REVIEW

**Comment by TobyAsE** [comment]
Hi Diogenes, welcome to the project!
It would be great if you put into the commit message which characters exactly you added. Either by specifying a range or every single one seperately.
For exampe see this commit message: https://github.com/SerenityOS/serenity/commit/764e33f31809ad770d50ecb6e9b7f71b70549b08

**Review by Xexxa — COMMENTED** [review]
I really like 1F692, the raised ladder makes it clear what it is.

Generally these looks amazing, quite a few of these is way better then I could ever have done.

Comparing the glyphs with the [Unicode charts](https://www.unicode.org/charts/PDF/U1F680.pdf):
1F698 is the same as 1F697, not sure if that is intentional or not?
1F696 look like it was intended for 1F694?
You could probably have a circle around 1F6B0 like 1F6B1.

If these things are intentional I would say it's in the realm of artistic freedom, but please look them over.

**Comment by Diogenes31** [comment]
> 1F698 is the same as 1F697, not sure if that is intentional or not?

It's not ideal, but it is deliberate. I struggled to come up with a glyph that was as clear as the oncoming car, that was sideways. I can cut that out of the pr if necessary.

> 1F696 look like it was intended for 1F694?

It wasn't but I think it does fit better there. Maybe in the future I can colorize it one as red and blue and the other as yellow? Not sure, I'll swap it for now and revisit it later.

> You could probably have a circle around 1F6B0 like 1F6B1.

I can add that, I'll see how it looks. Generally when restricted to such small resolution adding stuff like circles can really hurt legibility, but it's worth looking at.

**Comment by Diogenes31** [comment]
I resolved these things:
> 1F698 is the same as 1F697, not sure if that is intentional or not?
> 1F696 look like it was intended for 1F694?
by drawing a sideways car glyph for 1F697, and by moving 1F696 to 1F694.

**Review by Xexxa — APPROVED** [review]
lgtm

**Pull request merged**
