### PR TITLE
Base: Add 9 new emojis and improve 13 emojis

### PR DESCRIPTION
**Pull request by electrikmilk**
This adds 9 new emojis:
U+1F6AB U+1F6DF U+1F51F U+1F381 U+1FAAB U+1FAB4 U+2B1B U+2B1C U+26F3

...and improves 13 emojis:
U+2A_U+FE0F_U+20E3 U+23_U+FE0F_U+20E3 U+30_U+FE0F_U+20E3 U+31_U+FE0F U+20E3 U+32_U+FE0F_U+20E3 U+33_U+FE0F_U+20E3 U+0034_U+FE0F_U+20E3 U+35_U+FE0F_U+20E3 U+0036_U+FE0F_U+20E3 U+37_U+FE0F_U+20E3 U+38_U+FE0F_U+20E3 U+39_U+FE0F_U+20E3 U+26AB

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
```
Running Meta/check-emoji.sh... 
Base/res/emoji/U+0034_U+FE0F_U+20E3.png should not include any emoji presentation selectors. U+FE0F codepoints should be removed from the filename.
Base/res/emoji/U+0036_U+FE0F_U+20E3.png should not include any emoji presentation selectors. U+FE0F codepoints should be removed from the filename.
Base/res/emoji/U+23_U+FE0F_U+20E3.png should not include any emoji presentation selectors. U+FE0F codepoints should be removed from the filename.
Base/res/emoji/U+2A_U+FE0F_U+20E3.png should not include any emoji presentation selectors. U+FE0F codepoints should be removed from the filename.
Base/res/emoji/U+30_U+FE0F_U+20E3.png should not include any emoji presentation selectors. U+FE0F codepoints should be removed from the filename.
Base/res/emoji/U+31_U+FE0F U+20E3.png contains invalid characters in its filename. Only uppercase letters, numbers, +, and _ should be used.
Base/res/emoji/U+31_U+FE0F U+20E3.png should not include any emoji presentation selectors. U+FE0F codepoints should be removed from the filename.
Base/res/emoji/U+32_U+FE0F_U+20E3.png should not include any emoji presentation selectors. U+FE0F codepoints should be removed from the filename.
Base/res/emoji/U+33_U+FE0F_U+20E3.png should not include any emoji presentation selectors. U+FE0F codepoints should be removed from the filename.
Base/res/emoji/U+35_U+FE0F_U+20E3.png should not include any emoji presentation selectors. U+FE0F codepoints should be removed from the filename.
Base/res/emoji/U+37_U+FE0F_U+20E3.png should not include any emoji presentation selectors. U+FE0F codepoints should be removed from the filename.
Base/res/emoji/U+38_U+FE0F_U+20E3.png should not include any emoji presentation selectors. U+FE0F codepoints should be removed from the filename.
Base/res/emoji/U+39_U+FE0F_U+20E3.png should not include any emoji presentation selectors. U+FE0F codepoints should be removed from the filename.
[FAIL]: Meta/check-emoji.sh
```

**Review by Xexxa — CHANGES_REQUESTED** [review]
...and I was like "how could somebody possible improve my awesome keycaps emoji" and then I compared and yours are surely better. :-D

When removing `U+FE0F` from the filename `U+31_U+FE0F U+20E3.png` you also removed `U+20E3`, only `U+FE0F` should have been removed.

See correct filenames in https://github.com/SerenityOS/serenity/pull/15034/files (the ones that was renamed).

**Comment by electrikmilk** [comment]
> ...and I was like "how could somebody possible improve my awesome keycaps emoji" and then I compared and yours are surely better. :-D
> 
> When removing `U+FE0F` from the filename `U+31_U+FE0F U+20E3.png` you also removed `U+20E3`, only `U+FE0F` should have been removed.
> 
> See correct filenames in https://github.com/SerenityOS/serenity/pull/15034/files (the ones that was renamed).

Thanks! I didn't know they were there as https://emoji.serenityos.net/ did not show them until when I checked a second ago.

**Comment by Xexxa** [comment]
> > ...and I was like "how could somebody possible improve my awesome keycaps emoji" and then I compared and yours are surely better. :-D
> > When removing `U+FE0F` from the filename `U+31_U+FE0F U+20E3.png` you also removed `U+20E3`, only `U+FE0F` should have been removed.
> > See correct filenames in https://github.com/SerenityOS/serenity/pull/15034/files (the ones that was renamed).
> 
> Thanks! I didn't know they were there as https://emoji.serenityos.net/ did not show them until when I checked a second ago.

That's not strange, I fixed the issue on https://emoji.serenityos.net/ after seeing your PR. Basically we do U+31_U+20E3.png and my site expected U+0031_U+20E3.png. :^)

**Review by Xexxa — COMMENTED** [review]
Looks great.

Just remove `Base/res/emoji/.DS_Store` :^)

**Review by Xexxa — APPROVED** [review]
LGTM!

**Pull request merged**
