### PR TITLE
Add `binutils-devel` to fedora build instructions

### PR DESCRIPTION
**Pull request by lindgrenj6**
Ran into this when building on Fedora 34.

### CODE REVIEW

**Comment by linusg** [comment]
See #7104. I'm still curious why and if this is actually needed - I'm building the toolchain and serenity just fine on different Fedora 34 machines.

**Comment by linusg** [comment]
If you get the same error as in the linked PR, please provide details from `config.log` as the message suggests.

**Comment by lindgrenj6** [comment]
Interesting! My apologies. Well either way I'll try to be of some use. It looks like my error is different at least.

The error I ran into was: `cannot find -lbfd` during the `BuildIt.sh` script run:
```
[binutils/install] make[4]: Entering directory '/tmp/serenity/Toolchain/Build/i686/binutils/bfd'
[binutils/install] /usr/bin/ld: cannot find -lbfd
[binutils/install] collect2: error: ld returned 1 exit status
```

Here is the config.log for buildutils/install: https://gist.github.com/lindgrenj6/40dcad61b8cc5cf3977669adf9c487b6

**Comment by linusg** [comment]
Had a look around the internet, no conclusive solution. Let's just add it to the list then :)

**Pull request merged**
