### PR TITLE
readelf: Add support for core notes and relocations

### PR DESCRIPTION
**Pull request by bcoles**
`readelf` now supports core notes and relocations. Perhaps the must immediately useful feature is the ability to read notes from core dump files.

read notes from core dump file

This also adds minimal output for the dynamic section (simply printing the number of dynamic entries, but not displaying these entries).

This also adds output for unwind which simply prints a message stating that unwind info is not supported. This is the same as GNU `readelf` which supports unwind info only for a very limited number of architectures (ie, not x86 and x86_64). However, GNU `readelf` attempts to parse unwind information as part of `-a` (all) (even though it will usually fail) and so does our `readelf`. Thus adding a message related to unwind info is included for consistency.

### CODE REVIEW

**Comment by Dexesttp** [comment]
Rather than having two `has_section` and `lookup_section` methods, could you make `lookup_section` return an "Optional<Section>" ? I don't think it would slow things down since the `lookup_section` method (and the new `has_section`) are already creating a bunch of section objects  to look up their names.

**Comment by bcoles** [comment]
> 
> 
> Rather than having two `has_section` and `lookup_section` methods, could you make `lookup_section` return an `Optional<Section>` ? I don't think it would slow things down since the `lookup_section` method (and the new `has_section`) are already creating a bunch of section objects to look up their names.

Perhaps. I'm not interested in reworking the ELF image and relocation image API for the moment.

I've removed the changes to LibELF from this PR. It now only modifies `readelf`.

**Comment by awesomekling** [comment]
Nice!

**Comment by bcoles** [comment]
> 
> 
> > Rather than having two `has_section` and `lookup_section` methods, could you make `lookup_section` return an `Optional<Section>` ? I don't think it would slow things down since the `lookup_section` method (and the new `has_section`) are already creating a bunch of section objects to look up their names.
> 
> Perhaps. I'm not interested in reworking the ELF image and relocation image API for the moment.
> 
> I've removed the changes to LibELF from this PR. It now only modifies `readelf`.

I finally circled back to look at this, only to discover that it was implemented by kling in 16221305ade1e37d68c95d9bf674021afc18570f yesterday.

**Pull request merged**
