### PR TITLE
Utilities: Port to LibMain and with ArgsParser

### PR DESCRIPTION
**Pull request by alexmajor**
Update seq command to use serenity main and argument parser along
with clean-up.

### CODE REVIEW

**Review by kennethmyhra — APPROVED** [review]
LGTM! Just needs a rebase

**Comment by bgianfo** [comment]
Another merge conflict @alexmajor

**Comment by alexmajor** [comment]
> Another merge conflict @alexmajor 

Resolved

**Review by bgianfo — CHANGES_REQUESTED** [review]
I played around with this locally and it looks like this breaks the case where you start at a negative number. For example this is the output before your change: 

```
$ seq -4 1 4
-4
-3
-2
-1
0
1
2
3
4
```

Output after your change:

```
$ seq -4 1 4
Unrecognized option -1
Usage: 

... snip ...
```

**Comment by alexmajor** [comment]
> I played around with this locally and it looks like this breaks the case where you start at a negative number. For example this is the output before your change:
> 
> ```
> $ seq -4 1 4
> -4
> -3
> -2
> -1
> 0
> 1
> 2
> 3
> 4
> ```
> 
> Output after your change:
> 
> ```
> $ seq -4 1 4
> Unrecognized option -1
> Usage: 
> 
> ... snip ...
> ```

Thank you for testing this. I will investigate and now I get to figure out how to add a test!

**Pull request closed without merging**
