### PR TITLE
Use C++20 "using enum" to shorten long switch case statements

### PR DESCRIPTION
**Pull request by Mandar12**
This will improve readability.

### CODE REVIEW

**Comment by ADKaster** [comment]
I believe the reason we didn't have these before was because of the experimental clang cross compiler. clang trunk (or whichever release we picked, 12.0.1?) doesn't support `using enum` yet.

@BertalanD ?

I personally really like `using enum` though 🙂

**Comment by ADKaster** [comment]
Actually it looks like using enum is in trunk and will be part of clang 13. Which currently has release candidate 1 in the llvm tree, so maybe we'll be able to use it soon (tm)

**Comment by BertalanD** [comment]
@ADKaster is correct. This wouldn't compile with Clang 12.0.1, which is a shame, but not a deal breaker IMO.

Good news though, Clang 13 (will ship with this feature)[https://clang.llvm.org/cxx_status.html] in a month or so. Or if we insist on this, I can port over my toolchain patches to 13.0.0-rc1.

**Comment by BertalanD** [comment]
This compiles successfully with the release candidate compiler (#9378).

Once we have that,  44b6f402ae72d26b43efca6f68deab8d66c9e807 can be reverted.

**Pull request closed without merging**
