### PR TITLE
WindowServer: Don't crash when closing an AutocompleteBox

### LINKED ISSUE #10982: WindowServer: Crash due to GML Playground behavior
To Reproduce:

* Open GML Playground.
* Additionally, have the following applications open: Terminal, the Terminal settings dialogue window, Settings, Keyboard Settings.
* Start inserting a widget by typing @ and then some more stuff. The autocomplete window must appear.
* Press Enter while the autocomplete window is open to select that class. I had this happen with GUI::Label, specifically.

WindowServer then crashes, taking all applications, applets and the desktop environment with it, but SystemServer restarts it successfully. A crash report for Playground appears, but that's probably just because WindowServer disappeared suddenly. I'll include it here anyway.
```
521.431 WindowServer(15:15): ASSERTION FAILED: parent()
../../Userland/Services/WindowServer/Window.cpp:529
521.440 [#0 WindowServer(15:15)]: Terminating WindowServer(15) due to signal 6
521.445 [#0 FinalizerTask(4:4)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) + 0x572
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) [clone .localalias] + 0x40e
0xdeadc0de  Kernel::Scheduler::pick_next() [clone .localalias] + 0x12f
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() [clone .localalias] + 0x214
0xdeadc0de  Kernel::Thread::die_if_needed() [clone .localalias] + 0x1bb
0xdeadc0de  syscall_handler + 0x2364
0xdeadc0de  syscall_asm_entry + 0x31
0x9f802365  libc.so: .text + 0x16365
0x9f7ed94a  libc.so: .text + 0x194a
0x9f7ee3dd  libc.so: .text + 0x23dd
0xafd11f88  /bin/WindowServer: .text + 0x68f88
0xafd20a3a  /bin/WindowServer: .text + 0x77a3a
0xafd2794f  /bin/WindowServer: .text + 0x7e94f
0xafd27d6f  /bin/WindowServer: .text + 0x7ed6f
0xafd28047  /bin/WindowServer: .text + 0x7f047
0xafd28433  /bin/WindowServer: .text + 0x7f433
0xafd0a908  /bin/WindowServer: .text + 0x61908
0xafd0aeec  /bin/WindowServer: .text + 0x61eec
0xafcbab88  /bin/WindowServer: .text + 0x11b88
0xafcbae18  /bin/WindowServer: .text + 0x11e18
0xafcd8749  /bin/WindowServer: .text + 0x2f749
0x1a506d53  libipc.so.serenity: .text + 0x1d53
0xafcccbb2  /bin/WindowServer: .text + 0x23bb2
0x57e120da  libcore.so.serenity: .text + 0x2b0da
0x57e133d1  libcore.so.serenity: .text + 0x2c3d1
0x57dfe4d1  libcore.so.serenity: .text + 0x174d1
0x57dff01b  libcore.so.serenity: .text + 0x1801b
0xafcaaadf  /bin/WindowServer: .text + 0x1adf
0xafcaad9d  /bin/WindowServer: .text + 0x1d9d

521.510 [#0 FinalizerTask(4:4)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) + 0x572
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) [clone .localalias] + 0x40e
0xdeadc0de  Kernel::Scheduler::pick_next() [clone .localalias] + 0x12f
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() [clone .localalias] + 0x214
0xdeadc0de  Kernel::Thread::die_if_needed() [clone .localalias] + 0x1bb
0xdeadc0de  syscall_handler + 0x2364
0xdeadc0de  syscall_asm_entry + 0x31
0x9f800b83  libc.so: .text + 0x14b83
0x1c0aa69f  libpthread.so: .text + 0x169f
0x1c0aa723  libpthread.so: .text + 0x1723
0xa27926ae  libthreading.so.serenity: .text + 0x6ae
0xa27935f5  libthreading.so.serenity: .text + 0x15f5
0x1c0a9876  libpthread.so: .text + 0x876

521.547 [#0 FinalizerTask(4:4)]: Generating coredump for pid: 15
522.984 CrashDaemon(16:16): New coredump file: /tmp/coredump/WindowServer_15_1637433012
522.989 CrashDaemon(16:16): Unable to map coredump /tmp/coredump/WindowServer_15_1637433012: Error(errno=13)
523.011 Playground(40:40): ASSERTION FAILED: response
../../Userland/Libraries/LibIPC/Connection.h:95
523.020 [#0 Playground(40:40)]: Terminating Playground(40) due to signal 6
523.023 SystemServer(6:6): Service WindowServer has exited with exit code 6
523.039 SystemServer(22:22): Service Desktop has exited with exit code 0
523.057 SystemServer(22:22): Service ClipboardHistory.Applet has exited with exit code 0
523.064 SystemServer(22:22): Service Audio.Applet has exited with exit code 0
523.075 SystemServer(22:22): Service Network.Applet has exited with exit code 0
523.084 [#0 FinalizerTask(4:4)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) + 0x572
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) [clone .localalias] + 0x40e
0xdeadc0de  Kernel::Scheduler::pick_next() [clone .localalias] + 0x12f
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() [clone .localalias] + 0x214
0xdeadc0de  Kernel::Thread::die_if_needed() [clone .localalias] + 0x1bb
0xdeadc0de  syscall_handler + 0x2364
0xdeadc0de  syscall_asm_entry + 0x31
0xae9fd365  libc.so: .text + 0x16365
0xae9e894a  libc.so: .text + 0x194a
0xae9e93dd  libc.so: .text + 0x23dd
0x84e1835f  libgui.so.serenity: .text + 0x12c35f
0x84d0f635  libgui.so.serenity: .text + 0x23635
0x84de5237  libgui.so.serenity: .text + 0xf9237
0x84e0989f  libgui.so.serenity: .text + 0x11d89f
0x619393d1  libcore.so.serenity: .text + 0x2c3d1
0x84e227e2  libgui.so.serenity: .text + 0x1367e2
0x84e2362a  libgui.so.serenity: .text + 0x13762a
0x619393d1  libcore.so.serenity: .text + 0x2c3d1
0x619244d1  libcore.so.serenity: .text + 0x174d1
0x6192501b  libcore.so.serenity: .text + 0x1801b
0x84d0c448  libgui.so.serenity: .text + 0x20448
0x626f88bc  /bin/Playground: .text + 0x18bc
0x626f8c6d  /bin/Playground: .text + 0x1c6d
530.060 CrashReporter(53:53): 0x619393d0: [libcore.so.serenity] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb0 (Object.cpp:213)     
530.070 CrashReporter(53:53): 0x84e227e1: [libgui.so.serenity] GUI::Window::handle_key_event(GUI::KeyEvent&) +0x71 (Window.cpp:458)
530.076 CrashReporter(53:53): 0x84e23629: [libgui.so.serenity] GUI::Window::event(Core::Event&) [clone .localalias] +0xe9 (Window.cpp:626)
530.094 CrashReporter(53:53): 0x619393d0: [libcore.so.serenity] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb0 (Object.cpp:213)     
530.104 CrashReporter(53:53): 0x619244d0: [libcore.so.serenity] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x180 (EventLoop.cpp:413)
530.118 CrashReporter(53:53): 0x6192501a: [libcore.so.serenity] Core::EventLoop::exec() +0x6a (EventLoop.cpp:370)
530.124 CrashReporter(53:53): 0x84d0c447: [libgui.so.serenity] GUI::Application::exec() +0x27 (Application.cpp:119)
530.137 CrashReporter(53:53): 0x626f88bb: [/bin/Playground] main +0x124b (main.cpp:290)
530.147 CrashReporter(53:53): 0x626f8c6c: [/bin/Playground] _entry +0x5c (crt0.cpp:46)
```

### PR DESCRIPTION
**Pull request by AtkinsSJ**
This fixes #10982

If a `GUI::WindowType::ToolWindow` Window is open when the AutocompleteBox closes, then WindowServer crashes on a VERIFY().. In `Window::event()`, the WindowCloseRequest event was being sent to the AutocompleteBox while it had no client and no parent attached, even though it had a parent when it was created. This patch fixes the crash by avoiding the VERIFY, since I believe that the WindowCloseRequest does not make sense to bubble up to a parent anyway.

I still don't understand why the situation was happening, but this does stop the crashing. I could not find any other windows which would cause the crash when they are closed. Maybe someone who understands WindowServer will have a better idea.

### CODE REVIEW

**Comment by awesomekling** [comment]
This feels hackish. One problem is that we're currently using `Window::m_client` nullity to distinguish between client windows and WindowServer-internal windows. However, when a client disconnects, we'll null out `Window::m_client`, making the window appear WindowServer-internal to logic like this.

Perhaps a more robust fix would be adding a boolean to permanently distinguish between client/internal windows?

**Comment by AtkinsSJ** [comment]
It's definitely a hack. That sounds much better!

**Comment by AtkinsSJ** [comment]
Turns out Window already has an `is_internal()` method so I've replaced the two checks for `m_client` with that. It... sort of works? Turns out there are two crashes: the wrong VERIFY that a window has a parent, which this fixes; and then an IPC issue here:

https://github.com/SerenityOS/serenity/blob/0d679bf34892b8e4577798d7e877af40f3cea0e8/Userland/Libraries/LibGUI/Window.cpp#L207

This triggers the VERIFY here:
https://github.com/SerenityOS/serenity/blob/0d679bf34892b8e4577798d7e877af40f3cea0e8/Userland/Libraries/LibIPC/Connection.h#L95

... I guess because there's no client connection to get a response from.

In master, that just crashes. With the `is_internal()` changes, it causes a kernel panic.

**Comment by AtkinsSJ** [comment]
Changing the autocomplete window to a WindowType::Menu stops the crash, which makes me think it must be key that it's a tooltip. And the only place that does anything different with Tooltip windows is this:

https://github.com/SerenityOS/serenity/blob/0d679bf34892b8e4577798d7e877af40f3cea0e8/Userland/Services/WindowServer/WindowManager.cpp#L1787-L1790

Sure enough, without that loop, the crash doesn't happen. I don't know if that loop is important, the commit where it was added doesn't comment on it. Looks like it might be there to hide tooltips when you switch virtual desktops, but that happens fine without that loop.

Again, removing that doesn't feel like the solution to the real bug but I don't know what _is_. Seems very much like the autocomplete window is closed by AutocompleteBox, and then somehow it gets sent an extra WindowCloseRequest when it's already disconnected and closed.

**Comment by AtkinsSJ** [comment]
New solution to the WindowServer crash: Modifying `Window::request_close()` to this:

```c++
void Window::request_close()
{
    if (is_destroyed())
        return;

    Event close_request(Event::WindowCloseRequest);
    event(close_request);
}
```

Alternatively, I could check it inside that previously-mentioned loop, but this feels safer. Now, I don't know whether it's valid that a window can be marked as destroyed while still attached to a parent, but it doesn't seem to cause any other problems, and I am not the right person to figure that out if it does need fixing. :sweat_smile:

**Pull request merged**
