### PR TITLE
LibWeb: Implement quotes in `content`

### PR DESCRIPTION
**Pull request by AtkinsSJ**
Implement the `quotes` property which defines what quotation marks to use, and the `open-quote`, `close-quote`, `no-open-quote`, and `no-close-quote` values for the `content` property which use those quotation makes in generated content.

`quotes` allows a list of opening/closing quotation mark pairs, but we currently always use the first pair available because we do not track the current nesting level.

image

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Changes: Fixed conflict from ref-test changes.

**Comment by AtkinsSJ** [comment]
Changes: Give QuotesData.strings an initializer.

**Review by ADKaster — APPROVED** [review]
something something could use tests

**Comment by ADKaster** [comment]
wow as I typed that I saw the test at the top of the diff. never mind me

**Pull request merged**
