### PR TITLE
Base: Add more emoji

### PR DESCRIPTION
**Pull request by toblu302**
🐑 - U+1F411 sheep
🐗 - U+1F417 boar
🐷 - U+1F437 pig face
🐻 - U+1F43B bear face
🐼 - U+1F43C panda face

### CODE REVIEW

**Review by kleinesfilmroellchen — APPROVED** [review]
Did you run optipng or zopflipng on the images?

**Review by Xexxa — APPROVED** [review]
Perfect this time. Emoji looks good(again) and commit message and optimization according to (unwritten?) rules this time. Happy to see you contribute again @toblu302, I hope to see many more!

**Comment by linusg** [comment]
> (unwritten?)

https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy

> If you have images that go along with your code, run `optipng -strip all` on them to optimize and strip away useless metadata - this can reduce file size from multiple kilobytes to a couple hundred bytes.

@Xexxa :)

**Comment by Xexxa** [comment]
> > (unwritten?)
> 
> https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy
> 
> > If you have images that go along with your code, run `optipng -strip all` on them to optimize and strip away useless metadata - this can reduce file size from multiple kilobytes to a couple hundred bytes.
> 
> @Xexxa :)

Afaik there is no info in the official docs what your commit message should contain when submitting emoji and I know from @linusg what is expected. So some rules seems to be unwritten:^)

**Pull request merged**
