### PR TITLE
DynamicLoader: Make heuristic for running directly actually correct

### PR DESCRIPTION
**Pull request by supercomputer7**
When we run directly the dynamic loader, we shouldn't rely on the passed program path to be run, but rather on whether the main program fd number is not -1, because the kernel will set it to a non-negative number if it exists.

To test that the heuristic is working correctly, the /usr/lib/Loader.so file can be copied to /tmp/Loader.so and then be invoked from that path.

### CODE REVIEW

**Comment by Hendiadyoin1** [comment]
`being running`

**Comment by BertalanD** [comment]
+1 for removing the reliance on hard-coded paths.

Quick question, though: how does this behave in the edge case of running `/usr/lib/Loader.so /usr/lib/Loader.so`. The "inner" program can access the same auxiliary vector as well, so it will think that it's loaded as the interpreter as well, which means infinite recursion. (?)

**Comment by supercomputer7** [comment]
> +1 for removing the reliance on hard-coded paths.
> 
> Quick question, though: how does this behave in the edge case of running `/usr/lib/Loader.so /usr/lib/Loader.so`. The "inner" program can access the same auxiliary vector as well, so it will think that it's loaded as the interpreter as well, which means infinite recursion. (?)

Trying to run the proposed command will actually make it fail - because the "second" instance will try to invoke a syscall directly (without LibC) which after the "first" instance is disabled per our "no syscalls from any other memory regions than LibC" security measure.

Still, I'd like to actually refuse running the dynamic loader this way - in general we should not allow running self-relocating shared object ELFs this way, as there's really no added value this way.

**Comment by supercomputer7** [comment]
I just disabled the annotation of a syscall region (which was simply one line `int rc = syscall(SC_prctl, PR_SET_NO_NEW_SYSCALL_REGION_ANNOTATIONS, 1, 0, nullptr);`).

The result is:
Screenshot_2023-10-28_10-42-29

Still I want to disable running of static-pie ELFs altogether, so a patch will be ready soon for that.

**Review by ADKaster — APPROVED** [review]

**Pull request merged**
