### PR TITLE
Kernel: Resolve a couple of deadlocks in MasterPTY when running under SMP enabled

### PR DESCRIPTION
**Pull request by IdanHo**

### CODE REVIEW

**Comment by supercomputer7** [comment]
This somewhat reverts #19882. Is it OK to actually take the spinlock for a moment to check that there's no SlavePTY attached and then continue to the rest of the unblocking sequence?

**Comment by IdanHo** [comment]
@supercomputer7 I dont think it reverts it, accesses to slave are still protected with a spinlock. Specifically in these 2 contexts the rest of the sequences do not depend on holding the slave lock.

In the case of the unblocking callback, evaluating the block condition will simply trigger a check to see if waiters may be unblocked, if it was called spuriously (e.g. because the slave disappeared between calling the unblock callback and the actual block condition evaluation), the waiters will simply not unlock.

In the case of the read method, i think it's also ok, because the check is if slave is null, and slave starts non-null, and can only change its state to null once (and never back to non-null) in notify_slave_closed. So if the check happens, and it returns non-null, and then it turns null concurrently, and we call m_buffer->read, the behaviour from the perspective of the read caller is the same as if the slave turned null after we called m_buffer->read. On the other hand, if the check happens and returns null, then it can possibly change to non-null after.

**Comment by supercomputer7** [comment]
> @supercomputer7 I dont think it reverts it, accesses to slave are still protected with a spinlock. Specifically in these 2 contexts the rest of the sequences do not depend on holding the slave lock.
> 
> In the case of the unblocking callback, evaluating the block condition will simply trigger a check to see if waiters may be unblocked, if it was called spuriously (e.g. because the slave disappeared between calling the unblock callback and the actual block condition evaluation), the waiters will simply not unblock.
> 
> In the case of the read method, i think it's also ok, because the check is if slave is null, and slave starts non-null, and can only change its state to null once (and never back to non-null) in notify_slave_closed. So if the check happens, and it returns non-null, and then it turns null concurrently, and we call m_buffer->read, the behaviour from the perspective of the read caller is the same as if the slave turned null after we called m_buffer->read. On the other hand, if the check happens and returns null, then it can possibly change to non-null after.

Thank you very much for the explanation!

Can you please add comments so this is clear for anyone viewing the code? Especially the second paragraph - it was not clear to me but now makes a lot more sense. The first paragraph is also valuable as a comment for the unblocking callback part.

**Comment by IdanHo** [comment]
Sure, added the explanations as comments.

**Pull request merged**
