### PR TITLE
LibWeb: Some CSS::Parser related cleanups/refactorings

### PR DESCRIPTION
**Pull request by Hendiadyoin1**
No functional changes should be included.

The biggest change is the u32 for <delim-token>'s.

Due to the large size of the refactoring the full diff is not really readable, for a better overview use the per commit diffs.

### CODE REVIEW

**Review by AtkinsSJ — CHANGES_REQUESTED** [review]
Very nice! I especially like that delimiter change. I do have a couple of minor nit-picks.

**Comment by Hendiadyoin1** [comment]
Rebasing this through two conflicts is difficult, because I never know what changed and the diff algorithm does not like bigger code movements...

**Comment by Hendiadyoin1** [comment]
Ups failed at one rename
Will push in a second

**Review by AtkinsSJ — APPROVED** [review]
Looks good to me! Let's get this merged before you get any more conflicts. :^)

**Pull request merged**
