### PR TITLE
LibGUI, About: A prettier About dialog

### PR DESCRIPTION
**Pull request by nvella**
Following on from the discussion in #2273, this PR contains the implementation for the prettier about dialog.

The version information (currently short Git hash) is written to `/res/version.ini` at build time (in `build-root-filesystem.sh`), which is then later displayed in the dialog.

Screenshots:
image

image

### CODE REVIEW

**Comment by bugaevc** [comment]
> `/res/version.ini`

Should be `/ect/version.ini`

**Comment by linusg** [comment]
> Should be /ect/version.ini

From #2273:

> Currently I'm writing the version information to /res/version.ini as part of the build-root-filesystem.sh script. I'm thinking /res is a good place for this file, as most graphical applications unveil it for their icons.

**Comment by bugaevc** [comment]
Hmmm, but that's more of a workaround for not unveiling `/etc/` in every GUI app than an actual reason why it belongs in `/res`. ini config files is exactly the kind of thing that belongs into `/etc`, while resources (such as images) belong in `/res`.

If there's no good solution, we can indeed leave it in `/res`, but let's not pretend it's not a workaround and it belongs there :slightly_smiling_face:

**Comment by nvella** [comment]
It definitely is a work-around 😅 I felt that `/res` was 'best-effort' for what will definitely be unveiled, but it's very much not preferable. It'd be cool if there was a 'guarantee' of sorts around certain 'safe' files which will always be unveiled - but these are definitely not decisions for me to make.

**Comment by awesomekling** [comment]
Let's roll with it. We can tweak it as we go, if we think of improvements :)

Nice work @nvella :star:

**Pull request merged**
