### PR TITLE
Base: Add some symbols to Katica

### PR DESCRIPTION
**Pull request by electrikmilk**
This adds Currency Symbols (20A0—20CF), Combining Diacritical Marks for Symbols (20D0—20FF), and Number Forms (2150—218F) to Katica Regular 10.

Screen Shot 2022-01-16 at 00 52 42
Screen Shot 2022-01-16 at 00 53 04

### CODE REVIEW

**Comment by electrikmilk** [comment]
Synced with master in latest commit.

**Comment by electrikmilk** [comment]
Properly synced with master in most recent commit. Didn't realize @Xexxa has been so busy!

**Comment by bgianfo** [comment]
Nit: it would be nice if the commit message had the details of which symbols were added like the PR description has.

**Comment by Xexxa** [comment]
> Properly synced with master in most recent commit. Didn't realize @Xexxa has been so busy!

Yeah, guess so. :) As you are probably aware you can copy multiple glyphs in font editor(shift click to select a range), so I would recommend working on your glyphs in a separate file and when you are done start by doing a fresh pull and then copy over your work. ;-)

**Comment by electrikmilk** [comment]
> > Properly synced with master in most recent commit. Didn't realize @Xexxa has been so busy!
> 
> Yeah, guess so. :) As you are probably aware you can copy multiple glyphs in font editor(shift click to select a range), so I would recommend working on your glyphs in a separate file and when you are done start by doing a fresh pull and then copy over your work. ;-)

That's fair, I'll do that in the future just to be sure.

**Comment by electrikmilk** [comment]
> Nit: it would be nice if the commit message had the details of which symbols were added like the PR description has.

Fair enough, amended commit.

**Pull request merged**
