### PR TITLE
AK+LibJS: Improve floating point decimals formatting

### PR DESCRIPTION
**Pull request by gmta**
Both our AK formatter and LibJS' `Number.prototype.toFixed` learn how to format a larger number of decimals correctly. We now also round floating points during formatting, so e.g. `1.999` formatted with 1 decimal results in `2.0`.

Note that in LibJS I diverged from the spec for this, but most other JS engines seem to do this as well for `.toFixed`.

Fixes 1 test262 case (`built-ins/Number/prototype/toFixed/range.js`).

### CODE REVIEW

**Comment by gmta** [comment]
> For the current implementation more precision can be calculated by [retrieving one digit at a time](https://github.com/ronak69/serenity/commit/463d3d721647f3dbefc8c15a77558043e39c1005#diff-ed46a10c48f9704561d6d3668b75fc3bec72ea9a36adc72c00793a6c82496dcb). But anyway, a proper algorithm like ryu or dragonbox would be so much better.

...this PR is retrieving one digit at a time? And yes, we still have the FIXME as you can see.

**Comment by trflynn89** [comment]
The LibWeb test failure seems closely related, unless this has flaked before:
```diff
-rotate(1deg) => matrix(0.999847, 0.017452, -0.017452, 0.999847, 0, 0)
-rotateX(1rad) => matrix3d(1, 0, 0, 0, 0, 0.540302, 0.841470, 0, 0, -0.841470, 0.540302, 0, 0, 0, 0, 1)
-rotateY(1grad) => matrix3d(0.999876, 0, -0.015707, 0, 0, 1, 0, 0, 0.015707, 0, 0.999876, 0, 0, 0, 0, 1)
+rotate(1deg) => matrix(0.999848, 0.017452, -0.017452, 0.999848, 0, 0)
+rotateX(1rad) => matrix3d(1, 0, 0, 0, 0, 0.540302, 0.841471, 0, 0, -0.841471, 0.540302, 0, 0, 0, 0, 1)
+rotateY(1grad) => matrix3d(0.999877, 0, -0.015707, 0, 0, 1, 0, 0, 0.015707, 0, 0.999877, 0, 0, 0, 0, 1)
```

We do have an implementation of Ryu in AK/StringFloatingPointConversions.h FWIW (not saying we need to use it right away here, just mentioning in case you didn't know)

**Comment by gmta** [comment]
@trflynn89

> The LibWeb test failure seems closely related

JFC - again I was tricked by the Lagom test that does not include the Ladybird build by default. Thanks for noticing! Will fix that test up first, that's the rounding improvement in the diff playing a role. Will also take a look at Ryu to see if that's worthwhile to use for our formatting.

**Comment by gmta** [comment]
Looking at `AK/StringFloatingPointConversions.{h,cpp}`, we might definitely be able to use that. Some things are missing like f80 support and rounding to an arbitrary number of decimals. Also that branch by @ronak69 looks interesting and could maybe be adapted to the new code after this PR is merged? Support for zero padding in f80 and hexadecimal floats seems pretty awesome :^)

**Pull request merged**
