### PR TITLE
LibCore: Implement waiting for the debugger on FreeBSD

### PR DESCRIPTION
**Pull request by nipos**
This implements #20327 for the FreeBSD platform.
It compiles fine and I think it should theoretically work fine,but unfortunately I couldn't find out how to bring it into that state where it waits for a debugger,so I couldn't really try it.
Never worked with debuggers before.
Would be nice if someone could tell me how to try it or try it for me.
I don't expect any issues,however,as it is nearly identical to the MacOS implementation.

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Once you have a program that uses `Process::wait_for_debugger_and_break()`, you should be able to run it, and then `pidof ProgramNameHere` to get its pid, and then `gdb -p PidHere` to attach to it.

**Review by LucasChollet — COMMENTED** [review]
We have the `AK_OS_BSD_GENERIC` that covers both macOS and other BSDs, so you might be able to do something like:
```cpp
#ifdef AK_OS_BSD_GENERIC
// Common implementation
#ifdef AK_OS_MACOS
// Specific return for macOS
#elif AK_OS_FREEBSD
// Specific return for FreeBSD
#endif
```

**Comment by LucasChollet** [comment]
> But how can I tell the program that it should wait for the debugger?
I think that you want `Process::wait_for_debugger_and_break()`

> I know,but I'm only implementing that for FreeBSD right now.
I don't know how that should be implemented for other BSDs but I'm sure there is something to do to avoid code duplication.

**Comment by ADKaster** [comment]
In order to test you need to insert the call to wait_for_debugger_and_break somewhere in the main function or other code path in the application, and rebuild the application. In this case, either the Ladybird UI process, or the WebContent process.

**Comment by nipos** [comment]
The merge conflict caused by the Hurd implementation is now fixed.

**Pull request merged**
