### PR TITLE
Kernel+Userland: Remove ProcFS PCI node, remove Hardware tab from SystemMonitor

### PR DESCRIPTION
**Pull request by supercomputer7**
Still a draft, because I'm not sure if this is the right direction for `SystemMonitor`. What I do know is that we need a separate application, like in Windows, that describes all of the connected hardware, preferably in a tree-based manner, from SysFS and certainly not from the ProcFS. As for Storage data, `SystemMonitor` might still be a better choice than implementing a new application. However, we technically could take `PartitionEditor` and the storage data from `SystemMonitor` and create a `StorageManager` GUI application, similarly to how Windows allows you to view and manage partitions and other storage devices in one place.

### CODE REVIEW

**Comment by supercomputer7** [comment]
For now I just remove the Hardware tab. It seems that we can think about the Storage tab later on, but let's just get rid of the awkward Hardware tab which in my opinion should not be in SystemMonitor, but in a GUI application called "Hardware Manager" or something like that.

**Comment by linusg** [comment]
> What I do know is that we need a separate application, like in Windows, that describes all of the connected hardware, preferably in a tree-based manner

Yes! I've been working on that a while ago in private, might be usable as the base for that :)

**Review by linusg — COMMENTED** [review]
Typo in first commit: tabs -> tab

**Comment by supercomputer7** [comment]
> Typo in first commit: tabs -> tab

Done.

> Yes! I've been working on that a while ago in private, might be usable as the base for that :)

I see. I'm quite comfortable with doing this because we can still view this info with `lscpu` and `lspci`, so it is just not exposed from a GUI application yet. I might get into working on a GUI application, but it is certainly an area of the codebase I'm much more new to, and to be honest, other people can pick this up quicker than me. I still don't know how to design such GUI application to be reasonably good-looking (and I don't talk about the code but it's about mere GUI design which is something I'm not used to do) for this task. Still, I might consider this when I find time or find this more interesting than other tasks in the project I need to complete first :)

**Pull request merged**
