### PR TITLE
Demos: Use ErrorOr<T> syntax

### PR DESCRIPTION
**Pull request by pbrw**
Updated all remaining demos to support new LibMain features:

- changed `main` to `serenity_main`
- passing one arguments object if necessary
- made use of TRY with pledge and unveil 

I decided to squash those changes into one PR to not stress pipelines too much.

### CODE REVIEW

**Comment by pmhpereira** [comment]
There is now a TRY() pattern for creating both Application and Window.

```    
auto app = TRY(GUI::Application::try_create(arguments));
auto window = TRY(GUI::Window::try_create());
```

**Comment by pbrw** [comment]
Work in progress. New method compatible with TRY(...) are quickly introduced and I want to make use of all of them.

**Comment by awesomekling** [comment]
Please remove the merge commit and squash fixups into the relevant preceding commit.

**Comment by pmhpereira** [comment]
What awesomekling meant is that you should interactive-rebase all the commits on this PR:
- rebase the 1st commit on this PR to be on-top of the current `master`.
- DELETE the ones called "merge" (because rebasing the 1st commit will automatically update the PR to the current version of the code)
- EDIT the 1st  commit of each Demo to contain the total changes for that Demo
- DELETE the 2nd commit of each Demo, because you just made the remaining changes to the code in the step above.

If this sounds confusing, you can probably ask on the Discord for some help. :^)

**Comment by pbrw** [comment]
Hey, thanks for help! The commit juggling was definitely the hardest part of this issue but at least I learned the git rebase ;)

PR should be all good now. I put the new wrapped functions in all the places I could find. Such a great task for my first contributions :)

**Comment by awesomekling** [comment]
Very nice, thanks for working on this :)

**Pull request merged**
