### PR TITLE
Ports: Add qop

### PR DESCRIPTION
**Pull request by ninadsachania**

### CODE REVIEW

**Comment by nico** [comment]
From CI:

```
AvailablePorts.md is missing the following ports:
    qop
[FAIL]: Meta/lint-ports.py
```

**Comment by ninadsachania** [comment]
> From CI:
> 
> ```
> AvailablePorts.md is missing the following ports:
>     qop
> [FAIL]: Meta/lint-ports.py
> ```

Fixed.

**Comment by nico** [comment]
Could you squash both commits together, so that the lint step is green at each commit?

**Comment by ninadsachania** [comment]
> Could you squash both commits together, so that the lint step is green at each commit?

Done.

**Pull request merged**
