### PR TITLE
LibGfx/JPEG: Teach JPEGLoader how to be patient with non-compliant images [1/N]

### PR DESCRIPTION
**Pull request by LucasChollet**
Fix this image:

0x00-to-0xFF-between-segments

### CODE REVIEW

**Comment by nico** [comment]
Are there images like this in the wild?

libjpeg-turbo seems to not be able to decode this.

**Comment by LucasChollet** [comment]
> libjpeg-turbo seems to not be able to decode this.

libjpeg (or whatever the default image reader on gnome uses) does

> Are there images like this in the wild?

Is this wild enough?
https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-jpeg/src/test/resources/jpeg/0x00-to-0xFF-between-segments.jpg

No external images are linked by the original author, and the image I added in the description looks very generated on purpose.

**Comment by nico** [comment]
> Is this wild enough? https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-jpeg/src/test/resources/jpeg/0x00-to-0xFF-between-segments.jpg

It's a broken image from a jpeg test suite. That doesn't seem terribly in-the-wild to me.

FWIW, Safari and Chrome/Mac can't display that image either.

**Comment by LucasChollet** [comment]
I made this patch because I assumed that an external image made the author of TwelveMonkeys create the test case.

But I agree, if that's not the case, the interest is quite limited

**Pull request closed without merging**
