### PR TITLE
Userland: less: Dynamically re-wrap lines on resize 

### PR DESCRIPTION
**Pull request by petelliott**
I've been wanting to do this since resizing was added, but never got around to it.

as a bonus, I've ported less to LibMain

Screenshot from 2021-12-27 19-48-26

Screenshot from 2021-12-27 19-48-38

### CODE REVIEW

**Comment by awesomekling** [comment]
It looks like it didn't work correctly for the very first line in the screenshot(?)

**Comment by petelliott** [comment]
> It looks like it didn't work correctly for the very first line in the screenshot(?)

It does it's just probably not a well chosen screenshot. You can see the l from the subline at the end of the first line. I played around with the window a lot and moved the cursor up and down.

**Comment by petelliott** [comment]
> > It looks like it didn't work correctly for the very first line in the screenshot(?)
> 
> It does it's just probably not a well chosen screenshot. You can see the l from the subline at the end of the first line. I played around with the window a lot and moved the cursor up and down.

nevermind, that is a bug.

**Comment by petelliott** [comment]
That was caused by tab widths not being properly calculated. (also you couldn't go up past the end of the first line)

new behavior:
Screenshot from 2021-12-28 10-25-22

**Comment by awesomekling** [comment]
Please use the prefix "less:" (or "Userland/less:" if you really want the nesting) so that https://changelog.serenityos.org/ can understand it :)

**Comment by petelliott** [comment]
> Please use the prefix "less:" (or "Userland/less:" if you really want the nesting) so that https://changelog.serenityos.org/ can understand it :)

done

**Pull request merged**
