### PR TITLE
GlTeapot: Adds the ability to open and view 3D files

### PR DESCRIPTION
**Pull request by ebiederstadt**
This PR adds an open dialog to the GlTeapot demo, making it possible to open and view other 3D objects. Of course right now we can only load objects from OBJ files, but more file formats could be added in the future :^)

### CODE REVIEW

**Comment by stelar7** [comment]
Maybe a rename to 3DModelViewer? (since its no longer just a teapot)

**Comment by Quaker762** [comment]
> Maybe a rename to 3DModelViewer? (since its no longer just a teapot)

Yeah, this should either be moved into its' own program or renamed :)

**Comment by ebiederstadt** [comment]
Thank you for the feedback. Changing the name makes a lot of sense. Of the two options (moving it into a new program and keeping the teapot demo, or just renaming the program), is there one that you prefer? 

Also, if we do rename the program, would it make sense to move it from `demos` to a different category, such as `graphics` or `utilities`?

**Comment by Quaker762** [comment]
> Thank you for the feedback. Changing the name makes a lot of sense. Of the two options (moving it into a new program and keeping the teapot demo, or just renaming the program), is there one that you prefer? 
> 
> Also, if we do rename the program, would it make sense to move it from `demos` to a different category, such as `graphics` or `utilities`?

I'll defer this decision to @awesomekling . Either way, I think moving into `Graphics` would be appropriate :)

**Comment by awesomekling** [comment]
Please squash linting fixups into the relevant preceding commit instead of stacking them in additional commits.

Moving it to the Graphics category makes sense to me. And yeah "3D Model Viewer" sounds excellent. :)

**Comment by ebiederstadt** [comment]
Thank you for the suggestions! I'll change the name and move things over to `graphics` :^)

**Review by linusg — CHANGES_REQUESTED** [review]
Please combine the last two commits into one, renaming (i.e. moving) it once and then again seems unnecessarily complicated. Just do `Demos/GLTeapot` -> `Applications/3DFileViewer` directly. Squashing should do the trick.

**Pull request merged**
