### PR TITLE
LibJS: Add operator precedence parsing

### LINKED ISSUE #1428: LibJS: Add operator precedence parsing
Currently expressions are parsed left to right without regard for operator precedence.

Pratt parsing is a simple and elegant algorithm that can be used:
https://eli.thegreenplace.net/2010/01/02/top-down-operator-precedence-parsing

I'll implement this, so this is a reminder for myself.

### LINKED ISSUE #1432: LibJS: foo.bar() should generate a CallExpression with a MemberExpression inside
cc @sunverwerth

### PR DESCRIPTION
**Pull request by sunverwerth**
Obey precedence and associativity rules when parsing expressions
with chained operators.

This PR also allows call expression with an arbitrary expression as a callee.

Fixes #1432
Fixes #1428

### CODE REVIEW

**Comment by awesomekling** [comment]
This approach looks very intuitive :) What's holding it back?

**Comment by sunverwerth** [comment]
I'm currently making sure everything still works. Also, I got sidetracked and added all the missing tokens 🙃

**Comment by sunverwerth** [comment]
I think this is ready to merge. The few tests that I did parsed correctly.
My brain hurts though, I feel this can be refactored a lot. Especially the `parse_secondary_expression` part.

**Comment by awesomekling** [comment]
Let’s do it!

**Pull request merged**
