### PR TITLE
Base: Emoji stuff

### PR DESCRIPTION
**Pull request by linusg**
Add fire emoji and add a file containing all the emojis we support.

image

### CODE REVIEW

**Comment by awesomekling** [comment]
I know I'm not the best artist but that was supposed to be the facepalm emoji 😢 🤦

**Comment by linusg** [comment]
oh... now that's a facepalm on my end :facepalm:

but as you said it's hard to communicate on so few pixels. Will drop the commit :)

**Comment by awesomekling** [comment]
That fire emoji is literally lit btw

**Comment by awesomekling** [comment]
Feel free to improve the facepalm emoji if you have ideas :D

**Pull request merged**
