### PR TITLE
Don't crash when updating menu item that's not in the window server, …

### PR DESCRIPTION
**Pull request by christopherdumas**
…just don't try to update the server!

Fixes: #82.

### CODE REVIEW

**Comment by christopherdumas** [comment]
Okay, that was the approach I wanted to take (I was just considering making a new branch & PRing when I was done) but I wasn't sure a structural change like that would be OKed.

Am I right in thinking that other GUI objects already keep their own references to server side objects? It sure looks like that seeing as there are no other Update events.

Also, why is there duplicated state on the application side and the window server side? I'm not exactly sure I understand why the distinction, as I've never seen this before. It would help doing this right if I understand more. (:

**Comment by awesomekling** [comment]
> Okay, that was the approach I wanted to take (I was just considering making a new branch & PRing when I was done) but I wasn't sure a structural change like that would be OKed.

It's absolutely okay to make architectural changes, as long as they are sound :)

> Am I right in thinking that other GUI objects already keep their own references to server side objects? It sure looks like that seeing as there are no other Update events.

Yes, the server side objects are referenced by ID in the client. Windows, menubars, menus and menu items have ID's on the client side that correspond to objects on the server side.

> Also, why is there duplicated state on the application side and the window server side? I'm not exactly sure I understand why the distinction, as I've never seen this before. It would help doing this right if I understand more. (:

The main reason for duplicating state is to avoid having to do synchronous IPC, since that could cause apps to lag or stutter while they wait for a response. That said, there is a lot of synchronous IPC still and I'd like to reduce it. Ideally the window server would hold the canonical values for things like window rects and titles, and would push them out to clients as they change.

**Comment by christopherdumas** [comment]
Okay that makes a lot of sense. But...

> Yes, the server side objects are referenced by ID in the client. Windows, menubars, menus and menu items have ID's on the client side that correspond to objects on the server side.

I already was aware of that, what I meant was, how do the other UI elements update the server side state? Like menubars or buttons? I don't see any Update events for anything but MenuItems?

**Comment by awesomekling** [comment]
> I already was aware of that, what I meant was, how do the other UI elements update the server side state? Like menubars or buttons? I don't see any Update events for anything but MenuItems?

Buttons don't have any server-side state, they are rendered and managed entirely on the client side. This is the same for the majority of widgets, they override the GWidget::paint_event() function and draw themselves into their window's backing store using a GPainter.

There's currently no way to remove menubars or menus, which is why you're not seeing any Update* or Remove* messages for that :)

**Comment by christopherdumas** [comment]
Okay, that all makes sense. Just trying to get a feel for what the general design direction is.

**Comment by christopherdumas** [comment]
I deleted my comment relating to that because I realized it was a stupid question (time delta: just long enough for it to be awkward :).

**Comment by christopherdumas** [comment]
Okay, how's this? I made it so that (as the commit message states), menu items start out with a clearly invalid ID of `-1`, instead of the possibly-valid ID of `0`, and *only get a valid ID if the menu they are attached to gets added to the Window Server`. This way, they can just not send the window server updates if the ID isn't valid.

**Comment by awesomekling** [comment]
Yes, this looks nice :) Although now the call to add the go_menu to the menubar is commented out. Other than that it's good!

**Comment by christopherdumas** [comment]
Oh yes I forgot about that. Duh!

**Comment by awesomekling** [comment]
Stellar! Thanks for fixing this, Christopher :+1:

**Comment by christopherdumas** [comment]
My pleasure! It's really nice working on this codebase, to be honest.

**Pull request merged**
