### PR TITLE
Base: Add seven new emoji

### PR DESCRIPTION
**Pull request by tarob0ba**
This commit adds seven more emojis to the system.

🌈 - U+1F308 RAINBOW
🌲 - U+1F332 EVERGREEN TREE
🔺 - U+1F53A UP-POINTING RED TRIANGLE
🔻 - U+1F53B DOWN-POINTING RED TRIANGLE
🚥 - U+1F6A5 HORIZONTAL TRAFFIC LIGHT
🚦 - U+1F6A6 VERTICAL TRAFFIC LIGHT
🇨🇮 - U+1F1E8 U+1F1EE CI Côte d'Ivoire

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
This conflicts on emoji.txt now, sorry! Once you fix that up it's good to go.

**Comment by tarob0ba** [comment]
All done. :]

**Comment by tarob0ba** [comment]
Time to do some squashing.

**Comment by tarob0ba** [comment]
Oops, gotta fix that.

**Pull request merged**
