### PR TITLE
Ports/dosfstools: Small fixups

### PR DESCRIPTION
**Pull request by timschumi**
I meant to mention this on the original PR, but then it got :ninjamerge:d while I was having lunch.

The release tarball arrives preconfigured, so there is no need for us to run autogen manually.

Also, replace the manual creation of symlinks with the `--enable-compat-symlinks` configure option, which automatically creates the symlinks that we want and more.

### CODE REVIEW

**Comment by supercomputer7** [comment]
I know this is probably too much nitpicking, but I'd split these changes into two separate commit, each with its own title.

**Comment by timschumi** [comment]
> I know this is probably too much nitpicking, but I'd split these changes into two separate commit, each with its own title.

I was torn on whether I should, because it really felt like too small of a change to split it up, but on the other hand I had problems with finding a good name for the singular commit. However, if someone else suggests to split up the commit, how could I say no? :^)

**Review by linusg — APPROVED** [review]
Sorry for the :ninjamerge:, should've waited for your approval :^)

**Comment by supercomputer7** [comment]
Thank you for cleaning up my small mistakes :)
Thanks for the merge @linusg !

**Pull request merged**
