### PR TITLE
LibPDF: Simplify CallSubr for type 1 font programs

### PR DESCRIPTION
**Pull request by nico**
https://adobe-type-tools.github.io/font-tech-notes/pdfs/T1_SPEC.pdf says in 8.4 First Four Subrs Entries:

"""If Flex or hint replacement is used in a Type 1 font program, the first four entries in the Subrs array in the Private dictionary must be assigned charstrings that correspond to the following code sequences. If neither Flex nor hint replacement is used in the font program, then this requirement is removed, and the first Subrs entry may be a normal charstring subroutine sequence. The first four Subrs entries contain:

Subrs entry number 0:
3 0 callothersubr pop pop setcurrentpoint return

Subrs entry number 1:
0 1 callothersubr return

Subrs entry number 2:
0 2 callothersubr return

Subrs entry number 3:
return

These code sequences must be encoded and encrypted via charstring encryption in accordance with the rest of the font program. They must then be included in the program using the
RD–NP format."""

My reading of this is that we don't need explicit code for these because these strings have to be present in the subrs data.

Also, the explicit code is incorrect in some cases:
* If neither Flex nor hint replacement is used
* For Type 2 CFF data

Instead, move the code needed to draw type 1 flexs (such as in Tests/LibPDF/type1.pdf) into the othersubr handler, where it belongs.

No real behavior change on any PDF I'm aware of, but it's More Correct and could conceivably help with some PDFs.

### CODE REVIEW

**Comment by nico** [comment]
@metalvoidzz Do you remember why you put this code in? I tried to find PDFs that hit this codepath, but couldn't find any. So this is kind of untested.

(It does fix a regression in a document using CFF outlines though, together with some other changes.)

**Comment by nico** [comment]
(This code was originally added in b14f0950a56 but then moved to its current place in 416585f75a4 to make it usable for CFF fonts.)

**Comment by trflynn89** [comment]
Changes LGTM, lemme know when then open question is resolved and I can merge
(also one of the other PDF PRs caused a merge conflict here)

**Comment by janso3** [comment]
This seems to break our type1.pdf test document:

type1_skip_regression noticed during review

IIRC, this was the reason I added the code in the first place, though maybe I also wanted to handle flex paths differently at different sizes. Admittedly I don't remember the spec quite well.

**Comment by nico** [comment]
Ok, I modified this to do the flex processing in the OtherSubr handler. Tests/LibPDF/type1.pdf now looks good again.

@MacDue The 2nd commit has the FIXME I mentioned on Discord.

**Comment by nico** [comment]
(red CI is unrelated)

**Pull request merged**
