### PR TITLE
LibWeb: Make SubtleCrypto use the correct algorithm name for SHA-1

### PR DESCRIPTION
**Pull request by rosvik**
[The spec](https://w3c.github.io/webcrypto/#sha-registration) defines "SHA-1" as a recognized algorithm name, not "SHA1".

This makes SHA-1 hash values show up on https://string.248.no/.

### CODE REVIEW

**Review by AtkinsSJ — COMMENTED** [review]
Welcome! This is a nice fix. :^)

If you wouldn't mind, could you add a text test for this? Evidently we don't have coverage for the SubtleCrypto algorithms. :sweat_smile: They go [here](https://github.com/SerenityOS/serenity/tree/master/Tests/LibWeb/Text), and there's a Crypto subdirectory in `input` and `expected` already. Just printing out a hash using each algorithm would be helpful. If you need help just post on Discord.

**Comment by rosvik** [comment]
Thanks! Sure, I'll see what I can do 👍

**Comment by rosvik** [comment]
Added a simple test now. :^)

**Comment by awesomekling** [comment]
Great! Welcome to the project :^)

**Pull request merged**
