### PR TITLE
DevTools/Profiler: Replace `DeprecatedFlyString` with `FlyString`

### PR DESCRIPTION
**Pull request by ninadsachania**
This addresses part of https://github.com/SerenityOS/serenity/issues/22447.

### CODE REVIEW

**Comment by nico** [comment]
Similar to what Sam said in discord and what's in #25498: I think most uses of DeprecatedFlyString are valid IIRC, so maybe we should just rename it to FlyBytes or something and keep it? @AtkinsSJ

**Comment by ninadsachania** [comment]
> Similar to what Sam said in discord and what's in #25498: I think most uses of DeprecatedFlyString are valid IIRC, so maybe we should just rename it to FlyBytes or something and keep it? @AtkinsSJ

What should be the new name? `FlyByteString`?

**Comment by nico** [comment]
> > Similar to what Sam said in discord and what's in #25498: I think most uses of DeprecatedFlyString are valid IIRC, so maybe we should just rename it to FlyBytes or something and keep it? @AtkinsSJ
> 
> What should be the new name? `FlyByteString`?

That's a better name than `FlyBytes`, yes :) That sounds right to me.

**Comment by AtkinsSJ** [comment]
It'd be worth checking what the users are. I'm still skeptical about it being useful to have a FlyByteString but I haven't looked into it deeply.

**Comment by nico** [comment]
I think this is generally a good change. It's possible some of these should be removed, but at in many cases this is actually what we want.

However, it's a big patch and it will likely make cherry picks harder, so maybe it should wait until we're done with cherry picks (which will happen, when ladybird gets serious about swift, but also for other reasons eventually).

Or maybe this doesn't cause that many conflicts; we'll find out by just letting it sit for a while :)

**Pull request closed without merging**
