### PR TITLE
LibCrypto: Optimize UnsignedBigInteger import_data/export_data

### PR DESCRIPTION
**Pull request by tomuta**
No need to do complicated math to import or export numbers,
just convert the byte stream to words and vice versa.

### CODE REVIEW

**Comment by tomuta** [comment]
Hm, I didn't realize there were unit tests for this. How do I run these? Seems like `ninja test` only runs the stuff in `Tests/`

**Comment by alimpfard** [comment]
> How do I run these? 

`test-crypto test -c` inside serenity, or `Meta/Lagom/test-crypto test -c` outside.

`ninja test` _should_ run them, as the first test even.

**Comment by tomuta** [comment]
> > How do I run these?
> 
> `test-crypto test -c` inside serenity, or `Meta/Lagom/test-crypto test -c` outside.
> 
> `ninja test` _should_ run them, as the first test even.

Hm not for me. That command only runs 21 tests, looks like only the tests for AK. Seems like there's only Build/Userland/test-crypto, I don't see one in Meta/Lagom.

**Comment by alimpfard** [comment]
Have you built with `BUILD_LAGOM=1`?
that might be why.

**Comment by tomuta** [comment]
> Have you built with `BUILD_LAGOM=1`?
> that might be why.

Well I did not because I had no idea about that variable ;-)

**Comment by alimpfard** [comment]
lol
we should probably mention that somewhere outside of CMakeLists.txt, could probably be useful.

**Comment by tomuta** [comment]
Well I can't get `BUILD_LAGOM=1` to work. I tried `BUILD_LAGOM=ON`, too. Not even blowing away all of `Build/` and rebuilding the toolchain seems to make it work. Whatever, I think this will make it happy...

**Comment by alimpfard** [comment]
Ah, you need to pass it to cmake, sorry if I wasn't clear on that, I use `cmake .. -GNinja -DBUILD_LAGOM=1`.

**Comment by awesomekling** [comment]
Not sure if you got tests working locally, but I ran them here and they seem fine :)
(Also the CI runs them on PR's)

**Pull request merged**
