### PR TITLE
AK+Browser+Ladybird: Fix relative file URL completion

### PR DESCRIPTION
**Pull request by vkoskiv**
The added test case illustrates the issue pretty well. Basically, before this fix, all assets that had a relative URL in a document loaded from a `file://` failed to load.

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Can you swap the commits around so the test passes when it's added?

**Comment by vkoskiv** [comment]
> Can you swap the commits around so the test passes when it's added?

Done!

**Comment by AtkinsSJ** [comment]
Thanks! Sorry to be even more of a pain but now that commit message adding the test needs changing since both tests do pass. :sweat_smile:

**Comment by vkoskiv** [comment]
> Thanks! Sorry to be even more of a pain but now that commit message adding the test needs changing since both tests do pass. sweat_smile

Fixed, thanks. Details are important!

**Pull request merged**
