### PR TITLE
AK: Add `simd_cast<T>` and replace `to_TxN` with it

### PR DESCRIPTION
**Pull request by Hendiadyoin1**

### CODE REVIEW

**Comment by nico** [comment]
Why? RHS looks significantly less nice, no?

**Comment by Hendiadyoin1** [comment]
Feels nicer this way, instead of adding a new `to_XYZ` for every vector we intend to use down the line

**Comment by nico** [comment]
I'd optimize for readability at the call sites. (There are more calls than implementations.)

To me, `auto r = to_u32x4(clamped.x() * 255);` looks much nicer than `auto r = vector_cast<u32x4>(clamped.x() * 255);`.

(If most people working on the project disagree, I'm willing to change my mind though. Maybe worth asking for a show of hands who prefers which form on discord?)

**Comment by nico** [comment]
Thanks for the patch! I renamed it to `simd_cast` per poll and merged it.

**Pull request merged**
