### PR TITLE
LibGUI: ComboBox fix

### LINKED ISSUE #3431: ComboBox: Value is changed when moving mouse over entries
A recent change changed `ComboBox` to highlight the entry the mouse is moving over. But I don't think that should actually change the selected value. At least that is not a behavior I'm accustomed to. E.g. in Display Properties that also causes quite some CPU cycles because it has to load the images. The bigger problem I see is that if you dismiss the ComboBox you're under the impression that the value that is now the selected value was the original value before dismissing it.

### PR DESCRIPTION
**Pull request by pkotzbach**
Fixes #3431

### CODE REVIEW

**Comment by Lubrsi** [comment]
If you put "Fixes" followed by the issue number, e.g. "Fixes #3479", GitHub will automagically close the issue :^)

**Comment by Lubrsi** [comment]
Sorry, I forgot to clarify that it has to be in the body, not the title.

**Comment by pkotzbach** [comment]
Thank you, I'm starting to getting used to github :)

**Comment by awesomekling** [comment]
Please observe the [contribution guidelines](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md)

Specifically:
>**Don't**
>Use weasel-words like "refactor" or "fix" to avoid explaining what's being changed.

We need to have some kind of description of what's being fixed and why. :)

**Pull request closed without merging**
