### PR TITLE
LibVideo/VP9: Make inter-prediction fast path accumulators 32-bit

### PR DESCRIPTION
**Pull request by Zaggy1024**
Some occasional cases could cause the accumulator to overflow and have
an incorrect result. It would be nice to use a smaller accumulator, but
it seems not to be correct. :^(

### CODE REVIEW

**Comment by GMTA** [comment]
Was there a measurable difference between using i16s and i32s there?

**Comment by awesomekling** [comment]
In general, 16-bit math is not faster than 32-bit math on modern CPUs, so unless there is data suggesting otherwise I think we can stick to 32-bit math :)

**Comment by Zaggy1024** [comment]
The case in which I think it may matter is for SIMD, but without using [[gnu::target]] I don't think there's a noticeable difference. Either way, this is the only way it functions correctly, so it'll have to stay this way.

**Comment by Zaggy1024** [comment]
Actually, disregard my previous comment, it appears it causes about a 20% regression in performance, probably due to the above mentioned implications for vectorization. It's unfortunate, but I'm not sure that there's a way around it.

**Comment by Zaggy1024** [comment]
On the bright side, we do gain back most of that performance if we enable AVX2 in that function, which is something that should be possible once Daniel's patch for IFUNC lands.

**Comment by Zaggy1024** [comment]
Looks like I regain a little performance by calculating the products in an i16[8] and then summing after, I'll amend it with that.

**Pull request merged**
