### PR TITLE
Browser: Add DuckDuckGo to bookmarks

### PR DESCRIPTION
**Pull request by xspager**
Google can't have all the fun can it?

### CODE REVIEW

**Comment by danboid** [comment]
duckduckgo.com doesn't open in Browser for me.

**Comment by xspager** [comment]
I hope this motivate fixing some of what's preventing it from open. But I'm new here, so you tell me.

**Comment by danboid** [comment]
I don't think it'll get accepted as a bookmark until we can load and use DDG but it's up to @awesomekling

**Comment by danboid** [comment]
I do prefer to use DDG myself so and agree DDG should be a priority site to get working in Browser.

**Pull request merged**
