### PR TITLE
LibCore: Make TCPServer propagate errors

### PR DESCRIPTION
**Pull request by AtkinsSJ**
Most of this is fairly self-explanatory. All(?) the socket-related syscalls now have Core::System wrappers. TCPServer now returns ErrorOr from any methods that can fail. I've ported EchoServer and TelnetServer to LibMain, so that they can take advantage of this.

Then, I have the experimental commit which I'd really like some feedback on. It's an attempt to solve the problem of "how do you propagate errors that happen inside a callback lambda?" The solution here is, make the callback return an ErrorOr, then pass that error to a second error-handling callback. If that callback isn't set, just log the error and exit.

Also, we lose some of the more-detailed error messages by replacing everything with TRY. There's probably a way of getting the best of both worlds.

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Oops, this broke a test.

**Comment by creator1creeper1** [comment]
Do we really want to have error handling callbacks?

**Comment by AtkinsSJ** [comment]
> Do we really want to have error handling callbacks?

I don't know! That's why this is experimental. :^) I couldn't think of any other methods for propagating the error at the time. Now I'm thinking maybe some kind of CallbackWithError class would be nice, that wraps the two functions so it's a single object instead of two separate things. Still a bit clumsy though.

Also, the test works on my end so it seems like flakiness? Though I've re-run CI a couple of times and that one test is consistently failing, always on Azure.

**Comment by AtkinsSJ** [comment]
So... the test failing is definitely flakey, but this PR seems to make it worse.

Every time, it fails at least once, on either the "Azure Pipelines / CI (SerenityOS Serenity_Clang_i686)" or "Azure Pipelines / CI (SerenityOS Serenity_Clang_x86_64)" runs, but sometimes both. All other runs are always fine, and it varies which part of the "LibCore/TestLibCoreStream" crashes.

**Comment by creator1creeper1** [comment]
The `ErrorOr` wrappers and LibMain ports are obviously all good changes. I like the idea of an `CallbackWithError` class, but we should watch out that we don't create gigantic objects (a `Function` already has `4 * sizeof(void *)` inline storage) just to do a little bit of control flow.

**Comment by AtkinsSJ** [comment]
Agni was saying he had a prototype that instead put errors into the event loop and handled then that way. I think that sounds pretty elegant, so I'll put that commit to one side for a while.

**Comment by creator1creeper1** [comment]
As I said in the discord - I think an error handling callback allows the user to control Errors much more precisely. But let's see how the prototype turns out.

**Pull request merged**
