### PR TITLE
LibC: Expose PAGE_ROUND_UP in mallocdefs.h

### PR DESCRIPTION
**Pull request by ccapitalK**

### CODE REVIEW

**Comment by IdanHo** [comment]
What's the point of this change? 🤔

**Comment by ccapitalK** [comment]
A bunch of people want to have page_round_up in userspace for various reasons. I want it so we can do stuff for the JIT PR more easily, but @Quaker762  and @alimpfard also want it for their own reasons.

**Comment by alimpfard** [comment]
I just wanted it to pass a nice value to `mmap` in `BasicBlock()` :P

**Comment by Quaker762** [comment]
Quake-II requires a call similar to this related to Hunk file memory mapping.

**Comment by IdanHo** [comment]
:+1: just wanted to make sure it fits the "dont add an api if youre not using it anywhere" paradigm

**Pull request merged**
