### PR TITLE
Add is_not_empty to string types

### PR DESCRIPTION
**Pull request by erf**
This PR adds the convenient method `is_not_empty` to the following String classes:
- String
- FlyString
- StringBuilder
- StringView

I feel this is a more expressive way to denote that a string "is not empty" compared to using the "not" (!) operator, which sometimes  can be hard to notice in between the parentheses.

So instead of writing: `if(!someString.is_empty())`, you could write: `if(someString.is_not_empty())`.

This is a similar to Dart lang's String method [isNotEmpty](https://api.dart.dev/stable/2.16.1/dart-core/String/isNotEmpty.html). 

Dart also have this method in it's [List](https://api.dart.dev/stable/1.10.1/dart-core/List/isNotEmpty.html) and other collection classes, which perhaps could be inspiration for serenity's collections.

I mentioned this on Discord and believe there are various opinions on this API change, but I'll leave that up to the maintainers.

### CODE REVIEW

**Comment by MacDue** [comment]
You're probably going to need to find a few spots to use these methods, I don't unused code is normally accepted.

**Comment by creator1creeper1** [comment]
IMO, this doesn't add expressiveness at all and in fact makes the code longer to write. It also leaves two public APIs that do essentially the same thing. There's already a built-in way of saying "the negation of the condition", and that's '`!`'.

**Comment by erf** [comment]
> IMO, this doesn't add expressiveness at all and in fact makes the code longer to write. It also leaves two public APIs that do essentially the same thing. There's already a built-in way of saying "the negation of the condition", and that's '`!`'.

I hear you, but I feel like with this API you don't have to look back and forth to determine what is going on, but everything can be expressed in the method call - it's a bit easier to read.

**Comment by linusg** [comment]
We've decided this change is not adding enough value to merge it - as is, it only scratches the surface. When introducing this pattern, we'd have to do it consistently across the codebase, adding negated variants of *every* `is_foo()` functions, which is overkill. `!` is fine, actually :^)

**Pull request closed without merging**
