### PR TITLE
LibJS: Implement automatic semicolon insertion

### PR DESCRIPTION
**Pull request by sunverwerth**
This implements one of the weirder parts of the Javascript spec.

### CODE REVIEW

**Comment by awesomekling** [comment]
This might be even nicer if `StringView` had a `bool contains(char) const`, no? :)

**Comment by sunverwerth** [comment]
True. Let me go ahead and add it

**Comment by sunverwerth** [comment]
@awesomekling Done. JS tests are all green

**Comment by awesomekling** [comment]
Cool! Now we just need to remember to consume or insert semicolon when parsing statements I guess :)

**Comment by sunverwerth** [comment]
Ah crap! I spotted a mistake.
I'll open another PR 🙃

**Comment by awesomekling** [comment]
Sounds like an opportunity to add a test too ;)

**Pull request merged**
