### PR TITLE
LibC: Add timeval operations

### PR DESCRIPTION
**Pull request by mauri870**
This commit add macros for the timeval operations timeradd, timersub,
timercmp, timerisset, timerclear.

### CODE REVIEW

**Comment by xTibor** [comment]
I don't think it's a good idea to lift GPL'd code from glibc into the codebase. I'd rather reimplement it under BSD.

**Comment by awesomekling** [comment]
> I don't think it's a good idea to lift GPL'd code from glibc into the codebase. I'd rather reimplement it under BSD.

I definitely agree with you that we should not be yanking code from GPL sources.
However, in this particular case, I believe the functions originally came from NetBSD:

http://cvsweb.netbsd.org/bsdweb.cgi/src/sys/sys/time.h?rev=1.10&content-type=text/x-cvsweb-markup

Also @mauri870, please add a prefix to your commit messages, per CONTRIBUTING.md:

**Comment by xTibor** [comment]
It's glibc, not NetBSD. Note the variable names and the use of pre-increment/decrement operator.

https://sourceware.org/git/?p=glibc.git;a=blob;f=time/sys/time.h;h=0473dae339439d790ba10230efac3e0070cdff5c;hb=HEAD#l166

**Comment by mauri870** [comment]
Thank you for the feedback. I've changed the sources, this is not a POSIX thing so I got the macros from BSD. Do I need to implement this in a different way?

**Comment by awesomekling** [comment]
I think it's okay this way.

**Pull request merged**
