### PR TITLE
Meta: Remove .gitignore from Base/

### PR DESCRIPTION
**Pull request by ronak69**
Base/.gitignore leaks into serenity's file-system. It can be safely removed by adding equivalent un-ignore pattern in top-level .gitignore.

It may look "un-polished" or be "annoying" to some. But for others it may be something quirky and good that shows the origin of the file-system. Simulation vibes.

Is the comment ok or should i remove it?

### CODE REVIEW

**Comment by timschumi** [comment]
There are more `.gitignore` files in there.

**Comment by ronak69** [comment]
I found `Base/usr/include/.gitignore` and `Base/usr/lib/.gitignore`. Seems redundant because there are `.gitkeep` files in those directories as well.

**Comment by ronak69** [comment]
... But both of them ignore every file. I don't know if it is a "feature" and local clones of the repository have collected untracked files in them.

**Comment by ronak69** [comment]
Either way, one of `.gitkeep` or `.gitignore` will have to stay because the directories are empty (git doesn't track empty directories).

`.gitkeep` is unnecessary if `.gitignore` is there. If `.gitignore` patterns are moved to the top-level then `.gitkeep` will be required.

**Comment by ronak69** [comment]
BTW FYI there are six tracked-but-ignored files.

```console
$ git ls-files | git check-ignore --stdin --no-index | git check-ignore --stdin --no-index -v
Ladybird/.gitignore:11:android/assets/  Ladybird/android/assets/.gitkeep
Ladybird/.gitignore:3:ladybird  Ladybird/android/src/org/serenityos/ladybird/TransferAssets.java
Ports/.gitignore:1:*/*  Ports/SuperTuxKart/ReadMe.md
Ports/.gitignore:1:*/*  Ports/qemu/version.sh
Ports/.gitignore:1:*/*  Ports/zig/scripts/constants.txt
Ports/.gitignore:1:*/*  Ports/zig/scripts/generate-serenity-constants.zig
```

**Comment by timschumi** [comment]
> There are more `.gitignore` files in there.

Let's see what CI says about #20268. If that passes, this might be a moot point anyways.

As for the comment in the (now top-level) `.gitignore`, how about "Ensure that all files in /Base can be tracked, even if they match one of the above rules."?

**Comment by ronak69** [comment]
Changed the comment.

**Review by timschumi — APPROVED** [review]

**Pull request merged**
