### PR TITLE
LibC: fix definition of wint_t

### PR DESCRIPTION
**Pull request by Redfoxymoon**
__WINT_TYPE__ is not defined, change wint_t to be an unsigned int, related to #856

### CODE REVIEW

**Comment by awesomekling** [comment]
What do you mean that `__WINT_TYPE__` is not defined? Then how would it compile?

**Comment by MWGuy** [comment]
@awesomekling when i start compile ``m4``, gcc tells this:
```
printf-args.h:101:5: error: unknown type name 'wint_t'
     wint_t   a_wide_char;
     ^~~~~~
In file included from printf-args.c:21:
printf-args.h:101:5: error: unknown type name 'wint_t'
     wint_t   a_wide_char;
     ^~~~~~
```

**Comment by Redfoxymoon** [comment]
True. It must be coming from GCC's headers. I suspect autotools might not find the builtin definitions, but anyway: we shouldn't be relying on GCC for type definitions like these...

**Comment by awesomekling** [comment]
> we shouldn't be relying on GCC for type definitions like these

Why not? What happens if we fall out of sync with the compiler's idea of `wint_t`?

**Comment by awesomekling** [comment]
Let's agree with the compiler on what `wint_t` is. If we need to do this differently to support other compilers, we can use `#ifdef`

**Pull request closed without merging**
