### PR TITLE
Base: Add Houses, Safety pin emoji

### PR DESCRIPTION
**Pull request by premek**

### CODE REVIEW

**Review by tarob0ba — CHANGES_REQUESTED** [review]
Please run `optipng -strip all <path>` on this.

**Comment by premek** [comment]
I thought I did but I forgot the `-strip all`
Thanks @tarob0ba , should be fixed now

**Review by tarob0ba — APPROVED** [review]
These look lovely! :^)

**Review by Xexxa — CHANGES_REQUESTED** [review]
Could you please update your commit message, change from:

```
Base: Add Houses, Safety pin emoji
```
to:
```
Base: Add Houses, Safety pin emoji

🧷 - U+1F9F7 Safety Pin
🏘 - U+1F3D8 House Buildings
```

**Comment by Xexxa** [comment]
I forgot to say: These emoji looks great! Two steps closer to full coverage! :dancer:

**Comment by premek** [comment]
sure, done, thank you :)

**Review by Xexxa — APPROVED** [review]
LGTM!

**Pull request merged**
