### PR TITLE
LibWeb: Maintain precision when using background-size: {cover, contain}

### PR DESCRIPTION
**Pull request by jamierocks**
Fixes GH-24225.

| Before | After |
| --- | --- |
| image | image |

### Test case (slightly modified from GH-24225)

```html
<style>
    body {
        margin: 0;
        padding: 0;

        height: 150vh;
    }

    #test {
        width: 100%;
        height: 100vh;

        background: url(https://placehold.co/2200x1311/gray/white/png?text=WHF!&font=Montserrat);
        background-size: cover !important;
        background-position: center !important;
    }
</style>
<body>
    <div id="test">
    </div>
</body>

```

### CODE REVIEW

**Comment by trflynn89** [comment]
The test case should be added to the LibWeb test suite. A ref test is probably appropriate for this one.

**Comment by jamierocks** [comment]
I see that the build has failed twice owing to tests.

```
Fail: /home/vsts/work/1/s/Tests/LibWeb/Ref/border-radius.html
Fail: /home/vsts/work/1/s/Tests/LibWeb/Ref/css-background-size.png
Fail: /home/vsts/work/1/s/Tests/LibWeb/Ref/css-background-size.html
Fail: /home/vsts/work/1/s/Tests/LibWeb/Ref/css-backgrounds.html
```

Seems to be the culprit - have I done something wrong with adding the tests?

**Comment by AtkinsSJ** [comment]
If you click through to the CI results on Azure, you'll get to [here](https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=47272&view=results). There's a "2 published" link there, which will let you download screenshots of ref test results so you can see what's wrong.

A couple of those are just slight pixel variations that make sense because you've modified how backgrounds are painted. But otherwise, you do have a couple of issues:
- You need a meta tag in the ref test HTML that says where the reference page is. You'll see that in other test files.
- The png file `css-background-size.png` should be in `Tests/LibWeb/Ref/assets` so that we don't think it's a test file. (Maybe we should be smarter about not treating images as test inputs. :sweat_smile:)

**Comment by jamierocks** [comment]
That's really helpful - thank you :)

Looking at the other tests - it actually seems that `css-backgrounds.html` already tests this (amongst other things), so it probably makes sense to remove the test I added.

**Comment by jamierocks** [comment]
Thank you again for your help. I removed the test I added, happy with the existing `css-backgrounds` test that covers both `cover` and `contain`.

I was also happy that the slight differences were intentional. :)

**Pull request merged**
