### PR TITLE
Pre-kernel Environment - Part 1

### PR DESCRIPTION
**Pull request by supercomputer7**
This is meant to be the pre-kernel environment that AK & I have talked about in the IRC channel.
The idea is to supply a boot environment to link the kernel object files, then to load the kernel in a randomized address to enable KASLR. The plan is to add an ELF linker in it, and a small subsystem to read the ramdisk.

The ramdisk layout is currently very simple - nothing more than essentially a virtual disk, GPT partitioned with two partitions - one for configuration (will include in it a data that the pre-kernel environment can understand and parse) and another for data (presumably will hold a FAT32 filesystem, but of course we can choose a different filesystem). The data partition will hold the kernel image (for those who don't want to link everything during boot) and the kernel ELF object files.

Another nice idea that we discussed in the IRC channel is how to simplify the kernel bootstrapping design, and I came to a conclusion that we should do all the initial paging configuration in the pre-kernel environment, thus we allow the kernel to be more portable.

Also, we can have nice features like a special rescue environment.

### CODE REVIEW

**Comment by supercomputer7** [comment]
@awesomekling @bugaevc @deoxxa If you have suggestions or you see something incorrect, please let me know about it :)

**Comment by awesomekling** [comment]
Please find a way to avoid duplicating so much stuff.

And also, let me just reiterate that the important part here is building a boot-time JIT linker, this project does not need a custom bootloader :)

**Comment by supercomputer7** [comment]
> Please find a way to avoid duplicating so much stuff.
> 
> And also, let me just reiterate that the important part here is building a boot-time JIT linker, this project does not need a custom bootloader :)

I'll try to do so, but be aware that we will remove some code from the kernel.

Again, I'm not trying to build a custom bootloader - this is not a bootloader (it won't be able to boot other OSes, for example) - this a pre-kernel environment, meant to link the kernel during boot. The handover protocol is just a way to pass vital information like the paging configuration and such...

Currently I still need to work on the builtin ELF linker, I didn't say it's a finished product :)

**Comment by supercomputer7** [comment]
@awesomekling I'd like to merge this branch now, as a preparation for the next part, so,
if you can provide a review on the changes, it'll be awesome :)

**Comment by bugaevc** [comment]
Please, "Applying changes" -> "Apply changes"

**Comment by awesomekling** [comment]
Okay, I think this will be pretty good :)

**Pull request merged**
