### PR TITLE
Kernel+DynamicLoader: Various fixes around mmap & mprotect syscalls

### PR DESCRIPTION
**Pull request by supercomputer7**
This PR should fix a couple of issues I've seen in current implementation:
- We never completely block transition from writable regions to being executable ones, because the `DynamicLoader` has to do some text relocation and to properly support this, we do various checks (which are "fine"), but we might as well want to completely avoid such complication in the first place.
- The `Region` `has_been_{r,w,x}` flags are not clearly understandable because **nothing sets them clearly**. A simple search doesn't show those bits being set, and only by looking deeper into the `Region` `set_access_bit` method we could see that there's ORing with `(access << 4)` when enabling an access bit.
- The logic of enabling syscall region enforcing is overly complicated, instead of being set-once flag.

The following 3 commits are trying to solve all of the mentioned problems. Hopefully I didn't mess anything up, but I'd like to get reviews on these changes and be pointed on problems if so are appeared in this PR.

### CODE REVIEW

**Comment by DanShaders** [comment]
Really like this change from userspace perspective. I think I spend around 20 minutes the day before yesterday figuring out how and when various protections get enabled.

**Comment by supercomputer7** [comment]
The second commit will probably disable `dlopen` from working in a program that needs to dynamically load a module or a shared library.
While it might not be a big problem currently (because nothing in our ecosystem actually do that), it might be a problem for ports - however, we could put the `WXALLOWED` mount flag (as a bind mount, or just have a separate filesystem mounted specifically for ported software binaries) for ports that need it however, so no actual big issue, besides that we will need to investigate on why the port crashed and find this as the reason.

**Comment by DanShaders** [comment]
> The second commit will probably disable dlopen from working in a program that needs to dynamically load a module or a shared library.

No, if it had done that, the CI would have failed. It does, however, prevent loading modules with text relocations (since only them require remapping from W to X memory) but DynamicLoader doesn't really like text relocations even in initially loaded objects.

**Comment by ADKaster** [comment]
This has a conflict with DanShaders' Kernel/Memory/Region changes that I merged today

**Comment by supercomputer7** [comment]
> > The second commit will probably disable dlopen from working in a program that needs to dynamically load a module or a shared library.
> 
> No, if it had done that, the CI would have failed. It does, however, prevent loading modules with text relocations (since only them require remapping from W to X memory) but DynamicLoader doesn't really like text relocations even in initially loaded objects.

Right, it will prevent loading modules that need text relocations to work. Not that we do any of that in our codebase, so it should be OK.

**Review by ADKaster — APPROVED** [review]

**Pull request merged**
