### PR TITLE
Base: Replace office.png icon with BSD licensed one

### PR DESCRIPTION
**Pull request by MrRar**
Related to https://github.com/SerenityOS/serenity/issues/17468

This PR replaces an icon copied from Windows with an icon I created myself. I am licensing this icon under CC0.

I don't know if this icon is good enough but I thought I would give it a try.

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
> I am licensing this icon under CC0.

All resources & code not imported from elsewhere should be 2-clause BSD: https://github.com/SerenityOS/serenity/blob/master/LICENSE

**Comment by MacDue** [comment]
CC0 is "No rights reserved" wouldn't that allow re-licencing/including a 2-clause BSD project?

**Comment by linusg** [comment]
yes and no, it would also mean that we have to (1) keep a note somewhere that this one icon is special and (2) people can take it without crediting the project. Not worth the hassle :)

**Comment by MrRar** [comment]
> (1) keep a note somewhere that this one icon is special and

Under CC0 you are free to relicense this icon under any license you choose and you don't have to credit me the author.

(2) people can take it without crediting the project.

If your concerned about people taking parts of Serenity without crediting Serenity, you need to consider that any contributer can take and reuse and relicense their contributions without crediting Serenity.

I'm not sure I am able to do so, but in as far as I am able, I revoke the CC0 license and license the icon under your 2-clause BSD license.

**Comment by linusg** [comment]
ok, please remove the mention of CC0 from the commit message then.

**Comment by MrRar** [comment]
> ok, please remove the mention of CC0 from the commit message then.

Done.

**Pull request merged**
