### PR TITLE
LibGfx: Avoid emoji slow path for keypad characters that are not emojis

### PR DESCRIPTION
**Pull request by MacDue**
This adds an extra check that if we see a keypad character (digits 0-9, \#, or *), we check that there's a keycap modifier or a variation selector next. If there's not we know this is not an emoji and just an ASCII character.

Adding this check brings glyph_or_emoji_width() back down to 1% of the profile when scrolling on gradients.html (rather than 33%).

### CODE REVIEW

**Comment by nico** [comment]
The perf is cool, but doesn't it seem a bit iffy to hardcode these constants in LibGfx? It seems nicer if this knowledge was somewhere in `Unicode::` maybe?

**Comment by MacDue** [comment]
Any suggestions on what that function would be in `Unicode::` (or if it already exists?) :sweat_smile:  
I did have a look, and I didn't see a function that matched for the "combining enclosing keycap", but my knowledge of LibUnicode is a bit limited :P

**Comment by trflynn89** [comment]
Sorry didn't realize this PR was open, I added more formal verification based on the spec to #17579

**Comment by MacDue** [comment]
Closed in favor of https://github.com/SerenityOS/serenity/pull/17579

**Pull request closed without merging**
