### PR TITLE
LibDebug/HackStudio: Support debugging variables with enum types

### PR DESCRIPTION
**Pull request by FalseHonesty**
Variables with enum types can now be both viewed and modified in the variables view!

This patch also adds all the missing Attribute, Tag, and Form enum values as of v5 of the DWARF spec.

cc @itamar8910

### CODE REVIEW

**Comment by itamar8910** [comment]
Awesome. I'll get around to reviewing this tomorrow :smiley:

**Comment by itamar8910** [comment]
The DWARF guys thought of everything huh? :laughing: 

Looks good to me - @awesomekling?
Also, feel free to add yourself to the copyright headers in relevant files.

**Comment by FalseHonesty** [comment]
> The DWARF guys thought of everything huh? laughing

I know, I was really blown away by the sheer number of attributes and such.

> Also, feel free to add yourself to the copyright headers in relevant files.

It doesn't really matter to me, I'm fine leaving them as they are. Thanks for the review!

**Comment by awesomekling** [comment]
:star:

**Pull request merged**
