### PR TITLE
LibWeb: Allow calculated values for `background-size` dimensions

### PR DESCRIPTION
**Pull request by Zaggy1024**
This fixes the sizing of the arrow icons displayed to the left of parent sections on a table of contents on Wikipedia articles, which are sized using the equation `calc(max(0.75em, 12px))`. Now, the icon will not expand past the edges of the box they are within, avoiding clipping the edges of the arrows.

Before:
image

After:
image

### CODE REVIEW

**Comment by Zaggy1024** [comment]
Oddly, I can't get this to pass a reftest by making a `-ref.html` with a fixed `background-size: 12px`, despite the fact that the sizes and color values seem to perfectly match when I render out an image with headless browser.

**Comment by AtkinsSJ** [comment]
What's the html for the test? When I've had that problem before it's from things being painted multiple times on top of each other, meaning partially transparent pixels end up darker than they should. It only became visible when I really whopped up the contrast.

Code looks good though! I'm happy for this not to have a test, up to you.

**Comment by Zaggy1024** [comment]
```html
<!DOCTYPE html>
<html>
<head>
    <style>
        span {
            display: inline-block;
            min-width: 12px;
            min-height: 12px;
            background-image: url("data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjIwIiBoZWlnaHQ9IjIwIiB2aWV3Qm94PSIwIDAgMjAgMjAiPjx0aXRsZT5leHBhbmQ8L3RpdGxlPjxnIGZpbGw9IiMwMDAiPjxwYXRoIGQ9Im0xNy41IDQuNzUtNy41IDcuNS03LjUtNy41TDEgNi4yNWw5IDkgOS05eiIvPjwvZz48L3N2Zz4=");
            background-size: calc(max(0.75em, 12px));
            background-repeat: no-repeat;
            background-position: center;
        }
    </style>
</head>
<body><span></span>
```

This is the reproduction case. As far as things being painted on top of each other, it didn't seem to do so when I ran headless-browser, the color values were perfectly matched. I don't know much about the reftest runner, though, so I can't say whether it's doing something odd there, I suppose.

**Comment by trflynn89** [comment]
Make sure you run headless-browser with some extra layout test flags:
```bash
./Build/lagom/bin/headless-browser --resources $SERENITY_SOURCE_DIR/Base/res --layout-test-mode --dump-layout-tree test.html
```

**Comment by awesomekling** [comment]
I would suggest removing the SVG (and *anything* else not actually required) from the test. :)

**Comment by Zaggy1024** [comment]
> Make sure you run headless-browser with some extra layout test flags:
> 
> ```shell
> ./Build/lagom/bin/headless-browser --resources $SERENITY_SOURCE_DIR/Base/res --layout-test-mode --dump-layout-tree test.html
> ```

That seems to be the command for layout tests, not ref tests, it doesn't output an image if I use that.

> I would suggest removing the SVG (and _anything_ else not actually required) from the test. :)

The test case requires a background image of some kind, since background colors ignore the `background-size` and `background-repeat` CSS properties. A simple 2x2 PNG also fails the ref test, despite also resulting in pixel-identical renders from headless-browser:

```html
<!DOCTYPE html>
<html>
<head>
    <style>
        span {
            display: inline-block;
            min-width: 12px;
            min-height: 12px;
            background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAAWSURBVBhXY2RgYPgPxAxMIIKBgYEBAA4oAQODdgF7AAAAAElFTkSuQmCC");
            background-size: calc(max(0.75em, 12px));
        }
    </style>
</head>
<body><span>
```

**Comment by Zaggy1024** [comment]
Looks like the issue is that ref tests instantly capture the screenshot after `on_load_finish` is called, so it doesn't get a chance to repaint after the background image has loaded.

**Comment by awesomekling** [comment]
> Looks like the issue is that ref tests instantly capture the screenshot after `on_load_finish` is called, so it doesn't get a chance to repaint after the background image has loaded. Not sure if there's a way to guarantee that all images have loaded before taking a screenshot, but I think that would be preferable to setting a timer and making every test run slow.

Oh, interesting! CSS background images indeed don't block the `load` event, but they *should* share the loading mechanism with an `` for the same URL. Perhaps we can use that in order to ensure that the image is loaded before triggering the paint? (i.e by adding a dummy image with the same URL :)

**Comment by Zaggy1024** [comment]
> > Looks like the issue is that ref tests instantly capture the screenshot after `on_load_finish` is called, so it doesn't get a chance to repaint after the background image has loaded. Not sure if there's a way to guarantee that all images have loaded before taking a screenshot, but I think that would be preferable to setting a timer and making every test run slow.
> 
> Oh, interesting! CSS background images indeed don't block the `load` event, but they _should_ share the loading mechanism with an `` for the same URL. Perhaps we can use that in order to ensure that the image is loaded before triggering the paint? (i.e by adding a dummy image with the same URL :)

Forgot to reply and say that worked, but thanks for the suggestion!

**Pull request merged**
