### PR TITLE
MacPDF: Toggle outline view expansion on double click

### PR DESCRIPTION
**Pull request by trflynn89**
CC @nico

### CODE REVIEW

**Comment by nico** [comment]
Fine with me if you want to do this, but it's fairly non-standard. Most other outline views don't have this behavior.

Don't have it:
* Preview.app, which seems to have a somewhat customized outline view
* The source navigator (cmd-2) in Xcode
* The find navigator (cmd-4) in Xcode
* The issue navigator (cmd-5) in Xcode
* The breakpoint navigator (cmd-8) in Xcode
* The reports navigator (cmd-9) in Xcode
* Notes.app (if you create nested folders in the sidebar)
* Activity Monitor.app, with View->All Processes, Hierarchically
* Disk Utility.app

Has it:
* The project navigator (cmd-1) in Xcode
* …that's all I could find

**Comment by trflynn89** [comment]
Huh, I'm surprised it is so non-standard, feels like a strict usability benefit to me. Or maybe it's just me that always double clicks instead of having to be accurate with clicking the `>` :man_shrugging:

**Comment by Hendiadyoin1** [comment]
Acrobat (on Windows) seems to allow double clicks to expand chapters (most of the time)
While Firefox does not seem to do the same in their builtin viewer

**Comment by nico** [comment]
Behavior of Windows applications isn't relevant for macOS apps :)

Double-click is supposed to enter the selection, which I suppose for a PDF viewer means opening that page (which single click already does), I think.

**Pull request closed without merging**
