### PR TITLE
LibTextCodec: Add alternate Cyrillic (aka Koi8-r) encoding

### PR DESCRIPTION
**Pull request by can3p**
Koi8-r is one of the older character encodings widely used in russian part of the internet

Wiki: https://en.wikipedia.org/wiki/KOI8-R

Example website using the encoding: https://koi8.pp.ru/

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Looks like this should fix #6840. If you add `Fixes #6840` to the pull request description or commit message, it'll get closed automatically when this is merged. :^)

**Comment by BertalanD** [comment]
The clang-format linter doesn't like how you arranged the code points in a table, and wants to reformat it to one element per line. I think your version is neater. Could you surround the array with `// clang-format off` and `// clang-format on` to stop this from happening?

**Comment by can3p** [comment]
@AtkinsSJ @BertalanD thanks for the feedback! Will do both.

Regarding the lint problem - I've simply copied a similar function that's used for another encoding, wasn't able to figure out from the get go why there was a problem in my function but not in the original. I'll take a look later today and make sure lint check passes

**Comment by BertalanD** [comment]
The reason why it only fails for your code is that only newly added lines are linted, and the other conversion tables were added before the mandatory CI clang-format linting.

**Comment by can3p** [comment]
All done! thanks for the explanation

**Comment by AtkinsSJ** [comment]
Looks like the commit message got awkwardly split. We limit the message line length to 72 characters, so you'll want to change it to something like this:

```
LibTextCodec: Add alternate Cyrillic (aka Koi8-r) encoding

Fixes #6840.
```

Code looks fine to me though.

(I promise you get used to things like this. :^) )

**Pull request merged**
