### PR TITLE
CI: Add statement to ensure workflow runs only on serenity

### PR DESCRIPTION
**Pull request by r0x0d**
Ensure that the `cmake.yml` workflow runs only on SerenityOS repository.

### CODE REVIEW

**Comment by davidot** [comment]
Can you explain the reasoning behind this?
Right now you have made the check so strict that it won't even run in a PR. (Check this one for example).

And it can be useful to run CI on your own fork when trying things out or just to test.
I you don't want to run it on your own fork you can disable actions entirely in 
Settings > Actions > General > Disable Actions

**Comment by r0x0d** [comment]
Hi, @davidot! Sorry for not providing a more meaningful rationale in the commit message. 

The reason I'm opening this is a follow-up of a previous PR exactly like that I did some time ago, #9923. I noticed every other workflow on Serenity has this `if` statement to prevent it from running on forks, only this one was left behind... 

As of the reason on why the workflow didn't started on the PR is a mysterious to me... Maybe it's because of the `refs` checking against the `master` branch? I was just following the same standard as other workflows here. 

Anyway, feel free to close this PR if you think it's not entirely necessary or this workflow is intended to run on forks and upstream.

**Comment by trflynn89** [comment]
The other workflows are specifically meant to only run on `master` instead of on PRs. For example, manpages.yml updates a remotely hosted set of docs, and sonar-cloud-static-analysis.yml runs once per day for some static analysis of the master branch. So it makes sense to not run those on PRs.

> Maybe it's because of the refs checking against the master branch?

Yep that's the reason - see lintcommits.yml as an example for a workflow that doesn't run on forks, but does run on PRs.

**Comment by r0x0d** [comment]
Oh, I see now, @trflynn89! Thanks for the explanation. 

Seeing from this point of view it makes total sense to not add this statement to prevent running on forks.

**Comment by trflynn89** [comment]
Oh to be clear, I think disabling cmake.yml on forks is fine - you'll just need to get rid of the `master` branch ref like lintcommits.yml  does.

**Review by trflynn89 — APPROVED** [review]

**Pull request merged**
