### PR TITLE
LibGL: Generate GL_OUT_OF_MEMORY error in `glBufferData` when OOM

### PR DESCRIPTION
**Pull request by mkanilsson**

### CODE REVIEW

**Comment by LucasChollet** [comment]
Welcome to the project!

The FIXME sugests that other errors are possible. Even if none others are returned by the `set_data` method, it might be nice if you take care of the `GL_INVALID_VALUE` case.

Otherwise, it looks good!

**Comment by mkanilsson** [comment]
Thank you!
 
Currently, I follow spec for version 1.5 since that's the version I could find in the source code. 

The specs for version 1.5 makes no mention of `GL_INVALID_VALUE` when talking about `glBufferData` but I do find it for version 2 and up. 

And I interpreted
> If the GL is unable to create a data store of the requested size, the error
OUT OF MEMORY is generated.

As "all errors that can arise when trying to create a data store should be a `GL_OUT_OF_MEMORY` error" 

1.5 Spec: https://khronos.org/registry/OpenGL/specs/gl/glspec15.pdf (page 45 for glBufferData)

Should I use specs for another version than 1.5? 

I'd be happy to improve my code!

**Comment by LucasChollet** [comment]
My bad, might have led you astray. I don't know if we implement 2003's 1.5 specification or the subset of OpenGL 4 corresponding to 1.5 🤷

**Comment by mkanilsson** [comment]
Okay, then I'll wait until I can get in touch with someone who knows. Thanks a lot!

**Review by GMTA — APPROVED** [review]
LGTM!

**Pull request merged**
