### PR TITLE
LibCrypto : UnsignedBigInteger computation improvements

### PR DESCRIPTION
**Pull request by Dexesttp**
## Objective

This Pull Request aims to :
- Improve algorithms used by BigIntegers to reduce the execution time
- Reduce the number of allocations during RSA / BigInteger computations
- Reduce the memory footprint of the RSA / BigInteger computations

This is the first step to improve the operations, other improvements to the algorithms are still ongoing and will be made available in future Pull Requests.

## Overview of changes

This PR contains the following changes

- An extended API for UnsignedBigInteger which includes :
    - Static non-allocating add/subtract/multiply/divide/shift operations
    - Special cases for operations between a BigInt and a small number (currently implemented : `divide_by_u16`)
- Modifications to `ModularFunction.h` to use the API and improve performances.
- Modifications to the `test-crypto.cpp` application to include time of execution for each test (in seconds + microseconds)
- A bookkeeping commit (added a missing `move()`, fixed a typo in the tests names, and moved some methods around in UnsignedBigInteger to match the .h file)

## Updated UnsignedBigInteger API

Here is the proposed API :

```C++
class UnsignedBigInteger {
    static void add_without_allocation(const UnsignedBigInteger& left, const UnsignedBigInteger& right, UnsignedBigInteger& output);
    static void subtract_without_allocation(const UnsignedBigInteger& left, const UnsignedBigInteger& right, UnsignedBigInteger& output);
    static void shift_left_without_allocation(const UnsignedBigInteger& number, size_t bits_to_shift_by, UnsignedBigInteger& temp_result, UnsignedBigInteger& temp_plus, UnsignedBigInteger& output);
    static void multiply_without_allocation(const UnsignedBigInteger& left, const UnsignedBigInteger& right, UnsignedBigInteger& temp_shift_result, UnsignedBigInteger& temp_shift_plus, UnsignedBigInteger& temp_shift, UnsignedBigInteger& temp_plus, UnsignedBigInteger& output);
    static void divide_without_allocation(const UnsignedBigInteger& numerator, const UnsignedBigInteger& denominator, UnsignedBigInteger& temp_shift_result, UnsignedBigInteger& temp_shift_plus, UnsignedBigInteger& temp_shift, UnsignedBigInteger& temp_minus, UnsignedBigInteger& quotient, UnsignedBigInteger& remainder);
    static void divide_u16_without_allocation(const UnsignedBigInteger& numerator, u32 denominator, UnsignedBigInteger& quotient, UnsignedBigInteger& remainder);
}
```

The method signatures are very unwieldy, but contain everything required to prevent allocations. Names can be reworked/changed if needed !

## Fuuture improvements

In addition to this PR, other improvements could bbe made in future Pull Requests such as :
- Changing the UnsignedBigInteger multiplication algorithm to use Karatsuba or Toon3 multiplication (depending of performance gains for each algorithm)
- Changing the ModularPower algorithm to use montgomery multiplication for odd powers (instead of multiplication and modulo as it is currently done).

## Performance Improvements

The impact can be seen mostly during the `pk` test suite (ran with `test-crypto -t pk`). Below are the improvements for a single run of the test suite. Note that the results depend of your configuration and are impacted by other things happening on the computer, so YMMV.

| Test Name | Original code | Pull Request results | Change |
|------------|---------------|---------------------|-----------|
| `RSA RAW \| Encryption` | 0s 882ms | 0s 325ms | -63% |
| `RSA PKCS #1 1.5 \| Encryption` | 280s 112ms | 207s 626ms | -25% |
| `RSA \| ASN1 DER / PEM encoded Key import` | 0s 041ms | 0s 030ms | -26% |
| `Number Theory \| Modular Inverse` | 0s 001ms | 0s 001ms | = |
| `Number Theory \| Modular Power` | 0s 078ms | 0s 035ms | -55% |
| `RSA Encrypt` | 287s 331ms | 231s 590ms | -19% |
| `RSA EMSA_PSS \| Construction` | 0s 212ms | 0s 022ms | -89% |

In addition, the new methods reduce greatly the number of allocations. Here are the top 4 methods with self-hits (inverted tree) during a 5-second `profile` run while the `RSA PKCS #1 1.5 Encryption` test is running :

| Method | Original code | Pull Request results |
|---------|---------------|----------------------|
| `malloc` | 1412 | 31 |
| `free` | 1384 | 39 |
| `divided_by` | 1162 | 3762 |
| `multiplied_by` | 1093 | 3158 |

### CODE REVIEW

**Comment by Dexesttp** [comment]
I made a typo in the test execution time code, so the table had some completely wrong values. It was updated accordingly.

**Comment by awesomekling** [comment]
Can we do this kind of work incrementally in-tree instead?
We'll get a lot more testing if we do, and it also makes reviewing easier :)

**Comment by Dexesttp** [comment]
Sure ! I mostly wanted to wait until the optimizations actually improved the PK tests below the minute mark to make it usable-ish for TLS, but incremental improvements are good too.
I'll continue working on the improvements and submit another PR when it's done !

**Comment by awesomekling** [comment]
Great! This is nice progress btw :)

**Pull request merged**
