### PR TITLE
HexEditor: Use Yes/No/Cancel prompts for message boxes

### LINKED ISSUE #7169: HexEditor: Use Yes/No/Cancel prompts for message boxes
HexEditor shows a message box when closing the window and when trying to create a new file when changes have been made to the existing file. These should use `Yes`, `No` and `Cancel` for the buttons:

Screenshot from 2021-05-16 11-02-11

Screenshot from 2021-05-16 11-02-24

### PR DESCRIPTION
**Pull request by apoorv-mishra**
Use Yes/No/Cancel prompts in message box for saving changes on closing a file with unsaved changes.

Fixes #7169

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
This closes HexEditor when I do this:

1. Modify the current file.
2. Try to close HexEditor.
3. Confirm that I want to save changes.
4. Click cancel in the file picker window.
5. Notice that HexEditor was closed and my changes were lost.

**Comment by apoorv-mishra** [comment]
Sorry, I didn't understand the your steps.

> Try to close HexEditor.

How? Via `File -> Quit` or the `x` icon or `Alt+F4`?

>Confirm that I want to save changes.

Clicked on "Yes" in "Save changes" message box?

>Click cancel in the file picker window.

I don't understand this. What's a file picker window? Where do you see it after you've clicked "Yes" in step 3(assuming you've done so).

**Comment by gunnarbeutner** [comment]
https://user-images.githubusercontent.com/388571/122103208-a6532000-ce16-11eb-9637-925217df8db4.mp4

**Comment by apoorv-mishra** [comment]
Thanks @gunnarbeutner ! Fixed.

**Review by gunnarbeutner — APPROVED** [review]

**Pull request merged**
