### PR TITLE
Ports/citron: Update to the latest commit

### PR DESCRIPTION
**Pull request by tcl3**
With this patch added, the `citron` port now builds with GCC 13.

I'd be happy to make a PR to the upstream repository if it would be preferred for me to make the change there. Let me know.

Currently, I'm seeing the following error when launching the program in serenity:

citron_error
___
The file that it's complaining about exists, so I'm not immediately sure what's going on. It's possible I'm doing something wrong, as I'm not sure how this is supposed to work :shrug:.

### CODE REVIEW

**Comment by timschumi** [comment]
Yeah, this looks to be something that should be fixed upstream. I heard the developer is a fan of the project. :^)

As for fixing this locally ahead of time, I'm not even sure if `SIGTERM` is the correct signal to raise here. This looks like more of an assert, so `SIGABRT` would likely be more appropriate.

**Comment by alimpfard** [comment]
@tcl3 let's upstream it, I can take this patch if you don't wanna make a PR.

**Comment by tcl3** [comment]
@alimpfard - I'll make a PR now.

**Comment by alimpfard** [comment]
Regarding the error, I'll take a look at it tomorrow, but let's consider the port functional if a simple hello-world works:
```
# test.ctr
Pen writeln: 'hello world'.
```
run by `ctr test.ctr`.

**Comment by tcl3** [comment]
My latest push updates `citron` to the latest upstream commit. I've removed some patches that set Makefile options and replaced them with `export`s in `package.sh`, as I believe that'll be easier to maintain. I'm still getting the original error when invoking `citron`, including trying to run the hello world program suggested above. 

Text of the error:

```
Uncaught error has occurred.
No such file or directory
#7 realPath (/usr/share/Citron/extensions/importlib.ctr: 44)
#6 v (/usr/share/Citron/extensions/importlib.ctr: 44)
#5 each: (/usr/share/Citron/extensions/importlib.ctr: 41)
#4 __resolve_request:internally: (/usr/share/Citron/extensions/importlib.ctr: 88
)
#3 paths (/usr/share/Citron/extensions/importlib.ctr: 88)
#2 __load: (/usr/share/Citron/extensions/importlib.ctr: 114)
#1 Library/Data/Map (/usr/local/bin/citron: 34) [Ignored]
------------------------------------
The probable cause of the exception: 
42 | 
43 |     v is v + '/' + ext_path.
44 |     v is File new: v, realPath.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
45 |     (var f is File new: (v + '/$$name' + '.ctr')) exists ifTrue: {
```

**Comment by alimpfard** [comment]
Looks like it's still trying to invoke the REPL...either way though, that it gets to that point means the compiler is working, so LGTM.

**Pull request merged**
