### PR TITLE
Ports: sl

### PR DESCRIPTION
**Pull request by Ivoah**
Port of https://github.com/mtoyoda/sl for SerenityOS

### CODE REVIEW

**Comment by awesomekling** [comment]
Hey neat :)

**Comment by bugaevc** [comment]
I'm getting
> cp: cannot stat '/home/sergey/dev/serenity/Root/usr/local/share/terminfo/78/xterm': No such file or directory

trying to build this. Does it depend on some other port, like ncurses or something?

**Comment by bugaevc** [comment]
Also, it installs `sl` into `/usr/bin`, and not `/usr/local/bin` as it should. And we already have `/bin/sl` which launches Solitare.

**Comment by Ivoah** [comment]
> I'm getting
> 
> > cp: cannot stat '/home/sergey/dev/serenity/Root/usr/local/share/terminfo/78/xterm': No such file or directory
> 
> trying to build this. Does it depend on some other port, like ncurses or something?

Yes it depends on ncurses. I have that listed in the depends section though. Is there something more I need to do for that?

**Pull request merged**
