### PR TITLE
Kernel: Implement more of the initialization process for the aarch64 Kernel

### PR DESCRIPTION
**Pull request by FireFox317**
This PR contains a simple implementation of the Processor class, and moves some of the initialization into it.

It also reorders the NOLOAD sections to the end of the ELF file, such that objcopy doesn't add them to the binary and thus saves 6MBs in the final `kernel8.img`.

### CODE REVIEW

**Comment by nico** [comment]
Typo "scrinks" in 2md commit message.

**Comment by nico** [comment]
Other than that, looks good to me 🙂

**Comment by FireFox317** [comment]
> Typo "scrinks" in 2md commit message.

Fixed :)

**Review by linusg — CHANGES_REQUESTED** [review]
Seperate -> Separate in both code & commit messages. Thanks for taking time to review @nico! :^)

**Comment by FireFox317** [comment]
@linusg and @nico, Thanks for the review!

Fixed the spelling mistakes, and also added an extra commit that sorts the aarch64 CMake sources.

**Pull request merged**
