### PR TITLE
Userland JS repl: add live syntax highlighting

### PR DESCRIPTION
**Pull request by alimpfard**
This PR adds live syntax highlighting to the js repl.
Some of the colours might be of questionable taste, however.

### CODE REVIEW

**Comment by awesomekling** [comment]
This looks overly complex and will be a maintenance burden. It's also way more C than C++.
Furthermore, it doesn't work correctly and breaks basic REPL functionality.

I don't think we want this feature as-is. At the very least it would need to be written in idiomatic Serenity C++ and actually work. :)

**Comment by alimpfard** [comment]
well, I'll commence refactors on the more-C++ side~

so far as repl functionality goes, could you elaborate on that a bit?
I _did_ some testing, and the repl seemed to behave fine

**Comment by awesomekling** [comment]
> so far as repl functionality goes, could you elaborate on that a bit?
> I _did_ some testing, and the repl seemed to behave fine

Some immediately noticeable issues:
* Backspace does not work
* ^W does not work
* ^U does not work
* The cursor is not in the right position

**Comment by alimpfard** [comment]
> backspace
Curious, this _does_ work for me.

I'd have to lookup what those two combinations do, as I admit, I am not a frequent user of control-combinations in repls.

let's see if I can make this little feature look presentable, then.

**Comment by alimpfard** [comment]
Well, you're right on it being a maintenance pain; reimplementing a decent chunk of tty functionality is not a good point either.

I do wonder if exposing Shell/LineEditor as a userspace library is the more sane approach here (also adding some hooks to LineEditor would be ideal).

ideas?

**Comment by awesomekling** [comment]
> Well, you're right on it being a maintenance pain; reimplementing a decent chunk of tty functionality is not a good point either.
> 
> I do wonder if exposing Shell/LineEditor as a userspace library is the more sane approach here (also adding some hooks to LineEditor would be ideal).
> 
> ideas?

That is a fantastic idea! A line editing library would be a great thing to have, and would be a much better place for this kind of functionality. :)

**Comment by alimpfard** [comment]
So if one was to theoretically try to expose said Shell/LineEdit to userspace, where would be the proper place to move it?

and I think closing this PR would be best, until we have the proper tools to deal with it.

**Comment by awesomekling** [comment]
> So if one was to theoretically try to expose said Shell/LineEdit to userspace, where would be the proper place to move it?

I would suggest creating a `LibLine` and moving the `LineEditor` from `Shell` to there.

> and I think closing this PR would be best, until we have the proper tools to deal with it.

Sure.

**Pull request closed without merging**
