### PR TITLE
LibJS/JIT: Add fast-path for float arithmetic

### PR DESCRIPTION
**Pull request by feliwir**
- [x] Introduce floating point registers.
- [x] Add a fast path for double+double path
- [x] Add a fast path for double-double path
- [x] Add a fast path for double*double path

### CODE REVIEW

**Comment by awesomekling** [comment]
I don't understand the state of this PR. You have 2 unchecked boxes, does that mean it's a draft?
Also, it's nice to show benchmark data when making performance changes :)

**Comment by awesomekling** [comment]
> > I don't understand the state of this PR. You have 2 unchecked boxes, does that mean it's a draft? Also, it's nice to show benchmark data when making performance changes :)
> 
> Sorry, state is definetly unfinished. I just opened it so i can get early feedback from others in Discord. Should i close it before it's done?

Just mark it as a draft until it's ready for review :)

**Comment by skyrising** [comment]
Here are the results on my machine:
```
Suite      Test                                   Speedup  Old (Mean ± Range)           New (Mean ± Range)
---------  -----------------------------------  ---------  ---------------------------  ---------------------------
Kraken     ai-astar.js                              1.029  2.447 ± 2.350 … 2.560        2.377 ± 2.320 … 2.420
Kraken     audio-beat-detection.js                  1.231  1.437 ± 1.410 … 1.460        1.167 ± 1.160 … 1.170
Kraken     audio-dft.js                             1.328  1.053 ± 1.040 … 1.070        0.793 ± 0.760 … 0.820
Kraken     audio-fft.js                             1.379  1.347 ± 1.320 … 1.390        0.977 ± 0.970 … 0.990
Kraken     audio-oscillator.js                      1.138  2.093 ± 2.060 … 2.130        1.840 ± 1.830 … 1.850
Kraken     imaging-darkroom.js                      1.172  5.020 ± 5.000 … 5.040        4.283 ± 4.200 … 4.390
Kraken     imaging-desaturate.js                    1.494  2.017 ± 1.960 … 2.050        1.350 ± 1.330 … 1.370
Kraken     imaging-gaussian-blur.js                 1.123  17.940 ± 17.860 … 18.040     15.973 ± 15.650 … 16.190
Kraken     json-parse-financial.js                  1      0.080 ± 0.080 … 0.080        0.080 ± 0.080 … 0.080
Kraken     json-stringify-tinderbox.js              1.029  0.237 ± 0.230 … 0.240        0.230 ± 0.230 … 0.230
Kraken     stanford-crypto-aes.js                   0.995  0.667 ± 0.650 … 0.680        0.670 ± 0.640 … 0.700
Kraken     stanford-crypto-ccm.js                   0.99   0.680 ± 0.670 … 0.690        0.687 ± 0.680 … 0.690
Kraken     stanford-crypto-pbkdf2.js                0.989  1.160 ± 1.140 … 1.180        1.173 ± 1.170 … 1.180
Kraken     stanford-crypto-sha256-iterative.js      1.007  0.500 ± 0.490 … 0.510        0.497 ± 0.490 … 0.500
Octane     box2d.js                                 1.063  3.690 ± 3.670 … 3.710        3.470 ± 3.440 … 3.510
Octane     code-load.js                             1      2.170 ± 2.160 … 2.180        2.170 ± 2.160 … 2.180
Octane     crypto.js                                0.997  6.160 ± 6.130 … 6.190        6.177 ± 6.140 … 6.200
Octane     deltablue.js                             1.006  3.110 ± 3.100 … 3.120        3.090 ± 3.060 … 3.110
Octane     earley-boyer.js                          0.983  32.587 ± 32.300 … 32.820     33.157 ± 32.730 … 33.440
Octane     gbemu.js                                 0.983  4.677 ± 4.580 … 4.750        4.757 ± 4.750 … 4.770
Octane     mandreel.js                              1.007  30.923 ± 30.740 … 31.070     30.707 ± 30.300 … 31.300
Octane     navier-stokes.js                         1.334  2.770 ± 2.100 … 3.160        2.077 ± 2.040 … 2.100
Octane     pdfjs.js                                 0.987  4.027 ± 3.940 … 4.090        4.080 ± 4.020 … 4.150
Octane     raytrace.js                              0.984  8.587 ± 8.530 … 8.620        8.730 ± 8.520 … 8.890
Octane     regexp.js                                1.009  28.813 ± 28.580 … 28.960     28.560 ± 28.490 … 28.610
Octane     richards.js                              1.002  2.033 ± 2.030 … 2.040        2.030 ± 2.020 … 2.040
Octane     splay.js                                 0.997  3.177 ± 3.170 … 3.190        3.187 ± 3.180 … 3.200
Octane     typescript.js                            0.974  69.607 ± 68.530 … 71.110     71.433 ± 70.390 … 72.060
Octane     zlib.js                                  1.012  122.093 ± 121.020 … 122.700  120.703 ± 120.050 … 121.230
```

**Comment by awesomekling** [comment]
Really cool :)

**Pull request merged**
