### PR TITLE
LibGUI: Comfy status bar buttons

### PR DESCRIPTION
**Pull request by thankyouverycool**
https://user-images.githubusercontent.com/66646555/155134257-86cf437e-5d11-4f16-9fc6-085df026622e.mp4

### CODE REVIEW

**Comment by paulwratt** [comment]
very cool, can they be programmed?

**Comment by thankyouverycool** [comment]
> can they be programmed?

in LibGooey, the only limit is your imagination

**Comment by nico** [comment]
Looks neat! Maybe they should have some kind of affordance so they look interact-able even when not hovered? (Tiny drop down arrow on the right or what)

**Comment by paulwratt** [comment]
> Tiny drop down arrow on the right or what

realestate down there is limited. Sometimes its nice for an GUI to supprise you with is "untapped abilities".

**Comment by awesomekling** [comment]
Interesting expansion of the `Tray` button style concept (which was originally only intended for trays widget (the thing on the left in GUI file picker dialogs.)

Seems okay though, and the name even kinda sorta fits it. :)

Also, sweet feature!

**Pull request merged**
