### PR TITLE
Lagom: Tmux is not needed for lagom gdb

### PR DESCRIPTION
**Pull request by Coderdreams**

### CODE REVIEW

**Comment by ADKaster** [comment]
This change makes sense, but the commit message does not follow the proper style. Please force-push your branch with an amended commit message that follows the pattern:

> Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").

<https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy>

Namely, "Lagom: Tmux is not needed for lagom gdb" doesn't start with a verb, and is not in the imperative mood. The "what" belongs in the first line of the commit message, and the "why" belongs in the commit description.

**Comment by Coderdreams** [comment]
> This change makes sense, but the commit message does not follow the proper style. Please force-push your branch with an amended commit message that follows the pattern:
> 
> > Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").
> 
> https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy
> 
> Namely, "Lagom: Tmux is not needed for lagom gdb" doesn't start with a verb, and is not in the imperative mood. The "what" belongs in the first line of the commit message, and the "why" belongs in the commit description.

Fixed

**Comment by trflynn89** [comment]
"unrequiring" isn't a word (and while we're here, the prefix should be Meta) -> `Meta: Do not require tmux to run gdb on Lagom`

**Comment by Coderdreams** [comment]
The original commit message was perfectly understandable, that's some annoying bs policy.

**Pull request merged**
