### PR TITLE
Userland: Begin implementing libraries for aarch64

### PR DESCRIPTION
**Pull request by serenityosrocks**
This compiles, links and runs.  Doesn't do anything interesting yet, but this is progress.

### CODE REVIEW

**Comment by serenityosrocks** [comment]
Also of note: this only works with clang.  gcc needs a little more work yet.

**Comment by bgianfo** [comment]
In `AK` for example, instead of `#ifdef`ing the implementations, we could have separate "AK::Details" namespaces (possibly in a different file we include) for the different architectures. That would be a much cleaner approach. 

We shouldn't turn the code base into a `#ifdef` hellscape without a reason.

**Comment by bgianfo** [comment]
This should also be separated into smaller, atomic commits. Right now it's just one giant change, which is difficult to review.

**Review by bgianfo — CHANGES_REQUESTED** [review]
This should be separated into smaller, atomic commits. Right now it's just one giant change, which is difficult to review.

As mentioned earlier, please also think about ways to avoid using `ifdef` for porting, it makes the code incredibly hard to maintain.

**Comment by bgianfo** [comment]
> This compiles, links and runs.

How do you know it runs? We don't have aarch64 even booting into the kernel... So all of this code is unreachable?

**Comment by bgianfo** [comment]
#10621 Actually has some changes that would help here.

**Pull request closed without merging**
