### PR TITLE
LibC: Misc additions and a typo fix

### PR DESCRIPTION
**Pull request by RealKC**

### CODE REVIEW

**Comment by awesomekling** [comment]
Actually, `stdbool.h`, `stdnoreturn.h` and `stdalign.h` are all provided by the compiler and should not be part of **LibC**. So I think the correct fix here is to remove our `stdbool.h` :)

**Comment by RealKC** [comment]
Oh that would also work then, so drop the stdbool, stdnoreturn and stdalign commits and remove stdbool.h?

**Comment by awesomekling** [comment]
Yeah :)

**Comment by RealKC** [comment]
Think that should do it

**Pull request merged**
