### PR TITLE
Base+Browser: Add Browser icons

### PR DESCRIPTION
**Pull request by electrikmilk**
- Add some missing icons to the menubar.
- Propose we use the browser icon as the default favicon, as other browsers do
- Modified new and close tab icons

Change default tab icon
Screen Shot 2022-01-11 at 17 11 57

Duplicate tab
Screen Shot 2022-01-11 at 17 12 52

Menubar icons
Screen Shot 2022-01-11 at 17 12 26
Screen Shot 2022-01-11 at 17 12 20
Screen Shot 2022-01-11 at 17 12 12
Screen Shot 2022-01-11 at 17 12 07

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Nice work! It would be good if you could also make Browser *use* these, as a second commit. Should just be a case of adding the path to the relevant Action constructors.

**Review by linusg — CHANGES_REQUESTED** [review]
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy

> Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").

---

Please also consider running something like `optipng` over these images. GitHub shows a 1500% size increase for close-tab.png for example, which isn't great.

**Comment by electrikmilk** [comment]
> https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy
> 
> > Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").
> 
> Please also consider running something like `optipng` over these images. GitHub shows a 1500% size increase for close-tab.png for example, which isn't great.

- Changed commit message
- Optimized PNGs with optipng

**Comment by electrikmilk** [comment]
Only thing I'm not sure of at this point is how to make tab.png the default favicon for tabs.

**Comment by electrikmilk** [comment]
This might be related to the Pixel Paint icons error, because I used Photoshop and not Gimp.

**Comment by linusg** [comment]
> imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work")

...so it should be "Add", not "Added" (in all PRs).

**Comment by linusg** [comment]
> and why optipng didn't seem to help much...

Not sure either, but thanks for trying if it helps! Perhaps it actually needs that much more bytes :shrug:

**Comment by linusg** [comment]
I believe the default icon for any LibWeb page, and therefore Browser as well, is here:

https://github.com/SerenityOS/serenity/blob/d92558b3b3df6304894d59dcd7dbd8e90eb89958/Userland/Libraries/LibWeb/Loader/FrameLoader.cpp#L32-L35

We probably want a browser-specific default bitmap as the tab icon doesn't make sense universally, so this needs a bit more work than just changing the filename. Feel free to give it a try, or we can defer it to a later point :)

**Comment by electrikmilk** [comment]
> I believe the default icon for any LibWeb page, and therefore Browser as well, is here:
> 
> https://github.com/SerenityOS/serenity/blob/d92558b3b3df6304894d59dcd7dbd8e90eb89958/Userland/Libraries/LibWeb/Loader/FrameLoader.cpp#L32-L35
> 
> We probably want a browser-specific default bitmap as the tab icon doesn't make sense universally, so this needs a bit more work than just changing the filename. Feel free to give it a try, or we can defer it to a later point :)

That's fair, given that most browsers seem to use their logo as a new tab icon...

Screen Shot 2022-01-11 at 4 48 33 PM
Screen Shot 2022-01-11 at 4 48 47 PM

**Pull request merged**
