### PR TITLE
Base: Add Italic version of Katica

### PR DESCRIPTION
**Pull request by electrikmilk**
Screen Shot 2022-02-06 at 17 41 44
Screen Shot 2022-02-06 at 17 42 03

### CODE REVIEW

**Review by Xexxa — CHANGES_REQUESTED** [review]
Metadata shows name as "Roman Regular" and family as "Roman" :^)

**Comment by electrikmilk** [comment]
> Metadata shows name as "Roman Regular" and family as "Roman" :^)

😬

**Comment by electrikmilk** [comment]
@Xexxa Fixed metadata

**Review by Xexxa — APPROVED** [review]
lgtm

**Pull request merged**
