### PR TITLE
LibJS: Implement (no-op) debugger statement

### PR DESCRIPTION
**Pull request by linusg**
https://tc39.es/ecma262/#sec-debugger-statement

> Evaluating a DebuggerStatement may allow an implementation to cause a breakpoint when run under a debugger. If a debugger is not present or active this statement has no observable effect.

Anyone wanna add a JS debugger to HackStudio?

### CODE REVIEW

**Comment by alimpfard** [comment]
That's gonna be a very annoying thing to implement, what with the billions of implicit execution stuff that the Interpreter has...

**Comment by sunverwerth** [comment]
This would be easier to implement once we have a VM for javascript.

**Comment by linusg** [comment]
who am i kidding, the only debugger I use is `console.log()` anyway!

**Comment by linusg** [comment]
@awesomekling may I ask for a review pls :)

**Comment by awesomekling** [comment]
\o/

**Pull request merged**
