### PR TITLE
LibLine: Allow the user to override (or add) keybinds in the config file

### PR DESCRIPTION
**Pull request by alimpfard**
This PR adds configurable keybindings.
My current favourite keybinding is `e=internal:finish_edit`, it makes almost everything impossible to do lol

### CODE REVIEW

**Comment by awesomekling** [comment]
Sure sure, as long as we have nice defaults :)

**Comment by alimpfard** [comment]
They're the same defaults as before~
I can't stop people from `" "=internal:transpose_words` though

**Comment by awesomekling** [comment]
I think this broke `^W` and `^U`

**Comment by alimpfard** [comment]
> I think this broke ^W and ^U

Fixed by #3203~

**Pull request merged**
