### PR TITLE
LibJS: Strict mode should be function- or file-level, not block-level

### LINKED ISSUE #3641: LibJS: Strict mode should be per-file or per-function, not per-block
cc @linusg

### PR DESCRIPTION
**Pull request by mattco98**
Fixes #3641

### CODE REVIEW

**Comment by awesomekling** [comment]
Can we store this with the function or program node instead of the block node?

**Comment by linusg** [comment]
This comment is about to become outdated and should be removed :)

https://github.com/SerenityOS/serenity/blob/e4bda2e1e70efed986745431e132b6608586b991/Libraries/LibJS/Interpreter.h#L89-L95

**Comment by mattco98** [comment]
> Can we store this with the function or program node instead of the block node?
Yeah that'd probably be better, I'll do that instead :)

> This comment is about to become outdated and should be removed :)
True, I'll go ahead and remove that

**Comment by awesomekling** [comment]
Excellent @mattco98, thanks for fixing this :)

**Pull request merged**
