### PR TITLE
LibJIT: Fix minor typo

### PR DESCRIPTION
**Pull request by miloudi98**
This fixes a simple typo. Sorry if I was missing something.

Quick question:
Are there any plans of adding new features to the x86 assembler? Or is it good mature enough for now?
I see that memory addressing modes requiring a SIB byte are not supported. Is there no use-case for it in the JIT compiler? Or is it simply not implemented yet?

### CODE REVIEW

**Comment by timschumi** [comment]
I'm not the resident JIT expert, but I assume that these are (currently) very intentional.

**Comment by miloudi98** [comment]
Interesting, yeah I had a feeling it was intentional. Is it possible to know why you need to do that?
Closing this PR.

**Comment by Hendiadyoin1** [comment]
Iirc this was for stack alignment,
I think it was mentioned in one of the videos that introduced this

**Comment by miloudi98** [comment]
Interesting, I'm curious about why we chose `push rbx` as the instruction used for stack alignment instead of something like a [NOP](https://www.felixcloutier.com/x86/nop). Performance maybe?
But that makes sense, thank you for the explanation.

**Pull request closed without merging**
