### PR TITLE
Everywhere: Use title case for man section titles

### PR DESCRIPTION
**Pull request by networkException**
The individual pages were using title case for their titles already,
now the overview page uses the same formatting.

### CODE REVIEW

**Comment by trflynn89** [comment]
While we're here, can we update the following files as well?
Base/usr/share/man/man1/man.md
Base/usr/share/man/man1/Help.md
Userland/Applications/Help/ManualModel.cpp

**Comment by networkException** [comment]
currently both `Libraries` and `Library Functions` are is used as the title for section three, what would be the preferred one?

**Comment by trflynn89** [comment]
> currently both `Libraries` and `Library Functions` are used as titles for section three, what would be the preferred one?

Good question, @awesomekling @linusg any preference here?

**Comment by awesomekling** [comment]
No strong feelings here. Both seem okay, just pick one :)

**Comment by networkException** [comment]
alright, I went with `Library Functions` as thats whats used on Linux, macOS and BSD according to Wikipedia

**Pull request merged**
