### PR TITLE
Kernel: Some small fixes for the write syscall path

### LINKED ISSUE #7069: Kernel: Sometimes TTY::write() writes more bytes than was supplied
How to reproduce: run `yes aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` in the terminal (argument should be at least 40 'a's long). In the scrollback, you will occasionally see lines that are longer than the argument. This persists even when `yes` is patched to use direct write syscalls instead of buffered file IO (even when VERIFY-ing that the call to `write()` always returns the length of the argument).

### PR DESCRIPTION
**Pull request by ccapitalK**
Some miscellaneous ~one/two-line~ small fixes for the write syscall path. Fixes #7069 .

### CODE REVIEW

**Comment by ccapitalK** [comment]
Actually, this fixes #7069 but would probably break the expected behaviour when c_lflag is set. I'll need to re-think this.

**Comment by ccapitalK** [comment]
Ok, the new version should handle that case. There is now a very rare chance that it will convert a '\n' into '\r\r\n' instead of '\r\n'

**Comment by linusg** [comment]
This has conflicts now

**Comment by ccapitalK** [comment]
I've pushed a new version that shouldn't have any conflicts.

**Pull request merged**
