### PR TITLE
LibJS: TypedArray fixes

### PR DESCRIPTION
**Pull request by linusg**
See commit messages for gory details. Someone was really winging it :)

### CODE REVIEW

**Comment by awesomekling** [comment]
Completely winging it!

**Comment by linusg** [comment]
I can't figure out why this doesn't build though, working fine locally :(

```
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(GlobalObject.cpp.o): in function `JS::TypedArrayPrototype* JS::Heap::allocate<JS::TypedArrayPrototype, JS::GlobalObject&>(JS::GlobalObject&, JS::GlobalObject&)':
./Build/../Libraries/LibJS/Heap/Heap.h:63: undefined reference to `JS::TypedArrayPrototype::TypedArrayPrototype(JS::GlobalObject&)'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: ./Build/../Libraries/LibJS/Heap/Heap.h:68: undefined reference to `JS::TypedArrayPrototype::initialize(JS::GlobalObject&)'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(GlobalObject.cpp.o): in function `JS::TypedArrayConstructor* JS::Heap::allocate<JS::TypedArrayConstructor, JS::GlobalObject&>(JS::GlobalObject&, JS::GlobalObject&)':
./Build/../Libraries/LibJS/Heap/Heap.h:63: undefined reference to `JS::TypedArrayConstructor::TypedArrayConstructor(JS::GlobalObject&)'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: ./Build/../Libraries/LibJS/Heap/Heap.h:68: undefined reference to `JS::TypedArrayConstructor::initialize(JS::GlobalObject&)'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(TypedArray.cpp.o): in function `JS::Uint8ArrayConstructor::Uint8ArrayConstructor(JS::GlobalObject&)':
./Build/../Libraries/LibJS/Runtime/TypedArray.cpp:99: undefined reference to `JS::TypedArrayConstructor::TypedArrayConstructor(AK::FlyString const&, JS::Object&)'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(TypedArray.cpp.o): in function `JS::Uint16ArrayConstructor::Uint16ArrayConstructor(JS::GlobalObject&)':
./Build/../Libraries/LibJS/Runtime/TypedArray.cpp:99: undefined reference to `JS::TypedArrayConstructor::TypedArrayConstructor(AK::FlyString const&, JS::Object&)'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(TypedArray.cpp.o): in function `JS::Uint32ArrayConstructor::Uint32ArrayConstructor(JS::GlobalObject&)':
./Build/../Libraries/LibJS/Runtime/TypedArray.cpp:99: undefined reference to `JS::TypedArrayConstructor::TypedArrayConstructor(AK::FlyString const&, JS::Object&)'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(TypedArray.cpp.o): in function `JS::Int8ArrayConstructor::Int8ArrayConstructor(JS::GlobalObject&)':
./Build/../Libraries/LibJS/Runtime/TypedArray.cpp:99: undefined reference to `JS::TypedArrayConstructor::TypedArrayConstructor(AK::FlyString const&, JS::Object&)'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(TypedArray.cpp.o): in function `JS::Int16ArrayConstructor::Int16ArrayConstructor(JS::GlobalObject&)':
./Build/../Libraries/LibJS/Runtime/TypedArray.cpp:99: undefined reference to `JS::TypedArrayConstructor::TypedArrayConstructor(AK::FlyString const&, JS::Object&)'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(TypedArray.cpp.o):./Build/../Libraries/LibJS/Runtime/TypedArray.cpp:99: more undefined references to `JS::TypedArrayConstructor::TypedArrayConstructor(AK::FlyString const&, JS::Object&)' follow
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(TypedArray.cpp.o): in function `JS::Uint8ArrayConstructor::~Uint8ArrayConstructor()':
./Build/../Libraries/LibJS/Runtime/TypedArray.cpp:99: undefined reference to `JS::TypedArrayConstructor::~TypedArrayConstructor()'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(TypedArray.cpp.o): in function `JS::Uint16ArrayConstructor::~Uint16ArrayConstructor()':
./Build/../Libraries/LibJS/Runtime/TypedArray.cpp:99: undefined reference to `JS::TypedArrayConstructor::~TypedArrayConstructor()'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(TypedArray.cpp.o): in function `JS::Uint32ArrayConstructor::~Uint32ArrayConstructor()':
./Build/../Libraries/LibJS/Runtime/TypedArray.cpp:99: undefined reference to `JS::TypedArrayConstructor::~TypedArrayConstructor()'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(TypedArray.cpp.o): in function `JS::Int8ArrayConstructor::~Int8ArrayConstructor()':
./Build/../Libraries/LibJS/Runtime/TypedArray.cpp:99: undefined reference to `JS::TypedArrayConstructor::~TypedArrayConstructor()'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(TypedArray.cpp.o): in function `JS::Int16ArrayConstructor::~Int16ArrayConstructor()':
./Build/../Libraries/LibJS/Runtime/TypedArray.cpp:99: undefined reference to `JS::TypedArrayConstructor::~TypedArrayConstructor()'
/home/runner/work/serenity/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: Libraries/LibJS/libjs.a(TypedArray.cpp.o):./Build/../Libraries/LibJS/Runtime/TypedArray.cpp:99: more undefined references to `JS::TypedArrayConstructor::~TypedArrayConstructor()' follow
collect2: error: ld returned 1 exit status
```

**Comment by linusg** [comment]
Also `build_lagom_with_fuzzers` was successful??!!

**Comment by alimpfard** [comment]
@linusg did you forget to add the new prototype cpp file to CMakeLists.txt?
I think Lagom uses globs, so this gets detected automagically there (\*hint hint\*)

**Pull request merged**
