### PR TITLE
LibC: Add ensure_pledge and ensure_unveil APIs

### PR DESCRIPTION
**Pull request by mustafaquraish**
Every time in the code base we do a `pledge()` or `unveil()` call,
it looks something like this:

```cpp
if (unveil("...", "...") < 0) {
    perror("unveil");
    return 1;
}
```
which to be seems like a bit of an eyesore, especially since many
applications need to make repeated calls to unveil(). These new
APIs allow you to just call :

```cpp
ensure_unveil("...", "...");
```

The program will only continue past that point if the unveil was
successful, otherwise it exits with a status of 1.

---

For now, I've also updated all the Applets to use these new APIs,
and in my opinion it looks much cleaner and nice on the eyes. If
this is something that you all don't mind adding, I can do make
these changes throughout the codebase incrementally.

### CODE REVIEW

**Comment by kleinesfilmroellchen** [comment]
Just a note on terminology: `unveil` is a system call, i.e. an API to the operating system.

**Review by kleinesfilmroellchen — APPROVED** [review]

**Comment by mustafaquraish** [comment]
> Just a note on terminology: `unveil` is a system call, i.e. an API to the operating system.

Thanks, these sort of tips are always helpful. Though I'm not sure I understand, how is the usage here incorrect? Would `ensure_unveil()` for instance be called a *new API* to perform unveil without manually checking for errors?

**Comment by kleinesfilmroellchen** [comment]
@mustafaquraish `ensure_unveil`, at least in your implementation, is a library function in LibC. It wraps around the system call `unveil`. System call means that even though it's part of LibC and can be called by a normal program, it executes a system call which causes a bunch of magic (interrupt 42, context switch to ring 1 (?), assembly magic) and the kernel will do something for you that you can't do yourself. So it's significantly different from just any API, like calling out to IPC or just causing some complex unprivileged code to run (e.g. uncompressing a zip file)

**Comment by awesomekling** [comment]
If we're going to make a more convenient API for these, let's go a few steps further:
- Let's make it C++ and put it in LibCore
- Let's make it accept `StringView` instead of C strings
- Let's allow passing multiple paths to allow doing everything in one go :)

**Pull request closed without merging**
