### PR TITLE
Next iteration of SQL work

### PR DESCRIPTION
**Pull request by JanDeVisser**
- Again a lot of under-the-covers grunt work, but I think I have the Value machinery almost nailed now. Some more spit and polish coming up the next round though.
- But also: you can now insert into a table and see the results in SQL:
image

Note that the INSERT is still very limited in what it can do (basically only insert literals like in the screenshot), and SELECT is
even more limited: Only SELECT * FROM table works. Can't specify columns, or joins, or expressions, or aggregates. No. Just the asterisk wildcard and a single table.

Of course I had some more git grief when I wanted to get my work branch up-to-date with master. I think I did it all right; let me know if something's up.

### CODE REVIEW

**Comment by JanDeVisser** [comment]
Um yeah. I just found out you can't reuse a feature branch for a second pull request (the commits for the first PR are listed here in the second one). Lemme see if I can fix that.

**Comment by JanDeVisser** [comment]
Fixed it.

**Review by trflynn89 — APPROVED** [review]
Oops! Sorry, I was on vacation when this was opened and completely forgot about it when I got back. Looks good to me, nice work! :smile:

**Comment by trflynn89** [comment]
Shoot, looks like there's conflicts with the `master` branch though, sorry @JanDeVisser

**Comment by JanDeVisser** [comment]
No worries. I’ll rebase. I’m doing some more work and that’s taking a bit
longer than I thought, but maybe we can roll that into this one

**Comment by JanDeVisser** [comment]
Took the opportunity to once again do a bunch of refactoring while Tim was on vacation - introduced the `Serializer` class which mediates between client code and the raw data heap. This class will also mediate caching and locking between 'connections'.

@trflynn89

**Comment by JanDeVisser** [comment]
@trflynn89 I don't know man. I can do a pointless force-push to trigger a new CI round and hope that works better, but otherwise....

**Comment by trflynn89** [comment]
@JanDeVisser So the issues with the Azure builders have been fixed, so if you rebase on master, that macOS build should pass. That one GitHub Action builder is still flaky though.

**Comment by JanDeVisser** [comment]
@trflynn89 Ugh git played games with me again. I don't know where those commits came from; I thought I fetched and rebased like I usually do but something obviously went wrong. Let me see if I can fix.

**Comment by JanDeVisser** [comment]
The awesome rps on discord (no idea what his github account is) pointed out that ``sql``  doesn't seem to work- it hangs after startup. The server creates the database heap file but then crickets. I can confirm this, but when I set ``SQLSERVER_DEBUG`` to 1 it works. Most curious. I will investigate tomorrow

**Review by trflynn89 — APPROVED** [review]

**Comment by rstefanic** [comment]
I'm rps in Discord. I've submitted a PR related to the `SQLSERVER_DEBUG` issue.

**Pull request merged**
