### PR TITLE
LibJS+LibWeb: Implement WebAssembly Native Errors

### PR DESCRIPTION
**Pull request by networkException**
This pull request adds the CompileError, RuntimeError and LinkError native errors and exposes them on the WebAssembly object.

Initially I tried defining the errors outside LibJS, this however is non trivial as both [we](https://github.com/SerenityOS/serenity/blob/8ff7c52cf43273b9a7e2a63c0c12cf2dd0379d5e/Userland/Libraries/LibJS/Runtime/AbstractOperations.h#L134) and [the spec](https://tc39.es/ecma262/#sec-ordinarycreatefromconstructor) rely (?) on intrinsics knowing about them.

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
There's no reason whatsoever for these errors to live in LibJS. In fact, if anything that doesn't have a spec on tc39.es needs to exist in LibJS, that's an architectural issue we need to solve. (console excluded, and there's one HTML spec data member somewhere and that's already annoying)

Here's the spec you'll want to look at and implement in LibWeb: https://webassembly.github.io/spec/js-api/#error-objects

**Comment by networkException** [comment]
Ah I wasn't aware of the strict spec isolation (but it makes a whole lot of sense obviously). Sadly I don't really know where to begin with changing the architecture to support non LibJS native errors.

**Comment by alimpfard** [comment]
You can look at how the various `DOMException`s are currently implemented, these basically follow the same concept.

**Comment by linusg** [comment]
These are different though and explicitly _not_ platform objects, only things defined via WebIDL are.

They implement the _NativeError_ object structure from ES, as described in the spec I linked. You might be able to use the existing `DECLARE_NATIVE_ERROR` macros for this.

**Comment by networkException** [comment]
Right, I tried using `DECLARE_NATIVE_ERROR{,_CONSTRUCTOR,_PROTOTYPE}` initially.

However implementing [`ConstructorName::construct`](https://tc39.es/ecma262/#sec-nativeerror) requires [`ordinary_create_from_constructor`](https://tc39.es/ecma262/#sec-ordinarycreatefromconstructor) which isn't really designed to take host specific prototypes:

- The spec defines "Assert: intrinsicDefaultProto is this specification's name of an intrinsic object" as a step and

- we require a member of `Intrinsics` to be passed.

**Comment by AtkinsSJ** [comment]
This has conflicts.

**Pull request closed without merging**
