### PR TITLE
Base: Complete Mathematical Operators in Katica Regular 10

### PR DESCRIPTION
**Pull request by cubiclove**
Screenshot

https://www.unicode.org/charts/PDF/U2190.pdf
⇧ - U+21E7 UPWARDS WHITE ARROW (Corrected)

https://www.unicode.org/charts/PDF/U2200.pdf
∁ - U+2201 COMPLEMENT

∃ - U+2203 THERE EXISTS
∄ - U+2204 THERE DOES NOT EXIST

∈ - U+2208 ELEMENT OF
∉ - U+2209 NOT AN ELEMENT OF
∊ - U+220A SMALL ELEMENT OF
∋ - U+220B CONTAINS AS MEMBER
∌ - U+220C DOES NOT CONTAIN AS MEMBER
∍ - U+220D SMALL CONTAINS AS MEMBER
∎ - U+220E END OF PROOF

∓ - U+2213 MINUS-OR-PLUS SIGN
∔ - U+2214 DOT PLUS
∕ - U+2215 DIVISION SLASH
∖ - U+2216 SET MINUS
∗ - U+2217 ASTERIX OPERATOR
∘ - U+2218 RING OPERATOR
∙ - U+2219 BULLET OPERATOR
√ - U+221A SQUARE ROOT (Improved)
∛ - U+221B CUBE ROOT
∜ - U+221C FOURTH ROOT
∝ - U+221D PROPORTIONAL TO

∟ - U+221F RIGHT ANGLE
∠ - U+2220 ANGLE
∡ - U+2221 MEASURED ANGLE
∢ - U+2222 SPHERICAL ANGLE
∣ - U+2223 DIVIDES
∤ - U+2224 DOES NOT DIVIDE
∥ - U+2225 PARALLEL TO
∦ - U+2226 NOT PARALLEL TO

∭ - U+222D TRIPLE INTEGRAL
∮ - U+222E CONTOUR INTEGRAL
∯ - U+222F SURFACE INTEGRAL
∰ - U+2230 VOLUME INTEGRAL
∱ - U+2231 CLOCKWISE INTEGRAL
∲ - U+2232 CLOCKWISE CONTOUR INTEGRAL
∳ - U+2233 ANTICLOCKWISE CONTOUR INTEGRAL
∴ - U+2234 THEREFORE
∵ - U+2235 BECAUSE
∶ - U+2236 RATIO
∷ - U+2237 PROPORTION
∸ - U+2238 DOT MINUS
∹ - U+2239 EXCESS
∺ - U+223A GEOMETRIC PROPORTION
∻ - U+223B HOMOTHETIC
∼ - U+223C TILDE OPERATOR
∽ - U+223D REVERSED TILDE
∾ - U+223E INVERTED LAZY S
∿ - U+223F SINE WAVE

≁ - U+2241 NOT TILDE
≂ - U+2242 MINUS TILDE (Improved)
≃ - U+2243 ASYMPTOTICALLY EQUAL TO (Improved)
≄ - U+2244 NOT ASYMPTOTICALLY EQUAL TO
≅ - U+2245 APPROXIMATELY EQUAL TO (Improved)
≆ - U+2246 APPROXIMATELY BUT NOT ACTUALLY EQUAL TO
≇ - U+2247 NEITHER APPROXIMATELY NOR ACTUALLY EQUAL TO
≈ - U+2248 ALMOST EQUAL TO (Improved)
≉ - U+2249 NOT ALMOST EQUAL TO
≊ - U+224A ALMOST EQUAL OR EQUAL TO (Improved)
≋ - U+224B TRIPLE TILDE (Improved)
≌ - U+224C ALL EQUAL TO (Improved)
≍ - U+224D EQUIVALENT TO (Moved)
≎ - U+224E GEOMETRICALLY EQUIVALENT TO (Moved/Improved)
≏ - U+224F DIFFERENCE BETWEEN (Moved/Improved)

≝ - U+225D EQUAL TO BY DEFINITION
≞ - U+225E MEASURED BY
≟ - U+225F QUESTIONED EQUAL TO

≢ - U+2262 NOT IDENTICAL TO

≭ - U+226D NOT EQUIVALENT TO
≮ - U+226E NOT LESS-THAN
≯ - U+226F NOT GREATER-THAN
≰ - U+2270 NEITHER LESS-THAN NOR EQUAL TO
≱ - U+2271 NEITHER GREATER-THAN NOR EQUAL TO
≲ - U+2272 LESS-THAN OR EQUIVALENT TO
≳ - U+2273 GREATER-THAN OR EQUIVALENT TO
≴ - U+2274 NEITHER LESS-THAN NOR EQUIVALENT TO
≵ - U+2275 NEITHER GREATER-THAN NOR EQUIVALENT TO
≶ - U+2276 LESS-THAN OR GREATER-THAN
≷ - U+2277 GREATER-THAN OR LESS-THAN
≸ - U+2278 NEITHER LESS-THAN NOR GREATER-THAN
≹ - U+2279 NEITHER GREATER-THAN NOR LESS-THAN
≺ - U+227A PRECEDES
≻ - U+227B SUCCEEDS
≼ - U+227C PRECEDES OR EQUAL TO
≽ - U+227D SUCCEEDS OR EQUAL TO
≾ - U+227E PRECEDES OR EQUIVALENT TO
≿ - U+227F SUCCEEDS OR EQUIVALENT TO
⊀ - U+2280 DOES NOT PRECEDE
⊁ - U+2281 DOES NOT SUCCEED
⊂ - U+2282 SUBSET OF
⊃ - U+2283 SUPERSET OF
⊄ - U+2284 NOT A SUBSET OF
⊅ - U+2285 NOT A SUPERSET OF
⊆ - U+2286 SUBSET OF OR EQUAL TO
⊇ - U+2287 SUPERSET OF OR EQUAL TO
⊈ - U+2288 NEITHER A SUBSET OF NOR EQUAL TO
⊉ - U+2289 NEITHER A SUPERSET OF NOR EQUAL TO
⊊ - U+228A SUBSET OF WITH NOT EQUAL TO
⊋ - U+228B SUPERSET OF WITH NOT EQUAL TO
⊌ - U+228C MULTISET
⊍ - U+228D MULTISET MULTIPLICATION
⊎ - U+228E MULTISET UNION

⊢ - U+22A2 RIGHT TACK
⊣ - U+22A3 LEFT TACK
⊤ - U+22A4 DOWN TACK
⊥ - U+22A5 UP TACK
⊦ - U+22A6 ASSERTION
⊧ - U+22A7 MODELS
⊨ - U+22A8 TRUE

⊬ - U+22AC DOES NOT PROVE
⊭ - U+22AD NOT TRUE
⊮ - U+22AE DOES NOT FORCE
⊯ - U+22AF NEGATED DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE

⊲ - U+22B2 NORMAL SUBGROUP OF
⊳ - U+22B3 CONTAINS AS NORMAL SUBGROUP
⊴ - U+22B4 NORMAL SUBGROUP OF OR EQUAL TO
⊵ - U+22B5 CONTAINS AS NORMAL SUBGROUP OR EQUAL TO
⊶ - U+22B6 ORIGINAL OF
⊷ - U+22B7 IMAGE OF
⊸ - U+22B8 MULTIMAP
⊹ - U+22B9 HERMITIAN CONJUGATE MATRIX (Improved)

⊻ - U+22BB XOR
⊼ - U+22BC NAND
⊽ - U+22BD NOR

⋄ - U+22C4 DIAMOND OPERATOR
⋅ - U+22C5 DOT OPERATOR

⋈ - U+22C8 BOWTIE
⋉ - U+22C9 LEFT NORMAL FACTOR SEMIDIRECT PRODUCT
⋊ - U+22CA RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT

⋎ - U+22CE CURLY LOGICAL OR
⋏ - U+22CF CURLY LOGICAL AND
⋐ - U+22D0 DOUBLE SUBSET
⋑ - U+22D1 DOUBLE SUPERSET
⋒ - U+22D2 DOUBLE INTERSECTION
⋓ - U+22D3 DOUBLE UNION
⋔ - U+22D4 PITCHFORK

⋖ - U+22D6 LESS-THAN WITH DOT
⋗ - U+22D7 GREATER-THAN WITH DOT
⋘ - U+22D8 VERY MUCH LESS-THAN
⋙ - U+22D9 VERY MUCH GREATER-THAN
⋚ - U+22DA LESS-THAN EQUAL TO OR GREATER-THAN
⋛ - U+22DB GREATER-THAN EQUAL TO OR LESS-THAN
⋜ - U+22DC EQUAL TO OR LESS-THAN
⋝ - U+22DD EQUAL TO OR GREATER-THAN
⋞ - U+22DE EQUAL TO OR PRECEDES
⋟ - U+22DF EQUAL TO OR SUCCEEDS
⋠ - U+22E0 DOES NOT PRECEDE OR EQUAL
⋡ - U+22E1 DOES NOT SUCCEED OR EQUAL
⋢ - U+22E2 NOT SQUARE IMAGE OF OR EQUAL TO
⋣ - U+22E3 NOT SQUARE ORIGINAL OF OR EQUAL TO
⋤ - U+22E4 SQUARE IMAGE OF OR NOT EQUAL TO
⋥ - U+22E5 SQUARE ORIGINAL OF OR NOT EQUAL TO
⋦ - U+22E6 LESS-THAN BUT NOT EQUIVALENT TO
⋧ - U+22E7 GREATER-THAN BUT NOT EQUIVALENT TO
⋨ - U+22E8 PRECEDES BUT NOT EQUIVALENT TO
⋩ - U+22E9 SUCCEEDS BUT NOT EQUIVALENT TO
⋪ - U+22EA NOT NORMAL SUBGROUP OF
⋫ - U+22EB DOES NOT CONTAIN AS NORMAL SUBGROUP
⋬ - U+22EC NOT NORMAL SUBGROUP OF OR EQUAL TO
⋭ - U+22ED DOES NOT CONTAIN AS NORMAL SUBGROUP OR EQUAL
⋮ - U+22EE VERTICAL ELLIPSIS
⋯ - U+22EF MIDLINE HORIZONTAL ELLIPSIS
⋰ - U+22F0 UP RIGHT DIAGONAL ELLIPSIS
⋱ - U+22F1 DOWN RIGHT DIAGONAL ELLIPSIS
⋲ - U+22F2 ELEMENT OF WITH LONG HORIZONTAL STROKE
⋳ - U+22F3 ELEMENT OF WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
⋴ - U+22F4 SMALL ELEMENT OF WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
⋵ - U+22F5 ELEMENT OF WITH DOT ABOVE
⋶ - U+22F6 ELEMENT OF WITH OVERBAR
⋷ - U+22F7 SMALL ELEMENT OF WITH OVERBAR
⋸ - U+22F8 ELEMENT OF WITH UNDERBAR
⋹ - U+22F9 ELEMENT OF WITH TWO HORIZONTAL STROKES
⋺ - U+22FA CONTAINS WITH LONG HORIZONTAL STROKE
⋻ - U+22FB CONTAINS WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
⋼ - U+22FC SMALL CONTAINS WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
⋽ - U+22FD CONTAINS WITH OVERBAR
⋾ - U+22FE SMALL CONTAINS WITH OVERBAR

### CODE REVIEW

**Comment by Diogenes31** [comment]
Looks great to me! Excellent clarity on some fairly complex looking glyphs.

**Review by Xexxa — CHANGES_REQUESTED** [review]
Not sure if I'm a fan of the dots drawn as dashes for 22D6, 22D7, 22F5. Comparing with the dot in 2250 for example.

Except that minor issue, the glyphs looks great! The improved glyphs surely is improvements.

I also wondered who made that silly U+224D-U+224F placement mistake? Hello [14 months ago me](https://github.com/SerenityOS/serenity/pull/12356) :'-)

**Comment by cubiclove** [comment]
Screenshot 2023-04-14 at 17 13 12

I have changed those glyphs 🙂
Originally I'd worried the dots would be too hard to see so I turned them into dashes to make them more visible - but I agree we should have dots instead!

**Review by Xexxa — APPROVED** [review]
LGTM

**Pull request merged**
