### PR TITLE
AK+LibCore: Stop using `DeprecatedString::characters()`

### PR DESCRIPTION
**Pull request by DanShaders**
There are two distinct cases when we use this function currently. The first one is when we don't actually care about zero termination and pass length with the string. The second is when we are about to call some external C API and do actually care. With this PR, I propose to use new `DeprecatedString::characters_without_null_termination` in the former case and continue to use `DeprecatedString::characters` in the later.

Why do I care? As you probably know, I want to unify `*String` classes memory layout and thus allow fast casts between them. This is impossible to do cleanly without either reintroducing zero-termination to `String` or making `DeprecatedString` zero-termination optional. I decided to take the second path.

Optional zero-termination means that `characters()` won't be a cheap method to call anymore. It will have to reallocate underlying buffer in case it is not zero-terminated already (and it won't be in most of the cases). Fortunately, we don't have to call `characters()` often. Due to Serenity's NIH, we only need zero-termination when we interact with GUI framework in Ladybird chrome or invoke syscall/LibC syscall wrapper in Lagom. Both of these operations are relatively rare, so I'm fine with String doing memory gymnastics in these cases.

On Serenity itself, we do not have external APIs at all, so we theoretically don't even need `DeprecatedString::characters()` and all the reallocation code. In practice however, we sometimes call LibC functions, which do not have equivalents with `StringView` arguments. So, wrapping `characters` in `#ifndef AK_OS_SERENITY` will require a substantial refactor of Serenity-specific code, which I am currently not ready to do.

I am ready, however, to check all the calling sites of `characters` and mark if they need zero termination or not.

------

In case what is written above makes sense, this is first in series of migration PRs. I decided to also add superfluous `characters_for_external_api` to make this refactoring easier. With it, I can easily add `[[deprecated]]` to `characters()` locally and fix compilation errors. Note that I haven't added similar `DeprecatedFlyString::characters_for_external_api`, since I believe it doesn't make sense to use FlyString to call APIs (if one absolutely have to, casting to `DeprecatedString` is a trivial workaround).

This PR removes all uses of `Deprecated{Fly,}String::characters()` in AK and LibCore except for `LibCore/System.cpp`, `LibCore/DateTime.cpp` and `LibCore/SystemServerTakeover.cpp`. Two latter are addressed in #21701. I decided to not touch `System.cpp` since it has a million calls to `characters`, which all should be replaced with `characters_for_external_api`, and I am not sure what maintainers think about this name.

### CODE REVIEW

**Comment by alimpfard** [comment]
I haven't looked through the code, but here are some comments regarding your description:

> making `DeprecatedString` zero-termination optional. I decided to take the second path.

That seems very counter-intuitive to me, and I don't understand the need to have a fast cast from a byte string to a utf-8 string - utf8 validation will be the bottleneck, copying some memory is very likely not particularly expensive in comparison.

> Optional zero-termination means that `characters()` won't be a cheap method to call anymore [...]

Who will own the extra copy? the DeprecatedString instance?

> `characters_for_external_api` I am not sure what maintainers think about this name

I think it's rather pointless to push the requirement towards the API instead of simply using the type to encode it; I'm not convinced DS needs to lose the null termination, we gain just about nothing from this.

**Comment by DanShaders** [comment]
Answering in the assumption `StringBase` and theoretical `s/DeprecatedString/ByteString/` is merged:

If we think of `ByteString` as a sequence of arbitrary bytes with string semantics (basically `std::string`), why do we pretend that it will not ever have '\0' in the middle? By the same logic of making this a job for type system, we need three classes: `String` (UTF-8 validated), `ByteString` (arbitrary immutable sequence of bytes) and `CString` (arbitrary sequence of bytes, but no '\0' inside, zero-terminated). And if we are not completely free to use `ByteString` in syscalls taking `char const*`, why do we keep it zero-terminated?

Not requiring DS to be zero-terminated allows us to backport `String::substring_from_byte_offset_with_shared_superstring` to DS, for example.

Also, it feels like (from the perspective of university student) there is a general consensus that relying on null byte is not a good practice from security standpoint. Though, I cannot really provide any convincing arguments here. I guess it generally doesn't really matter if there is a null-terminator or not, but it looks as if Serenity in general prefers not to have it (see new `String` and syscall interface).

Oh, I haven't mentioned that the main point is to squeeze some performance without participating in DS -> String migration. Honestly, I am not sure how much we lose on these conversions, but I cannot really test without fully doing `characters` -> `characters_{without_zero_termination,for_external_api}` migration first.

> utf8 validation will be the bottleneck

As it is now, there is a lot of room for flags in `StringDetail` (we have 60 unused bits currently). So, for long strings we can easily store if the buffer was ever utf8 validated. Yes, this won't magically make us not ever validate UTF-8, but it will eliminate validation on round-trip conversions `String -> DS -> String` (which, I'm sure, are still common). Additionally, we can implement [this algorithm](https://arxiv.org/pdf/2010.03090.pdf), which will make validation reasonably fast.

> Who will own the extra copy? the DeprecatedString instance?

Yes. In case `characters()` has to reallocate, it will modify internal `StringBase` of DS. This is also the reason why I don't want to have this method in `DeprecatedFlyString`.

**Comment by DanShaders** [comment]
I forgot to mention that DS being optionally null-terminated (a) allows to store one more character in inline storage; (b) makes FlyString comparisons faster (by one conditional, though) without introducing additional complexity.

**Comment by DanShaders** [comment]
Okay, after some thinking I decided I would first measure the performance impact of this change with string unification actually implemented. Until then it'll be a draft.

**Comment by DanShaders** [comment]
Not stale

**Comment by DanShaders** [comment]
Let's close this for now instead of fighting with stalebot

**Pull request closed without merging**
