### PR TITLE
LibCore: Add an API to get the language name from the file extension

### PR DESCRIPTION
**Pull request by ry-sev**

### CODE REVIEW

**Comment by vkoskiv** [comment]
Please squash fix-ups to the relevant commit they belong to (with `--amend` or an interactive rebase)

**Comment by ry-sev** [comment]
I expect more languages/file extensions will be added in the future but I only put a few for now. Also, let me know if "Language" is not the correct name for this since other file extensions are included whose contents are not technically languages, such as "Plaintext".

**Comment by mustafaquraish** [comment]
Is there a need to create a new string whenever the function is called? Maybe this can just have a `FlyString` return value.

**Comment by ry-sev** [comment]
There's is no need to create a new string. I think i'm just naive when deciding between String, StringView, or FlyString; I think it was discussed on the discord server, I have to check.

**Comment by ry-sev** [comment]
Ok, I changed the return value to a FlyString. Thanks for the suggestion!

**Comment by awesomekling** [comment]
This PR just adds dead (unused) code, I don't understand the point of it.

Is this supposed to be used by something? Why is this more appropriate than guessing the MIME type?

**Comment by ry-sev** [comment]
The idea was to display the language name of a file opened in a statusbar in HackStudio. I didn't want to check the file type every time the update statusbar function is called. But thinking about it now, I could just put similar functionality in HackStudio::Language instead, since this PR may not be useful for other applications. Thanks for the feedback! I will close this PR.

**Pull request closed without merging**
