### PR TITLE
Remove all text relocations and remove PaX holes that existed for it.

### PR DESCRIPTION
**Pull request by nico**
Also reduces memory use after boot from 178 MiB to 173 MiB, due to libc having no dirty pages.

The patch is obviously correct.

---

Actually, I have no idea why this works. I thought plt_trampoline.S is what makes @PLT relocations work, so not sure why things don't blow up here.

@ADKaster @itamar8910

### CODE REVIEW

**Comment by ADKaster** [comment]
PLT worked and then with the full dynamic loader change it stopped working. The loader currently bypasses the lazy jump slot relocations happening at runtime by enforcing "bind now" behavior -- which does all the lazy relocs at program startup / lib load time.

**Comment by ADKaster** [comment]
Err looking at this it's actually very strange. That plt trampoline doesn't need built into LibC at all. Nor the dynamic loader/ dynamic object classes. Or. I guess any part of LibELF? There's some opportunities for Library refactoring here.

**Comment by awesomekling** [comment]
Can we just not support lazy binding? It has obvious security drawbacks and I'm not sure what benefit it actually provides.

**Comment by nico** [comment]
As far as I know the main benefit is that it makes application startup faster. If you link to a new .so and don't do lazy binding, you have to process all relocations to that so at load time, instead of paying just for the symbols your app actually needs, and only when it needs them.

(Another good way to make startup / binding faster is to do two-level lookup keyed first by so and then by symbol like macos (pre dyld cache, I suppose), instead of having a single huge namespace for all symbols.)

Maybe relocation processing is fast enough these days that it's not needed. Since we currently don't do it, maybe it's not worth adding this mmap exception for it. /shruggie

**Comment by awesomekling** [comment]
We still need the mmap exception for immediate binding. That only goes away if we ban text relocations entirely, unless I'm misunderstanding something(?)

**Comment by nico** [comment]
Right, right now the libc.so textrel is the only textrel there is according to `for l in $(find . -name '*.so'); do echo $l; (readelf -d $l | grep TEXT); done`. The only way to get them is to use asm files that add them, which most projects don't do. So maybe not supporting textrels is fine. (I guess they should get a nicer diag if we do that though.)

**Comment by awesomekling** [comment]
Okay, let's try not supporting them at all. With a better diagnostic, like you say.
This is not the kind of project that needs to make concessions for hypothetical future ports :smile:

**Comment by awesomekling** [comment]
Ninja-merged the first part of this patch in 1e6d04c7462848bc47a09e51a2f375022bc3ed93 since it's just too good. ;)

**Pull request closed without merging**
