### PR TITLE
Base: Move house on home-directory*.png icons to the left

### PR DESCRIPTION
**Pull request by linusg**
Otherwise it might be covered by the symlink overlay, which looks silly.

---

image image

image image

### CODE REVIEW

**Comment by linusg** [comment]
ran `optipng -strip all` on all images to keep them at their previous tiny size, apparently GIMP adds a lot of garbage by default (confirmed they're still loading in Serenity ofc)

**Comment by nico** [comment]
Maybe it could be in the upper right?

**Comment by linusg** [comment]
@nico which of these would you prefer?

image image

Personally I think both of these look worse than bottom left/right...

Another option is just centered:

image

**Comment by nico** [comment]
Hm, I guess they all need some getting used to. I retract my comment :)

**Pull request merged**
