### PR TITLE
AK/StackInfo: Add support for OpenBSD pthreads

### PR DESCRIPTION
**Pull request by nipos**
StackInfo currently doesn't provide a OpenBSD implementation.
Ladybird compiles and starts without StackInfo,but it crashes frequently.
This change makes it a lot more stable on OpenBSD,works just as good as on FreeBSD now.

### CODE REVIEW

**Comment by GMTA** [comment]
@nipos have you tried compiling it with the version that Linux and FreeBSD use? Looks like the `pthread_*` APIs being used there, are also available in OpenBSD.

So what I mean is, add `AK_OS_OPENBSD` as another `or` here:
https://github.com/SerenityOS/serenity/pull/17535/files#diff-57bb849c560d9dcce6cfccbb83f547cf49af849b6f53ffdf27de851d75fa7adeR31

**Comment by awesomekling** [comment]
Cool :)

**Comment by awesomekling** [comment]
Oh dangit, GitHub didn't show me GMTA's comment until *after* I clicked merge, sorry about that.

**Comment by nipos** [comment]
That's what I tried first,but OpenBSD doesn't support pthread_getattr_np (which is used on Linux) or pthread_attr_get_np (which is used on FreeBSD).
Skipping that line and continuing with pthread_attr_getstack makes it crash a little bit later than before,but it's still not usable.
After hours of research,I found out that pthread_stackseg_np seems to be more or less OpenBSDs replacement of pthread_getattr_np and pthread_attr_get_np,but it doesn't work *exactly* the same way so I had to include some more special handling.

**Comment by GMTA** [comment]
@nipos Ah you are right, `pthread_attr_get_np` is indeed not something OpenBSD supports. Carry on then :^)

**Pull request merged**
