### PR TITLE
PixelPaint: Several fixes, some code cleanup

### LINKED ISSUE #9971: PixelPaint: Grid drawing exceeds the image boundary
At `m_scale = 25` the grid lines extend beyond the image boundary.
This can be reproduced by:

1. Open PixelPaint
2. Fully zoom to the bottom or right edge
3. Zoom out one step at the time and in between the zoom steps, pan to trigger a redraw

unknown

### PR DESCRIPTION
**Pull request by mustafaquraish**
These 2 bugs are fixed:
- Drawing pixel grid outside image bounds (#9971)
- `Fit Image To View` action not working properly with rulers

Cleanup:
- Use FileSystemAccessServer exclusively now, remove unused methods 
- Use LibConfig to read in the pixel grid threshold as opposed to hardcoding it

Misc:
- Resize image to fit view on opening (I think this is a good default)

Fixes #9971

### CODE REVIEW

**Review by TobyAsE — COMMENTED** [review]
LGTM
Add a PixelPaint ini file too? I mean if we are using LibConfig, may as well...

**Comment by TobyAsE** [comment]
Also, add Fixes #9971 to the pr description, so it auto-closes on merge.

**Comment by mustafaquraish** [comment]
> LGTM
> Add a PixelPaint ini file too? I mean if we are using LibConfig, may as well...

The code reads the `~/.config/PixelPaint.ini` file. You can create it if you want to change the setting. I just didn't add a default empty one.

**Comment by mustafaquraish** [comment]
> Also, add Fixes #9971 to the pr description, so it auto-closes on merge.

Had already linked the PR, but added that exact phrasing too Incase GitHub looks for it. Thanks!

**Review by Granddave — APPROVED** [review]
Looks good, nice improvements!
I'm gonna start thinking about how we can refactor the rulers so we don't need to take `m_ruler_thickness` in to consideration at every place we are using `rect()` or similar functions. :)

**Pull request merged**
