### PR TITLE
Kernel: Add support for SA_SIGINFO

### PR DESCRIPTION
**Pull request by alimpfard**
The first two commits are from #12748, less pain to maintain like this.

Adds support for SA_SIGINFO, like you've always wanted
This includes a semi-dumb version of `ucontext` that probably can't do shit, and nice asm comments.

### CODE REVIEW

**Comment by awesomekling** [comment]
The commit "UserspaceEmulator: Update signal handlers to use the new stack layout" has a lot of different things going on in it. Can we split it up a little more?

**Comment by alimpfard** [comment]
Probably, will try splitting off the typed read stuff.

**Comment by alimpfard** [comment]
Done, hopefully I didn't mess anything up in the process.

**Comment by awesomekling** [comment]
> Done, hopefully I didn't mess anything up in the process.

One small problem: It doesn't build 😅

**Comment by alimpfard** [comment]
will look into it later today, including the CI failures.

**Comment by alimpfard** [comment]
Those shell failures are sus, drafting until I resolve them.

**Comment by awesomekling** [comment]
```
[Shell(9:9)]: KUBSAN: reference binding to misaligned address 0x0000002009978608 of type 'AK::Variant<Kernel::FPUState, AK::Error>'
[Shell(9:9)]: KUBSAN: at /home/vsts/work/1/s/./AK/Variant.h, line 151, column: 16
[Shell(9:9)]: Kernel + 0x0000000000af87df  print_location(AK::UBSanitizer::SourceLocation const&) +0x13f
[Shell(9:9)]: Kernel + 0x0000000000af9fe6  __ubsan_handle_type_mismatch_v1 +0x226
[Shell(9:9)]: Kernel + 0x0000000000a48115  AK::Detail::InheritFromUniqueEntries<0u, AK::Detail::ParameterPack<AK::Detail::VariantConstructors<Kernel::FPUState, AK::Variant<Kernel::FPUState, AK::Error> > >, AK::Detail::IntegerSequence<unsigned int, 0u, 1u>, AK::Detail::ParameterPack<AK::Detail::VariantConstructors<Kernel::FPUState, AK::Variant<Kernel::FPUState, AK::Error> > >, AK::Detail::ParameterPack<AK::Detail::VariantConstructors<AK::Error, AK::Variant<Kernel::FPUState, AK::Error> > > >::InheritFromUniqueEntries(Kernel::FPUState&&) +0x145
[Shell(9:9)]: Kernel + 0x0000000000a41c78  Kernel::Process::sys$sigreturn(Kernel::RegisterState&) +0x178
[Shell(9:9)]: Kernel + 0x000000000098b086  syscall_handler +0x7e6
[Shell(9:9)]: Kernel + 0x000000000098a890  syscall_asm_entry +0x30
[Shell(9:9)]: UB is configured to be deadly, halting the system.
```

**Pull request merged**
