### PR TITLE
Base: Add sha256sum manpage

### PR DESCRIPTION
**Pull request by danthedev123**
Added the sha256sum manpage as mentioned is needed in Issue #11311.

### CODE REVIEW

**Comment by timschumi** [comment]
Please extend the `checksum` manpage instead, since all four tools share 99% of the code.

**Comment by timschumi** [comment]
Also, where is the information about the options from?

**Comment by danthedev123** [comment]
Hello @timschumi!
I will also extend the checksum page, thanks for pointing it out. The info for the options is from the Linux manpage on sha256sum. I assumed that the options would be standard for all systems with that command. If the options are incorrect I would be happy to fix them, just let me know. Thanks!

**Comment by timschumi** [comment]
The only option that we currently support is `--check`, so the current manpage for `checksum` should be fine as-is, no change required.

Please don't copy content from other projects into Serenity without at least telling that you did so, and especially not without confirming that what you are submitting is actually valid.

**Comment by danthedev123** [comment]
Oh OK. So no change is required? If so I will close the issue. thanks!

**Pull request closed without merging**
