### PR TITLE
Rename ReadMe.md to README.md

### PR DESCRIPTION
**Pull request by nethracookie**

### CODE REVIEW

**Comment by drunderscore** [comment]
Ah, October is upon us.

**Comment by mehtaarn000** [comment]
How is this spam lol

**Comment by asynts** [comment]
It's because of Digital Oceans "Hacktoberfest". Basically, if you create four pull request on repositories somewhere that are not marked by "spam", you get a chance to win a t-shirt or something like that.

**Comment by mehtaarn000** [comment]
Ahh ok. But it should still be README.md anyways haha.

**Pull request closed without merging**
