### PR TITLE
Meta: Add myself to .mailmap

### PR DESCRIPTION
**Pull request by algorithmwolf**

### CODE REVIEW

**Comment by skyrising** [comment]
Looks like you actually used a different email for the commit you're trying to fix: <https://github.com/SerenityOS/serenity/commit/4ac1ad48a2ded915acd5dff809116652db627c9c.patch>

**Comment by algorithmwolf** [comment]
I am well aware. Unfortunately that email is abandoned. I will use the emails listed in this commit moving forward.

**Comment by nico** [comment]
I think the point of .mailmap is to map old email addresses to current ones, so that commits under the old address can be assigned to the current one (and show up as such in `git log`).

**Comment by algorithmwolf** [comment]
OK. I will use git_commit@ulveon.net moving forward. Hopefully that solves the problem?

**Review by kleinesfilmroellchen — APPROVED** [review]

**Pull request merged**
