### PR TITLE
Applets: Propagate errors using try_set_main_widget instead of set_main_widget

### PR DESCRIPTION
**Pull request by creator1creeper1**
These changes allow us to use try_set_main_widget instead of set_main_widget while constructing the different Applets, thereby improving error propagation.

### CODE REVIEW

**Comment by awesomekling** [comment]
This doesn't build on Clang CI

**Comment by creator1creeper1** [comment]
Thanks for the heads-up.

**Review by bgianfo — CHANGES_REQUESTED** [review]
Can we avoid the two phase construction in Audio applet, as discussed in discord recently?

**Comment by creator1creeper1** [comment]
Right, I didn't even think about this case when the discussion was going on. The problem is that all the GUI code seems pretty explicitly stateful to me, so I'm not whether we can just treat the windows as resources that we can pre-initialize.

**Comment by creator1creeper1** [comment]
I'm now convinced that it's impossible to avoid the two-phase construction in this case. The structure of the GUI code requires us to initialize parent objects before we initialize child objects, so we must first initialize the `AudioWidget` itself before we can initialize the GUI elements it contains.
If we consider the first line of the GUI initialization
```c++
m_slider_window = add<GUI::Window>(window());
```
what is really happening is the following:
```c++
m_slider_window = this->add<GUI::Window>(this->window());
```
`add()` is inherited from `GUI::Widget` which inherits it from `Core::Object`. `Core::Object::add()` simply calls the `::construct()` method of the type we're trying to add with the arguments we hand it. So it tries to construct a `GUI::Window` from `this->window()`. Now what we want to achieve is to first construct the `GUI::Window` independently from the `Core::Object* parent` that is `this->window()`. Only later do we then want to tell `m_slider_window` about our `this->window()` that should become its parent and then `add()` it to ourselves. But this is entirely impossible, because `GUI::Window` requires the `Core::Object* parent` in its constructor, so the parent object must exist before we construct this child object.

**Comment by bgianfo** [comment]
Ok, thanks for investigating!

**Pull request merged**
