### PR TITLE
Purge all the things!

### PR DESCRIPTION
**Pull request by bugaevc**
* Make malloc pages purgeable and volatile when empty
* Make shared inode mappings (in particular, executables themselves) purgeable

On a freshly booted system, this increases the number of pages `purge` prints from 30 to 659 (so over 2.5 MB).

### CODE REVIEW

**Comment by awesomekling** [comment]
Hmm, I like the `malloc` changes, but doesn't it seem overly crude to just include `InodeVMObject` in the purge mechanism? I feel like we can do better there. At the very least we should have a distinction between memory that userspace explicitly told us is purgeable vs memory that we (the kernel) knows can be reloaded from disk.

I think we should keep purging as a concept limited to `PurgeableVMObject` and instead build a separate mechanism for releasing inode-backed pages when we think that makes sense.

**Comment by bugaevc** [comment]
Why? I mean, I see that they're slightly different things by how we arrive there, but in the end it all comes down to purging physical pages that we know can be later recreated when needed.

There are more things than just inode mappings that the kernel can purge; there are various other caches and stuff. And purging them doesn't sound that different from purging userspace caches.

**Comment by awesomekling** [comment]
In the inode case, the work required to repopulate the pages is known and understood -- we'll have to read them from the filesystem again. We can also gather all kinds of information about which inode-backed pages are important and which ones are not (from process I/O activity, scheduling information, etc. As an example, a process that has been blocked for several minutes might be a better candidate for losing some executable pages than someone who is runnable right now.)

For userspace purgeable pages, we don't really have any of the information in the kernel, so we can't make nearly as sophisticated decisions. Adding a priority number to purgeable regions will make things a bit better, but it's still a very different beast IMO.

**Comment by bugaevc** [comment]
Maybe it's that you dislike how I have generalized "purging" to mean "free memory pages on request (by purging physical pages)"? We could pick a different word for that, and then "purging" (`MAP_PURGEABLE` volatile pages) would be one of the types of _that_.

In any case, if you're fine with the first half, feel free to only merge that.

**Comment by awesomekling** [comment]
Yeah, I guess so. That's a fair point :)

Is it actually possible to merge a partial PR?

**Comment by bugaevc** [comment]
> Is it actually possible to merge a partial PR?

'fcourse it is, just push those commits to your branch. GitHub won't display this PR as merged in its UI, but who cares.

**Comment by awesomekling** [comment]
Merged the first two (malloc) patches in 1ad5568759e3bfce20781286f24c466c62a78ddc and d91c40de3b86640e554654ee28d5c0dec0c8e1eb :)

**Pull request closed without merging**
