### PR TITLE
Ports: C-ray rendering engine

### PR DESCRIPTION
**Pull request by VKoskiv**
Ported my [lightweight path tracing renderer](https://github.com/VKoskiv/c-ray) to Serenity.

Right now it works to the extent that it only once crashed the kernel. Few patches may be able to be removed once the pthreads implementation matures.

You can see it working here in this very professional screenshot: 

Let me know if you want me to re-do my fork. It's a bit messier than what you might desire, though that can be remedied by a squash-merge as well.

### CODE REVIEW

**Comment by VKoskiv** [comment]
If you want to try it out, there is a patch that adds a readme with some instructions and notes to `/home/anon/c-ray/serenity_devs_readme.md`

**Comment by awesomekling** [comment]
* Please rebase and get rid of the merge commits since they are just noise.
* Please squash commits to reduce churn and simplify history. We don't need all those commits with the temporary version of strtod(), nor the ones messing with the indentation. Just one commit that adds strtod() is fine.
* Please use `clang-format` to make your code look like the rest of the codebase.

**Comment by VKoskiv** [comment]
@awesomekling I ran `clang-format` and squashed as requested.

**Comment by awesomekling** [comment]
Okay, almost there, but please separate the LibC and LibM changes from the porting work.
One commit per subsystem/library usually works. :)

**Comment by VKoskiv** [comment]
@awesomekling Done! This was good version control practice. I learned a bunch!

**Comment by awesomekling** [comment]
Cool beans! Thanks for the fixes :)

**Pull request merged**
