### PR TITLE
LibRegex: Fork before trying to match the repeated regexp

### LINKED ISSUE #9707: LibRegex: Regression in large regex used by test262 `Intl` tests
test262 uses a rather large regex to ensure the locales being tested are structurally valid. This regex regressed after commit 98624fe03.

The regex is:
```
^(([a-z]{2,3}|[a-z]{5,8})(-([a-z]{4}))?(-([a-z]{2}|[0-9]{3}))?(-([a-z0-9]{5,8}|(?:[0-9][a-z0-9]{3})))*(-((u((-([a-z0-9][a-z](-[a-z0-9]{3,8})*))+|((-([a-z0-9]{3,8}))+(-([a-z0-9][a-z](-[a-z0-9]{3,8})*))*)))|(t((-(([a-z]{2,3}|[a-z]{5,8})(-([a-z]{4}))?(-([a-z]{2}|[0-9]{3}))?(-([a-z0-9]{5,8}|(?:[0-9][a-z0-9]{3})))*)(-([a-z][0-9](-[a-z0-9]{3,8})+))*)|(-([a-z][0-9](-[a-z0-9]{3,8})+))+))|(([0-9]|[a-sv-wy-z])(-[a-z0-9]{2,8})+)))*(-(x(-[a-z0-9]{1,8})+))?)$
```

For example, this is now failing against the input string `und-u-ca-ethioaa`.

Also there's a `dbgln` that should probably be `dbgln_if`:
```c++
dbgln("max {}, min {}, reps {}", *maximum, minimum, repetitions);
```

CC @alimpfard 

For reference, this regex is created with the following JS (it is the `languageTagRE` var at the very end):
```javascript
var alpha = "[a-z]",
    digit = "[0-9]",
    alphanum = "[a-z0-9]",
    variant = "(" + alphanum + "{5,8}|(?:" + digit + alphanum + "{3}))",
    region = "(" + alpha + "{2}|" + digit + "{3})",
    script = "(" + alpha + "{4})",
    language = "(" + alpha + "{2,3}|" + alpha + "{5,8})",
    privateuse = "(x(-[a-z0-9]{1,8})+)",
    singleton = "(" + digit + "|[a-wy-z])",
    attribute= "(" + alphanum + "{3,8})",
    keyword = "(" + alphanum + alpha + "(-" + alphanum + "{3,8})*)",
    unicode_locale_extensions = "(u((-" + keyword + ")+|((-" + attribute + ")+(-" + keyword + ")*)))",
    tlang = "(" + language + "(-" + script + ")?(-" + region + ")?(-" + variant + ")*)",
    tfield = "(" + alpha + digit + "(-" + alphanum + "{3,8})+)",
    transformed_extensions = "(t((-" + tlang + "(-" + tfield + ")*)|(-" + tfield + ")+))",
    other_singleton = "(" + digit + "|[a-sv-wy-z])",
    other_extensions = "(" + other_singleton + "(-" + alphanum + "{2,8})+)",
    extension = "(" + unicode_locale_extensions + "|" + transformed_extensions + "|" + other_extensions + ")",
    locale_id = language + "(-" + script + ")?(-" + region + ")?(-" + variant + ")*(-" + extension + ")*(-" + privateuse + ")?",
    languageTag = "^(" + locale_id + ")$",
    languageTagRE = new RegExp(languageTag, "i");
```

### PR DESCRIPTION
**Pull request by alimpfard**
Otherwise the last failing fork would have nowhere to return to.
Fixes #9707.

I decided against copying the test262 test into our own suite.

### CODE REVIEW

**Comment by trflynn89** [comment]
Pulled this change in locally, unfortunately we're still tripping up on these:
```
"de-t-k0-qwertz-m0-din"
"en-t-d0-ascii-i0-handwrit"
```

These are transformed extensions with 2 key-value pairs each

**Comment by alimpfard** [comment]
:( marking as draft then.

**Comment by trflynn89** [comment]
LGTM!

**Comment by trflynn89** [comment]
We do have a failure with this regex on "pt-u-ca-gregory-u-nu-latn", but that was true before 98624fe03f047bc33002780bec2e37768c68e4b5, so certainly doesn't need to block this / can be looked at separately

**Comment by alimpfard** [comment]
> er nevermind, the issue wth that string is in another regex, -([0-9]|[a-wy-z])-(.*-)?\1(?![a-z0-9])

Boog fixed.

**Comment by trflynn89** [comment]
Sweet!

**Pull request merged**
