### PR TITLE
Calendar: Implement basic GUI calendar application

### PR DESCRIPTION
**Pull request by rhin123**
The plan is to be able to add events onto the calendar, but for now I'd like to see what you guys think so far. :sweat_smile:

### CODE REVIEW

**Comment by shannonbooth** [comment]
Maybe it would make sense to have some of your time functionality moved into a Library such as Core::DateTime, rather than the application itself? Seems like some of this logic might be useful elseware. Good on ya for implementing this though 😁

Closes #395 ?

**Comment by shannonbooth** [comment]
Yeah it seems #838 has some logic that is duplicated with day_of_week()

**Comment by rhin123** [comment]
> Yeah it seems #838 has some logic that is duplicated with day_of_week()

Alright moving those methods to Core::DateTime seem to make sense, fixed :+1:

**Comment by rhin123** [comment]
oh boy... :skull:  lets see if i can salvage this.. lol

**Comment by rhin123** [comment]
Ok i think i broke everything in my git. I'll just re-do the pull request... :sob:

**Pull request closed without merging**
