### PR TITLE
LibJS: Make Errors fully spec compliant

### PR DESCRIPTION
**Pull request by linusg**
cc @Lubrsi, can you confirm that this fixes the error you had on a website earlier?

### CODE REVIEW

**Comment by Lubrsi** [comment]
Fails to compile on my end:
```
[3/1279] Building CXX object Userland/Libraries/LibJS/CMakeFiles/LibJS.dir/MarkupGenerator.cpp.o
FAILED: Userland/Libraries/LibJS/CMakeFiles/LibJS.dir/MarkupGenerator.cpp.o 
/home/lukew/Desktop/serenity-project/serenity/Toolchain/Local/i686/bin/i686-pc-serenity-g++  -DDEBUG -DENABLE_COMPILETIME_FORMAT_CHECK -DLibJS_EXPORTS -DSANITIZE_PTRS -I../../Userland/Libraries -I../../. -I. -I../../Userland/Libraries/LibC -I../../Userland/Libraries/LibM -I../../Userland/Libraries/LibSystem -I../../Userland/Services -I../../Userland -IUserland/Services -IUserland/Libraries -IUserland -pie -fpic -fPIC   -fconcepts -Wno-literal-suffix -Wformat=2 -fdiagnostics-color=always -Werror -Wall -Wextra -Wno-address-of-packed-member -Wcast-qual -Wno-deprecated-copy -Wno-expansion-to-defined -Wimplicit-fallthrough -Wmissing-declarations -Wno-nonnull-compare -Wno-unknown-warning-option -Wundef -Wwrite-strings -ffile-prefix-map=/home/lukew/Desktop/serenity-project/serenity=. -fno-exceptions -fstack-protector-strong -g1 -fstack-clash-protection -O2 -std=c++2a -MD -MT Userland/Libraries/LibJS/CMakeFiles/LibJS.dir/MarkupGenerator.cpp.o -MF Userland/Libraries/LibJS/CMakeFiles/LibJS.dir/MarkupGenerator.cpp.o.d -o Userland/Libraries/LibJS/CMakeFiles/LibJS.dir/MarkupGenerator.cpp.o -c ../../Userland/Libraries/LibJS/MarkupGenerator.cpp
../../Userland/Libraries/LibJS/MarkupGenerator.cpp: In static member function 'static void JS::MarkupGenerator::error_to_html(const JS::Object&, AK::StringBuilder&, AK::HashTable<JS::Object*>&)':
../../Userland/Libraries/LibJS/MarkupGenerator.cpp:167:24: error: 'const class JS::Object' has no member named 'get_without_side_effects'
  167 |     auto name = object.get_without_side_effects("name").value_or(JS::js_undefined());
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~
../../Userland/Libraries/LibJS/MarkupGenerator.cpp:168:27: error: 'const class JS::Object' has no member named 'get_without_side_effects'
  168 |     auto message = object.get_without_side_effects("message").value_or(JS::js_undefined());
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by linusg** [comment]
huh, just tried a clean build and it did compile... let's see what CI says :sweat_smile:

**Comment by Lubrsi** [comment]
Seems to have compiled on CI, will have a look into why my build is failing

**Comment by Lubrsi** [comment]
It was a silly mistake :^), I had cherry picked half the PR :P

**Comment by Lubrsi** [comment]
Yes, it gets much further now :), it now crashes on a TODO in Document.cpp

**Review by awesomekling — CHANGES_REQUESTED** [review]
Typo in commit message:

`Error.prototype.name and Error.prototype.name`
->
`Error.prototype.name and Error.prototype.message`

**Comment by linusg** [comment]
Fixed :+1:

**Pull request merged**
