### PR TITLE
LibProtocol/ProtocolServer/Browser/pro: Make ProtocolServer stream downloaded data when and where possible

### PR DESCRIPTION
**Pull request by alimpfard**
What:
- Currently, ProtocolServer buffers the downloaded data until the download is finished, and then passes it along (by copying it into a shared buffer no less!) to its user
- In a good deal of situations, this is wasteful, and in some other situations, it makes no sense (e.g. when downloading a huge file to disk via `DownloadWidget` or `pro`)
- This PR makes ProtocolServer shove data down a pipe, and its user read it from the pipe (as the download is progressing) - if possible

Why:
- pipe `pro`'s output to `/dev/null` and laugh like a maniac
- Actually download huge files
- Open up the path for people that want to have fun with streaming downloads
- Make the API better in general
- Copy less stuff!

When:
- After some cleanups and some more extensive tests :)

cc @bugaevc @awesomekling and maybe @deoxxa (you asked to see the resulting API - this is most likely what it looks like)

### CODE REVIEW

**Comment by tomuta** [comment]
I like this, also this would probably pave the way to support HTTP/2...

**Comment by alimpfard** [comment]
HTTP/2 huh...it seems so far away, we don't even have support for persistent connections in LibHTTP.

**Comment by alimpfard** [comment]
This thing feels stable enough to undergo review now.
pls no hate, pls many reviews

**Comment by tomuta** [comment]
> HTTP/2 huh...it seems so far away, we don't even have support for persistent connections in LibHTTP.

HTTP/2 for the most part is quite straight forward. It's just binary frames and you have the concept of streams. And it's a persistent socket connection.

**Pull request merged**
