### PR TITLE
 LibC + Ports: Added strtoimax() and strtoumax() to make unnecesary a Prince of Persia patch

### PR DESCRIPTION
**Pull request by Baitinq**
They are the same as strtol() and strtoul() but if there is overflow/underflow then the maximum integer val/lower integer val/maximum uint val will be returned while also setting errno to ERANGE.

This makes the `remove_strtoimax.patch` obsolete.

### CODE REVIEW

**Comment by Baitinq** [comment]
This is probably a naive implementation so please let me know if I should change anything :D

**Comment by Baitinq** [comment]
EDIT: Fixed the format in accordance to the clang format.

**Comment by RealKC** [comment]
Some things I noticed:

1. You're checking if the value is in the range of (unsigned) int, but you should check if it's in the range of (u)intmax_t

2. I'd use stro(u)ll instead, to get a bigger range

3. I believe these functions should actually be defined in <inttypes.h>

**Comment by Baitinq** [comment]
> Some things I noticed:
> 
>     1. You're checking if the value is in the range of (unsigned) int, but you should check if it's in the range of (u)intmax_t
> 
>     2. I'd use stro(u)ll instead, to get a bigger range
> 
>     3. I believe these functions should actually be defined in <inttypes.h>

Ive added all your suggestions, thanks :D

**Comment by awesomekling** [comment]
Oh heck yeah :D

**Pull request merged**
