### PR TITLE
Documentation: Document setting UUID for VDI image

### PR DESCRIPTION
**Pull request by diversys**
Remove the note on updating the disk image by documenting setting UUID for VirtualBox VDI image.

### CODE REVIEW

**Comment by diversys** [comment]
cc @Lubrsi

**Review by linusg — CHANGES_REQUESTED** [review]
UUID of what? Please write commit messages so they're clear without needing additional context or having to look at the diff.

**Comment by linusg** [comment]
> commit message

You updated the PR title :)

**Comment by diversys** [comment]
I did both :)

**Comment by linusg** [comment]
image

**Review by linusg — APPROVED** [review]

**Pull request merged**
