### PR TITLE
Theme: Add Catppuccin theme

### PR DESCRIPTION
**Pull request by nullishamy**
Hey there!

I've ported the [Catppuccin theme](https://github.com/catppuccin/catppuccin) to Serenity.
The theme has 4 "flavours", including 3 dark and 1 light mode theme, so I have created a separate file for each.
This includes a `color-scheme` and a `theme`, so that the entire OS can be properly themed.

We have our own templating tools for building the ini files, which will live in https://github.com/catppuccin/serenity-os when it is created. Given Serenity's desire to have everything in house, we will of course keep the ini files here, but we would appreciate it if we could be assigned (so, assigning my user) to any issues that come up with the theme. This will allow us to stay in sync with any issues raised.

### CODE REVIEW

**Comment by nico** [comment]
The link in the description (https://github.com/catpuccin/catppuccin) 404s.

**Comment by nullishamy** [comment]
Edited, apologies.

**Comment by ADKaster** [comment]
Welcome to Serenity! catppuccin is a pretty cool theming project. However, we have quite a few themes in the base image, and it's getting a bit crowded. I couldn't tell from your screenshots in [the cattpucin issue](https://github.com/catppuccin/catppuccin/issues/2294)  how the purple, green, orange and blue pastel highlights are represented in Serenity. As such, the screenshots don't look very different from our existing themes? Or at least, the differences are subtle.

So, a couple suggestions for this:

- This seems like good fit for the theming-specific repository here: https://github.com/SerenityOS/theming
- The commit title should have `Base: ` as the category, rather than 'Theme: `.
 - If you really want the syntax highlighting help as a separate commit, it should mention which theme it's adding highlighting for. otherwise, merging them into one commit would be ok.
 - Please configure your editor to add a newline at EOF.

**Comment by nullishamy** [comment]
Thanks for the quick reply. No, Catppuccin is not *that* different from existing themes, so I think the theming repository is a good place to put it!

I can address the other points raised in my PR over there.

**Pull request closed without merging**
