### PR TITLE
Base: Add Control Pictures to font Katica Regular 10

### PR DESCRIPTION
**Pull request by Xexxa**
2400-2426 https://www.unicode.org/charts/PDF/U2400.pdf

**Important notice:**
Unicode charts often has clear representation of how a glyph should look, when it comes to "Control Pictures" the Unicode charts is like "do whatever, we don't care"* so I made up all the symbols for 2400-2421. Keep in mind that while this is following the specs it does not follow what most other fonts do, most other fonts seems to find a good symbol for the control code "ETX" is "ETX". 

2422-2426 was specified and therefore follows the Unicode charts.

_* The diagonal lettering glyphs are only exemplary; alternate representations may be, and often are used in the visible display of control codes._

Control-Pictures

### CODE REVIEW

**Comment by awesomekling** [comment]
Those ENQUIRY and ACKNOWLEDGE are great

**Comment by awesomekling** [comment]
Also ESCAPE :D

**Comment by Xexxa** [comment]
> Those ENQUIRY and ACKNOWLEDGE are great

Well, ENQUIRY is the weakest one imo "...it represents a signal intended to **trigger** a response", just showing a trigger was not clear enough. My personal favorite is DEVICE CONTROL modelled after a NES-controller. :^)

**Comment by electrikmilk** [comment]
That delete glyph is a nice solution, wasn't sure how we were gonna make the standard one.

**Pull request merged**
