### PR TITLE
Base: Add some Latin Extended-B for Katica Regular 10

### PR DESCRIPTION
**Pull request by electrikmilk**
This adds 0180—01FF of the Latin extended-B section of the unicode table: https://unicode-table.com/en/blocks/latin-extended-b

147864776-3dc32317-c0cd-4a85-821e-995e6f91a7f8

### CODE REVIEW

**Review by Xexxa — CHANGES_REQUESTED** [review]
First of all, these glyphs looks great!

Glyphs 10900-10901, 1091F are missing (#11551). When there is a merge conflict with binary files (like in our case) you might have to do some copy & paste.

I would also like to inform that the title is a bit misleading, most of 0200-024F is missing https://www.unicode.org/charts/PDF/U0180.pdf, a more accurate title would be "Add Latin Extended-B characters to Katica Regular 10" or "Add some Latin Extended-B characters to Katica Regular 10"

**Comment by electrikmilk** [comment]
> First of all, these glyphs looks great!
> 
> 
> 
> Glyphs 10900-10901, 1091F are missing (#11551). When there is a merge conflict with binary files (like in our case) you might have to do some copy & paste.
> 
> 
> 
> I would also like to inform that the title is a bit misleading, most of 0200-024F is missing https://www.unicode.org/charts/PDF/U0180.pdf, a more accurate title would be "Add Latin Extended-B characters to Katica Regular 10" or "Add some Latin Extended-B characters to Katica Regular 10"

Hmm... the unicode table I was working with didn't include the last dozen or so remaining glyphs. I'll adjust the wording...and maybe complete them in another PR later on.

As for the conflict...I'll copy those glyphs over if there aren't too many.

**Comment by Xexxa** [comment]
> > First of all, these glyphs looks great!
> > Glyphs 10900-10901, 1091F are missing (#11551). When there is a merge conflict with binary files (like in our case) you might have to do some copy & paste.
> > I would also like to inform that the title is a bit misleading, most of 0200-024F is missing https://www.unicode.org/charts/PDF/U0180.pdf, a more accurate title would be "Add Latin Extended-B characters to Katica Regular 10" or "Add some Latin Extended-B characters to Katica Regular 10"
> 
> Hmm... the unicode table I was working with didn't include the last dozen or so remaining glyphs. I'll adjust the wording...and maybe complete them in another PR later on.
> 
> As for the conflict...I'll copy those glyphs over if there aren't too many.

29 glyphs to copy, not to bad. I've had to do the same before. :) That's also the reason why I always check the open PRs before making a push, because merge conflicts with binary files sucks... ;-)

**Review by electrikmilk — COMMENTED** [review]
Changed PR name to reflect actual changes, synced with master by adding Phoenician characters 10900-10901, 1091F. (#11551).

**Comment by awesomekling** [comment]
Please don't include merge commits in PR's.
Also, please squash the "sync" commit.

**Comment by electrikmilk** [comment]
> Please don't include merge commits in PR's.
> Also, please squash the "sync" commit.

I was trying to amend the commits and it did a merge, I'll be more careful with my commits in the future.

I cannot squash the sync commit because it got counted as a merge for some reason:
Screen Shot 2022-01-04 at 17 19 24

As I said in another PR I'm pretty new to PRs, apologies.

**Comment by electrikmilk** [comment]
Should I just start a new PR?

**Pull request closed without merging**
