### PR TITLE
Base: Add "Valve" Theme

### PR DESCRIPTION
**Pull request by kimkulak**
wwwvalve

### CODE REVIEW

**Comment by elisee** [comment]
According to https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md, the commit message should say "Add" not "Added".

> Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").

You can amend the commit and then force-push to your branch.

**Comment by kimkulak** [comment]
> According to https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md, the commit message should say "Add" not "Added".
> 
> > Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").
> 
> You can amend the commit and then force-push to your branch.

I have done as instructed. I hope to see the "Valve" theme in SerenityOS soon :^)

**Comment by AtkinsSJ** [comment]
Welcome to the project! :^)

I noticed in the previous PR, your screenshot said to add some sizes to it in Theme Editor. Those should just be in the theme INI file. Is Theme Editor not saving those properly?

**Comment by kimkulak** [comment]
> Welcome to the project! :^)
> 
> I noticed in the previous PR, your screenshot said to add some sizes to it in Theme Editor. Those should just be in the theme INI file. Is Theme Editor not saving those properly?

The theme I used as the base didn't have custom button sizes set and I didn't think of looking for them in other theme .ini files. The problem has since been resolved in the new commit.

**Comment by AtkinsSJ** [comment]
Sorry you're having trouble with git, it takes some getting used to.

I'd recommend making your changes on a branch, (one for each pull request,) instead of master. That helps avoid messing things up when you pull the latest changes.

You might find this video helpful too, it explains how to modify existing commits: https://www.youtube.com/watch?v=ElRzTuYln0M

**Pull request closed without merging**
