### PR TITLE
Base: Add media emojis

### PR DESCRIPTION
**Pull request by BriannaFoxwell**
🔀 - U+1F500 Shuffle Tracks Button
🔁 - U+1F501 Repeat Button
🔂 - U+1F502 Repeat Single
🔃 - U+1F503 Clockwise Vertical Arrows
🔄 - U+1F504 Counterclockwise Arrows Button
🔙 - U+1F519 Back Arrow

### CODE REVIEW

**Comment by MacDue** [comment]
You need to capitalize the first letter of your commit message, so `Base: Add media emojis` :^)

**Comment by BriannaFoxwell** [comment]
wait you mean the commit, not the PR,
i'm kinda new to using Git

**Comment by MacDue** [comment]
You should squash your "Optimise media emojis" emoji into your first commit (we don't allow fixup commits in PRs)
This video may help with that if you're new to git: https://youtu.be/ElRzTuYln0M

**Review by tarob0ba — APPROVED** [review]
LGTM.

**Review by Xexxa — CHANGES_REQUESTED** [review]
image

Our other media emoji have another style, not sure if it makes sense to mix both style and colour? (not a rhetorical question, I don't know myself). I guess these are more of playlist controls so it might make sense to have another style? (all other major emoji sets keeps the style between the the different media emoji)

Also, if we are going with blue it makes sense to use the same shade of blue as https://github.com/SerenityOS/serenity/blob/master/Base/res/emoji/U+1F6C5.png (unless your shade is copied from another of our emoji, if so, then we might have to change the shade of U+1F6C5.png)

**Comment by BriannaFoxwell** [comment]
The shade of blue was copied from U+1F520
of which

- Input latin uppercase (U+1F520) 🔠
- Input latin lowercase (U+1F521) 🔡
- Input numbers (U+1F522) 🔢
- Input symbols (U+1F523) 🔣
- Input latin letters (U+1F524) 🔤

are all using the same shade #00A8ED, different to the one you linked, U+1F6C5,
most others use the same shade of #00A5E9 so to keep it consistant I have also changed the shade of the above to match

I've also made the playlist media keys consistant to the existing media keys

**Review by Xexxa — APPROVED** [review]
Nice, adding new emoji **and** fixing old ones. Couldn't be much better. 🎉

**Comment by AtkinsSJ** [comment]
Nice! Welcome to the project. :^)

**Pull request merged**
