### PR TITLE
LibJS: Add tests for all the unscopable Array prototype properties

### PR DESCRIPTION
**Pull request by Lubrsi**
When I was writing for tests for groupBy and groupByToMap, I noticed
there were no tests for these.

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
```diff
- LibJS: Test for all the unscopeable Array prototype properties
+ LibJS: Add tests for all the unscopeable Array prototype properties
```

**Comment by linusg** [comment]
Also perhaps `unscopable` to match `@@unscopables`?

**Comment by Lubrsi** [comment]
I spelt `unscopable` right in the branch name but not in the commit title :sweat_smile:

**Comment by linusg** [comment]
Thanks!

**Pull request merged**
