### PR TITLE
Meta: Remove accidental duplicate file

### PR DESCRIPTION
**Pull request by filiphsps**
Looks like `NetworkSettings.gml` accidentally got placed
inside of `/Base/home/anon`.

### CODE REVIEW

**Comment by networkException** [comment]
I'm not sure what the initial intend was (if any) but I think having a demo file to open in GMLPlayground is kinda nice

**Comment by filiphsps** [comment]
> I'm not sure what the initial intend was (if any) but I think having a demo file to open in GMLPlayground is kinda nice

Feels like it should be placed under Documents if that’s the case, couldn’t find any mention of it being intentional in the original commit.

**Comment by MacDue** [comment]
The prefix here just be `Base: ` not `Meta: ` :^)

**Comment by filiphsps** [comment]
> The prefix here should be `Base: ` not `Meta: ` :^)

Fixed :^)

**Pull request merged**
