### PR TITLE
Add wc program

### LINKED ISSUE #159: Userland: Implement "wc" program
We should have a `/bin/wc` program that counts newlines, words and bytes in input.

POSIX spec: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/wc.html

### PR DESCRIPTION
**Pull request by CallumAttryde**
Added an implementation of wc to fix #159. Uses STL rather than C style functions (ifstream rather than FILE*, cout rather than printf, iterators, etc.)

Uses https://www.gnu.org/software/cflow/manual/html_node/Source-of-wc-command.html as inspiration

### CODE REVIEW

**Comment by CallumAttryde** [comment]
Ok, I'll re-implement using those classes & patterns. I notice that `getline` is missing from stdio.h; would you be averse to me adding that as part of this PR? My current implementation uses it

**Comment by awesomekling** [comment]
Adding anything missing in LibC is always encouraged :)

**Comment by awesomekling** [comment]
Okay, now it's looking more like it belongs :) And thanks for adding `getdelim()` and `getline()` to LibC!

Before we continue, please switch to using 4 spaces instead of tabs. You can use `clang-format` to automatically apply the project coding style.
Also please squash the commits in your PR instead of building them on top of each other. Squashed PR's makes code review infinitely easier.

**Comment by awesomekling** [comment]
Nice, thanks Callum! :)

**Pull request merged**
