### PR TITLE
LibWeb+LibGfx: Rounded background images 

### PR DESCRIPTION
**Pull request by MacDue**
**In a screenshot:**
image
**Left:** LibWeb, **Right:** Google Chrome

This PR adds support for using the `background-image` property with `border-radius`, so now we can have nice and round images :^) [elliptical and antialiased -- you get the drill]

Note: Using a `border-radius` does not yet work on a `` tag, since that is rendered a different way  (via an `ImagePaintable`). But I think it should be possible to get this code shared between both the `` tag and background images in a future PR.

### CODE REVIEW

**Comment by linusg** [comment]
@MacDue friendly reminder that use of the Lenna image is discouraged.

> I retired from modeling a long time ago. It's time I retired from tech, too. We can make a simple change today that creates a lasting change for tomorrow. Let's commit to losing me.

**Comment by MacDue** [comment]
I was simply using random images I found used in the other HTML examples. There's not really other good test background images there, so I guess I'll just find a few creative commons ones.

**Comment by MacDue** [comment]
I was simply using random images I found used in the other HTML examples. There's not really other good test background images there, so I guess I'll just find a few creative commons ones.

**Comment by MacDue** [comment]
@linusg I've replaced Lenna with a CC0 image.

**Pull request closed without merging**
