### PR TITLE
Base+LibCards: Add ‘Classic’ face cards

### PR DESCRIPTION
**Pull request by cubiclove**
These are hand-drawn face/court cards for traditional French-suited playing cards.
For each of the four suits (Clubs, Hearts, Diamonds & Spades) there is a corresponding King, Queen, Jack and a standalone symbol which can be used for the numeral card patterns, including Ace. There is a special Ace of Spades card. Also included is a Joker card.

These illustrations are in their own folder called `Classic` so that other face card designs can be added to `cards/fronts` in the future (though I personally have no plans to add any).

To make space for the illustrations, change the design of the generated cards:
- Alter the card dimensions to be `80 x 110px` with a corner radius of `7px`. This is inspired by the dimensions of physical playing cards. It gives `12px` of padding between the illustration and the card's border.
- Move the card letter and symbol closer to the edge to make space.
- Adjust the club symbol to have the same dimensions as the other symbols.

This almost, though not perfectly, recreates the design from the mock-up below. The spacing of the letters/symbols is not quite right but is better than it was before.

Classic Face Cards

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Looks good to me! The one thing that does jump out at me is that the Joker has a white background instead of a transparent one, but that's not really a problem since all our cards are white. (I keep wondering about having a dark mode for cards, but it's unlikely to actually happen.)

**Comment by cubiclove** [comment]
I gave the cards white backgrounds because  it resulted in a smaller file size. I can upload them with transparent backgrounds for future proofing.

**Comment by cubiclove** [comment]
I've given the cards transparent backgrounds and renamed the standalone symbols to `Club`, `Heart`, `Diamond` and `Spade` because they are used for the patterns of all the numeral cards, not just the Aces. Let me know if they are too large!
Of course there is still a special image for the Ace of Spades, as is tradition.

**Review by AtkinsSJ — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
