### PR TITLE
Meta: Set -audiodev and fix q35

### LINKED ISSUE #4093: QEMU: '-soundhw pcspk' is deprecated, please set a backend using '-machine pcspk-audiodev=<name>' instead
Not sure how urgent this is or when/if this will be removed from QEMU, but I noticed this warning when starting Serenity (via `ninja run`):

```
qemu-system-i386: warning: '-soundhw pcspk' is deprecated, please set a backend using '-machine pcspk-audiodev=<name>' instead
```

```
$ qemu-system-i386 --version 
QEMU emulator version 5.1.0 (qemu-5.1.0-5.fc33)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
```

### PR DESCRIPTION
**Pull request by X-yl**
- Meta: Set -audiodev explictly
- Meta: Remove extra displays for Q35 machine and support SPICE

Closes #4093 and #8903

**CAUTION**: I changed run.sh so please can someone test this before merging it :/

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
I can confirm that it works for me on Arch Linux.

**Comment by gunnarbeutner** [comment]
The VM also starts on Windows, but audio doesn't work. `-audiodev dsound,id=snd0` works though.

**Comment by gunnarbeutner** [comment]
I've decided to cherry-pick the audio fix into the master branch (even though it doesn't completely fix the problem on Windows).

**Comment by X-yl** [comment]
Sorry, I've been really busy. Just give me a bit and I'll push the fix you suggested.

**Comment by gunnarbeutner** [comment]
No worries. :)

**Comment by gunnarbeutner** [comment]
Just to recap from Discord:
* Drop Q35 changes (for now).
* Split format=raw change into a separate commit.

**Pull request closed without merging**
