### PR TITLE
LibWeb: Add a spinning ladyball in the favicon before page load 

### PR DESCRIPTION
**Pull request by ben-abraham**
This PR allows for animated favicons, as well as adding an animated spinning ladyball 🐞 to indicate that a page is still waiting for the `onload` event to fire.

spinner

(pretend it's spinning)
image

### CODE REVIEW

**Comment by nico** [comment]
Seems like a cool feature, but the ladyball in the location bar looks a bit weird and non-spherical. The left and top edges have different numbers of pixels than the right and bottom edges, for example.

**Comment by ben-abraham** [comment]
> Seems like a cool feature, but the ladyball in the location bar looks a bit weird and non-spherical. The left and top edges have different numbers of pixels than the right and bottom edges, for example.

This may be due to how the image is displayed in the location bar. I checked the image and each frame looks as expected, it was generated with a script, so there really shouldn't be any un-evenness.

**Comment by ben-abraham** [comment]
Okay, it's because the URL bar is scaling the icon down to a lower resolution and the resampling is introducing un-evenness around the edges. For example, if you use a full-frame icon it's perfectly centered, but also the text perfectly illustrates how the scaling is affecting things.

image

Switching to `ScalingMode::BilinearBlend` helps a lot, but it still is not un-even on the ladyball. Much more readable zoomed out.

image
image


To be fair, even DDG shows un-even on this view.

image

**Comment by nico** [comment]
Maybe the ladyball load icon should be the size of the icon in the location bar, so that it doesn't have to be rescaled at paint time?

**Comment by ben-abraham** [comment]
> Maybe the ladyball load icon should be the size of the icon in the location bar, so that it doesn't have to be rescaled at paint time?

Pre-scaling the spinner gives a much more centered result, but obviously any sites serving up 32x32 or higher will still have that un-evenness.

image

**Pull request closed without merging**
