### PR TITLE
FileManager: Permission checkboxes moved to a new tab

### PR DESCRIPTION
**Pull request by kessejones**
The checkboxes for changing permissions are now on a separate tab.

### CODE REVIEW

**Comment by awesomekling** [comment]
Why though?

**Comment by brendalf** [comment]
I like the ideia of moving to another table. We can start adding new features in the properties window, like details, size and etc.

**Comment by kessejones** [comment]
I think it gets more organized like that.
We can add a SelectBox on this new tab to change the group as well.

**Comment by tomuta** [comment]
I would argue that most of the time the properties are accessed to view/change permissions. If they're not on the initial page, that's yet another click. In my opinion we should strive to reduce the amount of clicks for most tasks (which is why I quite liked Windows 7 back in the day).

**Comment by awesomekling** [comment]
Agree with @tomuta, this hides information and functionality between an unnecessary click. Let's not do this (unless there's a good reason, like having way too much information that we can't fit)

**Pull request closed without merging**
