### PR TITLE
Ports: Implement sqlite3 db for installed package state

### PR DESCRIPTION
**Pull request by tbhaxor**
Motivation for using sqlite3 (binary file) instead of plain text file comes from #20809. I am planning to implement SemVer library and a package query utility.

This is a minor change towards building a package manager.

image

### CODE REVIEW

**Comment by ADKaster** [comment]
If you add this feature, it should use our in-house LibSQL and sql utility rather than using sqlite3 as an external dependency

**Comment by tbhaxor** [comment]
In the the serenity os, it will use LibSQL, but how can I use LibSQL in the host? As a first step, I am planning to implement package query feature.

**Comment by ADKaster** [comment]
The `sql` utility is built as part of Lagom. `./Meta/serenity.sh run lagom sql` to give it a spin.

**Comment by ADKaster** [comment]
Erm. Ok it's not that simple. You need to run 
```
./Meta/serenity.sh build lagom ladybird
```
first, and then you can 
```
./Meta/serenity.sh run lagom sql -p $PWD/Build/lagom/bin/SQLServer
```

**Comment by ADKaster** [comment]
You know, trying it out I'm not sure that LibSQL can create the table in the way you've scripted it in the PR. But, we certainly can't read a sqlite3 database from disk. Our binary database format  is different.

**Comment by tbhaxor** [comment]
> Our binary database format is different.

Oh, thanks for this info beforehand. I was planning to use LibSQL inside Userland. Now I will take decision accordingly.

**Comment by supercomputer7** [comment]
Just to inform you, that the installed packages file is meant to be used by the work-in-progress PackageManager (we already have it in the tree!). So any solution here must be compatible with something we can use within the package manager - which means no external dependencies to be installed for such features in the guest OS.

**Comment by tbhaxor** [comment]
> PackageManager

If you are working on it, shouldn't we collab? Or whosoever is working.

**Comment by tbhaxor** [comment]
_update_ will work on it with fresh approach and include updates to package manager as well

**Pull request closed without merging**
