### PR TITLE
Ports: Fix networking for OpenTTD

### PR DESCRIPTION
**Pull request by gunnarbeutner**
OpenTTD incorrectly only checks for `EWOULDBLOCK` while it _should_ also check for `EAGAIN`. With this patch applied joining network games works.

The game calls `gettimeofday()` so many times per second that the game becomes unusable after joining a reasonably active network game. So I've patched that out for now.

### CODE REVIEW

**Comment by ccapitalK** [comment]
Since this is a general posix compatibility issue on OpenTTD's side, I believe we should submit a patch upstream to fix this. Do you want to create the upstream patch, or should I?

**Comment by awesomekling** [comment]
How about an alternate solution:
```cpp
#define EWOULDBLOCK EAGAIN
```

That `gettimeofday()` hack is unfortunate. The best fix would be #5312 but we can do this in the meantime.

**Comment by gunnarbeutner** [comment]
Defining `EWOULDBLOCK` like that makes perfect sense. Apparently that's also how eglibc and newlib do it. I'll update the PR in a bit. :+1:

**Comment by gunnarbeutner** [comment]
> Since this is a general posix compatibility issue on OpenTTD's side, I believe we should submit a patch upstream to fix this. Do you want to create the upstream patch, or should I?
> 
> Note: I believe we'd still need to merge this commit if we do decide to upstream it, since we'd need to wait until OpenTTD's next release anyway.

Yeah, technically this is a bug. Feel free to upstream the patch.

**Comment by ccapitalK** [comment]
> > Since this is a general posix compatibility issue on OpenTTD's side, I believe we should submit a patch upstream to fix this. Do you want to create the upstream patch, or should I?
> > Note: I believe we'd still need to merge this commit if we do decide to upstream it, since we'd need to wait until OpenTTD's next release anyway.
> 
> Yeah, technically this is a bug. Feel free to upstream the patch.

Reported upstream https://github.com/OpenTTD/OpenTTD/pull/9142

**Comment by gunnarbeutner** [comment]
Awesome, thank you!

**Comment by TrueBrain** [comment]
Tnx for the upstream @ccapitalK , always appreciated!

Something I am curious about, and I have no clue if this is the place to ask: OpenTTD compiles and runs on many OSes and in 17 years that line of code exists, this has never been mentioned as a problem. So that makes me very curious to what is going on :D To be clear, POSIX clearly defines both should be expected, so a fix for that surely is the least we can do :) But it does make me curious why serenity doesn't map `EWOULDBLOCK` to `EAGAIN`. I would also expect this to be an issue for many more applications, as I would expect many would silently assume all OSes are just mapping those two to the same value :D
Very specifically, I wonder if serenity just always fires `EGAIN` and never `EWOULDBLOCK` (that it just picked either of the two values), or that it can fire both depending on some internal situation? As I can imagine a simple fix is an `#ifdef` that makes sure those two values are the same in one of our headers, similar to what @awesomekling suggested.
Sorry, long story, but these problems are fun, so it sparkles my curiosity a lot :)

Regarding the `gettimeofday()`, now that is interesting :) We have had reports that the framerate measuring tool can make the game slow in certain situations, but we never been able to pin it down. You might be on to something here.
Makes me wonder .. we also use a lot of `steady_clock`; this isn't an issue? It is only `high_resolution_clock` that is triggering `gettimeofday`? (`std::chrono` is a bit of a shit-show between OSes, because the specs leave a lot of room for the implementation :D)

Either way, if you find any other issues / weirdness / etc, feel free to poke me or create a ticket on our GitHub project; we are happy to help :)

**Comment by gunnarbeutner** [comment]
I guess no particular thought was spent on whether `EAGAIN` and `EWOULDBLOCK` should be the same value internally. Someone probably just added them to `<errno.h>` and was happy things worked at all.

The `eglibc` documentation at https://www.gnu.org/software/libc/manual/html_node/Error-Codes.html says this about `EAGAIN`:

```
Portability Note: In many older Unix systems, this condition was indicated by EWOULDBLOCK,
which was a distinct error code different from EAGAIN. To make your program portable, you
should check for both codes and treat them the same.
```

As far as our kernel is concerned we never return `EWOULDBLOCK` and always use `EAGAIN`.

As for `gettimeofday`, well, `steady_clock` is calling that too, internally. I just commented out the most prominent call that came up in our profiler, because I read in a comment for `ottd_rdtsc` that those performance timers aren't that important. Our kernel doesn't allow `rdtsc` for user-mode programs, so I had to patch that out:

```patch
 /* rdtsc for all other *nix-en (hopefully). Use GCC syntax */
-#if (defined(__i386__) || defined(__x86_64__)) && !defined(RDTSC_AVAILABLE)
+#if (defined(__i386__) || defined(__x86_64__)) && !defined(__serenity__) && !defined(RDTSC_AVAILABLE)
 uint64 ottd_rdtsc()
```

Oh, btw, I think we ran into each other on IRC a few days ago when I tried to debug that SDL issue. Hello again!

**Comment by TrueBrain** [comment]
> 
> 
> I guess no particular thought was spent on whether `EAGAIN` and `EWOULDBLOCK` should be the same value internally. Someone probably just added them to `<errno.h>` and was happy things worked at all.
> 

That is fair :) I do wonder how many more applications no longer follow the portability note .. as said, it is really rare these days :) Doesn't make it less wrong on our side, ofc :)

> 
> As for `gettimeofday`, well, `steady_clock` is calling that too, internally. I just commented out the most prominent call that came up in our profiler, because I read in a comment for `ottd_rdtsc` that those performance timers aren't that important. Our kernel doesn't allow `rdtsc` for user-mode programs, so I had to patch that out:
> 

In general, the performance timers you mention are to show to users if their game is slow, whereabouts the problem might be. So we constantly measure the whole code to have that data ready when a user opens the window. So yeah, they are not important as such. Having a RDTSC reduces the pain somewhat, as those should be a lot less expensive to call. Either way, not really ideal, and one can wonder if we shouldn't start measuring only when the framerate window is open instead of always. Something to think about on our end :)

> 
> Oh, btw, I think we ran into each other on IRC a few days ago when I tried to debug that SDL issue. Hello again!

Hi :D

**Comment by gunnarbeutner** [comment]
There, removed the patch for the port and defined `EWOULDBLOCK` as an alias for `EAGAIN`.

**Pull request merged**
