### PR TITLE
Chess: Change cursor style when interacting with a valid piece

### PR DESCRIPTION
**Pull request by BrandonKi**
This is a pretty minor change but it was bothering me :^)

Changes the cursor style when hovering over or dragging a piece.

### CODE REVIEW

**Comment by elisee** [comment]
Just FYI, it's no big deal but I saw you opened and closed #7640  before opening this one. Next time you don't need to open a new pull request just to fix things in it, you can fix your branch / commits locally and then force-push it, it's common practice here. If you need help with rebasing / fixing up commits, the Discord has people willing to help out.

**Comment by BrandonKi** [comment]
Good to know! I’ll do that next time.

**Comment by gunnarbeutner** [comment]
One minor thing I've noticed is that this also changes the cursor for the AI player's pieces while the AI is considering its next move.

**Comment by gunnarbeutner** [comment]
Also, while hovering over the bottom window border the game crashes:

```
CrashDaemon(21:21): New coredump file: /tmp/coredump/Chess_39_1622502787
CrashDaemon(21:21): --- Backtrace for thread #0 (TID 39) ---
CrashDaemon(21:21): 0x2d28e1ce: [libsystem.so] syscall2 +0xe (syscall.cpp:25)
CrashDaemon(21:21): 0x4396a225: [libc.so] raise +0x25 (signal.cpp:21)
CrashDaemon(21:21): 0x43953eb6: [libc.so] abort +0x2a (stdlib.cpp:233)
CrashDaemon(21:21): 0x43954a1b: [libc.so] __assertion_failed +0xeb (Format.h:236)
CrashDaemon(21:21): 0x10b4e8ba: [libchess.so] Chess::Board::get_piece(Chess::Square const&) const [clone .localalias] +0x3a (Chess.cpp:331)
CrashDaemon(21:21): 0x777ad016: [/bin/Chess] ChessWidget::mousemove_event(GUI::MouseEvent&) [clone .localalias] +0x126 (ChessWidget.cpp:308)
CrashDaemon(21:21): 0x3422f84e: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x7e (Object.h:113)
CrashDaemon(21:21): 0x5779fbde: [libgui.so] GUI::Window::handle_mouse_event(GUI::MouseEvent&) +0x5fe (Window.cpp:359)
CrashDaemon(21:21): 0x577a16d9: [libgui.so] GUI::Window::event(Core::Event&) [clone .localalias] +0x39 (Window.cpp:544)
CrashDaemon(21:21): 0x3422f84e: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x7e (Object.h:113)
CrashDaemon(21:21): 0x34217618: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x4e8 (Atomic.h:246)
CrashDaemon(21:21): 0x34217e1b: [libcore.so] Core::EventLoop::exec() +0x5b (EventLoop.cpp:362)
CrashDaemon(21:21): 0x5768eb58: [libgui.so] GUI::Application::exec() +0x28 (Application.cpp:100)
CrashDaemon(21:21): 0x777a9c33: [/bin/Chess] main +0x1d23 (main.cpp:223)
CrashDaemon(21:21): 0x777a9e28: [/bin/Chess] _start +0x58 (crt0.cpp:39)
```

**Comment by BrandonKi** [comment]
I fixed both the issues mentioned.

**Pull request merged**
