### PR TITLE
Ports: Update serenity-theming to 3b35200

### PR DESCRIPTION
**Pull request by Xexxa**

### CODE REVIEW

**Comment by bgianfo** [comment]
@Xexxa linter is failing, I think you forgot to update the ports documentation file.

**Comment by Xexxa** [comment]
> @Xexxa linter is failing, I think you forgot to update the ports documentation file.

Yes, I totally forgot that. 🤦‍♀️ Thanks for mentioning it!

**Comment by Xexxa** [comment]
I know, I should merge the last two commits... Git is fighting with me, I'll try again later :-P

**Comment by Xexxa** [comment]
After multiple earlier triumphs against Git it won this fight.

Closing this one to continue with new adventures!

**Pull request closed without merging**
