### PR TITLE
Discord Theme Created

### PR DESCRIPTION
**Pull request by nanoproductions**
Created a Discord Based theme for Serenity. 

image

### CODE REVIEW

**Comment by jsdevv** [comment]
Looks nice!

**Comment by JonArcherII** [comment]
As mentioned by linusg in #2500, please squash your commits. Also, you don't need to recreate the pull request each time 😉

**Comment by nanoproductions** [comment]
I squashed my commits! Let me know for any further issues.

**Comment by linusg** [comment]
No... you did not. There are 56 commits in this PR, the goal should be one :)

**Comment by devsh0** [comment]
Checkout a video on how to squash commits in Git. You should find plenty on YouTube.

**Comment by nanoproductions** [comment]
I feel like I messed up the git repo with learning rebase and all, so I will restart my repo with a brand new fork, and submit the PR once that is done!

**Pull request closed without merging**
