### PR TITLE
AK+LibMain: Let Formatter format errors

### PR DESCRIPTION
**Pull request by juniorrantila**

### CODE REVIEW

**Comment by linusg** [comment]
Not doing it this way was a conscious decision. https://youtu.be/5PciKJW1rUc starting at 27:13

> Actually, we don't have to do that. We don't have to use this. We can also do better in main. It's nice to have a simple serialisation function, and then since we might want to get fancy here and dump out more metadata, let's not screw around with the simple format string serializer

**Comment by juniorrantila** [comment]
Oh, my bad. I think it's worth mentioning though that it's not only main that prints Error and you sometimes get things like `error: Error(errno=2)`, which isn't terribly descriptive. These messages would automatically become clearer with the change. Plus it provides the user with a way to prepend a message to a warning, akin to how one would use perror().

**Comment by linusg** [comment]
Do you have an example of where such an error is printed? FWIW, closing the PR doesn't mean that you did anything wrong, and we might be able to consolidate the error formatting for better messages across the board - the generic formatter might just not be the right place for it :)
It really depends on who is printing the message you mentioned and why.

**Comment by juniorrantila** [comment]
Oh, sorry. Totally missed the message. Have seen it used that way a few times just browsing around (usually when warning instead of fully erroring out). Last time was in cat, but the precise error message stated above I think occurred when I did something like `cat < non_existent_file`.

**Pull request closed without merging**
