### PR TITLE
Filemanager: Add Ctrl+A select all action

### PR DESCRIPTION
**Pull request by shannonbooth**
Work further towards #269

### CODE REVIEW

**Comment by awesomekling** [comment]
Ace :+1:

**Comment by bugaevc** [comment]
Again, this is wrong for all but flat models. You have to walk a model recursively.

**Comment by shannonbooth** [comment]
Ah thanks. Yeah honestly I wasnt even aware there was a hierachy. I can try fix this up when I have some free time, unless you want to 🙂

**Comment by bugaevc** [comment]
This is actually interesting: what should a "flat" view do, should it select all the items even if it cannot display most of them, or only the ones that are visible? I'd say the latter.

So maybe this doesn't belong in `GAbstractView` then.

**Comment by shannonbooth** [comment]
Personally I think I would normally expect all items to be selected, even if some are not visible. That is the typical behaviour for filemanagers where there lots of files that can't all fit on the screen.

Maybe it would make sense for certain view types to override that behaviour though...

**Comment by bugaevc** [comment]
I don't mean visible as in "scrolled into view", I mean visible as in — a `GItemView`, unlike a `GTreeView` or a `GColumnsView`, can only display a single "flat slice" of a model, not the full hierarchy. All the other indexes (of nested files and folders, in case of `GFileSystemModel`) are there, but flat views essentially ignore them.

The complication is `GAbstractView` doesn't know (and shouldn't know) if it's a flat or a hierarchical view.

**Comment by shannonbooth** [comment]
Oh I see. It seems I need to spend a bit more time hacking on this all to understand it more 🙂

**Pull request merged**
