### PR TITLE
Optimized image files

### PR DESCRIPTION
**Pull request by tiagofilipesilva**
This PR is about reducing the binary size of images without losing quality.

To upload yet:

- [ ] /Base/res/icons/*

### CODE REVIEW

**Comment by awesomekling** [comment]
Please don't do this. This is not worth adding bloat to the git history

**Comment by linusg** [comment]
It also does not work. The emoji picker crashes upon opening, for example.

<details>
<summary>Crash</summary>

```
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) +181
0xdeadc0de  Kernel::Scheduler::pick_next() +1952
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() +125
0xdeadc0de  Kernel::Thread::die_if_needed() +157
0xdeadc0de  syscall_handler +1414
0xdeadc0de  syscall_asm_entry +49
0x08121951  raise +22
0x080480bd  abort +13
0x0811cd66  tolower +0
0x080f9e58  Gfx::unfilter(Gfx::PNGLoadingContext&) +120
0x080fba19  Gfx::decode_png_bitmap(Gfx::PNGLoadingContext&) +676
0x080fbb3f  Gfx::load_png_impl(unsigned char const*, unsigned long) +58
0x080fbba7  Gfx::load_png(AK::StringView const&) +58
0x080e158e  Gfx::Bitmap::load_from_file(AK::StringView const&) +168
0x08101a79  Gfx::Emoji::emoji_for_code_point(unsigned int) +183
0x080f3932  Gfx::Painter::draw_text_line(Gfx::Rect<int> const&, AK::Utf32View const&, Gfx::Font const&, Gfx::TextAlignment, Gfx::Color, Gfx::TextElision) +194
0x080f4244  Gfx::Painter::draw_text(Gfx::Rect<int> const&, AK::Utf32View const&, Gfx::Font const&, Gfx::TextAlignment, Gfx::Color, Gfx::TextElision) +1060
0x080f4449  Gfx::Painter::draw_text(Gfx::Rect<int> const&, AK::Utf32View const&, Gfx::TextAlignment, Gfx::Color, Gfx::TextElision) +73
0x08089ab6  GUI::TextEditor::paint_event(GUI::PaintEvent&) +3370
0x0808e381  GUI::Widget::handle_paint_event(GUI::PaintEvent&) +171
0x0811a22e  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
0x0808e534  GUI::Widget::handle_paint_event(GUI::PaintEvent&) +606
0x0811a22e  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
0x0808e534  GUI::Widget::handle_paint_event(GUI::PaintEvent&) +606
0x0811a22e  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
0x08095524  GUI::Window::handle_multi_paint_event(GUI::MultiPaintEvent&) [clone .part.0] +794
0x0811a22e  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
0x08112b0c  Core::EventLoop::pump(Core::EventLoop::WaitMode) +308
0x08112c8b  Core::EventLoop::exec() +43
0x080487e4  main +985
0x08049b0e  _start +94
```

</details>

**Comment by tiagofilipesilva** [comment]
@awesomekling  I'm not putting bloat, it's actually the opposite. This is not a hackoctober stunt or whatever is going on.

@linusg You're not complying with either PNG or DEFLATE specifications, hence the crash.

**Comment by awesomekling** [comment]
This *is* bloat. When you commit this, the git repository will still contain the old versions as well as the new versions, increasing the size of the history forever.
Also, the fact that you haven't even tested it before opening a PR is not nice.

**Comment by tiagofilipesilva** [comment]
@awesomekling 

Maybe my autism is getting the best of me but:

- you're angry because changing bitmaps increases the git history size?
  - That's normal, and will happen everytime someone changes a bitmap;
  - I didn't chose bitmaps over text vectorials for icons or wallpapers of this project, maybe this should be done when it reaches an HaikuOS-level;
- the files were tested in two operative systems (Windows and GNU/Linux), just not on Serenity because I can't virtualize for the time being; they are valid PNGs and I ran under the assumption that Serenity was able to parse _valid_ PNGs. There is some sort of test files for these image types. I will try to have a look if they are following the specifications or not and open a bug report later on.

**Comment by awesomekling** [comment]
Of course I’m not angry. I’m just telling you that replacing some PNGa with smaller ones does not achieve anything other than wasting megabytes of hard drive space for hundreds of people. The bitmaps are already in the repo, it’s no longer possible to reduce the amount of effective space they use.

Although it is not cool to submit PRs to a project without even testing the changes yourself. Please don’t do that.

**Pull request closed without merging**
