### PR TITLE
Base: Add some clock emoji

### PR DESCRIPTION
**Pull request by pingiun**
Added:

23F0: ⏰ E1.0 Alarm Clock
23F1: ⏱️ E1.0 Stopwatch
23F2: ⏲️ E1.0 Timer Clock

### CODE REVIEW

**Review by AtkinsSJ — CHANGES_REQUESTED** [review]
Welcome! These look good, but please optimise your images, they should be only a few hundred bytes each. From [here](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy):

> If you have images that go along with your code, run `optipng -strip all` on them to optimize and strip away useless metadata - this can reduce file size from multiple kilobytes to a couple hundred bytes.

**Comment by pingiun** [comment]
> `optipng -strip all`

This makes a lot of sense, optimized in cf5852ff647a7bb2defab65539a46912409566cc

**Review by AtkinsSJ — APPROVED** [review]

**Comment by AtkinsSJ** [comment]
Great! I'll just get our resident emoji expert to take a look. :^)

**Review by Xexxa — CHANGES_REQUESTED** [review]
U+23F0 Looks great!
U+23F1 This one has an empty column, make it 9x10 and remove the unneccessary padding.
U+23F2 The area inside the timer clock is transparent, is that on purpose? It can make it harder to recognize the emoji on different backgrounds...

The commit message should contain all the emoji, codepoint and names, see for example this PR: https://github.com/SerenityOS/serenity/pull/15735/commits

**Comment by Xexxa** [comment]
Ohh, I almost forgot, welcome to the project @pingiun! The emoji in this PR looks really good and we are always happy getting better emoji coverage in SerenityOS!

**Comment by pingiun** [comment]
> U+23F0 Looks great! U+23F1 This one has an empty column, make it 9x10 and remove the unneccessary padding. U+23F2 The area inside the timer clock is transparent, is that on purpose? It can make it harder to recognize the emoji on different backgrounds...
> 
> The commit message should contain all the emoji, codepoint and names, see for example this PR: https://github.com/SerenityOS/serenity/pull/15735/commits

Ty for the feedback, it should all be good now

**Comment by treuks** [comment]
I would recommend for you to make the frame around ⏱️ a bit darker because it's basically invisible in the light mode. You could also add a bit of a blue-ish hue to it if you want to.

**Comment by treuks** [comment]
sorry, meant the frame around ⏲️ 😅 the ⏱️ looks great like that too though

**Comment by treuks** [comment]
i think you forgot the legs

**Comment by pingiun** [comment]
> i think you forgot the legs

**Review by Xexxa — APPROVED** [review]
LGTM!

**Comment by treuks** [comment]
yep that looks good to me

**Comment by Xexxa** [comment]
> > i think you forgot the legs
> 
> You mean like this?

That works too! My timer clock is round so I didn't mind the previous design :^)

**Pull request merged**
