### PR TITLE
Chess: Make sure to kill ChessEngine process on exit

### LINKED ISSUE #17427: Chess: Closing the game window makes the ChessEngine process rapidly approaches 100% CPU
Pretty easy to reproduce:

- Open the Chess game
- Select the Engine as your opponent
- Close the game

It doesn't take more than 5 seconds for the Engine to consume all of the CPU.

I know it is probably an easy fix - missing deconstructor maybe - but I didn't found the correct place to fix it just yet.

image

EDIT:

Using the profiler, it seems that it is spinning on wait_for_event

image

### PR DESCRIPTION
**Pull request by kemzeb**
Resolves #17427 using a workaround.

### CODE REVIEW

**Comment by kemzeb** [comment]
Just to quickly reiterate what I said in the issue, I think the problem has to do with `Engine`'s destructor not being called for some reason when the application exits. I have yet been able to find out why the destructor is never called and welcome any suggestions or changes to this PR!

**Comment by cristeigabriel** [comment]
From my short research, the engine destructor is never called on exit because the widget destructor is never automatically called, which is where engine destructor would be called.

**Comment by kemzeb** [comment]
That makes sense, so I assume the way it works is when the application exits it simply won't call on any destructors since the process will end anyways. 

If that's the case, I can't see any other option other than making the call `set_engine(nullptr)` so that we can kill the `ChessEngine` process before exiting the application.

**Comment by cristeigabriel** [comment]
There's some discussion in the Discord regarding potential approaches to this.

**Comment by ADKaster** [comment]
I don't think this workaround is sufficient. if you do this:
```sh
Chess & # start chess in the background
# in Chess, open up the engine prompt to start a ChessEngine process
kill -9 %1 # kill Chess with SIGKILL
```

Then neither of these workarounds will be called. As discussed on discord, the real solution is likely related to the actual file descriptors and responding to errors trying to read/write to them, for the UCI protocol.

**Comment by kemzeb** [comment]
Makes perfect sense to me. Since I don't believe this workaround will solve the issue well enough and better solutions are in the works, I will close this PR.

**Pull request closed without merging**
