### PR TITLE
AK: Remove unused 'address' variable from IPv4Address

### PR DESCRIPTION
**Pull request by ImanSeyed**
I kinda messed up the #17241 PR, so I had to open a new PR to fix this. Sorry for that D:

### CODE REVIEW

**Comment by timschumi** [comment]
What does this patch do? What is the "problem"? How does this fix that problem? All of those questions should be answered by the commit title and message, especially since this seems to be a _very_ weird issue.

**Comment by ImanSeyed** [comment]
> For example, let's say the format of IPv4 is like `A.B.C.D` and we got `c0 a8 14 01` from the network which is network ordered. If we want to get the `c0` (192), we have to use (`SubClass::D` \* 8) instead of (`SubClass::A` \* 8) because the `SubClass::A` is zero and to get `c0` we need to shift bits to right 24 times. But for little-endian current implementation is fine.
> 
> UPDATE:  
> According to [this](https://github.com/SerenityOS/serenity/blob/fef15becb238c1c4a15fb8eed90b8bac03ff03cc/AK/IPv4Address.h#L47) constructor, there is a bug because the `m_value` is obviously network ordered and the formatting is [reversed](https://github.com/SerenityOS/serenity/blob/fef15becb238c1c4a15fb8eed90b8bac03ff03cc/AK/IPv4Address.h#L70).

@timschumi I've already explained it in the previous PR. This issue only affects [to\_string()](https://github.com/SerenityOS/serenity/blob/fef15becb238c1c4a15fb8eed90b8bac03ff03cc/AK/IPv4Address.h#L59) and [to\_deprecated\_string()](https://github.com/SerenityOS/serenity/blob/fef15becb238c1c4a15fb8eed90b8bac03ff03cc/AK/IPv4Address.h#L68) functions. I just reversed the shifting and ANDing process. 

```
(c0XX'XXXX << 0) & FF00'00 => c0
(XXa8'XXXX << 8) & FF00'00 => a8
(XXXX'14XX << 16) & FF00'00 => 14
(XXXX'XX01 << 24) & FF00'00 => 01
```

**Comment by timschumi** [comment]
> According to [this](https://github.com/SerenityOS/serenity/blob/fef15becb238c1c4a15fb8eed90b8bac03ff03cc/AK/IPv4Address.h#L47) constructor, there is a bug because the m_value is obviously network ordered and the formatting is [reversed](https://github.com/SerenityOS/serenity/blob/fef15becb238c1c4a15fb8eed90b8bac03ff03cc/AK/IPv4Address.h#L70).

Looks fine to me. The parameter `address` is a `NetworkOrdered<u32>`, so it's in network byte order. The value (`m_data`) gets stored as a simple `u32` though, so it's in native byte order. The only thing that seems to be required beyond removing the dead code is actually making it little-/big-endian independent.

Also, the information that you pasted here should also be reflected in the description of the commit.

**Comment by ImanSeyed** [comment]
@timschumi current implementation does something like this to `c0 a8 14 01`:

```
A.B.C.D
(m_data >> bits_to_shift) & 0x0000'00FF;
(c0XX'XX01 >> 0) & 0x0000'00FF; // 01, which is wrong if you're looking for SubClass::A
(XXa8'1400 >> 8) & 0x0000'00FF; // 14, also wrong...
...
```

If we initialize the `m_data` using a `NetworkOrdered<u32>` value, the stored value in the `m_data` won't magically get `byteswap`\-ed, so I guess `m_data` is also big-endian.

**Comment by timschumi** [comment]
> the stored value in the m_data won't magically get byteswap-ed

Yes, [it will](https://github.com/SerenityOS/serenity/blob/master/AK/Endian.h#L133).

**Comment by ImanSeyed** [comment]
> > the stored value in the m_data won't magically get byteswap-ed
> 
> Yes, [it will](https://github.com/SerenityOS/serenity/blob/master/AK/Endian.h#L133).

I've seen this actually, but we expect the value to be big-endian if the parameter is NetworkOrdered, right? That's all I'm saying.

**Comment by ADKaster** [comment]
Seeing as the static assertions in the IPv4 tests for all supported platforms fire and fail to compile TestIPv4Address.cpp, I would suggest taking a look at the tests and running them locally to confirm that there is actually a bug here. If the bug is in the tests, fine, but your patch does not compile currently.

e.g. 
https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=26508&view=logs&j=2566f013-1391-5cbe-90ce-ae4ec398ae06&t=84932543-dadf-5f2f-567f-c183cdc02e79&l=2682

**Comment by GMTA** [comment]
@ImanSeyed you pass in `0xc0a81401`, which is LE, into the `NetworkOrdered<u32>` constructor, which converts it to BE.

If you were to read an `u32` from a network stream, wouldn't you get the LE value `0x0114a8c0` instead? At least, that's how I would expect `NetworkOrdered<u32>` to work.

**Comment by GMTA** [comment]
@ImanSeyed in your example, `addr1[0] == 192`. You pass in `0xc0'a8'14'01` (little-endian) to `NetworkOrdered<u32>`, but that doesn't have any effect for `IPv4Address` and gets stored unaltered in `IPv4Address::m_data`, which means that `addr2[0] == 1`.

If you were to read a big-endian value from a network stream and pass that into `NetworkOrdered<u32>`, that would need to be the value `0x01'14'a8'c0`.

**Comment by GMTA** [comment]
I'm not sure why `NetworkOrdered<u32>` is used at all in `IPv4Address` at the moment since both in the constructor and `.octet()` it's effectively ignored and it takes the original value instead.

**Comment by ImanSeyed** [comment]
> If you were to read a big-endian value from a network stream and pass that into `NetworkOrdered<u32>`, that would need to be the value `0x01'14'a8'c0`.

@GMTA Oh right... so I have to do something like this to store a network ordered variable:

```c++
// IP header from the network stream: 45 00 00 3c a8 c3 40 00 40 06 e8 a3 c0 a8 14 01 c0 a8 14 03
auto constexpr a = NetworkOrdered<u32>(0xc0'a8'14'01); // stores "0xc0'a8'14'01" inside a host ordered var
a(); // returns the BigEndian order
auto constexpr addr = IPv4Address(a); // host ordered value get passed to IPv4Address
```

So I guess the order is fine, but it could be simply a `u32`.

**Comment by ImanSeyed** [comment]
> If you were to read a big-endian value from a network stream and pass that into `NetworkOrdered<u32>`, that would need to be the value `0x01'14'a8'c0`.

@GMTA Oh right... so I have to do something like this to store a network ordered variable:

```c++
// IP header from the network stream: 45 00 00 3c a8 c3 40 00 40 06 e8 a3 c0 a8 14 01 c0 a8 14 03
auto constexpr a = NetworkOrdered<u32>(0xc0'a8'14'01); // stores "0xc0'a8'14'01" inside a host ordered var
a(); // returns the BigEndian order
auto constexpr addr = IPv4Address(a); // host ordered value get passed to IPv4Address
```

So I guess the order is fine, but it could be simply a `u32`.

**Comment by GMTA** [comment]
@ImanSeyed
> so I have to do something like this

No, I'm saying that if you have `c0 a8 14 01` in your network stream, that is the same as `0x0114a8c0` in little-endian host format. So that's what you would write in your code _before_ passing it in to `NetworkOrdered<u32>`.

**Comment by ImanSeyed** [comment]
> No, I'm saying that if you have `c0 a8 14 01` in your network stream, that is the same as `0x0114a8c0` in little-endian host format. So that's what you would write in your code _before_ passing it in to `NetworkOrdered<u32>`.

@GMTA Okay. So I guess I only need to delete the unused line. What about the NetworkOrdered\<u32> constructor though? Should I change the parameter type to `u32` or just leave it there?

**Comment by GMTA** [comment]
@ImanSeyed 
> So I guess I only need to delete the unused line
Sure, that would be fine with me!
> What about the NetworkOrdered<u32> constructor though?
The only reason I can think of now for why we have that, is to indicate to the user that they need to think about what kind of `u32` they supply to the constructor. If it was `u32`, you might be left guessing whether it's little or big endian. But since it's `NetworkOrdered<u32>`, you know you need to take a little-endian value and put that into a `NetworkOrdered<u32>`.

**Pull request merged**
