### PR TITLE
Meta: Make image building use doas instead of sudo when available

### PR DESCRIPTION
**Pull request by brandon-doornbos**
If I have to change anything else, or if there is a better way of doing this, do tell.
This is my first real pull request :^).

### CODE REVIEW

**Comment by brandon-doornbos** [comment]
Don't mind all the force-pushing, I am still not extremely proficient in Git and my pre-commit reset and therefore did not run. Should be good now.

**Comment by mhermier** [comment]
If `doas` is accepted as an alternative, maybe the required change should be move to a dedicated script responsible for privilege escalation (by direct call or `source`).

**Comment by brandon-doornbos** [comment]
That's actually pretty logical now that I think about it, I'll see if I can make something.

**Comment by DolphinChips** [comment]
Tested this on NixOS 21.11, works just fine!

**Review by linusg — COMMENTED** [review]
Typo in commit message: `seperate`

**Comment by brandon-doornbos** [comment]
Thank you @DolphinChips for checking and @linusg for reviewing :^). Is there a better way to fix the typo than rewording via rebase and then force-pushing?

**Comment by DolphinChips** [comment]
> Is there a better way to fix the typo than rewording via rebase and then force-pushing?

I'm not aware such way (nor there's anything wrong with force-pushing to personal branches :D)

**Comment by brandon-doornbos** [comment]
The typo is fixed, the commit linter check is failing on multiple other pulls because of some circular dependency or something. If the other checks succeed this pull should now be good.

**Comment by bgianfo** [comment]
@brandon-doornbos can you fix the merge conflict please?

**Comment by brandon-doornbos** [comment]
I did not see the conflict until now sorry, I'll fix it tomorrow.

**Comment by brandon-doornbos** [comment]
@bgianfo would opening a new pull request on the current master branch be a better idea, since I cannot integrate doas support and keep fuse2fs working currently?

**Comment by bgianfo** [comment]
> @bgianfo would opening a new pull request on the current master branch be a better idea, since I cannot integrate doas support and keep fuse2fs working currently?

What ever works for you, it's generally better to keep working in the same PR though.

**Comment by brandon-doornbos** [comment]
This pull seems moot to me. Since we can now make images without needing root in the first place.

**Pull request closed without merging**
