### PR TITLE
Kernel: Add more entries to the list of valid E1000E device ids

### PR DESCRIPTION
**Pull request by stelar7**

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
That would break booting my laptop (i.e. because something's wrong with `E1000ENetworkAdapter` for that particular adapter).

**Comment by stelar7** [comment]
> That would break booting my laptop (i.e. because something's wrong with `E1000ENetworkAdapter` for that particular adapter).

Maybe there should be a distinction between valid and tested/working devices?

**Comment by awesomekling** [comment]
> > That would break booting my laptop (i.e. because something's wrong with `E1000ENetworkAdapter` for that particular adapter).
> 
> Maybe there should be a distinction between valid and tested/working devices?

Yeah, just split the list into whitelisted/blacklisted ID's or something like that.
Then we can keep the full list while not breaking boot for known-non-working cards.

**Comment by stelar7** [comment]
> Yeah, just split the list into whitelisted/blacklisted ID's or something like that.
> Then we can keep the full list while not breaking boot for known-non-working cards.

Split so that the non-verified cards return false now :)

**Pull request merged**
