### PR TITLE
LibWeb+WebContent: Move paint recording init into BrowsingContext

### PR DESCRIPTION
**Pull request by kalenikaliaksandr**
This refactoring makes WebContent less aware of LibWeb internals. The code that initializes paint recording commands now resides in `BrowsingContext::paint()`. Additionally, we no longer need to reuse PaintContext across iframes, allowing us to avoid saving and restoring its state before recursing into an iframe.

### CODE REVIEW

**Comment by kalenikaliaksandr** [comment]
Ref-test is not a regression. That is how changed it looked before: 
css-background-repeat-ref

**Comment by awesomekling** [comment]
Hmm, why browsing context and not navigable?

**Comment by awesomekling** [comment]
[HTML spec](https://html.spec.whatwg.org/multipage/document-sequences.html#infrastructure-for-sequences-of-documents) says navigables are user-facing and browsing contexts are developer-facing.

It seems to me that painting belongs more in the category of user-facing concepts. :)

**Comment by kalenikaliaksandr** [comment]
agreed. I moved paint() method to navigable.

**Pull request merged**
