### PR TITLE
Base: Add new fixed-width font Stharia

### PR DESCRIPTION
**Pull request by djwisdom**
New fixed-width font SthariaRegular10 for consideration.

image

### CODE REVIEW

**Review by Xexxa — CHANGES_REQUESTED** [review]
Taste is highly subjective but I get the "who would use this font and why?"-feeling on this one.

I really a lot of the glyphs in this font but in total it feels very uneven, chaotic and experimental.

Can you provide some information on the thinking behind this font or example of a similar font out in the wild?

**Comment by djwisdom** [comment]
> 

Indeed it is highly subjective, the primary reason is that the font name "Stharia" is specifically requested of me. As to the 'experimental look'... it is as you say, I just go with the flow when I started making the glyphs. The only guiding condition was for the glyphs to base it's overall form off of the number zero with a diagonal slash. The diagonal slash is very evident on the numbers 6, 9 and 8. As for the thick vertical lines, my font has dimension of 8x10, so since the middle is even number, in order to maintain balance, the center will need to be thick.  Overall, this is me showing to my special someone that I adhered to her request. That is all. Approved or not approved, at least I made her happy.

**Review by Xexxa — COMMENTED** [review]
After DM with djwisdom I can see the through line behind some of the design choices, so I'm changing to a neutral review. The mixture of different styles and bold/regular/italic is still very unappealing to me personally, but someone else might like it. **There is no tech issues with this PR**, it's just a matter of taste.

**Comment by djwisdom** [comment]
Closing this PR too in similar fashion with the separate PR Sobriety.

**Pull request closed without merging**
