### PR TITLE
jp: add variable indentation level and use stdin input by default

### PR DESCRIPTION
**Pull request by ngc6302h**
This PR was originally for a new utility, but upon realizing it was sort of duplicated, turned into extending an existing one.

Pass -i N where N is an integer to change the indentation to N spaces.

### CODE REVIEW

**Comment by bcoles** [comment]
This looks similar to the existing [jp](https://github.com/SerenityOS/serenity/blob/master/Userland/Utilities/jp.cpp) tool. Although `jp` does not accept stdin by default, instead requiring `cat /proc/all | jp /dev/stdin` and does not support customizable indentation.

**Comment by ngc6302h** [comment]
> This looks similar to the existing [jp](https://github.com/SerenityOS/serenity/blob/master/Userland/Utilities/jp.cpp) tool. Although `jp` does not accept stdin by default, instead requiring `cat /proc/all | jp /dev/stdin` and does not support customizable indentation.

Whoops, I didn't realize. What do you recommend I do now?

**Comment by bcoles** [comment]
> 
> 
> > This looks similar to the existing [jp](https://github.com/SerenityOS/serenity/blob/master/Userland/Utilities/jp.cpp) tool. Although `jp` does not accept stdin by default, instead requiring `cat /proc/all | jp /dev/stdin` and does not support customizable indentation.
> 
> Whoops, I didn't realize. What do you recommend I do now?

Perhaps augment `jp` to support `stdin` and add an indentation command line option?

**Comment by ngc6302h** [comment]
> > > This looks similar to the existing [jp](https://github.com/SerenityOS/serenity/blob/master/Userland/Utilities/jp.cpp) tool. Although `jp` does not accept stdin by default, instead requiring `cat /proc/all | jp /dev/stdin` and does not support customizable indentation.
> > 
> > 
> > Whoops, I didn't realize. What do you recommend I do now?
> 
> Perhaps augment `jp` to support `stdin` and add an indentation command line option?

Very well :)

**Pull request merged**
