### PR TITLE
Meta: Fix grammar s’s -> s’

### PR DESCRIPTION
**Pull request by filiphsandstrom**
Fixes a grammatical error that for some unexplainable reason bugged me :^)

### CODE REVIEW

**Comment by filiphsandstrom** [comment]
> Hello!
> 
> One or more of the commit messages in this PR do not match the SerenityOS [code submission policy](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md?rgh-link-date=2022-02-13T16%3A15%3A34Z#code-submission-policy), please check the `lint_commits` CI job for more details on which commits were flagged and why. Please do not close this PR and open another, instead modify your commit message(s) with [git commit --amend](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message) and force push those changes to update this PR.

Old habits die hard, still accidentally end my commits with "." heh.

**Comment by trflynn89** [comment]
Not a grammatical error: https://www.lexico.com/grammar/apostrophe
> With personal names that end in -s: add an apostrophe plus s when you would naturally pronounce an extra s if you said the word out loud

We would pronounce the extra s in this case, so "Linus's" is correct

**Comment by filiphsandstrom** [comment]
> Not a grammatical error: [lexico.com/grammar/apostrophe](https://www.lexico.com/grammar/apostrophe)
> 
> > With personal names that end in -s: add an apostrophe plus s when you would naturally pronounce an extra s if you said the word out loud
> 
> We would pronounce the extra s in this case, so "Linus's" is correct

Isn't that just in British English though, or am I wrong on the internet here?

**Comment by filiphsandstrom** [comment]
> Not a grammatical error: [lexico.com/grammar/apostrophe](https://www.lexico.com/grammar/apostrophe)
> 
> > With personal names that end in -s: add an apostrophe plus s when you would naturally pronounce an extra s if you said the word out loud
> 
> We would pronounce the extra s in this case, so "Linus's" is correct

After a bit more research it turns out we're both right depending on which style you follow. So lets just leave it as-is :^)

**Pull request closed without merging**
