### PR TITLE
LibSyntax+Userland: Make LibSyntax not depend on LibGUI

### PR DESCRIPTION
**Pull request by alimpfard**
This moves some stuff around to make LibGUI depend on LibSyntax instead of the other way around, as not every application that wishes to do syntax highlighting is necessarily a LibGUI (or even a GUI) application.

### CODE REVIEW

**Comment by BertalanD** [comment]
Does this alone let us remove LibWebView's dependency on LibGUI on Lagom?

**Comment by alimpfard** [comment]
I assume so, I'm not sure what else LibWebView would need LibGUI for.

**Review by AtkinsSJ — APPROVED** [review]
Nice!

**Comment by ADKaster** [comment]
> Does this alone let us remove LibWebView's dependency on LibGUI on Lagom?

For LibWebView, yes. LibWeb, no. We still use GUI::MouseButton in MouseEvent/EventHandler and we still use Kernel/API/KeyCode.h for keyboard events.

**Review by trflynn89 — APPROVED** [review]
Nice! I didn't go through the moved code with a fine-toothed comb, but LGTM

**Review by BertalanD — APPROVED** [review]

**Pull request merged**
