### PR TITLE
Maps: Add massage_for_display to latitude and longitude when loading favorites

### PR DESCRIPTION
**Pull request by BrendanKelly84213**
This prevents a crash when attempting to add a favorite in Maps application

### CODE REVIEW

**Comment by DanShaders** [comment]
How do we end up with strings instead of doubles in that model?

**Comment by BrendanKelly84213** [comment]
> How do we end up with strings instead of doubles in that model?

 The model is a `JsonArrayModel`, `JsonArrayModel::data()` has this condition (JsonArrayModel.cpp 139):
 
 ```
 if (data->is_number())
   return data->serialized<StringBuilder>();
```

**Comment by bplaat** [comment]
This seems wrong or I don't understand my own code and LibGUI anymore haha

**Comment by DanShaders** [comment]
The crash is actually a regression since #22729, but that PR only highlighted the problem, the code was never correct in the first place :)

The high-level problem here is a mismatch in philosophy of `JsonValue` and `Variant`-like classes. `JsonValue` should (and now, is) hide what exact type it uses to store number, while `Variant` treats different arithmetic type as just different types and exposes that information in API. With that in mind, implicit conversion in the `JsonValue -> Variant` direction is never correct. I added serialization in the line you mentioned hoping nobody actually tries to roundtrip `JsonValue` using `Variant` but that's clearly not the case.

The proper fix here would be to not rely on JsonArrayModel display model role and use something else, but that's probably quite invasive. Therefore, an okaish solution is to add `massage_for_display` for latitude and longitude that look like this:
```cpp
[&](JsonObject const& object) {
    return object.get_double_with_precision_loss("latitude").value();
}
```

**Review by bplaat — APPROVED** [review]
Looks good to me, this fixes the bug LGTM

**Comment by AtkinsSJ** [comment]
The commit title no longer seems to reflect the change. But otherwise the code seems good to me.

**Comment by AtkinsSJ** [comment]
> > The commit title no longer seems to reflect the change. But otherwise the code seems good to me.
> 
> Should it have more detail? Was trying to fit inside character limit so I went pretty terse with it.

It says "Maps: Add massage_for_display for lat and long" but doesn't add anything named "massage_for_display".

**Comment by AtkinsSJ** [comment]
Ahhhh ok. Let's merge this then!

**Pull request merged**
