### PR TITLE
LibJIT: Add Barebones JIT library + simple BF JIT interpreter

### PR DESCRIPTION
**Pull request by ccapitalK**
The intention of this PR is to get the ball rolling on implementing a JIT. We are still a ways away from being able to do so in LibJS (we need a bytecode interpreter there before we can start JIT compiling), but there are a lot of other places where we could do JIT compilation. Examples are:

[ ] LibRegex
[ ] LibGL
[ ] LibWasm
[ ] UserspaceEmulator
[ ] Chess AI?
[ ] LibSQL

It's fairly barebones right now. I intend to refactor the x86 instruction encoding logic into LibX86, and then start working on a simple IR format/optimizer. The actual design is still up in the air, I want this to grow into a high quality generic JIT implementation that all SerenityOS components can use as needed, but this will probably need some clever design decisions to ensure it doesn't get too tightly coupled to one specific use case. Feel free to bikeshed on how this should be designed.

I've also added a simple interpreter and JIT compiler for the brainfuck language, as a simple hello world program for this library.

### CODE REVIEW

**Comment by Hendiadyoin1** [comment]
as a small optimization, it might be usefull to bind the currenct cell to a specific register (like eax) and only access the memory when moving the cell or doing IO

also how difficult would a lookahead for additions and subtractions be?

**Comment by awesomekling** [comment]
At first glance, I was reluctant to support JIT'ing at all, but after thinking about it some more, I think we're in a good position here to build something quite good, *if we find a strong, reusable architecture*. Unlike most other JIT's, this would indeed be a system-wide framework that anyone with a reasonable use-case could plug into.

If you want to build a JIT framework for SerenityOS, I suggest taking an approach similar to the `MacroAssembler` from JavaScriptCore: https://github.com/WebKit/WebKit/tree/main/Source/JavaScriptCore/assembler

By building a good macro assembler architecture with abstract general-purpose registers, we can even write target-agnostic codegen logic. Ideally, users of the JIT should not have to think about what the target CPU is. :)

**Comment by ccapitalK** [comment]
So the BF JIT is basically complete, I've abstracted most of the x86-specific code gen stuff into LibJIT. Unfortunately, I don't think it is possible to make the assembler class completely platform-agnostic. I've tried to make the assembler assume as little about the registers as possible (so that we could ideally just treat them as reg0, reg1, etc.), but there are still dependencies. The main issues are platform dependencies related to registers. For instance, in x86 the 32 bit register `eax` aliases with the 8 bit `al` and `ah` registers, the roughly equivalent register on arm `W0` aliases with only one 8 bit register `B0`. Small things like that make it hard to determine what a good cross-platform API would be for this case, since that means that if you have code that both manipulates 8 bit and 32 bit values, it's hard to keep track of which instructions clobber which registers without depending on platform details. I've looked into how WebKit tries to solve this problem, and it appears to be a fairly leaky abstraction in that regard :( . 

Also, I've decided to just write down the instruction encodings directly in LibJIT, instead of trying to implement instruction encoding in LibX86 (which turned into an epic yak-shave). Anyway, I feel like the next step (implementing all of these instructions) could be parallelized between different people and different use cases, I would probably end up writing a lot of poorly tested incorrect code If I tried to implement them all from the spec. :sunglasses: What are your thoughts on the general architecture and what are your thoughts on how the security aspects should be handled? I was thinking we should probably introduce a new pledge, and IIRC there was some discussion on separating the JIT code generation into a separate process from the actual code execution.

**Comment by Hendiadyoin1** [comment]
> there was some discussion on separating the JIT code generation into a separate process from the actual code execution.

This sound's a bit ambigous
Meant by this is, that, for example WASM-JITs, should be heavily sandboxed, which is best done in another process with only the data it needs, and nothing else (and mabye an IPC invoke_wasm_function handle).

Also you should turn off your relaxations of the mapping security, and do a workaround instead, like writing a file in /tmp/jit and mapping it then as executable, or loading it into another process (as discussed via discord)

**Pull request closed without merging**
