### PR TITLE
LibJSGCVerifier: Support building & running with the Lagom build

### LINKED ISSUE #23832: LibJSGCVerifier: Make it possible to run the verifier on a Lagom build
At the moment, the LibJSGCVerifier needs an x86_64clang build to run.

We need to be able to run it on a standalone Lagom build as well.

## Funding

- We're currently trying [Polar.sh](https://polar.sh/SerenityOS) where you can help fund the work on this issue.
- Contributor(s) receive the funding once the issue is completed & confirmed.

<a href="https://polar.sh/SerenityOS/serenity/issues/23832">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/SerenityOS/serenity/issues/23832/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by IdanHo**
Resolves #23832.

### CODE REVIEW

**Comment by awesomekling** [comment]
Tried this locally, seems like every file errors like this:
```
/usr/include/unistd.h:226:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^~~~~~~~~~
1 error generated.
```

**Comment by IdanHo** [comment]
@awesomekling that means it picked up your Serenity toolchain clang, not your lagom clang. Did you build with LAGOM_BUILD=ON?

**Comment by awesomekling** [comment]
> @awesomekling that means it picked up your Serenity toolchain clang, not your lagom clang. Did you build with LAGOM_BUILD=ON?

I only have a lagom build on this machine! Built with `Meta/serenity.sh build lagom ladybird`

**Comment by IdanHo** [comment]
Right, I mean building the LibJSGCVerifier itself (see the updated README)

**Comment by awesomekling** [comment]
> Right, I mean building the LibJSGCVerifier itself (see the updated README)

Oh duh! My bad. This works beautifully :sweat_smile:

**Pull request merged**
