### PR TITLE
ClangPlugins: Invert lambda capture mechanism; Emit errors instead of warning

### PR DESCRIPTION
**Pull request by mattco98**
This also removes the `IGNORE_USE_IN_ESCAPING_LAMBDA` annotation in favor of a `DOES_NOT_OUTLIVE_CAPTURES` annotation that is applied directly to the lambda instead of to each individual capture declaration.

I also added a FixIt hint for one of the errors:
image_skip_no pdf

Soft depends on #24350, as otherwise those issues will be flagged as errors and fail the build, but that _technically_ doesn't matter until this is integrated in CI

### CODE REVIEW

**Comment by mattco98** [comment]
Looks like clang-format can't handle the C++23 lambda attributes if they're macro identifiers unfortunately, so that conversion will have to wait

**Comment by nico** [comment]
> Looks like clang-format can't handle the C++23 lambda attributes if they're macro identifiers unfortunately, so that change will have to wait

I _just_ filed https://github.com/llvm/llvm-project/issues/92657 -- is this that same bug?

**Comment by mattco98** [comment]
> I just filed https://github.com/llvm/llvm-project/issues/92657 -- is this that same bug?

Maybe? Depends on what that annotation is applied to. This bug is related to the annotations introduced in [P2173R1](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2173r1.pdf), which apply directly to the `operator()` of the lambda, like in this snippet:

```c++
#define ATTR [[clang::annotate("attr")]]
void foo()
{
    auto lambda = [] ATTR (int& arg) {};
}
```

I know annotations that appear after the return type apply to that type, but I'm not sure about annotations that are applied before the return type. If this is the same thing then I'll just use the style you used instead (though what does the annotation apply to if there is no return clause at all?)

**Comment by mattco98** [comment]
ref: llvm/llvm-project#92661

**Review by ADKaster — APPROVED** [review]

**Pull request merged**
