### PR TITLE
WindowServer: AppletManager.

### PR DESCRIPTION
**Pull request by asliturk**
Move applet logic to AppletManager class. Remove applet code from MenuManager.
With new AppletManager applet order is configurable via WindowManager.ini file.

### CODE REVIEW

**Comment by bugaevc** [comment]
Someday Andreas is gonna ban me for nitpicking on commit messages, but until then:

Please fix commit messages to follow the common style. E.g. "Clock.MenuApplet: Add window title"

**Comment by bugaevc** [comment]
Note: there should be no period at the end of the first line of the commit messages :slightly_smiling_face:

Wouldn't the `[Applet]` category better be named `[Applets]`?

**Comment by asliturk** [comment]
> Note: there should be no period at the end of the first line of the commit messages slightly_smiling_face
> 
> Wouldn't the `[Applet]` category better be named `[Applets]`?

There is no plural usage for group name in any INI file. I am not sure :confused:

**Comment by awesomekling** [comment]
Thank you for fixing this silly but annoying issue! :)

**Pull request merged**
