### PR TITLE
PixelPaint: Make image cropping actions work with multiple layers

### PR DESCRIPTION
**Pull request by tcl3**
This PR modifies the behavior of the "Crop Image to Selection" and "Crop Image to Content" actions, so that they work when an image has multiple disjoint layers that don't cover the entire image.

Previously these actions wouldn't work if the selection did not encompass all the layers in the image.

NB: Crop Image to Selection will now delete layers that fall entirely outside of the current selection. This matches how GIMP behaves (I also tried this in Photoshop, which doesn't delete these layers, but resizes them to 0x0.)

Video:

https://user-images.githubusercontent.com/2817754/221109059-18d80d54-e27d-4783-a664-dc4bbd332826.mp4

### CODE REVIEW

**Comment by tcl3** [comment]
I've just had another look at this; I've not really shown what the bug is that I'm fixing.

Here's how "Crop to Selection" behaves without the changes from this PR:

https://user-images.githubusercontent.com/2817754/223185383-d810bdd0-3d35-42ee-9b20-2e87485c5a37.mp4

(The error message shown here should display an error code. I have a fix for this, but I believe it is outside the scope of this PR)

**Comment by tcl3** [comment]
Latest push resolves `NonnullRefPtrVector` conflicts.

**Comment by GMTA** [comment]
https://user-images.githubusercontent.com/3210731/227746872-c68a7591-e2b4-457e-8585-836ddd938e3c.mp4

**Comment by tcl3** [comment]
Interestingly, rebasing this onto master causes an error message to be shown rather than crashing. I'm not sure what's causing this change in behavior :shrug: 

As mentioned in the PR referenced above. I think the best way forward is to constrain selections to be within the canvas. I'm going to set this to draft while I make a PR that does that.

Would probably be a good idea to add a few `VERIFY()`s after the above change is made too.

**Comment by tcl3** [comment]
These changes now depend on #17802

**Review by GMTA — APPROVED** [review]

**Pull request merged**
