### PR TITLE
LibWebView+Ladybird: Centralize search engines in LibWebView, implement search in AppKit chrome

### PR DESCRIPTION
**Pull request by trflynn89**
https://github.com/SerenityOS/serenity/assets/5600524/3eb58557-0f22-4463-8632-b36d7bd00c9b

And while in the area, some visual improvements to the Qt settings dialog.

Before:
before

After:
after

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Losing the config-file for search engines is a bit sad.

**Comment by trflynn89** [comment]
> Losing the config-file for search engines is a bit sad.

I was thinking about that, but A) the ability to change that file wasn't used (it's read-only in the settings right now), and B) we can set custom search engines through settings (at least on Serenity, I don't think other chromes implemented this yet). So my thinking is: default search engines are hard-coded so they can be used by everyone, and each chrome can add the ability to add more through their settings.

**Comment by AtkinsSJ** [comment]
That's fair enough. And if/when we do get a full "configure search engines" thing, we can just use these standard ones to populate the list initially, so you'd still want it centralised.

**Review by AtkinsSJ — APPROVED** [review]
One minor suggestion, which you can feel free to ignore. Otherwise all good!

**Pull request merged**
