### PR TITLE
Kernel: Improve the unveil() system call

### PR DESCRIPTION
**Pull request by MaxWipfli**
This PR fixes quite a lot of bugs related to the `unveil` system call.

The following four commits all fix bugs related to unveiling `/` (the root directory). They mostly have to do with the fact that there is always a node for `/`, because it's the root node of the `UnveilNode` trie:
* Use LexicalPath to avoid two consecutive slashes in unveil path.
* Change unveil state to dropped even when node already exists.
* Don't assume there are no nodes if m_unveiled_paths.is_empty().
* Properly reset m_unveiled_paths on execve().

The other commits fix other bugs in the `unveil` implementation. The relevant bugs are described in the commit descriptions.

I also extended an clarified the `unveil(2)` man page.

Discussion in Discord has resulted in the decision to allow unveiling subfolders of already unveiled folders with any permissions as long as `unveil(nullptr, nullptr)` hasn't been called. Regardless of that, there was a bug there (fixed in dedd46a8d5d01ab83f1e7671c83100c860779b79), because if this was possible or not would depend on what other paths have already been unveiled. If you think this should not be allowed, I am happy to discuss. :^)

### CODE REVIEW

**Comment by bgianfo** [comment]
It would be awesome if we could add regression tests for some/all of the bugs you found. 
There's already a small test harness for unveil here `Tests/Kernel/TestKernelUnveil.cpp`, we could probably enhance the tests to be more fine grained if we utilized the `EXPECT_CRASH(...)` facility in `LibTest`.

**Comment by MaxWipfli** [comment]
> It would be awesome if we could add regression tests for some/all of the bugs you found.
> There's already a small test harness for unveil here `Tests/Kernel/TestKernelUnveil.cpp`, we could probably enhance the tests to be more fine grained if we utilized the `EXPECT_CRASH(...)` facility in `LibTest`.

Good idea, will look into it (hopefully tomorrow).

**Comment by MaxWipfli** [comment]
> Good idea, will look into it (hopefully tomorrow).

So it turns out writing tests for the bugs I found is really hard (especially since a few of them require an `execve()` to even have an effect). The main problem is that you cannot reset the veil from userspace (for obvious reasons). You would have to write a custom test runner which then uses `execve` to spawn different tests, as this is the only way to reset the veil. I don't really know how to do this, so I think the current tests have to suffice for the moment.

**Comment by bgianfo** [comment]
>  You would have to write a custom test runner which then uses `execve` to spawn different tests, as this is the only way to reset the veil. I don't really know how to do this, so I think the current tests have to suffice for the moment.

The `EXPECT_CRASH(...)` stuff runs in a sub process... so I think you could use that / extend it for your needs, but sure I understand yak shaving on tests isn't the most exciting thing in the world. 😄 No pressure.

**Pull request merged**
