### PR TITLE
Base: Optimize icons, graphics, themes and wallpapers

### PR DESCRIPTION
**Pull request by cubiclove**
It turns out many `.png` files hadn't been run through optiPNG. Now they have and there's some nice savings!

### CODE REVIEW

**Comment by nico** [comment]
I tried that a while ago in #15697; feedback on Discord was "nah".

**Comment by cubiclove** [comment]
Oh right, why was that?

**Comment by AtkinsSJ** [comment]
To summarise a long discussion: Replacing an image with an identical optimised one only adds to the overall repo size, because git is bad at binary files. So, if the goal is to reduce repo size, it's better to wait until an image is modified and then make sure that replacement is optimised.

I think that's where the CI check for optipng came from: Ensure new/modified images are optimised, but ignore existing ones.

Personally I would tend towards the "optimise them all anyway" side, but it does make sense not to.

**Comment by cubiclove** [comment]
That makes sense. I’ll close the PR.

**Pull request closed without merging**
