### PR TITLE
Meta: Add python related build files to .gitignore

### PR DESCRIPTION
**Pull request by aduerig**
On master after running `./Meta/serenity.sh run lagom ladybird` on linux:
```
git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Ladybird/Qt/ladybird_rc.py
	Meta/__pycache__/
```

### CODE REVIEW

**Comment by ADKaster** [comment]
What distro and Qt version are you using that generates those files? I don't see those at all on Ubuntu 22.04 with Qt 6.2.4 from the ubuntu apt repos.

**Comment by aduerig** [comment]
> What distro and Qt version are you using that generates those files? I don't see those at all on Ubuntu 22.04 with Qt 6.2.4 from the ubuntu apt repos.

Arch Linux, up to date. Interestingly the python file says in the header:
```
Created by: The Resource Compiler for PyQt5 (Qt v5.15.2)
```

I jammed a CMakeLists.txt print after:
https://github.com/SerenityOS/serenity/blob/e02a4f518171488a50ed1c4c90472bf605a920c0/Ladybird/CMakeLists.txt#L98
`message(STATUS "Qt6 found at ${Qt6_DIR} and version is ${Qt6_VERSION}")`
Which prints: `Qt6 found at /usr/lib/cmake/Qt6 and version is 6.6.0`

**Comment by ADKaster** [comment]
Curious. On my platform, the only qrc generated file is the one here:

```
serenity$ head -n10 Build/lagom/Ladybird/ladybird_autogen/4DVC4UZSMN/qrc_ladybird.cpp 
/****************************************************************************
** Resource object code
**
** Created by: The Resource Compiler for Qt version 6.2.4
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

static const unsigned char qt_resource_data[] = {
  // /home/andrew/serenity/Ladybird/Icons/back.tvg
```
Which was created by the Qt Resource Compiler from `/usr/lib/qt6/libexec/rcc`

This feels like a `$PATH` issue? Perhaps even a reportable issue to Qt or CMake... That being said, if this is the default behavior when installing a fresh set of qt6 development tools on Arch, then we can go ahead and merge this in to prevent any weird surprises.

**Comment by aduerig** [comment]
I'll verify my path and python env is correct. Thinking about it more it's possible I have multiple versioned Qt libraries installed for my global python environment, though I would hope that's fine anyway and it wouldn't use the wrong version.

I'll reopen the PR if I still have them after doing a tiny bit more digging.

**Pull request closed without merging**
