### PR TITLE
Reorder sections in BuildInstructions.md

### PR DESCRIPTION
**Pull request by trustable-code**
Old order: 
- Debian / Ubuntu
- Windows
- Arch Linux / Manjaro

New order: 
- Debian / Ubuntu
- Arch Linux / Manjaro
- Windows

### CODE REVIEW

**Comment by Hendiadyoin1** [comment]
Any greater reason behind this?

**Comment by trustable-code** [comment]
I just found it weird to have Linux - Windows - Linux.

**Comment by awesomekling** [comment]
> I just found it weird to have Linux - Windows - Linux.

Seems reasonable. Please put the reasoning in the commit message :)
Also, please format the commit message in accordance with project style. (See [contributing guidelines](https://github.com/SerenityOS/serenity/blob/022b4a3ed38655e6c89d71b8b45936871d2d76d2/CONTRIBUTING.md))

**Comment by trustable-code** [comment]
Replaced by https://github.com/SerenityOS/serenity/pull/11566

**Pull request closed without merging**
