### PR TITLE
LibGfx/JPEGWriter: Don't throw away highest-frequency component in FDCT

### PR DESCRIPTION
**Pull request by nico**

### CODE REVIEW

**Comment by nico** [comment]
`Build/lagom/bin/image -o out.jpg in.png --quality 100` output before:

out-none

After:

out-just

**Comment by trflynn89** [comment]
Code looks good, but help me out - I can't tell the difference between the two pictures :upside_down_face:

**Comment by nico** [comment]
Zoom in a bit, and ideally use nearest-neighbor sampling for zooming. There's some high-frequency "dirt" in the first image that isn't in the 2nd. For example:
* To the left of "b" of "basic"
* Around the "The" at the start of the first bullet point
* Once you've seen those, you'll see it all over the picture

**Comment by trflynn89** [comment]
Ah I see, yeah it's really obvious to the left of the "F"s in the last 2 bullet points too. Thanks.

**Pull request merged**
