### PR TITLE
Ports/devilutionX: Remove SDL2_mixer dependency

### PR DESCRIPTION
**Pull request by AJenbo**
This was replaced by SDL_audiolib a couple of versions ago

### CODE REVIEW

**Comment by timschumi** [comment]
Commit title should start with `Ports:` (or `Ports/devilutionX:`). Also, if `SDL2_mixer` has been replaced with `SDL_libaudio`, shouldn't we have that as a dependency instead?

**Comment by gmta** [comment]
Also, what even is `SDL_libaudio`?

**Comment by AJenbo** [comment]
@timschumi You probably don't have a port of SDL_audiolib and so it is build statically from the vendored dependecies.

@gmta https://github.com/realnc/SDL_audiolib

**Comment by AJenbo** [comment]
Not sure why the CI timed out, I don't think it's because I fixed the commit message?

**Comment by ADKaster** [comment]
> You probably don't have a port of SDL_audiolib and so it is build statically from the vendored dependecies.

Correct, It's 'vendored' using FetchContent

https://github.com/diasurgical/devilutionX/blob/master/3rdParty/SDL_audiolib/CMakeLists.txt#L40

Assuming the build still works this is probably fine, but it might be a good set of future patches to go and port the actually required dependencies so that it doesn't fetchcontent its own copy going forward.

**Pull request merged**
