### PR TITLE
Base: Update Cupertino Theme and enable window-close-modified icon

### PR DESCRIPTION
**Pull request by djwisdom**
Aim for consistent user-experience across all themes

Before:

image

After:

image

### CODE REVIEW

**Comment by IdanHo** [comment]
Please do all of these in a single PR next time. Running the whole CI 4 times to for an update PNG is not a good use of resources.

**Comment by djwisdom** [comment]
Will do.  Now that you mention it, it was indeed wasteful on my part.

**Comment by adamsoutar** [comment]
On macOS, when closing a window is going to interrupt you with a pending action (like a "Document has been modified" modal), the close button gets a persistent dot in it - both when hovering and idle.

I wonder if we should follow that instead, considering this is Cupertino?

image
image

**Comment by djwisdom** [comment]
> On macOS, when closing a window is going to interrupt you with a pending action (like a "Document has been modified" modal), [the close button gets a persistent dot in it](https://apple.stackexchange.com/questions/66292/whats-the-dot-in-the-centre-of-the-red-window-close-button-for) - both when hovering and idle.
> 
> I know you're going for a consistent experience across themes, but I wonder if we should follow that instead, considering this is Cupertino?
> 
> image image

Maybe something along these lines? -> 
image

**Pull request merged**
