### PR TITLE
JIT: Optimization for 64-bit mov

### PR DESCRIPTION
**Pull request by TobyAsE**
This introduces an optimization where a 64-bit-mov from an immediate to a register gets converted to a 32-bit-mov of the top bits of the immediate and a left-shift afterwards. Obviously this only works if the immediate's lower 32 bits are 0. This is quite often the case, for example the LibJS Tags reside in the top bits.
This encoding saves 1 byte compared to the plain 64-bit-mov.

I didn't expect this to have measurable results, but it has! A dumb loop program with 1 billion iterations gets about 2% faster. I just thought it was a fun exercise in the new shiny JIT and the confusing x86 instruction encoding...

Top: With, Bottom: Without
image

### CODE REVIEW

**Comment by awesomekling** [comment]
That's a pretty surprising result! Could you test the Kraken benchmark before/after and see how we fare on a more diverse benchmark?

There's a runner and comparison tool here: :)
https://github.com/SerenityOS/js-benchmarks

**Comment by TobyAsE** [comment]
The Kraken ai-astar.js stays the same, the differences here are not statistically relevant:
Without my patch: Time (mean ± σ):      7.136 s ±  0.036 s 
With my patch:       Time (mean ± σ):      7.156 s ±  0.043 s
The times are within 1 sigma of each other

**Comment by awesomekling** [comment]
I tried replicating your results on two machines here (one laptop, one desktop).

On my laptop, the two approaches are equally fast.
On my desktop, the single mov is slightly faster (~1%) than the mov+shl.

In other words, I think may help on some CPUs, and hurt on others.
Since there's no known measurable speedup on any non-micro-benchmark, I'm leaning towards "let's not do this", at least not without more data suggesting a more consistent performance improvement.

**Comment by TobyAsE** [comment]
Interesting results indeed!
It was fun nonetheless :^)

**Pull request closed without merging**
