### PR TITLE
AK: Make `remove_all_matching` returns the number of entries removed

### PR DESCRIPTION
**Pull request by mhermier**
Hi,
It can be useful to know the number of removed entries without counting the elements in the structure. And it is better than returning a plain bool, and is still compatible with bool.

### CODE REVIEW

**Comment by IdanHo** [comment]
This is dead code (because nothing uses it in the project), we don't add dead code to Serenity. If you have a legitimate use case for this, you can add it as a separate commit.

**Comment by pbrw** [comment]
> This is dead code (because nothing uses it in the project), we don't add dead code to Serenity. If you have a legitimate use case for this, you can add it as a separate commit.

It's not dead code, it's used e.g. _serenity/Kernel/FileSystem/Ext2FileSystem.cpp_ line 707. Also Andreas uploaded whole video about this feature.

**Comment by drunderscore** [comment]
No, it is not used.

The return value is unused by your example and all other uses.

**Comment by creator1creeper1** [comment]
> This is dead code

To be honest, I can't even find a call-site using the `bool` return value (although I might have overlooked something). Why can't this just be `void`? I think @mhermier has a good point in that *if* some call-site were to want to know whether something was removed, it would probably also want to know how many entries where removed.

**Comment by mhermier** [comment]
Most of the usage of the original API is a unused, in the code there is only 1 usage of the returned value... So yes sometimes we need to introduce dead code, for the sake of symmetry or future proofing...

**Comment by mhermier** [comment]
The dead code argument is stupid here. It is a template, if the returned value is not used it will most probably be optimized by the compiler, because the value is written and never read. If it is only used as a bool, if the compiler might optimize it if is smart enough and determine that it produce more efficient code. And to conclude, do you really want me to put a `dbgln` in front on every usage of `remove_all_match` to justify a potential usage, just in case one suspect that one of the usage does not removed the number of element that is expected?

**Comment by alimpfard** [comment]
The bool return value was added _for_ that one single user.
Future-proofing isn't really this project's style, iterative improvements as needed are more in line with it - it's safe to say that if at some point, someone ends up needing the "how many" as opposed to the "did it match something", they will add it and be done with it.
As for symmetry, the current signature matches the signature of other remove_matching methods in the codebase, so this is the odd one out if anything.

In general, while not exactly a hard rule, please avoid random API changes with no clear users unless it's a significant improvement in the quality of existing code or is motivated by a further change that does so.

While it might seem like a clear improvement to you, please also see it from our perspectives where it looks like a random API change without any users or particularly compelling reason(s), and that we'd ultimately like to avoid ballooning the scope/APIs of any one interface without reason

---

I'm not going to lie, there's quite a bit of frustration behind this, so I apologise if I sound a bit too harsh, but... I've been seeing quite a lot of changes like that lately.

**Comment by mhermier** [comment]
It is not about being harsh, it is not important. But if usage is too much in mind, you end up being limited, not by the the language itself (because every one can augment the code base), because you are always thinking in terms of cost/usage.

This change has *zero* cost, the API is maintained and augmented, the ABI is broken but it is not a goal for now.

And if one usage is really needed, I can make any change like adding a log the number of removed cache entries in the "LookupServer", or add a feedback in "HackStudio" for a "close all but current file" and display the number of closed files or what ever random debugging or quality of life improvement that can come in my mind on every usage of that API.

Don't get me wrong, It doesn't mean everything needs to be accepted. But if there are more changes likes this, it means that users are using the code, it is alive, and people are hitting some rough edges, or design mistakes and tries to circumvent them.

If the rule was strictly applied, for only 1 usage, everything instance would return void, and for that single user we would use count before and after `remove_all_matching`. So returning bool here was not a bad decision by trying to be smarter, but a short term vision of the real problem being solved.

**Review by linusg — CHANGES_REQUESTED** [review]
s/returns/return/

**Comment by awesomekling** [comment]
This is not used anywhere, so effectively dead code. Closing.

**Pull request closed without merging**
