### PR TITLE
Meta: Build without root

### PR DESCRIPTION
**Pull request by cdfrey**
The fuse2fs tool that is part of e2fsprogs-1.46 has a 'fakeroot' mount option.  This allows a non-root users to modify file ownership and permissions without actually being root.  This package is available in Debian bullseye and buster-backports.
    
If fuse2fs is available, the script now assumes the user wants to use it.  Otherwise, it falls back to the usual root requirements.

### CODE REVIEW

**Comment by Sylvyrfysh** [comment]
What type of performance impact does this have? If it is significant, maybe consider checking if the user is a sudoer first, and if not, fall back to this?

**Comment by cdfrey** [comment]
> What type of performance impact does this have? If it is significant, maybe consider checking if the user is a sudoer first, and if not, fall back to this?

Thanks for responding!

I have not noticed a large speed impact, but my computer is not fast, nor does it have an SSD disk, so others may notice it more than me.  I'm sure any impact is absorbed by my slow spinning disk.

One advantage to using fuse2fs if it is available is that there is no need to type your password at the sudo prompt anymore.  I noticed that even awesomekling does that in some of his videos.  That may offset any decrease in performance from running ext2 in userspace.

**Comment by cdfrey** [comment]
So I ran a quick test, and on my system, using fuse2fs is nearly one second faster than root.

Using fuse2fs:

time rsync -aH --chown=0:0 --inplace Build/i686/Root/ mnt/
real	0m29.716s
user	0m2.038s
sys	0m2.047s


Using root with a loopback mount:

time rsync -aH --chown=0:0 --inplace Build/i686/Root/ mnt/
real	0m30.388s
user	0m1.872s
sys	0m1.921s

Your mileage may vary.

**Comment by bgianfo** [comment]
@cdfrey would you mind fixing the conflict?

**Comment by cdfrey** [comment]
> @cdfrey would you mind fixing the conflict?

@bgianfo Thanks, it is done and pushed up.

**Pull request merged**
