### PR TITLE
LibJS: Fix parsing of numeric object keys

### PR DESCRIPTION
**Pull request by sunverwerth**
Numeric keys were interpreted as their source text, leading to
something like {0x10:true} to end up as {"0x10":true}
instead of {16:true}

### CODE REVIEW

**Comment by awesomekling** [comment]
Is this meant to be a draft?

**Comment by sunverwerth** [comment]
@awesomekling Yes, it's almost finished, I think. I still need to consult the standard to see if what I did is actually correct...

**Comment by sunverwerth** [comment]
Quick update, I haven't been able to put much time into SerenityOS lately ='(
I hope I can find some more time after this week. ❤️

**Review by linusg — COMMENTED** [review]
This looks great, thanks for fixing!

We can keep it on the TODO list for now, but eventually this should be able to replace most of this code:

https://github.com/SerenityOS/serenity/blob/a1029738fdd2bc7471f6db8ec4963734afc4575a/Libraries/LibJS/Runtime/NumberPrototype.cpp#L76-L141

https://tc39.es/ecma262/#sec-number.prototype.tostring

> Return the String representation of this Number value using the radix specified by radixMV. Letters a-z are used for digits with values 10 through 35. The precise algorithm is implementation-defined, however the algorithm should be a generalization of that specified in 6.1.6.1.20.

(the section number at the end is what you just implemented :slightly_smiling_face:)

**Comment by sunverwerth** [comment]
@linusg It was a lot of work and I feel my brain is fried :D Someone who is an expert in floating point math should take a good look at what I just wrote.
Also there's a segfault in there somewhere, I'll need to iron that out and then I can remove the draft status. :+1:

**Comment by awesomekling** [comment]
Very awesome :)

**Pull request merged**
