### PR TITLE
Core: Notifier::Exceptional; Shell: more completion stuff

### PR DESCRIPTION
**Pull request by alimpfard**
- `EINTR` treated as "exceptional event" for Notifiers, callback added
- LibLine: ^C works again
- Shell: redirection path completion
```
$ ls foob*
foobar
$ foo > "foob<tab>
$ foo > "foobar"
```

update: @bugaevc pls

### CODE REVIEW

**Comment by bugaevc** [comment]
Isn't `Notifier::Exceptional` meant to represent read/write errors?

**Comment by alimpfard** [comment]
_technically_, `EINTR` is an error...
I could add another mask, I just saw that it wasn't used and took it for myself :P

**Comment by bugaevc** [comment]
I'd expect a signal notifier to not be tied to any fd at all — you'd create a separate notifier and say which signals you're interested in.

**Comment by alimpfard** [comment]
This is not a signal notifier, this is just a "notify me when your select was interrupted".
I briefly thought about adding signal notifiers, but that would be pretty weird to have in an event loop, as...you know, event loops are not immediate and signals are.

**Comment by bugaevc** [comment]
You don't have to actually handle the signal (notify the notifier) from the signal handler, you could just record somewhere that the signal was received, and then process it when you get `-EINTR` back from the syscall

**Comment by alimpfard** [comment]
Furthermore, what _should_ `Exceptional` notify you of?
Notifier does not do any reads, nor any writes, it only tells you if you can do those, and the only failure point is `select`...I suppose I could flesh it out a little and have it include errno in the SyscallException object, and remove that assertion

**Comment by alimpfard** [comment]
> and then process it when you get -EINTR back from the syscall

That completely disables the _urgent_ meaning of signals, the event queue could be pretty damn saturated and then the event would be dispatched waaaaaaaaaaaay too late

**Comment by bugaevc** [comment]
> Furthermore, what should Exceptional notify you of?
> Notifier does not do any reads, nor any writes, it only tells you if you can do those, and the only failure point is select

True; perhaps Andreas was thinking of the `poll()` syscall which does report errors at `poll()` time (and even calls that "exceptional condition").

> That completely disables the urgent meaning of signals, the event queue could be pretty damn saturated and then the event would be dispatched waaaaaaaaaaaay too late

So when `select()` returns, check for pending signals first and dispatch I/O later.

**Comment by alimpfard** [comment]
> So when select() returns, check for pending signals first and dispatch I/O later.

Sure, why not.

**Comment by alimpfard** [comment]
Closing this as I don't feel like dealing with SignalNotifiers

**Pull request closed without merging**
