### PR TITLE
LibJS: Allow reserved words as keys in object expressions.

### LINKED ISSUE #1768: LibJS: Parser fails when object literal contains identifier that is also a known token
```
> o = { test: "foo", catch: "bar", if: "baz" }
Error: Unexpected token Catch as member in object initialization. Expected a numeric literal, string literal or identifier (line: 1, column: 21))
Error: Unexpected token Colon as member in object initialization. Expected a numeric literal, string literal or identifier (line: 1, column: 26))
Error: Unexpected token If as member in object initialization. Expected a numeric literal, string literal or identifier (line: 1, column: 35))
Error: Unexpected token Colon as member in object initialization. Expected a numeric literal, string literal or identifier (line: 1, column: 37))
Throwing JavaScript Error: ReferenceError, 'bar' not known
Uncaught exception: [ReferenceError]: 'bar' not known
> o
Throwing JavaScript Error: ReferenceError, 'o' not known
Uncaught exception: [ReferenceError]: 'o' not known
>
```

### PR DESCRIPTION
**Pull request by sunverwerth**
Fixes #1768

The spec makes it a bit hard to understand what exactly counts as a reserved word, but I think this is it!

https://www.ecma-international.org/ecma-262/5.1/#sec-7.6

### CODE REVIEW

**Comment by sunverwerth** [comment]
Converted to draft. I will also add the changes to MemberExpression.

**Comment by sunverwerth** [comment]
Draft again... 😄 I need to add tests

**Comment by awesomekling** [comment]
Blessed!

**Comment by linusg** [comment]
Hooray, thanks @sunverwerth!

**Pull request merged**
