### PR TITLE
Base: Add a bunch of heart emoji (and others)

### PR DESCRIPTION
**Pull request by kleinesfilmroellchen**
U+00A9, U+00AE, U+1F192, U+1F193, U+1F195, U+1F493, U+1F495, U+1F497,
U+1F498, U+1F49D, U+1F5A4, U+1F9E1

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
Nice :)
Can you please update the commit message to use the same format as Xexxa, including each emoji and its name?

**Comment by squeek502** [comment]
Right now the convention is to remove leading zeros on codepoints with < 4 hex digits, so `U+00A9` and `U+00AE` should be `U+A9` and `U+AE`. This may change in the future, but currently that's what the lookup code and generate-emoji-txt.sh expects.

**Comment by Xexxa** [comment]
> Can you please update the commit message to use the same format as Xexxa, including each emoji and its name?

For me this is a leftover from when we updated emoji.txt manually, while creating the lines for emoji these could as well be pasted into the commit message, now when emoji.txt is generated automatically it kinda feels like a lot of extra unnecessary work? Is it even necessary to include the codepoints in the commit message, can't you just check the files to see that? Asking because I didn't know this was a rule and quite a few other emoji PRs does not have that, also, if possible, I would like to spend a little less on writing commit messages if it's not needed :^)

**Comment by linusg** [comment]
I find it very useful to see which emojis changed at a glance. In the terminal, no image previews are shown and I'd have to look up code points.

**Comment by squeek502** [comment]
> it kinda feels like a lot of extra unnecessary work

Note that after https://github.com/SerenityOS/serenity/pull/15000, it's fairly easy to generate a list if you put all the new/updated emoji in a folder.

```
Meta/generate-emoji-txt.sh Build/i686/UCD/emoji-test.txt <path to folder with new emoji> new-emoji.txt
```

**Comment by kleinesfilmroellchen** [comment]
@linusg I'm not using Xexxa's *exact* format but the format that the Unicode chart uses. I hope that's okay and we can merge this now.

**Review by Xexxa — APPROVED** [review]
LGTM

**Pull request merged**
