### PR TITLE
AK:HashMap+LibJs:Lexer add ctor with capacity + use it in Js Lexer

### PR DESCRIPTION
**Pull request by tryfinally**
1. Add ctor to Hashmap to allow ensuring capacity.
2. Refactor LibJS:Lexer to use it.

### CODE REVIEW

**Comment by nico** [comment]
A question I forgot to ask on the previous similar change: Why is the number of elements passed to the hash map the best size for the hash map? It virtually guarantees that there are buckets with more than 1 element. Maybe there's some reason why this is the best size/collision tradeoff, but it's at least not obvious to me.

If the "hash of fixed list of strings" use case is important, maybe it would make sense to add a perfect hash function generator that takes a list of fixed strings and generates a perfect hash function, then we could do a n-elt hash table without collisions (and with a fast, special-purpose hash function).

**Comment by tryfinally** [comment]
I think that a good idea. Especially on those lexer maps.
For now maybe just use a load factor?

**Comment by alimpfard** [comment]
Or maybe just add a constexpr hashmap and throw all this out?

_/me pushes for more constexpr_

**Comment by awesomekling** [comment]
Also please put the HashMap change in a separate commit

**Comment by bgianfo** [comment]
> Or maybe just add a constexpr hashmap and throw all this out?

@alimpfard Are you talking  about this? https://www.youtube.com/watch?v=INn3xa4pMfg
The token mapping does seem like a pretty nice use case for for something like what's mentioned in the video.

**Pull request closed without merging**
