### PR TITLE
LibHTTP+LibWeb+RequestServer: Add HTTP::HeaderMap + simplify Set-Cookie handling

### PR DESCRIPTION
**Pull request by kennethmyhra**
Commits cherry picked from: https://github.com/LadybirdBrowser/ladybird/pull/116 and https://github.com/LadybirdBrowser/ladybird/pull/119

### CODE REVIEW

**Review by tcl3 — APPROVED** [review]

**Comment by kennethmyhra** [comment]
Missed a spot `Fetch::Fetching::log_response()`, not sure why that didn't fail locally 🤔

**Comment by nico** [comment]
Hm, how should we handle commit messages for cherry-picks that break the build and need fixups?

* just sneak it into the cherry-pick?
* tweak commit message to say "cherry-picked from abcde and then changed XXX to fix compile"?
* put the fix in a separate commit? (kinda cleanest, but breaks the "every revision must build" invariant, so that's a nonstarter)

In some cases it might be possible to do the fixup in a commit _before_ the breaking upstream change. Is that possible here? If not, then "cherry-pick with amended commit message" is maybe best?

**Comment by kennethmyhra** [comment]
This what I did: `just sneak it into the cherry-pick?`. Not possible to sneak it in before or after without breaking the build.

I can add a note to the commits, for this one that would basically be:
> Updated various SerenityOS components to make it build.

The `Fetching::Fetch::log_response()` fix I mentioned above should though have broken the build in Ladybird as well. Seems it does so on our `GNU DEBUG_ALL` pipeline.

**Comment by nico** [comment]
Adding something like "Updated to fix DEBUG_ALL build" to the cherry pick commit message makes sense to me :)

**Comment by kennethmyhra** [comment]
It breaks on Ladybird too if I build with `-DENABLE_ALL_THE_DEBUG_MACROS=ON`. I'll make a PR against Ladybird to fix that and cherry pick it back in this PR before we merge.

**Comment by kennethmyhra** [comment]
Put up the mentioned fix here: https://github.com/LadybirdBrowser/ladybird/pull/119

**Comment by nico** [comment]
(Also, looks like 

> It breaks on Ladybird too if I build with `-DENABLE_ALL_THE_DEBUG_MACROS=ON`. I'll make a PR against Ladybird to fix that and cherry pick it back in this PR before we merge.

Thinking about this again, this doesn't help with the "every commit should build". I suppose we could squash the two cherry-picks and put two "cherry-picked commit XXX" lines in the squashed commit message.

**Comment by kennethmyhra** [comment]
I squashed commit: https://github.com/LadybirdBrowser/ladybird/commit/c51d01bea712d75f9b2cd700be942935044e49b4 into the first one where the change/breakage occurs.

**Pull request merged**
