### PR TITLE
Portability fixes

### PR DESCRIPTION
**Pull request by jcs**
Here are a bunch of cherry-picked commits from my hosted branch for 64-bit `size_t` support, building with clang, etc.

Tested on a regular build (cross-compiled under OpenBSD) and seems to work fine in qemu.

### CODE REVIEW

**Comment by jcs** [comment]
Hold off on this for now, need to push some tweaks...

**Comment by jcs** [comment]
Ok, this is ready for review now.

**Comment by bugaevc** [comment]
🎉

But may I please ask that the commit messages be formatted according to Serenity conventions — capital letter after the colon (unless it's a name like `dbgprintf()`), and "foo is unused" should be "Remove unused foo" (verb, in imperative)

**Comment by awesomekling** [comment]
Let's merge'em. This is some really good stuff :heart: :smile:

**Comment by jcs** [comment]
Thanks, friends.

**Pull request merged**
