### PR TITLE
LibWeb: Bring document loading to spec, and fix Acid3

### LINKED ISSUE #22230: REGRESSION: LibWeb: Acid3 no longer starts
To reproduce, open http://wpt.live/acid/acid3/test.html and note that the test doesn't start running.

Regressed with 2805e16c1c1658c65fe5dabaa63b4a0e98346f1f
cc @AtkinsSJ

### PR DESCRIPTION
**Pull request by AtkinsSJ**
Implement the document-loading algorithms from the HTML spec, instead of the ad-hoc system we had before. This makes Acid3 load again (Fixes #22230):

image

As noted, this does also remove the Gemini document-loading code (which is only a few lines). That was already dead code since switching to navigables, and needs to be reimplemented in a different way.

### CODE REVIEW

**Comment by kalenikaliaksandr** [comment]
I tried to figure why it hangs in tests. The issue is that with these changes document becomes active (`Navigable::activate_history_entry()` makes document active) after readiness changes to complete so `Document::update_readiness()` can't call `page_did_finish_loading()` because it can't find out if document belongs to top-level navigable because document is not part of session history yet.

I think we need to stop assuming that document readiness becomes complete only after document becomes active. One way to implement this is:
1. In `Document::update_readiness()` when it is called to change document's state to complete:
   If document is active then immediately call `page_did_finish_loading()` otherwise set flag `needs_to_call_did_finish_loading` to true.
2. In `Document::make_active()` if `needs_to_call_did_finish_loading` is true then call `page_did_finish_loading()`

**Comment by kalenikaliaksandr** [comment]
applying this patch on top of your branch fixes hanging tests (at least for me):
```diff
diff --git a/Userland/Libraries/LibWeb/DOM/Document.cpp b/Userland/Libraries/LibWeb/DOM/Document.cpp
index a21c1487fb..7707eb12e7 100644
--- a/Userland/Libraries/LibWeb/DOM/Document.cpp
+++ b/Userland/Libraries/LibWeb/DOM/Document.cpp
@@ -1938,10 +1938,14 @@ void Document::update_readiness(HTML::DocumentReadyState readiness_value)
     if (readiness_value == HTML::DocumentReadyState::Complete)
         dbgln("Document active? {}", is_active());
 
-    if (readiness_value == HTML::DocumentReadyState::Complete && navigable() && navigable()->is_traversable()) {
+    if (readiness_value == HTML::DocumentReadyState::Complete) {
         dbgln("-> calling page_did_finish_loading");
-        HTML::HTMLLinkElement::load_fallback_favicon_if_needed(*this).release_value_but_fixme_should_propagate_errors();
-        navigable()->traversable_navigable()->page().client().page_did_finish_loading(url());
+        if (navigable() && navigable()->is_traversable()) {
+            HTML::HTMLLinkElement::load_fallback_favicon_if_needed(*this).release_value_but_fixme_should_propagate_errors();
+            navigable()->traversable_navigable()->page().client().page_did_finish_loading(url());
+        } else {
+            m_needs_to_call_page_did_load = true;
+        }
     }
 }
 
@@ -3101,6 +3105,10 @@ void Document::make_active()
 
     // 4. Set window's relevant settings object's execution ready flag.
     HTML::relevant_settings_object(window).execution_ready = true;
+
+    if (m_needs_to_call_page_did_load) {
+        navigable()->traversable_navigable()->page().client().page_did_finish_loading(url());
+    }
 }
 
 HTML::ListOfAvailableImages& Document::list_of_available_images()
diff --git a/Userland/Libraries/LibWeb/DOM/Document.h b/Userland/Libraries/LibWeb/DOM/Document.h
index fb93147bcb..a529150a77 100644
--- a/Userland/Libraries/LibWeb/DOM/Document.h
+++ b/Userland/Libraries/LibWeb/DOM/Document.h
@@ -767,6 +767,8 @@ private:
 
     // https://www.w3.org/TR/web-animations-1/#pending-animation-event-queue
     Vector<PendingAnimationEvent> m_pending_animation_event_queue;
+
+    bool m_needs_to_call_page_did_load { false };
 };
 
 template<>

```

**Comment by kalenikaliaksandr** [comment]
Or you could slap spin_until to wait until document becomes active in update_readiness()

**Comment by AtkinsSJ** [comment]
> applying this patch on top of your branch fixes hanging tests (at least for me):

That's great! Thank you very much for figuring this out! :^)

Marked as ready for review.

**Pull request merged**
