### PR TITLE
Kernel: Use Process::credentials() and remove user ID/group ID helpers

### PR DESCRIPTION
**Pull request by AnthonyIacono**
Move away from using the group ID/user ID helpers in the process to allow for us to take advantage of the immutable credentials instead.

### CODE REVIEW

**Comment by AnthonyIacono** [comment]
I would love some feedback on where it makes sense to name things with more verbose names (`current_process_credentials` vs `credentials`, etc) and also when it makes sense to do `credentials()->uid()` vs making a local variable for the credentials to prevent future versions of ourselves from unnecessary calling `credentials()` a second time on the process. I assume that doing so would diminish some of the value of having the immutability.

**Comment by jamesbellamy99** [comment]
Personally I've gone with `current_process_credentials` when there has already been a variable named `current_process`, if the process variable is just `process` then I've gone with `credentials`

**Comment by AnthonyIacono** [comment]
> Personally I've gone with `current_process_credentials` when there has already been a variable named `current_process`, if the process variable is just `process` then I've gone with `credentials`

Awesome, I went ahead and followed that (let me know if I missed anything)

**Comment by jamesbellamy99** [comment]
Tests are currently failing to run, if you run them on Serenity they cause a kernel panic due to 
```
[TestSigAltStack(152:152)]: ASSERTION FAILED: !PtrTraits::is_null(bits)
[TestSigAltStack(152:152)]: ././Kernel/Library/LockRefPtr.h:440 in T* AK::LockRefPtr<T, PtrTraits>::as_nonnull_ptr(FlatPtr) const [with T = Kernel::Process; PtrTraits = AK::LockRefPtrTraits<Kernel::Process>; FlatPtr = unsigned int]
```

**Comment by AnthonyIacono** [comment]
@jamesbellamy99 Good catch, I think that's fixed now.

**Pull request merged**
