### PR TITLE
Ports: Changed variable names in .hosted_defs.sh

### PR DESCRIPTION
**Pull request by panos**
- DESTDIR and SERENITY_ROOT have not been removed for the time being, in order to ensure a steady transition and to not break all the ports at once.

... Lots of stuff being unpacked here. This was implemented based on this suggestion: https://github.com/SerenityOS/serenity/pull/6482#issuecomment-822356488

In other news, I figured out where the variables are located and what each variable does, so that's good.

### CODE REVIEW

**Comment by panos** [comment]
The linting's a bit weird, but I didn't want to change the order of the variables or not leave a newline before a comment. Either way, that's supposed to be temporary until all ports successfully transition to the new format and until the documentation's updated.

**Comment by linusg** [comment]
As mentioned on Discord, I think we can choose even more descriptive names for these while we're here. Something like `SERENITY_SOURCE_ROOT` and `SERENITY_INSTALL_ROOT`, but suggestions welcome. I also think `SERENITY_ROOT` can go away in this PR, it should just be global search and replace, nothing difficult. :)

**Comment by panos** [comment]
> As mentioned on Discord, I think we can choose even more descriptive names for these while we're here. Something like `SERENITY_SOURCE_ROOT` and `SERENITY_INSTALL_ROOT`, but suggestions welcome. I also think `SERENITY_ROOT` can go away in this PR, it should just be global search and replace, nothing difficult. :)

Sorry, missed the e-mail. I feel like the latter should happen in another PR, though, as this is about to get messy.

**Comment by panos** [comment]
Proposal:

- `DESTDIR` -> `SERENITY_INSTALL_ROOT`
- `SERENITY_ROOT` -> `SERENITY_PORTS_ROOT`, because the Ports folder is neither the entire source code directory or the `Root` folder as in `SERENITY_INSTALL_ROOT`.

**Comment by linusg** [comment]
The current `SERENITY_ROOT` is not the ports directory though, but the the repository root (and it's used for various other things that are not ports!)

**Comment by panos** [comment]
> The current `SERENITY_ROOT` is not the ports directory though, but the the repository root (and it's used for various other things that are not ports!)

Oh, then it's correct. WAIT, I completely forgot that this shell file was in the `Ports` folder and not inside of another port folder, I just got a bit mixed up. Yeah, I concur, `SERENITY_ROOT` seems just about fine.

**Comment by panos** [comment]
So, let's sum this up:

- `DESTDIR` -> `SERENITY_INSTALL_ROOT`. `DESTDIR` will be kept around.
- `SERENITY_SOURCE` will point to the root folder of the repository. Let's keep the "root" terminology in the directory structure sort of sense out of here.
- `SERENITY_BUILD_DIR` will remain unchanged.
- `SERENITY_INSTALL_ROOT` will point to `$SERENITY_BUILD_DIR}/Root`.

**Comment by linusg** [comment]
`SERENITY_SOURCE` -> `SERENITY_SOURCE_DIR`, but yes, this sounds good!

**Comment by panos** [comment]
> `SERENITY_SOURCE` -> `SERENITY_SOURCE_DIR`, but yes, this sounds good!

True, it's important not to break the consistency.

**Review by linusg — COMMENTED** [review]
cool - if you please could replace the two uses of `SERENITY_ROOT` in `SERENITY_BUILD_DIR` and `PATH` with `SERENITY_SOURCE_DIR` as well, I think we're good to go!

**Comment by panos** [comment]
> cool - if you please could replace the two uses of `SERENITY_ROOT` in `SERENITY_BUILD_DIR` and `PATH` with `SERENITY_SOURCE_DIR` as well, I think we're good to go!

Thanks for the heads-up!

**Pull request merged**
