### PR TITLE
Clarify macOS Build Instructions

### PR DESCRIPTION
**Pull request by jarhill0**
I just went through successfully building and running SerenityOS under macOS, and I noticed a few things that could be improved in the documentation to create a smoother install experience on macOS.

Also, as a small change, I noticed a place in that document where the phrasing could be more inclusive. Hopefully that isn't seen as out of scope for this PR (since I'm making documentation improvements based on my install experience). It just felt too small to get its own PR.

### CODE REVIEW

**Comment by awesomekling** [comment]
> Also, as a small change, I noticed a place in that document where the phrasing could be more inclusive. Hopefully that isn't seen as out of scope for this PR (since I'm making documentation improvements based on my install experience). It just felt too small to get its own PR.

This project is not an appropriate arena to advertise your personal politics. Please remove this commit.

**Comment by jarhill0** [comment]
It's not about politics. It's just accurate that if one woman ever has used SerenityOS as the `anon` user then `anon` isn't really a "he."

I've removed the commit.

**Comment by desmondcayce** [comment]
fukkin BASED

**Comment by Eugeny** [comment]
Screenshot 2024-07-04 at 19 03 58

nightmare blunt rotation

**Pull request merged**
