### PR TITLE
LibWeb: Fix buttons with TextNode label

### LINKED ISSUE #20472: LibWeb: Buttons with a `TextNode` label don't render it
The label of the following button doesn't render:

```
<button>
    Test
</button>
```

Looks like a regression due to https://github.com/SerenityOS/serenity/pull/20314.

### PR DESCRIPTION
**Pull request by axgallo**
Fixes #20472.

### CODE REVIEW

**Comment by awesomekling** [comment]
Don't we lose vertical centering for text if we do it this way though?

**Comment by axgallo** [comment]
It restores the previous behavior for buttons which only had a `TextNode` child, so we lose it indeed. I can look further into it.

**Comment by axgallo** [comment]
Had to ditch the flow-root wrapper and manually set the line height, but mostly works, including vertical alignment. Longer term we might need a dedicated formatting context.

**Comment by awesomekling** [comment]
Nice, thanks for fixing this up! :)

**Pull request merged**
