### PR TITLE
Base: Add and fix 41 emoji

### PR DESCRIPTION
**Pull request by Xexxa**
x28-screenshot

:^)

### CODE REVIEW

**Comment by Xexxa** [comment]
I think I fixed the issue? :ciflakes:?

**Comment by djwisdom** [comment]
As usual, great work on the new sets of emoji Xexxa! lgtm

**Comment by linusg** [comment]
> I think I fixed the issue? :ciflakes:?

No, linting has no flakes :)

```
> "🏴󠁮󠁯󠀰󠀲󠁿 - U+1F3F4 U+E006E U+E006F U+E0030 U+E0032 U+E007F NO-02 Akershus".length
77
```

The limit is 72.

**Comment by Xexxa** [comment]
> > I think I fixed the issue? :ciflakes:?
> 
> No, linting has no flakes :)
> 
> ```
> > "🏴󠁮󠁯󠀰󠀲󠁿 - U+1F3F4 U+E006E U+E006F U+E0030 U+E0032 U+E007F NO-02 Akershus".length
> 77
> ```
> 
> The limit is 72.

> " - U+1F3F4 U+E006E U+E006F U+E0030 U+E0032 U+E007F NO-02 Akershus".length
65

So 1 character created from 6 codepoints is counted as 12 characters. How does this make any kind of sense?

**Pull request merged**
