### PR TITLE
Base+HackStudio: Add icons

### PR DESCRIPTION
**Pull request by electrikmilk**
Insert or add icons where they are missing.

Context menu for TreeView was missing new file and open icons:
Screen Shot 2022-02-07 at 08 13 24

Adding and removing an Editor or Terminal:
Screen Shot 2022-02-07 at 08 13 38

"Go to line..." was using the "Go Forward" icon:
Screen Shot 2022-02-07 at 08 13 48

Project > New was missing a new file icon:
Screen Shot 2022-02-07 at 08 14 04

### CODE REVIEW

**Comment by awesomekling** [comment]
This has lint errors

**Comment by electrikmilk** [comment]
Failed checks appear to be unrelated to my changes now.

**Review by itamar8910 — APPROVED** [review]

**Comment by electrikmilk** [comment]
Failing checks appear irrelevant.

**Comment by electrikmilk** [comment]
Sorry, Github suggested a merge to resolve the conflicts, unsure what to do here. I know we aren't supposed to include merges in our commits, do I rebase?

**Pull request closed without merging**
