### PR TITLE
PixelPaint: Guide tool and move tool performance improvements

### PR DESCRIPTION
**Pull request by tcl3**
This patch improves the performance of the move tool when using arrow keys and the guide tool when dragging a guide. 

Both of these scenarios would cause a lot of calls to `ImageEditor::update_modified()`, which would cause the histogram and vectorscope widgets to update repeatedly. This caused the program to lock up for large images.

### CODE REVIEW

**Comment by nico** [comment]
Other, more general fix ideas (if you're interested, else this is fine too -- could do both):

* Add a timer, and instead of updating the histogram immediately when it's invalidated, start the timer to run for 30ms or so. (If the timer is already running, do nothing.) When the timer finishes, actually update the histogram. That batches together histogram updates and will help with CPU usage in general.

* Something something multi threading

**Comment by tcl3** [comment]
@nico - I had a quick look into using a timer to limit the number of times the event can fire. There is a function `Core::debounce` that kind of does what we want, but ideally we want something that will fire immediately and block subsequent calls rather than waiting until after its timeout is expired to fire.

I have a look at adding a  `Core::throttle` function to do this.

**Comment by tcl3** [comment]
@nico - So, I implemented a `Core::throttle` helper and tested it against `Core::debounce` by quickly pressing the arrow keys with the move tool to generate events. I couldn't really see a noticeable difference between the two so I just used what's already there.

**Review by nico — APPROVED** [review]
Is the move change still needed after the debounce change? Might be nice if the histogram updated every now and then while moving. But /shruggie.

**Comment by tcl3** [comment]
I've just tested without the move change and performance is fine, so I've removed it from the PR. The debounce causes the histogram not to update while repeat events are being fired.  

I went back to the `throttle` function I wrote and using that gives reasonable performance while allowing the histogram to update. I've found other potential uses for it as well, so it may be worth opening another PR to bring it in.

**Review by nico — APPROVED** [review]
Looks great :)

**Pull request merged**
