### PR TITLE
gron: Add options for enabling/disabling colored output

### PR DESCRIPTION
**Pull request by AtkinsSJ**
These match the options in the original gron:
https://github.com/tomnomnom/gron

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
s/options/option/

**Comment by AtkinsSJ** [comment]
> s/options/option/

It's two options though? Which is silly, sure, but I think it's grammatically correct. (Unlike my ability to spell "grammatically" first try.)

**Comment by linusg** [comment]
Oh, I totally read it as one `args_parser.add_option()` call. Sorry 🤦

**Comment by AtkinsSJ** [comment]
Hehe, no worries! Thanks for always being so thorough, it's great. :^)

**Pull request merged**
