### PR TITLE
Base: Update Durrque theme for a better look and feel

### PR DESCRIPTION
**Pull request by djwisdom**
## Before:
Durrque-before

## After:
Durrque_after

- Status font color updated for better blending
- Active+Inactive window title bars given more emphasis
- Reverse shadow for glow effect

### CODE REVIEW

**Comment by bgianfo** [comment]
Nitpick: Please fix the commit message to be have proper grammar.

**Comment by AtkinsSJ** [comment]
Nice idea with the glow effect, much easier to see than the shadow was. :^)

**Comment by nico** [comment]
Is Base/res/icons/themes/Durrque/frame-half-shadow-light.png used for anything? If so, how?

**Comment by djwisdom** [comment]
Good catch! I was experimenting with reversing the frame shadow color to produce the 'glow' effect, totally missed removing that png. Currently frame-half-shadow-light.png is no longer used in Durrque theme. You are encouraged to remove it and submit a PR. :^)

**Pull request merged**
