### PR TITLE
PixelPaint: Fix layer order

### PR DESCRIPTION
**Pull request by zeGolem**
PixelPaint's layer used to be shown from bottom-most to topmost, making the background layer the top one, which is opposite to the behaviour of most other paint applications, as it makes more sense for the background layer to be at the bottom of the layer list.

### CODE REVIEW

**Comment by metmo** [comment]
This would also require a change in `LayerListWidget::select_top_layer()`, `LayerListWidget::select_bottom_layer()`, and the other actions that handle layer movement.

**Comment by zeGolem** [comment]
> This would also require a change in `LayerListWidget::select_top_layer()`, `LayerListWidget::select_bottom_layer()`, and the other actions that handle layer movement.

No, this is kinda confusing, but each layer is linked to a corresponding gadget, and the gadgets are used to render the layer list shown in the window. I'm changing the order of the gadgets, not the layer they're linked to, so those functions still work as intended, because they're acting directly on the layers (I tested it).

**Comment by metmo** [comment]
> > This would also require a change in `LayerListWidget::select_top_layer()`, `LayerListWidget::select_bottom_layer()`, and the other actions that handle layer movement.
> 
> No, this is kinda confusing, but each layer is linked to a corresponding gadget, and the gadgets are used to render the layer list shown in the window. I'm changing the order of the gadgets, not the layer they're linked to, so those functions still work as intended, because they're acting directly on the layers (I tested it).

My bad! I do however note that they behave odd when rearranging them, they do not end up in the position where i drop them.

**Comment by zeGolem** [comment]
> > > This would also require a change in `LayerListWidget::select_top_layer()`, `LayerListWidget::select_bottom_layer()`, and the other actions that handle layer movement.
> > 
> > 
> > No, this is kinda confusing, but each layer is linked to a corresponding gadget, and the gadgets are used to render the layer list shown in the window. I'm changing the order of the gadgets, not the layer they're linked to, so those functions still work as intended, because they're acting directly on the layers (I tested it).
> 
> My bad! I do however note that they behave odd when rearranging them, they do not end up in the position where i drop them.

Indeed… There are quite a few places in the code that assume the layer index is the same as the gadget index, which causes issue now that they're not in sync, I'll look into this and fix them

**Comment by sin-ack** [comment]
Hm... why isn't this whole thing using a `LayerModel` backing it or something? Then you could just display them in reverse by indexing the model.

**Comment by zeGolem** [comment]
> Hm... why isn't this whole thing using a `LayerModel` backing it or something? Then you could just display them in reverse by indexing the model.

I can't find any models relating to the layer list… I tried grepping for "model" in the PixelPaint directory and only found results in the RectangleSelectionTool… But if someone else finds it, it'd probably be easier to change that way

**Comment by zeGolem** [comment]
This last commit should fix issues when reordering layers and adding/deleting them

**Comment by sin-ack** [comment]
> > Hm... why isn't this whole thing using a `LayerModel` backing it or something? Then you could just display them in reverse by indexing the model.
> 
> I can't find any models relating to the layer list… I tried grepping for "model" in the PixelPaint directory and only found results in the RectangleSelectionTool… But if someone else finds it, it'd probably be easier to change that way

Why not add one yourself? I feel like that would be a cleaner solution rather than changing visit order all over the place.

**Comment by zeGolem** [comment]
Hi, sorry for the late update, but due to IRL issues, I won't be able to finish this patch, as it still requires a major rewrite… Sorry for the inconvenience

**Pull request closed without merging**
