### PR TITLE
WASM -> Wasm

### PR DESCRIPTION
**Pull request by steren**
Meta: Use proper abbreviation for WebAssembly in README ("Wasm", as recommended at https://webassembly.org/)

### CODE REVIEW

**Comment by MacDue** [comment]
The correct prefix for a change to the README would be `Meta: ` (I think). 
Something like `Meta: Abbreviate WebAssembly as Wasm in the README` would be a more Serenity style commit title.

**Comment by steren** [comment]
Thanks. I updated the PR description. I hope that is enough.

**Comment by MacDue** [comment]
You have to update the commit title (just editing the PR won't do it :sweat_smile:)

Assuming you used the command line you can do that with `git commit --amend` then editing the title/body, then force pushing with `git push -f`. If you used the web interface I don't think that supports editing commits.

**Comment by steren** [comment]
I sent this PR from my phone :D

the easiest is to just send a new one

**Comment by steren** [comment]
Here we go: https://github.com/SerenityOS/serenity/pull/17337

**Pull request closed without merging**
