### PR TITLE
Kernel+Userland: Propagate proper filetypes in SysFS, ProcFS and DevPtsFS, add the listdir utility

### PR DESCRIPTION
**Pull request by supercomputer7**
Should actually fix the problem being represented in #22533 (even though we just allow zeroed type now).

Still need to add a man page for the new `listdir` utility, but I will want to ensure I did write it correctly as well :)

### CODE REVIEW

**Comment by supercomputer7** [comment]
> Assuming that the listdir utility should reveal situations where filetypes aren't known/propagated by the kernel, you'd need something like the following patch to ensure that DirIterator doesn't fix up the filetypes for this specific usecase:
> Patch

That's a good idea, thank you for suggesting this!
I sent a new revision now :)

**Comment by supercomputer7** [comment]
This is ready for review now, as I added a manual page for the `listdir(1)` utility :)

**Comment by ADKaster** [comment]
Conflicts with the DirIterator change I merged today

**Review by ADKaster — APPROVED** [review]
I like the improvements to the FS and LibCore a lot. I'm not really sure I understand why this new `lsdir` utility isn't just some extra flags to `ls` though. I'll merge as-is, but I would strongly consider moving the functionality into the existing utilities instead of making new ones. Even if it's custom behavior not part of POSIX :)

**Pull request merged**
