### PR TITLE
Userland: Provide a misbehaving application

### PR DESCRIPTION
**Pull request by BenWiederhake**
This will be a test case for #2977.

This shows that any "hanging" application currently takes down the inspector with it.

Maybe you don't want to merge it, but it's definitely going to be useful to demonstrate that #2977 can still be reproduced.

### CODE REVIEW

**Comment by nico** [comment]
Feels like this fits in with the programs in Userland/Tests maybe?

**Comment by BenWiederhake** [comment]
Not really, since the program has basically no way to determine whether Inspector is hanging.

**Comment by nico** [comment]
They're (almost?) all manual tests I think, no?

**Comment by BenWiederhake** [comment]
Those in `Userland/Tests/`? Not really, most of them seem to be intended to output either `PASS` or `FAIL`, and about half of them actually do.

**Pull request merged**
