### PR TITLE
Base: Added/adjust glyphs in font Tiny Regular

### PR DESCRIPTION
**Pull request by Xexxa**
Maintainence to stabilize the font.

Added glyph FFFD (BitmapFont.cpp:255 :-p)
Adjusted multiple glyphs for improved consistency.
Added a few glyphs to current ranges.
Added range Mende Kikakui 1E800-1E8DF (incomplete, I
continued my work in Katica)

### CODE REVIEW

**Comment by awesomekling** [comment]
> Added glyph UFFFD (BitmapFont.cpp:255 :-p)

Could you please explain what you mean, instead of making a cryptic file:line reference?

**Comment by Xexxa** [comment]
> > Added glyph UFFFD (BitmapFont.cpp:255 :-p)
> 
> Could you please explain what you mean, instead of making a cryptic file:line reference?

Sorry! According to a comment in the source all fonts should have the FFFD glyph.

**Comment by awesomekling** [comment]
> > > Added glyph UFFFD (BitmapFont.cpp:255 :-p)
> > 
> > 
> > Could you please explain what you mean, instead of making a cryptic file:line reference?
> 
> Sorry! According to a comment in the source all fonts should have the FFFD glyph.

Right, I mean can you please put that in the commit message instead of "BitmapFont.cpp:255 :-p" :)

**Comment by Xexxa** [comment]
> Right, I mean can you please put that in the commit message instead of "BitmapFont.cpp:255 :-p" :)

Ahh, I see. Github told me to --force-with-lease, hope I did the right thing here.

**Comment by linusg** [comment]
Tweaked the commit message a bit and fixed a typo - please use imperative mood as per the [contribution guidelines](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md) :)

**Pull request merged**
