### PR TITLE
PixelPaint: Fix Undo/Redo buttons

### LINKED ISSUE #5814: PixelPaint: Two undo actions required for after a new change
When a change is made in PixelPaint, two undo actions are required to undo that change. After that initial two undo actions further undo actions work as expected until a new change is made.  

Reproduction steps:
- Open PixelPaint
- Draw a few lines using the pen tool
- Try using undo - notice nothing changes
- Try using undo again - notice one line is removed
- Try using undo again - works as expected and another line is removed

### PR DESCRIPTION
**Pull request by mrkct**
~~The "Undo" action would crash the program due to a nullptr dereference. The first commit fixes that.~~  
This was fixed in another commit meanwhile.

The now first commit is due to the fact that undoing to the start of the drawing would deselect all layers so we just select the first one if there were no layers selected in the snapshot.

The second commit fixes the fact that you sometimes needed to press undo twice to actually start undo-ing stuff, and also that you couldn't undo the very first action you did in the editor.

Fixes #5814.

### CODE REVIEW

**Comment by awesomekling** [comment]
How does this affect the behavior of UndoStack in TextEditor, for example?

**Comment by mrkct** [comment]
My bad, this breaks TextEditor and other programs. Changing this to draft, I will try to take a look in the weekend

**Comment by alexmajor** [comment]
Should this be linked to #5814.

**Comment by mrkct** [comment]
I have removed one of the commits since that was fixed by someone else in the meanwhile. 

Instead of changing how UndoStack works I have changed PixelPaint. Admittedly this is a bit of an hack, but it's fully contained in `ImageEditor::undo` and I have added a comment explaining what's going on there. 

I think to remove this hack we would have to rework how `ImageUndoCommand` works, right now this whole issue comes from the fact that we are restoring the same snapshot both when we undo or redo the same command. That is probably a whole lot of problems I'm not going to tackle now though.

**Pull request merged**
