### PR TITLE
AK: Add (maybe_)discard and (maybe_)unused documenting functions

### PR DESCRIPTION
**Pull request by mhermier**
Currently in the code, the C void cast `(void)` trick is used in the code to hide some warnings.
I propose to add of this header to centralize attributes modifiers. Here, it adds some helper functions/macros that helps to make the code auto document the different usage of the void casting trick and package them in a nice searchable names.

### CODE REVIEW

**Comment by ccapitalK** [comment]
Can you please give examples of uses for the 3 helpers? It's just that I'm having a difficult time imagining where they would be useful, I don't understand the purpose of discard, and I believe the other two have idiomatic ways of being handled using c++ language features. We have `[[maybe_unused]]` for parameters that may be unused and unnamed function parameters for variables that are definitely not used.

**Comment by mhermier** [comment]
I started a patch to test it in the code base, to see it in action, but I didn't wanted to get the review to be too much noisy.

Here is a made example of the helpers in action:
```
void foo(auto &bar, auto &baz) {
  maybe_unused(bar);           // Usage depends if COND is defined
  unused(baz);                 // There is no usage of baz anywhere
#ifdef COND
  maybe_discard(bar.method()); // method is free to do return a [[nodiscard]] value, a value or void, depending on bar type
  discard(bar.other_method()); // other_method must return a [[nodiscard]] value
#endif
}
```

About [[maybe_unused]], it has the slight disadvantage that I find it very noisy at variable definition. When reading a method signature or a variable definition, there is already a huge bunch of non critical information to trim out before reading what is interesting for hacking, and the way it is done (while logical) produce more noise.

**Comment by ccapitalK** [comment]
> I started a patch to test it in the code base, to see it in action, but I didn't wanted to get the review to be too much noisy.
> 
> Here is a made example of the helpers in action:
> 
> ```
> void foo(auto &bar, auto &baz) {
>   maybe_unused(bar);           // Usage depends if COND is defined
>   unused(baz);                 // There is no usage of baz anywhere
> #ifdef COND
>   maybe_discard(bar.method()); // method is free to do return a [[nodiscard]] value, a value or void, depending on bar type
>   discard(bar.other_method()); // other_method must return a [[nodiscard]] value
> #endif
> }
> ```
> 
> About [[maybe_unused]], it has the slight disadvantage that I find it very noisy at variable definition. When reading a method signature or a variable definition, there is already a huge bunch of non critical information to trim out before reading what is interesting for hacking, and the way it is done (while logical) produce more noise.

Ok, that makes sense. I get the purpose of `discard` now, It seems like an antipattern but I guess there are always going to be times where you legitimately don't want to use something marked nodiscard. The only thing I'm not sure about in your example is whether we need `unused`, isn't it better practice to just make the method signature `void foo(auto &bar, auto &)`?

**Comment by mhermier** [comment]
While it looks like an anti-pattern, there are definitively usage of it in the code base. If you grep the source code for `(void)` there is currently 614 occurrences of it. ~5% are C methods signatures, ~30% are unused, and the rest is discard. The presence is real, but since names are not used users don't have easy access to see the anti-pattern propagation. With these names in place, at least they can be grepped and help to reason about their necessity and the signature of what is called.

It would be, but in practice it not always possible to not name parameters. Names convey meaning and position, and when used in conjunction with templates, inline methods and virtual methods, it is a must have to document what you expect the user to feed.

**Comment by mhermier** [comment]
Functions are now in 2 files AK/Discard.h AK/Unused.h introduced in 2 separated patches, with some changes (did not finished to trim all the usage yet).

**Comment by mhermier** [comment]
I think patch is ready for merge, last minute change request are welcome.

**Comment by bgianfo** [comment]
> I think patch is ready for merge, last minute change request are welcome.

The commit linting checks are failing: 
```
Error: One or more of the commits in this PR do not match the code submission policy:

Userland: Use `(maybe_)discard` instead of  `[[maybe_unused]] auto foo =` (9f66cfdf0d37533f184db4524dbad889fd594b0d):
  Commit message lines are too long (maximum allowed is 72 characters, except for URLs)
```

**Comment by mhermier** [comment]
I know. I didn't find a way to reduce the comment size while being descriptive enough, without being cryptic and start using sed command line comments.

**Comment by bgianfo** [comment]
I don't personally see the utility in adding these macros. 

IMHO, the macros obscure the code by adding a macro based work around that essentially becomes a new language primitive.
I haven't seen a compelling argument for why `(void)` or `[[maybe_unused]]` as they are used today is inadequate?

**Comment by mhermier** [comment]
They are not really inadequate but they either hide information or bloat function signatures. `(void)` casting can either be used to hide an unused variable or a discarded value tagged `nodiscard`. The thing is, while the first one is acceptable, the second one looks a lot like a code smell. And there is no easy way to distinguish between both usage.

`[[maybe_unused]]` can be used the same way with the bonus that it bloats the readability of the code. One have to visually trim the syntax to understand what is going on and access the information.

`[[maybe_unused]] auto foo = bar()` is all wrong to my eyes. The user has to decide the type or not, declare a name that does not conflict in with the rest of the names, and fortunately copy elision is mandatory else we would have a variable copy bonus... In contrast, `discard(bar())` is less typing, does not force the user to makes decisions and can be easily grepped...

**Comment by mhermier** [comment]
This patch can wait. I'm pretty sure it will become relevant one day, when one will have to dig for some obscure bug related to some manually discarded value, and grep'ing was too much harder than it should have been.

**Comment by alimpfard** [comment]
> `[[maybe_unused]]` can be used the same way with the bonus that it bloats the readability of the code

Note that we don't really have ignored `nodiscard` values that have trivial destructors (i.e. we don't need to specify `[[maybe_unused]]` for, they have a lifetime, and that's a "use").
This only really matters with things that have trivial dtors like PODs, references, etc - and...`(void)`'ing those can hardly ever create bugs when their lifetime simply _doesn't matter_ imo

**Comment by mhermier** [comment]
Unless I'm mistaken, `[[maybe_unused]]` can lead to unnecessary copying in the following scenario:
```
[[nodiscard]] Foo const& foo();
[[maybe_unused]] auto bar = foo();
```

**Comment by mhermier** [comment]
Updated. Now `discard`ed values cannot be of type `Error` or `ErrorOr<T>`. Fortunately we don't had that usage in the code.

**Comment by mhermier** [comment]
Updated.
Now `discard(ErrorOr<T>)` with an error will print a stack trace in kernel land, and abort in user land. It catch (at least) one problematic code-path in the kernel, in `TestTLS` where a closed socket is being closed again.

**Comment by paulwratt** [comment]
Hmm.. Contraversial _AND_ Useful. Who would have thought?

**Comment by linusg** [comment]
I don't think we'll merge this.

**Pull request closed without merging**
