### PR TITLE
Base: Add the flag emoji for Hesse (DE-HE)

### PR DESCRIPTION
**Pull request by networkException**

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
Please run `optipng -strip all` over this, 5 kB for a few pixels is too much :)

(we're looking into enforcing that via CI for new PNGs)

**Comment by networkException** [comment]
Wow that was really a bunch of unnecessary bytes, I just assumed that gimp was somewhat storage efficient

**Comment by linusg** [comment]
I think most of it is Exif metadata, GIMP version etc.

**Review by linusg — APPROVED** [review]
Sehr schön! :^)

**Comment by networkException** [comment]
Danke! :^)

**Pull request merged**
