### PR TITLE
Kernel: Remove DiskCache entirely

### PR DESCRIPTION
**Pull request by supercomputer7**
We will re-introduce caching, but the DiskCache design is utterly incapable of figuring what are the important things to cache or not.

This decreases boot times by half on my machine (from about 4 seconds to 2 seconds), so this is an actual improvement that we should keep in future filesystem cache design.

### CODE REVIEW

**Comment by Panky-codes** [comment]
While I am 100% onboard with filesystem cache in the future instead of disk cache, I don't completely agree with removing the disk cache entirely. When I did some changes recently to the disk cache, I tried to add some counters to measure cache hit and it was pretty high in my experiment once we have a running system. 

I agree that the boot might be slow because we need to fill them up but we need to measure the cache hit on a running system. You might not notice the perf impact while running it on QEMU because each storage access might be just access to the page cache of the host and not the actual device (in the case of bare metal). 

As people are trying to boot with old hardware to test out serenity, I wonder how much slower it will be to access a rotating disk every time if we don't have the disk cache at all(even if the cache hit ratio is low). On top of that, our block layer doesn't batch IOs before sending them to the device, which makes the problem even worse.

I would rather remove the disk cache after we add the filesystem cache. Let me know what you think.

**Comment by supercomputer7** [comment]
> While I am 100% onboard with filesystem cache in the future instead of disk cache, I don't completely agree with removing the disk cache entirely. When I did some changes recently to the disk cache, I tried to add some counters to measure cache hit and it was pretty high in my experiment once we have a running system.
> 
> I agree that the boot might be slow because we need to fill them up but we need to measure the cache hit on a running system. You might not notice the perf impact while running it on QEMU because each storage access might be just access to the page cache of the host and not the actual device (in the case of bare metal).
> 
> As people are trying to boot with old hardware to test out serenity, I wonder how much slower it will be to access a rotating disk every time if we don't have the disk cache at all(even if the cache hit ratio is low). On top of that, our block layer doesn't batch IOs before sending them to the device, which makes the problem even worse.
> 
> I would rather remove the disk cache after we add the filesystem cache. Let me know what you think.

As much as I am a bare metal advocate, bare metal is not our top priority. Yes, it might be slower. We can't say a lot without testing and giving definitive numbers on the matter, so my guess or your guess could be thrown to the air but will not hold a much in serious discussion.

As @Hendiadyoin1 said on the discord server ([here](https://discord.com/channels/830522505605283862/830525093905170492/1116475899429269577)) we don't actually benefit from the current design, in such a way that it only stands in our way to create a better one, while having actual good IO results.
Caches work, but I rather have no cache than a very bad cache design that makes booting a lot more slow. 

We could have this commit being merged and put a new PR where we try to address this problem, while trying to keep the results as they were here :)

**Comment by GMTA** [comment]
Do you have some before/after measurements after booting? Starting up applications, reading/writing files, etc.?

**Comment by supercomputer7** [comment]
I measured the boot times again, it seems like we only now gain a few hundreds of milliseconds (not 2 seconds).
However, writing is faster with disk-cache, and reading is slightly faster, so we should keep it for now.
Marking this as a draft, because I will try to replace disk cache with fs cache.

**Comment by supercomputer7** [comment]
I will put it as closed for now, because it will take some time before I can improve on this.

**Pull request closed without merging**
