### PR TITLE
Kernel: Mark a bunch of syscalls as not needing the big process lock.

### PR DESCRIPTION
**Pull request by IdanHo**
~8~7 syscalls down, ~20~21 more to go.

### CODE REVIEW

**Comment by supercomputer7** [comment]
Some of these syscalls are addressed here - #20891. I need to review Andrew's comments. Are you sure it's OK to remove the big lock on those syscalls? I had to do some work there...

**Comment by IdanHo** [comment]
As far as I can tell, the only syscalls we have in common in the PRs are ioctl, create_thread & allocate_tls, and it looks like the changes you make in your PR are for other syscalls.
Regarding allocate_tls specifically, I believe the change I made to spinlock protect m_master_tls_region in the first commit in this PR is required for allocate_tls to be safe.

**Comment by IdanHo** [comment]
Changing this to WIP since I think the VP9 timeouts might be related to the changes, investigating

**Comment by IdanHo** [comment]
Ok, the issue is the sys$futex commit, while it's true the futex implementation does not use any big lock protected resources under process, it is still implicitly assuming the whole futex syscall is serialized using it, AKA the implementation is not correct in some way. For now I'll drop the commit from this PR, and will take a look into fixing it more thoroughly in a separate one.
Note that even with the process lock, the implementation would still be wrong, since the process lock would not serialize cross-process futex syscall, meaning even without any changes futex will currently cause deadlocks on SMP enabled.

**Pull request merged**
