### PR TITLE
Ports: Add mruby port

### PR DESCRIPTION
**Pull request by dantecatalfamo**
This is my first PR on serenityOS, sorry if I make any mistakes!

Mruby is a lightweight implementation of the ruby programming language.

I've been watching SerenityOS for a while and thought I would finally dive in. Being a ruby fan I thought this would be a great place to start :^).

I've submitted the crossbuild config to the mruby repository [here](https://github.com/mruby/mruby/pull/5533), so hopefully that patch can get removed in the next release.

### CODE REVIEW

**Comment by IdanHo** [comment]
We do not accept fixup commits for commits in the same PR, fixup commits should be squashed into the original commits instead.

**Comment by dantecatalfamo** [comment]
Squashed :slightly_smiling_face:

**Comment by dantecatalfamo** [comment]
The upstream crossbuild config got merged in, I should be able to remove the crossbuild patch when the next version comes out :slightly_smiling_face: https://github.com/mruby/mruby/pull/5533

**Review by kennethmyhra — APPROVED** [review]
Tested by using `mirb` in the shell. Port LGTM

**Pull request merged**
