### PR TITLE
LibCpp: Regression tests for the Parser

### PR DESCRIPTION
**Pull request by itamar8910**
For regression testing, the resulting AST of parsing .cpp files is compared to the baseline that's stored in .ast files.
To run the parser tests: `/usr/Tests/LibCpp/test-cpp-parser`.

Oh and don't worry about the large diff numbers, most of it is 34b3c64 & test data :sweat_smile:

### CODE REVIEW

**Comment by alimpfard** [comment]
Do consider using `LibTest/JavaScriptTestRunner.h` if the tests would benefit from a scripted environment :^)

**Comment by itamar8910** [comment]
> Do consider using `LibTest/JavaScriptTestRunner.h` if the tests would benefit from a scripted environment :^)

Sounds useful, I couldn't find this file though?

**Comment by alimpfard** [comment]
It lives here: https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibTest/JavaScriptTestRunner.h

For an example, see test-web:
https://github.com/SerenityOS/serenity/blob/master/Tests/LibWeb/test-web.cpp

**Comment by itamar8910** [comment]
Oh right I wasn't on the latest master. I'll check it out, moving this PR to draft in the meantime :+1:

**Comment by linusg** [comment]
Typo in AST output: `NumricLiteral`

**Comment by alimpfard** [comment]
Looks like LibCpp doesn't produce JavaScript-friendly output, so a test-js style testrunner might not be the best option here ^^'

**Comment by itamar8910** [comment]
> Looks like LibCpp doesn't produce JavaScript-friendly output, so a test-js style testrunner might not be the best option here ^^'

Got it. Maybe in the future if we switch the AST dump to produce JSON.

**Pull request merged**
