### PR TITLE
LibGUI: Read and write clipboard metadata to json

### PR DESCRIPTION
**Pull request by mkanilsson**
This PR adds support for reading and writing metadata in `Clipboard::DataAndType:::from_json()` and `Clipboard::DataAndType::to_json()`, respectively.

The `metadata` field will only be set if there is metadata to store.

### CODE REVIEW

**Comment by nico** [comment]
I'm not super familiar with this area – what's the effect of this PR?

**Comment by LucasChollet** [comment]
From what I remember (I'm the author of that FIXME, but it feels that I did that forever ago), metadata fields are what we use to save image/files in the clipboard. Or at least stuff big enough for me to consider it silly to save them in a JSON. Especially as this JSON file is read and written quite often.

**Comment by mkanilsson** [comment]
Yes, like Lucas said, the metadata field is used for things like images, their size, format and so on. They are also used for glyphs in the font editor. More information can be found here https://github.com/SerenityOS/serenity/blob/master/Base/usr/share/man/man5/clipboard.md

Currently there isn't anything uses metadata AND saves it to disk as images and glyphs are only stored in memory.

I mostly did this PR to remove those FIXME's but it might be useful in the future if someone find a use-case for it.

**Comment by LucasChollet** [comment]
It's already a very nice improvement as it allows us to:
* Copy an image from Browser or the host (through the spice client) - or anything copying `image/x-serenityos`
* Reboot serenity
* Paste in PixelPaint - or anything supporting to paste `image/x-serenityos`

The issue that I see, and the reason I left it as a FIXME is that the file we save the clipboard history in is read and written quite often. Embedding images (so huge amount of bytes) written as ASCII is far from optimal and might cause lags. One suggestion would be to save the metadata as binary in separate files and only have keys linking to these files in the JSON. It would also come with its share of issues like the deletion of the files etc...

**Comment by nico** [comment]
Thanks for the details!

**Comment by mkanilsson** [comment]
I'm unsure that Lucas comment applies as the image data is store in the `data` field.

https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibGUI/Clipboard.cpp#L192

```json
{
    "data": "image data here",
    "mime_type": "image/x-serenityos",
    "metadata": {
        "not": "here"
    }
}
```

Metadata for images are: `width`, `height`, `scale`, `pitch` and `format`.

From my testing, mine types `images/x-serenityos` and `glyph/x-fonteditor` aren't saved to disk and won't show up in the clipboard history applet.

**Pull request merged**
