### PR TITLE
Add some emoji

### PR DESCRIPTION
**Pull request by treuks**
New:
1F37E fully-qualified     # 🍾 E1.0 bottle with popping cork
1F38D fully-qualified     # 🎍 E0.6 pine decoration
1F960 fully-qualified     # 🥠 E5.0 fortune cookie
1F985 fully-qualified     # 🦅 E3.0 eagle
1FAC5 fully-qualified     # 🫅 E14.0 person with crown

Modified:
1F5FE fully-qualified     # 🗾 E0.6 map of Japan

### CODE REVIEW

**Comment by nico** [comment]
While the new Japan is prettier, its shape is imho less recognizably Japan. (Just my 2c, feel free to ignore.)

**Comment by treuks** [comment]
perhaps i should get the old shape and merge them together?

**Comment by treuks** [comment]
oh right, that's what i forgot

**Review by davidot — APPROVED** [review]
Great, much smaller. Thanks!

(I don't have much opinions on the icons themselves)

**Review by AtkinsSJ — APPROVED** [review]
That eagle especially is :man_cook: :pinched_fingers: :heart: 

Edit: Ninja'd by Mr Kling himself. :laughing:

**Pull request merged**
