### PR TITLE
LibGfx: Scaffolding for reading ICC tag table

### PR DESCRIPTION
**Pull request by nico**
The idea is that we'll have one type for each tag type.
For now, this treats all tag types as unknown, but it puts most
of the infrastructure for reading tags in place.

---

Pretty underwhelming screenshot:

```
% Build/lagom/icc ~/src/Compact-ICC-Profiles/profiles/sRGB-v2-nano.icc
preferred CMM type: 'lcms'
version: 2.1.0
device class: DisplayDevice
data color space: RGB
connection space: PCSXYZ
creation date and time: 2018-03-20 05:14:29
primary platform: Microsoft
flags: 0x00000000
  embedded in file: no
  can be used independently of embedded color data: yes
device manufacturer: 'saws'
device model: 'ctrl'
device attributes: 0x0000000000000000
  media is reflective, glossy, of positive polarity, colored
rendering intent: Perceptual
pcs illuminant: X = 0.964202, Y = 1, Z = 0.824905
creator: 'hand'
id: eb771f3c-aa535102-e93e286c-9146ae57

tags:
'desc': 'desc', offset 240, size 95
'wtpt': 'XYZ ', offset 268, size 20
'rXYZ': 'XYZ ', offset 288, size 20
'gXYZ': 'XYZ ', offset 308, size 20
'bXYZ': 'XYZ ', offset 328, size 20
'rTRC': 'curv', offset 348, size 52
'gTRC': 'curv', offset 348, size 52
'bTRC': 'curv', offset 348, size 52
'cprt': 'text', offset 400, size 10
```

(The `tags:` part at the bottom is new in this PR.)

Future patches will extract actual data from the tag types and show that.

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
For `LibGfx: Scaffolding for reading ICC tag table`:

https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy
> Write the commit message subject line in the imperative mood

Code LGTM.

**Comment by nico** [comment]
> For `LibGfx: Scaffolding for reading ICC tag table`:
> 
> https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy
> 
> > Write the commit message subject line in the imperative mood

What would that mean here? "Add scaffolding for..."?

**Comment by linusg** [comment]
Yeah, something like that :)

**Comment by linusg** [comment]
Or "LibGfx: Scaffold..." if you want to game the system :stuck_out_tongue:

**Comment by nico** [comment]
Done!

**Pull request merged**
