### PR TITLE
FileManager: only allow one delete confirmation box at a time

### PR DESCRIPTION
**Pull request by DAlperin**
Only allow one delete confirmation box to be open at once. Previously hitting the delete key multiple times would open multiple confirmations on top of each other, the second of which would error.

### CODE REVIEW

**Comment by awesomekling** [comment]
This solution only addresses a specific scenario, but the problem is general.

We should instead fix this by scoping the action to the widgets that are allowed to use it.

It's currently possible to scope an action to a widget by passing an optional `GWidget*` argument to the action constructor. However, if you look in `GWindowServerConnection::handle(const WindowClient::KeyDown&)`, you can see that we only check for actions associated with the *currently focused* widget:

```cpp
    if (auto* focused_widget = window->focused_widget()) {
        if (auto* action = focused_widget->action_for_key_event(*key_event)) {
            if (action->is_enabled()) {
                action->activate();
                return;
            }
        }
    }
```

This will not work in the `FileManager` case, since there's a `DirectoryView` wrapper widget that contains both a `GItemView` and a `GTableView`. Since we don't know ahead of time which sub-view will be focused in the future, we'd want to either:

* **a)** Associate the action with the `DirectoryView` and bubble up the widget ancestor chain in `GWindowServerConnection`
* **b)** Associate the action with all subviews of `DirectoryView`. This would require making it possible for an action to be associated with more than one widget at a time, through some API like `GWidget::add_action()` perhaps.

**Comment by DAlperin** [comment]
That makes sense now that I think about it. Let me give some solutions a shot.

**Comment by DAlperin** [comment]
I'm going to close this PR for now since the solution is going to be non-filemanager specific.

**Comment by sveilleux1** [comment]
As a note: still happening after #1078 fix.

**Pull request closed without merging**
