### PR TITLE
LibGfx/JPEG: Teach JPEGLoader how to be patient with non-compliant images [2/N]

### PR DESCRIPTION
**Pull request by LucasChollet**
Fix this image
exif-empty-icc-profile

### CODE REVIEW

**Review by nico — APPROVED** [review]
Test? :)

**Comment by nico** [comment]
(Also, do you know where the image is from? It technically _is_ a broken image, but this looks like something that does seem to happen in real life, sadly :/)

**Comment by LucasChollet** [comment]
> Test? :)

In TwelveMonkeys' repo, there is a text file, with something like "The usage fits under fair-use, but if it bothers you, tell me and I will delete the file". I don't know if we can do the same here.

> (Also, do you know where the image is from? It technically is a broken image, but this looks like something that does seem to happen in real life, sadly :/)

The original author only gave a link to a google drive.
I don't know if you're aware of that, but there is a [super neato software](https://github.com/nico/hack/blob/6646852f40be0a95ce65ba55f306723a8d414ec0/jpeg_exif_dump.c) that gives you all the information about the encoder (if you trust the exif data).
So I guess that it was first encoded by Adobe and baddly stripped by "ACD Systems Digital Imaging"

**Comment by AtkinsSJ** [comment]
Including that image in the repo does seem a bit legally dubious. Maybe modify an image we do have rights to, to have the same error in it?

I'm happy to merge without that, but tests are tasty.

**Comment by LucasChollet** [comment]
> Maybe modify an image we do have rights to, to have the same error in it?

Let's be honest, my laziness prevented me to do that, but it actually wasn't complicated at all. Hope that both of you enjoy that test!

**Comment by AtkinsSJ** [comment]
:tada:

I'm also lazy about adding tests. :laughing:

**Pull request merged**
