### PR TITLE
LibGUI: Wrap the EmojiInputDialog in a scrollable container and add a search box

### PR DESCRIPTION
**Pull request by trflynn89**
emoji1
emoji2
emoji3

### CODE REVIEW

**Comment by trflynn89** [comment]
I was going to add a search box as well, but we don't have emoji code point names available with the way we're currently loading available emoji. We'd have to link in LibUnicode, which is a hefty price for every app to load.

It might make sense to break LibUnicode into LibUnicode (for UCD data) and LibLocale (for CLDR data). The UCD data is much much smaller, and is what would be used here, so it'd be much less costly. Then LibLocale's only user would be LibJS (and whoever uses LibJS).

**Comment by djwisdom** [comment]
And such a timely love for Emoji Dialog box it is :^)

**Comment by linusg** [comment]
> We'd have to link in LibUnicode, which is a hefty price for every app to load.

Perhaps it would make sense to make the emoji picker a standalone application instead of being baked into each GUI app. The shortcut can be the same, just on a global level. This would also make it work with non-LibGUI applications.

**Comment by trflynn89** [comment]
> Perhaps it would make sense to make the emoji picker a standalone application instead of being baked into each GUI app. The shortcut can be the same, just on a global level. This would also make it work with non-LibGUI applications.

That can probably work as long as we can get and insert the selected emoji still, maybe either some IPC or just get `ConnectionToWindowServer` to listen to the launched app's stdout

**Comment by trflynn89** [comment]
Thinking about a separate app some more, one downside is that this would require every app to have `exec` permissions. Or maybe WindowServer could launch the dialog on the app's behalf, not sure if that's out of scope for WindowServer though

**Comment by trflynn89** [comment]
Kept it in LibGUI for now, and added a search box linked against LibUnicode now that #15096 makes that much less of an issue.

**Review by linusg — APPROVED** [review]
Stellar work!

**Comment by trflynn89** [comment]
Credit for titlecasing the emoji names + a couple layout fixes go to @electrikmilk! Some `co-author` lines unfortunately got dropped in a rebase.

**Pull request merged**
