### PR TITLE
UE: Some more comments; AK: Add sincos helper

### PR DESCRIPTION
**Pull request by Hendiadyoin1**
Some stuff that I found trying to find out why tgamma and Cube don't work propperly.
Sadly no fixes....

On the sincos thing:
I don't like the semantics, would a structured binding be appropriate here?

### CODE REVIEW

**Comment by awesomekling** [comment]
From Wikipedia (emphasis mine):
> In computer programming and software design, code refactoring is the process of restructuring existing computer code—changing the factoring—**without changing its external behavior**.

Hence, "refactor X to be a bit more correct" doesn't read quite right! Could you please write what's being fixed instead? :^)

**Comment by awesomekling** [comment]
> Error: One or more of the commits in this PR do not match the code submission policy:
> `UserspaceEmulator: Make error checks in FYL2XP1 and FYL2X a bit closer` (89f13b8a2c12530dd5c1c8df546b5c6664f290ea):
> **Empty line between commit title and body is missing**

**Comment by linusg** [comment]
ping @Hendiadyoin1

**Comment by Hendiadyoin1** [comment]
Yes I will work on this this weekend

**Review by awesomekling — APPROVED** [review]
Oops, this now has a conflict in LibDSP. Otherwise, it looks great!

**Comment by Hendiadyoin1** [comment]
Resolved that conflict

**Pull request merged**
