### PR TITLE
Ports/quake: Convert to in-tree format with patches

### PR DESCRIPTION
**Pull request by lightspot21**
This PR serves to obsolete https://github.com/SerenityPorts/SerenityQuake by re-making the port (same version) in the usual package.sh + patches format.

Although version 0.70 is available upstream, it needs OpenGL primitives that are not implemented yet (such as GL_VERTEX_PROGRAM_ARB) and a couple other functions which I don't have the time to implement yet. 

Anyone wishing to take up the OpenGL work for 0.70 is more than welcome to do so.

### CODE REVIEW

**Comment by GMTA** [comment]
Hey @lightspot21! I'm not seeing all the patches that are in https://github.com/SerenityPorts/SerenityQuake/commits/master for example, how does that work?

**Comment by timschumi** [comment]
Yeah, this looks like it's missing quite a lot of stuff. It's unclear why there are suddenly more configure flags (since a "convert to in-tree patches" commit should result in the patched source code being basically 1-to-1 with what we had before, with the exception of consolidated and/or no longer necessary patches). We are also missing all of the startup code as far as I can tell.

**Comment by lightspot21** [comment]
Oops, looks like this goes to the draft status then? Thought that since this was an old port most patches wouldn't be necessarily needed, so I started from scratch to see what is actually needed to compile and run. 

@timschumi what do you mean by more configure flags? Only difference I could find with a quick check is pulling TARGET_CD = null out of the makefile, and TARGET_UNIX=serenity, which I made for convenience.

**Comment by timschumi** [comment]
Sorry, I meant the make options, not the configure options.

I'm also not saying that what you are doing is incorrect (obviously, bringing up Serenity as a UNIX-like target instead of rolling our own completely makes a lot of sense), but having an import with no real functional changes and then moving stuff around afterwards is a lot more comfortable for tracking down issues after the fact. :^)

**Comment by GMTA** [comment]
Note that not all patches have to do with the game's functionality; for example, [this commit](https://github.com/SerenityPorts/SerenityQuake/commit/aa6273f15bcfc07f8aa9376fbcc0f5eaa94b59a7) makes sure we don't get spammed to death when debugging LibGL.

**Pull request closed without merging**
