### PR TITLE
git is required by Meta/serenity.sh rebuild-toolchain

### PR DESCRIPTION
**Pull request by ooxi**

### CODE REVIEW

**Comment by timschumi** [comment]
One can't obtain a proper copy of the `serenity` repository without Git, so this is already an implicit dependency anyways.

**Comment by ooxi** [comment]
> One can't obtain a proper copy of the serenity repository without Git, so this is already an implicit dependency anyways.

https://github.com/SerenityOS/serenity/archive/refs/heads/master.zip

Moreover https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructions.md#serenityos is listing git, too.

**Comment by BertalanD** [comment]
> https://github.com/SerenityOS/serenity/archive/refs/heads/master.zip

Sure, you could do that. But even if git is installed, building from a ZIP archive will fail as basically *all* our scripts call out to `git rev-parse --show-toplevel` to determine where the root of the source tree is *and* ZIP cannot contain UNIX file permissions so our scripts will not be executable.

**Comment by ooxi** [comment]
I mean sure, continue to see git is an implicit rather than an explicit dependency ^^

I only opened this issue since I was hit by it, trying to build serenity following your instructions.

**Comment by BertalanD** [comment]
Just to clarify, I don't think that making the list of obvious-but-explicit dependencies uniform across all platforms is a bad idea &ndash; just please fix up the commit title to match the guidelines.

We should, however, find a way to discourage people from using the GitHub-generated source archives. Of course, it's not something that you specifically need to do in this PR.

**Comment by oskar-skog** [comment]
The ZIP format does support POSIX permissions (except setuid/setgid), but they're not being used by Github for whatever reason.

**Pull request closed without merging**
