### PR TITLE
VimEditingEngine: Prevent crash upon 'x' or 'v' on blank lines

### LINKED ISSUE #8769: TextEditor: App crashes when cutting from empty lines
Steps to reproduce:

1. Turn on Vim mode (Edit -> Vim emulation).
2. Insert a blank line (i.e. there should be at least two lines in the file).
3. Navigate to the first line and hit "x".

```
CrashDaemon(20:20): --- Backtrace for thread #0 (TID 34) ---
CrashDaemon(20:20): 0x248c81ce: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
CrashDaemon(20:20): 0x39caab44: [libc.so] raise +0x24 (syscall.h:34 => signal.cpp:20)
CrashDaemon(20:20): 0x39c949e5: [libc.so] abort +0x29 (stdlib.cpp:230)
CrashDaemon(20:20): 0x39c954ca: [libc.so] __assertion_failed +0xea (assert.cpp:31)
CrashDaemon(20:20): 0xbc498c8e: [libgui.so] GUI::TextDocument::text_in_range(GUI::TextRange const&) const +0x23e (Utf32View.h:71)
CrashDaemon(20:20): 0xbc4c020c: [libgui.so] GUI::VimEditingEngine::yank(GUI::TextRange) +0x8c (VimEditingEngine.cpp:1227)
CrashDaemon(20:20): 0xbc4c1bef: [libgui.so] .L1681 +0x8f (VimEditingEngine.cpp:969)
CrashDaemon(20:20): 0xbc4a7361: [libgui.so] GUI::TextEditor::keydown_event(GUI::KeyEvent&) [clone .localalias] +0x151 (TextEditor.cpp:818)
CrashDaemon(20:20): 0xbc4c9ace: [libgui.so] GUI::Widget::handle_keydown_event(GUI::KeyEvent&) +0x2e (Widget.cpp:313)
CrashDaemon(20:20): 0x2f158a00: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb0 (Object.cpp:213)
CrashDaemon(20:20): 0xbc4dbb4c: [libgui.so] GUI::Window::handle_key_event(GUI::KeyEvent&) +0xcc (Window.cpp:450)
CrashDaemon(20:20): 0xbc4e4319: [libgui.so] GUI::Window::event(Core::Event&) +0x109 (Window.cpp:586)
CrashDaemon(20:20): 0x2f158a00: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb0 (Object.cpp:213)
CrashDaemon(20:20): 0x2f1401e9: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x3e9 (EventLoop.cpp:398)
CrashDaemon(20:20): 0x2f1409fa: [libcore.so] Core::EventLoop::exec() +0x5a (EventLoop.cpp:362)
CrashDaemon(20:20): 0xbc3b5617: [libgui.so] GUI::Application::exec() +0x27 (Application.cpp:106)
CrashDaemon(20:20): 0x216fb840: [/bin/TextEditor] main +0x840 (main.cpp:130)
CrashDaemon(20:20): 0x216fbdc7: [/bin/TextEditor] _entry +0x57 (crt0.cpp:45)
```

### PR DESCRIPTION
**Pull request by arieldon**
Previously, pressing 'x' for deletion on an otherwise empty line insinuated a crash in TextEditor because TextRange aimed to select and use a nonexistent code point -- likewise for visual mode with 'v'.

This patch fixes #8769.

### CODE REVIEW

**Comment by blishko** [comment]
It seems to me there is a deeper issue here.
I can still crash TextEditor after this fix in the following way:

1. Insert some text on first line.
2. Press Enter to get to the second line, which will be empty.
3. Switch to VIM emulator mode.
4. Switch to visual mode (using `v`).
5.  Press up arrow to try to move to the first line => crash.

Here is the stack trace:
```
CrashDaemon(20:20): --- Backtrace for thread #0 (TID 31) ---
CrashDaemon(20:20): 0x77da81ce: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
CrashDaemon(20:20): 0x8be07bc4: [libc.so] raise +0x24 (syscall.h:34 => signal.cpp:20)
CrashDaemon(20:20): 0x8bdf1a05: [libc.so] abort +0x29 (stdlib.cpp:230)
CrashDaemon(20:20): 0x8bdf24ea: [libc.so] __assertion_failed +0xea (assert.cpp:31)
CrashDaemon(20:20): 0x2e6daeee: [libgui.so] GUI::TextDocument::text_in_range(GUI::TextRange const&) const +0x23e (Utf32View.h:71)
CrashDaemon(20:20): 0x2e6e1a8b: [libgui.so] GUI::TextEditor::selected_text() const [clone .localalias] +0x7b (TextEditor.cpp:1277)
CrashDaemon(20:20): 0x3d82053e: [/bin/TextEditor] TextEditor::MainWidget::update_statusbar() +0x1ae (MainWidget.cpp:806)
CrashDaemon(20:20): 0x2e6e74c1: [libgui.so] GUI::TextEditor::did_update_selection() [clone .localalias] +0x101 (Function.h:91)
CrashDaemon(20:20): 0x2e701ab6: [libgui.so] GUI::VimEditingEngine::update_selection_on_cursor_move() +0x186 (VimEditingEngine.cpp:1249)
CrashDaemon(20:20): 0x2e7039e8: [libgui.so] .L1597 +0x108 (VimEditingEngine.cpp:1094)
CrashDaemon(20:20): 0x2e6e95c1: [libgui.so] GUI::TextEditor::keydown_event(GUI::KeyEvent&) [clone .localalias] +0x151 (TextEditor.cpp:818)
CrashDaemon(20:20): 0x2e70cdae: [libgui.so] GUI::Widget::handle_keydown_event(GUI::KeyEvent&) [clone .localalias] +0x2e (Widget.cpp:313)
CrashDaemon(20:20): 0x10dffa00: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb0 (Object.cpp:213)
CrashDaemon(20:20): 0x2e71ee2c: [libgui.so] GUI::Window::handle_key_event(GUI::KeyEvent&) [clone .localalias] +0xcc (Window.cpp:450)
CrashDaemon(20:20): 0x2e7275f9: [libgui.so] GUI::Window::event(Core::Event&) +0x109 (Window.cpp:586)
CrashDaemon(20:20): 0x10dffa00: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb0 (Object.cpp:213)
CrashDaemon(20:20): 0x10de71e9: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x3e9 (EventLoop.cpp:398)
CrashDaemon(20:20): 0x10de79fa: [libcore.so] Core::EventLoop::exec() +0x5a (EventLoop.cpp:362)
CrashDaemon(20:20): 0x2e5f7757: [libgui.so] GUI::Application::exec() +0x27 (Application.cpp:106)
CrashDaemon(20:20): 0x3d816840: [/bin/TextEditor] main +0x840 (main.cpp:130)
CrashDaemon(20:20): 0x3d816dc7: [/bin/TextEditor] _entry +0x57 (crt0.cpp:45)
```

**Comment by arieldon** [comment]
@blishko You're right -- it turns out I did not properly handle the issue with the last commit, but I think the new changes fix it, at the very least I am able to press 'x' for delete on an empty line without crash, as well as select an empty line with 'v' and move up (and down). I removed the original changes because they were no longer necessary as far as I can tell.

**Comment by blishko** [comment]
@arieldon, the new version seems to work nicely!

**Comment by gunnarbeutner** [comment]
CI currently fails for this because of some required reformatting of your code changes. :)

**Comment by arieldon** [comment]
@gunnarbeutner I reformatted the lines of code that caused issue.

**Pull request merged**
