### PR TITLE
Kernel: Storage hot plug advancements #2

### PR DESCRIPTION
**Pull request by supercomputer7**

### CODE REVIEW

**Comment by supercomputer7** [comment]
This is waiting for a review...
cc @awesomekling

**Comment by mjz19910** [comment]
- These commits may not be useful changes
   - Kernel/FileSystem: Stop writing cache if received EIO error
     - How do we recover from this, the cache should not be marked as clean, we need to retry a limited number of times and/or propagate the error after we are convinced the device will not recover(sometimes you get flaky hdds, eventually the data will read correctly, or maybe not... and really, in that case, this should be logged)
   - Kernel/WorkQueue: Introduce new WorkQueue for AHCI operations
     - Can't we just use the io queue for ahci ops, explain a use case or wait until you find a case you require the io work queue to do stuff that does not fit well, then maybe you need a queue for ahci operations... When certain ordering is needed to avoid a crash, then maybe the queue needs a priority, or you need a seperate queue...

- These commits would be better as separate pull requests
  - Kernel/Ext2FileSystem: Don't use buffer on the stack when traversing
  - Kernel/DevTmpFS: Enable support for InodeWatchers
 
- These may be somewhat useful, cherry-pick these commits as a separate pull request
  - Kernel/AHCI: Assert if m_connected_device is null
  - Kernel/Storage: Narrow AHCI port index from 32 bits to 8 bits

There is no real topic for this pull request, i look at the commits, and they seem all over the place, why is the DevTmpFS included, it might be a storage improvement, but not really related to hot plug...

**Comment by supercomputer7** [comment]
>     * These commits may not be useful changes
>       
>       * Kernel/FileSystem: Stop writing cache if received EIO error
>         
>         * How do we recover from this, the cache should not be marked as clean, we need to retry a limited number of times and/or propagate the error after we are convinced the device will not recover(sometimes you get flaky hdds, eventually the data will read correctly, or maybe not... and really, in that case, this should be logged)
>       * Kernel/WorkQueue: Introduce new WorkQueue for AHCI operations
>         
>         * Can't we just use the io queue for ahci ops, explain a use case or wait until you find a case you require the io work queue to do stuff that does not fit well, then maybe you need a queue for ahci operations... When certain ordering is needed to avoid a crash, then maybe the queue needs a priority, or you need a seperate queue...
> 

I'm certainly no expert on how to do this in a perfect way, but it seems very bad to re-iterate on writing cache if there's a EIO error (because of disk error) - it doesn't crash the OS, but the system is almost completely stuck which is not good. If you have suggestions on how to better handle such case, please let me know.
For AHCI WorkQueue, look at #9646 on why I'm doing this. I try to commit simple changes, I'm not against multiple PRs but there's one goal I'm working on and these commits are the way to move forward IMO.

>     * These commits would be better as separate pull requests
>       
>       * Kernel/Ext2FileSystem: Don't use buffer on the stack when traversing
>       * Kernel/DevTmpFS: Enable support for InodeWatchers
> 
You might be right about this, but the overall goal is to advance through a `udev` program so all of this is in place to do this.
>     * These may be somewhat useful, cherry-pick these commits as a separate pull request
>       
>       * Kernel/AHCI: Assert if m_connected_device is null
>       * Kernel/Storage: Narrow AHCI port index from 32 bits to 8 bits
> 
> 
I certainly agree this seems a bit off, but it all comes from this #9646 pull request.
> There is no real topic for this pull request, i look at the commits, and they seem all over the place, why is the DevTmpFS included, it might be a storage improvement, but not really related to hot plug...

The idea was to get prepared to creating a `udev` daemon for Serenity, that's why DevTmpFS needs to be ready for such thing.

**Comment by supercomputer7** [comment]
I'll re-send this and more patches in separate PRs.

**Pull request closed without merging**
