### PR TITLE
PixelPaint: Use background color when cropping layer to content

### PR DESCRIPTION
**Pull request by tcl3**
This PR expands the functionality of the "Crop Image to Content" and "Crop Layer to Content" features by allowing them to detect and crop the background color of an image instead of just cropping transparent pixels.

The background color is determined by looking at the corner pixels of the image. If no background color is found, the old behavior of cropping transparent pixels is retained.

Video:

https://user-images.githubusercontent.com/2817754/213524406-a02ed9a0-ad8c-40a8-9b5f-c9c4c95a051b.mp4

### CODE REVIEW

**Comment by GMTA** [comment]
If I have a transparent layer with a big red "X" reaching all the way into the corners, would it then just disregard the entire layer?

**Comment by tcl3** [comment]
Do you mean like this?

image

That will stay as it is, because an entire vertical or horizontal line must be the same color, or be transparent if there is no solid background, in order to be cropped.

**Comment by GMTA** [comment]
> That will stay as it is, because an entire vertical or horizontal line must be the same color, or be transparent if there is no solid background, in order to be cropped

That could work!

**Comment by awesomekling** [comment]
Great improvement :)

**Pull request merged**
