### PR TITLE
Base: Add new theme Chillychilly

### PR DESCRIPTION
**Pull request by djwisdom**
For consideration on top of the already numerous themes :^)

Obligatory snapshot : 

image

### CODE REVIEW

**Comment by kleinesfilmroellchen** [comment]
Looks like the syntax highlighting colors would also benefit from being adjusted

**Comment by djwisdom** [comment]
Yes, I agree but even Default theme behaves the same with highlighted syntax.

image

**Comment by kleinesfilmroellchen** [comment]
That's not a reason to not have theme-specific syntax highlighting colors, when you can just copy those colors from the theme colors themselves :^)

**Comment by djwisdom** [comment]
Default theme syntax highlighting colors

image

Chillychilly theme syntax highlighting colors

image

Implemented theme-specific syntax highlighting colors. Muchas gracias for the tip. Now it looks much better. :^)
I will push this update pending feedback on this syntax highlighting color update.

**Review by kleinesfilmroellchen — APPROVED** [review]
Please squash the two commits.

**Pull request merged**
