### PR TITLE
LibWeb+LibGfx: Support stroke-linecap, stroke-linejoin property

### PR DESCRIPTION
**Pull request by zhiyuang**
To support stroke-linecap and stroke-linejoin:
1. Refactor `Path::stroke_to_fill` method. It previously used convolution algorithm to fill stroke path, the result is great but not flexible to implement stroke-linejoin property. So this time refactoring this method to a simple algorithm, just computing parallel lines of splited path lines as the path offsets.
2. Refactor `Painter::for_each_line_segment_on_cubic_bezier_curve` method from an iterative approach to a recursive approach. This change is for ensuring the callback executed in order in the path from the start to end. This is important when doing the line join.

image

Right now `stroke-linejoin` supports `miter`, `bevel`, `round`, `arcs` and `miter-clip` will be implemented in future.

### CODE REVIEW

**Comment by MacDue** [comment]
I plan to try this out soon, I've just been a little busy the past few days :)

**Comment by zhiyuang** [comment]
no problem, take your time 😄

**Comment by MacDue** [comment]
Just done a quick test and found if I zoom to >= 200-300% on `Base/res/html/misc/svg.html` WebContent freezes with my CPU stuck at a 100%.

There also seems to be a slight regression on:
```
<!doctype html>
<svg
  width="480"
  height="480"
  viewBox="0 0 480 480"
>
  <path
    d="M306.85 275.36c-53.53 91.82-124.62 150.42-158.78 130.89-34.16-19.53-18.46-109.8 35.08-201.61 53.53-91.82 124.62-150.42 158.78-130.89 34.16 19.53 18.46 109.8-35.08 201.61Z"
    fill="black"
    fill-opacity=".1"
    stroke="black"
    stroke-width="100"
  ></path>
</svg>
```

As a gap has now appeared:
Screenshot from 2023-08-04 20-18-49

**Comment by zhiyuang** [comment]
thanks! Let me check 🤔

**Comment by zhiyuang** [comment]
It spends me some time to debug..

**Comment by zhiyuang** [comment]
It spends me some time to debug... In a short word, these two bugs are all related to float precision.

1. For the `Base/res/html/misc/svg.html`, the code that cause the issue is:

```
<svg height="500" width="500">
  <g fill="none" stroke="red" stroke-width="5">
    <path d="M 300,300 l 30,10
             a 10,10 20 0,1 30,10 l 30,10
             a 10,20 20 0,1 30,10 l 30,10
             a 10,30 20 0,1 30,10 l 30,10
             a 10,40 20 0,1 30,10 l 30,10 z">
              </path>
  </g>
</svg>
```
The root cause is that after zooming in and the point scaling, the intersect point computing become incorrect. For the path closing part, when computing the intersect point between last segment and the first segment, they become not parallel anymore (which are parallel indeed). The computed intersect point become too large, which consumes the cpu to draw. 
The related code snippets: 
```
// FIXME: 0.01 is an experimental number. If denom is too small, then t will be too large.
if (AK::abs(denom) < 0.01f) {
       return {};
}
```

**Comment by zhiyuang** [comment]
2. For this sample:
```
<!doctype html>
<svg
  width="480"
  height="480"
  viewBox="0 0 480 480"
>
  <path
    d="M306.85 275.36c-53.53 91.82-124.62 150.42-158.78 130.89-34.16-19.53-18.46-109.8 35.08-201.61 53.53-91.82 124.62-150.42 158.78-130.89 34.16 19.53 18.46 109.8-35.08 201.61Z"
    fill="black"
    fill-opacity=".1"
    stroke="black"
    stroke-width="100"
  ></path>
</svg>
```

The root cause is still float precision. This svg path consists of 1 move segment and 4 cubic bezier curve segment and last point is same as beginning point to become closed in nature. But because float precision, in our system right now, this path consist of 1 move segment, 4 cubic bezier curve segment and 1 line segment. Because the checking of the closed path become unsatisfied after float computing:

```
if (segment->type() == Segment::Type::MoveTo) {
      if (last_point == segment->point()) // this does not equal anymore
          return;
      append_segment<LineSegment>(segment->point());
      invalidate_split_lines();
      return;
  }
```
As a result, it appends a randomly generated line segment because of float precision. Then generating this line segment offset path, it cause a blank line in the painting.

**Comment by zhiyuang** [comment]
@MacDue do you have any suggestions on this, are there any existed solutions in the project to handle float precision?

**Comment by MacDue** [comment]
I've not had a proper look at the code yet (so no suggestions there), but I do remember when I was looking for a method of implementing `stroke_to_fill()` I came across https://w3.impa.br/~diego/projects/Neh20/index.html, which seems to handle the various joins (and more), and claims their approach works well at single precision. I've not looked at in much detail though, and ultimately implemented something much simpler for the initial implementation. It might contain some ideas that help fix these issues though.

**Pull request closed without merging**
