### PR TITLE
Ports: add libvorbis

### PR DESCRIPTION
**Pull request by ElectrodeYT**
Add libvorbis port.

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
Please add this to https://github.com/SerenityOS/serenity/blob/master/Ports/AvailablePorts.md

**Comment by ElectrodeYT** [comment]
Sorry, just did!

**Comment by linusg** [comment]
Please also squash all of these commits into one as per the [contibution guidelines](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy) :)

**Comment by ElectrodeYT** [comment]
Yea sorry, i was doing that, i had a minor case of unexpected earth quake that got in the way.

We dont really have them here lol

**Comment by awesomekling** [comment]
Please use unified diff format for patches (`diff -u`)
Also, no need to mention in commit messages that you did a squash :)

**Comment by ElectrodeYT** [comment]
Ok, done :)

**Comment by awesomekling** [comment]
Oh dang, this needs a conflict resolution before being merged. Sorry about that

**Comment by ElectrodeYT** [comment]
what have i done

**Comment by ElectrodeYT** [comment]
imma make a new pull request at this point, i severely mistyped the git command

**Comment by ElectrodeYT** [comment]
continued in #6048

**Pull request closed without merging**
