### PR TITLE
Ladybird/Qt: Introduce a hamburger menu and use by default

### PR DESCRIPTION
**Pull request by jamierocks**
image

### CODE REVIEW

**Comment by mzl01apq** [comment]
What's the usecase of hamburger menus?

**Comment by jamierocks** [comment]
> What's the usecase of hamburger menus?

The same as the menubar - to display available actions for the browser.

**Comment by mzl01apq** [comment]
> > What's the usecase of hamburger menus?
> 
> The same as the menubar - to display available actions for the browser.

It adds an extra click when you want to access the contents that were previously located in the menu bar.

**Comment by nico** [comment]
@mzl01apq you have 0 commits in this repo. Please keep your opinions to yourself. Opinions on UI aren't exactly a rare resource to be cherished. On the opposite: Everyone has an opinion on UI and it's to he celebrated when people manage to keep their opinion to themselves 🙂

**Pull request merged**
