### PR TITLE
Applets: Add DesktopPicker applet

### PR DESCRIPTION
**Pull request by Petelliott**
2021-07-18-125458_1920x1080_scrot

I only recently found out that serenity supports multiple virtual desktops. In order to make this feature more discoverable, I've added and applet that displays the current virtual desktop layout, the current virtual desktop, and lets users click on any virtual desktop to switch.

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
I think this is a good idea in general, but can we do something about requiring the user to pixel-perfectly click on a tiny spot on the screen? :)

**Comment by awesomekling** [comment]
> I think this is a good idea in general, but can we do something about requiring the user to pixel-perfectly click on a tiny spot on the screen? :)

What do you suggest? We already have the Ctrl+Alt+ArrowKey combo for moving between virtual desktops.

**Comment by gunnarbeutner** [comment]
I'm not entirely sure this is more useful, but how about:

Hovering over the icon opens the virtual desktop switcher in a speech bubble next to the icon. Clicking on the icon in the taskbar switches between the last two virtual desktops.

I think my main problem with the virtual desktop shortcuts is that they're not discoverable. For example a user doesn't have to know that Ctrl-C is a thing, because they can discover that by looking at the shortcut hints in the Edit menu. There's no such thing for the virtual desktop though.

**Comment by tomuta** [comment]
> > I think this is a good idea in general, but can we do something about requiring the user to pixel-perfectly click on a tiny spot on the screen? :)
> 
> What do you suggest? We already have the Ctrl+Alt+ArrowKey combo for moving between virtual desktops.

Well maybe do some menu-style popup? I mean it works fine with 2x2 but 4x4 or 8x8 would get what, maybe a pixel each? ;-)

**Comment by tomuta** [comment]
I do however think this is a great first step and we should merge it as it is. We can always improve upon it.

**Comment by gunnarbeutner** [comment]
Sure, works for me. :)

**Pull request merged**
