### PR TITLE
LibGui+WindowServer: Offset applications that are opened directly on eachother

### PR DESCRIPTION
**Pull request by Petelliott**
If you opened many terminals before they would be right on top of eachother, and it didn't look like anything happened.
This change should make it more obvious when you application opens, and make it easier to grab the old windows.

example:
2020-07-28-155650_3200x1800_scrot

### CODE REVIEW

**Comment by awesomekling** [comment]
It would be nice if this could just happen automagically instead of apps having to use an API for it.
How about this:
- All new windows start out in a special "WindowServer will choose the position" mode.
- WindowServer clients can override this mode by explicitly setting a position before showing the window.
- Most apps only specify initial window size instead of initial window rect.

**Comment by Petelliott** [comment]
How do you suggest WindowServer chooses the initial position?

Some ideas:
- Randomly. This will basically eliminate the purpose of this PR, but have the same desired effect.
- Based on a default for all apps, with an api to request a recommended position
- Based on a hash of the application, so the same app always opens at the same Location.

I personally like the hash one.

**Comment by awesomekling** [comment]
Another idea:
- At an offset from the last window that was opened with unspecified position and has not been moved by the user.

**Comment by Petelliott** [comment]
Sounds good. I'm going to make a new PR, because not much functionality is shared with this one

**Pull request closed without merging**
