### PR TITLE
Base: Add some latin ligatures to Csilla and Katica fonts

### PR DESCRIPTION
**Pull request by metalvoidzz**
ligatures
This patch adds ligatures for latin ſt, ff, fi, fl and st to
Csilla and Katica font variants.

### CODE REVIEW

**Comment by Hendiadyoin1** [comment]
The st looks a bit weird, if you ask me..
--- 
TIL there are ligatures for the long s...

**Comment by metalvoidzz** [comment]
Yeah, I was struggling with the round s a bit. What would you change about it?

**Comment by bgianfo** [comment]
CC: @Xexxa for their thoughts.

**Review by Xexxa — CHANGES_REQUESTED** [review]
The only issue I've found is the inconsistency between KaticaBold10 and KaticaBold12, except for KaticaBold10 all ligatures seems to be based on the Latin characters in each font and follow the Unicode charts, there is obviously always going to be compromises when a glyph has to fit in a small space.

Katicia Regular 10 has 10px width so it makes sense to give Katica Bold 10 the same, I'll pr that right away, then you will have the space to add the same serifs to KaticaBold10 as you have in the 12 version.

A couple of small issues regarding the PR itself, it makes things easier if the commit message contains the codepoints you added glyphs to:

>This patch adds ligatures for latin ſt(FB05), ff(FB00), fi(FB01), fl(FB02) and st(FB06) to
Csilla and Katica font variants.

It also makes it easier to review if screenshots of all changed glyphs are included in the PR ;-)

**Comment by metalvoidzz** [comment]
Thanks for the feedback :^)
I modified Katica Bold based on your PR:
katica_ligatures

**Review by bgianfo — CHANGES_REQUESTED** [review]
The linter noticed that you seem to have marked the font resources as executable.

```
[OK]: Meta/check-style.py
Running Meta/lint-executable-resources.sh... 
These files are marked as executable, but are in directories that do not commonly
contain executables. Please double-check the permissions of these files:
-rwxr-xr-x 1 runner docker 52592 Feb  6 23:47 Base/res/fonts/CsillaBold10.font
-rwxr-xr-x 1 runner docker 50288 Feb  6 23:47 Base/res/fonts/CsillaBold12.font
-rwxr-xr-x 1 runner docker 94576 Feb  6 23:47 Base/res/fonts/CsillaRegular10.font
-rwxr-xr-x 1 runner docker 62832 Feb  6 23:47 Base/res/fonts/CsillaRegular12.font
-rwxr-xr-x 1 runner docker 52592 Feb  6 23:47 Base/res/fonts/KaticaBold10.font
-rwxr-xr-x 1 runner docker 54384 Feb  6 23:47 Base/res/fonts/KaticaBold12.font
```

**Review by Xexxa — COMMENTED** [review]
Looks good!

**Comment by metalvoidzz** [comment]
@bgianfo I fixed the file permissions.

**Pull request merged**
