### PR TITLE
DesktopPicker: Add mouse wheel control

### PR DESCRIPTION
**Pull request by luk1337**
This lets us use scroll wheel up/down to move between columns and
shift + scroll wheel up/down to move between rows.

### CODE REVIEW

**Comment by alimpfard** [comment]
:thinking: what if we make this consistent with the existing scrolling behaviour? (scroll -> up/down, shift+scroll -> left/right)

**Comment by luk1337** [comment]
I personally think it's better the way it is now but if that'd be preferred instead I can amend the change.

**Comment by alimpfard** [comment]
I'm not sure, that's just an idea
I haven't tested either, not having to press shift does sound nice.

**Comment by alimpfard** [comment]
I think it's best if we make it behave the same as everywhere else, so it'd be nice if you could make it do that :)

**Comment by luk1337** [comment]
Done, also made the code a bit cleaner.

**Pull request merged**
