### PR TITLE
LibJS: Fix parser scoping

### LINKED ISSUE #8299: LibJS: Issue with Type enum in ScopePusher
Consider the `Type` enum definition in `ScopePusher` in the JS parser:
https://github.com/SerenityOS/serenity/blob/10728cd4213e4077f4b8352e912849dd725fe47d/Userland/Libraries/LibJS/Parser.cpp#L29-L46

Given how it's used below, I'd assume it was originally meant to be a bit field and that the value of `Function` should be `4`. As it is right now, `Function` is essentially defined as `Var | Let`, which semantically doesn't make much sense to me. If there is any actual design intent behind this, I'd love to know.

Unfortunately, simply changing the definition to `4` would cause quite some weirdness in the JS engine, which leads me to believe there are more issues deeper down in the parser and right now things are only working due to pure luck.

An example:
```javascript
function foo() {
    function inner() {};
    if (true) {
        if (true) {
            if (true) {
                console.log("hi");
            }
        }
    }
}
foo();
```
With `Function = 4`, the `inner` function is part of **all** block scopes following its declaration. This leads to a `ScriptFunction` being created and `set_variable()` being called on the VM for `inner` 5 times, which can't be right.

For reference, this extension to the scope pusher was initially introduced by PR #2497.

### PR DESCRIPTION
**Pull request by Hendi48**
This pull request improves function hoisting so that there's no more `skip` in the `function-hoisting` test.

As a side effect, it also does some general improvements w.r.t to scoping, especially when it comes to arrow functions. This caused scoping bugs in two other tests to show up, which have also been fixed.

~~The PR is currently in draft status because it breaks 67 annexB tests in test262.~~ Outside of annexB, it doesn't cause any regressions and even allows two more tests to pass successfully.

Closes #8299 .

### CODE REVIEW

**Comment by linusg** [comment]
> ~The PR is currently in draft status because it breaks 67 annexB tests in test262.~ Outside of annexB, it doesn't cause any regressions and even allows two more tests to pass successfully.

I'm confused, does it still cause regressions?

---

Please make the second commit message more specific, it suggests that function hoisting is currently completely broken, which it isn't.

**Comment by Hendi48** [comment]
Some annexB tests still break (mostly related to `eval` code), but fixing them all in this PR isn't feasible, especially because some of them only passed coincidentally in the first place.

Basically it breaks a lot of `eval` tests, but also fixes a whole bunch of other annexB behavior at the same time. The net pass count is -5 at the end due to that, but generally I think this is a good step towards more correctness in the parser.

> Please make the second commit message more specific, it suggests that function hoisting is currently completely broken, which it isn't.

Will do.

**Review by linusg — APPROVED** [review]
Great work!

**Comment by linusg** [comment]
this has a linting error, in case you didn't notice :)

**Pull request merged**
