### PR TITLE
Meta: Enable building with Xcode in a sane way

### PR DESCRIPTION
**Pull request by ADKaster**
First, we need to set the CMAKE_FOLDER property.

This property is useful in Xcode and Visual Studio, and that's about it.

It organizes targets into folders so that the IDE doesn't become a
cluttered mess. Other IDEs work based on the filesystem structure rather
than a target-based structure.

Ends up looking like this:

image

Without CMAKE_FOLDER, every target in the system ends up at the top level, which is a cluttered mess.

Next there are some changes to support multi-config generators, and some workarounds for the way Xcode creates temporary files for CMake targets on case-insensitive filesystems.

### CODE REVIEW

**Comment by nico** [comment]
Idea: Keep not supporting the Xcode generator, and never have to worry about this stuff.

**Comment by trflynn89** [comment]
Genuine question: it seems like a pretty large footprint / amount of complexity to support Xcode. What's the benefit and does that outweigh the cost here?

**Comment by ADKaster** [comment]
> What's the benefit and does that outweigh the cost here?

I the the benefit here is if there's things you want to do with Cocoa/SwiftUI/UiKit and Lagom libraries, it might be easier to mess around with the builtin GUI tools in Xcode than another IDE.

Whether that outweighs the ugly CMake variables and awkward workarounds, I don't know. For me, it kind of doesn't.

There are a few fixes here to support multi-config generators that I'd like to get in anyway.

The Folders thing is a horrible hack that feels annoying.

And the workarounds for Xcode target generation as created by CMake are super sad.

**Comment by filiphsps** [comment]
IMO this solves the biggest hurdle with Ladybird/Lagom macOS-specific development. To call it a pain right now would be a big understatement.
While you can get something ok setup with vscode (or similar) it's lackluster to say the least (but preferable over the xcode targets generated by cmake).

Of course, the big question is does it make sense to add all of this complexity for what is very much a non-primary platform and on top of that a non-primary IDE for most right now? Personally I'd love to get to properly take advantage of xcode's tools but I'm also not the one who would have to maintain it.

-my biased "it would be neat" 2cents.

**Comment by nico** [comment]
FWIW I do lots of macOS specific dev and it's fine right now IMHO. It's not like we're all in on .storyboard or .xib or whatever (rightfully so).

**Comment by trflynn89** [comment]
My workflow might've been anything but standard, but I found myself actively avoiding Xcode when building the AppKit chrome :man_shrugging: (except for view debugging, which is super useful, and easy to do without any build system support). I've tried using storyboard but found it worse than just writing code, even with poor documentation.

**Comment by ADKaster** [comment]
Dropping this PR since the Xcode workflow seems unnecesssary for the most active macOS contributors. If we can find a reason to use Xcode over CLion and VsCode, might revisit this.

I've pulled the multi-config commit into its own PR, #23590

**Pull request closed without merging**
