### PR TITLE
Ports+Kernel+LibC+AK+LibM: Add basic mesa port with OSMesa-based LibGL

### PR DESCRIPTION
**Pull request by speles**
Only software rendering is supported currently.

OpenGL: Softpipe (regular software rendering) and LLVMpipe (software rendering that's using LLVM for code generation and JIT compilation) are both working.
Tested this with 3DFileViewer and HL port.
Right now using LLVMpipe has 1.5x-3x better performance than LibSoftGPU, and on my PC brings HL to ~30 FPS which makes it actually playable :^)

Vulkan: Lavapipe (software rendering with LLVM) builds, but I have no idea how to test it.

The `libGL.so` library itself is not built by mesa, because we have no GLX or similar, and adding custom mesa frontend like, for example, Haiku does with its `hgl` is a bit over my head right now.
Instead, I opted for building `OSMesa.so` and tying it as a backend for Serenity's LibGL. The code is kind of ugly, but I have no idea how to make it much better, so any suggestions would be highly appreciated.

Also, having JIT requires us to make mmap/mprotect less secure, but I have no idea how to do it better than just having a pledge for it. If this can't be merged as is, please suggest a better way to approach this problem.

### CODE REVIEW

**Comment by nico** [comment]
Adding a mesa port is cool, for other ports to optionally build against it.

But actual serenity code doesn't want any dependencies on third-party code, so making LibGL depend on OSMesa seems wrong.

**Comment by speles** [comment]
> Adding a mesa port is cool, for other ports to optionally build against it.
> 
> But actual serenity code doesn't want any dependencies on third-party code, so making LibGL depend on OSMesa seems wrong.

Well, I understand your point, but also there are a few arguments I'd want to make:
- While this is really a dependency on OSMesa, it's not a hard dependency, just a run-time one.
So the worst-case scenario for the users that don't want to install the mesa port would be just not being able to use it.
For the LibGL contributors, it'll also (probably) be not a lot of hassle, since in most cases it'll boil down to adding a macro invocation after adding a new method to the GLContext interface unless GLContext will go through some major refactoring, or the philosophy of the methods prototypes (i.e. being really close to the most generic OGL version from the method group) changes.
- Limiting mesa port usage to other ports makes it almost useless even for them, because then each port has to decide whether it will support LibGL of OSMesa, due to the linking/include inconsistencies between them.
- The previous problem, and even allowing the users to use OSMesa backend in Serenity applications, can theoretically be circumvented by inventing some kind of adapter around the OSMesa that'll expose LibGL interface as a part of the port, but I believe it will be much more fragile and will require a bunch of work to actually allow users to choose between them to begin with.
- While using third-party dependencies is rare in Serenity, it's not unheard of. For example, HackStudio heavily relies on ports (git, make, gcc, etc.) for a lot of its functionality, and there are no "native" alternatives.

**Comment by Quaker762** [comment]
> Not liking this change - Mesa is basically an open source alternative to LibGL+LibSoftGPU, and core changes to Serenity to support this port are not Serenity-like. Mesa is cool to have though, so if you can manage to contain the required LibGL compat changes within the Mesa port directory that would be open for discussion!
> 
> Please join us in #opengl on Discord if you'd like, that might help with discussing a good way forward.

Agreed. Code in the mainline branch should _not_ have hacked in code to depend on a Port.

**Comment by speles** [comment]
OK, I've removed the LibGL changes and instead added LibGL-like interface to the mesa itself, so the user can substitute it via `LD_LIBRARY_PATH`.

Admittedly, that was way, way easier to do than I anticipated, and feels like a less hackish solution too.
The only thing that actually needs changes for compatibility is the last (3DFileViewer) commit, but the GL::present_context existed already, so I believe it's OK, and is more of a bugfix.

Please review the new changes

**Comment by speles** [comment]
Huh, the CI failed on DOMEventListener build error, not sure how I this is related to my changes or how I can fix that :/

**Comment by AtkinsSJ** [comment]
> Huh, the CI failed on DOMEventListener build error, not sure how I this is related to my changes or how I can fix that :/

It's not you, don't worry. And it's been fixed now. :^)

**Pull request closed without merging**
