### PR TITLE
HackStudio: Clear selection on file open

### PR DESCRIPTION
**Pull request by gootik**
Currently, if you open a file in HS editor and there is some selection it will stay and you will have selection in the new opened file. This PR fixes it.

### CODE REVIEW

**Comment by gootik** [comment]
@awesomekling I'm not sure if you prefer GTextEditor to clear the selection on set_document() or not

**Comment by awesomekling** [comment]
> @awesomekling I'm not sure if you prefer GTextEditor to clear the selection on set_document() or not

Yeah, we should definitely clear the selection on `set_document()` :)

**Comment by gootik** [comment]
Done!

**Comment by awesomekling** [comment]
Great!

**Pull request merged**
