### PR TITLE
Base: Add Lydian characters to font Katica Regular 10

### PR DESCRIPTION
**Pull request by Xexxa**
10920–1093F https://www.unicode.org/charts/PDF/U10920.pdf

https://serenityos.net/~xexxa/KaticaRegular10 (please tell me if I should change domain)

lydian

### CODE REVIEW

**Comment by Xexxa** [comment]
NKo
07C0–07FF https://www.unicode.org/charts/PDF/U07C0.pdf
nko

**Comment by bgianfo** [comment]
@Xexxa can you fix the merge conflict?

**Comment by Xexxa** [comment]
> @Xexxa can you fix the merge conflict?

The latest commit has the glyphs from #11083 included. Do I have to do anything more? (This is why I always look if there is an open PR before submitting a new PR :-p)

**Comment by IdanHo** [comment]
> The latest commit has the glyphs from #11083 included. Do I have to do anything more? (This is why I always look if there is an open PR before submitting a new PR :-p)

You still have to rebase onto the latest tree since you changed the file.

**Comment by Xexxa** [comment]
> > The latest commit has the glyphs from #11083 included. Do I have to do anything more? (This is why I always look if there is an open PR before submitting a new PR :-p)
> 
> You still have to rebase onto the latest tree since you changed the file.

That's above my paygrade mate! Last time I tried to rebase something I f---ed up more then once. I will just close this PR and make a new one. (Next time I meet a colleague IRL I will try to learn the finer points of GIT)

**Comment by Xexxa** [comment]
New PR:  #11087

**Pull request closed without merging**
