### PR TITLE
LibWeb+Ladybird/Qt: Improve timer precision

### PR DESCRIPTION
**Pull request by tcl3**
This PR includes changes that improve the accuracy and precision of timer events. See the individual commits for details.

I used the following test page to test timer precision and accuracy:

```html
<!DOCTYPE html>
<script>
    function sleepMilliseconds(delay) {
        return new Promise((resolve) => setTimeout(resolve, delay));
    }

    async function testTimerPrecision() {
        let previousTime = performance.now();
        const outputElement = document.getElementById("output");
        for (let i = 0; i < 10; ++i) {
            await sleepMilliseconds(100);
            const currentTime = performance.now();
            outputElement.appendChild(document.createTextNode(`Time elapsed: ${currentTime - previousTime} milliseconds\n`));
            previousTime = currentTime;
        }
    }
</script>
<body onload="testTimerPrecision()">
<pre id="output"></pre>
</body>
```

The results in QT Ladybird are as follows:

Before:
```
Time elapsed: 94 milliseconds
Time elapsed: 97 milliseconds
Time elapsed: 93 milliseconds
Time elapsed: 97 milliseconds
Time elapsed: 93 milliseconds
Time elapsed: 97 milliseconds
Time elapsed: 100 milliseconds
Time elapsed: 100 milliseconds
Time elapsed: 100 milliseconds
Time elapsed: 100 milliseconds
```

After:
```
Time elapsed: 101.21944400000001 milliseconds
Time elapsed: 100.653346 milliseconds
Time elapsed: 100.524011 milliseconds
Time elapsed: 100.56357700000001 milliseconds
Time elapsed: 100.51349099999999 milliseconds
Time elapsed: 100.38906799999995 milliseconds
Time elapsed: 100.70682600000009 milliseconds
Time elapsed: 100.85266200000001 milliseconds
Time elapsed: 100.93509699999993 milliseconds
Time elapsed: 100.71393 milliseconds
```

---

Results for Chrome and Firefox:

Chrome:
```
Time elapsed: 100.39999999850988 milliseconds
Time elapsed: 100.29999999701977 milliseconds
Time elapsed: 100.30000000447035 milliseconds
Time elapsed: 100.10000000149012 milliseconds
Time elapsed: 100.19999999552965 milliseconds
Time elapsed: 100.30000000447035 milliseconds
Time elapsed: 100.19999999552965 milliseconds
Time elapsed: 100.20000000298023 milliseconds
Time elapsed: 100.10000000149012 milliseconds
Time elapsed: 100.19999999552965 milliseconds
```

Firefox:
```
Time elapsed: 100 milliseconds
Time elapsed: 100 milliseconds
Time elapsed: 101 milliseconds
Time elapsed: 99 milliseconds
Time elapsed: 101 milliseconds
Time elapsed: 100 milliseconds
Time elapsed: 100 milliseconds
Time elapsed: 101 milliseconds
Time elapsed: 100 milliseconds
Time elapsed: 100 milliseconds
```

---

Note: I have tested QT Ladybird, the Serenity Browser and headless-browser and all produce similar results. I haven't tested the Cocoa chrome, as I don't have access to a Mac.

### CODE REVIEW

**Review by trflynn89 — APPROVED** [review]
In the AppKit chrome, I get:
```
Time elapsed: 101.973 milliseconds
Time elapsed: 101.54899999999999 milliseconds
Time elapsed: 101.81600000000003 milliseconds
Time elapsed: 102.154 milliseconds
Time elapsed: 102.029 milliseconds
Time elapsed: 102.15899999999993 milliseconds
Time elapsed: 102.47300000000007 milliseconds
Time elapsed: 102.38400000000001 milliseconds
Time elapsed: 102.00799999999992 milliseconds
Time elapsed: 102.29200000000003 milliseconds
```

so...not very good 😆 

Looking at the docs for [CFRunLoopTimer](https://developer.apple.com/documentation/corefoundation/cfrunlooptimer?language=objc):
> A timer is not a real-time mechanism; it fires only when one of the run loop modes to which the timer has been added is running and able to check if the timer’s firing time has passed. If a timer’s firing time occurs while the run loop is in a mode that is not monitoring the timer or during a long callout, the timer does not fire until the next time the run loop checks the timer. Therefore, the actual time at which the timer fires potentially can be a significant period of time after the scheduled firing time.

Something to look into.

**Comment by trflynn89** [comment]
huh, that said I get similar results with the Qt chrome on my mac:
```
Time elapsed: 101.622 milliseconds
Time elapsed: 101.551 milliseconds
Time elapsed: 101.79599999999996 milliseconds
Time elapsed: 102.37 milliseconds
Time elapsed: 101.71900000000005 milliseconds
Time elapsed: 102.33999999999992 milliseconds
Time elapsed: 102.15500000000009 milliseconds
Time elapsed: 102.09399999999994 milliseconds
Time elapsed: 101.98700000000008 milliseconds
Time elapsed: 101.61899999999991 milliseconds
```

**Comment by tcl3** [comment]
> huh, that said I get similar results with the Qt chrome on my mac:
> And Firefox is even worse

Hmm, looking at the [High Resolution Time](https://w3c.github.io/hr-time/#dfn-relative-high-resolution-time) specification, the time resolution can be an arbitrarily high implementation-defined value. That might account for the difference, or it could be the underlying OS (HPET on vs off, power profile, etc.). I can't be sure. 

Either way, I think it's still an improvement on what I was seeing prior to this change. I've run the test multiple times and I've seen a swing of up to 10ms either way (on Qt ladybird on Linux).

**Comment by DanShaders** [comment]
Shouldn't we limit `performance.now` precision to 100us as per https://w3c.github.io/hr-time/#clock-resolution reference to coarsen time?

Also, I think these timers are handled by generic EventLoopImplementationUnix, not a chrome-specific loop impl (I'm not very familiar with LibWeb/chromes/event loops interop though). If this is in fact true, we will compare these "precise" timestamps with coarse time [here](https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp#L333) and I would very much prefer to leave coarse time there.

**Comment by tcl3** [comment]
> Shouldn't we limit `performance.now` precision to 100us as per https://w3c.github.io/hr-time/#clock-resolution reference to coarsen time?

Yes, we should do this. Our `coarsen_time()` is currently a no-op:

https://github.com/SerenityOS/serenity/blob/c41b359ca5e720edbd4f14051e6421522a9df316/Userland/Libraries/LibWeb/HighResolutionTime/TimeOrigin.cpp#L22-L28

I'm not sure of the best way to implement this though, the specification says it can be implemented in an implementation-defined way.

> Also, I think these timers are handled by generic EventLoopImplementationUnix, not a chrome-specific loop impl (I'm not very familiar with LibWeb/chromes/event loops interop though). If this is in fact true, we will compare these "precise" timestamps with coarse time [here](https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp#L333) and I would very much prefer to leave coarse time there.

The `performance.now()` timer doesn't use any event loop implementation. The performance interface uses an internal `Core::ElapsedTimer`. The `ElapsedTimer` gets it's elapsed time by making a cal to `clock_gettime` with the appropriate `clock_id`, depending on whether a precise or coarse timer was requested.

The event loop change I made affects `setTimeout()` calls. These use `Web::HTML::Timer` objects, which in turn use `Core::Timer` internally. These then interact with the current `EventLoopImplementation`.

I've updated the commit message for Ladybird/Qt commit to make it clear that it affects `setTimeout()`.

**Comment by DanShaders** [comment]
I think we use ELIQt with Qt Chrome and ELIUnix on MacOS and Serenity judging by

https://github.com/SerenityOS/serenity/blob/a8a1d8746e28e743a7d86e6e660140fc28949e4f/Ladybird/WebContent/main.cpp#L57-L62

With that, changes LGTM.

**Review by ADKaster — APPROVED** [review]

**Pull request merged**
