### PR TITLE
Base: Add five new emojis

### PR DESCRIPTION
**Pull request by djwisdom**
⚡ - U+26A1 HIGH VOLTAGE
⚪ - U+26AA WHITE CIRCLE
⚫ - U+26AB BLACK CIRCLE
⚾ - U+26BE BASEBALL
✉ - U+2709 ENVELOPE

Coverage: https://emoji.serenityos.net

### CODE REVIEW

**Review by Xexxa — CHANGES_REQUESTED** [review]
Most implementations of 26BE seems to be... white. Any specific reason you made the baseball black?

**Comment by djwisdom** [comment]
Inspired by Docomo / KDDI version

**Comment by djwisdom** [comment]
Apologies, just woke up and inadvertently clicked the wrong button.

**Comment by squeek502** [comment]
Docomo / KDDI versions have transparent 'fill', not black. I'd suggest a white ball with red stitches for it to be recognizable as a baseball.

**Comment by djwisdom** [comment]
Updating emoji as per recommendation, 'after' I submit a kernel panic issue. I'll be back.

**Comment by djwisdom** [comment]
Today is not my day, I keep having kernel panics but hey, that's also a part of improvement. Successfully pushed the proper baseball emoji.

**Review by Xexxa — APPROVED** [review]
LGTM!

**Comment by squeek502** [comment]
This'll need to be rebased to remove the `emoji.txt` changes since https://github.com/SerenityOS/serenity/pull/14934 has been merged.

**Pull request merged**
