### PR TITLE
Base: Add various misc. emojis

### PR DESCRIPTION
**Pull request by tarob0ba**
This commit adds various color emojis to the system.

🎨 - U+1F3A8 ARTIST PALETTE
💡 - U+1F4A1 ELECTRIC LIGHT BULB
🤍 - U+1F90D WHITE HEART
🤎 - U+1F90E BROWN HEART
🥝 - U+1F95D KIWIFRUIT
🍩 - U+1F369 DOUGHNUT
🎄 - U+1F384 CHRISTMAS TREE
🤤 - U+1F924 DROOLING FACE
🥓 - U+1F953 BACON

I'm happy that we're improving our support for color emoji. :^)

### CODE REVIEW

**Comment by filiphsps** [comment]
Looks like your commit author info got messed up

**Comment by tarob0ba** [comment]
Ack... I swear I had updated my author info.

**Comment by tarob0ba** [comment]
I forgot I updated my email and never updated my git config.

**Comment by linusg** [comment]
Thanks, very cute :)

**Pull request merged**
