### PR TITLE
Ports: Update Composer to 2.3.4

### PR DESCRIPTION
**Pull request by GMTA**
This fixes some warnings when running with PHP 8.1.

### CODE REVIEW

**Comment by EWouters** [comment]
This conflicts with https://github.com/SerenityOS/serenity/pull/13395. Why is that not merged?

**Comment by GMTA** [comment]
> This conflicts with #13395. Why is that not merged?

What exactly is the conflict? I don't see it?

**Comment by EWouters** [comment]
Actually, you updated to an even newer version.

**Comment by GMTA** [comment]
> Actually, you updated to an even newer version.

Ah, by the time I looked you already rebased/resolved that conflict I guess :-) make sure to advertise in #code-review so your PR gets merged!

**Pull request merged**
