### PR TITLE
Lagom: Port LibGUI to lagom

### PR DESCRIPTION
**Pull request by filiphsandstrom**
Very much TODO.
Making this super early non-compiling work public in a big-brain-moment to force myself to complete it.

### CODE REVIEW

**Comment by drunderscore** [comment]
Not sure all the `#ifdef __serenity__` are really great... super intrusive to the current and future code I'm feeling ..

**Comment by filiphsandstrom** [comment]
> Not sure all the `#ifdef __serenity__` are really great... super intrusive to the current and future code I'm feeling ..

Not gonna be there in the future, just temporary while getting it to compile. I’ll instead be resorting to implementing a fake “WindowServer Connection” :)

**Comment by trflynn89** [comment]
I don't think this should be an open PR if it's so actively in development. Every time you push, it'll trigger and hog CI resources from other PRs. You can make it a PR on your own fork if you want a handy link to use for discussion.

**Comment by filiphsandstrom** [comment]
> I don't think this should be an open PR if it's so actively in development. Every time you push, it'll trigger and hog CI resources from other PRs. You can make it a PR on your own fork if you want a handy link to use for discussion.

You're completely right.

**Pull request closed without merging**
