### PR TITLE
LibRegex: Make Fork{Jump,Stay} non-recursive

### PR DESCRIPTION
**Pull request by alimpfard**
cc @trflynn89 - you reported this.
This _shouldn't_ have any obvious issues ~~(except leaking some strings - I'll be figuring that out next, and if that fails...well, we can still have it, just more slow)~~ - String leakage fixed :^)

- **AK: Correct Tuple's constructor signatures**
    Random drive-by fix, not related to this specific PR
- **LibRegex: Make Fork{Jump,Stay} non-recursive**
- **LibRegex: Add some tests for Fork{Stay,Jump} performance**
    Recursive -> non-recursive impl
- **AK: Add a simple bump allocator**
- **LibRegex: Use a bump-allocated linked list for fork save states**
    `UniformBumpAllocator<T>` allows allocating only values of type `T`, and gives you the nice ability to actually call their dtors when they're deallocated :P
- **LibRegex: Make Matcher<>::match(Vector<>) take a reference to the vector**
    Another drive-by fix, but this time it's actually related to performance :P

### CODE REVIEW

**Comment by trflynn89** [comment]
Nice!

**Comment by alimpfard** [comment]
Ooooh, looks like this has borked some js regexp tests, moving back to draft for now.

**Comment by alimpfard** [comment]
Changelog:
- All boogs fixed, thar be no moar boogs

**Comment by alimpfard** [comment]
YOLO, looks like this is doing just fine, we can fix any future issues...in the future.

**Pull request merged**
