### PR TITLE
Base: Improve 2048 Icons and manpage

### PR DESCRIPTION
**Pull request by cubiclove**
* Give the icon the same colors as the original game's icon. Give the tile slightly rounded corners and subtle shading.
* Give the game a decent manpage explaining the rules and the settings.

**New vs Old Icons:**
New vs Old

Contributes towards #21091

### CODE REVIEW

**Comment by LucasChollet** [comment]
Nice! :rocket:

Looks good from my nonqualified eyes!

**Comment by AtkinsSJ** [comment]
Manpage change looks good. :+1:

The icon is nicer looking. Though, it doesn't have a lot of contrast, especially the 16x16 size. Whether that's actually a problem is debatable though.

**Comment by cubiclove** [comment]
The icon is the same colour as the [official 2048 app icon](https://en.wikipedia.org/wiki/2048_(video_game)#/media/File:2048_logo.svg), though the website favicon is slightly darker. I tested variations out and I think it look fine in-situ, or at least on par with the existing icon. The subtle shading helps it stand out a little.

Should I change it?

**Comment by LucasChollet** [comment]
I would say it's fine as is, but it's only my humble opinion.

**Comment by AtkinsSJ** [comment]
Fine by me! Let's get this merged. :^)

**Comment by cubiclove** [comment]
I'm afraid there's more manpages to come Sam, I'm on a roll

**Comment by AtkinsSJ** [comment]
> I'm afraid there's more manpages to come Sam, I'm on a roll

image

**Pull request merged**
