### PR TITLE
Ports: Add support for zip files and ensure configure is executable

### PR DESCRIPTION
**Pull request by danboid**
Add support for zip files and ensure configure is executable

### CODE REVIEW

**Comment by danboid** [comment]
Configure is usually executable but not always so it it doesn't hurt to make sure building doesn't fail just because of that. I've had a few apps where it wasn't.

**Comment by danboid** [comment]
bsdtar could be used to uncompress the tarballs to but most Linux users only have GNU tar installed. I chose bsdtar for uncompressing zips because it has a Serenity port already plus infozip unzip is dead and 7za requires pthreads to run.

**Comment by danboid** [comment]
Whitespace fixed, sorry about the mess!

The chmod configure is mainly for dealing with .zip archives, but it can happen with tarballs too.

**Comment by awesomekling** [comment]
Ah, right :)

**Pull request merged**
