### PR TITLE
Applets/Audio: Remove unveiling /tmp/portal/config

### PR DESCRIPTION
**Pull request by doctor-rd**

### CODE REVIEW

**Comment by kleinesfilmroellchen** [comment]
The `AudioApplet` class connects to the ConfigServer, see line 28. Therefore, this will not work.

**Comment by doctor-rd** [comment]
The connection to ```ConfigServer```is established with ```Config::pledge_domains("AudioApplet")```.

**Comment by kleinesfilmroellchen** [comment]
Yes, but we still need to pledge the portal or else either the IPC connection establishment fails or the `unveil(nullptr, nullptr)` fails.

**Comment by doctor-rd** [comment]
```TextEditor``` is a great example for the usage of the ```ConfigServer```.

**Comment by trflynn89** [comment]
> Yes, but we still need to pledge the portal or else either the IPC connection establishment fails or the `unveil(nullptr, nullptr)` fails.

That connection is established by the call to `pledge_domains`, which occurs before `unveil` is ever called, so it establishes  just fine. See #9617.

**Review by kleinesfilmroellchen — APPROVED** [review]

**Pull request merged**
