### PR TITLE
Themes: Add Sunshine theme 16x16 window icons

### PR DESCRIPTION
**Pull request by bcoles**
Sunshine

### CODE REVIEW

**Comment by awesomekling** [comment]
The close (X) button looks a little off, no?

**Comment by bcoles** [comment]
> 
> 
> The close (X) button looks a little off, no?

It does. The original Sunshine did not have a close button. I tried to fix it with highlighting but it looks goofy. Then again, the original design is pretty goofy too.

image

**Comment by awesomekling** [comment]
Ok that looks nice enough!

**Comment by bcoles** [comment]
Oh.. you merged before I could force push the new icon lol

**Comment by awesomekling** [comment]
oh whoops 🤦🏻

**Pull request merged**
