### PR TITLE
PixelPaint: Use a bucket cursor for the bucket tool

### PR DESCRIPTION
**Pull request by mrkct**
Previously when selecting the Bucket tool we kept the default arrow cursor.  

These 2 commits add a new 'Bucket' cursor type and use it for PixelPaint.

The cursor icon is the same as the icon for the bucket tool in PixelPaint. The dark mode one has the black border recolored to white.

Nitpick: is the type 'LibGfx' correct for the first commit? It also touches WindowManager and adds the 2 icons

### CODE REVIEW

**Review by kleinesfilmroellchen — CHANGES_REQUESTED** [review]
I think a better color for the bucket paint would be one of the standard theme colors, e.g. the dark brown. Other than that, looks good!

**Comment by Granddave** [comment]
@mrkct @kleinesfilmroellchen
> I think a better color for the bucket paint would be one of the standard theme colors, e.g. the dark brown.

Did you copy the icon directly from the toolbar? In that case I think we either should redo all of them or leave the cursor as is since they all share the same kind of gray.

image
image

**Comment by kleinesfilmroellchen** [comment]
> @mrkct @kleinesfilmroellchen
> 
> > I think a better color for the bucket paint would be one of the standard theme colors, e.g. the dark brown.
> 
> Did you copy the icon directly from the toolbar? In that case I think we either should redo all of them or leave the cursor as is since they all share the same kind of gray.
> 
> image image

Oh, I didn't realize they were already in PixelPaint. In that case, you can leave them.

**Comment by awesomekling** [comment]
Please configure your editor to put a newline at the end of files.

Also, "bucket" doesn't really feel like a "standard cursor" IMO, is it really generally useful outside of PixelPaint? This seems more like an app-specific "custom cursor"

**Pull request merged**
