### PR TITLE
LibWeb: Use relative units for gradients until painting

### PR DESCRIPTION
**Pull request by MacDue**
This commit tweaks gradients so resolve_color_stop_positions() no longer cares about the actual length of the gradient. All stops are resolved to relative positions along the gradient line (between 0 and 1), and are only scaled back to pixels (if required) during the actual painting.

This has no immediate benefit right now, but it might make using CSS pixels for gradients easier :^)

cc @AtkinsSJ

### CODE REVIEW

**Comment by MacDue** [comment]
Converting this to draft for now as there's some subtle off-by-one rendering bugs on `repeating-linear-gradient()`s that I can't debug now :zzz:

**Comment by MacDue** [comment]
@AtkinsSJ, I've fixed this painting issues now, though I'm not _super_ happy with change, so I'll leave it up to you if it's worth merging. 

There's no pixels in the resolving code now, but the `GradientLine` class that's used for painting both conic/linear gradients still  needs to accept both angles and pixels. The gradient line is some about of pixels in length for a linear gradients, but it's just 360 degrees for conic gradients.

**Comment by AtkinsSJ** [comment]
Thanks! Looks good to me.

**Comment by MacDue** [comment]
beware more gradients are coming :^)

**Pull request merged**
