### PR TITLE
GAction: Added common actions

### PR DESCRIPTION
**Pull request by rhin123**
I'd like your opinion on how I'm handling custom actions, and also what I'm doing wrong. Also...

Why is m_document_dirty always true in the QuitAction?
How would i properly reference window() in the QuitAction?

I also have a feeling that we should move these custom actions into a new parent class of common actions.

### CODE REVIEW

**Comment by awesomekling** [comment]
I think we should think bigger. Let's build an API for generating common actions.
Perhaps something like this, that would construct a new GAction and return it to us:

```cpp
namespace GCommonActions {
    static NonnullRefPtr<GAction> make_cut_action(Function<void()>);
    static NonnullRefPtr<GAction> make_copy_action(Function<void()>);
    static NonnullRefPtr<GAction> make_paste_action(Function<void()>);
    static NonnullRefPtr<GAction> make_quit_action(Function<void()>);
    ...
};
```

Then we could use it like this:
```cpp
auto quit_action = GCommonActions::make_quit_action([&] {
    // whatever we do in response to the quit action
});
```

Basically, the idea is that these functions construct new GAction objects with the right name, keyboard shortcut and icon.

Also, let's make every app decide for itself what to do when we activate the quit action. The logic for deciding whether it's fine to quit is going to be different in many programs, so we don't have to think of a one-size-fits-all solution.

What do you think?

**Comment by rhin123** [comment]
Yeah I think this approach is better. I'll try to knock it out

**Comment by rhin123** [comment]
@awesomekling what'd you think. Wasn't sure how to cancel the event inside the callback method so I just return a boolean.

**Comment by awesomekling** [comment]
Hmm. I think we should just invoke the callback and not call `GApplication::quit()` inside the default quit action. Let the callback do that instead, if it wants. That makes things a lot simpler.
The common actions should just be a handy way to create common actions with the right name, icon and shortcut. What they do is up to the client who uses them.

**Comment by rhin123** [comment]
@awesomekling I think were good to go. I just want your word before I start implementing this everywhere else.

**Comment by awesomekling** [comment]
Ok let's merge it :)

**Pull request merged**
