### PR TITLE
Issue#17129: Remove Core::IODevice and replace all uses of it with AK…

### PR DESCRIPTION
**Pull request by adityasingh22**
…::Stream

### CODE REVIEW

**Comment by circl-lastname** [comment]
Hello, unfortunately there's plenty of linter errors you can see in the CI log, and the commit message should also be limited to 72 characters and start with `Everywhere:` instead of the issue number. If you do not know how to fix this please say.

**Comment by Hendiadyoin1** [comment]
Or as it is only affecting LibChess,
```
LibChess: Migrate to AK::Stream
```
Also you say you remove Core:IODevice, which is not quite the case, if LibChess was the last user, you can add a second commit removing the file eg:
```
LibCore: Remove IODevice

This was deprecated by AK::Stream and all its former users
were migrated.
```

Also, you can remove the `AK` prefixes from all usages of `AK::Stream` it is exported to the global namespace by `AK/Forward.h`

**Comment by adityasingh22** [comment]
Hi @circl-lastname, I am not aware of how to solve the linting error. If some documentation or help can be provided that'd be great.
Hi @Hendiadyoin1, I didn't get your point "_Also you say you remove Core:IODevice, which is not quite the case, if LibChess was the last user, you can add a second commit removing the file eg:_". Could you please explain a bit more?

**Comment by circl-lastname** [comment]
You can solve the linting issue by going to the CI log, I've linked it [here](https://github.com/SerenityOS/serenity/actions/runs/4517564277/jobs/7956856468?pr=18034#step:9:107). Simply make the suggested changed and then you can squash the changes into your first commit. The commit message can be easily fixed along the way as by squashing you'll be prompted to do so.

**Comment by Hendiadyoin1** [comment]
> Hi @Hendiadyoin1, I didn't get your point

So your current commit title says `Remove Core::IODevice`, which is not 100% true, because after your commit Core::IODevice still exists in tree,
If LibChess was the last user of it, you can add a second commit removing it entirely

**Comment by AtkinsSJ** [comment]
Commit message issues aside, this doesn't even build. The only CI runs that succeed are Lagom because Lagom doesn't build LibChess.

Please don't submit PRs without building and running your changes.

**Pull request closed without merging**
