### PR TITLE
Calculator: accept more keyboard input

### PR DESCRIPTION
**Pull request by ignas-sa**
Allow user to clear/remove last numeral from input (Esc/Backspace
respectively) and type the decimal point.

### CODE REVIEW

**Comment by bugaevc** [comment]
Tip: when you make a PR, please look who wrote the code you're changing, and cc them (if it wasn't @awesomekling)

The patch looks good to me, but please change the commit message to match other commit messages in the project. For example, it could be "Calculator: Accept more keyboard input"

**Comment by ignas-sa** [comment]
Fixed that tab.

**Comment by awesomekling** [comment]
There are still multiple formatting issues. Please just use `clang-format` :)

**Comment by awesomekling** [comment]
:+1:

**Pull request merged**
