### PR TITLE
Base: Add Temple OS themes

### PR DESCRIPTION
**Pull request by electrikmilk**
Add Temple OS themes for the system and terminal

Screen Shot 2022-01-27 at 22 20 58
Screen Shot 2022-01-27 at 21 56 46

### CODE REVIEW

**Comment by trflynn89** [comment]
TBH I'm a bit torn between paying tribute to Terry and recognizing that this might just not be a good fit for Serenity. It clashes pretty hard with all other Serenity themes - I think when adding a new theme, we should ask if it's one that Serenity developers would actually use, and I find it hard to imagine a TempleOS theme would see much usage?

**Comment by bgianfo** [comment]
I agree with @trflynn89, this is reminiscent of the old "hot dog stand" theme (#916). :smile: Fun for a bit, but just something that sits around untouched without much utility.

Also please look at the theme file, it's full of git stash markers, and will likely fail to parse.

**Comment by awesomekling** [comment]
Agreed with @trflynn89 and @bgianfo. It's cute, but let's not do user-facing memes in the system :)

**Comment by tomuta** [comment]
I agree. But something I would love to see is a Win 3.1 theme. Which probably wouldn't be that far off ;-)

**Comment by electrikmilk** [comment]
@tomuta I also saw similarities to Windows 3.1 when creating this theme, perhaps instead a Redmond 3.1 theme, with this theme as a base, would make more sense for Serenity.

**Comment by electrikmilk** [comment]
> I agree with @trflynn89, this is reminiscent of the old "hot dog stand" theme (#916). 😄 Fun for a bit, but just something that sits around untouched without much utility.
> 
> Also please look at the theme file, it's full of git stash markers, and will likely fail to parse.

That theme is a nightmare 😂

I understand what you mean, not very pleasant for practical use.

**Pull request closed without merging**
