### PR TITLE
Kernel/HID: Fix PS2 keyboard scan code tables

### LINKED ISSUE #22599: Kernel: Some keys are not working
I believe #22499 caused some keys to no longer work correctly.

I have only tested a few keys on fi, en-us and en-gb.  My physical keyboard is scandinavian.

On all layouts the key between left shift and Z opens About Terminal in the terminal
and in TextEdit it enables Markdown preview.

The plus key on the numpad isn't working in any layout, nothing happens when it's pressed.

Shift + Q becomes '?' on the us layout, and shift + '=' does nothing.

On only the fi layout, numpad slash becomes minus and numpad minus becomes plus.

Shift + 8 (not numpad) becomes '*' instead of '(' on the fi layout.

### PR DESCRIPTION
**Pull request by supercomputer7**
We do this by implementing the following fixes:
- The Key_Plus is assigned to a proper map entry index now which is 0x4e both on the keypad and non-keypad keys.
- Shift+Q now prints out "Q" properly on scan code set 2.
- Key BackSlash (or Pipe on shift key being pressed down) is now working properly as well.

Partially fixes #22599. I still don't know how to properly check the fi layout (do I need a keyboard with this layout?).

### CODE REVIEW

**Comment by oskar-skog** [comment]
I've just started testing it.  Still broken, just differently.   I'm going to draw some pictures to show all the boogs.

If you're running in QEMU, I'd suggest using a virtual keyboard with a non-US layout to test that things are working correctly.

**Comment by oskar-skog** [comment]
Without any boot arguments:
default

**Comment by supercomputer7** [comment]
@oskar-skog 
I sent another revision - let's focus on getting the scan code set 1 to work properly (or at least to a very good state).

**Comment by oskar-skog** [comment]
Numpad numbers and decimal separator are working now and I didn't notice any regressions.

I think it's just:
- Numpad division still appears to be mapped to the key to the left of right shift.
- The key to the left of backspace not working correctly with shift (on non-US layout)
- Print Screen does something weird, but who cares.

**Comment by supercomputer7** [comment]
> Numpad numbers and decimal separator are working now and I didn't notice any regressions.
> 
> I think it's just:
> 
>     * Numpad division still appears to be mapped to the key to the left of right shift.
> 
>     * The key to the left of backspace not working correctly with shift (on non-US layout)
> 
>     * Print Screen does something weird, but who cares.

OK, thank you for helping with testing!
I will get to this probably this weekend :)

**Comment by supercomputer7** [comment]
> Numpad numbers and decimal separator are working now and I didn't notice any regressions.
> 
> I think it's just:
> 
>     * Numpad division still appears to be mapped to the key to the left of right shift.
> 
>     * The key to the left of backspace not working correctly with shift (on non-US layout)
> 
>     * Print Screen does something weird, but who cares.

I start to believe that Numpad division key needs its own entry in keymap JSON files... so maybe we should wait with this, I have a FIXME for this (so we can fix this).
As for non-US layouts, did this ever work in the first place?

Besides these 2 points, we can get this merged soon.

**Comment by oskar-skog** [comment]
> I start to believe that Numpad division key needs its own entry in keymap JSON files

I'm pretty sure it already has that, otherwise it would never have worked for me previously.
But maybe it's not used in all keymaps?

**Comment by supercomputer7** [comment]
> > I start to believe that Numpad division key needs its own entry in keymap JSON files
> 
> I'm pretty sure it already has that, otherwise it would never have worked for me previously. But maybe it's not used in all keymaps?
> 
> Edit: Uh, what? I can't find it? Do I misremember division key ever working?

No, it's not working because we changed how the kernel sends the scancode keys to userspace, so we did miss this entry.
Basically codepoints (which is still propagated to userspace IIRC) are used in the VT console so we can have a virtual console even if userspace didn't load any keymap.
In the past we gave the codepoint to the userspace program (which did use this directly) but this is not relevant anymore, as we give it a number (iirc) that it looks into the current keymap for translation.

**Pull request merged**
