### PR TITLE
Everywhere: Merge LibDl into LibC

### PR DESCRIPTION
**Pull request by timschumi**
Same as with LibPthread earlier, this moves the actual `dlfcn` implementation into LibC, and adds a bit of compatibility code to redirect everything that will still try to access `libdl.so` to `libc.so` instead.

This skips the dance of having to link against `LibC` just to get access to some symbols that are filled in by the dynamic loader anyways, while having the POSIX-to-Serenity layer in a seperate library entirely. I'm also hoping to eliminate a bunch of custom LDFLAGS patches from ports once we are done with this and LibM.

This technically breaks existing Clang builds again (since `libunwind.so` linked against libpthread _and_ libdl), but at least that can be worked around for now by installing `patchelf` and running `patchelf --remove-needed libdl.so Toolchain/Local/clang/lib/i686-pc-serenity/libunwind.so.1.0` (`x86_64-pc-serenity` for x86_64 respectively).

### CODE REVIEW

**Comment by timschumi** [comment]
Need to fix some LibELF bugs first.

**Comment by timschumi** [comment]
Nevermind, we just can't handle ELF files where dependencies have been _added_ using `patchelf`.

**Comment by ADKaster** [comment]
We'll want to change the CMake platform files too

**Comment by timschumi** [comment]
Is there anything else to update apart from `Toolchain/CMake/Platform/SerenityOS.cmake`?

**Comment by ADKaster** [comment]
I'm blind, that's the only file. We'll want to upstream that before 3.25 so we can execute the plan :tm: in my PR

**Pull request merged**
