### PR TITLE
WebContent+WebDriver: Implement `POST /session/{session_id}/window/new`

### PR DESCRIPTION
**Pull request by ebanner**
continuing work from #16272

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Please add

```
Co-authored-by: your name <your@email>
```

At the bottom of the commit message (after a blank line), so that you get credit for your work. :^)

**Comment by linusg** [comment]
Also has conflicts.

**Comment by trflynn89** [comment]
Note this doesn't resolve any of the comments made on the original PR

**Comment by ebanner** [comment]
@trflynn89 Ah yes, this PR was just a symbolic act on my part to signal that I'm working on it. I've made zero changes so far

I don't know why GitHub doesn't default the PR to a draft. My bad!

**Comment by trflynn89** [comment]
Sorry, this ended up being implemented in PRs #17733 and #17855

**Pull request closed without merging**
