### PR TITLE
Applications: FontEditor, relocate form items by fons size

### PR DESCRIPTION
**Pull request by asliturk**
FontEditor

### CODE REVIEW

**Comment by awesomekling** [comment]
Oh that's really cool! But we need to fix it so we can see the whole "demo string"
In the screenshot, the large demo text should end in "WIZARD!", not "W..." :)

**Comment by asliturk** [comment]
> Oh that's really cool! But we need to fix it so we can see the whole "demo string"
> In the screenshot, the large demo text should end in "WIZARD!", not "W..." :)

Fixed.

**Comment by linusg** [comment]
`s/fons size/font size` in the last commit's message

**Comment by awesomekling** [comment]
:+1:

**Comment by bugaevc** [comment]
But... why rewrite the UI back in C++?

**Pull request merged**
