### PR TITLE
Ports: Update libarchive to v3.5.2

### PR DESCRIPTION
**Pull request by kenXengineering**
Updated GPG fingerprint to Martin Matuska's latest public key

### CODE REVIEW

**Comment by kenXengineering** [comment]
This fixes #9921

**Review by linusg — CHANGES_REQUESTED** [review]
Welcome! :^)
Please split this into two separate commits, one for the GPG fingerprint fix, and one for the version bump. You should also put the `Fixes #9921` in the first commit message to automatically link and close is once merged.

**Comment by linusg** [comment]
oh, based on the description in the issue it makes more sense to have them in one commit. alright then :)

**Review by linusg — APPROVED** [review]

**Comment by linusg** [comment]
You will however need to update https://github.com/SerenityOS/serenity/blob/master/Ports/AvailablePorts.md.

**Comment by kenXengineering** [comment]
Thanks for the welcome!  I added the updated AvailablePorts.md changes and squashed it into one commit.

**Pull request merged**
