### PR TITLE
 Maps: Add Maps Settings with multiple tile providers options

### PR DESCRIPTION
**Pull request by bplaat**
I have added a basic Maps Settings application where I can choose a tiles provider for the `MapWidget`. The current options where all the free tile providers in https://wiki.openstreetmap.org/wiki/Raster_tile_providers. You can easily add more in the `MapsTileProviders.json`.

## Demo video
https://github.com/SerenityOS/serenity/assets/19894029/3a14759f-a177-4afe-b51a-1e969982f372

*This is SerenityOS x86_64 running on a ARM64 platform so the performance looks worse then it is*

Looking forward to feedback :)

### CODE REVIEW

**Comment by EWouters** [comment]
Looks very nice! In order to meet the [attribution criteria](https://wiki.osmfoundation.org/wiki/Licence/Attribution_Guidelines#Attribution_text) for OpenStreetMap, we must also inform that the map data is available under the Open Database License. Custom tile providers may also have other attribution criteria, so perhaps an option for that would be appropriate.

**Comment by bplaat** [comment]
Good point, I will add the copyright attributions and links to the json file and use them in the MapWidget.

**Comment by bplaat** [comment]
The map tile providers can now also set the attribution text and url 🎉, I also have updated the GML code to the new GML compiler, it works quite nice.

**Review by ADKaster — COMMENTED** [review]
This looks good, one question though: Does this settings menu show up in the `Settings` app automagically? Or is there addtional stuff that the other settings (e.g. DisplaySettings) do to show up in there?

**Comment by bplaat** [comment]
Yes it is automatically put in the Settings app. The Settings app indexes all applications with a name suffix of " Settings", because the app is called "Maps Settings" it shows up in the settings app.

**Review by ADKaster — APPROVED** [review]

**Pull request merged**
