### PR TITLE
CI: Automatically apply pull request labels for generic PR actions

### PR DESCRIPTION
**Pull request by kleinesfilmroellchen**
Generic PR actions include opening a PR, submit review comments, adding new commits, etc. This prevents the reviewer and PR submitter from having to manually bounce the labels back and forth in the general case. The reviewer also may not have permission to set labels, meaning the reviewer won't be able to update the labels accordingly themselves.

This does not handle more subjective labels such as pr-is-blocked and pr-unclear. Unfortunately, there does not seem to be a GitHub Actions trigger for when a PR has merge conflicts, so the pr-has-conflicts label cannot be automatically applied.

Co-authored-by: kleines Filmröllchen <filmroellchen@serenityos.org>

Note: Because of [dumb GitHub restrictions](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull-request-events-for-forked-repositories-1), I cannot test this beyond the opening/closing stuff.

@Lubrsi

### CODE REVIEW

**Comment by bgianfo** [comment]
What changes are here since Luke's original PR?

**Comment by kleinesfilmroellchen** [comment]
@bgianfo I have addressed all cosmetic comments, switched the one confusing ternary around, added "pr-has-conflicts" to the "exception list" so that it is always preserved, and moved the entire script to a separate file to make development easier. I forgot to remove one debug logging statement but that will be gone in the next force push.

**Comment by kleinesfilmroellchen** [comment]
Also, I have changed the workflow to run on pull_request_target, as well as when a review is edited.

**Comment by kleinesfilmroellchen** [comment]
okay git just had a stroke, one minute

**Pull request closed without merging**
