### PR TITLE
LibGfx/GIF: Correctly write frames with a non-null position

### LINKED ISSUE #24411: gif encoder creates broken outputs
Input 1:

7z7c

`animation -o wow1.gif 7z7c.gif`

Output 1:

wow1

Input 2:

star-wars-impossible

Output 2:

`/animation -o wow.gif ~/Downloads/star-wars-impossible.gif` (this requires #24410 to produce this glitchy output at all):

wow

### PR DESCRIPTION
**Pull request by LucasChollet**
Fix #24411

### CODE REVIEW

**Review by nico — APPROVED** [review]
Maybe tweak the animation test to hit this case (see webp animation test for an example).

**Comment by LucasChollet** [comment]
Sure, you'll have to wait until tomorrow for that tho

**Comment by LucasChollet** [comment]
> see webp animation test for an example

This was the worst advice you could give me. I copied some parts of it, including this line, which behavior isn't really intuitive:
`rgb_bitmap_2->scanline(3)[3] = Color::Red;`
(hint: type of the lhs is ARGB aka int)

Fun fact: for some reason that I don't understand, the WebP test fails if you write a color with an alpha value equal to 255, but pass otherwise. I'll let you fix this one.

**Comment by nico** [comment]
#24433

**Pull request merged**
