### PR TITLE
Base: Add kill(1) manpage

### PR DESCRIPTION
**Pull request by Vantadaga**
See #11311

### CODE REVIEW

**Comment by kennethmyhra** [comment]
You need to update the commit title for the linter to be happy, not only the PR title

**Comment by kennethmyhra** [comment]
Have a look at this video (https://www.youtube.com/watch?v=ElRzTuYln0M) to learn our workflow of rewriting git history to reword, amend, reorder, delete, etc.

**Comment by demostanis** [comment]
s/singal/signal/
And perhaps a list of signals should be added? Or reference a man page that lists them?
Also what's the default signal to terminate processes?

**Comment by Vantadaga** [comment]
> s/singal/signal/ And perhaps a list of signals should be added? Or reference a man page that lists them? Also what's the default signal to terminate processes?

I will add a reference to the list of signals and add the name of the default signal

**Pull request closed without merging**
