### PR TITLE
LibC: Implement Itanium DSO Object Destruction API

### PR DESCRIPTION
**Pull request by ADKaster**
Implement __cxa_atexit and __cxa_finalize per the Itanium ABI spec. This allows serenity C++ programs to have globals with non-trivial destructors, and also lays some groundwork for dynamic linking in Userspace.

https://itanium-cxx-abi.github.io/cxx-abi/abi.html#dso-dtor

Also, get rid of the exit time destructor in LibGUI that causes every GUI app to ASSERT on exit :)

Unfortunately, the file static Allocators that the malloc implementation uses are not trivially destructible, so we have to guard against things trying to be free'd/allocated after they are destroyed. Now each Allocator has a "destroyed" flag that needs checked before interacting with it in malloc/free. If the chosen allocator has been destroyed in malloc, we panic, but in free, since the process is being destroyed anyway it's ok to not do as much bookkeeping as we might like.

### CODE REVIEW

**Comment by ADKaster** [comment]
Oh hm. Seems removing that ASSERT didn't fix the problem, just move it.

```
te(20): CEventLoop::quit(0)
USERSPACE(20) ASSERTION FAILED: node == m_head
/home/andrew/serenity/AK/InlineLinkedList.h:183 in void AK::InlineLinkedList<T>::remove(T*) [with T = ChunkedBlock]
signal: te(20) sent 6 to te(20)
terminate_due_to_signal te(20) <- 6
Finalizing Thread 0 in te(20)
0x0013f9ee  Scheduler::switch_now() +52
0x00143c54  Thread::die_if_needed() +92
0x00141026  syscall_handler +751
0x00140d03  syscall_asm_entry +24
0x080b55dd  raise +22
0x08048320  abort +13
0x080b5565  kill +0
0x080b3c1b  AK::InlineLinkedList<ChunkedBlock>::remove(ChunkedBlock*) +83
0x080b3922  free +798
0x0804cb2a  AK::OwnPtr<AK::Function<AK::NonnullRefPtr<GWidget> (GWidget*)>::CallableWrapperBase>::clear() [clone .isra.0] +22
0x0804cc34  GWidgetClassRegistration::~GWidgetClassRegistration() +16
0x08048e2e  __cxa_finalize +62
0x080b4001  exit +13
0x0805e09b  GApplication::exec() +37
0x0804862f  main +611
0x08048d86  _start +94
```
Any thoughts? Looks like the GWidgetClassRegistration *really* doesn't want to ever be destroyed.

**Comment by ADKaster** [comment]
Looks like it's failing on the last destructor for GWidgetClassRegistration?
It's fine destroying all but the last one...
```
te(17): CEventLoop::quit(0)
__cxa_finalize: 22 entries in the finalizer list
__cxa_finalize: calling entry[21] 0x080954e4(0x080fe590) dso: 0x080fa284
__cxa_finalize: calling entry[20] 0x080b51b6(0x080ffe60) dso: 0x080fa284
__cxa_finalize: calling entry[19] 0x080b3b01(0x00000000) dso: 0x080fa284
__cxa_finalize: calling entry[18] 0x0809795e(0x080fe598) dso: 0x080fa284
__cxa_finalize: calling entry[17] 0x08091154(0x080fe454) dso: 0x080fa284
__cxa_finalize: calling entry[16] 0x0807948e(0x080fe408) dso: 0x080fa284
__cxa_finalize: calling entry[15] 0x080792b8(0x080fe418) dso: 0x080fa284
__cxa_finalize: calling entry[14] 0x080734d6(0x080fe3f8) dso: 0x080fa284
__cxa_finalize: calling entry[13] 0x080734d6(0x080fe3fc) dso: 0x080fa284
__cxa_finalize: calling entry[12] 0x080734d6(0x080fe400) dso: 0x080fa284
__cxa_finalize: calling entry[11] 0x080734d6(0x080fe404) dso: 0x080fa284
__cxa_finalize: calling entry[10] 0x080715f2(0x080fe3e8) dso: 0x080fa284
__cxa_finalize: calling entry[9] 0x0804cc54(0x080fe380) dso: 0x080fa284
__cxa_finalize: calling entry[8] 0x0804cc54(0x080fe388) dso: 0x080fa284
__cxa_finalize: calling entry[7] 0x0804cc54(0x080fe390) dso: 0x080fa284
__cxa_finalize: calling entry[6] 0x0804cc54(0x080fe398) dso: 0x080fa284
__cxa_finalize: calling entry[5] 0x0804cc54(0x080fe3a0) dso: 0x080fa284
__cxa_finalize: calling entry[4] 0x0804cc54(0x080fe3a8) dso: 0x080fa284
__cxa_finalize: calling entry[3] 0x0804cc54(0x080fe3b0) dso: 0x080fa284
__cxa_finalize: calling entry[2] 0x0804cc54(0x080fe3b8) dso: 0x080fa284
__cxa_finalize: calling entry[1] 0x0804cc54(0x080fe3c0) dso: 0x080fa284
__cxa_finalize: calling entry[0] 0x0804cc54(0x080fe3c8) dso: 0x080fa284
USERSPACE(17) ASSERTION FAILED: node == m_head
/home/andrew/serenity/AK/InlineLinkedList.h:183 in void AK::InlineLinkedList<T>::remove(T*) [with T = ChunkedBlock]
signal: te(17) sent 6 to te(17)
terminate_due_to_signal te(17) <- 6
Finalizing Thread 0 in te(17)
0x0013f9ee  Scheduler::switch_now() +52
0x00143c54  Thread::die_if_needed() +92
0x00141026  syscall_handler +751
0x00140d03  syscall_asm_entry +24
0x080b560d  raise +22
0x08048320  abort +13
0x080b5595  kill +0
0x080b3c4b  AK::InlineLinkedList<ChunkedBlock>::remove(ChunkedBlock*) +83
0x080b3952  free +798
0x0804cb5a  AK::OwnPtr<AK::Function<AK::NonnullRefPtr<GWidget> (GWidget*)>::CallableWrapperBase>::clear() [clone .isra.0] +22
0x0804cc64  GWidgetClassRegistration::~GWidgetClassRegistration() +16
0x08048e59  __cxa_finalize +105
0x080b4031  exit +13
0x0805e0cb  GApplication::exec() +37
0x0804862f  main +611
0x08048d86  _start +94
```

**Comment by ADKaster** [comment]
Fixed it, malloc's Allocators were destroyed and we are trying to free things.

**Comment by awesomekling** [comment]
Okay! Let's merge it :) Thanks for working on this!

**Pull request merged**
