### PR TITLE
Browser: Add option to disable switching to new tabs automatically

### PR DESCRIPTION
**Pull request by mrkct**
When I middle-click a link I prefer to stay on the current tab and then, by myself, switch to that tab once I'm ready to look at it.

This PR adds an option to do that.

### CODE REVIEW

**Comment by nico** [comment]
Instead of adding an option, how about doing this on shift-middleclick, like in all other browsers?

**Comment by stelar7** [comment]
> Instead of adding an option, how about doing this on shift-middleclick, like in all other browsers?

For me (windows/chrome), shift-middleclick focuses the new tab, while non-shift middleclicks does not focus it. 
(Not sure if this what was you ment, but it sounds like its the other way around)

**Comment by mrkct** [comment]
Since this PR was opened another commit broke middle clicking URLs in both Browser and Ladybird. The first commit fixes that bug.

> Instead of adding an option, how about doing this on shift-middleclick, like in all other browsers?

Both Firefox and Chromium have this same option. Anyway I also added that shift-middle does the opposite behavior of non-shift middle clicking as Firefox and Chromium behave like this
Also, I changed the option to be disabled by default to be in line with Ladybird (which already did not activate tabs opened by middle clicks)

**Comment by nico** [comment]
> For me (windows/chrome), shift-middleclick focuses the new tab, while non-shift middleclicks does not focus it. (Not sure if this what was you ment, but it sounds like its the other way around)

Right, doing that seems nice than adding an option (?)

**Comment by mrkct** [comment]
> > For me (windows/chrome), shift-middleclick focuses the new tab, while non-shift middleclicks does not focus it. (Not sure if this what was you ment, but it sounds like its the other way around)
> 
> Right, doing that seems nice than adding an option (?)

That's implemented in the second commit.

I also added the checkbox because previously Browser worked the opposite way of most browsers and thought whoever implemented it that way used the equivalent option in Firefox or Chrome.

I can drop the commit that adds the option, but I don't see why not give the user a choice considering the code is pretty simple.

**Comment by SebastianZaha** [comment]
> Since this PR was opened another commit broke middle clicking URLs in both Browser and Ladybird. The first commit fixes that bug.

True, sorry about that, did not notice that middle click was not handled and relied on the activation default being true.

**Comment by SebastianZaha** [comment]
Just chiming in to say the fix in the first commit is still relevant for the regression I introduced for middle-clicking on links. If this whole PR is not desirable, perhaps the author can cherry-pick it into a separate PR. (Or I can do it as well).

**Comment by mrkct** [comment]
Right now I don't have a dev environment setup for rebasing on master and checking if this pr still builds & works.

@SebastianZaha if you want to make a pr for that commit feel free to do so.

**Comment by SebastianZaha** [comment]
I looked into the fix today, both for the middle click and for generally being consistent with Ctrl-click, ctrl-shift-click, shift-middleclick, ctrl-shift-enter (when link is tab-selected) etc. But it seems there are various interactions and bugs that tie into navigables, and there is also bigger work related to that in other PRs currently, so I will wait with these investigations until after that work is completed.

**Pull request closed without merging**
