### PR TITLE
Ports: Make array-like settings actual arrays

### PR DESCRIPTION
**Pull request by timschumi**
This helps when we need to have spaces in any of the *opts settings, since they were split regardless previously due to being passed without quotes.

### CODE REVIEW

**Comment by timschumi** [comment]
Just noticed that `showproperty` apparently has issues with empty arrays, so that will require some fixups.

**Comment by timschumi** [comment]
Rebased onto current master to resolve a conflict. The test failure seems unrelated.

**Comment by GMTA** [comment]
I like this change - however, it should be rebased on `master` and account for new ports (at least, `ncdu` is the one that I'm aware of).

**Comment by timschumi** [comment]
Indeed, I forgot to check for new ports the last time that I rebased. `ncdu` does now use the correct format, and I haven't seen any other changes in the git log that we would have to adapt to.

**Pull request merged**
