### PR TITLE
Ports: npiet

### PR DESCRIPTION
**Pull request by Ivoah**
Interpreter for piet programming language
https://www.bertnase.de/npiet/
https://www.dangermouse.net/esoteric/piet.html

### CODE REVIEW

**Comment by bgianfo** [comment]
Looks like the port lints are failing: 

```
Ports/npiet is missing required property 'auth_type'
Ports/libgd is missing required property 'auth_type'
[FAIL]: Meta/lint-ports.py
```

**Comment by linusg** [comment]
Please squash changes after code review as per the [contribution guidelines](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy) instead of adding a fixup commit to fix mistakes from the two previous commits.

Also take care to properly capitalize the first letter of the commit message after the prefix.

**Review by linusg — CHANGES_REQUESTED** [review]
Not like that though, one commit per port was correct. Just no fixups :)

**Comment by Ivoah** [comment]
Third time's the charm! Hopefully I got it all right this time...

**Pull request merged**
