### PR TITLE
Meta: Allow running Lagom tests with "serenity.sh run lagom <target>"

### PR DESCRIPTION
**Pull request by trflynn89**
Example invocations of this script change:

```bash
$ ./Meta/serenity.sh run lagom TestString
-- Configuring done
-- Generating done
-- Build files have been written to: /home/flynn/workspace/serenity/Build/lagom
ninja: Entering directory `/home/flynn/workspace/serenity/Build/lagom'
[0/2] Re-checking globbed directories...
[0/1] cd /home/flynn/workspace/serenity/Build/lagom && /home/flynn/workspace/serenity/Toolchain/Local/cm...SOURCE_DIR=/home/flynn/workspace/serenity /home/flynn/workspace/serenity/Build/lagom/Tests/AK/TestString
Running 19 cases out of 19.
Running test 'construct_empty'.
Completed test 'construct_empty' in 0ms
[... truncated for brevity ...]
Completed test 'repeated' in 0ms
Finished 19 tests and 0 benchmarks in 1ms (0ms tests, 0ms benchmarks, 1ms other).
Out of 19 tests, 19 passed and 0 failed.
```
```bash
$ touch AK/String.cpp

$ ./Meta/serenity.sh run lagom TestString construct_empty
-- Configuring done
-- Generating done
-- Build files have been written to: /home/flynn/workspace/serenity/Build/lagom
ninja: Entering directory `/home/flynn/workspace/serenity/Build/lagom'
[0/2] Re-checking globbed directories...
[11/12] cd /home/flynn/workspace/serenity/Build/lagom && /home/flynn/workspace/serenity/Toolchain/Local/.../flynn/workspace/serenity /home/flynn/workspace/serenity/Build/lagom/Tests/AK/TestString construct_empty
Running 1 cases out of 19.
Running test 'construct_empty'.
Completed test 'construct_empty' in 0ms
Finished 1 tests and 0 benchmarks in 0ms (0ms tests, 0ms benchmarks, 0ms other).
Out of 1 tests, 1 passed and 0 failed.
```
```bash
$ cat ~/Desktop/test.js 
const a = new Date();
print(a);

$ ./Meta/serenity.sh run lagom js ~/Desktop/test.js
-- Configuring done
-- Generating done
-- Build files have been written to: /home/flynn/workspace/serenity/Build/lagom
ninja: Entering directory `/home/flynn/workspace/serenity/Build/lagom'
[0/2] Re-checking globbed directories...
[0/1] cd /home/flynn/workspace/serenity/Build/lagom && /home/flynn/workspace/serenity/Toolchain/Local/cm.../home/flynn/workspace/serenity /home/flynn/workspace/serenity/Build/lagom/js /home/flynn/Desktop/test.js
[Date] Wed Jan 25 2023 14:56:09 GMT-0500 (Eastern Standard Time)
```
```bash
$ ./Meta/serenity.sh run lagom js -c "let a = 12389; print(a); print(a);"
-- Configuring done
-- Generating done
-- Build files have been written to: /home/flynn/workspace/serenity/Build/lagom
ninja: Entering directory `/home/flynn/workspace/serenity/Build/lagom'
[0/2] Re-checking globbed directories...
[0/1] cd /home/flynn/workspace/serenity/Build/lagom && /home/flynn/workspace/serenity/Toolchain/Local/cm...workspace/serenity /home/flynn/workspace/serenity/Build/lagom/js -c "let a = 12389; print(a); print(a);"
12389
12389
```
```bash
./Meta/serenity.sh run lagom test-js -f NumberFormat -t                
-- Configuring done
-- Generating done
-- Build files have been written to: /home/flynn/workspace/serenity/Build/lagom
ninja: Entering directory `/home/flynn/workspace/serenity/Build/lagom'
[0/2] Re-checking globbed directories...
[2/3] cd /home/flynn/workspace/serenity/Build/lagom && /home/flynn/workspace/serenity/Toolchain/Local/cm...DIR=/home/flynn/workspace/serenity /home/flynn/workspace/serenity/Build/lagom/test-js -f NumberFormat -t
 PASS  builtins/Intl/NumberFormat/NumberFormat.@@toStringTag.js (7ms)
 PASS  builtins/Intl/NumberFormat/NumberFormat.js (54ms)
 PASS  builtins/Intl/NumberFormat/NumberFormat.prototype.format.js (69ms)
 PASS  builtins/Intl/NumberFormat/NumberFormat.prototype.formatRange.js (7ms)
 PASS  builtins/Intl/NumberFormat/NumberFormat.prototype.formatRangeToParts.js (9ms)
 PASS  builtins/Intl/NumberFormat/NumberFormat.prototype.formatToParts.js (94ms)
 PASS  builtins/Intl/NumberFormat/NumberFormat.prototype.resolvedOptions.js (33ms)
 PASS  builtins/Intl/NumberFormat/NumberFormat.supportedLocalesOf.js (8ms)

Test Suites: 24 passed, 24 total
Tests:       192 passed, 192 total
Files:       8 total
Time:        284ms
```

### CODE REVIEW

**Review by ADKaster — COMMENTED** [review]
At a scroll through this seems reasonable enough, though I wonder if the bashisms in use are ok on macOS? It tends to have issues from what I remember

**Comment by trflynn89** [comment]
> I wonder if the bashisms in use are ok on macOS? It tends to have issues from what I remember

I'll try to test that, but our build instructions do say to use bash from homebrew on mac

**Comment by trflynn89** [comment]
>I wonder if the bashisms in use are ok on macOS? It tends to have issues from what I remember

Worked fine with bash 3.2.57 on a mac for me

**Comment by trflynn89** [comment]
@ADKaster realized it's trivial to now use this to run ladybird with arguments too, so I pushed a second commit to do that.

**Pull request merged**
