### PR TITLE
Ports/libyaml: Fix download location

### PR DESCRIPTION
**Pull request by EWouters**
I'm not sure how the other link got into the commit.

### CODE REVIEW

**Comment by timschumi** [comment]
I'm pretty sure that the original link is correct. Also, have you made sure that the checksum is still the same?

**Comment by trflynn89** [comment]
> I'm pretty sure that the original link is correct. Also, have you made sure that the checksum is still the same?

The old link is for the release package that the libyaml authors create, the new link is for a .tar.gz of the source code that GitHub provides. That change seems right to me if we are cross-compiling from source. And the existing hash (fa240d...) is actually for the new link - on master, if you run package.sh, we get a hash mismatch.

**Comment by EWouters** [comment]
I must have tried the Release link as timschumi mentioned before that that was the preferable source, but it has a different build system. And so I thought I reverted the change, but I borked it.

It feels like a big responsibility that PRs don't always get tested before they get merged, as I do make silly mistakes. Ports CI wen?

**Comment by linusg** [comment]
> It feels like a big responsibility that PRs don't always get tested before they get merged, as I do make silly mistakes.

Just don't make untested PRs then :^)

**Review by timschumi — APPROVED** [review]
Well, it builds. (`x86_64 GNU`)

**Pull request merged**
