### PR TITLE
DisplaySettings: Add UI for switching the scale factor

### PR DESCRIPTION
**Pull request by nico**
For now, only support 1x and 2x scale.

I tried doing something "smarter" first where the UI would try
to keep the physical resolution constant when toggling between
1x and 2x, but many of the smaller 1x resolutions map to 2x
logical resolutions that Compositor rejects (e.g. 1024x768 becomes
512x384, which is less than the minimum 640x480 that Compositor
wants) and it felt complicated and overly magical.

So this instead just gives you a 1x/2x toggle and a dropdown
with logical (!) resolutions. That is, 800x600 @ 2x gives you
a physical resolution of 1600x1200.

If we don't like this after trying it for a while, we can change
the UI then.

### CODE REVIEW

**Comment by nico** [comment]
dpi1x
dpi2x

**Comment by nico** [comment]
(fuzzer build is "/home/runner/work/serenity/serenity/Userland/Libraries/LibGfx/Bitmap.cpp:502: undefined reference to `Gfx::Bitmap::to_bitmap_backed_by_anon_fd() const'", not caused by this change, already broken at head.)

**Comment by tomuta** [comment]
Hm that seems rather confusing. I would have expected things to be twice as big when I select that option. At least that's what Windows and Ubuntu do. It would never cross my mind that I'd have to select a resolution other than the monitor's native resolution, half the resolution. Or am I misunderstanding this?

**Comment by nico** [comment]
Hm, I can't see a button for this in Ubuntu. (I'm using https://en.wikipedia.org/wiki/Cinnamon_(desktop_environment) ). Windows only has a ui scale slider and no pixels at all as far as I can tell – I guess it always uses the display's native resolution? (But a qemu window has no such thing as a native resolution.)

**Comment by nico** [comment]
Oh, and I didn't click "Apply" yet in screenshot two. When you click "Apply" after switching from 100% to 200% without touching the resolution dropdown, the qemu window sizes doubles in each dimenson.

**Comment by tomuta** [comment]
> Hm, I can't see a button for this in Ubuntu.

Maybe it requires certain hardware support to show up? Not sure, Here's how it looks like on 20.10:
Screenshot from 2021-01-15 19-30-50

> Windows only has a ui scale slider and no pixels at all as far as I can tell – I guess it always uses the display's native resolution? (But a qemu window has no such thing as a native resolution.)

Well in Windows 10 it's the madness of settings all over the place. I believe the resolution setting is in one place and then you have to click on advanced settings or something and then they have it there. Too lazy to boot into it to take a screenshot, but it's effectively the same as in Ubuntu: You pick the resolution as-is (in most cases you'd pick the native resolution of the display) and then a scale factor where 1x/100% is normal, 2x/200% everything is twice the size.

**Comment by tomuta** [comment]
> Oh, and I didn't click "Apply" yet in screenshot two. When you click "Apply" after switching from 100% to 200% without touching the resolution dropdown, the qemu window sizes doubles in each dimenson.

So then it would use a display resolution of 2048x1536 in this particular example? That sounds confusing when it only shows 1024x768.

**Comment by nico** [comment]
Right, that's what it'd do. As the commit message says, I tried the other behavior first but it gets a bit messy because the lower few resolutions at 2x are below Serenity's minimum resolution.

Exposing logical coordinates everywhere is self consistent with the code too. I think I'd like to try this for a bit and see how it feels. We can definitely iterate on the ui though.

**Comment by nico** [comment]
Another reason why this makes some amount of sense is that when you resize a window, you get an overlay that shows the current window size in logical coordinates, and with this approach the numbers on the overlay match the numbers in the DisplaySettings dialog.

**Pull request merged**
