### PR TITLE
Github: Enable build breaks on x86_64 test failures

### PR DESCRIPTION
**Pull request by dascandy**

### CODE REVIEW

**Review by gunnarbeutner — APPROVED** [review]

**Comment by dascandy** [comment]
x86_64 CI was broken in the past 24 hours. Opened PR8863 to fix it again, and then will rerun the checks.

**Comment by ADKaster** [comment]
Lately (at least the last 6 months?) We've been setting the commit category on the .github/workflow files to `CI: `, rather than GitHub

**Comment by sin-ack** [comment]
> Lately (at least the last 6 months?) We've been setting the commit category on the .github/workflow files to `CI: `, rather than GitHub

It's kind of confusing because the `.github` folder is not named with our naming convention. Perhaps it is a good idea to add this as a bulletpoint to the `CONTRIBUTING` file?

**Comment by ADKaster** [comment]
Hmm ok double checking looks like before May it was always "Meta" and I started the trend of using CI 😅

**Pull request merged**
