### PR TITLE
LibMarkdown: Add whitespace after code blocks

### PR DESCRIPTION
**Pull request by demostanis**
I thought I had done that in #14723

### CODE REVIEW

**Comment by demostanis** [comment]
(This PR adds a new line after code blocks (as the title says) so that it looks better)
image

**Comment by bgianfo** [comment]
Why are there other changes here than what is described in the commit message? What are they fixing? All that should be required is the single newline at the end of the loop?

**Comment by demostanis** [comment]
@bgianfo for the `const&`, LSP was advising this change. For the `\x1b[0m` I removed, it was added by mistake in my precedent PR, and it was used to remove background coloring of code blocks (which isn't a thing anymore)
Should I make three different commits?

**Comment by bgianfo** [comment]
No, please don't split it into three commits, your PR title and message should just accurately describe the all the changes you made.

**Comment by demostanis** [comment]
@bgianfo is that  better?

**Pull request merged**
