### PR TITLE
Utilities/du: Add options to filter files with min and max sizes

### PR DESCRIPTION
**Pull request by supercomputer7**

### CODE REVIEW

**Comment by timschumi** [comment]
This is inherited from coreutils.

**Comment by timschumi** [comment]
> Does it make sense to be 100% compatible with coreutils here? For me, it makes a lot more sense to have a range with 2 flags instead of "put a minus sign to do that or not a minus sign otherwise", which doesn't even let you have a range as a filter.

If you want to implement one option in the terms of the other, then feel free to do that. But we probably shouldn't yeet the old option outright.

**Comment by supercomputer7** [comment]
> > Does it make sense to be 100% compatible with coreutils here? For me, it makes a lot more sense to have a range with 2 flags instead of "put a minus sign to do that or not a minus sign otherwise", which doesn't even let you have a range as a filter.
> 
> If you want to implement one option in the terms of the other, then feel free to do that. But we probably shouldn't yeet the old option outright.

Alright, I think it's OK now :)

**Review by timschumi — APPROVED** [review]
Not quite sure what the purpose of an upper limit and a lower limit at the same time would be, but given that you thought of implementing this in the first place, I'm going to assume that you had something in mind.

**Comment by supercomputer7** [comment]
> Not quite sure what the purpose of an upper limit and a lower limit at the same time would be, but given that you thought of implementing this in the first place, I'm going to assume that you had something in mind.

Oh, that was a thing I wanted to implement after trying to search for files in a specific size on my host linux machine yesterday, and was frustrated to see that I need to work with `grep` and sort things beforehand...

**Pull request merged**
