### PR TITLE
Userland/JS: Extend the global object when using a REPL 

### PR DESCRIPTION
**Pull request by DAlperin**
~~Add the option to load in a global repl object by calling interpreter.enable_repl_session(print); where print is a function that accepts a JS::Value for use in displaying evaluated output. The repl command are: repl.exit(code), repl.load("file1", "file2", "fileEtc"), and repl.help()~~

CC: @awesomekling @bugaevc

### CODE REVIEW

**Comment by bugaevc** [comment]
Hmm, why is it something LibJS should implement? APIs like this are usually provided by "the environment" — in a browser, you'd have `window` and so on. I'd say this should live in `js.cpp`. Or, alternatively, LibJS itself should implement a full(er)-featured interpreter.

**Comment by awesomekling** [comment]
It’s now possible to provide a custom global object class for Interpreter to use. LibWeb uses this to install a Web::Bindings::WindowObject as the GO. I think we can use the same approach here and have the js program install a custom GO as well. Just make a new object that inherits from JS::GlobalObject and install functions/properties on it.

**Comment by DAlperin** [comment]
Sounds good.

**Comment by DAlperin** [comment]
It is now implemented by extending the custom object when using a REPL

**Comment by awesomekling** [comment]
Okay very cool. Thank you for implementing this :)

**Pull request merged**
