### PR TITLE
rev: Add support for the '-' filename

### PR DESCRIPTION
**Pull request by Mango0x45**
- Meta: Ignore vim's .exrc config
- Rev: Read from stdin if the filename '-' is given
- Rev: Document the '-' filename

### CODE REVIEW

**Review by MacDue — COMMENTED** [review]
Nit: For utilities the commit prefix is normally the name without any case changes (so the prefix here should be `rev:  ` not `Rev: `).

**Review by MacDue — APPROVED** [review]
Seems alright, not sure if adding `.exrc` to the `.gitignore` should be included in this PR though.

**Comment by Mango0x45** [comment]
> not sure if adding `.exrc` to the `.gitignore` should be included in this PR though.

I could create a new PR for it, but is it really all that important? It’s got its own commit anyways.

**Comment by MacDue** [comment]
It's probably alright as is

**Pull request merged**
