### PR TITLE
Ladybird/AppKit: Add Default Check and Handler

### PR DESCRIPTION
**Pull request by tomlister**
Asks the user whether they want to set Ladybird as the default browser, and registers event handlers to make a new tab once a user clicks on a URL in another application

Screenshot 2024-04-05 at 7 30 08 pm

### CODE REVIEW

**Comment by tomlister** [comment]
@warpdesign On launch. I just realised that this alert blocks the main thread, and I'm working on preventing that from happening.

**Comment by warpdesign** [comment]
> @warpdesign On launch. I just realised that this alert blocks the main thread, and I'm working on preventing that from happening.

I personally don't like this kind of pops up every single browser vendor does.

**Comment by tomlister** [comment]
> I personally don't like this kind of pops up every single browser vendor does.

That's fair enough, I can understand how it can be annoying. It tried to make the popup language as simple and painless as possible. Additionally, there is a suppression checkbox to ensure it never pops up again. Do you have any alternatives as to how it could be triggered?

**Comment by awesomekling** [comment]
This seems highly premature as we’re nowhere near ready to be anyone’s default browser 😅

**Comment by tomlister** [comment]
Reduced implementation to one method.
Still having issues with the handler not being called on a cold start of Ladybird (open link when Ladybird is closed).
Could there be something up with the event loop? Any thoughts?

**Pull request closed without merging**
