### PR TITLE
2048: Evil AI

### PR DESCRIPTION
**Pull request by dmitrii-ubskii**
A hard mode for 2048 in which the tile generator hates you. It generates new tiles with the worst possible place and value.

New PR (#7142) because the only way I know to fix the commit messages was to force-push amended commits.

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
> 2048: Reapply clang-format (whoops)

Please don't add separate fixup commits, squash these changes into the appropriate previous commits instead.

The commit history should be clean, atomic commits.

**Comment by dmitrii-ubskii** [comment]
> > 2048: Reapply clang-format (whoops)
> Please don't add separate fixup commits, squash these changes into the appropriate previous commits instead.
> The commit history should be clean, atomic commits.

That should do it.

**Comment by linusg** [comment]
> That should do it.

No need to mention it in the commit message either :)

**Comment by dmitrii-ubskii** [comment]
I did not mean to close this, dammit. Not sure how that keeps happening. Sorry about that.

**Pull request closed without merging**
