### PR TITLE
LibWeb: Separate the painting commands list from RecordingPainter

### PR DESCRIPTION
**Pull request by kalenikaliaksandr**
Separating the recorder list from the painter will allow us to save it for later execution without carrying along the painter's state. This will be useful once we have a separate thread for executing painting commands, to which we will have to transfer commands from the main thread.

Preparation for https://github.com/SerenityOS/serenity/pull/23108

### CODE REVIEW

**Comment by awesomekling** [comment]
Since the namespace is already `Web::Painting`, how about `Web::Painting::Command` and `Web::Painting::CommandList` instead of `Web::Painting::PaintingCommand` and `Web::Painting::PaintingCommandList`?

**Comment by kalenikaliaksandr** [comment]
sure, makes sense. I have done following renamings:
- Painting::PaintingCommand to Painting::Command
- Painting::PaintingCommandsList to Painting::CommandsList
- Painting::PaintingCommandExecutor to Painting::CommandExecutor
- Painting::PaintingCommandExecutorCPU to Painting::CommandExecutorCPU
- Painting::PaintingCommandExecutorGPU to Painting::CommandExecutorGPU

**Comment by awesomekling** [comment]
Command list, not commands list :)

**Comment by kalenikaliaksandr** [comment]
> Command list, not commands list :)

Fixed

**Pull request merged**
