### PR TITLE
Fonts: Update Satori and Ataraxia fonts

### PR DESCRIPTION
**Pull request by djwisdom**
Latin glyphs are now added to the fonts.

### CODE REVIEW

**Comment by djwisdom** [comment]
Failed checks mainly due to connection refused status and not related to the submitted fonts I believe.

**Review by Xexxa — CHANGES_REQUESTED** [review]
`Themes: Update Ataraxia fonts`
Commit category should be "Base" and not "Themes", it should also mention how/why there should be an update, like "Base: Add Latin-1 Supplement characters to Ataraxia fonts"

`First maintenance update for Ataraxia fonts`
This does not add anything relevant. You should mention what codepoints you have added, in this case it looks like 00A1-00FF? There is ~1000 Latin characters. Right now I'm not sure what to review without comparing with an older version of each font-file which is more work then I would like and makes a messy git history (from what I understand).

**Comment by djwisdom** [comment]
Yup, it should be Base and not Themes. Need to avoid doing the same mistake in the future. and it is indeed the additional 00A1-00FF code points. Will update the commit title/description. Thanks xexxa.

**Comment by djwisdom** [comment]
I give up. I always stumble on the lint checker. Here's my git history.
  510  history | grep git
  511  git log --oneline
  512  git log
  513  git rebase -i 0b0f7b60f638366d71ec6f699e49829c5f2c6a4c
  514  git log
  515  git rebase -i 95c064b281d0774aa0b21512f8b789dd4bf65db6
  516  git rebase -i 95c064b281d0774aa0b21512f8b789dd4bf65db6
  517  git rebase --abort
  518  git status
  519  git rebase -i 95c064b281d0774aa0b21512f8b789dd4bf65db6
  520  git log
  521  git rebase --abort
  522  git status
  523  git rebase -i 95c064b281d0774aa0b21512f8b789dd4bf65db6
  524  git rebase --abort
  525  git status
  526  git branch
  527  git log
  528  git status
  529  git rebase -i 31b24c2b297f603856b4850fb9568b5b91a75621
  530  history | grep git
  531  git log
  532  git rebase HEAD^ --soft
  533  git reset HEAD^ --soft
  534  git status
  535  git restore --staged  Base/res/fonts/AtaraxiaRegular10.font
  536  git status
  537  git log
  538  git status
  539  git commit
  540  git status
  541  rm Base/res/fonts/AtaraxiaRegular10.font
  542  git status
  543  cd Base/fonts
  544  cd Base/res/fonts
  545  ls
  546  scp djwisdom@192.168.0.12:\~/Satori*.font .
  547  git status
  548  git log
  549  git status
  550  git add SatoriBold10.font SatoriRegular10.font
  551  git status
  552  git commit
  553  git log
  554  git status
  555  git add SatoriMonoBold10.font SatoriMonoRegular10.font
  556  git status
  557  git commit
  558  git status
  559  git log
  560  git rebase --continue
  561  git push
  562  git pull
  563  git push
  564  git log --one-line
  565  cd ../..
  566  cd ..
  567  git log --oneline
  568  git log
  569  git rebase -i 44bd74c0f595da3a44c0e722a52ef4c821d8bf45
  570  git rebase --continue
  571  git status
  572  git commit
  573  git rebase --edit-todo
  574  git status
  575  git rebase --continue
  576  git reset HEAD^ --soft
  577  git status
  578  git log
  579  git status
  580  git pull
  581  git branch
  582  git rebase --continue
  583  git log
  584  git pull
  585  git log
  586  git commit --ament
  587  git commit --amend
  588  git status
  589  git pull
  590  git log
  591  git status
  592  git log --oneline
  593  git rebase -i HEAD~14
  594  git log --oneline
  595  git status
  596  clear
  597  git log --oneline
  598  git pull
  599  git status
  600  git log --oneline
  601  git push
  602  history

This is the first time I tried squash only to find out that the linter will still trip on the commit I thought I already squashed. I need to learn more git tricks else I need to manage my expectation more. :^)

**Pull request closed without merging**
