### PR TITLE
AK+LibC+Kernel+Ports: Add GNU core utilities

### PR DESCRIPTION
**Pull request by timschumi**
I’d just like to interject for a moment. What you’re referring to as SerenityOS, is in fact, GNU/SerenityOS, or as I’ve recently taken to calling it, GNU plus SerenityOS.

While not terribly useful in the long term (as we are aiming to make our own tools sufficiently compatible), it has been (and likely will be) a good benchmark for POSIX compatibility.

~~This Pull Request is a draft until #13320 and #13324 are merged, which this depends on.~~

### CODE REVIEW

**Comment by circl-lastname** [comment]
Does this conflict in any way with the Serenity utilities? What command runs when you enter `ls` for instance?

**Comment by EWouters** [comment]
This does not seem to compile for me (on Mac)
```
  CC       lib/frexp.o
lib/freadptr.c: In function 'freadptr':
lib/freadptr.c:123:3: error: #error "Please port gnulib freadptr.c to your platform! Look at the definition of fflush, fread, getc, getc_unlocked on your system, then report this to bug-gnulib."
  123 |  #error "Please port gnulib freadptr.c to your platform! Look at the definition of fflush, fread, getc, getc_unlocked on your system, then report this to bug-gnulib."
      |   ^~~~~
make[2]: *** [lib/freadptr.o] Error 1
make[2]: *** Waiting for unfinished jobs....
lib/freadahead.c: In function 'freadahead':
lib/freadahead.c:101:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
  101 |  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
      |   ^~~~~
make[2]: *** [lib/freadahead.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by timschumi** [comment]
> Does this conflict in any way with the Serenity utilities? What command runs when you enter `ls` for instance?

No, they won't conflict, as coreutils gets installed to `/usr/local/bin`, but the Serenity utilities are located in `/usr/bin` or `/bin`.

If you run `ls` and both are installed, the coreutils version will be used, as our `PATH` is configured to look in `/usr/local/bin` first.

> This does not seem to compile for me (on Mac)

The function is definitely there though. You built the system before trying to build the Port, right?

**Comment by EWouters** [comment]
Ah, my bad, I forgot to the system first, will check now.

**Comment by timschumi** [comment]
Same thing here, that issue has been fixed separately and is already fixed in `master`. But granted, I should rebase this PR.

**Comment by EWouters** [comment]
Yes, can confirm that it works!

**Comment by timschumi** [comment]
From `coreutils-9.0/src/stat.c`:

```
/* Return the type of the specified file system.
   Some systems have statfvs.f_basetype[FSTYPSZ] (AIX, HP-UX, and Solaris).
   Others have statvfs.f_fstypename[_VFS_NAMELEN] (NetBSD 3.0).
   Others have statfs.f_fstypename[MFSNAMELEN] (NetBSD 1.5.2).
   Still others have neither and have to get by with f_type (GNU/Linux).
   But f_type may only exist in statfs (Cygwin).  */
```

I haven't noticed before, but `f_basename` is apparently a AIX/HP-UX/Solaris-specific extension, and there doesn't seem to exist any POSIX equivalent to that. Do we implement those at all? Do we have any preference for which to pick if there are multiple options (for example in this case)?

**Pull request merged**
