### PR TITLE
Chess: Remove 1:1 window aspect ratio

### PR DESCRIPTION
**Pull request by joshuagollaher16**
The window is now able to be resized both horizontally and vertically. The board now adjusts position to the center of the board, which will try to take up as much space as possible while remaining a square.

The window can also now be maximized :^)

### CODE REVIEW

**Comment by awesomekling** [comment]
Yeah, this seems like a reasonable solution to the problem :)
But please use `clang-format`

**Comment by joshuagollaher16** [comment]
I ran clang-format and committed the changes.

**Comment by josh-perry** [comment]
I don't think you meant to close this?

**Comment by joshuagollaher16** [comment]
I didn't mean to, sorry.

I'm new to git and didn't know if I needed to resubmit it for the new commits.

**Comment by joshuagollaher16** [comment]
Why does it say missing commit category? Isn't Chess: the category?

**Comment by ADKaster** [comment]
Your branch has 3 commits when it should have only 1. The merge commit shouldn't be there, and your clang-format fix should be squashed into the first commit. Feel free to ask around on the #development channel on discord if you're not sure how to rebase and squash for the PR per the contribution guidelines :).

**Comment by joshuagollaher16** [comment]
Alright, I think I got it figured out.

I reset, then merged my two commits, and pushed so I think it should work now.

Sorry for being a dolt :^)

**Comment by joshuagollaher16** [comment]
Closed because I put the pr on a separate branch from master

**Pull request closed without merging**
