### PR TITLE
Keymaps: Added a new Italian keymap.

### PR DESCRIPTION
**Pull request by ITHackerstein**
This adds a new keymap for Italian keyboards.

Right now, there isn't a way to type the curly braces the standard way
(AltGr + Shift + [), so I came up with these two ways:
AltGr + 8, Alt + [ -> {;
AltGr + 9, Alt + ] -> }.

### CODE REVIEW

**Comment by emanuele6** [comment]
related #2150

**Comment by ITHackerstein** [comment]
I've actually managed to implement a new map for the Shift+AltrGr key combination.

The last thing left to do is change the KeyboardMapper application to support this new map.

**Comment by ITHackerstein** [comment]
Now KeyboardMapper also supports the Shift + AltGr map.

**Comment by emanuele6** [comment]
Closes #2150

**Comment by emanuele6** [comment]
Fixes #2150.

**Comment by emanuele6** [comment]
Can you please squash together 55c3903 and 1f3b809?

**Comment by ITHackerstein** [comment]
I think we're ready to merge, aren't we?

**Comment by awesomekling** [comment]
Oops, sorry I didn't notice this until now.
This cannot be merged due to conflicts. And please don't include merge commits in PR's.
Also this should not have been squashed into a single commit.

**Comment by ITHackerstein** [comment]
Okay, so I split the commit again into multiple commits, fixed the merge conflict and I think it's now fine.

**Pull request merged**
