### PR TITLE
LibGfx: Improve spec compliance and add support for uncompressed grayscale images in TGAImageDecoderPlugin

### PR DESCRIPTION
**Pull request by mkanilsson**
This PR improves spec compliance in TGAImageDecoderPlugin by respecting the order of image data set in Image descriptor bits 4 & 5. Previously, X and Y origin was incorrectly used to determine the order of image data but they are supposed to be used to position the image on the screen as TarGA is a file format designed for graphics cards.

This fixes a bug where images generated with `magick input.tga -colorspace Gray -compress None output.tga` would render upside-down.

Support for uncompressed grayscale images is also added.

### CODE REVIEW

**Comment by nico** [comment]
Thanks!

Could you add test images? Either images you've drawn yourself, or convert an existing image to the newly supported format.

Put them in Tests/LibGfx/test-inputs/tga and `git add` them.

Build like so:

    Meta/serenity.sh build lagom image animation unzip TestDeflate TestImageDecoder TestBitStream gzip

Run tests like so:

     (cd Tests/LibGfx; ../../Build/lagom/bin/TestImageDecoder)

(You can pass the name of a test as an argument to run just that test.)

Say in the commit description how you created the image (the `magick` invocation you have in the PR description is great).

Add the test image for each feature into the commit adding support for that feature.

**Comment by mkanilsson** [comment]
I've added a test case and image for uncompressed black and white.

Adding a test for the spec compliance part is a bit harder since decoding doesn't fail, it just reads the bytes in the wrong order resulting in the image being upside-down.

**Comment by nico** [comment]
You can get a pixel from the first scanline (`frame->get_pixel()`) and from the last scanline and make the test check that it has the right value. If the image is flipped, that will fail. (Row 0 is always supposed to be the top row in LibGfx)

**Comment by nico** [comment]
(like so:


```
    auto frame = TRY_OR_FAIL(expect_single_frame_of_size(*plugin_decoder, { 400, 300 }));

    // ...
    EXPECT_EQ(frame.image->get_pixel(60, 75), Gfx::Color(130, 130, 130));
```

This is from test_tiff_grayscale_alpha.)

**Comment by mkanilsson** [comment]
Done! Took some time to find a way to generate the images. I hope my description in the commit is good enough.

**Comment by nico** [comment]
Thanks! Happy to merge as-is.

From looking around, it sounds like GIMP can save tga files with origin set to either bottom-left or top-left.

ImageMagick might also support it, via `convert -orient BottomLeft logo.tga` (cf `-orient LIST`).

Preview.app does seem to support bottom left and top left, but not origins on the right. We can still support it, but it doesn't seem to be widely used.

Finally, two notes on the tests:

1. Instead of having the pixel data in the same order in all 4 files, it's imho slightly preferable to have them all render the same (which, if ImageMagick does indeed support this via `-orient`, should be fairly easy to do) – red pixel always in the top right after decoding, green always top right, etc.
2. Once that is done, instead of adding 4 tests, you could have a single test that loops through the 4 filenames and does the same check for all of them. See e.g. test_jbig2_decode for an example of that.

Let me know if you'd prefer I merge this as-is, or if you'd like to futz with it some more :) Either works for me.

**Comment by mkanilsson** [comment]
Sure thing, I can fix that tomorrow.

I'll probably end up using a python script for the images but I'll try ImageMagick and see how it goes.

Orientation in GIMP seems to only set x/y origin which according to the spec (https://www.conholdate.app/viewer/view/rVqTeZPLAL/tga-file-format-specifications.pdf?default=view&preview=
) is used for positioning of the image relative to the bottom-left of the screen (Page 7, Image Specification - Field 5) and not Image descriptor bits 4 & 5, which are meant for data order(Page 9, Image Specification - Field 5). I might be wrong about how GIMP save the image though, I'll dig into it.

**Comment by nico** [comment]
With #25030 and this patched in, `Build/lagom/bin/image -o tmp.png Tests/LibGfx/test-inputs/tga/square-right-top.tga` produces a tmp.png that looks like square-left-top.tga in Preview.app – maybe your python script has x and y swapped?

**Comment by mkanilsson** [comment]
The bits are set correctly in my python script, however, I might have messed up the names. This has been fixed by following the table in the spec (Table 2 - Image Origin), everything is now working as expected and creating the images in GIMP was very straightforward. If it had "right" in the name, I flipped the left and right side. If it had "top" in the name, I flipped the top and bottom. 

I applied your patch and all images get displayed correctly after converting them to png.

**Comment by nico** [comment]
Thanks!

**Pull request merged**
