### PR TITLE
FileManager: Close the properties window on escape

### PR DESCRIPTION
**Pull request by LucasChollet**
**LibGUI: Don't call `on_escape_pressed` from EditingEngines**

The call will be handled in `TextEditor::keydown_event`, just after that
`EditingEngine::on_key()` is called.

**LibGUI: Bubble up Key_Escape if no hook is plugged in TextEditor**

The TextEditor widget was always accepting the Key_Escape event, even if
the `on_escape_pressed` was empty. In other words, it was discarding the
event.

This behavior prevented shortcuts to be activated at a higher level.

**FileManager: Return a StringView from PropertiesWindow::get_description**

**FileManager: Exit the properties window on escape**

### CODE REVIEW

**Comment by awesomekling** [comment]
Hmm, I wonder if the properties window is technically a "dialog", and maybe it could inherit  `GUI::Dialog` then. And maybe `GUI::Dialog` could then always handle escape presses, and we wouldn't need to think about it here. :yakthonk:

**Comment by LucasChollet** [comment]
> Maybe it could inherit GUI::Dialog then

I thought that you might not want to do that: 7e6c27a6, (it's #4648).

> GUI::Dialog could then always handle escape presses

It already does by overriding the event function and giving this event an absolute priority, which I think is bad as you might want to have a custom behavior for the widget (as closing the IncrementalSearchBanner).

There are three possibilities that I see to make the PropertyWindow close on escape:
1. Make the property window a Dialog and allow dialogs to be non-modal
2. Make PropertiesWindow handle escape the same way as dialogs (and taking the priority over widgets) which I think is a bad design
3. Convince TextBox to not swallow none used events

IMO, option 3 is a long term investment as it solves a fundamental issue with the widget. But once that's fixed, we can reduce the priority of dialog-specific events and make PropertyWindow a non-modal dialog.

**Comment by awesomekling** [comment]
That's some nice digging, you got me there! 😅 

Okay, then the main thing that feels weird here is using a `GUI::Action` (`m_on_escape`) instead of just listening for the escape key event. We don't normally use invisible actions that don't go in a menu or toolbar, so this feels out-of-place.

**Comment by LucasChollet** [comment]
> That's some nice digging, you got me there! sweat_smile

I suspected that someone would ask me this question. But when I saw that it was you, I went like, perfect timing to pull out a UNO reverse card! :smile:

> Okay, then the main thing that feels weird here is using a GUI::Action (m_on_escape) instead of just listening for the escape key event. We don't normally use invisible actions that don't go in a menu or toolbar, so this feels out-of-place.

It didn't feel very natural to do that, but it's the best "easy" solution. Listening to the escape key event is basically recreating the `Dialog` class.
The real solution IMO is to reduce the escape key priority in `Dialog`s, allow them to be modal and make the property window be a `Dialog`. But I fear that the first step is a :yakhole:, and it needs thorough testing anyway. Which I wasn't fond of the day I created this PR. Let's see if I get down to it in the next few days, otherwise I will add a fixme.

**Comment by awesomekling** [comment]
Supporting modeless `Dialog` does seem like a nice future to me. But yeah, that's def a bit of work. Let's take this as-is, and we can iterate :)

**Pull request merged**
