### PR TITLE
Vyankatesh 🍉

### PR DESCRIPTION
**Pull request by VyankateshRohokale**
Migration: Replace DeprecatedFlyString with FlyString #22447  
Replaced DeprecatedFlyString with FlyString

### CODE REVIEW

**Review by VyankateshRohokale — COMMENTED** [review]
It wont complete without Return 0 , until deprecatedFlyString is not replaced everywhere in my opinion

**Comment by logkos** [comment]
> It wont complete without Return 0 , until deprecatedFlyString is not replaced everywhere in my opinion

no you need to satisfy lint and follow PR/commit name format

**Comment by VyankateshRohokale** [comment]
can you please elaborate?? , this is my first Open Source Contribution

**Comment by skyrising** [comment]
Looks like this is just a partial find & replace of "DeprecatedFlyString" with "FlyString".
That's not the goal of #22447 and doesn't even compile, as you can see with the failing CI.

**Pull request closed without merging**
