### PR TITLE
VMMouse support

### LINKED ISSUE #1155: PS2Mouse: Implement vmmouse support
Vmmouse is an extension to the PS/2 mouse protocol originally created for VMware, also supported by QEMU. By implementing this QEMU would automatically capture/release the mouse cursor on hovering/leaving the VM window. This would also help solving the problem of some people trapping themselves in the VM.

Protocol: https://wiki.osdev.org/VMware_tools#Absolute_Mouse_Coordinates

There's a small catch: vmmouse reports absolute mouse coordinates, the [Kernel](https://github.com/SerenityOS/serenity/blob/4a36a5161833f28f045f30fe30c64f3100cce2e1/Kernel/MousePacket.h#L29) and [WindowServer](https://github.com/SerenityOS/serenity/blob/4a36a5161833f28f045f30fe30c64f3100cce2e1/Servers/WindowServer/WSScreen.cpp#L104) only handles relative ones at the moment. They would need to be taught to the concept of absolute positioning.

Might also help with #956 due to most of the mouse data going through the VMware magic backdoor, not the PS/2 port. (The real fix for that would be sprinkling QEMU's PS/2 host device with mutexes, but that's an another story.)

### PR DESCRIPTION
**Pull request by supercomputer7**
Closes #1155 
Thanks to @bugaevc for the help with the WindowServer stuff!

### CODE REVIEW

**Comment by xTibor** [comment]
Nice, works wonderfully!

However the bad news: vmmouse combined with the window snapping feature exposes an another QEMU bug, now in their GTK interface. When the cursor leaves the VM window QEMU doesn't set the virtual cursor position to the edge of the window like any sane implementation would. This could result in the mouse stopping way ahead of the edge (16+ pixels or more), not triggering window snapping.

Thankfully their SDL interface handles this correctly though.

**Comment by supercomputer7** [comment]
> Nice, works wonderfully!
> 
> However the bad news: vmmouse combined with the window snapping feature exposes an another QEMU bug, now in their GTK interface. When the cursor leaves the VM window QEMU doesn't set the virtual cursor position to the edge of the window like any sane implementation would. This could result in the mouse stopping way ahead of the edge (16+ pixels or more), not triggering window snapping.
> 
> Thankfully their SDL interface handles this correctly though.

I noticed it, but I can't do much about it probably... how do we enable the SDL interface by default?

**Comment by supercomputer7** [comment]
Just a side note, I noticed while working on it that when the WSEventLoop::drain_mouse() is being invoked, it seems that it receives "2 packets" on reading from /dev/psaux.
The reason for that - it doesn't receive anything after reading the whole mouse queue and the `MousePacket state` stays blank (with default values). This is not a major problem since the WSEveneLoop ignores this packet in the end of the method, and the real mouse packets (either relatives or not) are processes and are not ignored.
In the future, I'd like to solve this issue by changing the drain mechanism entirely, but for now it works fine.

**Comment by awesomekling** [comment]
Very cool :) Nice job guys!

**Pull request merged**
