### PR TITLE
LibC: Implement sigsuspend, pause

### PR DESCRIPTION
**Pull request by boricj**
Needed by mksh.

### CODE REVIEW

**Comment by boricj** [comment]
This doesn't quite work : with this PR, it appears that `mksh` is hogging the CPU and cannot be stopped or killed when it tries to exit. I need to figure out what's going on with that before this is mergeable.

**Comment by roytam1** [comment]
> it appears that `mksh` is hogging the CPU and cannot be stopped or killed when it tries to exit

which version of mksh you're using? current git/cvs HEAD version of mksh will use `poll` for `pause`. You may need to modify `Build.sh` to test `sigsuspend`.
ref: https://github.com/MirBSD/mksh/commit/de953e34e1359c7ac7dffd5f5abeb24888351247

so you have to comment out line 1151 and 1152 for testing `sigsuspend`.
https://github.com/MirBSD/mksh/blob/master/Build.sh#L1149

**Comment by boricj** [comment]
I'm using the version that's in pkgsrc 2021Q2.

I'm starting to think that the problem is not related to `sigsuspend`: I've rewritten its implementation using `pselect` under the hood and the issue still occurs. From what I could observe, upon exit or EOF `mksh` uses `siglongjmp` to break out of the interpreter loop, but something goes horribly wrong and it keeps going.

I don't really _need_ `mksh` to bootstrap pkgsrc because I could just use the existing `bash` port, but I'd rather have the full bootstrap work instead of special-casing even more SerenityOS inside `bootstrap`.

**Comment by roytam1** [comment]
> `mksh` uses `siglongjmp` to break out of the interpreter loop, but something goes horribly wrong and it keeps going.

you can tell mksh to use `setjmp` and `longjmp` instead of using `sigsetjmp`. this is also listed in git/cvs HEAD of mksh's Build.sh.
but of course fixing these APIs will help for example `oksh` to run better.

**Comment by boricj** [comment]
I haven't figured out yet what's going on with `mksh`, but I did find `pselect` as a suitable back-end for `sigsuspend`. This makes this PR rather trivial.

**Pull request merged**
