### PR TITLE
LibX86+UserspaceEmulator: Add MMX instruction prototypes

### PR DESCRIPTION
**Pull request by Hendiadyoin1**
This adds all Instruction wrappers for the mmx extension.

If this gets merged before #6593 I will implement these there, otherwise it will be in this one (I have to rebase either way)

### CODE REVIEW

**Comment by linusg** [comment]
Typo in PR title / commit message

**Comment by Hendiadyoin1** [comment]
Oh.. fixed that

**Comment by awesomekling** [comment]
There is still a typo in the commit message. (Emualtor)

**Comment by Hendiadyoin1** [comment]
I thought I fixed, that... should be fixed now...

**Comment by Hendiadyoin1** [comment]
@linusg, @awesomekling anything else?

**Pull request merged**
