### PR TITLE
AK: Don't put element count next to heap-allocated data in FixedArray

### PR DESCRIPTION
**Pull request by DanShaders**
This not only makes code easier to follow but also makes it faster.

PS: I haven't actually tried to find FixedArray's current users in the codebase but this makes my WIP async inflate 5% faster.

### CODE REVIEW

**Comment by LucasChollet** [comment]
Not that I'm in favor of one solution or the other, but that was made on purpose in this commit:
f03f70a8

**Comment by LucasChollet** [comment]
Do you know why it is faster? Is it from the branch removal in `size()` and `data()`?

**Comment by DanShaders** [comment]
Yes, because of that and because it does less indirection this way.

**Comment by DanShaders** [comment]
@awesomekling, where were these empty `FixedArray`s that you were shrinking?

**Comment by awesomekling** [comment]
> @awesomekling, where are these empty `FixedArray`s that you were shrinking?

Looking at the current uses of `FixedArray`, I'm gonna say "somewhere in the past". :sweat_smile: 
I don't see anything that would justify making `FixedArray` more complicated.

**Pull request merged**
