### PR TITLE
Meta: Automatically label PRs with merge conflicts

### PR DESCRIPTION
**Pull request by filiphsps**
This is just a simple nicety to slightly reduce the PRs-related burden on maintainers :^)

### CODE REVIEW

**Comment by ADKaster** [comment]
Does Luke's big ol labeler PR have a case for this?

**Comment by filiphsps** [comment]
> Does Luke's big ol labeler PR have a case for this?
Are you referring to https://github.com/probot/stale?

If so, no there's no prebuilt probot app for that, of course we can always build one ourselves if that'd be preferred instead of using a third-party GitHub action.

**Comment by davidot** [comment]
> Does Luke's big ol labeler PR have a case for this?

Not yet, and in fact it would need to not remove that conflict label for this to work properly

**Comment by filiphsps** [comment]
> Does Luke's big ol labeler PR have a case for this?

ah you were referring to https://github.com/SerenityOS/serenity/pull/15597 which I completely missed. That's imo the better route to go.

**Pull request closed without merging**
