### PR TITLE
FAQ: remove question about only supporting 32 bit

### PR DESCRIPTION
**Pull request by inalone**
As the system now supports x86_64, this question about the system being 32 bit is no longer relevant.

### CODE REVIEW

**Comment by awesomekling** [comment]
This question is still asked several times every week, so I think it would be better to rewrite the answer to say that there is now a 64-bit port. :)

**Comment by inalone** [comment]
Thank you Andreas, I have now added that in :)

**Comment by awesomekling** [comment]
Please squash fixups into the original commit (see [contributing guidelines](https://github.com/SerenityOS/serenity/blob/ca2c81251a7d036f586f3d0a32bc35e2b9f93144/CONTRIBUTING.md) :))

**Comment by inalone** [comment]
Apologies Andreas, still fairly new to git, will figure out how to do that thank you :)

**Comment by gunnarbeutner** [comment]
Please have a look at the CI build steps. The one that checks commit messages currently fails.

**Comment by awesomekling** [comment]
Closing since this was abandoned, fixed it myself in afcd053b68e529cfb25c19ffe2726f6337e01aa8

**Pull request closed without merging**
