### PR TITLE
Base: Add More Emojis

### PR DESCRIPTION
**Pull request by electrikmilk**
Adds Cat face emojis U+1F63B, U+1F63C, U+1F63D, U+1F63E, U+1F639,
U+1F640

U+1F63B U+1F63C U+1F63D U+1F63E U+1F639 U+1F640

Adds Party Popper emoji U+1F389

U+1F389

Adds Rocket Emoji U+1F680

U+1F680

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
Please run `optipng -strip all` over these to get them down from 9 kB to a couple hundred bytes maximum :)

**Review by electrikmilk — COMMENTED** [review]
Used `optipng` as suggested.

**Review by Xexxa — APPROVED** [review]
I love cats and I approve of this PR!

🐾 🐈 🐱

**Comment by Xexxa** [comment]
This has never been required but a lot of people add the added emojis to https://github.com/SerenityOS/serenity/tree/master/Base/home/anon/Documents/emoji.txt. I don't know if the users use the emoji-picker or emoji.txt to find emojis, just a suggestion ;-)

**Comment by electrikmilk** [comment]
Added Rocket emoji as well, as Party Popper is mostly made for Github in the browser. I will add these emojis to the `txt` file as @Xexxa recommended.

**Comment by electrikmilk** [comment]
Updated `emojis.txt`.

**Comment by electrikmilk** [comment]
> Not putting the emojis in the right space when everything else is in order in emoji.txt (sorted after U+xxxxx in a weird numeric way it looks like) causes some twitches for me, it looks nicer if the order is followed. I'm not sure if this is a weird personal autistic opinion or if it makes sense to change...
> 
> 
> 
> Also, hex is missing for "CAT FACE WITH WRY SMILE".

Adjusted to be in correct order of the hex codes, added missing hex.

**Review by Xexxa — APPROVED** [review]
LGTM

**Pull request merged**
