### PR TITLE
Ports: Add v2 release of libfirefly

### PR DESCRIPTION
**Pull request by tbhaxor**
I have built firefly package for vector calculations in C++ and I am currently working on it to make more user friendly and add helper functions to do complex tasks like performing Gram- Schmidt Orthogonalization.

### CODE REVIEW

**Comment by BertalanD** [comment]
This seems to depend on #20369, correct?

**Comment by BertalanD** [comment]
Or not? Anyway, please squash the commits into one -- each individual commit in a PR should pass CI, and not add code that will be changed in the next one.

Why are the shellcheck comments necessary? We don't use them in other port scripts.

**Comment by timschumi** [comment]
Is there anything that uses this?

**Comment by tbhaxor** [comment]
> This seems to depend on #20369, correct?

Currently, no

> Why are the shellcheck comments necessary? We don't use them in other port scripts.

It was complaining in my IDE, I prefer to use shellcheck to prevent writing dangerous code unintentionally

> Is there anything that uses this?

No, but I plan to build machine learning libraries that will use it

**Comment by tbhaxor** [comment]
> Anyway, please squash the commits into one -- each individual commit in a PR should pass CI, and not add code that will be changed in the next one.

Done, thanks for this. I learnt new thing today 😄

**Comment by tbhaxor** [comment]
It's too early to port this library. I've found a lot of issues with my code and need to fix them.

**Pull request closed without merging**
