### PR TITLE
TTY+Kernel: Added TIOCSTI ioctl placeholder.

### PR DESCRIPTION
**Pull request by Baitinq**
Added the TIOCSTI ioctl, which inserts a byte in the TTY's input queue.
This can be used to simulate input (Could have some security
implications). Initially added it because cmatrix uses it and I am
planning to port it.

### CODE REVIEW

**Comment by awesomekling** [comment]
We should not support `TIOCSTI` due to the huge security problems. However, it would be fine to add the `#define` and make it fail with `EIO` for compatibility.

**Comment by Baitinq** [comment]
Okay, that seems like the best thing to do. Will update my commit :)

**Comment by Baitinq** [comment]
@awesomekling what about a promise for this ioctl? would that even make sense?

**Comment by awesomekling** [comment]
> @awesomekling what about a promise for this ioctl? would that even make sense?

No, we should simply not implement it as it's inherently insecure :)

**Pull request merged**
