### PR TITLE
WindowServer: Process dnd mouse events first

### LINKED ISSUE #3151: Drag&Drop crashes application
Drag&Drop is causing FileManager and Terminal to crash as soon as you start dragging:

> FileManager(24): Initiate drag!
> FileManager(24): Initiate drag!
> USERSPACE(24) ASSERTION FAILED: !s_current_drag_operation
> ../Libraries/LibGUI/DragOperation.cpp:49
> [FileManager(24:24)]: Terminating FileManager(24) due to signal 6
> [FinalizerTask(4:4)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) +181
> 0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) +183
> 0xdeadc0de  Kernel::Scheduler::pick_next() +1681
> 0xdeadc0de  Kernel::Processor::check_invoke_scheduler() +125
> 0xdeadc0de  Kernel::Thread::die_if_needed() +157
> 0xdeadc0de  syscall_handler +1414
> 0xdeadc0de  syscall_asm_entry +49
> 0x080d5e3f  raise +22
> 0x080480bd  abort +13
> 0x080d21d6  tolower +0
> 0x0806c60e  GUI::DragOperation::exec() +50
> 0x0805abcf  GUI::AbstractView::mousemove_event(GUI::MouseEvent&) +1181
> 0x080d0286  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
> 0x0809499a  GUI::Window::handle_mouse_event(GUI::MouseEvent&) +236
> 0x080d0286  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
> 0x080c96fc  Core::EventLoop::pump(Core::EventLoop::WaitMode) +308
> 0x080c987b  Core::EventLoop::exec() +43
> 0x0806c7a3  GUI::DragOperation::exec() +455
> 0x0805abcf  GUI::AbstractView::mousemove_event(GUI::MouseEvent&) +1181
> 0x080d0286  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
> 0x0809499a  GUI::Window::handle_mouse_event(GUI::MouseEvent&) +236
> 0x080d0286  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
> 0x080c96fc  Core::EventLoop::pump(Core::EventLoop::WaitMode) +308
> 0x080c987b  Core::EventLoop::exec() +43
> 0x08051f1d  run_in_windowed_mode(AK::RefPtr<Core::ConfigFile>, AK::String) +10060
> 0x08048d5b  main +2384
> 0x0804992e  _start +94

It seems like somehow two `DragOperation` instances get created.

### PR DESCRIPTION
**Pull request by tomuta**
Fixes duplicate GUI::DragOperation instances being created.

Fixes #3151

### CODE REVIEW

**Comment by tomuta** [comment]
@alimpfard I'll happily change the author to you since I'm basically stealing your fix here ;-)

**Comment by alimpfard** [comment]
Nah, please go ahead with yourself as the author.

**Comment by linusg** [comment]
I think this is worth a short comment in the code as it's not obvious why one of these seemingly related function calls is done beforehand (I'm just afraid future me will break it again lol)

**Comment by tomuta** [comment]
@linusg is the comment I added descriptive enough?

**Comment by linusg** [comment]
@tomuta yup, looks good, thanks! :)

**Pull request merged**
