### PR TITLE
Port: Update nano to version 6.0

### PR DESCRIPTION
**Pull request by BodgeMaster**
The new version seems to just work so all I had to change was the version number.

This is my first time contributing so please tell me if I did something wrong.
I just wanted to get started while trying to learn at the same time and this was the first thing that came to my mind.

### CODE REVIEW

**Comment by linusg** [comment]
https://github.com/SerenityOS/serenity/pull/12292#issuecomment-1030621248 also applies here.

**Comment by BodgeMaster** [comment]
Okay, changed the name.

**Comment by BodgeMaster** [comment]
So apparently I get confused with more than two branches. Redid the thing with the changed commit message.

**Review by linusg — CHANGES_REQUESTED** [review]
Please remove the first sentence from the commit message, that's not relevant to anyone else :)

**Comment by alimpfard** [comment]
> Port: Update nano to version 6.0

The category is "Ports" (same as the directory), not "Port"; please change that.

**Comment by BodgeMaster** [comment]
Done.

**Pull request merged**
