### PR TITLE
LIBGUI: Add GML properties to calendar widget

### PR DESCRIPTION
**Pull request by glenfordwilliams**
This pr introduces additional GML properties to the calendar widget.

- grid -bool
- date - string/array
- mode -  enum

image

```
@GUI::Widget{

    @GUI::Widget{
        layout: @GUI::HorizontalBoxLayout{}
        @GUI::Widget {
            //October 10 2020
            @GUI::Calendar{
                height : 200
                width: 300
                date: [10,10,2020]
            }
        }
      @GUI::Widget {
                //October 10 2020
                @GUI::Calendar{
                   height : 200
                   width: 300
                   date: "2020-10-10"
                }
            }
    }
    @GUI::Widget{
        layout: @GUI::HorizontalBoxLayout{}

        @GUI::Widget {
            //October 1 2020
            @GUI::Calendar{
               height : 200
               width: 300
               grid: false
            }
        }
        @GUI::Widget {
            //October 1 2020
            @GUI::Calendar{
               height : 200
               width: 300
               mode: "Month"
            }
        }
    }
}
```

edited  to show updated purpose

### CODE REVIEW

**Comment by alimpfard** [comment]
> also introduces a @GUI::GMLObject class for setting key value pairs to class properties

This...sounds a bit counterproductive? allowing arbitrary stuff (and expecting arbitrary stuff) is rather bad for a declarative language imo
Perhaps consider a `GUI::Calendar::Date`, or a more generic `GML::Date` object?

**Comment by glenfordwilliams** [comment]
> > also introduces a @GUI::GMLObject class for setting key value pairs to class properties
> 
> This...sounds a bit counterproductive? allowing arbitrary stuff (and expecting arbitrary stuff) is rather bad for a declarative language imo
> Perhaps consider a `GUI::Calendar::Date`, or a more generic `GML::Date` object?

Is it that bad an idea?

**Comment by alimpfard** [comment]
Bad? Not really, but imagine if everything accepted arbitrary objects and read out random fields from them
bye bye reliable autocomplete and static analysis

**Comment by glenfordwilliams** [comment]
Oh right, didn't really think along those lines. Will have to rethink my approach then

**Comment by glenfordwilliams** [comment]
updated to use a `@GUI::GMLDate` with properly defined properties. Api still feels clumsy but for now it should work until there is a better abstraction for components outside of the GUI namespace

**Comment by awesomekling** [comment]
I'm not sure what's going on here, but GML is intended for UI declarations, not arbitrary object instantiation :)

**Comment by awesomekling** [comment]
If you want to assign an initial date to a `GUI::Calendar` widget from GML, make it accept a date string. There's no need for special objects.

Also please don't add widget subclasses that are not actually widgets. :)

**Comment by glenfordwilliams** [comment]
@awesomekling  updated to use  just a optional string/array for setting the date

**Comment by awesomekling** [comment]
I don't really understand the purpose of this PR. This seems like a large amount of complexity with very little benefit. You are not even using the property for anything in the end?

**Comment by awesomekling** [comment]
Also, please observe the [contribution guidelines](https://github.com/SerenityOS/serenity/blob/08190dd0ce5f23de6dffcd2c7521314202b05514/CONTRIBUTING.md) and squash fixups into earlier commits instead of stacking them.

**Comment by glenfordwilliams** [comment]
@awesomekling  my apologies, i updated my top comment to make things clearer. I took into account your previous comments and updated my code

**Comment by awesomekling** [comment]
Again, this seems like a large amount of complexity with very little benefit.

There's no code change here that makes use of the new property. What is this actually needed for?

Also, supporting both string and array properties seems excessive.

**Comment by glenfordwilliams** [comment]
> Again, this seems like a large amount of complexity with very little benefit.
> 
> There's no code change here that makes use of the new property. What is this actually needed for?
> 

Which of the properties are we talking about here?

> Also, supporting both string and array properties seems excessive.
personally   thought it would be a useful thing to to, but since you are in disagreement i can remove the array option

**Comment by linusg** [comment]
@glenfordwilliams this PR has various merge conflicts, please rebase :)

> > There's no code change here that makes use of the new property. What is this actually needed for?
>
> Which of the properties are we talking about here?

The `grid` and `mode` properties on `GUI::Calendar`.

**Comment by awesomekling** [comment]
Closing this since it's basically adding dead code and increasing complexity for no reason.

**Pull request closed without merging**
