### PR TITLE
Fix includes so that Super Mario compiles.

### PR DESCRIPTION
**Pull request by Coderdreams**
Fixed includes so that Super Mario compiles and installs.

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
That shouldn’t be necessary. If it fails due to that we should fix the include search path instead so that it picks up ˋ/usr/local/include´ from the install dir instead.

**Comment by gunnarbeutner** [comment]
I just tried building Super Mario in a Docker container that doesn't have anything other than the base system files installed. Does installing `pkg-config` on the host fix the build for you?

**Comment by pbaena-optimous** [comment]
I have pkg-config on the host, not even installing the SDL 1 packages I was able to build, these are my SDL packages installed:

ii  libsdl-image1.2:amd64                                       1.2.12-12                                           amd64        Image loading library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-net1.2:amd64                                         1.2.8-6                                             amd64        Network library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-sound1.2:amd64                                       1.0.3-9                                             amd64        Sound library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl1.2-dev                                               1.2.15+dfsg2-5                                      amd64        Simple DirectMedia Layer development files
ii  libsdl1.2debian:amd64                                       1.2.15+dfsg2-5                                      amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:amd64                                         2.0.10+dfsg1-3                                      amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:i386                                          2.0.10+dfsg1-3                                      i386         Simple DirectMedia Layer
ii  libsdl2-dev:amd64                                           2.0.10+dfsg1-3                                      amd64        Simple DirectMedia Layer development files
ii  libsdl2-image-2.0-0:amd64                                   2.0.5+dfsg1-2                                       amd64        Image loading library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-image-dev:amd64                                     2.0.5+dfsg1-2                                       amd64        Image loading library for Simple DirectMedia Layer 2, development files
ii  libsdl2-mixer-2.0-0:amd64                                   2.0.4+dfsg1-2build1                                 amd64        Mixer library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-mixer-dev:amd64                                     2.0.4+dfsg1-2build1                                 amd64        Mixer library for Simple DirectMedia Layer 2, development files

**Comment by gunnarbeutner** [comment]
Can you show us the complete build output for the port?

**Comment by pbaena-optimous** [comment]
Would this be enough?:

Installing dependencies of Super-Mario!
Fetching Super-Mario!
Downloading URL: https://github.com/Bennyhwanggggg/Super-Mario-Clone-Cpp/archive/refs/heads/master.zip
master.zip already exists
Expecting sha256sum: fcacc15d3b5afccb3227f982d3e05f2cfeb198f0fffd008fdcda005cb7f87f91
sha256sum(master.zip) = 'fcacc15d3b5afccb3227f982d3e05f2cfeb198f0fffd008fdcda005cb7f87f91'
+ bsdtar xf master.zip (nocd)
+ touch .master.zip_extracted
Patching Super-Mario!
+ patch -p1
patching file src/Core.cpp
+ touch .disable_graphic_acceleration.patch_applied
+ patch -p1
patching file CMakeLists.txt
+ touch .fix_cmakelists.patch_applied
+ patch -p1
patching file src/FireBall.cpp
patching file src/Map.h
+ touch .fix_fireball_header.patch_applied
Configuring Super-Mario!
+ cmake -DCMAKE_TOOLCHAIN_FILE=/media/extras/serenity/Toolchain/CMake/CMakeToolchain.txt
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Check for working C compiler: /media/extras/serenity/Toolchain/Local/i686/bin/i686-pc-serenity-gcc
-- Check for working C compiler: /media/extras/serenity/Toolchain/Local/i686/bin/i686-pc-serenity-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /media/extras/serenity/Toolchain/Local/i686/bin/i686-pc-serenity-g++
-- Check for working CXX compiler: /media/extras/serenity/Toolchain/Local/i686/bin/i686-pc-serenity-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'sdl2'
-- Checking for one of the modules 'SDL2_image>=2.0.0'
-- Checking for one of the modules 'SDL2_mixer>=2.0.0'
-- Configuring done
-- Generating done
-- Build files have been written to: /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master
Building Super-Mario!
+ make -j8
Scanning dependencies of target uMario
[ 10%] Building CXX object CMakeFiles/uMario.dir/src/Beetle.cpp.o
[ 10%] Building CXX object CMakeFiles/uMario.dir/src/Block.cpp.o
[ 10%] Building CXX object CMakeFiles/uMario.dir/src/AboutMenu.cpp.o
[ 10%] Building CXX object CMakeFiles/uMario.dir/src/BlockDebris.cpp.o
[ 10%] Building CXX object CMakeFiles/uMario.dir/src/Bowser.cpp.o
[ 11%] Building CXX object CMakeFiles/uMario.dir/src/BulletBill.cpp.o
[ 13%] Building CXX object CMakeFiles/uMario.dir/src/BulletBillSpawner.cpp.o
[ 10%] Building CXX object CMakeFiles/uMario.dir/src/Bubble.cpp.o
In file included from /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/Minion.h:6,
                 from /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/BulletBill.h:6,
                 from /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/BulletBill.cpp:1:
/media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/header.h:6:10: fatal error: SDL.h: No such file or directory
    6 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
In file included from /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/Bubble.h:6,
                 from /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/Bubble.cpp:1:
/media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/header.h:6:10: fatal error: SDL.h: No such file or directory
    6 | #include <SDL.h>
      |          ^~~~~~~
In file included from /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/Minion.h:6,
                 from /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/BulletBillSpawner.h:6,
                 from /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/BulletBillSpawner.cpp:1:
/media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/header.h:6:10: fatal error: SDL.h: No such file or directory
    6 | #include <SDL.h>
      |          ^~~~~~~
In file included from /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/BlockDebris.h:6,
                 from /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/BlockDebris.cpp:1:
/media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/header.h:6:10: fatal error: SDL.h: No such file or directory
    6 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
In file included from /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/Minion.h:6,
                 from /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/Bowser.h:6,
                 from /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/Bowser.cpp:1:
...

**Comment by gunnarbeutner** [comment]
That looks OK, actually. Try to figure out which include and library path it's trying to use for SDL2.

**Comment by Coderdreams** [comment]
/media/extras/serenity/Toolchain/Local/i686/bin/i686-pc-serenity-g++ --sysroot=/media/extras/serenity/Build/i686/Root   -I/media/extras/serenity/Build/i686/Root/media/extras/serenity/Build/i686/Root/usr/local/include/SDL2 -I/media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src  -Wall -Wextra -pedantic -std=c++11   -o CMakeFiles/uMario.dir/src/AboutMenu.cpp.o -c /media/extras/serenity/Ports/Super-Mario/Super-Mario-Clone-Cpp-master/src/AboutMenu.cpp

That's the problem thank you. Weird that I ended up with a repeated full path on the include dir, that's the issue. I built the toolchain a couple of times, I should delete everything and start from scratch and see if that fixes it.

**Comment by Coderdreams** [comment]
Hmm, I deleted the Build directory and started from scratch, but the problem persists. The include directory has the full i686 path twice. Is there any other directory that I should delete?

**Comment by pbaena-optimous** [comment]
I built the toolchain totally from scratch on a different directory and it worked. You can discard this PR.

Thank you.

**Pull request closed without merging**
