### PR TITLE
Implementation of the cut command.

### PR DESCRIPTION
**Pull request by marprok**
I implemented a very basic cut command. It supports only the -b option on a single file but I added the feature of specifying ranges of bytes to print.

### CODE REVIEW

**Comment by marprok** [comment]
I got rid of my custom data structures and started using the AK/Vector data structure as well as the already implemented quick_sort function.

**Comment by awesomekling** [comment]
Hmm, this code is still very hard to read.

Please see: https://github.com/SerenityOS/serenity/blob/master/Contributing.md
In particular,
**Choose expressive variable, function and class names. Make it as obvious as possible what the code is doing.**

Variable names like `n`, `nr`, `len`, `c`, `v', etc. don't make it obvious what's going on. Please prefer extremely obvious names that tell you exactly what they are.
Also, names like `byteCount` should be `byte_count` to be consistent with the rest of the project.

Also since this isn't C89, you don't have to declare all variables at the start of the function. Instead, declare them as close as possible to when they are first used. This makes it much easier to understand their purpose.

Some other notes:

- Please squash these commits into a single commit for review instead of adding updates on top of updates. Right now I can't review this PR without going to your repository and looking at `cut.cpp` in the PR branch :)
- `char*` pointers that are never written to should be `const char*`.
- All error messages should be printed to `stderr`, not `stdout`.
- When using a vector, prefer `append()` over `prepend()` if order does not matter. `append` is trivial while `prepend` has to shift the contents of the vector one step to the "right" to make room in the 0th position.
- If you want a data structure where you can add something repeatedly without getting duplicates, a `HashTable<T>` is more suitable. Note that hash tables don't have stable sort order though.
- `atoi()` has no way to report an error to the caller. For this reason it's better to use `strtol()` so we can report an error to the user if given an invalid number string.
- Since `print_usage()` has the side effect of also exiting the program, let's include that in the name. Something like `print_usage_and_exit()` would make it more obvious what's happening.

**Comment by marprok** [comment]
Thanks for the feedback, it is my first commit here and it is important for me to learn as much as possible :)
* The char* are used because I modify the string.
*  The strings that I pass on atoi are checked to contain only numbers.
* In other Userland programs such as kill.cpp, you use stdout to print an error.
* I use the Vector data structure because I need to iterate it's contents for each line, so array random access is more efficient plus I need to sort it.
* I will squash the commits into a single one. 
* I will rename the variables.

**Comment by awesomekling** [comment]
> Thanks for the feedback, it is my first commit here and it is important for me to learn as much as possible :)

Of course :)

> * The char* are used because I modify the string.

The pointer `file` in `main()` is never modified.

> * The strings that I pass on atoi are checked to contain only numbers.

Consider using `String::split()` and `String::to_int()` to parse the "list" specifications.

> * In other Userland programs such as kill.cpp, you use stdout to print an error.

That's a mistake and we should fix that (separately from this) :)

> * I use the Vector data structure because I need to iterate it's contents for each line, so array random access is more efficient plus I need to sort it.

Right, so it might make sense to use a `HashTable<int>` while you're parsing the options, and then transfer the contents to a `Vector<int>` and sort that vector once it's finished.
It's not terribly important here since we're dealing with small quantities, more of a general thing to keep in mind.

> * I will squash the commits into a single one.
> * I will rename the variables.

Great!

**Comment by marprok** [comment]
I fixed most of the things you have mentioned. The String::split and the String::to_int methods require me to use AKString which I think is an overkill since I just parse a small list separated by commas.

**Comment by marprok** [comment]
I ported the program so that it uses the String class. I believe the code is much cleaner and easy to read now.

**Comment by awesomekling** [comment]
Okay, this is starting to look a lot better! Good work so far :)

Let's fix up some quality issues:
- The commits are still not squashed.
- `Index_t` is a non-idiomatic name, let's call it `Index` or `ListIndex` instead.
- `RangedInex` -> `RangedIndex`
- `print_ussage_and_exit` -> `print_usage_and_exit`
- `FILE* fd` -> `FILE* fp`, as `fd` by convention means "file descriptor" and `fp` by convention means "FILE pointer"
- In `main()`, please don't declare all local variables at the top of the function. Instead, declare them when they are first used.
- I don't think you need the `bool ranged` variable, can't you always print a newline after processing each line?

**Comment by marprok** [comment]
Fixed all your requests. The whole commit squashing thing is new to me so I don't know if I am doing it right. I hope now that it is closer to what you want.

**Comment by awesomekling** [comment]
It's still not squashed. Squashing means that you combine all of your existing commits into a single commit.
You do that by using `git rebase`, here's a nice blog that explains how to do it:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Pull request closed without merging**
