### PR TITLE
Base: Add new fix-width Sobreity font for consideration

### PR DESCRIPTION
**Pull request by djwisdom**
Snapshot of Sobriety font being used in Text Editor and in Terminal

image

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
How many more fonts do you plan to add? Shifting focus towards improving coverage of the existing ones would be preferable.

**Comment by djwisdom** [comment]
I'm already done with this last one actually. :^) Pivoting focus back again to system fonts.

**Comment by Xexxa** [comment]
> How many more fonts do you plan to add? Shifting focus towards improving coverage of the existing ones would be preferable.

I find both this one and #13701 to be distinct in style and consistent (also all tech seems good to). So these are great fonts!

At the same time get where @linusg is coming from, are these fonts unique and different enough to merit inclusion? I'm happy I don't have to make that judgement! That's the primary reason I tried to collect descriptions from all the font authors on <https://fonts.serenityos.net/font-family>, to get a feeling of the thinking behind and intended usage of a font.

Some day we have to draw a line of what should be on a default installation and what should be added by the user, I look forward to the day when a user can install a font from inside SerenityOS and we have "Get more fonts"-links in our font dialogs... :caret:

I guess a checklist for font inclusion going forward could look something like:

Does the submitted font:
* differ enough from the fonts already in the system in style?
* something a user would use/expect in the system (does another OS has a similar font installed by default)

Special circumstances not on the checklist above:
* has a special purpose other fonts can't fulfill (I talk about you different scripts with very non-latin proportions)
* has a unique coverage/quality better what we currently have.

Just thinking out loud here.

**Comment by djwisdom** [comment]
I didn't think font submission can be this challenging. For me it doesn't matter. Approved or rejected is the same to me. I chose to share and the mere fact my fonts were 'seen' was enough justification for me. Closing PR to prove my point.

**Pull request closed without merging**
