### PR TITLE
Ports: Update radare2 from 5.4.0 to the latest 5.7.0

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by bgianfo** [comment]
Please squash your fix up commit

**Comment by EWouters** [comment]
This was included in #14179. Now there are merge conflicts.

**Comment by linusg** [comment]
@EWouters a PR with a single commit getting merged sooner than a PR with 33 commits should not be a surprise to anyone :^)

**Comment by EWouters** [comment]
Sure :^)
I have some fixes in my branch as well so I just merged them.

**Pull request merged**
